### ISSUE TITLE
log of requests and what happens

### ISSUE THREAD

**Issue by slavab89** [panva/node-oidc-provider#100]
I am trying to add logging to my provider server, meaning that i would like to know more details about the request that came through.

I know about the events that are being sent when different things happen but they do not always provide me with enough information.
For instance, i would like to write to my log / console where the request came from, what headers did he send, did he send a body, a query etc... pretty basic auditing of requests that come through.

When attaching to almost all events, i believe, i dont have that information - that information is on the request/response which i dont have on the event.

Is it possible to either send the request/response objects along with the event, or think of some other way to allow auditing?
Maybe allow to inject a middleware at the end of the request that will be used for logging (not ideal cause it will be open for anyone doing anything there).

**Comment by panva** [comment]
> that information is on the request/response which i dont have on the event.
ctx is request/response > https://github.com/panva/node-oidc-provider/blob/master/docs/events.md  
ctx.request, ctx.response are koa wrappers, ctx.req, ctx.res are the pure node ones.

> Maybe allow to inject a middleware at the end of the request that will be used for logging (not ideal cause it will be open for anyone doing anything there).
This is possible, see the [example](https://github.com/panva/node-oidc-provider/blob/4da409a7f8a130d827233afd29d1e863f9ea0c42/example/index.js#L52-L64) where a prepend a middleware.

Before you yield it's start of a request, after it's the end.

**Comment by slavab89** [comment]
That is correct, i can inject a middleware in the beginning or the end.
However, not all requests get to the final middleware.
If i inject a middleware for logging at the end - because i want to log out the request data, alongside the client that makes the request, the grant uuid etc - then during the [/auth/:uuid](https://github.com/panva/node-oidc-provider/blob/master/lib/actions/authorization/respond.js#L65)  route, it will end with a redirectand wont get to the final middleware that i've injected.

On the other hand, on the token issue events, i only get the token, i dont get the context of the request.

I dont think i can inject a middleware (using unshift) in the beginning because the oidc context is not yet created.

I'm using express so i think it makes things even more harder =[ (Cant really use morgan (unless i implement something similar on my own) because morgan takes all the data out of the req, res. Yet the oidc context is saved on koa context, outside of req, res objects.

**Comment by panva** [comment]
Just unshift a middleware at the beginning of the stack and immediately yield in it. The middleware will resume processing when oidc-provider is done with the request and you will have all the request data available after that yield.

**Comment by panva** [comment]
in this middleware you have this.req and this.res for your morgan.

**Comment by panva** [comment]
You can't make this any simpler than that.

```
    provider.app.middleware.unshift(function* logger(next) {
        console.log('request started', this);
        yield next;
        console.log('request ended', this, this.oidc, this.href, this.params, this.oidc.params);
    });
```

**Comment by panva** [comment]
resources: http://koajs.com/#cascading
Note the koa website already uses async functions (koa2), v1 of oidc-provider is still koa1 (using generators). A switch to koa2 internal will be a breaking change of the upcoming v2.

**Comment by slavab89** [comment]
😱 Dont know how i missed the 
```
provider.app.middleware.unshift(function* logger(next) {
        console.log('request started', this);
        yield next;
        console.log('request ended', this, this.oidc, this.href, this.params, this.oidc.params);
    });
```
ability that you wrote... First go to next (to handle the request) then log what you want.

Sorry to bother some more but i'm still missing a little something.
In `/token` route, when creating and saving AccessToken, an event is emitted with the token information (`token.issued`) however i cant log it as part of the whole request log cause its not saved anywhere else - which is ok in thought, but still.

Was thinking of just fetching it from the DB once again but dont see any information that could help me with that on oidc context (only a hacky way of finding the last access token of the client/account)


Maybe i'm looking at this whole thing a bit wrong?

**Comment by slavab89** [comment]
Regarding Koa, i did notice that you're using V1, but i dont think that the switch to V2 would change something in the logic that i'm trying accomplish.
I assume it would also require the minimal version of node to be 7+.

**Comment by panva** [comment]
`token.issued` can not have accesss to the request context, it's emitted by a model, not a controller.

> Regarding Koa, i did notice that you're using V1, but i dont think that the switch to V2 would change something in the logic that i'm trying accomplish.
I assume it would also require the minimal version of node to be 7+.

Yes, >=7.6.0 will be required. And you will have to change the function and its signature from, a writeup on the steps to upgrade will be available.
```
function * (next) {
   ctx = this;
   yield next;
}
```
to
``` 
async function (ctx, next) {
   await next()
}
```

**Comment by slavab89** [comment]
Yeah, assumed its because its in the model.
hmmm... ok so for now i guess i'll write several log entries. 1 for the request details and 1 for the issued token details (basically i need the account_id, client_id and jti (cause its the identification of the token in the DB)

**Comment by slavab89** [comment]
Another option that i might think is to use some kind of a temporary cache for the requests.
When a request happens, save it in the mapping, and when the event happens, update it... but i dont think i have some id to match in the mapping + its super ugly.

I've seen some other issues that asked about providing the model with the request, or at least the wrapper maybe?

Is there no option to do that?
When a request to `/token` arrives, log out the created token data alongside the request details. (an example of a route)

**Comment by panva** [comment]
>+ its super ugly.

You're right. Bad idea.

> When a request to /token arrives, log out the created token data alongside the request details. (an example of a route)

You have access to the response body and status as well as the parameters. This gives you: value of the issued token (also the id used to store it!), client_id and indirectly also the subject (from the issued id token).

**Comment by panva** [comment]
Coming back to your original problem.

> I am trying to add logging to my provider server, meaning that i would like to know more details about the request that came through.

Is this not achieved already having a way of prepend/append logs in the request's lifecycle?

**Comment by slavab89** [comment]
It is achieved that way by prepending/appending a middleware to handle logging. But the "interesting" details are not accessible because they are in the model (token details)

I think i'll go with the path that you've suggested:
1. Prepending a Koa middleware in order to save the oidc context
2. Prepending a middleware that will "monkey patch" the response object and parse the send body. Once parsed, i'll have the token details that were sent to the user as well the request details themselves (hopefully)
