### ISSUE TITLE
Doc: Allowing HTTP and/or localhost for implicit response type web clients

### ISSUE THREAD

**Issue by apgapg** [panva/node-oidc-provider#1006]
https://github.com/panva/node-oidc-provider/blob/main/recipes/implicit_http_localhost.md

The above docs seem outdated. I am getting error at Schema not found.
`Property 'Schema' does not exist on type 'typeof Client'.ts(2339)`

**Comment by panva** [comment]
It is not outdated. Just not type defined which is fine for me for a workaround.

**Comment by apgapg** [comment]
But IDE reports error and the project doesnt run. Am i missing something as mentioned in docs?
