### ISSUE TITLE
Broken integration with openid-client revocation endpoint

### ISSUE THREAD

**Issue by slavab89** [panva/node-oidc-provider#101]
Just updated to the latest version (1.15.8)
With the following commit [35c5ba4](https://github.com/panva/node-oidc-provider/commit/35c5ba46c0b377b37a7b4c21333e9693513884b9#diff-10051a54505804eb0058f7ed763ceda9R39) it seems to break the integration with openid-client.
Specifically with the revocation endpoint. When using `revoke` function, it fails to parse the response body [revoke function](https://github.com/panva/node-openid-client/blob/master/lib/client.js#L659).

The contentType returned from the OP seems to be `text/plain`. Moreover, for some odd reason, the `response.body` that openid-client receives at that line is `OK`, not even an empty response (Not sure why and how).
This doesnt happen with version 1.15.7.

**Comment by panva** [comment]
Cool find. As a matter of fact, both libs are at fault.

- provider should respond with empty body (koa pushes "OK" in by default thanks to the response code)
- client should ignore the body so long as it gets 200 OK.

Will fix.

**Comment by panva** [comment]
Fixed in 18cee7a (1.15.9)
