### ISSUE TITLE
id token with utf-8 characters

### ISSUE THREAD

**Issue by jakubzloczewski** [panva/node-oidc-provider#102]
I want to send utf-8 characters in id token (jwt) but it isn't working with current implementation - some characters are not send properly and it causes problem that id token payload is unparsable using JSON.parse.

I've tried with modified lib/helpers/jwt.js:58 where I added 'utf8' as second parameter of update method of JWS.Signer (node-jose)

```
return jose.JWS.createSign(
      { fields, format },
      { key, reference: key.kty !== 'oct' }).update(j(payload), 'utf8').final();
```

And it works.

Do you know if jwt or open connect id standards say something about encoding of characters in id token? If not maybe it would be good to go with utf8 as default encoding or give ability to change it to desired encoding by providers settings?

Thanks for any help!

**Comment by panva** [comment]
Hey @jakubzloczewski thank you for reaching out. Could you provide concrete claim examples you wish to return? I will take a look.

**Comment by jakubzloczewski** [comment]
I have tried with some special characters in the name claim:
```
{
  "email": "xxx@xxx.com",
  "name": "ąś∂źć√",
  "nickname": "jakub"
}
```

**Comment by panva** [comment]
Got it reproduced, will fix promptly!

**Comment by jakubzloczewski** [comment]
Thank you, as always you were superfast
