### ISSUE TITLE
Possible to allow rotated refresh token reuse?

### ISSUE THREAD

**Issue by jamesacres** [panva/node-oidc-provider#1022]
Hi 👋 , quick question, is there a way to keep old refresh tokens valid when they are re-used?

When a rotated refresh token is used, it is marked as consumed, and if it is reused an error is thrown `throw new InvalidGrant('refresh token already used');`

I see we have the ability not to destroy by using revokeGrantPolicy which in the readme does mention "Rotated Refresh Token re-use" however, I believe re-use is still prevented as this error is still thrown?

Context in our use case is Alexa wishes to keep old refresh tokens valid, and I suspect this may be leading us to revoke their chain when they re-use old ones, which isn't ideal and their implementation does not seem to follow best practices.

https://developer.amazon.com/en-US/docs/alexa/account-linking/requirements-account-linking.html#access-token-uri-requirements

Refresh tokens – The authorization server should not immediately invalidate old refresh tokens when generating a new one. In addition to possibly causing outages, this tends to leave the user in a state from which the only recovery is to disable, enable, and account-link the skill from the Alexa app again. The best practice is either to have refresh tokens that do not expire, or, for refresh tokens that do expire, to keep a certain number of old refresh tokens valid. In that case, only invalidate refresh tokens after the authorization server confirms that the Alexa service successfully received the most recent refresh token and used it to obtain a new access token.

Many thanks in advance for your help,
James

**Comment by panva** [comment]
@jamesacres this falls in line of a question, not an issue. I'm transferring to Discussions where it should've been in the first place.
