### ISSUE TITLE
Token introspection?

### ISSUE THREAD

**Issue by flyweight** [panva/node-oidc-provider#103]
Filip,

I have a custom authorizer (aws lambda) that sits behind an API gateway.  After authenticating via your OIDC Provider, they are provided with a bearer token.  Requests will come in with a bearer token in the Authorization header through the API gateway and into the custom authorizer.  My authorizer doesn't have the client id/secret that was originally used to create the bearer token.  How can I validate the token and get the available scopes?  Thanks for your help.

**Comment by panva** [comment]
I am not familiar with the capabilities of a lambda authorizer. Sorry. But as you titled the topic Introspection, it is supported > see the readme and configuration.

Any client can do token introspection, it is not limited to the one a token belongs to. An introspection purposed client can exist that has grant_types, response_types and redirect_uris as empty arrays.

**Comment by panva** [comment]
https://tools.ietf.org/html/rfc7662#section-2.1

**Comment by flyweight** [comment]
> Any client can do token introspection, it is not limited to the one a token belongs to. An introspection purposed client can exist that has grant_types, response_types and redirect_uris as empty arrays.

This is perfect.  Thanks for the fast response.

**Comment by panva** [comment]
Happy to help.
