### ISSUE TITLE
Support Hashed client_secret

### ISSUE THREAD

**Issue by joshperry** [panva/node-oidc-provider#104]
For security reasons we'd like to only store client_secret as a salted hash in our database.

If the unhashed client_secret is not available then symmetric encryption and HMAC based signing features would not be available. In our case we only use asymmetric keys for protecting tokens so we do not need an unhashed client_secret.

What would you think of an option that would allow us to provide a mutation function to hash the auth client_secret before comparing it to the (hashed) secret in the client metadata at:
https://github.com/panva/node-oidc-provider/blob/master/lib/shared/token_auth.js#L72
and https://github.com/panva/node-oidc-provider/blob/master/lib/shared/token_auth.js#L40

**Comment by panva** [comment]
Like so? https://tools.ietf.org/html/rfc6819#section-5.1.4.1.3

I assume this is an OP-wide policy, no exceptions for specific clients, which means indeed that symmetric signing and encryption features will be disabled. (HS* sig algs, PBES2-* encryption algs).

What about dynamic registration features? A secret needs to be generated and returned in clear to a registration response, but stored hashed, it will then be missing from further read and Dynamic Registration Management will not accept requests with the client_secret field in the request.

Will you provide a PR with the feature and test coverage or is this more of a feature request? It does sounds like a lot of  hoops to go through for little added value ;) Wouldn't it be simpler to instruct your adapter to encrypt / decrypt the Client metadata instead?

**Comment by joshperry** [comment]
Yes exactly, this would be an OP-wide policy.

Dynamic registration should not be a problem, we can still generate and return client_secret in clear text for the client before hashing and persisting it. The only place we would not be able to return the secret is at the client metadata GET endpoint, I'm not sure if returning the hashed value or no value would be preferable here.

I also noticed that oidc-provider has a PUT endpoint for client metadata that I could not find defined in the spec. An option would be to modify that endpoint to allow the client to signal the OP to generate and return a new client_secret for cases where the original was lost (the other case would be for an expired client_secret, but it doesn't look like that feature is supported here).

I'd be willing to take a crack at a PR, just wanted to have a conversation first to try and figure out the best way to accomplish this inside spec before I start putting code down.

Appreciate the feedback.

**Comment by panva** [comment]
I don't see this violating any spec, especially if it's an optional setting. But have you considered the encryption?

Update and Delete is taken from [RFC7592 - OAuth 2.0 Dynamic Client Registration Management Protocol](https://tools.ietf.org/html/rfc7592).

Update Request, on one hand

> This request MUST include all client metadata fields as returned to the client from a previous registration, read, or update operation.

but then 

> If the client includes the "client_secret" field in the request, the value of this field MUST match the currently issued client secret for that client.  The client MUST NOT be allowed to overwrite its existing client secret with its own chosen value.

So i'd say the "client_secret" could be omitted from the request at all times, and in your specific case actually completely forbidden / ignored (and not returned).


> I'm not sure if returning the hashed value or no value would be preferable here.

omit client_secret from the response

**Comment by joshperry** [comment]
Ah, thanks for the link!

Yes, we are currently encrypting the secret with a symmetric key and we have methods for securing secrets like these, but if the host or process was compromised we would have to assume that all client secrets were exposed. Key management is error prone and I'm just trying to maximize our security-in-depth position.

This alone may not be a huge security win, but in concert with the rest of our security story, unnecessarily storing secrets only adds risk with little to no benefit. However, perhaps I'm being overly cautious considering the almost non-secret nature of client secrets in a lot of cases?

**Comment by panva** [comment]
> However, perhaps I'm being overly cautious considering the almost non-secret nature of client secrets in a lot of cases?

Any secret bundled with a distributed package (such as a native iOS app) is not secret anymore and must be treated as such by an OP. For those, true, it makes no difference what you store in your OP database. oidc-provider supports PKCE and the complete [AppAuth](https://appauth.io/) package.

Let's assume an attacker gets to your environment and extracts everything out of it, that includes client_secret hashes and the mechanism(alg, salt) you use to hash it, as well as the mechanism that generates these secrets (oidc-provider). Unless you use an adaptive function 
 such as bcrypt or similar to create and compare the secret they will be able to just brute-force search the secrets anyway (you dont use hashes for account passwords either). And i don't think you want to compare expensive bcrypt for every token call, do you?

On top of that, your OP may be the most secure OP in the world, the weakest links are then the RPs where you still have the cleartext secret. I think your best story is detection and abuse prevention. oidc-provider has behaviors in which support [rotating refresh tokens on use](https://github.com/panva/node-oidc-provider/blob/master/lib/helpers/defaults.js#L387-L399)(default in 2.0), revoking the whole token chain upon [repeated auth code](https://github.com/panva/node-oidc-provider/blob/master/lib/actions/token/authorization_code.js#L39-L47) use etc.

You see the prevention of abuse is covered, an RP should realize its tokens are awfuly often revoked unexpectedly - that's the latest for of detection. But you can also listen for the `token.revoked` and `grant.error` events to find this out sooner yourself.

**Comment by joshperry** [comment]
Yeah exactly, Android APKs and desktop binaries have the same issue, the only secure use-case is protecting it behind a service.

I'm going to have to agree with you here, there is better fruit to pick right now. Your perf argument is also one I hadn't considered: our current in-house oidc impl that we've been running with for a couple years _does_ use salted pbkdf2 with 10k iterations for the client secret...

I really appreciate the thoughtful replies, and the extremely well done project. Your code and docs are enjoyable to read and I'm excited to be retiring our in-house impl with this.

**Comment by panva** [comment]
You're very welcome, I would be very interested to learn more about your product and the scale of the environment. If you have the chance to share some insight, please send me a private message via email. Developer feedback and improvement suggestions are always welcome.

> our current in-house oidc impl that we've been running with for a couple years does use salted pbkdf2 with 10k iterations for the client secret

This is intriguing, could you elaborate on the time and resource costs of this approach?

**Comment by joshperry** [comment]
Absolutely, I'll send an email over with some info tomorrow.

The check takes about 1 second on our current servers, and we haven't seen much issue with perf currently, but that's because our main SPA web application actually uses implicit mode so we don't do secret verification on the majority of requests. 

However, our tokens are quite short lived,  we are starting to ramp up third party partner integrations with our system, and we have some binary apps in the oven. I could definitely see this being a bit of an issue as the load increases and a source of unwanted latency, for especially our mobile users.
