### ISSUE TITLE
Authenticate user after login screen on backend.

### ISSUE THREAD

**Issue by sidgangs99** [panva/node-oidc-provider#1041]
**Describe the bug**

I'm trying to implement `node-oidc-provider` library. While integrating, I could not figure out how to authenticate email and password with my own application in which is written in `NestJs`. Although, is this a way to configure `findbyLogin` func inside configuration and if so, then what all parameters do it accepts. 

Also I hope `findAccount` just provides me email ID, there must be some function which I can use, or I have to build me own.

**To Reproduce**
Provider and Client configuration: (inline or gist)
```js
 proxy: true,
    pkce: {
      required: function pkceRequired(ctx, client) {
        return false;
      },
    },
    async findAccount(ctx, id) {
      return {
        accountId: user.id,
        //   logic to actually authenticate with Nbyula
        async claims(use, scope) {
          return {
            sub: user.id,
            // email: user.email,
          };
        },
      };
    },
    expiresWithSession: async function expiresWithSession(ctx, token) {
      return !token.scopes.has('offline_access');
    },
    features: {
      introspection: {
        enabled: true,
      },
    }

```

**Comment by panva** [comment]
Hi @sidgangs99

Please follow the right channel to ask questions. The issues tracker is for bug reports, not questions. I'm closing this and transferring it to a Discussion intended for Q&A.
