### ISSUE TITLE
Error: missing required parameter 'grant_type'

### ISSUE THREAD

**Issue by jack-farley** [panva/node-oidc-provider#1046]
**Describe the bug**
When I send a request to the token endpoint, it gives me an 'invalid_request' error with description 'missing required parameter 'grant_type'". The request is as follows:

`https://localhost:3000/oidc/token?grant_type=authorization_code&code=thz799Q44kxWOwioKsV5i-zeBszXnDYLje_QrWq4qhF&redirect_uri=https://0.0.0.0:3000/test&client_secret=secret`

Clearly, grant_type is specified as a parameter, so either the error message is incorrect or there is a bug in the handling of token requests.

**To Reproduce**
Provider and Client configuration: (inline or gist)
```js
const pkceMethod : PKCEMethods = 'S256';

const codeResponse : ResponseType = 'code';
const idTokenResponse : ResponseType = 'id_token';
const bothResponse : ResponseType = 'code id_token';

const openIdConfig = {
    clients: [{
        client_id: 'id',
        client_secret: 'secret',
        redirect_uris: [`https://${config.url}:${config.port}/test`],
        grant_types: ['authorization_code', 'implicit', 'refresh_token'],
        response_types: [codeResponse, idTokenResponse, bothResponse],
    }],
    claims: {
      address: ['address'],
      email: ['email', 'email_verified'],
      phone: ['phone_number', 'phone_number_verified'],
      profile: ['birthdate', 'family_name', 'gender', 'given_name', 'locale', 'middle_name', 'name',
        'nickname', 'picture', 'preferred_username', 'profile', 'updated_at', 'website', 'zoneinfo'],
    },
    interactions: {
        url(ctx : any, interaction : any) {
            return `/interaction/${interaction.uid}`
        }
    },
    findAccount: Account.findAccount,
    pkce: {
        methods: [
            pkceMethod
        ],
        required: function pkceRequired(ctx : KoaContextWithOIDC, client: any) {
            return false;
        },
    },
    features: {
        devInteractions: {
            enabled: false,
        }
    },
};

const provider = new Provider(`https://${config.url}:${config.port}`, openIdConfig);

app.use('/oidc', provider.callback());
```

Steps to reproduce the behaviour:

1.  Go through the authorization code flow to get an authorization code for a particular user.
2.  Hit the token endpoint with the above request.

**Expected behaviour**
The response from this request should either provide the tokens or return an error that is not "missing required parameter 'grant_type'".

**Environment:**
 - oidc-provider version: 7.5.1
 - node version: 14.17.2

**Additional context**

 - [x] the bug is happening on latest oidc-provider too.
 - [x] i have searched the issues tracker on github for similar issues and couldn't find anything related.
 - [x] i have searched the [FAQ](https://github.com/panva/node-oidc-provider/blob/v7.x/docs/README.md#faq) and couldn't find anything related.

**Comment by panva** [comment]
You are not providing parameters using the way you're supposed to.

**Comment by jack-farley** [comment]
I'm pretty sure that's the standard way to provide parameters in both OIDC and HTTP, no? If you could elaborate, that would be much appreciated.
