### ISSUE TITLE
Different Client ID, same browser session, it does not ask to authenticate  

### ISSUE THREAD

**Issue by cloudstorydev** [panva/node-oidc-provider#1047]
**Describe the bug**
Open a browser, authenticate using client_id="xyz", and success
Same browser session, authenticate using client_id = "abc", redirect back to app without login prompt. It apparently picked up the same session from the database with client_id xyz, based on the logs.  Token issued are correct (abc), but why no login prompt?

 
**Environment:**
 - oidc-provider version:   7.1.1
 - node version:  v12.22.1
 
**Logs**
 After trying to login using second client_id (abc):

Executing (default): SELECT "id", "uid", "data", "expiresAt", "consumedAt", "createdAt", "updatedAt" FROM "idp_sessions" AS "Session" WHERE "Session"."id" = 'Uog8Kd0zeYvoHRroqGbz1';
Executing (default): SELECT "id", "data", "expiresAt", "consumedAt", "createdAt", "updatedAt" FROM "idp_clients" AS "Client" WHERE "Client"."id" = 'abc';
resource indicator:  http:/localhost:8080 Client {
  applicationType: 'web',
  grantTypes: [ 'authorization_code', 'refresh_token' ],
  idTokenSignedResponseAlg: 'RS256',
  postLogoutRedirectUris: [
    'https://abc.idm.test/oidc/logout',
    'https://abc.lms.test/oidc/logout',
    'http://localhost:8000/oidc/logout'
  ],
  requireAuthTime: false,
  responseTypes: [ 'code' ],
  subjectType: 'public',
  tokenEndpointAuthMethod: 'none',
  introspectionEndpointAuthMethod: 'none',
  requireSignedRequestObject: false,
  requestUris: [],
  clientId: 'abc',
  clientSecret: 'secret',
  redirectUris: [
    'https://abc.idm.test/oidc/callback',
    'https://abc.lms.test/oidc/callback',
    'http://localhost:8000/oidc/callback'
  ]
}

====== 

Executing (default): UPDATE "idp_authorization_codes" SET "consumedAt"=$1,"updatedAt"=$2 WHERE "id" = $3
===== auth code consumed ====  AuthorizationCode {
  exp: 1626257325,
  iat: 1626256725,
  nonce: '91446a375caaca3dc3573c1ef5e73934',
  scope: 'openid email access_plans tenant ',
  grantId: 'WXeSxAKj19RMwkZfh6a-78QlMgypjMv9XLOH_nsvD3T',
  authTime: 1626256608,
  clientId: 'abc',
  resource: 'http:/localhost:8080',
  accountId: 'xyz:ee9ebc2d-3d2f-4196-95fd-be5c5e02ba1b',
  sessionUid: 'rLefgw4lMLj01tEgRyvsV',
  redirectUri: 'https://abc.lms.test/oidc/callback',
  codeChallenge: 'cCIhcoGo9jwDuwakQZz5HLyi-2oFlx-W3XSzYkWbW2Q',
  expiresWithSession: true,
  codeChallengeMethod: 'S256',
  kind: 'AuthorizationCode',
  jti: 'B1qi63fwG16lC7hK8lJpLwWj7f9TUsUgdECN38IWC8A'
}

======= 

esource indicator:  http:/localhost:8080 Client {
  applicationType: 'web',
  grantTypes: [ 'authorization_code', 'refresh_token' ],
  idTokenSignedResponseAlg: 'RS256',
  postLogoutRedirectUris: [
    'https://abc.idm.test/oidc/logout',
    'https://abc.lms.test/oidc/logout',
    'http://localhost:8000/oidc/logout'
  ],
  requireAuthTime: false,
  responseTypes: [ 'code' ],
  subjectType: 'public',
  tokenEndpointAuthMethod: 'none',
  introspectionEndpointAuthMethod: 'none',
  requireSignedRequestObject: false,
  requestUris: [],
  clientId: 'abc',
  clientSecret: 'secret',
  redirectUris: [
    'https://abc.idm.test/oidc/callback',
    'https://abc.lms.test/oidc/callback',
    'http://localhost:8000/oidc/callback'
  ]
}
===== TOKEN ISSUED =====   AccessToken {
  accountId: 'xyz:ee9ebc2d-3d2f-4196-95fd-be5c5e02ba1b',
  expiresWithSession: true,
  grantId: 'WXeSxAKj19RMwkZfh6a-78QlMgypjMv9XLOH_nsvD3T',
  gty: 'authorization_code',
  sessionUid: 'rLefgw4lMLj01tEgRyvsV',
  sid: undefined,
  kind: 'AccessToken',
  jti: 'J_3lZ7JqLKobk2M1U2Vmv',
  clientId: 'abc',
  aud: 'resource-server-audience-value',
  scope: '',
  expiresIn: 7200,
  format: 'jwt'
}

**Comment by panva** [comment]
This is the intended single sign on session persistance behaviour. For further question like topics use discussions, not the bug issue tracker.

**Comment by cloudstorydev** [comment]
Thanks for the response.  I saw in other discussion about multi tenancy, it's kind of suggested to use different client_id. Any suggestions how to make it login again if it's different client_id?

**Comment by cloudstorydev** [comment]
I did try to return undefined when searching for session in adapter, but error when logout : "could not find logout details"
this one also set to false. 
   expiresWithSession: (ctx, token) =>{
      return false;
    }, 

How to disable Session totally?
