### ISSUE TITLE
Protect registration_endpoint

### ISSUE THREAD

**Issue by mogeda** [panva/node-oidc-provider#105]
Is there any way to protect registration_endpoint? It looks anyone can register a client via registration_endpoint as long as the registration feature enabled in OP.

**Comment by panva** [comment]
The mechanism for protecting this endpoint is Initial Access Token (as per specification). See the configuration page to see how to enable this.

You have the chance to create a fixed one, or create and control them through your adapter.

**Comment by mogeda** [comment]
thank you for the information and quick responses!

**Comment by panva** [comment]
You're very welcome. I very much recommend to go through the specs if you're using these "optional" features.
