### ISSUE TITLE
Kickoff the Example App

### ISSUE THREAD

**Issue by coreyperkins** [panva/node-oidc-provider#106]
I am taking a stab at learning how the example app works, but I am having a hard time getting going. I have noticed several routes available, but I do not think I am providing the correct parameters to make it to the login page. I checked SO, but I was not able to pull up much help there.

I do successfully see the server configuration @ http://localhost:3000/.well-known/openid-configuration.

The /interaction/:grant route appears to take a grant type. I have called this route with authorization_code (because I found that to be a supposed grant type in the configuration on line 28 of example/index.js) but it fails with "oops something went wrong". I also included the client_id parameter set to the client_id in the configuration.

Anybody got a url I can sling at this guy to get the login page logic starting on line 74 of example/index.js to render? Thx.

EDIT: Here are some of the things I see when I set the debug flag and hit the route.

Thu, 25 May 2017 18:47:40 GMT oidc-provider:server_error uuid=f230c786-b636-468a-9e83-64dbfd7e61ed path=/interaction/authorization_code error=Error: interaction cookie manipulated, expired or otherwise not received at Provider.grantCookie (/Users/corey/Source/Repos/oidc-provider/lib/provider.js:35:11) at Provider.interactionDetails (/Users/corey/Source/Repos/oidc-provider/lib/provider.js:165:24) at Object.renderInteraction (/Users/corey/Source/Repos/oidc-provider/example/index.js:70:29) at renderInteraction.next (<anonymous>) at Object.dispatch (/Users/corey/Source/Repos/oidc-provider/node_modules/koa-router/lib/router.js:334:12) at dispatch.next (<anonymous>) at Object.allowedMethods (/Users/corey/Source/Repos/oidc-provider/node_modules/koa-router/lib/router.js:369:12) at allowedMethods.next (<anonymous>) at onFulfilled (/Users/corey/Source/Repos/oidc-provider/node_modules/co/index.js:65:19) at /Users/corey/Source/Repos/oidc-provider/node_modules/co/index.js:54:5
Thu, 25 May 2017 18:47:40 GMT oidc-provider:server_error:trace Error: interaction cookie manipulated, expired or otherwise not received
    at Provider.grantCookie (/Users/corey/Source/Repos/oidc-provider/lib/provider.js:35:11)
    at Provider.interactionDetails (/Users/corey/Source/Repos/oidc-provider/lib/provider.js:165:24)
    at Object.renderInteraction (/Users/corey/Source/Repos/oidc-provider/example/index.js:70:29)
    at renderInteraction.next (<anonymous>)
    at Object.dispatch (/Users/corey/Source/Repos/oidc-provider/node_modules/koa-router/lib/router.js:334:12)
    at dispatch.next (<anonymous>)
    at Object.allowedMethods (/Users/corey/Source/Repos/oidc-provider/node_modules/koa-router/lib/router.js:369:12)
    at allowedMethods.next (<anonymous>)
    at onFulfilled (/Users/corey/Source/Repos/oidc-provider/node_modules/co/index.js:65:19)
    at /Users/corey/Source/Repos/oidc-provider/node_modules/co/index.js:54:5

EDIT: I have duplicated this on master and using the v1.15.11 tag.

**Comment by panva** [comment]
Interactions are required from a user during Authorization Request. You aren't doing an authorization request at all.

**Comment by coreyperkins** [comment]
I misunderstood the example to be complete.

**Comment by panva** [comment]
I see. If setting up your own OpenID Connect Provider is indeed what you're looking after then follow the step by step guide instead https://github.com/panva/node-oidc-provider-example
