### ISSUE TITLE
enabledJWA.requestObjectEncryptionAlgValues does not accept "RSA-OAEP"

### ISSUE THREAD

**Issue by deboraelkin2** [panva/node-oidc-provider#1060]
### What happened?

If you set  the configuration parameter 
`enabledJWA.requestObjectEncryptionAlgValues = ["RSA-OAEP"]`

The `/.well-known/openid-configuration` endpoint returns:
` "request_object_encryption_alg_values_supported": []` 

Instead of the expected value.

If you remove the configuration parameter, the configuration endpoint returns:

````
"request_object_encryption_alg_values_supported": [
    "A128KW",
    "A256KW",
    "dir"
  ]
````

instead of the [documented default value](https://github.com/panva/node-oidc-provider/blob/HEAD/docs/README.md#enabledjwarequestobjectencryptionalgvalues)
````
"request_object_encryption_alg_values_supported": [
  'A128KW',
  'A256KW',
  'ECDH-ES',
  'RSA-OAEP',
  'dir'
]
````

### Version

v7.5.4

### Node.js version

v12.19.0

### Reproduction & Logs

Use a vanilla instance, invoke the `/.well-known/openid-configuration` endpoint and verify that the response contains 
````
"request_object_encryption_alg_values_supported": [
    "A128KW",
    "A256KW",
    "dir"
  ]
````
instead of the documented default value:
````
"request_object_encryption_alg_values_supported": [
  'A128KW',
  'A256KW',
  'ECDH-ES',
  'RSA-OAEP',
  'dir'
]
````

### 

- [X] I have searched the issues tracker and discussions for similar topics and couldn't find anything related.
- [X] I have searched the [FAQ](https://github.com/panva/node-oidc-provider/blob/v7.x/docs/README.md#faq) and couldn't find anything related.
- [X] I agree to follow this project's [Code of Conduct](https://github.com/panva/node-oidc-provider/blob/main/CODE_OF_CONDUCT.md)

**Comment by deboraelkin2** [comment]
Looking at the code (oidc-provider/lib/helpers/configuration.js), this is because of the regular expression applied on the configuration parameter value (line 284):

````
this.setAlgs('requestObjectEncryptionAlgValues', allowList.requestObjectEncryptionAlgValues.filter(RegExp.prototype.test.bind(/^(A|P|dir$)/)), 'encryption.enabled', ['requestObjects.request', 'requestObjects.requestUri', 'pushedAuthorizationRequests.enabled']);
````  
So `RSA-OAEP` is filtered out, regardless of the values of the other configuration parameters: encryption.enabled, requestObjects.request, etc

It is beyond my basic knowledge as to the implications of changing the value of that regular expression

**Comment by panva** [comment]
https://op.panva.cz/.well-known/openid-configuration

You're just missing an applicable key in the OP's jwks for the algorithm to show up.

**Comment by panva** [comment]
Please consider [supporting](https://github.com/panva/node-oidc-provider?sponsor=1) the library if you'd like assistance with its configuration. Supporting the library means, amongst other things, that any support and the library itself will be available in the future.
