### ISSUE TITLE
revocation of expired token & allow only 1 active access/refresh token

### ISSUE THREAD

**Issue by slavab89** [panva/node-oidc-provider#107]
I've noticed that my DB starts to pile up with access/refresh tokens 😄 

It seems that if a token is expired, it cannot be revoked / destroyed because while trying to "find" it in the revocation endpoint, it doesnt pass `ignoreExpiration` param. Is there a reason for that?
If there is, how should i clean up old access keys? Using only an active token? Or during the session_end endpoint as you've suggested in https://github.com/panva/node-oidc-provider/issues/84.

Moreover, is there a way for me to have only 1 active tokenset? So that if i try to create a new access_token / refresh_token, it will mark the "old" ones as consumed or something like that.

**Comment by panva** [comment]
> Moreover, is there a way for me to have only 1 active tokenset?

There is not. A policy like this is not supported at this time.

> I've noticed that my DB starts to pile up with access/refresh tokens

When tokens are saved the expiration is part of the call to your adapter, i suggest to drop tokens from your persistance after they expire. A great mechanism for this is i.e. redis key TTL or mongodb's document ttl. You can also just store the expiration date, index it, and do a batch drop of past tokens once every while.

> It seems that if a token is expired, it cannot be revoked / destroyed because while trying to "find" it in the revocation endpoint, it doesnt pass ignoreExpiration param. Is there a reason for that?

I'll take a look at this, either way - an expired / revoked token is to be the same, and it's not the RP's responsibility to clean up, the OP should, see above.

**Comment by panva** [comment]
> Moreover, is there a way for me to have only 1 active tokenset? So that if i try to create a new access_token / refresh_token, it will mark the "old" ones as consumed or something like that.

Such policy is something you can integrate on your own, the `token.issued` event would be a great place for you to run the necessary queries to drop the other tokens for a given client/account combination.

**Comment by slavab89** [comment]
I believe that i understand why the revocation endpoint is not destroying an expired token - like you've said, for the RP, that token is not valid anyway.

Regarding having only 1 active token:
My only concern is the possibility that 2 requests to create a token would arrive to the server together and both newly created tokens would end up as "consumed" (Because both actions to consume the token would send an async request to the DB).
And if i'll have a distributed OP, it would be worse... I guess its not the way to go.


What i'm trying to "fix" is a more general architecture thing for my app.
When trying to get some data from the Resource Owner, i check that the token is valid using `/introspect`. When its not valid, i try to immediately create a new token using `/refresh`.
The thing is that there are times when i need 2 things together from the RO (2 async requests).
This causes a creation of 2 tokens instead of only 1.
The flow should be different i'm sure of it 😜

**Comment by panva** [comment]
> I guess its not the way to go.

Why? It is exactly what you need, a policy. Enforced policy is the only thing you can do to "fix" the flow problem. Once your clients realize their implementation leads to race conditions and edge cases where their freshly received token is no longer valid, they will be forced to fix / change it.

**Comment by slavab89** [comment]
Since i'm also a client of myself i'm trying to do the whole flow.
But i understand what you're trying to say =].
