### ISSUE TITLE
Token introspection fails after token exchange flow

### ISSUE THREAD

**Issue by 6S** [panva/node-oidc-provider#1070]
### What happened?

Hello,

I have implemented the token exchange grant type.

It seems to work well, i.e. I get a new access token with the requested scopes after using this grant type.

However when I try to check the generated access token, the introspections endpoint tells me that my freshly generated token is not active.

I would like to point out that I only encounter this problem when the client requesting the token exchange is different from the client who obtained the initial token via an authorization code flow:

- Auth code flow using client A > Token exchange using client A > Introspection: OK (active=true)
- Auth code flow using client A > Token exchange using client B > Introspection: NOK (active=false)

### Version

7.3.1

### Node.js version

14

### Reproduction & Logs

Here my implementation of the token exchange:

```js
function registerTokenExchangeGrantType(provider: Provider): void {
  const grantType = 'urn:ietf:params:oauth:grant-type:token-exchange';
  const parameters = ['scope', 'subject_token', 'subject_token_type'];
  provider.registerGrantType(
    grantType,
    async (ctx, next) => {
      const { AccessToken } = provider;
      const scopeParams = ctx.oidc.params.scope as string;
      const scopes = [...new Set(scopeParams.split(' '))];

      checkScope(ctx);

      const subject_token_type = ctx.oidc.params.subject_token_type as string;
      if (!subject_token_type) {
        throw new errors.InvalidRequest('missing parameter subject_token_type.');
      }
      if (subject_token_type !== 'urn:ietf:params:oauth:token-type:access_token') {
        throw new errors.InvalidRequest('unsupported subject_token_type.');
      }
      const subjectToken = ctx.oidc.params.subject_token as string;

      const accessToken = await provider.AccessToken.find(subjectToken, { ignoreExpiration: true });
      if (!accessToken || accessToken.isExpired) {
        throw new errors.InvalidGrant('Invalid token');
      }
      const account = await AccountService.findUser(ctx.oidc.client.clientId, accessToken.accountId, null);
      if (!account) {
        throw new errors.InvalidGrant('Invalid token');
      }

      const newAccessToken = new AccessToken({
        accountId: accessToken.accountId,
        claims: accessToken.claims,
        client: ctx.oidc.client,
        expiresWithSession: false,
        grantId: accessToken.grantId,
        gty: 'urn:ietf:params:oauth:grant-type:token-exchange',
        sessionUid: accessToken.sessionUid,
        sid: accessToken.sid,
        scope: scopes.join(' ') || undefined,
      });

      ctx.oidc.entity('AccessToken', newAccessToken);
      const newAccessTokenValue = await newAccessToken.save();

      ctx.body = {
        access_token: newAccessTokenValue,
        expires_in: token.expiration,
        token_type: token.tokenType,
        scope: token.scope,
      };

      await next();
    },
    parameters,
  );
}
```

### 

- [X] I have searched the issues tracker and discussions for similar topics and couldn't find anything related.
- [X] I have searched the [FAQ](https://github.com/panva/node-oidc-provider/blob/v7.x/docs/README.md#faq) and couldn't find anything related.
- [X] I agree to follow this project's [Code of Conduct](https://github.com/panva/node-oidc-provider/blob/main/CODE_OF_CONDUCT.md)

**Comment by panva** [comment]
The grantId points to a grant object for a single client and account id. Since you copy the grantId, during introspection by any client the grant will be loaded and there will be a mismatch between the tokens client and the grant's client.

There's no bug, just that your implementation doesn't take the grant relationship into account at all. 

Userinfo response would also not work.

**Comment by 6S** [comment]
Hello,

Thanks a lot for your reply.

I managed to solve the issue by retrieving the session and generating a `grantId` for the client performing the token exchange. :relaxed:

```js
      const session = await provider.Session.get(ctx);
      const newAccessToken = new AccessToken({
        accountId: accessToken.accountId,
        claims: accessToken.claims,
        client: ctx.oidc.client,
        expiresWithSession: false,
        grantId: session.grantIdFor(ctx.oidc.client.clientId),
        gty: 'urn:ietf:params:oauth:grant-type:token-exchange',
        sessionUid: accessToken.sessionUid,
        sid: accessToken.sid,
        scope: scopes.join(' ') || undefined,
      });
```

Remember also to set `expiresWithSession` to `false`. I haven't quite figured out why this parameters has to be set to `false` but it works.

Just a question: why the new token is exchanged without error if the `grantId` is not related to the proper client or if `expiresWithSession` is set to `true` while the new generated token is invalid .
Are there circumstances in which this pattern makes sense? Otherwise shouldn't it be possible to return an error at the token exchange step?

**Comment by 6S** [comment]
Related to #749
