### ISSUE TITLE
client_secret_post type doesn't include client_secret

### ISSUE THREAD

**Issue by jessereitsma** [panva/node-oidc-provider#108]
Hi,

First of all, i'm not sure if this is somehow related to #83.. 

I use this module in combination with a Jira Service Desk plugin, but I keep getting the error:
```
{ error: 'invalid_request', error_description: 'client_secret must be provided in the Authorization header' }
```

After some debugging I found that this error was thrown by `token_auth.js`
`this.oidc.authorization` is an object with only `clientId` in it, not `clientSecret`.
(Which is required according to the assert there)

The `this.oidc.authorization` object is set in `find_client_id.js`.
There is an if located with `client_secret_basic`, `client_secret_post` and `client_secret_jwt and private_key_jwt`.
My code runs in the else if for the `client_secret_post`, but the only thing that is done there is the following:
```
this.oidc.authorization.clientId = params.client_id;
```

But the `clientSecret` is not set there.. But `params.client_secret` is defined with the right clientSecret.
If I put the following line under the clientId line:
```
this.oidc.authorization.clientSecret = params.client_secret;
```

It works for me, but I'm not sure if this is the right way to go.

**Comment by panva** [comment]
Hello @jessereitsma,

This is unrelated to that ticket. It's likely a [misconfiguration](https://github.com/panva/node-oidc-provider/wiki/FAQ#client_idsecret-must-be-provided-in-s) on your end.

Your client is configured with `token_endpoint_auth_method: "client_secret_basic"`, so the OP expects the secret to be in the header. If your client sends the credentials in a POST body, then you need your client to be configured with `token_endpoint_auth_method: "client_secret_post"`

**Comment by jessereitsma** [comment]
Ah, thanks. It works.
I had tried it before, but I think I had some other settings wrong which cauzed it to not work that time.
Tried it again with my current configuration (except for the `client_secret_post`) and it works.

**Comment by panva** [comment]
Great!
