### ISSUE TITLE
refresh token grant with a consumed token appears to session in invalid state

### ISSUE THREAD

**Issue by fiendfiend** [panva/node-oidc-provider#1086]
### What happened?

I had a frontend issue which resulted in duplicated `POST /token` refresh_token grant requests.

However this appeared to uncover a separate issue relating to this code in `lib/actions/grants/refresh_token.js`:

```
  if (refreshToken.consumed) {
    await Promise.all([
      refreshToken.destroy(),
      revoke(ctx, refreshToken.grantId),
    ]);
    throw new InvalidGrant('refresh token already used');
  }
```

As a result of the this, the grant associated with the refresh token is destroyed, however the grantId is still referenced in the OIDC context session:

```
session: {
    accountId:  "USER_ID"      
    authorizations: {
     [CLIENT_ID]: {
      grantId:  "CONSUMED_GRANT_ID"        
      sid:  ""        
     }
  }
```

Should we expect `node-oidc-provider` to handle this and update the authorisations in the session?

### Version

v7.3.2

### Node.js version

v14.15.5

### Reproduction & Logs

Perform refresh_token flow with the same token twice such that the second call triggers the `refresh token already used` branch in the default refresh_token grant implementation.

The associated grant will be deleted from the data store, however a reference to it remains in the session authorisations array.

### 

- [X] I have provided a gist or a public repo which can be cloned, installed and ran locally in order to reproduce the bug in the textarea above.
- [X] I have searched the issues tracker and discussions for similar topics and couldn't find anything related.
- [X] I have searched the [FAQ](https://github.com/panva/node-oidc-provider/blob/v7.x/docs/README.md#faq) and couldn't find anything related.
- [X] I agree to follow this project's [Code of Conduct](https://github.com/panva/node-oidc-provider/blob/main/CODE_OF_CONDUCT.md)

**Comment by panva** [comment]
Hi @fiendfiend 

> Should we expect node-oidc-provider to handle this and update the authorisations in the session?

No you should not.
