### ISSUE TITLE
node-oidc-provider with LDAP support

### ISSUE THREAD

**Issue by phish108** [panva/node-oidc-provider#109]
This is not a bug report, just wanted to say thank you for your work. 

I started building on your work for an LDAP integration. The repo is available here [on github](/BLC-HTWChur/ldap-oidc-provider).

**Comment by panva** [comment]
I __love__ it! Please keep me posted and let me know if there's anything you see the library is missing that you'd need. Either here via issues or by email.

**Comment by panva** [comment]
If I may suggest/recommend, already use node > 7.6.0 and start using the [`next`](https://github.com/panva/node-oidc-provider/blob/82a092b/CHANGELOG.md) branch of oidc-provider, the latest npm release is now `2.0.0-pre.2`. Reason is, node8 is just around the corner and finalization of [oauth-native-apps](https://tools.ietf.org/html/draft-ietf-oauth-native-apps) as well, which means the 2.0.0 release of oidc-provider is also imminent.
