### ISSUE TITLE
Questions  the scope

### ISSUE THREAD

**Issue by thomas-lee** [panva/node-oidc-provider#11]
Hi, I am new to Open ID Connect and I saw your library. 

It looks good but I have a few questions,

According to the OAuth 2.0, we can mention scopes in the token request.
Just like this example, we can mention something like read:page, edit:page as scopes.
https://brandur.org/oauth-scope,

I want to know if i can  verify the request scope and update the available scope(some permission checking on the scopes) returned in the response.

As a result, client requests from the resource server can check against the scope and validate, return the resource back.

I am thinking if it is possible to do some checking and update the scope values myself on the token.js.

But I don't know if it follows properly on the OpenID Connect / OAuth 2.0 specifc.

Another concern is about whether affect the resource server to validate the access token.

Thanks.

```
const at = new provider.AccessToken({

});
```

**Comment by panva** [comment]
Hello,

you are free to define and use as many custom scopes you need. When instantiating a new Provider just give an array of scopes you'd like your provider to expose, just be sure to provide all scopes in this case, like so

```js
const provider = new Provider('http://localhost:3000', {
  scopes: [
    'address',
    'email',
    'offline_access',
    'openid',
    'phone',
    'profile',
    'edit:page',
    'read:page'
  ],
  ... // rest of your settings
}
```

Afterwards just include the scopes you want the authorization to result in to the authorization request and you are set.

In the rest of your application you can load the actual AccessToken like so:

```js
provider.AccessToken.find(tokenValue).then(console.info, console.error);
```
This is especially helpful if you're creating an OAuth2.0 covered API and need to [validate the Bearer token](https://github.com/panva/node-oidc-provider/blob/master/lib/actions/userinfo.js#L58-L65). Now i realize it may be super useful to expose generic enough koa and express middlewares that do just that in the coming releases.

Please keep in mind the API of the library is not to be taken as stable, (noted by the semver not hitting 1.0.0 yet and specifically these parts will undergo big changes)

**Comment by thomas-lee** [comment]
Thanks for your rapid response,

I have tried the scope config you mentioned, it only validates the support scope in the configuration, but I want more dynamic scopes value that different scopes for different users.

In the login page and the interaction/grant, I guess I can't pass back the scopes they want from my storage/checking.


Btw, the scope I want is the resource access scope which expects to send along with in the token request instead of authorize request?

As you mention, I can use provider.AccessToken.find to check or validate the access token?
So how can I access it from relying party or resource server?


Thanks a lot.

what is the problem/unstable part on the current code? 
I guess I will use your code which help me on the OPEN ID connect flow.

**Comment by panva** [comment]
> In the login page and the interaction/grant, I guess I can't pass back the scopes they want from my storage/checking.

This is what i plan to implement with #4 in a similar way [login details are passed back](https://github.com/panva/node-oidc-provider/blob/master/lib/middlewares/resume.js#L24-L39).


> Btw, the scope I want is the resource access scope which expects to send along with in the token request instead of authorize request?

grant_type=authorization_code does not accept scope parameter to extend/limit the scopes defined during authorization. The grant simply gives the same scopes the authorization was requested with to the access token, you can further limit (but not extend) the scopes your tokens have with grant_type=refresh_token.


> As you mention, I can use provider.AccessToken.find to check or validate the access token?
So how can I access it from relying party or resource server?

Well, if you control all the applications then you may just as well instantiate a Provider in them using the same storage adapter. Then the code will work. If you don't want to do that you can enable [introspection](https://tools.ietf.org/html/rfc7662) and use the introspection endpoint to query for validity and information about a given token. Caching the results in your RP or RS would then be a great idea.


> what is the problem/unstable part on the current code?
There is no problem or unstable code, the code is tested and already put to use in my private projects. However as i continue to use it i discover i need new ways to bend it to do my bidding and for that purpose the way it's configured and the way it exposes it's internal entities will most likely change.


> any plan/day for the 1.0.0 release?
As soon as there are no needs for the API to evolve drastically.


> I guess I will use your code which help me on the OPEN ID connect flow.
Great, let me know how it goes.
