### ISSUE TITLE
Token Decryption

### ISSUE THREAD

**Issue by eskinderg** [panva/node-oidc-provider#111]
I am using node-oidc-provider with my angular2 app which is working excellent.

I have this configuration in my angular2 app.

  settings: {
    authority: 'http://localhost:5000',
    client_id: 'oidcCLIENT',
    redirect_uri: 'http://localhost:4200/authorize',
    post_logout_redirect_uri: 'http://localhost:4200',
    response_type: 'id_token token',
    client_secret: '91c0fabd17a9db3cfe53f28a10728e39b7724e234ecd78dba1fb05b909fb4ed98c476afc50a634d52808ad3cb2ea744bc8c3b45b7149ec459b5c416a6e8db242',
    scope: 'openid email profile',
    silent_redirect_uri: 'http://localhost:4200/silent-renew.html',
    automaticSilentRenew: true,
    accessTokenExpiringNotificationTime: 4,
    silentRequestTimeout:200,
    filterProtocolClaims: true,
    loadUserInfo: true
  }

And on the oidc-provider side, i have this client configuration

module.exports.clients = [{
  client_id: 'oidcCLIENT',
  client_secret: '91c0fabd17a9db3cfe53f28a10728e39b7724e234ecd78dba1fb05b909fb4ed98c476afc50a634d52808ad3cb2ea744bc8c3b45b7149ec459b5c416a6e8db242',
  grant_types: ['implicit'],
  response_types: ['id_token token'],
  post_logout_redirect_uris: ['http://localhost:4200'],
  redirect_uris: [
    'http://localhost:4200/authorize'
  ],
}];

Everything works file. I am able to authenticate using my angular2 app and get both the id_token and token as well and use the id_token on every request to my nodejs api. 
I couldn't figure out how i todecrypt and verify the id_token in my nodejs api middleware and get the payload data.

Thanks

**Comment by panva** [comment]
This has nothing to do with this specific library does it... You're looking for general understanding of JWT and OpenID Connect's ID Token.

And you probably mean decoding, as there is nothing in your config that would enable token encryption (which is possible too). In your backend you should validate the signature of the received id token as just presenting a token is not enough.

- https://jwt.io
- https://tools.ietf.org/html/rfc7519
- http://openid.net/specs/openid-connect-core-1_0.html#CodeIDToken
- http://openid.net/specs/openid-connect-core-1_0.html#ImplicitIDToken
