### ISSUE TITLE
Question about Set-Cookie in authorization end point

### ISSUE THREAD

**Issue by thomas-lee** [panva/node-oidc-provider#112]
In the authorization end point, it will set-cookie and location(redirect) to the login page.

In the  response header, we will set property("Set-Cookie")
```
_grant={"client_id":"app","redirect_uri":"http://127.0.0.1:3000/callback","response_mode":"query","response_type":"code","scope":"openid"}; path=/openid/core/auth/b52de1f0-00ak-4db0-b22f-87f934eb4abe; expires=Tue, 13 Jun 2017 03:53:15 GMT; httponly
```
So we will later have cookies in the login request header.

But some how comma is not allowed in the cookies (mentioned in the RFC standard) (even if we JSON.stringify, there are still commas)

https://stackoverflow.com/questions/25387340/is-comma-a-valid-character-in-cookie-value
https://stackoverflow.com/questions/1969232/allowed-characters-in-cookies

The features works great but since the cookies is too long and is truncated by firewall. And then support team said it is illegal to have comma according to the cookies specification.

So I want to ask if there is alternative way not to use cookies and use another way to implement ?

Thanks

**Comment by panva** [comment]
@thomas-lee thank you for reaching out,

It's not the first time i'm hearing the format is sub optimal, it is the first time that i see headers cut by firewall tho ;)

For 2.0 I will change the format to be comma-less, but in order for it to be easily usable (i.e. base64url) the encoding will only increase the string length.

The cookie transport is great for having the interactions read and resolved by a system other than the oidc-provider, outside of it's node process. I'll see how it easy it would be to re-use the session adapter and only store a cookie with the interaction detail session id.

**Comment by thomas-lee** [comment]
Thanks for your update.

I am not sure how firewall truncated since we will also added some cookies apart from the provider's cookies. 

It becomes very long and I guess it reaches the default firewall limit and truncates the cookies and thus fail to parse the json later.

I am upgrading from 0.7.X to 1.15.X, and waiting for your version 2.

thanks

**Comment by panva** [comment]
You should still ask that firewall doesn't cut the cookies. The JSON content is properly handled by all browsers and web servers, don't see why the support team would need to have an issue with it ;)

**Comment by panva** [comment]
[2.x](https://github.com/panva/node-oidc-provider/commit/5c4e0b4ad1510f5da4bd4118870bc5110b6b5061) uses the Session adapter instance to create short lived sessions and store the details there. The interaction helpers have been changed to return a Promise and load these sessions based on the cookie from the request. the cookie now only contains a reference. PSA, please sign your cookies, setup your cookie signing keys.
