### ISSUE TITLE
Paseto needs node 16+

### ISSUE THREAD

**Issue by DrogoNevets** [panva/node-oidc-provider#1125]
### What happened?

When trying to install dependencies `paseto` throws an error declaring the engine need is 16+
but `node-oidc-provider` only supports upto LTS (currently 14)

### Version

7.8.0

### Node.js version

16.10.0 & 14.18.0

### Reproduction & Logs

create new project 
`yarn add node-oidc-provider`
errors thrown

`yarn install` output
![Screenshot 2021-10-05 at 13 49 32](https://user-images.githubusercontent.com/1665375/136025684-30dc1750-6933-46aa-ac8e-c47ef9314641.png)

`yarn add paseto` output
![Screenshot 2021-10-05 at 13 50 47](https://user-images.githubusercontent.com/1665375/136025909-97d8d826-431c-41b6-9d1f-245e22b8bf6b.png)

### 

- [X] I have provided a gist or a public repo which can be cloned, installed and ran locally in order to reproduce the bug in the textarea above.
- [X] I have searched the issues tracker and discussions for similar topics and couldn't find anything related.
- [X] I have searched the [FAQ](https://github.com/panva/node-oidc-provider/blob/v7.x/docs/README.md#faq) and couldn't find anything related.
- [X] I agree to follow this project's [Code of Conduct](https://github.com/panva/node-oidc-provider/blob/main/CODE_OF_CONDUCT.md)

**Comment by panva** [comment]
`paseto@3` is an optional dependency of oidc-provider, that means it does not block installs when engine checks fail, this goes for both `npm` and `yarn`.

```
❯ node -v
v14.18.0
❯ yarn add oidc-provider
yarn add v1.22.11
info No lockfile found.
[1/4] 🔍  Resolving packages...
[2/4] 🚚  Fetching packages...
info paseto3@3.0.1: The engine "node" is incompatible with this module. Expected version ">=16.0.0". Got "14.18.0"
info "paseto3@3.0.1" is an optional dependency and failed compatibility check. Excluding it from installation.
[3/4] 🔗  Linking dependencies...
[4/4] 🔨  Building fresh packages...

success Saved lockfile.
success Saved 86 new dependencies.
```

Installing paseto directly is a different story, but for oidc-provider, there's nothing wrong, nothing to be done.
