### ISSUE TITLE
JWT access tokens are not saved upon login

### ISSUE THREAD

**Issue by aleehedl** [panva/node-oidc-provider#1127]
### What happened?

Trying to use `userInfo` endpoint with JWT access tokens but does not seem possible.

Just by looking into the code, these lines call `upsert` only if payload exists:
https://github.com/panva/node-oidc-provider/blob/d7a5ba5ba191d5af8e4bed9449cbb43a3d5a1619/lib/models/base_model.js#L59-L62

And the function `getValueAndPaylod` of format `jwt` never returns field `payload`. In order to use the `userInfo` endpoint the access token should be persisted.

### Version

7.8.0

### Node.js version

14.7.3

### Reproduction & Logs

Configuration with userinfo and jwtUserinfo features enabled. Log in, then use the `userInfo` endpoint with  header `Authorization: Bearer <access-token>`, which always returns:

```
{
    "error": "invalid_token",
    "error_description": "invalid token provided"
}
```

### 

- [X] I have provided a gist or a public repo which can be cloned, installed and ran locally in order to reproduce the bug in the textarea above.
- [X] I have searched the issues tracker and discussions for similar topics and couldn't find anything related.
- [X] I have searched the [FAQ](https://github.com/panva/node-oidc-provider/blob/v7.x/docs/README.md#faq) and couldn't find anything related.
- [X] I agree to follow this project's [Code of Conduct](https://github.com/panva/node-oidc-provider/blob/main/CODE_OF_CONDUCT.md)

**Comment by panva** [comment]
@aleehedl this is the intended behaviour, a JWT access token is issued with an audience (resource indicator) other than the userinfo endpoint. It is not desired for resource servers to be able to turn to the UserInfo endpoint with such token and get the information that was released for the RP. UserInfo is a resource for the RP, not the RS.
