### ISSUE TITLE
Custom claims from request parameter JWT

### ISSUE THREAD

**Issue by r1ch** [panva/node-oidc-provider#113]
Filip,

Thanks for this fantastic library!

**What I'm trying to achieve**
I want to take a JWT as a request parameter to the  `/authorization` endpoint and have custom claims (within the JWT) propagated to the stored AccessToken.

**What I've tried**
I've looked at adding custom claims per the documentation [here](https://github.com/panva/node-oidc-provider/blob/master/docs/configuration.md#configuring-available-claims)

And I have sent in a JWT per [the OICD spec](http://openid.net/specs/openid-connect-core-1_0.html#RequestObject)

This works for the acr_values - I see these exposed as `id_token.acr` on `provider.AccessToken.find()`. Which means that the library is successfully decoding the JWT, but then drops/masks the additional non-standard claims (as designed).

(My JWT payload)
```
"iss":"whoever",
...
"acr_values": "xxx:yyy:zzz",
"claims": {
  "id_token": {
    "intent_id": {
      "value": "urn:org:intent:123ABCXZ",
      "essential": true
    }
  }
}
```

These are for scopes 'read' and 'write'
I've tried to add this to the claims config that initialises the provider:
```
const config = {
  features:{
    request: true
  }
  claims:{
    id_token:["read","write","intent_id","value"],
    read:["intent_id"],
    write:["intent_id"],
    intent_id:null
  }
}

const oidc = new Provider(issuer,config)
```
(Yes you can see I've tried every combination I could think of!)

Am I barking up the wrong tree - how should I tell the library that the claims.id_token.intent_id should be stored?

Thanks again for all the hard work that's gone into the library and thanks in advance for your help.

Rich

**Comment by panva** [comment]
Hey @r1ch, it is not intended (both spec or library) behavior that `claims` value or values you pass in are returned by the endpoints. The value and essential properties aim to provide necessary input to your custom user interactions. That being said i understand the what you're trying to do and here's how you might do it (albeit you must consider the claims parameter can be modified by users themselves, unless provided as part of a signed request).

1) config
```
const config = {
  features:{
    request: true
  }
  claims:{
    // id_token:["read","write","intent_id","value"], < this does nothing, or do you really want an "id_token" scope?
    read:["intent_id"], // you intend to have read as a scope? fine
    write:["intent_id"], // you intend to have write as a scope? fine
    intent_id:null // if you have the above two lines this one is not necessary.
  }
}
```

2) have the claims parameter part of your signed request, but beware a malicious user may still remove the signed request and put any parameters in the query.

3) findById
findById that you configure for the library to get user claims gets the request context bound to this (in 1.x). So what you need is to dig through the context and find your original claims from the request and return them together with your actual user info. The value of the claims parameter is stored internally for each token that needs it (auth code, refresh token and access token) so it's just about getting to the token instance. I think what's missing a common place in the oidc context where the loaded token would be referenced, saving you the trouble of having to load it yourself.

Are you following my train of thought?

**Comment by panva** [comment]
Your `findById` gets called from several places, the koa `ctx` is always bound to this.

1) called during authorization request
for implicit/hybrid response types where id token is returned by the endpoint, your claims object (unparsed in some scenarios) is accessible from `ctx.oidc.params.claims`

2) during userinfo calls
Your claims object is accessible from `ctx.oidc.accessToken`

3) during authorization_code grants
the claims object is bound to the code, but that one is not bound to a ctx (yet, will do in some releases to save you an unnecessary query), but you get the code in `ctx.oidc.params.code` and you may load it using `provider.AuthorizationCode.find(ctx.oidc.params.code)`, the resolved AuthorizationCode object has a `claims` property

4) during refresh_token grants
same as above only instead of `AuthorizationCode` and `code` param use `RefreshToken` and `refresh_token`.

**Comment by r1ch** [comment]
Thank you for such a quick response!

I need to digest this a little and write some code ;)

My use case for interrogating the claims parameter is during an authentication middleware (for express...  rather than koa sadly) but very similar.

Currently that's where I do the provider.AccessToken.find() - a two step findById sounds like a better approach.

**Comment by panva** [comment]
The point is the claims is then actually returned by the userinfo response and is in an id token. You don't need to then do any token finding and can separate your authorziation server from your resource servers that you cover by these tokens.

**Comment by r1ch** [comment]
OK - I feel like I'm getting there slowly!

As you say spec suggests we don't return claims in the userinfo etc. (thanks for pointing that out)

Is there anyway to access the claims that were presented as a signed JWT to /authorize when I'm in the context of user interaction (e.g. in the handler for /interaction/:grant). I can see the claims in the cookie - but is that the right place to be accessing them?

Rich

**Comment by r1ch** [comment]
Doh! 

I've only just understood that findById is an injectable function in the config. Thanks - that's very neat! Per [this](https://github.com/panva/node-oidc-provider/blob/master/docs/configuration.md#accounts) if google directs anyone else here.

**Comment by panva** [comment]
If you're going to be sending in claims parameter like `{"id_token":{"intent_id":"123"},"userinfo":{"intent_id":"123"}}`, then in order for the library to return the intent_id claim it needs to be returned by the userinfo's struct claims method, example below that shows how to pull the data you want from the tokens internal metadata.

```js
  async findById(id) {
    const ctx = this;
    return {
      accountId: id,
      async claims() {
        const acc = { sub: id };
        if (ctx.oidc.accessToken) {
          console.log(ctx.oidc.accessToken);
          // acc.intent_id = ...;
        } else if (this.oidc.params.code) {
          const code = await provider.AuthorizationCode.find(this.oidc.params.code);
          console.log(code.claims);
          // acc.intent_id = ...;
        } else if (this.oidc.params.refresh_token) {
          const token = await provider.RefreshToken.find(this.oidc.params.refresh_token);
          console.log(token.claims);
          // acc.intent_id = ...;
        } else if (this.oidc.params.claims) {
          console.log(this.oidc.params.claims);
          // acc.intent_id = ...;
        }
        return acc;
      },
    };
  },
```

**Comment by panva** [comment]
> I've only just understood that findById is an injectable function in the config. Thanks - that's very neat!

How else would you have the account and it's claims returned from your environment?!

**Comment by panva** [comment]
2.x will come with e39e206dd0e4cbf703e536b232f2beaa5373996f that pushes the related token to the findById as a third param (see [2.x changelog](https://github.com/panva/node-oidc-provider/blob/5c4e0b4/CHANGELOG.md) for the other breaking changes). For 1.x see the above example. But please beware the signed request can always be removed by a malicious user and replaced with a plain claims parameter, you must treat this as user input then a properly sanitize and validate in other places.

**Comment by r1ch** [comment]
Thanks for all your help @panva

**Comment by panva** [comment]
@r1ch you are welcome, if you encounter issues please don't hesitate to open tickets here, if you just want support / help reach me via email (within reason please)
