### ISSUE TITLE
id_token from authorization code flow does not have claims

### ISSUE THREAD

**Issue by arunkarepu** [panva/node-oidc-provider#1132]
### What happened?

I tried running your example and registered two clients one with implicit flow and another with authorization code flow 
`clients: [
    {
      client_id: 'authcode',
	  client_secret: 'codesecret',
      grant_types: ['authorization_code'],
      response_types: ['code'],
      redirect_uris: ['https://testapp/signin-oidc'],
      token_endpoint_auth_method: 'client_secret_basic',
      post_logout_redirect_uris: ["https://testapp/signin-oidc"]
    },
	{
      client_id: 'impclient',
	  client_secret: 'tokensecret',
      grant_types: ['implicit'],
      response_types: ['id_token'],
      redirect_uris: ['https://testapp/signin-oidc'],
      token_endpoint_auth_method: 'client_secret_basic',
      post_logout_redirect_uris: ["https://testapp/signin-oidc"]
    }
  ]`

Then I used below url to start the authorization code flow
http://localhost:3000/auth?client_id=authcode&redirect_uri=https://testapp/signin-oidc&response_type=code&scope=openid email profile&code_challenge=hM6DWdhr58Kamj4BdblvlLqsjnhuVQFZFQOd7YTkq88&code_challenge_method=S256&nonce=123&state=321

which after successful authentication, redirected to below url with code:
https://testapp/signin-oidc?code=diIv5W1f6E4IkjJPvp5kPnyLqSLu6qeBLNBDnPdd_1T&state=321

To get id_token, I executed below url 
`
POST http://localhost:3000/token
Content type: application/x-www-form-urlencoded
grant_type:authorization_code
client_id:authcode
client_secret:codesecret
code:diIv5W1f6E4IkjJPvp5kPnyLqSLu6qeBLNBDnPdd_1T
redirect_uri:https://testapp/signin-oidc
code_verifier:BTzZkoscsISp8dTLEYBN5jlXgz3HMG1s99aRZpGp-_A
`
and the response I got is
`{
    "access_token": "3pc0NTji10mZFkN6zDgUvd2TTFdlXXqm9sXFQWE3iM3",
    "expires_in": 3600,
    "id_token": "eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCIsImtpZCI6InIxTGtiQm8zOTI1UmIyWkZGckt5VTNNVmV4OVQyODE3S3gwdmJpNmlfS2MifQ.eyJzdWIiOiJhcnVuIiwibm9uY2UiOiIxMjMiLCJhdF9oYXNoIjoiSFB1RkhPVHdkTmVDMjVBTHNhUGtHZyIsImF1ZCI6ImF1dGhjb2RlIiwiZXhwIjoxNjM0MjM5MDIyLCJpYXQiOjE2MzQyMzU0MjIsImlzcyI6Imh0dHA6Ly9sb2NhbGhvc3Q6MzAwMCJ9.VLf7Ifh1sczaxsuAbfLl9UwdC9HthAZI3p2pdFqpnSchjzbgrCCPzkkksWpUmY8gtLA9fkc6KKzUJfJzFQxkcwVUDMUenCFRUumI_nvmfjCD2bBQYQimsOFo_g96ztT0DMwf4O0nAQdW-1kgPhFFTjv4_mgLgbXn_mUJ2Je1fPgCSFZWGMDECJ_h7oDQWt6ecgWQk61EuiBbrggn0XRgsiI2yNb1xePGb4cEJiMjWOWpBtsHfQXwBk2iJgNAblNx3DQRTV6kklU46-bpez77F6-bV7F4n-93clekcFFarmTGhF_GlkbmRePNG9w5Xr-vFr-Zzf_u-MxV4AoR3ld8Ng",
    "scope": "openid email profile",
    "token_type": "Bearer"
}`

When I checked it in jwt.io, all I got is
`{
  "sub": "arun",
  "nonce": "123",
  "at_hash": "HPuFHOTwdNeC25ALsaPkGg",
  "aud": "authcode",
  "exp": 1634239022,
  "iat": 1634235422,
  "iss": "http://localhost:3000"
}`

But expected is

`{
  "sub": "arun",
  "email": "johndoe@example.com",
  "email_verified": false,
  "birthdate": "1987-10-16",
  "family_name": "Doe",
  "gender": "male",
  "given_name": "John",
  "locale": "en-US",
  "middle_name": "Middle",
  "name": "John Doe",
  "nickname": "Johny",
  "picture": "http://lorempixel.com/400/200/",
  "preferred_username": "johnny",
  "profile": "https://johnswebsite.com",
  "updated_at": 1454704946,
  "website": "http://example.com",
  "zoneinfo": "Europe/Berlin",
  "nonce": "123",
  "s_hash": "jSPPbIboNKeqbt7VTCbOKw",
  "aud": "impclient",
  "exp": 1634238927,
  "iat": 1634235327,
  "iss": "http://localhost:3000"
}`

### Version

v7.8.1

### Node.js version

v14.17.3

### Reproduction & Logs

https://github.com/panva/node-oidc-provider/tree/main/example

### 

- [X] I have provided a gist or a public repo which can be cloned, installed and ran locally in order to reproduce the bug in the textarea above.
- [X] I have searched the issues tracker and discussions for similar topics and couldn't find anything related.
- [X] I have searched the [FAQ](https://github.com/panva/node-oidc-provider/blob/v7.x/docs/README.md#faq) and couldn't find anything related.
- [X] I agree to follow this project's [Code of Conduct](https://github.com/panva/node-oidc-provider/blob/main/CODE_OF_CONDUCT.md)

**Comment by panva** [comment]
https://github.com/panva/node-oidc-provider/blob/main/docs/README.md#id-token-does-not-include-claims-other-than-sub
