### ISSUE TITLE
HTTPS Redirect even if HTTP redirect is set

### ISSUE THREAD

**Issue by NilsBaumgartner1994** [panva/node-oidc-provider#1140]
### What happened?

Since i was developing local on my computer with "Directus" as my Backend-CMS, it sets the redirect_uri to an http (since local on my computer). The OIDC-Provider works in de Express-Example after configurating the allowed redirect_uris but, unfortunatly it redirects automaticly to https instead to the given http.

### Version

latest

### Node.js version

v14.15.4

### Reproduction & Logs

A docker-compose file can be given if needed.

### 

- [ ] I have provided a gist or a public repo which can be cloned, installed and ran locally in order to reproduce the bug in the textarea above.
- [X] I have searched the issues tracker and discussions for similar topics and couldn't find anything related.
- [X] I have searched the [FAQ](https://github.com/panva/node-oidc-provider/blob/v7.x/docs/README.md#faq) and couldn't find anything related.
- [X] I agree to follow this project's [Code of Conduct](https://github.com/panva/node-oidc-provider/blob/main/CODE_OF_CONDUCT.md)

**Comment by panva** [comment]
This looks like a question, one that could use more clarity. Please start a Q&A Discussion for questions, unless you have a bug to report.

**Comment by NilsBaumgartner1994** [comment]
https://github.com/panva/node-oidc-provider/discussions/1142
