### ISSUE TITLE
2.0.x branch

### ISSUE THREAD

**Issue by maitscha** [panva/node-oidc-provider#116]
Hi!

First of all: Congrats to this great library!

I'm using your library for a minor modified OIDC Provider prototype. I have seen that the 2.0 release is on its way, so I'm asking if the current version v2.0.0-pre.3 can already be used without major drawbacks. I'm using node 8.1 with async/await, so the 2.0 release would perfectly fit in my current project setup. I know that it's a pre-release, so bugs are welcome ;) Is there a planned release date for 2.0?

Regards

**Comment by panva** [comment]
Hi @maitscha, thank you!

pre.3 still does not have some big breaking changes in place [made last few days](https://github.com/panva/node-oidc-provider/compare/v2.0.0-pre.3...e39e206), i was hoping to hit 2.0 with https://tools.ietf.org/html/draft-ietf-oauth-native-apps enabled by default when it gets finalized. But with the recent ios11 development that one might still undergoe some changes. No date yet, gotta finish test coverage, properly test the last big changes and go through all docs to reflect changes. Will pull oauth-native-apps out again, and release that one by default enabled in 3.0 with no other breaking changes.

**Comment by maitscha** [comment]
Ok, that sounds like pre.3 can already be used. I have read that the interaction cookie management has some major improvements in v3, so I think it's worth to switch to v3.

**Comment by panva** [comment]
no no, that WILL already land in v2.0, you will have to make adjustments switching from pre to an actual tag

**Comment by maitscha** [comment]
Ok, great to hear that the improved cookie management is already in v2. Thank you very much for the info!!
