### ISSUE TITLE
Extra params are not returning session/end API

### ISSUE THREAD

**Issue by satishynitb** [panva/node-oidc-provider#1168]
Extra params are not returning while hitting session/end API.

I want to add one query parameter in session/end api like we have id_token_hint and post_logout_redirect_uri.
(request example: curl --location --request GET 'https://abc.com/session/end?post_logout_redirect_uri=https://www.google.com&id_token_hint=eyJhbGciOiJvOmbqUR5IJsYT6-Q&extra_sample_key=ywiuyriuyweuiyr6283682eeeeee' )

That (extra_sample_key) query parameter i want to fetch in pre-processing middleware of session/end api. 
Provider.use(async (ctx, next) => {
          // I was tying to access using "ctx.request.query" and "ctx.req.query" not able to access it. Even that extra parameter is not present in ctx.url 
              parameter
          if (ctx.path === '/session/end') {
           // Here I want to access extra query parameter that i am sending.
          }
          await next();
        });

using "oidc-provider": "6.18.2"  and "express": "4.17.1"

**Comment by panva** [comment]
This is not worthy of an issue, kindly open a Q&A discussion with details instead.
