### ISSUE TITLE
Question: Ensure interactionFinished returnTo URL has correct path

### ISSUE THREAD

**Issue by r1ch** [panva/node-oidc-provider#117]
I'm running a test deployment in AWS - behind their API gateway so at:

`issuer = "https://long.aws.url/alpha"`

The interactionUrl config function : 
```
interactionUrl = "/interaction/" +  this.oidc.uuid
```
or
```
interactionUrl = issuer + "/interaction/" + this.oidc.uuid
```

Will yield relative or absolute paths -- both work fine `https://long.aws.url/alpha/interaction/...` for the redirection to start the interaction. However the library puts the respondTo URL in the cookie to know how to signal the end of the interaction when we call `interactionFinished()` and misses out the `/alpha`. How should I be ensuring that this URL also has the `/alpha` mountPath?

**Comment by panva** [comment]
Hey @r1ch, i tested deploying oidc-provider using https://www.npmjs.com/package/serverless-http a while back, deployment using https://serverless.com with a catch-all route on api gateway and had no such issues.

Just get a valid certificate and use that one in your api gateway pointed directly to /alpha

**Comment by panva** [comment]
The problem is that the /alpha does not reach the node process as a path, using a custom cert and domain gets around the /alpha being in the url.

**Comment by r1ch** [comment]
Ah - that makes sense - thank you.

**Comment by panva** [comment]
Even had a dynamo adapter and a cloudformation template to set everything up. Not sure where that went.

**Comment by r1ch** [comment]
I also have a dynamo adapter :) god I hate the DynamoJSON format - the less I have to look at the records on the DB the better. 

Anyway - you've been a great help - can I make a beer fund donation?

**Comment by panva** [comment]
Glad to help, just use the library and let me know of your scale and successes ;)
