### ISSUE TITLE
end_session.error being emitted as server_error

### ISSUE THREAD

**Issue by AlyaEru** [panva/node-oidc-provider#1172]
### What happened?

Hi! I am using oidc-provider for my koa application which supports the authorization code flow and logout.
I am trying to improve the logging for logout issues (particularly an issue where `id_token_hint` is occasionally missing from session end requests), so I added a listener for `end_session.error`. However, the missing `id_token_hint` error is not triggering the `end_session.error` listener. I turned on debug logging for the service, and it looks like this issue is getting treated as a `server_error` (without the original error details, just "oops something went wrong") rather than an `end_session.error`:
```
oidc-provider:error uid=pcO6fPN0gYgc6xSw7Tbqz path=/session/end method=GET error={ error: 'invalid_request', error_description: 'post_logout_redirect_uri can only be used in combination with id_token_hint' } detail=undefined +0ms
oidc-provider:server_error uid=pcO6fPN0gYgc6xSw7Tbqz path=/session/end method=GET error={ error: 'invalid_request', error_description: 'post_logout_redirect_uri can only be used in combination with id_token_hint' } +0ms
oidc-provider:server_error:trace {
oidc-provider:server_error:trace   error: 'invalid_request',
oidc-provider:server_error:trace   error_description: 'post_logout_redirect_uri can only be used in combination with id_token_hint'
oidc-provider:server_error:trace } +0ms
```
I assume this error is supposed to be emitted as a `end_session.error` with error details? It would be really helpful for my error logging if it were.
Note: I think the error is also getting thrown rather than just emitted as a `server_error`.
It looks like this issue was brought up in this issue https://github.com/panva/node-oidc-provider/issues/66 as an aside, but not resolved.

### Version

6.29.9

### Node.js version

v14.15.5

### Reproduction & Logs

Reproduce:
run a service that uses oidc-provider for logout
try to log out without providing an `id_token_hint` in the end session request
The error will be thrown as a server_error rather than an end_session.error

### Required

- [X] I have provided a gist or a public repo which can be cloned, installed and ran locally in order to reproduce the bug in the textarea above.
- [X] I have searched the issues tracker and discussions for similar topics and couldn't find anything related.
- [X] I have searched the [FAQ](https://github.com/panva/node-oidc-provider/blob/v7.x/docs/README.md#faq) and couldn't find anything related.
- [X] I agree to follow this project's [Code of Conduct](https://github.com/panva/node-oidc-provider/blob/main/CODE_OF_CONDUCT.md)

**Comment by panva** [comment]
Despite there being no gist or public repo for repro. I am unable to reproduce neither on v6.29.9 nor on the latest v7.x

There are tests in place that check the error emitted is in fact `end_session.error` and my local deployment confirms that behaviour.

**Comment by AlyaEru** [comment]
Hi, apologies for leaving out the gist, I thought this would be easily reproducible but it turned out to be far more complicated than I thought.
It turns out my issue was happening because my provider implements `renderError` and has it throw the error. Because of the ordering of [error_handler.js](https://github.com/panva/node-oidc-provider/blob/9da61e9c9dc6152cd1140d42ea06abe1d812c286/lib/shared/error_handler.js#L52), if renderError throws, the oidc-provider error emitting doesn't happen. For reasons obscure to me, the thrown error has its details removed by oidc-provider before the error reaches my service's error handling middleware.
Now that I know this I can change the behavior of `renderError` to fit my need.
It would be great if you guys could add more documentation about error handling, I had to take a pretty deep dive into the oidc-provider code to figure this out.
