### ISSUE TITLE
OP Session Management

### ISSUE THREAD

**Issue by ghalimoums** [panva/node-oidc-provider#118]
Hi @panva ,
I have an OpenID Connect provider running using node-oidc-provider with express and i also configured a relying party using Passport and the passport-openid-connect strategy. I also have a passport local strategy to start a session directly into the OP (using the same mongoDB collection). What i would like to do is when a user logs into the RP using the openid-connect strategy, he would also be logged into his account on the OP. Just like the Facebook Login API, if you sign-in in a service using facebook connection, then your facebook session would be open. 
Is it possible to achieve this session synchronization using node-oidc-provider ?

**Comment by panva** [comment]
This is definitely doable but beyond the scope of what i have done so far - just use the same session cookie name and signi keys I guess?

**Comment by ghalimoums** [comment]
Thank you for your answer. I wasn't able to look at this until now. 
Should I use my own memory adapter to store sessions (mongodb for example) like you mentioned [here](https://github.com/panva/node-oidc-provider/blob/master/docs/configuration.md#persistance) ? Because I cannot access the content of the basic adapter (lru-cache) from my express code.

**Comment by panva** [comment]
absolutely! in fact you get warned in console that you should provide your own adapter!

**Comment by vietlongn** [comment]
Hi @ghalimoums,
I'm also running into this situation. Did you archived it?
