### ISSUE TITLE
By reference access_token (GUID)

### ISSUE THREAD

**Issue by jorgenkg** [panva/node-oidc-provider#119]
*This is not an issue*, but perhaps a feature request.

First of, I love this project! I've played around a lot with it, at it has helped me to understand how OAuth and OpenID Connect actually work. Great job!

~Next, I was wondering if this library could support "by reference" session tokens without too much work? This would save us for overly long access tokens and be more secure. (Rather than encryption).~

I don't know how I could miss that they already are opaque

**Comment by panva** [comment]
yup, i only use JWT as a mechanism for serializing the internal token metadata but return the opaque values (kid compacted with the formed sig in 1.0, kid compacted with a random value in 2.0 - getting rid of the integrity store)
