### ISSUE TITLE
OP initiated back-channel logout? + Explanation on grantId

### ISSUE THREAD

**Issue by slavab89** [panva/node-oidc-provider#120]
I'm currently trying to implement a password-reset functionality for my accounts.
After some "hacking" i was managed to get something working that resets the password of an account (Out of the scope of this project as it relates only to account management)
I would like to be able to log out (both from OP and RP) the account that did a "reset password" and force him to log in again.

I cant find a way to do that since i only have his account information (No session since he might not be logged in, no clientId etc.)

I was wondering if it would be possible to save his sessionId/grantId on the account itself (after a successful grant/authentication) as a way to find that information later on but i didnt find any relation between the uuid that is saved on the `session`, or on the `authorizations` inside and the `grantId` that's saved in the access token, are they even related somehow?
Moreover, what is the `grantId` that's present in the different tokens? I know that it is later used for `revocation` (To delete all previously created tokens too) but i couldnt find a place where its shared between different token creations..

**Comment by panva** [comment]
> I cant find a way to do that since i only have his account information (No session since he might not be logged in, no clientId etc.)

you have access to your persistence store > the account id is stored in the session object > index your storage by this field and drop the object when you want to remove all OP sessions for an account when needed.

`grantId` is just an internal id i generate during every authorization so that i can keep track of the token chain that came out of this authorization.

**Comment by slavab89** [comment]
And i guess i also can save the account on each token that's created and then drop all the tokens when a reset password happens. :)

I do need however to notify all RP's that the session is no longer valid. I can copy the code that does the back-channel logout but was wondering if i can somehow integrate into your code.

And another question while we're at sessions: In each session's authorizations object, you're saving a `sid` value for each connected client. Is this sid used in any place? What does it state for?

**Comment by panva** [comment]
> What does it state for?

keeping track of the sessions for touched RPs > http://openid.net/specs/openid-connect-session-1_0.html

> I do need however to notify all RP's that the session is no longer valid. I can copy the code that does the back-channel logout but was wondering if i can somehow integrate into your code.

That's what backchannel-logout is for > As i said, you can call the `Client#backchannelLogout` instance method yourself.

**Comment by slavab89** [comment]
Got it!

Every time i'm getting stuck at something, and every time i'm trying to dig into the code of the project (Which contains a lot of logics!!) and every time it allows me to make things work without the need for you to change something or expose some special API... amazing!! 😄

**Comment by panva** [comment]
It's almost like someone wrote this library with so many use cases in mind... ;)

**Comment by slavab89** [comment]
totally :)

Now i'm on the RP's side. I need a way to validate and decrypt the JWT `logout_token` that i'm receiving there.
I've noticed that oidc-client does not have this logic out of the box. Could you direct me to the requirements that i would need in order to do this? I see that the header of the token contains `alg` and `kid` which i assume should help validate the signature

**Comment by panva** [comment]
http://openid.net/specs/openid-connect-backchannel-1_0.html#LogoutToken

**Comment by slavab89** [comment]
Cool!
So i've ended up writing almost the same function as [verifyIdToken](https://github.com/panva/node-openid-client/blob/master/lib/client.js#L385) like you did, just that there is no `exp` in the token so your function gives an error or missing param (And basically its "private").

**Comment by slavab89** [comment]
> keeping track of the session states for touched RPs

Regarding this.. Is it possible to transfer this generated sid to the RP? as part of something (except the backchannel logout request of course)?
I need to find the user's session based on the token that i get.
I've seen that there is the `check_session` way but this requires browsers so i guess it wont work

**Comment by panva** [comment]
as per spec `sid` is an ID Token claim when sessionManagement feature flag is enabled

**Comment by slavab89** [comment]
😄 !!
So for anyone that gets here or is interested. This is what i ended up doing:
On the RP side:
* Once a user successfully logs in, i save a mapping between oidc generated `sid` (Can be taken out from the id_token or token introspection) and RP generated `sessionId`
* Have a `backChannelLogout` endpoint handler that validates the received logout_token and then gets the RP generated `sessionId` based on the received `sid` value, deletes that and then deletes the `sessionId` entry itself

On the OP side:
* For a regular RP initiated logout flow, works out of the box
* Add a handler for password reset that finds all the sessions of an account > get the clients based on `authorizations` > trigger a backChannelLogout of each of them (Would trigger the second point of the RP) > destroy all those sessions.

**Comment by panva** [comment]
He hey ;) You've implemented back-channel logout ;) congrats
