### ISSUE TITLE
How could I update access token life dynamically

### ISSUE THREAD

**Issue by haoruiqian** [panva/node-oidc-provider#122]
I'm using oidc-provider 1.15.11, the life of access/refresh token is configurable in my system, so it might change during oidc server is running, I know we can configure token life by specify "ttl.AccessToken" in configuration when start oidc server, then how could I update the token life value without restart oidc server when admin change it in my system?

**Comment by panva** [comment]
The current configuration scheme does not allow for re-configuration during runtime, this is something i wish to tackle at some point, it's just not a priority. In distributed setup a rolling restart gives you the option to change configuration process by process.

**Comment by haoruiqian** [comment]
Thanks @panva , what do you mean by "rolling restart"? This will restart oidc provider itself, or need to restart whole server? If it's oidc provider itself, then how to do that?

**Comment by panva** [comment]
I mean, restart your process with the new conf in place.
