### ISSUE TITLE
Refresh token for password grant type

### ISSUE THREAD

**Issue by haoruiqian** [panva/node-oidc-provider#123]
Following https://github.com/panva/node-oidc-provider/blob/master/docs/configuration.md#custom-grant-types I can add support for password grant type, and generate refresh token as well inside the handler, but how could I use it to get a new access token?

I created a client which supports grant types "password" and "refresh_token", but it violated the rule https://github.com/panva/node-oidc-provider/blob/master/lib/helpers/client_schema.js#L220, refresh_token grant type must be used in combination with authorization_code grant type, so I added authorization_code to the supported grant types as well, then it required redirect_uris, which I didn't want to set because this client was just for password grant type and should not have redirect_uris.

Then how could I use this refresh token to get a new access token?

**Comment by panva** [comment]
Hi @haoruiqian,

I released 1.15.12 where i just lifted the validation - please keep in mind the use of password grant type is discouraged, hopefully you need it to protect a confidential and secure component of your IDP, otherwise password scraping by clients (such as as confidential websites, let alone public native apps!!!) is considered a bad practice

**Comment by haoruiqian** [comment]
Thanks @panva , I know that it's discouraged, but it's one requirement of my system.

**Comment by rakeshostwal** [comment]
@haoruiqian how did you generate the refresh token in the password grant type using Handler?

**Comment by panva** [comment]
Oh come on! Stop using ROPC. For real, If you need it today something's wrong!

https://youtube.com/watch?v=qMtYaDmhnHU
https://youtube.com/watch?v=zuVuhl_Axbs

**Comment by haoruiqian** [comment]
@rakeshostwal , the argument of handler is the oidc provider instance,  the instance 
has reference to RefreshToken class https://github.com/panva/node-oidc-provider/blob/master/lib/provider.js#L124, then you may create a refresh token using `new instance.RefreshToken(...)`.
