### ISSUE TITLE
how to use in koa 2

### ISSUE THREAD

**Issue by adnan-kamili** [panva/node-oidc-provider#125]
The example given is for express and koa 1.x. Trying it with koa 2 fails with error:

`error: middleware must be a function`

Following is the sample code:

```javascript
async function start() {
    try {
        // Check the db connection
        await sequelize.authenticate();
        await sequelize.sync({ force: false });

        // Initialize oidc
        await oidc.initialize({ clients });
        router.get('/op', koaConvert(oidc.app));
        app.use(router.routes()).use(router.allowedMethods());

        // app.use('/op', oidc.app);

        // Start the server
        app.listen(appConfig.port);
        Logger.info("Environment:", process.env.NODE_ENV);
        Logger.info(`Listening on http://localhost:${appConfig.port}`);
    } catch (error) {
        Logger.error(error.message);
    }
}
```

**Comment by panva** [comment]
well of course it fails ;) v1 uses koa1 and offers to run on lts versions of node. If you want koa2 then work around the fact that you can get a plain node callback with `app.callback` and somehow mount that one.

You might also use the `next` release on npm/branch on github which is koa2 based and is pending some changes. The ETA currently is unknown.

**Comment by adnan-kamili** [comment]
Thanks for the quick reply. I tried the next release, but again the same error:

`router.get('/op', oidc.app);
`
"get `/op`: `middleware` must be a function, not `object`"

**Comment by panva** [comment]
stacktrace please...

**Comment by adnan-kamili** [comment]
Following worked:

app.use(mount('/op', oidc.app));

I should have mounted the oidc koa app instead of using it as a middleware

**Comment by panva** [comment]
Great, so using `next` and mounting koa app. perfect.

**Comment by panva** [comment]
FYI there still may be changes to 2.x so keep an eye on the changelog between tags using the github compare views

**Comment by adnan-kamili** [comment]
Are the docs being updated for next version, is their any ink for the next docs?

**Comment by panva** [comment]
the docs on the release tags are up to date, hence you can always use the github compare REF feature to see the diffs

- [2.0.0.pre.3](https://github.com/panva/node-oidc-provider/tree/v2.0.0-pre.3)
- [diff to next](https://github.com/panva/node-oidc-provider/compare/v2.0.0-pre.3...next)

**Comment by adnan-kamili** [comment]
Thanks, I have used following before https://github.com/openiddict/openiddict-core, 

and I expected 

grant_type=password

to be supported by default, but it doesn't look like so. I get 

```
{
    "error": "invalid_client",
    "error_description": "client is invalid"
}
```

Is it planned to be supported.

**Comment by panva** [comment]
[ROPC will not be supported](https://github.com/panva/node-oidc-provider/wiki/FAQ#password-grant-type-ropc) by default, it is not mentioned. 

> I suppose client should be ignored for the above case.

I don't follow, sorry. Every token endpoint call needs to have a client authenticated identified and authenticated first, only then is a check for permitted grant types run.

This library is not a drop in replacement for a complete server providing views models etc. Please read the docs thoroughly, think of this as a protocol implementation rather then a full featured server with user interactions and data models - those are for you to fit in.

**Comment by panva** [comment]
Alright, then you're in the right place 👍 
Yes, it is fixed in the `next` branch, but not in the latest `next` npm release which is still pre.3. It is also fixed in the ^1.0.0 stable release

**Comment by adnan-kamili** [comment]
As I would be using the `next` npm release only, is there any ETA for the fix to be available in next npm, so that I can use it.

**Comment by adnan-kamili** [comment]
Also in latest next docs it still uses generator functions instead of async await

https://github.com/panva/node-oidc-provider/blob/78ee4b8ba7d2da37c0482821fc17698166918b06/docs/configuration.md#custom-grant-types

**Comment by panva** [comment]
It doesn't in next branch. No ETA commited to.

**Comment by adnan-kamili** [comment]
I used the code snippet 

https://github.com/panva/node-oidc-provider/blob/next/docs/configuration.md

but it doesn't seem to have any effect.

       // Initialize oidc
        await oidc.initialize({ clients });
        const parameters = ['username', 'password'];

        oidc.registerGrantType('password', function passwordGrantTypeFactory(providerInstance) {
            return async function passwordGrantType(ctx, next) {
            ...

**Comment by panva** [comment]
I doubt it, seeing how there are [tests present](https://github.com/panva/node-oidc-provider/blob/next/test/custom_grants/custom_grants.test.js) for the custom grant type features.

- do you have a client configured?
- are you authenticated said client?
- does the client have password grant type amongst its grant_types?

**Comment by adnan-kamili** [comment]
As I see in the tests you expect custom grant to be added to the client grant types. But that's not necessarily true for password grant. It doesn't care whether a client exists or not as user is providing it's own username/password itself. The openid-dict for .net core, link I shared above, also does the same, no check for clients in case of password grant

https://github.com/openiddict/openiddict-core/blob/dev/samples/Mvc.Server/Controllers/AuthorizationController.cs

**Comment by panva** [comment]
> It doesn't care whether a client exists or not as user is providing it's own username/password itself.

The resource owner (user) is providing the credentials to a client that talks to the AS. A client MUST exists (to whom would otherwise access tokens be issued to?), and it also MUST authenticate with the AS with one of the available token endpoint auth methods.

This was already way too much involvement from me for a bad practice grant type ;) more on this in [6749](https://tools.ietf.org/html/rfc6749#section-4.3)

**Comment by adnan-kamili** [comment]
As per the spec:

   The authorization server MUST:

   o  require client authentication for confidential clients or for any
      client that was issued client credentials (or with other
      authentication requirements), ...

As mentioned, it is must for confidential clients or if a client was issued client credentials.

 Suppose I want my web api to be used on my web app, so a three legged authentication would be an overkill, and I would use password grant, and client is not confidential too because browser cannot safely store the client credentials, hence their is no point in expecting client credentials from the browser.

**Comment by panva** [comment]
What you're looking for is a cookie kept session, and a form submitted to any custom web app endpoint expecting CSRF, doing Google's hidden captcha > OWASP. ROPC does not provide CSRF, captcha, nothing of the sort. Nothing will prevent an attack from starting brute-forcing your login form if you secure it this way, let alone if you do it from the browser!!!

All token endpoint calls in oidc-provider do require client to be identified and authenticated using it's registered token_endpoint_auth_method (none is supported). I was hoping you're at least running a highly confidential client, like the client behind the aforementioned form. It turns out to be the complete opposite.

**Comment by adnan-kamili** [comment]
Rest API'S using token based authentication is common these days, and token auth is not vulnerable to csrf attack. Brute forcing is prevented by rate limiting.
My rest API will be used by the web app and will be directly invoked by customers for automation purpose requiring client credentials grant type. So if you are using oidc anyways, why not use it for web browser token authentication too using password grant, instead of having two different auth mechanisms. 

I don't understand if other implementations in other languages like dotnet are allowing that, and spec recommends that the client credentials validation in confidential cases, what is the harm in allowing that, i think instead of forcing ones opinion, a library should let the users configure and decide if spec allows that. 

Secondly, in password grant example you are not returning id_token, in openid user is expected to send the openid scope, so Id token should also be returned, else its simply oauth2.

**Comment by panva** [comment]
If you're going to go ahead and justify bad practice and insecure authentication forms by an authorization framework which needs to be profiled to be usable in secure applications then please go ahead. There is also no mention of this grant type in the OIDC profile of OAuth2.0
