### ISSUE TITLE
adapter example for RDBMS databases

### ISSUE THREAD

**Issue by adnan-kamili** [panva/node-oidc-provider#126]
It would be nice to have an adapter example for RDBMS database using any popular orm like Sequelize https://github.com/sequelize/sequelize

**Comment by panva** [comment]
I myself never did one and am not aware of anyone doing so, you may want to try https://gitter.im/node-oidc-provider/Lobby but as far as an issue, i will not be creating an example for a relational DB.

i know of users with adapters for
- mongo (in repo + branched off the one in repo)
- redis (in repo)
- at least two for dynamo db
- an API based adapter
- file based adapter

**Comment by panva** [comment]
i have an example in the works, will reference this once its pushed
