### ISSUE TITLE
scopes in client credentials grant

### ISSUE THREAD

**Issue by fgyara2** [panva/node-oidc-provider#129]
Hi Panva,

Firstly a big Thank You for this awesome library.

I have a question around how scopes are passed around during a client credentials grant.

I have configured a provider so that it supports a couple of custom scopes and configured a client that can use one of those scopes:

```code
const config = {
    features: { 
        clientCredentials: true
    },
    scopes: [ "alpha", "beta"],
    clients: [
        {
          client_id: 'foo',
          client_secret: 'bar',
          redirect_uris: ['https://www.getpostman.com/oauth2/callback'],
          response_types: [],
          scopes: [ "alpha"],
          grant_types: ['client_credentials']
        }
   ]
}
```

Now, when I execute a client credentials grant and try to authenticate `foo` with the scope `beta`, the request still succeeds and I can get an access token issued. I was expecting to receive an error as described in the [OAuth Spec][https://tools.ietf.org/html/rfc6749#section-5.2]

Am I missing something ?

**Comment by fgyara2** [comment]
So I dug in a bit and from what I could gather "scopes" isn't really a valid field in the "client" array.

How do I define the scopes that are available (permitted) for a specific client ?

**Comment by panva** [comment]
Hello @fgyara2, you can't - the client defines the scopes it wants by including them in the client credential grant.

**Comment by panva** [comment]
What you can do is define your own client_credentials grant, using the custom grants feature and put your logic in there while using my definition as a general guideline.

**Comment by mcnijman** [comment]
Is there a reason you don't want to support this out of the box? I think the current flow just skips the authorization part, and grants whatever scope is available if the client is authenticated (and thus allowing access to all resources protected by the OP. The specs (https://tools.ietf.org/html/rfc6749#section-1.3.4) describe it differently, if I understand correctly.

I assume it should not be too hard to implement this, just throwing at the ctx whenever a scope does not match the predefined allowed scopes for the client, somewhere in the getClientCredentialsHandler: https://github.com/panva/node-oidc-provider/blob/60c5b843435056b25ce4938dffc49c753ee44a90/lib/actions/grants/client_credentials.js

**Comment by panva** [comment]
> Is there a reason you don't want to support this out of the box?

The grant is supported out of the box assuming the client is the resource owner, just like the spec describes it. If the other way is what you are expecting then you simply [register a custom grant](https://github.com/panva/node-oidc-provider/blob/master/docs/configuration.md#custom-grant-types) and enforce your IdP policies there. You can use the [referred](https://github.com/panva/node-oidc-provider/blob/60c5b843435056b25ce4938dffc49c753ee44a90/lib/actions/grants/client_credentials.js) impelementation as a base and as you can see it is dead simple implementation.

**Comment by mcnijman** [comment]
Oh I see, thanks for the clarification
