### ISSUE TITLE
Is there any example using mysql?

### ISSUE THREAD

**Issue by hmheng** [panva/node-oidc-provider#130]
Hi there, I saw there is example using mongodb, but is there any step by step guide that showing setup using mysql?

Thanks.

**Comment by panva** [comment]
There is not, this is the [interface](https://github.com/panva/node-oidc-provider/blob/master/example/my_adapter.js) you need to follow, just plug your code there.

**Comment by panva** [comment]
i have an example in the works, will reference this once its pushed
