### ISSUE TITLE
Running into unexpected token when running index.js

### ISSUE THREAD

**Issue by hmheng** [panva/node-oidc-provider#131]
![image](https://user-images.githubusercontent.com/11830387/28120992-4fc3d296-674c-11e7-9b73-c881aaffc7d1.png)

Sorry, im new to node oidc. would appreciate if you can teach me steps by steps.

**Comment by maitscha** [comment]
`node --version` ?

**Comment by hmheng** [comment]
6.10.3

**Comment by hmheng** [comment]
Orh, it requires > 8 for 2.0. sorry

**Comment by maitscha** [comment]
node v6 doesn't support ES6 -> upgrade to node v8

**Comment by panva** [comment]
or use "v1.x" for node < 8
