### ISSUE TITLE
Login and consent confirmation in 2 steps

### ISSUE THREAD

**Issue by maitscha** [panva/node-oidc-provider#132]
Hi!

I would like to know if it is possible to split the login and the consent confirmation (if a session not yet exists) to 2 pages, instead of showing the login page and the confirmation of the consent in a single page.

Was there a reason to use a single page?

**Comment by panva** [comment]
You can use as many steps as you want - it's only that you need to resolve the interaction in one sweep before sending the user back to the resume path.

**Comment by maitscha** [comment]
So, if I split authentication and authorization to two pages, should the first page (the authentication page), how can the authentication page create a session (cookie, DB session, ...). Or just save the login object in the interaction session?

```
const interactionSession = await provider.interactionDetails(req);
interactionSession.login = { ... };
await interactionSession.save(60);
// now return the authorization page
```
