### ISSUE TITLE
Updating client metadata

### ISSUE THREAD

**Issue by mogeda** [panva/node-oidc-provider#133]
Is there any way to modify existing client information like adding extra refirect_uri? I see only retrieving client information is supported so guess I need to handle this in my app. Thanks.

**Comment by panva** [comment]
I see you have two options,

1. handle on your own using any UI and OOB process you define accessing the storage directly
2. using the experimental [RFC7592 - OAuth 2.0 Dynamic Client Registration Management Protocol](https://tools.ietf.org/html/rfc7592) for Update and Delete actions, this one is supported by `oidc-provider` under the `registrationManagement` feature flag - see the readme and configuration pages.

In distributed deployments both options require you to either reload your processes or calling `issuer.Client.cacheClear()` in all of them.

**Comment by mogeda** [comment]
registrationManagement flag, it is! I should read the readme more in detail. Thanks a lot.
