### ISSUE TITLE
Configure port for configuration endpoints when behind proxy

### ISSUE THREAD

**Issue by aldafu** [panva/node-oidc-provider#136]
As others I'm running the provider behind an Nginx. I'm using the default port for the provider, i.e. 3030. Now the problem I cannot seem to figure out is that .well-known/openid-configuration will report endpoints with that port as well. Also e.g. the default logout form will use a URL with default port 3030. How do I tell the provider that it is behind a proxy and should use the port from the proxy?

All I could find was the "proxy = true" setting for koa/express regarding the SSL termination. In my case SSL isn't terminated at Nginx, but still at the provider, but I don't think this is related?

**Comment by panva** [comment]
`proxy = true` is still what you need if the server you are hitting is nginx. And have nginx forward the standard `X-Forwarded-*` headers.

**Comment by aldafu** [comment]
Thanks a lot for the quick reply. It's been the missconfigured ```X-Forwarded``` headers from Nginx.
