### ISSUE TITLE
consider allowing http and localhost with implicit in "dev" mode?

### ISSUE THREAD

**Issue by tony-kerz** [panva/node-oidc-provider#147]
these checks prevent me from testing running oidc-provider locally:

[implicit + http](https://github.com/panva/node-oidc-provider/blob/master/lib/helpers/client_schema.js#L445)
[implicit + localhost](https://github.com/panva/node-oidc-provider/blob/master/lib/helpers/client_schema.js#L449)

i had to hack the code to test locally...

would you consider allowing with some kind of a dev-mode configuration?

**Comment by panva** [comment]
I would actually not. A similar question (#63) already popped up. If this becomes configurable, someone will just leave it enabled, I don't like that. While not a package maintainer's problem, I tend to enforce the rules so long as there is a simple setup you can do to get around this locally. And there is.

Caddy is a great webserver which can have valid ssl certificates issued for you based on a DNS entry if you configure it right, allowing your local services to run with valid https certificates.

**Comment by tony-kerz** [comment]
fair enough, i understand your point of view. [caddy](https://caddyserver.com/) looks nice, i'll look into how that might resolve my requirement.

**Comment by panva** [comment]
it's actually really simple, even when you're not able to route internet traffic to your local.

```
$ host rp.panva.de
rp.panva.de is an alias for panva.de.
panva.de has address 127.0.0.1
panva.de has IPv6 address ::1
```

Have your caddy built with i.e. `tls.dns.route53` or any other supported registrar and have the eTLD handled by it. Follow the requirements for each of those, but then the server definition is as easy as this,
```
https://rp.panva.de {
  tls {
    dns route53
  }

  proxy / localhost:3000 {
    transparent
  }
}
```

When running behind TLS offloading proxy follow the documentation to enable proxy mode.

**Comment by panva** [comment]
https://github.com/panva/node-oidc-provider/blob/master/recipes/implicit_http_localhost.md
