### ISSUE TITLE
SSO: Skip user consent

### ISSUE THREAD

**Issue by elendirx** [panva/node-oidc-provider#148]
Scenario: Client A authenticates the user via Auth code flow (Provider asks user for credentials). Later, Client B wants to do the same. User is already signed in so no credentials input is required, the consent request screen is displayed though.

While this is correct and desired behavior with 3rd party clients, with trusted clients where both Client A, Client B and even Provider belong to the same organization, it would be nice to have the option to skip the user consent screen.

Do you think it's a good or bad idea? Thanks!

**Comment by panva** [comment]
That's a policy you can already [configure](https://github.com/panva/node-oidc-provider/blob/968b649/lib/helpers/defaults.js#L345-L372).

**Comment by elendirx** [comment]
Oh, my bad, I was looking for it in the per-client config. Thanks for your time! Please close the issue.

**Comment by GilVieira** [comment]
To skip the interaction dynamically I added an "sso" field in my client table (for internal clients), how could I retrieve this information in the `interactionCheck`, I know I can retrieve the id `ctx.oidc.client.clientId`, but I would not like to have to do another search in the database, is there a way I can add the property on the client object of the provider and retrieve it in the `interactionCheck`?

Tks
