### ISSUE TITLE
handle bad user/password

### ISSUE THREAD

**Issue by sa-emcvey** [panva/node-oidc-provider#149]
Hi, I am using your library for an implicit auth flow and have enjoyed it so far, but I am stuck on one particular issue.

Logging in with the correct credentials works as expected, but I need to be able to handle the case where a user either enters a username that does not exist or uses the wrong password. In all of the examples, if a user doesn't already exist it just creates a new account for that user, but I need to be able to prompt them to try logging in again.

My authenticate function looks like this:
```
  static async authenticate(email, password) {

    // look up user in mongoDb table using mongoose model
    return Login.findOne(
      { email: email },
      {
        _id: true,
        email: true,
        pw: true,
      }
    )
      .then(user => {
        if (user) {
          if (<compare pasword here>) {
            // return user constructed as account with proper accountId
            return new Account(user);
          } else {
            // user exists but password incorrect;
            throw new Error('Incorrect password');
          }
        } else {
          throw new Error('User does not exist');
        }
      })
      .catch(err => {
        // can i handle error here somehow?
        throw err;
      });
  }
```

I used the example login route:
```
    app.post('/interaction/:grant/login', parse, (req, res, next) => {
      Account.authenticate(req.body.email, req.body.password)
        .then(account => {
          oidc.interactionFinished(req, res, {
            login: {
              account: account.accountId,
              acr: '1',
              remember: !!req.body.remember,
              ts: Math.floor(Date.now() / 1000),
            },
            consent: {
            },
          });
        })
        .catch(next);
    });
```

If I don't rethrow the error in Account.authenticate.catch, it reaches the provider.interactionFinished which automatically redirects to the client despite being given a server error response. `next` will handle errors of "route" or "router" and will exit either.

If I do rethrow the error, I need to handle it somewhere, but I'm unsure where/how, or how to redirect the user to login with the correct client params. It seems to me interactionFinished has to be called at some point, but I only see options for login and consent. Do I have to make a custom prompt for failed login, or am I missing something?

**Comment by panva** [comment]
You only call interactionFinished when the end-user has finished the interactions. What this entails is up to you. How you structure your interaction part of the app is up to you, the library only provides the protocol implementation. 

Things that every user management frontend should have, such as

- login
- registration
- double opt-in
- password reset

are your domain. But also the standard means of protecting your views

- csrf protection
- cookie signing
- helmet require
- brute force protection

... you need to take care of. Understand oidc does not replace the need for proper secure user management.

**Comment by robtweed** [comment]
I'm struggling with this same issue, and unfortunately don't understand @panva's response sufficiently to know how to handle an invalid username/password entered by the user to produce an error on the login form, getting the user to try again.

@sa-emcvey did you come up with a solution?

Many thanks for any assistance

**Comment by telemmaite** [comment]
My app flow is 

- User see only email field and Next button 
- Next triggers ajax to check if that email is registered
- If yes User is asked for password, so far because the AJAX we are at same starting place/interaction
- however once the User enters his password and presses Submit/Next we land at route interaction/login
- I check `Account.authenticate(req.body.email, req.body.password)` if I am not happy , I do **NOT** call oidc.interactionFinished and just `res.render` an error that the password is wrong.
- At this point the User can just retry with different password
