### ISSUE TITLE
How to AuthN in  APIGateway

### ISSUE THREAD

**Issue by liubog2008** [panva/node-oidc-provider#151]
Excuse me, I have three problems about how to authenticate token in OIDC:
1. `id_token` or `access_token` I used to access resource? Can I  use `id_token` to access resource?
2. If `id_token` is not used to access resource, when to use it ?（In fact, I find some API servers must use IDToken, e.g. kubernetes）
3. If `id_token` can be used to access resource, how to validate `aud` for multiple clients?

Could you give me some helps? 
Thank you very very much.

**Comment by panva** [comment]
Hi @liubog2008, these are neither library code related issues nor library use questions. I suggest you dig deeper into OIDC and maybe ask some place more [appropriate](http://openid.net/foundation/community/mailing-lists/).

**Comment by liubog2008** [comment]
Thank you for your help @panva
