### ISSUE TITLE
`await provider.interactionDetails(request)` is sometimes partially defined

### ISSUE THREAD

**Issue by mshwery** [panva/node-oidc-provider#154]
I have a custom handler for `GET /interaction/:grant` that checks the awaited results of `provider.interactionDetails(request)` much like [the example](https://github.com/panva/node-oidc-provider/blob/f231e68f6e6993479d3f9f41280c0fb085457c37/example/index.js#L60). After migrating to v2 we started encountering some instances where the awaited return object would not have an `interaction` property defined. Should that behavior be expected?

Since we are doing a property lookup for `details.interaction.reason` we are seeing exceptions thrown, despite doing some initial validation of the `details` object's existence:
>`Cannot read property 'reason' of undefined`

We encounter this in particular when swapping from one set of servers, to another (both running `oidc-provider@2.3.1`, both storage adapters configured to connect to the same Redis node).

Should we expect that the `interaction` property may be undefined on the (awaited) return object? Do you see anything obvious from this summary explanation that jumps out as problematic?

**Comment by panva** [comment]
I can see this remotely possible when

1) the cookie is not sent (i.e. protocol changed, cookie signing keys are different)
2) the adapter is not finding the object (read from secondaries, not replicated fast enough?)

all in all cases when the adapter returns falsy, there's an assertion missing clearly, i will fix that. Could you log the awaited returned object id property?

**Comment by panva** [comment]
https://github.com/panva/node-oidc-provider/commit/8e1c5d51a36b6fac64edbd8d25fd5b1fb30bbc9c addresses the missed assertion, this does not get rid of the underlying issue but may help you discover this, i can't see any other reason why the session wouldn't be found unless your cookie config or adapter is out of order.

Are you able to test with this specific version before i release a patch?

**Comment by mshwery** [comment]
Yes I can log the instances where the shape is unexpected and I can test specific versions.

It's been hard to reproduce without throwing real traffic at it though.

Thanks for all your work in this excellent library!

**Comment by mshwery** [comment]
Would I have any issue going from a v1 cache to v2 cache? I'm going to also bump the cache key prefix in redis so there aren't any collisions there where the cached data has a different shape than expected.

The odd part on my end is that when swapping between these two sets of servers, the working set is identical to the broken set. Same version of this library. Same configuration. Reading the same Redis instance. It should be no different than adding one more instance to the working set.

Any way, I'll add some logging and see what I can find over here.

**Comment by panva** [comment]
> Would I have any issue going from a v1 cache to v2 cache?

oidc-provider 1.x and 2.x? Yes, those two use different mechanisms. 1.x used the cookie to store details and parameters, 2.x uses the adapter storage instead.

**Comment by mshwery** [comment]
I've figured out my problem – I didn't complete migrating _all_ the changes. hadn't moved the adapter from the `Provider(config)` to the `provider.initialize({ adapter })`

**Comment by mshwery** [comment]
After adding logging around this code in still seeing instances where details is defined, but it has no `interaction`. The object returned from `provider.interactionDetails(request)` is an empty object: `{}` (at least after being stringified for the logs).

**Comment by panva** [comment]
I believe the cookie needed for the server to lookup the interaction is not sent (misconfiguration) or is expired. [v2.3.2](https://github.com/panva/node-oidc-provider/blob/master/CHANGELOG.md#232) makes it so that the helpers will throw instead of creating a new session with no data `{}`
