### ISSUE TITLE
How to tell provider that user logged in without consent?

### ISSUE THREAD

**Issue by jakubriedl** [panva/node-oidc-provider#155]
Hi,
We are implementing our custom interactions (as recommended). But we went into an issue that if we have two step interaction (1. login, 2. consent) we are getting in the second step `login_required` as interaction reason.

**How can we tell provider after login that user logged in?** And have second interaction step reason `consent_required`?

I've tried to create session manually but it seems hacky and didn't work properly with `prompt=login`.

Thanks for help

**Comment by panva** [comment]
> oidc-provider expects that you resolve all future interactions in one go and only then redirect the User-Agent back with the results

It is intentional that you must resolve all future interactions in one go, if that's split between multiple steps that's fine - so long as you only resolve with `interactionFinished` once.

**Comment by jakubriedl** [comment]
Ok fine, so how do you recommend to detect reasons? The `interactionCheck` is not called cause it is always returned `login_required` by previous check. Should I do it directly in `interaction/:grant` route handler? And how can I detect that `promt=login` was satisfied so I can render consent view? Maybe by some custom cookie when login successful?

**Comment by panva** [comment]
The library will always give you the first "reason", but this was never intended to be the mechanism for choosing what to render. By having access to the auth request parameters you're able to figure out if prompts or other mechanisms (e.g. max_age) were requested. How you keep the accumulated interaction state before the interactionCheck call is up to you.

**Comment by jakubriedl** [comment]
Ok, thanks. It would be nice to write down things like this in interaction part of docs. When I'm implementing it is quite hard to understand how it was meant when you designed the lib API. I often need to look into source code.

**Comment by panva** [comment]
I wholeheartedly welcome all documentation improvement PRs ;)

**Comment by maitscha** [comment]
+1

Very interested how your implementation will look like ;)

Had the same question here: #132

I ended up with the following code in the POST `/login` handler:

```js
    const interactionSession = await provider.interactionDetails(req);

    try {
        // save login username in interaction session
        interactionSession.login = {
            account: req.body.email,
            acr: '1',
            remember: !!req.body.remember,
            ts: Math.floor(Date.now() / 1000),
        };
        await interactionSession.save(60);
        renderAuthorizationPage(req, res, interactionSession);

    } catch (e) {
        renderErrorPage(req, res, interactionSession);
    }
```

And the POST `/authorization` handler finishes the interaction with `await provider.interactionFinished(req, res, result);`.
