### ISSUE TITLE
How should rejections/exceptions from `findById` be handled?

### ISSUE THREAD

**Issue by mshwery** [panva/node-oidc-provider#156]
Currently, any thrown exceptions or Promise rejections from `findById` result in a generic error that doesn't bubble to the custom `renderError` handler.

It seems that `findById` is expected to _always_ return an entity, but that conflicts with my understanding of its semantics. I stumbled upon this when a user account was deleted, but they previously had logged in (creating a new OIDC Session). There might be other exceptions that happen during `findById` as well (network flakiness, upstream service outage, etc).

Is there a supported way to handle these types of errors? Does `findById` expect an entity even if a matching user could not be found?

**Comment by panva** [comment]
if account is found return an object
if account is not found, return falsy
if there's an exception - reject with the error

**Comment by mshwery** [comment]
Cool. Thank you!

Returning `false` redirects the user back to the RP with an `invalid_grant` error. Is there a way to handle the error in the OP instead of redirecting back to the client callback uri or is that a deviation from the spec?

**Comment by panva** [comment]
`invalid_*grant*` redirect?

**Comment by panva** [comment]
I literally don't have an idea where you would be inside an authorization flow and be throwing invalid_grant.

**Comment by mshwery** [comment]
Let me verify real quick that this indeed isn't coming from `interactionCheck`. I haven't ruled that out just yet.

**Comment by panva** [comment]
No i'm saying inside authorization endpoint there is no invalid_grant. This is at the token request. I don't understand how you want to redirect a user during a backend request.

I understand why, just don't know what you wish to do, call findbyid during every authorization request pass even tho no claims are required to be returned at the time?

If you're doing stuff outside of the context of the app you might as well remove the session in the adapter so that the user is logged out.

**Comment by mshwery** [comment]
Ah, I see what you are saying.

I did verify this is happening outside of the context of my application code. The RP is showing a generic error of `invalid_grant` at one of the RP's configured `redirect_uris`. I was probably missing the fact that the redirect url handler was making a backend request to complete the authorization. I'm using the `openid-client` (`v1.11.0`) via Passport in that RP, so it's a bit abstracted from my code as to how the library handles this type of behavior (returning `false` from `findById`).

I'm not sure I have any prescriptive solutions here, but am trying to clarify who is responsible for handling this flow (RP or OP).

**Comment by panva** [comment]
the RP.

**Comment by panva** [comment]
You might OOB remove the session stored in the adapter when you delete accounts. Then this ddoesn't happen. Else it's the RPs job to handle this.

**Comment by mshwery** [comment]
Yeah, I think that makes the most sense as well. Thanks!
