### ISSUE TITLE
New to OpenID connect - Does this support SSO?

### ISSUE THREAD

**Issue by falconmick** [panva/node-oidc-provider#162]
Hey @panva 

Sorry if this is a stupid question, but I looked through as much of the info for this repo as I could and couldn't be sure.

If I wanted to use this as a SSO server for multiple applications authenticating with Office 365, is there anything special I would have to do? Or does the flow work in such a way that the user comes to the first site, logs in via node-oidc-provider which is on its own domain, then when they go to use the second app, they are once again redirected to the node-oicd-provider domain and see that they're logged in and are given a code without need for any interaction?

Cheers,
Michael.

**Comment by panva** [comment]
Hey @falconmick,

> If I wanted to use this as a SSO server for multiple applications authenticating with Office 365

this makes little sense to me, isn't office 365 already behind it's own SSO from microsoft?

> is there anything special I would have to do?

this library provides the protocol implementation, not user interactions, so you will have to code your own user interactions (login, consent, pw reset etc) and be responsible for securing them.

**Comment by falconmick** [comment]
From memory (sorry again for lack of understanding) office authorises per
app so you can’t just login once and have the ability to silently login to
other servers with limited distraction to the user.

Looking into this for another team member so I’m not the most versed
