### ISSUE TITLE
option for state cookie

### ISSUE THREAD

**Issue by mogeda** [panva/node-oidc-provider#163]
I see below in `lib/actions/authorization/respond.js`. Is there any specific reason to set httpOnly to false?

```js
cookies.set(
      stateCookieName, state,
      Object.assign({}, instance(provider).configuration('cookies.long'), { httpOnly: false }),
    );
```

**Comment by panva** [comment]
yes, because the state needs to be readable by javascript from within the client-side rendered js in `lib/actions/check_session.js` so that Session Status Change Notification from [Session Management 1.0](https://openid.net/specs/openid-connect-session-1_0.html) can work.
