### ISSUE TITLE
Introspection of access_token failing without token_type_hint

### ISSUE THREAD

**Issue by greigdendor** [panva/node-oidc-provider#166]
Hello there,

First of all, thanks for a great module. It's allowing us to build an in-house provider for our internal systems and it's a fantastic project.

Now the issue - this may be down to me misusing something but I believe there is an issue when doing token introspection without a hint.

Please note that I am using a custom adapter (for CouchDB), but from what I can see, the find() method is returning what it should return, and in debug mode when submitting the request, I can see the adapter returning results.

I was getting `{active: false}` for access_token introspections until I sent the `token_type_hint` parameter.

I believe this might be to do with the Promise.all() at the end of the case statement in `introspection.js`:

[introspection.js#L96](https://github.com/panva/node-oidc-provider/blob/14b1a9ea47629cc2bc19a6e94f011edf1c5067f9/lib/actions/introspection.js#L96)

It could be that any failure within the Promise.all is raising an error, as a result of [Promise.all fail fast behaviour](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Promise/all).

As mentioned, this may very well be something I am doing wrong so I would appreciate a nudge in the right direction if there is something obvious I am missing!

Many Thanks
Greig

**Comment by panva** [comment]
Hi @greigdendor

what error, do you have a stack trace, `DEBUG=oidc-provider:*`?

id_token_hint is OPTIONAL parameter for introspection and revocation and it is tested for. If there's a server_error it's coming from the adapter, `Promise.all` is intended here.

I'm guessing if you nail down the error in your adapter and it'll work. If there's an error that comes from within the library please let me know.

**Comment by panva** [comment]
tests

- at - https://github.com/panva/node-oidc-provider/blob/master/test/introspection/introspection.test.js#L23
- rt - https://github.com/panva/node-oidc-provider/blob/master/test/introspection/introspection.test.js#L118
- cc - https://github.com/panva/node-oidc-provider/blob/master/test/introspection/introspection.test.js#L198

**Comment by panva** [comment]
Hang on, i had to read it more times... Yes it is intended to do a `Promise.all` since w/o a hint it's a scatter-getter like operation, the adapter in normal operation should not throw any errors, if it does then yes that's why you don't get your results for a valid token w/o a hint. Find your adapter error, fix it and get your results. The scenarios where no hint is provided are tested for by the test suite.

**Comment by panva** [comment]
The catches are not necessary in those promise chains anymore, if you remove them it'll help you find your problem. I will test further and see if i can remove them to propagate adapter issues

**Comment by panva** [comment]
Check the latest master changes they should help you narrow it down. Either way, i see two couch instances and three find() calls. Also all three instances find access tokens? That means an access token data is returned to refresh token find call. That ain't right ;)

**Comment by greigdendor** [comment]
Thank you, and yes I was thinking the same thing about the three results! I’m having a detailed look at the adapter now and I’ll let you know what I come up with.
