### ISSUE TITLE
primaturely end the interaction with an error

### ISSUE THREAD

**Issue by KtorZ** [panva/node-oidc-provider#167]
Hi again,

On an other topic, I am trying to figure out a way to abort an interaction from within my authorization server with a specific error (for instance `access_denied` from the [OAuth 2.0 RFC](https://tools.ietf.org/html/rfc6749#section-4.1.2)). 

However, at the very best, it is possible to call the `interactionFinished` with an empty object, resulting in the `oidc-provider` redirecting the end-user towards the RP with an error `login_required` and description `End-User authentication is required`.  

I am missing something or is there currently no way to abort an interaction with a specific error code & description ?

**Comment by panva** [comment]
This is not supported at the moment. Two ways you have, 

1. build a feature for this
2. you have the redirect uri available in your interactions, same as the response mode, you can handle the sendoff to the RP yourself

**Comment by KtorZ** [comment]
My implementation currently relies on the second point indeed. However, while I redirect the user back to the RP, the interaction session remains active and open until expired. 

With the same spirit as #165, what would you think of enabling the AS to prematurely end the interaction with a singleton object `{ error: ... }`  containing an error code referenced in either of:

- http://openid.net/specs/openid-connect-core-1_0.html#AuthError
- https://tools.ietf.org/html/rfc6749#section-4.1.2.1

The description and state can be added by the `oidc-provider` as needed and it gives a clean way for the AS to handle errors (without having to manually build a url and perform the redirection).

**Comment by panva** [comment]
I don't see how oidc-provider would add a description for an error it's not throwing, so let's provide an object with both error and error_description. Else I agree, state and valid response mode handling will be handled by the existing implementation.

**Comment by KtorZ** [comment]
I don't see any room for custom error codes in the standard, which means that there's a fix list of values that could go in this `error` property and therefore, a corresponding list of descriptions that go with these errors. Don't you agree?

**Comment by panva** [comment]
I don’t agree, someone will just return a custom error for his closed ecosystem provider and will want to provide a description of his own ;)

**Comment by KtorZ** [comment]
I guess you're right. Let's go for an object: `{ error: ..., error_description: ... }` then to indicate a failed interaction. I will work on a PR.

**Comment by panva** [comment]
PR Merged, to be released with 2.5.0 in the coming days.

**Comment by KtorZ** [comment]
By the by, thanks for the diligence in handling those issues & PR :+1:

**Comment by panva** [comment]
You're welcome and thank you for the contributions! I took the liberty of ditching the assert and http-errors require since ctx.throw will take care of stringifying the error and result consent/login won't be used anyway if the result will throw. I know of a few users that accumulate these results and would likely just accumulate an error and then return the whole thing.
