### ISSUE TITLE
[Question] Passport + OIDC

### ISSUE THREAD

**Issue by da-pingwing** [panva/node-oidc-provider#169]
When using Passport how to authorize a user through OpenID Connect?
I've been trying to use the interactions but they just trigger "id must be provided to Session#find"

>/* Google Passport */
>  app.get('/auth/google',
>    passport.authenticate('google', { scope:
>    	[ 'https://www.googleapis.com/auth/plus.login',
>    	  'https://www.googleapis.com/auth/plus.profile.emails.read' ] }
>   )
>  );
>
>  app.get( '/auth/google/callback', function(req, res, next){
>    passport.authenticate( 'google', function(err, user, info) {
>      console.log('marker 4');
>     if(err) { return next(err); }
>      if(!user) { return res.redirect('/auth/google') }
>      req.logIn(user, function(err){
>        if (err) { return next(err) }
>        console.log('marker 5');
>      });
>    })(req, res, next);
>  });
>};

Thanks in advance

**Comment by panva** [comment]
This question makes no sense in the provider context, sorry.
