### ISSUE TITLE
OIDC provider & location header relative reference

### ISSUE THREAD

**Issue by janhalama** [panva/node-oidc-provider#170]
Hi,
OIDC provider redirects to interaction endpoint using relative reference in location header:

> Location: /interaction/7b2e8820-6a9a-4fde-aa51-0271f41b6337

Using relative reference location header values has been standadized by [RFC 7231](https://tools.ietf.org/html/rfc7231) which is relatively new (June 2014).

We do encounter problems with relative redirections on https protocol. Is it possible to configure OIDC provider to use absolute URIs?

Thanks.

Jan

**Comment by panva** [comment]
Hello @janhalama,

to answer your question yes, it's [configurable](https://github.com/panva/node-oidc-provider/blob/master/lib/helpers/defaults.js#L335-L346), it even logs a warning for you since 2.x.

What do you see wrong with the redirect in terms of 7231?

**Comment by janhalama** [comment]
Hello @panva,
thanks for prompt response.

InteractionUrl is what I was looking for.

We run identity provider behind Traefik reverse proxy, which might cause the problem.  Browser receives redirection responses with http status code 200 instead of 302.

Jan

**Comment by panva** [comment]
Ok, so you're not seeing an issue with the library. Glad I could help.
