### ISSUE TITLE
question: "id must be provided to Session#find" from http client

### ISSUE THREAD

**Issue by tony-kerz** [panva/node-oidc-provider#172]
i'm trying to write a test that uses `oidc-client` and `oidc-provider` to simulate a client authenticating, so attempting to programmatically:

1. GET the `authorization_endpoint` form
1. POST what the form would post if user/pass was provided and form was submitted

my question is around why calling GET on the `authorization_endpoint` from an http-client such as [axios](https://github.com/axios/axios) yields:
```
id must be provided to Session#find
```

[here is a link to the test](https://github.com/tony-kerz/node-oidc-proxy/blob/945717e04ae4ad52e3d41a847f52e82333d45027/test/ava/oidc-provider-test.js#L42)

> if i spin up the same configured instance of `oidc-provider` and hit it from a browser, it works fine, so i'm guessing it's something around the http-client, cookies, sessions, etc, but i can't put my finger on it.

any guidance appreciated, even alternative testing strategies...

**Comment by panva** [comment]
sorry, either do it from a browser environment or make sure your "user-agent" persists and mimics a cookie-jar behavior like your browser does. I cannot offer you support for doing a simulation in an invalid setup environment.

**Comment by panva** [comment]
Issue is your user-agent, simulating http calls without the proper cookies that the calls set will not work.

**Comment by tony-kerz** [comment]
thanks for the tip Filip!

this did the trick: https://github.com/3846masa/axios-cookiejar-support 👍
