### ISSUE TITLE
Client credential returning id_token for service account

### ISSUE THREAD

**Issue by joshperry** [panva/node-oidc-provider#173]
We'd like to implement the concept of a service account for our API, and I've [documented](https://jsapi.apiary.io/previews/pdkauthapi/introduction/authentication-flows/client-credentials-flow) how I think we'd like it to work using the client_credentials grant.

I've looked in the source code and it looks like I could monkey patch the `provider.ClientCredentials` class to send an id_token response. We would store the client's identity reference in the client document and use that to generate the id_token.

We want these clients to have their own identity for auditing and authorization purposes, I looked at the OAuth JWT Bearer grant type but that seemed more aimed at impersonation. Do you think there is a better method to accomplish this?

**Comment by panva** [comment]
There’s a feature in place allowing you to add grants. But it can be used to replace the existing ones if you need custom behavior. 

It is the recommended way. 

https://github.com/panva/node-oidc-provider/blob/master/docs/configuration.md#custom-grant-types

Note: the doc has a broken link, it is intended to link [here](https://github.com/panva/node-oidc-provider/tree/master/lib/actions/grants) to show you the source of existing grant type implementations.

**Comment by joshperry** [comment]
I see, so if I implement `client_credentials` grant it will override the built-in. Thank you.
