### ISSUE TITLE
scope param in successful token response

### ISSUE THREAD

**Issue by slavab89** [panva/node-oidc-provider#174]
When receiving the response token from a successful authentication i've noticed that its missing a scope param. It is optional most of the time but required at others.
My current workaround is to send an additional `introspect` request right after the token response to get the granted scopes.

I'm basic this on https://tools.ietf.org/html/rfc6749#section-4.1.4 and https://tools.ietf.org/html/rfc6749#section-5.1.

> scope
         OPTIONAL, if identical to the scope requested by the client;
         otherwise, REQUIRED. 

Please let me know if i misunderstood something.

**Comment by panva** [comment]
I believe there's no harm in returning it all the time. Would you prepare a PR where this is reflected in both authorization_code and refresh_token responses?

**Comment by panva** [comment]
see https://github.com/panva/node-oidc-provider/commit/79fea3e0988fb361f7d26c20a6167bc2b5a000df and close if it's fine for you

**Comment by slavab89** [comment]
😱 you're fast! i just started cloning and doing that change.
Thanks!

**Comment by slavab89** [comment]
btw, wanted to ask if you think there is any harm in exposing the list of granted scopes to the end user (via and API endpoint).. Mostly to be able to limit the visibility of some UI components based on the presence of different scopes.
