### ISSUE TITLE
CORS at the token endpoint

### ISSUE THREAD

**Issue by elendirx** [panva/node-oidc-provider#176]
Hi,

would it be possible to have CORS enabled at the token endpoint? I'd like to call it from within a single page JS app. Or is it against rules?

If it's ok, I'll submit PR.

**Comment by maitscha** [comment]
This should be doable without chaning the oidc-provider. Register some CORS middleware at the token endpoint prior to registering the oidc-provider.

**Comment by elendirx** [comment]
Thanks for your response. I must admit I'm clueless. If I register my custom token route prior to the oidc-provider, [this line](https://github.com/panva/node-oidc-provider/blob/master/lib/helpers/initialize_app.js#L80) still gets called later during the init. Also, when registering my custom token route with my custom CORS middleware, how do I register the library's default [token middleware](https://github.com/panva/node-oidc-provider/blob/master/lib/actions/token.js#L10)?

Too many questions from a javascript noob, I know. :-) But if you could point me in the right direction, I'd be grateful.

**Comment by maitscha** [comment]
How do you currently register the oidc middleware? for example for express:
```
const app = express();
app.use(provider.callback)
```

**Comment by elendirx** [comment]
```
provider.initialize({clients: clients}).then(() => {
  // get koa app
  const app = provider.app
```

I have no problem with changing it to something similar to your code snippet:

```
const app = new Koa()
app.use(provider.callback)
```

Then I can register another middleware prior to registering oidc-provider. But I still don't quite understand how to register CORS for the token endpoint this way. I believe I have to use Router to do that, right? Then what happens when the oidc-provider tries to define the token route during its own init?

**Comment by maitscha** [comment]
In Express you can register middleware functions for a specific path only, for example `app.use('/oidc/token', cors())`. This would call the cors middleware only for the `/oidc/token` path. I assume it works the same way in Koa?

**Comment by elendirx** [comment]
I believe I'm starting to understand your point. It's little different in Koa but I think you kicked me in the right direction. I will try to register CORS route prior to the oidc-provider initialization.

Thanks a lot for taking the time to help me!

I'm closing the issue for now.

**Comment by panva** [comment]
or,

```js
provider.app.middleware.unshift(async (ctx, next) => {
  await next();
  if (routeMatchesToken) {
    // add CORS headers of your own.
  }
});
```

**Comment by elendirx** [comment]
> For a website tho, i don't see why you would need to

Yes, I'm trying to do something non-standard, please don't even ask. I don't feel good about it so I'm trying to deviate from the standard as little as possible and enabling CORS should suffice.

Thank you!
