### ISSUE TITLE
updating client_secret in client information

### ISSUE THREAD

**Issue by mogeda** [panva/node-oidc-provider#177]
Is it possible to update client_secret? 
I'm also trying to set client_secret_expires_at during the registration time but it looks it's not allowed but always set to 0, never expired.

**Comment by panva** [comment]
`client_secret_expires_at` is not a client input, it's part of the response formed by the provider. Right now there's no built-in support for reseting, expiring or updating secrets through the registration specifications and this implementation. You're going to have to find an OOB solution which goes into your adapter storage and changes the secret and then reloads the processes with such clients already loaded.

**Comment by mogeda** [comment]
got it, thanks!
