### ISSUE TITLE
Fail to initialise oidc when using webpack

### ISSUE THREAD

**Issue by atomicleopard** [panva/node-oidc-provider#179]
The basic express example fails when processing an app with webpack.

initialise_app.js - line 54

        configuration.grantTypes.forEach(grantType => {
          try {
            const grant = require(`../actions/grants/${grantType}`) // eslint-disable-line global-require, import/no-dynamic-require
            this.registerGrantType(grantType, grant.handler, grant.parameters)
          } catch (err) {
            /* istanbul ignore if */
            if (err.code !== 'MODULE_NOT_FOUND') throw err
            console.log(`Failed to load oicd-provider grantType ${grantType}`)
          }
        })

Webpack replaces `require('../actions/grants/${grantType}')` with `__webpack_require__(395)('./${grantType}')` - this seems to have a different contract for throwing an exception when a module is not found (i.e. there is no `err.code`). This causes the 'implicit' grant type to fail, and prevent the initialisation process.

Given the set of grantTypes is baked in, is it possible to filter for those that have an implementation in `actions/grants`?

Commenting out the conditional throw allow oidc to start up.

**Comment by atomicleopard** [comment]
Thanks for this fix (and the speed of the turn around). Further usage has shown that this is also an issue on the 1.x stream, which it turns out I need.

**Comment by panva** [comment]
I'm assuming you're pushing your oidc to lambda through webpack/babel then? If that's the case i'd recommend to exclude this package from being required through webpack altogether.

**Comment by panva** [comment]
anyway, pushed to v1.x and published too, probably the last backport to that branch, with lts/8 coming to lambda soon v1.x is useless now

**Comment by atomicleopard** [comment]
Much appreciated - very much looking forward to lts/8 native, but for now some of the v2 dependencies are causing trouble (like new URL) which is more hassle than its worth solving. Thanks for your awesome work. 🙌
