### ISSUE TITLE
supporting dynamic scopes

### ISSUE THREAD

**Issue by mogeda** [panva/node-oidc-provider#180]
I pull scopes first from other service before I create oidc-provider object but it looks scopes can't be updated once the provider created and initialized. Is there any way to update scopes in config dynamically without restarting my service? Thanks.

**Comment by panva** [comment]
what's stopping you from waiting for the pulled scopes and then initializing? Currently I don't see a supported way to change the configuration.

**Comment by mogeda** [comment]
admin need to restart service whenever scopes added or updated in other service. It might be not that often like daily bases but restarting service will interrrupt clients which rely on the service.
I see new grantType could be added via registerGrantType so was wondering whether there is a way for scopes too.

**Comment by panva** [comment]
sorry you're going to have to work around this, implement a rolling restart ;)
