### ISSUE TITLE
Dynamic access token TTLs

### ISSUE THREAD

**Issue by jdiamond** [panva/node-oidc-provider#181]
Hi, is it possible for different clients to have different TTLs for their tokens? Thanks.

**Comment by panva** [comment]
Hi @jdiamond, yes and no, since you're in charge of the actual storage you're able to simply remove documents earlier to invalidate them depending on your policy, however this won't affect the oidc-provider responses, so things like introspection, and expires_in values will still report the configured values.

**Comment by jdiamond** [comment]
Thanks for the reply. Not sure I would want to go that route, though.

We have about a dozen clients configured with our provider. The default 8-hour TTL is fine for all but one. It's a dashboard app that's on a big display and we want it to stay "logged in" for much longer than that.

I was looking through the code and found where the ttl section in the provider configuration is consulted. Would it be possible to allow that to be a function so that it can compute a value dynamically? It would probably have to receive the client metadata to make that decision, though, and I don't think that's available at the point the ttl is read from configuration.

This dashboard app of ours uses implicit grants so it can't request offline_access and alwaysIssueRefresh doesn't seem to work with implicit grants (should it?). Being able to say that one client can have much longer TTLs was just one hope I had of making this work, but I'm open to other ideas.

If I have to, I might be able to change it to use a code grant, but I was exploring other options first.

Thanks.

**Comment by panva** [comment]
Can you work out a PR? The individual ttl parameters could accept a function (now they do just a number), when ttl would be a function it accepts one parameter (ctx) and would return the number for this particular context.

> alwaysIssueRefresh doesn't seem to work with implicit grants (should it?)

It really should not :)

**Comment by jdiamond** [comment]
I started to look at this and the path that seemed like it might work is changing every place that references `expiresIn` to treat it like a function and pass in `ctx`. It does seem like most of the places where `expiresIn` is used, there is a `ctx` in scope.

But I'll let you think about it because that was a pretty intrusive change that I wasn't feeling too confident about being able to pull off.

**Comment by panva** [comment]
Unfortunately you are incorrect, the calls for the Class getter expiresIn from the grants and authorization endpoint is only there for those responses, it doesn't control the ttl of the token. In BaseToken (a model) context there's no context, and shouldn't be.

Anyway, you can get your problem solved by overloading the `BaseToken` (to define this for all token types) or just `AccessToken` expiration instance getter, i.e.

```js
Object.defineProperty(provider.AccessToken.prototype, 'expiration', {
    get() {
      if (this.expiresIn) return this.expiresIn;
      
      if (this.clientId === '/...') {
        return 9001;
      }

      return this.constructor.expiresIn;
    }
  });
```

**Comment by jdiamond** [comment]
Thanks for the example. My tokens now get saved with my dynamic TTL, but the responses return the static TTL because of lines like this one:

https://github.com/panva/node-oidc-provider/blob/85193fb71729c58da1cdf3ccfbaf721260f36855/lib/actions/authorization/process_response_types.js#L21

Would it be OK to change lines like this from using the static `expiresIn` property to using the non-static `expiration` property?

**Comment by panva** [comment]
it would

**Comment by amaciver** [comment]
Hello @panva. You are an amazing human. 
Any plans for officially supporting custom TTLs in client metadata? Happy to go the overload route, but curious whether there is something that would dissuade you from making this a feature.

**Comment by panva** [comment]
token ttl is an AS policy, can't be part of client's metadata that could be dynamically registered with. i've been toying with the idea of providing a helper function like with audiences to determine a ttl of a token at creation tho, when i have the time

**Comment by amaciver** [comment]
great, thanks for the quick feedback! 🙇

**Comment by panva** [comment]
Btw you can already play around with the token’s instance getter ‘expiration’ and implement such policies.
