### ISSUE TITLE
2.8.1 crashes when using a custom grant type

### ISSUE THREAD

**Issue by TestExCi01** [panva/node-oidc-provider#182]
Sorry I found no release notes or beaking change information but this is what worked some days ago :-)

```
oidc.registerGrantType('password', ...)
await oidc.initialize({ adapter: persistence, keystore })
```

Now it crashes in initialize_app.js line 51 since only well known grant_types are allowed:
```
  configuration.grantTypes.forEach((grantType) => {
    if (grantType !== 'implicit') {
     const { handler, parameters } = grants[grantType];
      this.registerGrantType(grantType, handler, parameters);
    }
  });

TypeError: Cannot destructure property `handler` of 'undefined' or 'null'.
```

**Comment by panva** [comment]
ah damn, didn't see this coming, can you move oidc.registerGrantType after oidc.initialize?

**Comment by TestExCi01** [comment]
Sure. I tried going back to 2.8.0 but if this has no further consequences why not. I'll test it right now...

**Comment by TestExCi01** [comment]
Looks good - thanks! But IF we did nothing wrong so far I would suggest to mention this change somewhere (or perhaps custom grant types are that uncommon than keep it to us). Although it might be that I overread some ordering hint in the docs - who knows :-)

**Comment by panva** [comment]
I honestly just missed this, i can call it unintended and assert inside `registerGrantType` that initialize was called first for non-standard grants :)

**Comment by JochenAtWork** [comment]
Good enough for us. Thanks again!

(Just it's me - just used the wrong GitHub Account)

**Comment by panva** [comment]
yw.

**Comment by panva** [comment]
third time's the charm... 2.8.2 should resolve the issue as well
