### ISSUE TITLE
Interaction and resume cookies

### ISSUE THREAD

**Issue by maitscha** [panva/node-oidc-provider#184]
Hi!

I have a very general question:

The Open-ID Connect provider uses URLs to redirect the user to the grant pages, and back to the done-page, for example `/auth/:grantId`. What is the reason for the interaction and resume cookies? Are they required at all, since the grant-id is already defined with the URL path?

Thank you for your help!

**Comment by panva** [comment]
Multiple reasons actually

1) The cookie travel's with the browser and the interaction is therefore bound to it.
2) It has a signed component through KeyGrip
3) In the future will use Token Binding to not be a bearer token anymore, will not be exfiltrate-able anymore
4) You can customize the interactionUrl not to include the grantId in the url and then the cookie is the only way for your interaction to load the details and to know where to submit the result
