### ISSUE TITLE
Pass ctx through to Client.find

### ISSUE THREAD

**Issue by dashton82** [panva/node-oidc-provider#185]
Hi, 

We've been using your project for some time now with great success. We've taken advantage of implementing our own adapter for getting our clients, and also have a separate API for our user store. One thing that we would like to do is to persist a correlationId between requests so we can track any issues easier - from looking at the source code i think this can be done by adding the following to find in [client.js](https://github.com/DFE-Digital/node-oidc-provider/blob/master/lib/models/client.js#L316) :

```
      static async find(id, { fresh = false, ctx = null } = {}) {
      if (cache.has(id)) {
        const found = cache.get(id);
        if (found.noManage || (!fresh)) return found;
      }

      const properties = await getAdapter().find(id, ctx);

      if (properties) return add(properties);
      return undefined;
    }
```

Allowing the ctx to be passed into find, and then passed onto the find on the adapter.

So [check_client](https://github.com/DFE-Digital/node-oidc-provider/blob/master/lib/actions/authorization/check_client.js#L18) will become :

```
const client = await Client.find(String(clientId), { ctx });
```

and [end_session](https://github.com/DFE-Digital/node-oidc-provider/blob/master/lib/actions/end_session.js#L118):

```
const visitedClient = await Client.find(visitedClientId, { ctx });
```

Is this something that you would consider in a PR or is it something that I can achieve in a different way?

Thanks for your help,
Dan

**Comment by panva** [comment]
Hi @dashton82, I'm glad the library is seeing use and it makes me glad there's even success.

Controller details and request context should not, in my opinion, play a role in any model's `find()` and as such do not belong.

If ever, in 3.x down the road, i decide to restructure the middlewares, unify all models across the board, etc., i might reconsider this as a global sweeping change, not for now though.

**Comment by dashton82** [comment]
Hi @panva,

Thanks for the quick response - I can see your point that the request context may not be the best thing to pass - all I am really looking for is a specific header value to be passed through - is that something you would potentially consider at this point? No problem at all if not, I can work around it

**Comment by panva** [comment]
No, not at this point. My apologies.

**Comment by dashton82** [comment]
No problem! 

Cheers,
Dan
