### ISSUE TITLE
Q: How to provide my own mechanism of creating JWTs?

### ISSUE THREAD

**Issue by MeenaAlfons** [panva/node-oidc-provider#186]
Creating JWT (for id_token) could be implemented in several ways. for example:

- I want to use client_secret to sign the JWT
- I want to put multiple signatures in the JWT

I don't see anyway to do that with oidc-provider. Please help me if there is a way.

**Comment by panva** [comment]
Hi @MeenaAlfons,

What you're asking is possible, but since you have the need to ask i feel it would be appropriate to read up on the specifications since it would be clear otherwise...

If you want to use a symmetrical key for signing or derived symmetrical key for encryption just set the appropriate [client metadata](http://openid.net/specs/openid-connect-registration-1_0.html#ClientMetadata).

And you can't put multiple signatures in a jwt since it would require the use of a jwt format not utilized by oidc.

> All uses of JSON Web Signature (JWS) [JWS] and JSON Web Encryption (JWE) [JWE] data structures in this specification utilize the JWS Compact Serialization or the JWE Compact Serialization; the JWS JSON Serialization and the JWE JSON Serialization are not used.

**Comment by MeenaAlfons** [comment]
Thanks you @panva . That was enlightening.
I figured that putting multiple audiences will solve my case. But I couldn't found a way to do it in node-oidc-provider.

**Comment by panva** [comment]
I can confirm no such feature is available. If you specified based on which mechanism you’d expect this i can work something out. We can also agree on a solution and PR is always welcome.

**Comment by MeenaAlfons** [comment]
Let's start with the specs then I'll talk about a possible mechanism.

This part talks about the format of `aud` field of the ID Token which allows multiple audiences. This part also describes the general case to have `aud` as  "an array of case sensitive strings".

> **2. ID Token**
> - aud
> REQUIRED. Audience(s) that this ID Token is intended for. It MUST contain the OAuth 2.0 client_id of the Relying Party as an audience value. **It MAY also contain identifiers for other audiences. In the general case, the aud value is an array of case sensitive strings. In the common special case when there is one audience, the aud value MAY be a single case sensitive string.**


The following part puts two validations regarding `aud` field. It has two important information:
1. The client must find its `client_id` in the `aud` (audiences) array.
2. `azp` (authorized party) field must EXIST when multiple audiences is listed.

> **3.1.3.7.  ID Token Validation**
> &nbsp;&nbsp;&nbsp;&nbsp;3. The Client MUST validate that the aud (audience) Claim contains its client_id value registered at the Issuer identified by the iss (issuer) Claim as an audience. The aud (audience) Claim MAY contain an array with more than one element. The ID Token MUST be rejected if the ID Token does not list the Client as a valid audience, or if it contains additional audiences not trusted by the Client.
> &nbsp;&nbsp;&nbsp;&nbsp;4. If the ID Token contains multiple audiences, the Client SHOULD verify that an azp Claim is present.

**Before going to example cases, let me try to articulate what "multiple audiences" means:**
Issuing an id_token to a Client (resource server) about a specific subject actually represents an authorization for that client to access other resource servers about the same subject. This is only possible because the other clients will find their `client_id`s in the `aud` field and will be able to verify the integrity of the token with the issuer. The issuer here is the authorization authority that issued the token and signed it in order to be trusted.

Again from specs: `aud` represents **Audience(s) that this ID Token is intended for.**
The intention described in this statement depends on the application. It is not tied(associated) to any specific context. For example:
- In one application, the OP may tie the audiences to a Client. Every time an id_token is issued to that client, the audiences will include more clients than the requester (because the client may use it to gain access to specific resources in other clients).
- Another application may need to tie the audiences to the subject. The audiences of the issued id_token depends on the access level of that subject and which clients the subject is allowed to access.

By "tie" I mean "relational wise". To what entity the audiences are associated. I'm analyzing the situation to come up with a mechanism that are flexible to fulfill different cases.

It seems like we need a hook where the application is given the context of creating an `id_token` and is expected to provide the audiences for that `id_token`. Something like:

    // Called moreAudiences because the requester client will always be included in the `aud` field
    // parameters should reflect the full context of creating an `id_token` (I included the simplest
    // suggestion. I didn't try to collect what composes the context of creating an `id_token`)
    moreAudiences(ctx, sub, client, ...) {
        return [
            'my_additional_audience_id'
        ];
    }

This is another part of the specs that are related to the audiences. Just to collect the affected places.
> **12.2.  Successful Refresh Response**
> its aud Claim Value MUST be the same as in the ID Token issued when the original authentication occurred,

I hope this analysis helps in implementing this feature.

**Comment by panva** [comment]
Hi @MeenaAlfons , i'm aware of azp/aud and what it means providing multiple aud claims, the thing i struggle with is finding a mechanism that works well for all general uses of this library,

- clients loaded during initialize
- clients registered dynamically
- clients loaded from an adapter

I believe this must be a well structured policy defined by each AS a simple hook in the ID Token class might do it, but same as always, i don't feel passing ctx to models makes much sense, i'll think about it some more.

**Comment by MeenaAlfons** [comment]
Hi @panva , I've thought about it and looked into the code. oidc-provider already gets claims from the `account` which gives the user of the library the flexibility to provide they own claims. I think the `aud` claim could be treated the same. The user of the library would provide audiences as they need and the library will add the direct client to the audiences if it doesn't exist. 

Proposed Usage:

    // This goes to oidc configuration file

    claims: {
        openid: [
            'sub', 
            'aud' // This is required for the library to take aud claim into account (affects claims mask)
        ],
        ...
    },
    async findById(ctx, id, token) {
        return {
            accountId: id,
            async claims() {
                return {
                    sub: id,
                    aud: ['additional_aud', 'aud2'] // provide audiences as needed
                };
            },
        };
    },

Proposed Changes:

    // lib/models/id_token.js
    class IdToken {
      // ...
      
      async sign(client, ...) {
        // ...
        
        **// TODO
        // if (payload.aud does not contain client.clientId)
        //     add client.clientId to payload.aud**

        const signed = await (() => {
          if (!alg) return JSON.stringify(payload);

          const keystore = alg && alg.startsWith('HS') ? client.keystore : instance(provider).keystore;
          const key = keystore && keystore.get({ alg });

          return JWT.sign(payload, key, alg, {
            // TODO Remove the following line because it forces the audience to be just client.clientId
            audience: client.clientId,
            expiresIn: noExp ? undefined : (expiresIn || this.constructor.expiresIn),
            issuer: provider.issuer,
            subject: payload.sub,
          });
        })();
      
      } // end sign()
    
    } // end IdToken


I'll make a PR when we agree on a solution.

**Comment by panva** [comment]
This would make aud appear in regular json userinfo responses, i'd rather go with a helper function approach similar to findById.

Thank you @MeenaAlfons, i'll take it from here.

**Comment by MeenaAlfons** [comment]
There is something I didn't mention before because I thought it would be off topic (we were talking about id_token). Here it is:

Multiple audiences concept exists in other places like UserInfo Endpoint:
> **5.3.2.  Successful UserInfo Response**
> &nbsp;&nbsp;&nbsp;&nbsp;If signed, the UserInfo Response SHOULD contain the Claims iss (issuer) and aud (audience) as members. The iss value SHOULD be the OP's Issuer Identifier URL. The aud value SHOULD be or include the RP's Client ID value.

`SHOULD be or include` seems that UserInfo MAY have multiple audiences as well.

UserInfo is intended to `return Claims about the authenticated End-User`. So naturally `aud` is not part of it. But in case the UserInfo Response is signed, It SHOULD contain `iss` and `aud`.

I thought it is good to mention that here to take it into account (if relevant).

Thanks @panva for considering the change.

**Comment by panva** [comment]
Yes it is relevant and already handled as such (as id_token with all expected claims).
