### ISSUE TITLE
Passing additional parameters to auth endpoint

### ISSUE THREAD

**Issue by neeravarora** [panva/node-oidc-provider#187]
I need to pass additional parameters to the auth end point something like the following 
`http://localhost:9000/auth?client_id=foo&response_type=id_token+token&scope=openid+email&nonce=foobar&prompt=login&newParam=abc . 

Is it possible to do the same ?

**Comment by panva** [comment]
Did you read the documentation at all before opening an issue?

- https://github.com/panva/node-oidc-provider/blob/master/docs/configuration.md#extending-authorization-with-custom-parameters
- https://github.com/panva/node-oidc-provider/blob/master/docs/configuration.md#extraparams

**Comment by neeravarora** [comment]
Thanks @panva
