### ISSUE TITLE
Determining ACR based on available claims

### ISSUE THREAD

**Issue by cmahna** [panva/node-oidc-provider#190]
I'm pretty new to node and I'm using the example provider as a starting point. What I'm trying to do is provide an ACR (as a level of assurance) based on what claims are available. For example LoA1 only requires first_name, and LoA2 requires everything for LoA1 plus last_name, birth_date etc. I've already implemented the LoA calculation in the claims() function in account.js. How would I go about taking that value and putting it into result.login.acr?

Thanks!

**Comment by panva** [comment]
Your interactions should push this to the result just like the timestamp, amr or user identifier

**Comment by panva** [comment]
Please keep in mind the example interactions dont include necessary features like csrf protection, request throttling and bot/abuse protection.

**Comment by cmahna** [comment]
got it, thanks

**Comment by panva** [comment]
You see ACR is by definition based off the authentication, not just the available claims, and the given acr you provide is only returned to that one authorization request results, all subsequent fall back to the first one available which should be like a "session" kind of acr.

**Comment by cmahna** [comment]
So would you recommend just defining a claim separate from ACR that would indicate the identity assurance level?
