### ISSUE TITLE
Cookies are occasionally missing on posting login

### ISSUE THREAD

**Issue by maxkorp** [panva/node-oidc-provider#193]
I suspect I have something configured incorrectly, but I've been digging for a number of hours and cant quite figure out why this is happening, and I'm hoping maybe you might have some insight or know of some common implementation pitfalls that might cause this.

My interaction base route and login route are ripped pretty plainly from the examples
```js
server.app.get('/interaction/:grant', (req, res) => {
   return provider.interactionDetails(req)
      .then((details) => {
        const view = (() => {
          switch (details.interaction.reason) {
            case 'consent_prompt':
            case 'client_not_authorized':
              return 'page/interaction';
            default:
              return 'page/login';
          }
        })();

        res.render(view, {details});
      });
  });
```

```js
server.app.post('/interaction/:grant/login', w(async (req, res, next) => {
    return provider.interactionDetails(req)
      .then((details) => {
        // do stuff, don't get here when it dies
      });
```

My login post route on rare occasion dies fetching the interaction details, and it appears the interaction cookie (_grant, the default) and sometimes the _session cookie are missing. Interesting is that to view the login page, the details much be  fetched succesfully using the _grant cookie so I'm not sure how they can get to that point and then not have the cookie. I realize that the cookies are pathed to `/interaction/:grant`, but the login page posts to `/interaction/:grant/login`. On at least one occasion, the user said they tried logging in twice and it failed, and on the third attempt it worked. 

Session is hooked up through redis, using the redis adapter from the examples. There is session turned on in express directly as well, I don't know if that could cause conflicts, but since this error occurs prior to the session lookup (in models/session, session.find, the assert fails since the cookie is missing). 

Not a lot to go off of I know, if there is more information that I can provide please let me know.

**Comment by panva** [comment]
- which oidc-provider major version?
- the cookies have an hour ttl, might that be the case you're hitting?
- does `interactionDetails` reject?

**Comment by panva** [comment]
closing for lack of feedback.
