### ISSUE TITLE
login from a "third party"

### ISSUE THREAD

**Issue by slavab89** [panva/node-oidc-provider#195]
I'll try to explain my use-case while also trying to understand the need and usage of `initiate_login_uri`.

Given that a user wants to reset his password OR he is partially registered (got invited any only needs to set his password) i would like to "auto" login him into the system after he does that.

First of all, is this a viable flow? Should i force him to re-enter his username and new password due to... something?

I am struggling with how to implement that. I have seen that it is possible to initiate a login from a third party using `initiate_login_uri` but couldnt find any trace about it in the OP (what did i miss?) as well as documentation on how exactly that works, where does the request go from the RP and what's included in it?

Maybe i should implement some custom password grant type that will auto-generate everything and then redirect to one predefined homepage? is this even viable?

**Comment by panva** [comment]
"[Initiating Login from a Third Party](http://openid.net/specs/openid-connect-core-1_0.html#ThirdPartyInitiatedLogin)" is a flow the OP starts by redirecting the user to RP's `initiate_login_uri` which is part of its client metadata. The client will then start a regular authz flow. Knowing the client and your issuer identifier you can construct the uri just fine on your own and there's nothing needed from the OP.

> First of all, is this a viable flow? Maybe i should implement some custom password grant type that will auto-generate everything and then redirect to one predefined homepage? is this even viable?

Not questions for me to answer. You know your landscape and should know what's secure given your system's capabilities, requirements and target audience.

As far as what's ok and what isn't - none of this is part of the specs and you should draw inspiration from other providers out there.

I handle pw reset initiated from an RP by providing a custom prompt which never resolves and i strip the errors of it. The presence of the prompt will always push the user to interactions with the auth request details (client, etc) and then after he goes to his inbox for a reset link no auth flow is needed. At the end of this flow i use client's initiate_login_uri if available, other client_uri to send the user back to the original RP.

Hope this helps.

**Comment by slavab89** [comment]
Thanks for the clarification.

So i'm trying to run in my head what youve suggested about the custom prompt. If this custom prompt is happening using the regular `authentication` flow then the user, possibly, wont have a session throwing him on the first interaction check of `no_session`, no?
Moreover, even if that somehow passes then when the user enters his username for the pw reset in the UI, the interaction will give him back a redirect to some interaction that would cause him to "lose" focus on his current view.
Or you meant for the flow that you've described to be a somewhat different custom authentication flow?

btw, you dont happen to have some example of such flow..?

**Comment by panva** [comment]
You know you can check for prompt presence even in interactions right? Regardless of the state the prompt will make sure user ends up in interactions. Handle the interaction as an anonymous pw reset flow every time and then resume the auth with no results. Strip the callback params (xcept for state) and the user will end up on an rp site with email in his inbox triggered by your interactions. Finishing the flow then has nothing to do with oidc. As a matter of fact why i do this over authz request is just the added benefit of having clients, validated uris and so on.
