### ISSUE TITLE
Documentation for client_id & ridirect_url dynamic configuration?

### ISSUE THREAD

**Issue by RedTn** [panva/node-oidc-provider#197]
Hi, great library!
Is there a standard way to register new client_ids without doing it at initialize? I know in your documentation you mentioned via the adapter [https://github.com/panva/node-oidc-provider/blob/master/docs/configuration.md#clients](https://github.com/panva/node-oidc-provider/blob/master/docs/configuration.md#clients). Is there a configuration that I'm missing or do I have to construct this myself? I was referencing this page: [https://connect2id.com/products/server/docs/guides/client-registration#example-minimal](https://connect2id.com/products/server/docs/guides/client-registration#example-minimal)

**Comment by panva** [comment]
OpenID Connect Dynamic Client Registration 1.0 is the spec/feature you want to enable.
