### ISSUE TITLE
Question about setting up a user registration

### ISSUE THREAD

**Issue by JoshAntBrown** [panva/node-oidc-provider#198]
Hey, I'm looking at adding a user registration journey to my app. I had a look and couldn't find any examples of this. I'm happy that I can create this as part of my express app and handle all the user creation logic myself.

I guess the last part I'd like to be able to do (which is where this library comes in) is once the user has finished registering then I'd want to redirect them to a default client along with their token and everything as if they had just logged in.

Is this something that is possible? How might I go about implementing that last step?

**Comment by panva** [comment]
There's no default client, you should have everything as part of an authorization request, even registration, that's where user interactions come in.

**Comment by JoshAntBrown** [comment]
Thanks for the quick response! That makes sense, although I'd like to have links that go straight to registration.

It looks like I could pass some flag inside of the state parameter that I could read to show the registration form rather than login although this feels a bit like a hack.

Is this the best option or is there a better parameter I could pass the authorisation endpoint to direct the user straight to the registration form?

**Comment by panva** [comment]
It's not usual for the RP to dictate the views. But ultimately you have the following mechanisms available

- custom prompt value
- JWT encoded state parameter you will handle in your interactions
- custom parameter you will handle in your interactions as well as the `interactionCheck `[https://github.com/panva/node-oidc-provider/blob/master/docs/configuration.md#interactioncheck] helper
