### ISSUE TITLE
Issue with Routes URLs on .well-known/openid-configuration config

### ISSUE THREAD

**Issue by robertymb** [panva/node-oidc-provider#199]
Hi there, I have a question related with [Issue #79](https://github.com/panva/node-oidc-provider/issues/79) 

I'm using **nginx** and your [sample](https://github.com/panva/node-oidc-provider/tree/master/example) with some modifications such as issuer, claims, and others,

The question is my **.well-known/openid-configuration** where the routes are defined, they all have HTTP protocol instead of HTTPs as I was expecting(srry maybe I misunderstood something in the process). I tried to understand lib, and couldn't find out [provider.js#108](https://github.com/panva/node-oidc-provider/blob/master/lib/provider.js#L108) where the [routerUrl](https://github.com/panva/node-oidc-provider/blob/master/lib/provider.js#L143) is coming from.  

In a better explanation, when I define the issuer:
`const provider = new Provider('https://host_name/',config);`

and listener
`.then(() => provider.app.listen(3000))`

so, my well-know generated file sumarized:
```
authorization_endpoint | "http://host_name:3000/auth"
issuer | "https://host_name/"
jwks_uri | "http://host_name:3000/certs"
registration_endpoint | "http://host_name:3000/reg"
```
The issuer is correct, but shoudln't all others routes be generated with the issuer as the prefix?

I already tried to define the routes configuration (think this is a bad pratice) as the following:
```
routes : {
   authorization: "https://host_name/auth"
}
```
but this always give me the following error:
```
{
    "error": "invalid_request",
    "error_description": "unrecognized route"
}
```

my nginx is listening on 443:
```
server {
		listen			443 		ssl;
		server_name 		host_name,
		
		ssl on;
		ssl_certificate			nginx.crt;
		ssl_certificate_key		nginx.key;
		
		ssl_protocols        SSLv3 TLSv1 TLSv1.1 TLSv1.2;
        	ssl_ciphers          HIGH:!aNULL:!MD5;

		location / {
            		proxy_pass_header Server;			
			proxy_set_header Host $host;
			proxy_set_header X-Real-IP $remote_addr;
			proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
			proxy_set_header X-Forwarded-Proto $scheme;
			
			proxy_connect_timeout 10;
			proxy_read_timeout 10;
			proxy_pass http://host_name:3000/;
        }
}
```

Note: I read the wiki and set `provider.app.proxy = true;`.

I tried to explain everything that I have done. I'll glady be happy if you could direct me what should I do.

Thx in advance,

**Comment by panva** [comment]
Hi @robertymb, thanks for reaching out. This indeed points to an issue with the headers and having the app trust them.

> I already tried to define the routes configuration (think this is a bad pratice) as the following:
> 
> routes : {
>    authorization: "https://host_name/auth"
> }

don't, this won't do a thing.

Can you push these proxy_set_header declarations in the server context?

```
proxy_set_header Host $host;
proxy_set_header X-Real-IP $remote_addr;
proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
proxy_set_header X-Forwarded-Proto $scheme;
```

**Comment by panva** [comment]
Anyway, i tried your example with few modifications and it works for me just fine.

```nginx
server {
	listen			443 		ssl;
	server_name 		op.panva.de;

	ssl on;
	ssl_certificate			/usr/local/etc/nginx/keys/op.panva.de.crt;
	ssl_certificate_key		/usr/local/etc/nginx/keys/op.panva.de.key;

	ssl_protocols        SSLv3 TLSv1 TLSv1.1 TLSv1.2;
	ssl_ciphers          HIGH:!aNULL:!MD5;

	location / {
		proxy_pass_header Server;
		proxy_set_header Host $host;
		proxy_set_header X-Real-IP $remote_addr;
		proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
		proxy_set_header X-Forwarded-Proto $scheme;

		proxy_connect_timeout 10;
		proxy_read_timeout 10;
		proxy_pass http://localhost:3000/;
  }
}
```

**Comment by robertymb** [comment]
Hi @panva, thanks for the quick reply.

I tried the new headers on the server context, but I got the same behavior.

The server starts, and everything seems to work. But whenever I get to the well-kown page, the "redirect" redirects me to host_name:3000 and I can't acess it (Secure Connection Failed), how you said looks like an  issue with the headers and having the app trust them (probably because 3000 is not secure but 443 is).

```
provider.app.middleware.unshift(async (ctx, next) => {
      if (ctx.secure) {
        await next();
      } else if (ctx.method === 'GET' || ctx.method === 'HEAD') {
        console.log('Got here: ',ctx.href);
        console.log('Got here: ',ctx.href.replace(/^http:\/\//i, 'https://'));
        ctx.redirect(ctx.href.replace(/^http:\/\//i, 'https://'));
      } else {
        ctx.body = {
          error: 'invalid_request',
          error_description: 'do yourself a favor and only use https',
        };
        ctx.status = 400;
      }
    });
  }
```

In console:
```
Got here:  http://host_name:3000/.well-known/openid-configuration
Got here:  https://host_name:3000/.well-known/openid-configuration

```

Also, If I comment the redirect line (ctx.redirect(ctx.href.replace(/^http:\/\//i, 'https://'));) and add await.next(), the URLs on the well-known still have the http protocol and the 3000 port, like this:

```
authorization_endpoint | "http://host_name:3000/auth"
issuer | "https://host_name"
jwks_uri | "http://host_name:3000/certs"
registration_endpoint | "http://host_name:3000/reg"
```

Maybe, I'm missing something. I don't know what yet.

**Comment by panva** [comment]
Again, see what i've posted above all works as expected. You gotta dig in your setup.

**Comment by robertymb** [comment]
@panva, it was setup problem.

I'm using nginx on Windows, and it create one process when nginx is started. After some `nginx -s reload` I had five processes running nginx, and it wasn't routing right.

So I kill them all, started again and know works. (I should have done on docker since beginning haha)

Thanks for all your help and time.

**Comment by panva** [comment]
@robertymb yw
