### ISSUE TITLE
Customization of where claims appear based on scope?

### ISSUE THREAD

**Issue by cmahna** [panva/node-oidc-provider#200]
In my implementation, I define a custom scope, but I don't want certain claims to appear in the id_token. I was able to achieve this by making a slight modification to the library but I was wondering if there's already a way to easily customize this through the configuration? Thanks!

**Comment by panva** [comment]
There probably is a way, not sure how easy tho, can I see your modification?

**Comment by panva** [comment]
The easiest way to remove claims from IdTokens would be something along these lines.

```js
const _claims = provider.IdToken.prototype.payload;
provider.IdToken.prototype.payload = function () {
  const ret = claims();
  ret.notintendedforidtoken = undefined;
  return ret;
}
```

**Comment by cmahna** [comment]
I did something like this where you can define a scope like a claims parameter:
https://github.com/cmahna/node-oidc-provider/commit/37d5277fd939ce987582a471a5b6f8d6b5bc26d0

Probably not the best, I'm pretty inexperienced with JS.

**Comment by panva** [comment]
Ok, can you describe the behavior in words, what should be made possible with the configuration? If simply not including some claims in the id token, you can use the snippet above (in theory, didn't test yet). If something more i'd need more details so that the feature can be included.

**Comment by panva** [comment]
Once a release with https://github.com/panva/node-oidc-provider/commit/58d281fdde3af5af6d73d17c7f70f83362b0cfa3 is published you should have enough details in the findById() helper and its linked claims() call to decide which claims to return.

**Comment by cmahna** [comment]
Perfect, thanks

**Comment by panva** [comment]
And please keep in mind oidc-provider will still attempt to mask the claims depending on the scope automatically. This is intended for fine-tuning or avoiding to load external claims in some cases.
