### ISSUE TITLE
Handling invalid username / password

### ISSUE THREAD

**Issue by robtweed** [panva/node-oidc-provider#203]
I've added a follow-up question to
https://github.com/panva/node-oidc-provider/issues/149

I'm unfortunately unable to figure out how to handle invalid entry of usernames/passwords in the login form so the user is given an appropriate error and asked to re-try.  Any pointers to examples would be greatly welcomed

**Comment by panva** [comment]
I'm sorry but user interactions, user accounts and your login/registration flow is outside of the scope of a protocol implementation library. May I suggest to implement these views without considering oidc first and then hook them in. If such a system is not something you're up to then maybe a you're looking for a different solution such as a commercial offering or one that provides less flexibility but includes a full account management system.
