### ISSUE TITLE
Central error handling (renderError)

### ISSUE THREAD

**Issue by telemmaite** [panva/node-oidc-provider#204]
I am checking a few things into my interaction callbacks when something is missing I just throw error.
Normally it is successfully caught by renderError (which I also have redefined for me).
However when I throw error in `'/interaction/:grant'` or for example here ->
https://github.com/panva/node-oidc-provider/blob/master/example/index.js#L60
Error will directly dump as UnhandledPromiseRejectionWarning.

**Comment by panva** [comment]
You've just described a perfectly expected behavior since user interaction space is not part of this library. Please handle errors just like you would in any other app?
