### ISSUE TITLE
Redis adapter from example->upsert

### ISSUE THREAD

**Issue by telemmaite** [panva/node-oidc-provider#206]
I know that it is example and it is up to us to implement it...
https://github.com/panva/node-oidc-provider/blob/master/example/adapters/redis.js#L44

What I see is we expect async behavior of this function when we call provider.save
https://github.com/panva/node-oidc-provider/blob/master/lib/models/session.js#L52
https://github.com/panva/node-oidc-provider/blob/master/lib/shared/session.js#L16
https://github.com/panva/node-oidc-provider/blob/master/lib/actions/authorization/interactions.js#L188

Problem is that `multi.exec` is not handling (in the example!) the callback.
https://github.com/panva/node-oidc-provider/blob/master/example/adapters/redis.js#L67

This could lead to some unexpected behavior, as [Issue-193](https://github.com/panva/node-oidc-provider/issues/193)

**Comment by panva** [comment]
Hi @telemmaite, ioredis pipeline `exec` returns a promise when called without a callback function, so how is it not handled exactly?

**Comment by telemmaite** [comment]
OK my bad then, I did not see `// exec also returns a Promise:`. from ioredis documentation
I was pretty sure same as **Issue-193** that my session is sometimes not saved on time as expected.
Will have to search elsewhere for my problem.
