### ISSUE TITLE
Native client with PKCE in 2.13.0

### ISSUE THREAD

**Issue by wilsonjackson** [panva/node-oidc-provider#207]
Hi there. First off, this is a great library and I really appreciate the effort you've put into it.

I'm building an OP that needs to support both web and native clients. For native clients, I'm following the OAuth 2.0 for Native Apps BCP spec and attempting to use PKCE for the token requests. The intent is to use AppAuth-Android and AppAuth-iOS in the apps.

From #83 I gather that the AppAuth library doesn't send a `client_secret`, but it doesn't look like the changes referenced in that issue have made it into the 2.x releases, so if I try to send a test request with a `code_verifier` and no `client_secret` I get this back:

```
{
    "error": "invalid_request",
    "error_description": "client_secret must be provided in the body"
}
```

Is there a plan for fix this? Or should I be doing something differently? I'd be happy to submit a PR if all that needs to be done is porting the changes from 1.x to 2.x.

**Comment by wilsonjackson** [comment]
Actually, nevermind, I just found in the changelog where you specify to use method `none` and that works perfectly.

**Comment by fiznool** [comment]
I also had this issue. The fix in more detail: add the property `token_endpoint_auth_method: 'none'` to your client configuration.

There is also an `application_type: 'native'` property which should be set too for native apps.
Putting it all together:

``` js
const config = {
  clients: [{
    application_type: 'native',
    client_id: 'some-mobile-app',
    redirect_uris: ['com.reverse.domain://authcallback'],
    token_endpoint_auth_method: 'none'
  }]
};
```
