### ISSUE TITLE
Rotation of Initial access token?

### ISSUE THREAD

**Issue by codestorycooked** [panva/node-oidc-provider#208]
Hi @panva 

Can we have array of Initial access token for rotation ?
```
 this.features = {
            alwaysIssueRefresh: true,
            devInteractions: false,
            introspection: true,
            registration: { initialAccessToken:  ['ONE','TWO'] },

            registrationManagement: true
        };
```

**Comment by panva** [comment]
Just set the value to true which makes them load from your adapter.

```js
const configuration = { features: { registration: { initialAccessToken: true } } };

// adding a token and retrieving it's value
new (provider.InitialAccessToken)({}).save().then(console.log);
```

**Comment by codestorycooked** [comment]
Thanks But I don't want to use an adapter. Is it possible the other way( I meant without using an adapter) ?

**Comment by panva** [comment]
How will you ever run a production system without an adapter where sessions and tokens are bound to memory in each process?

I will accept a PR with what you are suggesting, assuming it is test covered.

**Comment by codestorycooked** [comment]
Hell @panva  can I create custom Initial Access Token and store it in the database. If not is there any recommendation?
