### ISSUE TITLE
invalid_request - could not parse the claims parameter JSON

### ISSUE THREAD

**Issue by senseibaka** [panva/node-oidc-provider#209]
Hi there,

Note: I am using `v1.x.x`, but I suspect this issue might occur in `v2.x.x` too.

Recently I've been messing around with submitting a signed request JWT to the `/auth` endpoint.
I'm using your `node-openid-client` and its handy `requestObject` function.

When the signed JWT contains claims, things get interesting.

After all the interaction stuff, my client ends up being redirected to the resume endpoint, `/auth/:grantId`.

From there, `authorization/check_claims.js` emits an error: `could not parse the claims parameter JSON`.

Now, I did a bit of digging and figured out that this seems to caused by a combination of two things.
* `shared/resume.js`:
```javascript
this.query = j(this.cookies.get(provider.cookieName('resume'), cookieOptions));
```
* and koa's query parameter from `request.js`, which doesn't support nested properties:
```javascript
set query(obj) {
  this.querystring = qs.stringify(obj);
},
```

I suspect this might apply to `v2.x.x` as well because of this line: https://github.com/panva/node-oidc-provider/blob/170ec898275355de3f3a0091315e40c4a4513333/lib/shared/resume.js#L24

Here are a couple of workarounds:
1. Make use of `koa-qs`, which overrides the behaviour of `query` to support nested objects
2. `JSON.stringify` the original `claims` property, so that it's treated as a string, rather than an object

So, having said all that, I guess I have a couple of questions:
* Does it seem like I'm doing something wrong along the way?
* Is this actually a bug?

Thanks

**Comment by panva** [comment]
Somewhere along the way this was fixed already as 2.x is not affected. I believe i ended up stringifying the claims parameter coming from a signed jwt so that downstream handling can remain the same for both ways of passing the param (param and request).

**Comment by senseibaka** [comment]
Thanks

I look forward to when Lambda supports node 8 (whenever that'll be...) so I can upgrade to `v2.x.x` 😛 
In the meantime, `koa-qs` seems to be the way to go.

**Comment by panva** [comment]
You can also send the claims parameter in the jwt as encoded json in 1.x, although not intended it will continue to work even in future releases.
