### ISSUE TITLE
Question: Database Maintanance

### ISSUE THREAD

**Issue by JochenAtWork** [panva/node-oidc-provider#210]
Actually I can't really believe that this question has not yet been answered but I'm not able to find the answer. So here's the point: if you use the provider together with a MongoDb adapter the collections seem grow indefinitly. Only some data has a time tag (e.g. expiration time for access tokens) but for most entities there seems to be no easy way to see if its is obsolete and could be deleted.

Any hints on how to get rid of obsolete stuff in the persistence?

Thanks in Advance

Jochen

**Comment by panva** [comment]
iirc all collections with the exception of clients and their registration access tokens do have a ttl index and corresponding values for it, at least in the example adapter

in any case - the expiresIn argument pushed to adapter#upsert is what you should be using to set your deletion policies as documented.
