### ISSUE TITLE
Override save and find method`

### ISSUE THREAD

**Issue by codestorycooked** [panva/node-oidc-provider#212]
@panva 
I want to override `save` and `find` method of baseToken. This is very basic example I came up with. But `find` is not working as expected. Any ideas or example? Thank you so much for your help.
```
 this.myProvider.InitialAccessToken.prototype.save = async function () {
      console.log('Token Saved');
    };

    this.myProvider.InitialAccessToken.prototype.find =  async function (token = '', { ignoreExpiration = false } = {}) {
      if (CommonUtils.isNullOrEmpty(token)) {
        console.log('Token not found');
      }
      console.log('Token found');
      return true;
    };
    new (this.myProvider.InitialAccessToken)({}).save().then(console.log);
```

**Comment by panva** [comment]
@codestorycooked I don't understand what you're trying to achieve. 

https://github.com/panva/node-oidc-provider/blob/master/lib/models/base_token.js#L110-L184 shows the BaseToken public methods that you can safely overload so long as you can follow what they do, with these a change to token structure is possible.

**Comment by panva** [comment]
also find is not an instance method, you have to change that one on the constructor. e.g.:

```js
// instance method
provider.AccessToken.prototype.getValueAndPayload = ...
// class method
provider.AccessToken.prototype.constructor.getJtiFromToken = ...
provider.AccessToken.prototype.constructor.verify = ...
```

**Comment by codestorycooked** [comment]
@panva  thanks a ton for that last example. I was struggling with find method which was on constructor.
