### ISSUE TITLE
Clients defined in configuration expire in cache and don't get re-found

### ISSUE THREAD

**Issue by jpavlick** [panva/node-oidc-provider#213]
Hey @panva, thanks for creating this codebase - it has been really useful for our implementation of oidc and has been very nice to work with.

We are using a combination of a homebuilt Postgres adapter and also defining a few clients in the config on startup. 
```  
await provider.initialize({
    adapter: Adapter,
    clients: config.get('clients'),
    keystore: keys
  });
```
It appears that the clients get added to the client cache on startup, but upon TTL expiration cannot be found again via the adapter. This doesn't happen with clients stored in Postgres. Is this behavior expected? I would have expected that if clients were provided via configuration there would be some method for re-adding them to the cache. As it is now, there is no backup for when they expire.

**Comment by panva** [comment]
Hello @jpavlick, clients coming from initialize should not expire at all, that's unintended and definitely a bug.

**Comment by panva** [comment]
Can you try with master and confirm this change resolves your issue?

**Comment by jpavlick** [comment]
Hey @panva, that fix works! Thanks for fixing it so quickly.
For what it's worth, we aren't planning on keeping very many initialize clients, but there are a few clients that don't belong in our organization's client datastore (such as our example client, which we'd like to keep around for testing).
