### ISSUE TITLE
accountId in interaction details

### ISSUE THREAD

**Issue by mcnijman** [panva/node-oidc-provider#214]
Hi,

Thanks for your awesome work with this module. Probably I just overlooked this, but I've been looking for too long now. If I understand correctly the default behaviour is to show the consent page if there is a logged in session and the client making the authorization request isn't authorized yet. With the knowledge that there is in fact a logged in user session, it would be likely possible to get the accountId somewhere, but I can't find it.

In your example, a location of where I would like to access the account would be here:

https://github.com/panva/node-oidc-provider/blob/58d281fdde3af5af6d73d17c7f70f83362b0cfa3/example/index.js#L94-L98

Thanks for your help.

**Comment by panva** [comment]
You might as well read the value of the op session cookie, load the op session and read it there. But I agree that's too much hassle, i'll add the accountId into the interactionDetails when it is available.

**Comment by mcnijman** [comment]
Thanks! I got it working like this:

```javascript
const session = await provider.Session.get(ctx);
const account = await Account.findById(ctx, session.account);
```

Not that much hassle, but making it available in the interactionDetails would be a great anyways.

**Comment by panva** [comment]
Actually i gave it a shot and realized its not as simple, it is to put in, but might be misused in cases such as login prompts etc. so i’ll just provide a similar helper to load the session details and document it. So you’re not far off from what i’ll bring forward
