### ISSUE TITLE
session check errors on "greet frame" message

### ISSUE THREAD

**Issue by sa-emcvey** [panva/node-oidc-provider#215]
Whenever I load a tab where a user is already logged in, so the cookie, session state, etc are already set and no redirects are necessary, I get an error from the session check. The very first message the iFrame receives is a "greet frame" message. When that is split into parts here:
```
 var message_parts = e.data.split(' ');
var clientId = message_parts[0];
var actual = message_parts[1];
```
There is actually only one part, "Greet frame," so clientId is incorrect and actual is undefined. 

When you then try to get the salt by splitting actual: `var salt = actual.split('.')[1];` an error is thrown: `TypeError: Cannot read property 'split' of undefined`.

This is causing oidc-client-js to stop sending messages, and for chrome it never restarts itself (for FireFox it does, so it seems there may be some sort of bug with that library).

Regardless of oidc-client-js issues, though, it seems to me like the session check iFrame should be able to handle the "greet frame" message better, as it is standard for most browsers.

**Comment by panva** [comment]
i’m not aware of any standard that tells browsers to send “greet frame” messages. The fact that this works with the example linked in readme tells me that much. Could you elaborate?

It seems this is indeed a problem with oidc-client-js as the handling in the frame is as intended - invalid message formats get responded to with an error.

**Comment by sa-emcvey** [comment]
My bad, I mistook it as a browser thing but it is actually fullstory, a third party user analytics tool we use. In the last section of [this page](https://help.fullstory.com/using/recording-iframes?from_search=21967143), they mention something about using postMessage, and how that can cause problems with others also using it. An excerpt:
```
FullStory must use the postMessageAPI to communicate recording data from frames up to the parent window, because these frames may be on different domains.
Unfortunately, this communication mechanism has a design flaw in that there's no formal way to designate scripts. Thus, multiple scripts communicating over this channel will receive each others' messages and must find a way to exclude those not intended for it.
```

While the main issue here seems to be that oidc-client-js stops sending the messages on Firefox but not on Chrome after it gets the error, I don't necessarily agree that automatically accepting and parsing all messages regardless of source or format should be the intended behavior. I think there should be some attempt to filter by expected message. While unlikely, if under some circumstance a message was received that was not intended for session check but did match the required format, it could incorrectly set the status to changed.

**Comment by panva** [comment]
Syntactically invalid messages are to be rejected as per [spec](https://openid.net/specs/openid-connect-session-1_0.html#OPiframe).

I’m sorry you’re running into issues but they seem to be related to a specific environment. 

For one a tracking library could have a mechanism like nofollow to ignore a certain frame. Then you might also defer loading this frame to after tracking was initialized. 

Now as for a hack that won’t require you to run a fork, look up pre and post middleware in the documentation and modify the action’s response body in the middleware’s after await section for the check_session path.

**Comment by sa-emcvey** [comment]
Do you mean modify the response so that it responds with a check session iFrame that is able to handle the other postMessages? I'll give that a try, just want to confirm that's what you mean. Thanks for the help.

**Comment by panva** [comment]
Yep.

**Comment by jdiamond** [comment]
The spec also says this:

> The OP iframe MUST enforce that the caller has the same origin as its parent frame. It MUST reject postMessage requests from any other source origin.

I don't see the example in the spec doing that or the code in this repo.

Would checking the origin prevent this error from happening?

MDN has a pretty clear warning that you should always check the sender's origin in the docs for postMessage here:

https://developer.mozilla.org/en-US/docs/Web/API/Window/postMessage#Security_concerns

**Comment by panva** [comment]
I realized the origin assertion is missing too yesterday. Unfortunately from the top of my head i don’t seem to be able to check that the parent origin is the same as message origin. See #216, suggestions are welcome

Also, if the message is triggered from a js loaded in the parent page the origin would be the same.

**Comment by panva** [comment]
Thinking about this some more i believe there should be no issue so long as the RP frame is properly implemented to only accept and handle messages from the right origin.

The OP frame responds with messages to the message source, the RP frame. That frame ought to have no tracking library of yours included tbh. If a message is received from the parent window and error is responded with that one should cause no harm since the handling of the logout logic and the states lies with the RP Frame where a fixed OP origin check should be present.

**Comment by panva** [comment]
I've implemented some more sanity checks for the message format and the message origin check in 6c27f10.

Note that this does not follow the current normative requirement since that one is not possible with the same-origin restrictions in current browsers but does at least provide some sanity check to avoid sending 'changed' when it should be 'error' if the origin is clearly not allowed.

> The OP iframe MUST enforce that the caller has the same origin as its parent frame. It MUST reject postMessage requests from any other source origin.
