### ISSUE TITLE
User should not be able to skip authentication form because of set cookies

### ISSUE THREAD

**Issue by hoeselm** [panva/node-oidc-provider#217]
Hi,

How can one configure the oidc-provider so that even though the user already filled out and submitted the authentication form once, the user has to fill it out again when coming back to the form?

I want this behaviour as the user should be possible to login with other credentials, even so when the user did not logout explicitly. Current behaviour is that the user is redirected immediately, leaving him with no change entering different credentials.

This seems to be an easy to solve problem, but I haven't come around yet. While I tried different things shouldn't setting the maxAge of the cookies.short let's say to 60 seconds work, as it is responsible for passing of authorization details to interaction (https://github.com/panva/node-oidc-provider/blob/master/docs/configuration.md#cookiesshort)?

Thank you for your help!

**Comment by panva** [comment]
Why don't you define your policy in the interactionCheck configuration helper -
 https://github.com/panva/node-oidc-provider/blob/master/docs/configuration.md#interactioncheck

simply return a login_required error whenever you wish to bypass the oidc-provider (long cookie) session
