### ISSUE TITLE
[Question] When is RP shown an error page vs being redirected?

### ISSUE THREAD

**Issue by mihaerzen** [panva/node-oidc-provider#219]
It seems there are two different ways how errors are reported to the RP:

1. Showing a `400` status page with `error` and `error_description`.
2. Redirect with `error` and `error_description` as a query parameters.

In which cases should an RP see the error page and when it should be redirected back?

I can see this described in the standard, however, my confusion came to place when I was passing the wrong `response_type` parameter. I was expecting to see an error page with `invalid_request` error, however, I got redirected with `unsupported_response_type` error.

Thank you for your clarification.

**Comment by panva** [comment]
When client or it's redirect uri cannot be verified to be whitelisted the spec prohibits a redirect back to the specified uri. In those cases error is rendered and you customize the way it looks for the user by searching the configuration documentation. It's the `renderError` configuration option. In all other cases during authorization flow when an error is raised and the uri and client are ok, the error is not displayed but instead pushed on to the RP.

**Comment by mihaerzen** [comment]
Perfect! Thx a lot for your explanation.
