### ISSUE TITLE
[Question] Client credentials flow does returns an access token rather than a JWT

### ISSUE THREAD

**Issue by SokratisVidros** [panva/node-oidc-provider#220]
Hi,

I am executing a client credentials flow by posting at http://oidc.test/oidc/token using `grant_type=client_credentials` as a parameter. The client is configured with `response_types: ['none']`. The response is an access token but not a JWT id_token token. That is, API clients can't verify the request via the id_token on their side as expected.

Is this a configuration issue or is it by spec?

Thanks in advance,
Sokratis

**Comment by panva** [comment]
`oidc-provider` choses to implement only opaque tokens (access, refresh, codes), not JWTs. If jwt tokens are what you need please look into #93 where a public `BaseToken` interface was defined that allows you to change the way tokens are generated and serialized.

**Comment by panva** [comment]
client_credentials is also not an OIDC feature hence no id token - the token is not related to a given user/identity, API clients using client credential tokens can use introspection to verify the token.

**Comment by SokratisVidros** [comment]
Makes sense. Thanks a lot!

**Comment by panva** [comment]
#294 introduces the option to have any token returned to an RP as a JWT. Calling for comments and reviews.
