### ISSUE TITLE
/session/check relies on availability of github

### ISSUE THREAD

**Issue by nico-schunke** [panva/node-oidc-provider#221]
Hi Filip,

we just noticed that the helper to check whether it is allowed to set thirdparty cookies (https://github.com/mindmup/3rdpartycookiecheck) ist hard coded at the /session/check action: https://github.com/panva/node-oidc-provider/blob/master/lib/actions/check_session.js#L86

To be honest I do not want to overwrite the whole logic to replace that url, called by the IFrame. Do you think there is an easy way to configure?

(btw: same applies for the sha256 script: https://github.com/panva/node-oidc-provider/blob/master/lib/actions/check_session.js#L23)

Personally I would like to host that scripts on my own CDN and take care about the availability by my own.

Thanks for feedbacking!

Best Nico

**Comment by panva** [comment]
If you wish to host these on your own (knowing the implications, such as the point of the 3rd party cookie check actually being on a different domain for it to be able to do what it does) you can [register a middleware](https://github.com/panva/node-oidc-provider/blob/master/docs/configuration.md#pre--and-post-middlewares) in the koa app stack and change the response body. Such as

```
provider.app.middleware.unshift(async (ctx, next) => {
  await next();

  if (ctx._matchedRouteName === 'check_session') {
    ctx.body = ctx.body.replace(...) // or similar, modifying the body replacing the script URIs
  }
});
```

Currently I don't plan to offer option to build this in unless there's a strong demand for it.

**Comment by nico-schunke** [comment]
Thanks for your answer. Your suggestion would work for me, tough it seems like to be a bit "hacky" to me. But anyways it does it fit my needs.

**Comment by panva** [comment]
You might say it is, but there's unfortunately not enough bandwith for me to give a configuration option for everything. If you want you could submit a PR where these external resources are in the configuration and can be overwritten. Your call.

**Comment by nico-schunke** [comment]
Understood. We'll think about when we come across again. Right now it is not really a showstopper. Thanks for your efforts and taking care.
