### ISSUE TITLE
Custom Scopes

### ISSUE THREAD

**Issue by codestorycooked** [panva/node-oidc-provider#222]
How do add Custom Scope like Auth0? I tried to add custom scopes to `consent` config but `check_scope.js` intersects it and removes scope added to `consent` config.

**Comment by panva** [comment]
Hi, please read the configuration section of the docs.

**Comment by codestorycooked** [comment]
In the configuration, we have set these scopes "openid profile scope1 scope2".
Our ID provider is sending us scope5 for a particular user.
I am trying to override and send this scope5 in `consent` in interactionFinished
```
consent{
scope='openid profile scope1 scope2 scope5'
}
```
But when i introspect the `access_token` I get only `openid profile scope1 scope2`

This is due to `check_scope.js` intersecting and removes scope5 in this case.

**Comment by panva** [comment]
1. in the configuration you're supposed to provide an array of strings, not a string.
2. The rest I'm afraid I don't follow, please try and provide a clear description of what you think is wrong and why.

**Comment by panva** [comment]
You need to add all supported scopes in the configuration, otherwise unrecognized scopes are ignored. This is intended.

**Comment by codestorycooked** [comment]
Is there any way to override this behavior?
