### ISSUE TITLE
suppress logout prompt

### ISSUE THREAD

**Issue by vikas-ss** [panva/node-oidc-provider#223]
Is there a way to bypass logout confirm "Do you want to logout" during session end endpoint?

**Comment by panva** [comment]
You can use the [logoutSource](https://github.com/panva/node-oidc-provider/blob/v2.14.0/docs/configuration.md#logoutsource) config option to render a self-submitting form.

**Comment by elendirx** [comment]
Hi, first let me say thanks again for this awesome library.
I'm trying to skip logout prompt too. Yes I can achieve that with a self-submitting form, but I feel that such extra step is not necessary. Do you think it would be worth creating a pull request with added config to skip rendering logout prompt page completely?

**Comment by panva** [comment]
The auto submitting form is in my opinion sufficient enough solution that does not require an extra branch and logic that would have to be tested and cared for.

**Comment by elendirx** [comment]
Ok, thanks for your opinion and quick response.
