### ISSUE TITLE
How to change header alg value in access token to be "RS256"

### ISSUE THREAD

**Issue by ashrafakl** [panva/node-oidc-provider#224]
Hi,

I'm using oidc-provider with mongodb adapter, with the following clients options

```js
[
    {
        application_type: 'web',
        client_id: 'foo',
        client_secret: 'bar',            
        grant_types: ['authorization_code', 'refresh_token'],
        response_types: ['code'],
        redirect_uris: ['http://localhost/testapp'],
        token_endpoint_auth_method: 'client_secret_post',
        token_endpoint_auth_signing_alg: 'RS256',
        id_token_signed_response_alg: 'RS256'
    }    
]
```

I checked  the access_token document created after a user logged-in successfully, I decoded the header value, the header alg value is equal to "none" not "RS256".
So there are something wrong or missing in client configuration ?

Thanks 

Ashraf Akl

**Comment by panva** [comment]
Hi @ashrafakl,

That's just leftovers from the way models were stored in 1.x (as signed JWTs), pay no attention to the header value. Access Tokens returned are opaque anyway, they are not JWTs. I only use JWT format (with no signatures) to have a unified model structure.

Sorry for the confusion, I plan to revise the data model completely in 3.x

**Comment by ashrafakl** [comment]
Thanks @panva for your quick reply
 
It is possible to change this behaviour by extending the BaseToken class?

**Comment by panva** [comment]
If jwt tokens are what you need please look into #93 where a public BaseToken interface was defined that allows you to change the way tokens are generated and serialized.
