### ISSUE TITLE
Can I call introspection method internally?

### ISSUE THREAD

**Issue by javiersuazomatus** [panva/node-oidc-provider#225]
I 'm integrating OIDC provider in a loopback project. I need to protect some endpoints through a middleware method that validates the access_token (or Bearer token) contained in the requests. How can i do this without calling the introspection endpoint?

**Comment by panva** [comment]
Yeah you might, it depends.

Are you running within the same node process? If so, just `provider.AccessToken.find(bearer)`. If not, look at the internals and just query your storage.

**Comment by javiersuazomatus** [comment]
Thank you very much for your answer. My question was not the most appropriate. Can I call the introspection method internally (the resource server and authorization server are the same server) and obtain the same response?

Example Response:

`{
    "active": true,
    "token_type": "access_token",
    "sub": "asdf@asd.as",
    "client_id": "modyo",
    "exp": 1520812924,
    "iat": 1520809324,
    "iss": "http://localhost:3000/oidc",
    "jti": "ZDBjMmRiZGQtYTVjMC00MjgyLWJlOWYtMjAzZGU0ZjYyNTM2",
    "scope": "openid"
}`

**Comment by panva** [comment]
no you can't, you can look at what the introspection method does and just mimic that with what `provider.AccessToken.find(bearer)` yields to you.
