### ISSUE TITLE
Reusable Refresh Token

### ISSUE THREAD

**Issue by javiersuazomatus** [panva/node-oidc-provider#227]
By default, a refresh token its is mark as consumed when is used to obtain a new access_token by a call to refresh token endpoint. Can I configure the provider to obtain new access tokens using a refresh token more than once?

**Comment by panva** [comment]
Hi @javiersuazomatus,

yes you can. 
https://github.com/panva/node-oidc-provider/blob/v2.14.0/docs/configuration.md#refreshtokenrotation set to "none" as per https://github.com/panva/node-oidc-provider/blob/v2.14.0/lib/helpers/defaults.js#L492-L506

**Comment by javiersuazomatus** [comment]
Thank you very much for your answer. Greetings from Chile!
