### ISSUE TITLE
authorization_endpoint response header with helmet/koa-helmet

### ISSUE THREAD

**Issue by mogeda** [panva/node-oidc-provider#231]
I'm using koa-helmet like below.
const helmet = require('koa-helmet');
app.use(helmet());
I tested endpoints and validated that extra headers starting with 'X-' were added as expected except for authorization_endpoint(/auth). Is there any special reason that authorization_endpoint was skipped for this? Thanks.

**Comment by panva** [comment]
can't reproduce your issue @mogeda 


```js
const Provider = require('.');
const helmet = require('koa-helmet');
const Koa = require('Koa');
const mount = require('koa-mount');
const oidc = new Provider('http://localhost:3000');
const koaApp = new Koa();
koaApp.use(helmet());

(async () => {
  await oidc.initialize();
  koaApp.use(mount(oidc.app));
  koaApp.listen(3000);
})();
```

```
curl -i http://localhost:3000/auth                            
HTTP/1.1 400 Bad Request
X-DNS-Prefetch-Control: off
X-Frame-Options: SAMEORIGIN
Strict-Transport-Security: max-age=15552000; includeSubDomains
X-Download-Options: noopen
X-Content-Type-Options: nosniff
X-XSS-Protection: 1; mode=block
Set-Cookie: _session=542bf222-a9c7-4271-8c98-a4c99b3dca05; path=/; expires=Sun, 17 Mar 2019 03:27:31 GMT; httponly
Content-Type: text/html; charset=utf-8
Content-Length: 248
Date: Fri, 16 Mar 2018 21:27:31 GMT
Connection: keep-alive
```

It's all there.

**Comment by mogeda** [comment]
I was using app in oidc like below instead of mounting

(async () => {
  await oidc.initialize();
  oidc.app.use(helmet());
  oidc.app.listen(3000);
})();

**Comment by mogeda** [comment]
I'm all set now, thanks a lot.

**Comment by panva** [comment]
Doing that you've been pushing helmet at the end of the middleware stack, authorization which doensn't await is one where it is clear, any error handled call would be another.
