### ISSUE TITLE
EAP

### ISSUE THREAD

**Issue by apowers313** [panva/node-oidc-provider#232]
I want to implement the FIDO bits of [EAP](http://openid.net/specs/openid-connect-eap-acr-values-1_0.html). Can you give me some hints of where to hook in to add acr values?

**Comment by panva** [comment]
Hi @apowers313 

1) configure the OP to support your values

```js
new Provider('...', {
  acrValues: [
    '0', // or 'session' to indicate the lowest "none" level
    'acr1',
    'acr2',
  ]
});
```

2) When acr is requested, as a result of the subsequent interaction pass the acr using the `provider.interactionFinished` helper, or other means using your adapter.

```js
provider.interactionFinished({
  login: { account, acr, remember, ts },
});
```
