### ISSUE TITLE
How to get SSO between 2 native apps (AppAuth samples)?

### ISSUE THREAD

**Issue by Alex-d14** [panva/node-oidc-provider#241]
Hi,

First, thanks for this great library.

I'm trying to test the [AppAuth](https://github.com/openid?q=AppAuth) sample apps (iOS and Android) against a Node.js web app based on "node-oidc-provider".

I have 3 apps: native sample app 1, native sample app 2 (both are using the same client id) and another web app (a different client id).

Here are the steps I'm following:
- Sign-in using sample app 1 
- Type username and password 
- Sign-in using the web app in Chrome mobile
- Click the "Authorize" button

I don't have to enter my username and password again, so the SSO works.

Then I'm trying to sign-in using sample app 2, but I'm asked for my username and password again: the SSO doesn't work.

I noticed the following:
- If I press "cancel" in sample app 2 (instead of typing my username and password) then the app is able to get an ID Token anyway
- If I set the "prompt" parameter value to "consent" in sample app 2 then it works (I can see the "Authorize" button), but I'm getting a "_prompt consent was not resolved_" error the next time I sign-out completely and try to sign-in again.
 
Is that an expected behavior?

Thanks for your help,

Best regards,
Alex.

**Comment by panva** [comment]
Hi @Alex-d14, if you're seeing SSO between one app and a browser then everything works as expected and issues are likely related to the specific AppAuth libraries (they vary from platform to platform) or their setup of yours.

NB: [this](https://github.com/panva/panva.github.io/blob/master/_drafts/appauth.md) unpublished article might be useful to you to see the common issues. On iOS for example, it takes time for cookies to be synced between multiple SFAuthenticationSession instances.

**Comment by Alex-d14** [comment]
Thanks for your answer. I'll try to dig into it.

**Comment by panva** [comment]
> If I press "cancel" in sample app 2 (instead of typing my username and password) then the app is able to get an ID Token anyway

1) This would not happen if both apps would use different clients (as they should!). Before anything else please fix this on your end.
2) It is indicative of one thing - by the time you go to authorize the session is not synced between the apps, but by the time you press cancel it is.
3) There's a bug in the native app forced interaction check that i'll look into.

**Comment by panva** [comment]
3) should be fixed in master
