### ISSUE TITLE
extraClientMetadata when loading clients async

### ISSUE THREAD

**Issue by ulrikstrid** [panva/node-oidc-provider#247]
I have the following in my config:
```js
    extraClientMetadata: {
      properties: ["modules"],
      validator: (key, value, metadata) => {
        metadata[key] = value;

        return metadata;
      }
    }
```

When I load a client the validator doesn't even get called, I have checked with a console.log in the function. And the modules property doesn't get added. Is this as intended?

**Comment by panva** [comment]
first, sanity check, what's your oidc-provider version?

**Comment by ulrikstrid** [comment]
I am so sorry, I was 1 version off and didn't realize this feature was so resent.
