### ISSUE TITLE
oops something went wrong when calling /me?access_token=XXXXXX

### ISSUE THREAD

**Issue by jonathan-casarrubias** [panva/node-oidc-provider#256]
Hi,

Sorry for disturbing creating an issue but I'm really close to finishing this implementation, to the day I'm able to do the entire flow

Using the https://openidconnect.net/

I'm able to:

1.- Configure using the .well-known configuration
2.- To login
3.- And to get the access_token
4.- And token_id.
5.- And able to successfully verify the token

But, when I use the access_token to get the user data calling the /me method, I get `oops something went wrong`

I have debugged and I see the findById method is being called, within the claims() method I do return the user values

![image](https://user-images.githubusercontent.com/1533239/39087514-ccd262c6-4567-11e8-9486-67350b377bb8.png)

But just after that moment I got the error, being extremely difficult to know what is referring to.

My Logs:

```json
// Loggin the found user within the findById method
{ 
  "_id": "5ac3d8139f27c41b933e139a",
  "fullname": "Jonathan Casarrubias",
  "email": "jcasarrubias@mean.expert"
}
// Then the claims() method returns the following
{
  "sub": "5ac3d8139f27c41b933e139a",
  "email": "jcasarrubias@mean.expert"
}
```

So I'm assuming is correctly configured,  but I can't get the user data from the /me method.

Is there any missing configuration or what might be throw that `oops something went wrong` error?

I would really appreciate any guidance to finish this implementation...

Cheers
Jon

**Comment by panva** [comment]
Can you post your provider configuration and the client metadata? Also logs when running the op with DEBUG=oidc-provider:*

**Comment by jonathan-casarrubias** [comment]
Sure...

Configuration:

```js
import {Service, Inject} from '@onixjs/core';
import {MongoAdapter} from './oidc.adapter';
import * as Provider from 'oidc-provider';
import {UserModel} from '../user.component/user.model';
/**
 * @class OIDCProvider
 * @author Jonathan Casarrubias
 * @license OnixJS
 * @description This class will serve as an OIDC Provider.
 * It internaly implements oidc-provider and connect with
 * the application model and datasource.
 */
@Service()
export class OIDCProvider {
  // Inject User Model
  @Inject.Model(UserModel) user;
  // Create oidc reference and configure
  public oidc: Provider = new Provider(`http://127.0.0.1:8080`, {
    // Add OnixJS Info into the Discovery File
    discovery: {
      sso_info: {
        version: 'OnixJS SSO - Version 1.0.0-alpha.1',
      },
    },
    // FindByID User and Claims
    findById: async (ctx, id, token) => {
      const users = await this.user.find({_id: id});
      const user = users.pop();
      return {
        accountId: user._id,
        claims: () => {
          return {
            sub: user._id,
            email: user.email,
          };
        },
      };
    },
    // Register scopes and claims
    claims: {
      openid: ['sub'],
      email: ['email'],
    },
    // Interactions URL
    interactionUrl: ctx => `/interaction/${ctx.oidc.uuid}`,
    // OIDC Provider Features
    features: {
      // disable the packaged interactions
      devInteractions: false,
      claimsParameter: true,
      clientCredentials: true,
      discovery: true,
      encryption: true,
      introspection: true,
      registration: true,
      request: true,
      requestUri: true,
      revocation: true,
      sessionManagement: true,
    },
  });
  /**
   * @init
   * @description
   * will initialize the OIDC Provider, it will load
   */
  init() {
    // Initialize OIDC
    this.oidc.initialize({
      //keystore,
      clients: [],
      // configure Provider to use the adapter
      adapter: MongoAdapter,
    });
  }
}
```


And The Client Metadata

```json
{
    "_id": "6572ac08-cabe-4d8b-b230-563481336b26",
    "application_type": "web",
    "grant_types": [
        "authorization_code"
    ],
    "id_token_signed_response_alg": "RS256",
    "require_auth_time": false,
    "response_types": [
        "code"
    ],
    "subject_type": "public",
    "token_endpoint_auth_method": "client_secret_post",
    "post_logout_redirect_uris": [],
    "request_uris": [],
    "client_id_issued_at": 1522784156,
    "client_id": "6572ac08-cabe-4d8b-b230-563481336b26",
    "client_name": "OpenID PlayGround",
    "client_secret_expires_at": 0,
    "client_secret": "ADEifvtE/f66U/9f5U5p2tcKLw27Ydcn2jDKxkT7MDL19herN/ZPxaE4XIc1qWzM",
    "contacts": [
        "jcasarrubias@mean.expert"
    ],
    "jwks_uri": "https://my-oidc.com/oauth/token",
    "logo_uri": "https://avatars3.githubusercontent.com/u/36309581?s=400&u=340c71985ff61d762c5f1068153aa8d711b996ee&v=4",
    "redirect_uris": [
        "https://openidconnect.net/callback"
    ],
    "introspection_endpoint_auth_method": "client_secret_post",
    "revocation_endpoint_auth_method": "client_secret_post",
    "userinfo_encrypted_response_alg": "RSA1_5",
    "userinfo_encrypted_response_enc": "A128CBC-HS256",
    "expiresAt": {
        "$date": "2018-04-04T19:35:56.974Z"
    }
}
```


And the logs:
![image](https://user-images.githubusercontent.com/1533239/39088320-2145bb16-4575-11e8-9221-7d7782a98312.png)

**Comment by jonathan-casarrubias** [comment]
Ok that helped me  a little, I see is something related to the "jwks_uri" though I'm not entirely sure what it refers to

**Comment by panva** [comment]
Your client config tells the provider that userinfo must be returned as encrypted jwt with asymmetrical key, that one being fetched from the jwks_uri in your client document. The URL you have in there is not likely a jwks endpoint.

Also [events](https://github.com/panva/node-oidc-provider/blob/master/docs/events.md) provider.on('server_error') for uncaughts / server errors

**Comment by jonathan-casarrubias** [comment]
Awesome I really appreciate you taking the time to answer, I took that metadata example from the specs so I’m not entirely sure about each prop so I’ll definitely research about those.

Cheers
Jon

**Comment by jonathan-casarrubias** [comment]
yup it worked like a charm, thanks a lot @panva

**Comment by panva** [comment]
On that note, when client jwks_uri cannot be refreshed it should probably throw `invalid_client_metadata` rather then `server_error`, i'll fix that.

**Comment by jonathan-casarrubias** [comment]
@panva I think that would be best, but I would also recommend to add a reference to `DEBUG=oidc-provider:*` witin the https://github.com/panva/node-oidc-provider-example/tree/master/03-oidc-views-accounts repo, since it definitely is extra helpful to see those logs.

Cheers
Jon

**Comment by panva** [comment]
It is right in the readme under debugging ;)

**Comment by panva** [comment]
no worries :)

**Comment by jonathan-casarrubias** [comment]
@panva actually my recommendation was to also add that info into the examples repo, I went to verify where it was located and I was unable to find it, so I assumed you were referring to the actual module repo in which that case you are right.

So I'll still recommend to also add it to the examples repo, I believe I spent most of my time implementing this module reading the examples repo than the actual module repo.

Cheers!
Jon

**Comment by panva** [comment]
> So I'll still recommend to also add it to the examples repo, I believe I spent most of my time implementing this module reading the examples repo than the actual module repo.

How could I actually fix that? :) The example repo will never contain all the configuration options or documentation.

**Comment by jonathan-casarrubias** [comment]
Great question indeed, the problem is that even though the main repo provides all the configurations, there are some folks like me that usually understand technology by reverse-engineering, therefore the example repo is the one providing me that possibility.


Then my following recommendation would be adding some note like in the following form:

> HINT: For more details consider [Specs](https://github.com/panva/node-oidc-provider#implemented-specs--features), [Configurations](https://github.com/panva/node-oidc-provider#configuration-and-initialization) and [Debugging](https://github.com/panva/node-oidc-provider#debugging).

You might want to add something like that at the top or bottom of each step within the examples.

Since I totally agree adding the entire documentation in here is not viable.

I hope this makes sense to you and provide value.

Hints definitely help developers to be guided through the proccess, keep in mind that it is an incredible amount of information when implementing something like this... So a HINT might be the solution.

Thoughts?

**Comment by panva** [comment]
> HINT: For more details consider documentation, configuration and details found in the [oidc-provider documentation](https://github.com/panva/node-oidc-provider#oidc-provider)

How about this, can you open a PR?
