### ISSUE TITLE
client_secret_post not allowing client_id and secret to be included in Authorization headers

### ISSUE THREAD

**Issue by flyweight** [panva/node-oidc-provider#26]
Our consumer is sending the username, password, grant_type, and scope in the body, but the client_id and secret are in the Authorization request header.

     header: 
      { authorization: 'Basic 

OAuth Spec:
For a grant_type of password, https://tools.ietf.org/html/rfc6749
Section 4.3.2 Access Token Request

Configuration setting for client:

token_endpoint_auth_method: 'client_secret_post',

The error being returned is "client_id must be provided in the body"
 
oidc-provider/lib/shared/token_auth.js

19       case 'client_secret_post': {
 20         const params = this.oidc.params;
 21 
 22         this.assert(params.client_id, new errors.InvalidRequestError(
 23           'client_id must be provided in the body'));
 24 
 25         this.assert(params.client_secret, new errors.InvalidRequestError(
 26           'client_secret must be provided in the body'));
 27 
 28         tokenCredentialAuth.call(this, this.oidc.client.clientSecret, params.client_secret);
 29 
 30         break;
 31       }

Would it be possible to support the client id/secret to be included in the auth header in this use case or is that illegal?

Thanks

**Comment by flyweight** [comment]
I could have misspoke.  It seems if I use `client_secret_basic`, my use case works.

**Comment by panva** [comment]
You got it right, oidc defines four client auth methods. All of them supported by this library. Once a client is configured with a method this method must however be used. The default when not specified is actually client_secret_basic

Client Authentication
- client_secret_basic
- client_secret_post
- client_secret_jwt
- private_key_jwt
