### ISSUE TITLE
Recommendations for adding properties to introspection response

### ISSUE THREAD

**Issue by just-tomht** [panva/node-oidc-provider#261]
Hello

My API would like an additional identifier associated with access_tokens. We are not willing to pass the id_token to them however. So we're using /introspection to get the contents of an access token. As I understand it, you support userinfo to get additional claims from the id_tokens but, this would add an additional call of overhead for us. Also the introspection spec supports this:

> https://tools.ietf.org/html/rfc7662#section-2.2
> Specific implementations MAY extend this structure with their own
> service-specific response names as top-level members of this JSON
> object.

So far the only way I can find to achieve this is to register an additional middleware that is listening to the response of `ctx.method !== 'OPTIONS' && ctx._matchedRouteName === 'introspection'`. Then adding any non-standard access_token claims to the body. This feels a bit like a dirty hack. Also, another hack, to associate these claims with the access_token, I'm doing something like this too:

```js
    async findById(ctx, id, token) {
      const user = gerUserAccount()
// Hacky: add claims to the ctx here, when access_token is created after this method is called, 
// it will populate it's claims in the AccessToken.
      ctx.oidc.claims = user.someAccessTokenClaims
      return { accountId: id, ...
```

Both of these steps feel kind of wrong... but I can't find another solution. I'm also aware of other considerations like:

- I shouldn't add claims to the introspection response if `active !== true`
- easy way to filter the claims for a scope according to config using this libraries helpers?

Do you have any guidance in this matter or know any other considerations I should be checking in this hack.

```js
  const oidc = new OidcProvider(...)

  oidc.use(async (ctx, next) => {
    await next()
    const { params } = ctx.oidc
    if (ctx.method !== 'OPTIONS' && ctx._matchedRouteName === 'introspection') {
      const token = await oidc.AccessToken.find(params.token)
      if (ctx.body.active === true) {
        ctx.body.claims = token.claims
      }
    }
  })

  await oidc.initialize({
    keystore,
    clients: ConfigService.getConfigVar('CLIENTS'),
    adapter: OidcMongoDbAdapter(db),
  })
```

**Comment by just-tomht** [comment]
Thanks for the prompt reply!

> And don't worry it'll all feel like a hack at first but most of it is stable api.

Good to know :)

>Eh? No, using the claims parameter you can fine-tune what gets returned in an id token and which claims are available in userinfo.

I think I'm potentially just using slightly off terminology as I'm new to OIDC but what you said is what I'm doing already. I just meant extra call from the API to get those claims from userinfo, right now the APIs only need to call introspection.

> it's already loaded and assigned to the context (since v2.18.0).

Sweet! Thanks that helps a bunch yeah.

> I'm not sure I follow this one, introspection does not use findById at all so it doesn't run.

So the findById call is being invoked when a user authenticates for example, this seems to be when their AccessToken is created and stored through the Adapter. With some debugging I found that the AccessToken had `claims: {}` as a property and so I could mutate the `ctx.oidc.claims` to inject some custom claims into that AccessToken which are also being returned from userinfo anyway.. It helped me manage it in one place.

> Adding properties to tokens and having them stored is supported already through several means, 

So I've seen that I can override some of the AccessToken prototype but I'd rather not go down that route. Also, claimsParameters didn't seem to work as it wasn't giving me the facility to fetch the claims out of the db when the AccessToken is initially created.

> can you explain in detail what you need (with prop names and reasons) so that i can better assist?

So we have several identifiers for a customer, the sub is a fixed identifier in our store. We also use a userName and other credentials and profile for login and our SPA clients. The additional identifier I'm adding here, I'll call it `third_party_id` is an identifier to a third party where our APIs will query to get customer data.

**Comment by panva** [comment]
- Why don't you add the claim to the id token or userinfo?
- Why don't you actually call userinfo? Considering you're running an SPA you are likely using `id_token token` implicit flow. If your client is certified it is able to validate an access and id_token belong together (at_hash) and so in the end you have claims such as exp, iat, iss, aud, azp already at hand, plus whatever is in userinfo.

**Comment by just-tomht** [comment]
> Why don't you add the claim to the id token or userinfo?

We aren't passing the id_token from the SPA to the API for security reasons, the same with the third_party_id.

The API will only have the access_token from a Bearer header, nothing else.

> Why don't you actually call userinfo? 

The SPA can call userinfo and might, although we're putting claims into the id_token anyway. But, we'd prefer that the API only needs to call introspection, not both introspection and userinfo. We'll probably go with this solution initially though and cache userinfo response in the API. But it's good to know the options for a performance improvement.

Thanks
