### ISSUE TITLE
Adding a model expiration test in the adapter conformance test? 

### ISSUE THREAD

**Issue by madarche** [panva/node-oidc-provider#263]
@panva do you think it would be appropriate to add *a model expiration test* in [the adapter conformance test](https://github.com/panva/node-oidc-provider/blob/master/lib/adapter_test.js)?

I have a test that checks that point on my custom implementation and I can try to put it upstream in  the adapter conformance test if you think this is a good idea.

Thanks

**Comment by panva** [comment]
For tokens the provider does not care, since it has all the checks necessary to handle returned but expired tokens. From my perspective it's not required for tokens. For sessions it currently is but that's something i'll tackle in 3.x.

**Comment by madarche** [comment]
I agree that **the expiration is well taken care of in the provider and that the provider has no problem regarding token expiration**.

The point here is to help developers to create clean custom adapters that don't leave expired models in the persistence layer. And that's why I propose to put this new test in [`/lib/adapter_test.js`](/lib/adapter_test.js), which is about *adapters* and nowhere related to the provider!

By contributing this test I would be sure that expiration *in the persistence layer* is always well behaving for everyone, including me (the first version of my custom adapter was faulty on this point), building their own custom adapter.

So @panva, could you reconsider your decision please and consider a PR for a test on the persistence layer?

**Comment by panva** [comment]
I’ve had cases where expired tokens are still very much useful for BI.
