### ISSUE TITLE
Shouldn't the grant object be destroyed when its grant related models are destroyed?

### ISSUE THREAD

**Issue by madarche** [panva/node-oidc-provider#264]
If I'm not mistaken, currently in the proposed [in-memory adapter](/lib/adapters/memory_adapter.js),  [redis adapter](/example/adapters/redis.js) and [mongodb adapter](/example/adapters/mongodb.js) the grant object (holding the references to the grant related models) is not destroyed when a model is destroyed.

Shouldn't this grant object be destroyed as well?

This is not a bug in the oidc-provider lib, but since developers are expected to use those proposed adapters as reference this can be misleading.

**Comment by panva** [comment]
> Shouldn't this grant object be destroyed as well?

What grant object?

**Comment by panva** [comment]
Ah I see, if you can open a PR for the memory and redis one i'm happy to accept it. Mongo does not have that issue.
