### ISSUE TITLE
Custom Claims?

### ISSUE THREAD

**Issue by jpreese** [panva/node-oidc-provider#27]
Looking at the UserInfo action endpoint specifically, all of the claims are set through account.claims().  Is there a way to set additional claims outside of account.claims() or am I overlooking something?

**Comment by panva** [comment]
Account.claims() should return all your op has available about the account. But there's a mechanism on top that cherry-picks which claims the endpoint or idtoken should return.

This is the 'claims' configuration option, it is binding claim names to scopes and in general allows them claim names to be used. 

Have you checked the example where the claims configuration is used to set all oidc suggested claim names? If a claim name is to be available to all requests, add it under the openid scope, else if you wish to specifically request via the claims parameter you can add it as a top level member of the claims config

**Comment by jpreese** [comment]
Thanks for the quick response, Panva!

Yes, I was mostly curious if the claims can only come from Account.claims().  Put another way, it sounds like if you want a claim to come through in one of your endpoints, it must be in Account.claims(), there just is not a way around that, and then allow it as a valid claim in the configuration.

I'm mostly asking because how we have our Account model set up, it might not make a lot of sense to have Account know about how to retrieve some claims, so we wanted that elsewhere. Silly example, but maybe you wanted the name of the website to come through as a claim. The name of the website doesn't really have anything to do with an Account. 

So I was hoping to be able to set that information in our own login/auth process and pass it down to oidc.session, within the login.result in the resume middleware, etc.

**Comment by panva** [comment]
The way i use i account i expose to oidc-provider is more like an aggregation layer, i don't even use my real account model with attached odm, i just proxy to it. At this point it's not even supporting async claims(), but it should at some point. To keep the already pretty confusing to configure library simple i wouldn't add more ways to fetch claims. Especially when they only appear in userinfo and idtoken, which by definition always belong to an account.

**Comment by jpreese** [comment]
Thanks again for the responses, panva. Just wanted to make sure that our thoughts lined up with the implementation. The proxy idea is a good one. Since we're using Sequelize as our ORM, and thus our Account model is currently essentially a row in a table, it'd probably make more sense to have some sort of oidc specific Account model, rather than use our generic account model.

Should be OK to close at your convenience.
