### ISSUE TITLE
Configuration of the user session ttl on the OP

### ISSUE THREAD

**Issue by madarche** [panva/node-oidc-provider#270]
Hello,

This is not a bug report. This is a question (or an evolution request).

For a usecase, I need user sessions on the OP to be rather short, 1/2 a day, compared to the 1 year default. I do it by the following configuration option: 
```javascript
cookies: {
    long: {maxAge: 6 * 60 * 60 * 1000},
}
```

Is this really the right way to configure the user session ttl on the OP?

I would rather expect the user session ttl to be in the [`ttl` configuration option](https://github.com/panva/node-oidc-provider/blob/master/docs/configuration.md#ttl), shouldn't it? Doesn't the user session ttl pertain more to the server configuration than to cookies which are just a mean to give this information to the user?

I would prefer to have a new option `ttl.UserSession` (or another name along this line) and have the cookie `maxAge` be set from this value rather than the opposite.

Is this reasoning logical? If so, could this change be set for the 4 release?

Thanks

**Comment by panva** [comment]
> Is this really the right way to configure the user session ttl on the OP?

Yes. It is used for setting the expiration on a cookie as well as ttl on the backend stored data.

> I would rather expect the user session ttl to be in the ttl configuration option, shouldn't it?

As documented ttl is for configuring token expirations.

I'll think this over for v4.x as i'm also planning some changes to session expiration but wouldn't expect a change. 

It is so that when the cookie gets dropped due to it's maxAge so should the stored session. That's why the adapter#upsert expiresIn values get taken from the cookie maxAge now. I wouldn't want to introduce a scenario where cookies are still present but the document is not or vice-versa - PITA to troubleshoot.

**Comment by madarche** [comment]
> Yes. It is used for setting the expiration on a cookie as well as ttl on the backend stored data.

Thanks for this confirmation!

> As documented ttl is for configuring token expirations.

Yes. So that's not the right place for what I'm talking about. Agreed.

> I'll think this over for v4.x as i'm also planning some changes to session expiration but wouldn't expect a change.

Maybe I was not clear enough: I was proposing this change to go *into* the 4 release.

> That's why the adapter#upsert expiresIn values get taken from the cookie maxAge now.

I have read this recent commit, and yes this is a good thing to do.

So after having read your answer I'm changing my proposition 🙂 : what about a new configuration option called `userSessionTtl`(or any new name along this line) ? This option would be used to initialize both the backend stored data expiration and the cookie maxAge. This would make the intent and the doc clearer. And this is really easy to put into the 4.x in time I believe. What do you think?

Thanks

**Comment by panva** [comment]
So cookie maxage would be in two places instead of one (long in userSessionTtl and short in cookies.short)?

Session expiration is bound to how long a cookie is kept in a browser. 
If this is just about making it clear please propose a change to the `affects` section of cookies.long documentation.

Plus the long cookie values aren't ONLY used for sessions but also the session management cookies.

**Comment by madarche** [comment]
OK, you're right @panva. This is clearly more of a documentation need. I'll propose a PR on the matter in a few days. Thanks!

**Comment by panva** [comment]
Thank you @madarche

**Comment by madarche** [comment]
But still a feeling: such an important thing as the user session ttl on the OP seems to require an option by itself rather than being a consequence of another option. That what caused me to ask the question in the first place.

**Comment by madarche** [comment]
I know this issue is closed, but one can still think on the subject. @panva what do you think about this following new proposal?

* remove previous property `cookies.long`
* remove previous property `cookies.short`
* add property `cookies.options` (definining secure, signed, httpOnly for all cookies) to be used for all cookies, long and short ones
* change option `ttl` to
  - `ttl.tokens` - expirations (in seconds) for all token types
  - `ttl.userSession`
  - `ttl.sessionManagement`
  - `ttl.interaction`

Rationale: there's no usecase, I believe, for having long cookies signed/etc. and not short cookies. the new `ttl.tokens` property is rightly containing only tokens, so it can be used by the code exactly as it does now.

This is just a proposal, all proposed names can be changed/improved, etc. as I have not an intimate knowledge of the underlying code.

**Comment by panva** [comment]
> there's no usecase, I believe, for having long cookies signed/etc. and not short cookies

signed, not signed I fully agree. But,

one can be setting short cookies for a subdomain where his other app (hosting separate user interactions) is hosted, using the `domain` option.

one can also have user interactions requiring the cookie to be readable by javascript, hence dropping httpOnly for these only.

I've witnessed and wish to support both cases above.

**Comment by madarche** [comment]
Understood. Thanks. I'm letting the subject rest a bit before trying to come up with a possible clean proposal compatible with those constraints. Thanks again for your time @panva 🙂

**Comment by panva** [comment]
> I'm letting the subject rest a bit before trying to come up with a possible clean proposal compatible with those constraints.

This is a big thorn for you, isn't it :)

**Comment by madarche** [comment]
Yes the subject bothers me :-) But it's not actually a problem because the software works as expected (thanks to you). I'm a bit of a perfectionist.

Often, good solutions arose almost by themselves when one thinks to something else.

**Comment by madarche** [comment]
@panva (no hurry, when you have time) what about this other proposal?

* remove previous property `cookies.long`
* remove previous property `cookies.short`
* remove previous property `cookies.keys`
* add property `cookies.security` (defining `httpOnly`, `secure`, `domain`, `signingKeys`), for all cookies. If `signingKeys` is present then the cookies will be signed
* add property `cookies.interaction` if present can override `cookies.security` params for interaction cookies, given for fine-grained control
* add property `cookies.session` if present can override `cookies.security` params for session (user session, session management) cookies, given for fine-grained control
* change option `ttl` to
  - `ttl.tokens` for all token types
  - `ttl.interaction` for interaction cookies
  - `ttl.session` for user sessions and session management cookies

**Comment by panva** [comment]
Hello @madarche i'll be sticking to the current configuration scheme for 4.x. I've dropped some of my goals for 4.x regarding configuration and this one is one of them. If and when I finally get around to reimplement the whole configuration scheme to allow for on-the-fly configuration i'll work this in.

**Comment by madarche** [comment]
Perfectly understood! Thanks.

PS: I've seen you have stopped trying to use `superstruct`. I've no strong opinion about this, it's just to let you know that I'm reading the commits with interest.

**Comment by panva** [comment]
`superstruct` is going to come back eventually for the new configuration scheme, I really like it. I just don't have the bandwidth to go through with it at the moment.
