### ISSUE TITLE
Enabling BackChannel Logout

### ISSUE THREAD

**Issue by robtweed** [panva/node-oidc-provider#275]
I've been digging into the available information on and code related to enabling and  implementing Back Channel Logout, but haven't managed to figure it out.

I've turned on the feature:

         features: {
             backchannelLogout: true,
              ...etc
         }

and can see that it is enabled when I look at the response from the /.well-known/openid-configuration URI

        {
            "backchannel_logout_supported": true,
             "backchannel_logout_session_supported": true,
              etc
         }

However, I'd have expected to see the backchannel_logout_uri included in this response. and assumed I'd have received the logout_token in the Token Set returned after authentication.  Unfortunately I don't see that information, and looking at the code makes me suspect that it's a case of using the available hooks to implement the backchannel logout logic myself.

Before I do so, can I just check that I'm correct, or maybe I'm missing something?
Some pointers on how to move forward would be welcomed.
For example it looks like I need to define the backchannelLogoutUri as a client property, and I assume I then need to handle requests sent to that endpoint / route?

**Comment by panva** [comment]
> However, I'd have expected to see the backchannel_logout_uri included in this response.

Why? That's a client property.

> and assumed I'd have received the logout_token in the Token Set returned after authentication

I'm guessing you assume backchannel logout is something the client triggers on the OP. That's not the case. No such back-channel mechanism exists.

> Before I do so, can I just check that I'm correct, or maybe I'm missing something?

First I'd recommend to understand the [spec](https://openid.net/specs/openid-connect-backchannel-1_0-04.html).

In brief:  
After enabling the feature (which you've done), your clients can be configured with `backchannel_logout_uri` metadata property to which requests will be sent by the OP after the user has logged out (using RP-Initiated Logout) in a session where that client has been active, that request will contain the `logout_token`.

**Comment by panva** [comment]
You might also want to go through the [tests](https://github.com/panva/node-oidc-provider/blob/v3.0.1/test/backchannel_logout/backchannel_logout.test.js) for this feature to understand it.
