### ISSUE TITLE
Notify an RP about changed user information

### ISSUE THREAD

**Issue by marcortw** [panva/node-oidc-provider#276]
Is it somehow possible to instruct an RP from the OP to ensure that new userinfo is fetched as soon as possible? For example, a user might have changed some of his attributes (e.g. the e-mail address) on the OP and I want to ensure that the RP gets that information as quickly as possible. This seems to be in a way similar to backchannel logout, where something happens on the OP and the RP should be notified about it.

I currently think of implementing something like a 'stale userinfo notificaton URI' on the RP to which an OP would send a JWT containing the stale sub id. But maybe there's something slightly more elegant and out-of-the-box way to do this.

**Comment by panva** [comment]
out-of-the-box, no
profiled specifications, no

this is all out of scope. but you might want to look into [secevents](https://datatracker.ietf.org/wg/secevent/documents/) and their use in some of the OpenID WG streams.
