### ISSUE TITLE
Uninitialised Buffer Vulnerability - base64url

### ISSUE THREAD

**Issue by MeirionHughes** [panva/node-oidc-provider#277]
> base64url allocates uninitialized Buffers

https://hackerone.com/reports/321687

**Comment by panva** [comment]
Hi, I’m aware. Working on a replacement. Unfortunately it’ll take some more time for node-jose to update.

Just to clarify, after my updates neither of the libraries is actually affected anymore since we’re always working with string inputs (headers, query strings) and so we’re never allocating a buffer with a number. 

I’ll post an update here in a few with the new releases.

**Comment by MeirionHughes** [comment]
No worries, I just stumbled upon it when looking this up. apparently `b64u` is a drop in replacement. I [PR'ed a quick fix](https://github.com/brianloveswords/base64url/pull/25) but it doesn't look like its being maintained.

**Comment by panva** [comment]
Yeah, the hackerone report history shows attempts have been made to contact @brianloveswords on multiple channels with no success. I thought about using base64-url, the API i'm using is identical, could you run a few encode/decode benchmarks to choose between the two? (b64u and base64-url)

**Comment by panva** [comment]
provider - https://github.com/panva/node-oidc-provider/tree/v3.0.2 released
client - https://github.com/panva/node-openid-client/tree/v2.0.3 released
token-hash - https://github.com/panva/oidc-token-hash/tree/v3.0.0 released
jose - https://github.com/cisco/node-jose/pull/179 PR pending

**Comment by MeirionHughes** [comment]
Looks like its specific to node 4; >= 6 will complain about `new Buffer(1000, encoding)`. 
base64-url has an engine requirement of >=6. 
b64u is 4+ without input check so its still vulnerable. 

Looks like base64-url is the way to go. 

given node-oidc-provider has an engine requirement of 8 presumably it was never an issue anyway.

**Comment by panva** [comment]
update & close

provider - https://github.com/panva/node-oidc-provider/tree/v3.0.2 released
client - https://github.com/panva/node-openid-client/tree/v2.0.3 released
token-hash - https://github.com/panva/oidc-token-hash/tree/v3.0.0 released
jose - https://github.com/cisco/node-jose/tree/0.11.1 released
