### ISSUE TITLE
Adapter for clients

### ISSUE THREAD

**Issue by janhartmann** [panva/node-oidc-provider#278]
Thanks for this amazing library! 

I am currently experimenting with creating a production ready oidc provider and wanted to move my clients to a storage.

I could not find any examples on how the adapter works for clients? Where is this adapter defined? 

Jan

**Comment by panva** [comment]
It's the [same](https://github.com/panva/node-oidc-provider/blob/v3.0.1/example/my_adapter.js) adapter. The constructor will get a name param which you can use to determine which model this instance is for.

**Comment by janhartmann** [comment]
Ah pefect, thanks!
