### ISSUE TITLE
working stateless (no session)

### ISSUE THREAD

**Issue by adrai** [panva/node-oidc-provider#280]
Would it be possible to have the whole user authentication part completely separated, and as a result verify a token then in the oidc server?
And after the token validation continue with the oauth workflow code=>accessToken, idToken ?

**Comment by panva** [comment]
Hi @adrai, could you elaborate on the flow you're thinking of?

**Comment by adrai** [comment]
I don't have a persistent session.
The only missing piece I have now is: How can I proceed with the openidconnect flow, trigger to generate an authorization code, etc... ?

**Comment by panva** [comment]
Hi @adrai, I really don't follow what you're asking.

**Comment by adrai** [comment]
sorry :-(
I try with a concrete question:
Seems like `interactionFinished` needs to access the cookies => https://github.com/panva/node-oidc-provider-example/blob/master/03-oidc-views-accounts/index.js#L122
Is there a proper workflow which will not need to access the cookies?

**Comment by panva** [comment]
> Is there a ~proper~ workflow which will not need to access the cookies?

There is not. oidc-provider does not have a support for this.

**Comment by adrai** [comment]
Is there a way I can workaround?
i.e. by generating the accesscode on my own? is there a function of you code I could use?

**Comment by panva** [comment]
Sorry, I don't have the bandwidth to entertain such use cases.
