### ISSUE TITLE
HTTP Request behaving different as expected

### ISSUE THREAD

**Issue by marcortw** [panva/node-oidc-provider#282]
I wanted, for demonstration purposes, use a proxy with TLS interception and configured some http options as mentioned in the docs:

```
Provider.useRequest();
const provider = new Provider(...)
provider.defaultHttpOptions = {
    rejectUnauthorized: false,
    strictSSL: false,
    ...config.app.outbound.proxy && {proxy: config.app.outbound.proxy_uri},
};
```
This eventually calls the 'requestWrap' method, where my options are still around in the function call. However, when you return the Promise on https://github.com/panva/node-oidc-provider/blob/master/lib/helpers/http/request.js#L38 you only copy the values from the keys you expect.

The docs say '... instance merges your passed options with these defaults' - which I interpreted that in case if you're using request, you can pass in a request options object which will then be merged with the defaults.

It would be nice if this would be possible and/or if you'd export a httpClient() wrapper like in the oidc client (as discussed in https://github.com/panva/node-openid-client/issues/35)

**Comment by panva** [comment]
I agree, would you open a PR for handling these extra options in the useRequest wrapper?

httpClient i’m not going to do

**Comment by panva** [comment]
You’re right. Lemme fix that for the useRequest option.

**Comment by panva** [comment]
can you try with the pass-all-to-request branch?
