### ISSUE TITLE
Adding extra properties to access_token

### ISSUE THREAD

**Issue by codestorycooked** [panva/node-oidc-provider#283]
I want to add extra parameters to `access_token` so when I introspect I get those values: 

```
{"active":true,"token_type":"access_token","sub":"kunal.deshmukh@siemens.com|472a31d955984bcd97fa27cd7788d18f","client_id":"43bbde3c-0c7d-4311-b313-3ebb17663f42","exp":1526985885,"iat":1526899485,"iss":"http://localhost:4010/","jti":"ZmQ4YTliMmMtNDI5NS00YjMxLWI5MGEtZDM4YzI3MjQ1OGI3", "account":"sampleAccount", "tenantInfo":"tenantInfo"}
```
I want to add "account" and "tenantInfo" to `access_token`

Thanks for your help.

**Comment by panva** [comment]
Hello @codestorycooked,

This isn’t supported, the introspection endpoint only works with claims stored directly on the token to avoid additional lookups. 

That being said you’re free to extend the introspection response with [custom registered middleware](https://github.com/panva/node-oidc-provider/blob/master/docs/configuration.md#pre--and-post-middlewares). The token you’ll find in ctx.oidc.entities
