### ISSUE TITLE
URL namespaced claims

### ISSUE THREAD

**Issue by codestorycooked** [panva/node-oidc-provider#285]
Do we support claims as url formats as below for OIDC configuration ? If yes how do I populate values for same.

```js
 this.claims = {
            'auth_time': null,
            'https://sws.siemens.com/claims/tenantId': null,
            'https://sws.siemens.com/claims/tenantName': null
        };
```
Thank you for helping us constantly.

**Comment by panva** [comment]
Hi @codestorycooked 

I don't mind the occasional question, this however is pretty self explanatory and could be tried first before asking.

Regardless,

```
this.claims = {
...
```

I'm going to ignore this as this looks like a piece of your config that has nothing to do with the configuration or any helper syntax.


As with any custom claims (as documented) you need to declare support for them, bind them to a scope (optional, see below) and return them from the claims method on your account.
```js
new Provider('http://localhost:3000', {
  claims: {
    'https://op.example.com/claims/foo': null,
    'profile': [
      'https://op.example.com/claims/bar',
    ]
  },
  async findById() {
    return {
      accountId: '...',
      async claims() {
        return {
          sub: '...',
          'https://op.example.com/claims/foo': 'foo',
          'https://op.example.com/claims/bar': 'bar',
        },
      },
    },
  },
});
```

**Comment by codestorycooked** [comment]
Thank you so much @panva
