### ISSUE TITLE
Redirect to custom URL after interactionFinished is executed

### ISSUE THREAD

**Issue by nataliahering** [panva/node-oidc-provider#287]
Hi,

In my scenario I would like to execute the following flow
- call and execute `provider.interactionFinished` method (which is setting the header based on the interaction.returnTo)
and then
- redirect to a custom `url` (which will render a custom page).
The `response.headers` object cannot be overwritten and therefore I cannot change in my custom code the header calculated in the `interactionFinished` method.
Any recommendations?

**Comment by panva** [comment]
Do it vice versa. Hold on to the results until you want to call interactionFinished. 

Else just do a custom function emulating the same behavior.
