### ISSUE TITLE
set session cookie expired at end of session

### ISSUE THREAD

**Issue by mogeda** [panva/node-oidc-provider#289]
I used to set cookies.long.maxAge to 0 to let the session cookie expired at the end of session. Since exp was introduced in session model in v4.0, it looks it's even failing to set session cookie itself with cookies.long.maxAge=0. Is there any way to set the session cookie expired when the browsing session ends? Thanks.

**Comment by panva** [comment]
This is likely a bug/overlooked setup/not tested for, I'll look into it. In your setup, how did you expire/delete the backend session objects, based on what?

**Comment by mogeda** [comment]
By default, I set cookies.long.maxAge=0 while defined extra ttl for session record with the default as 14 days. I read cookies.long.maxAge from env, so if it's available in env then used it for expiresAt too.

**Comment by panva** [comment]
> Is there any way to set the session cookie expired when the browsing session ends? Thanks.

This is the way to do it as documented. When calling interactionFinished you can set `login.remember` to false which will make it so that the cookies are transient.

```
provider.interactionFinished(req, res, {
   // ...
   login: {
	// ...
    remember: false,
   }
});
```

**Comment by panva** [comment]
That being said i can see a few issues with this approach and will look into a solution that restores the previous `0` value behaviour.

**Comment by panva** [comment]
@mogeda please try with master.

**Comment by mogeda** [comment]
The fix works, I can see the session cookie set as expected with cookies.long.maxAge=0 now. Thanks a lot as always.
