### ISSUE TITLE
Additional claims in access token introspection

### ISSUE THREAD

**Issue by jajadinimueter** [panva/node-oidc-provider#29]
Hi

Is there a reason you only support certain claims in https://github.com/panva/node-oidc-provider/blob/master/lib/actions/introspection.js? In https://tools.ietf.org/search/rfc7662#section-2.2 additional ones like "aud" are listed. The protocol even allows claims not described in the RFC. Is there a way for the user (us) to extend that response without changing the core code?

I have to add I am very new to openid connect and oauth2 and there's a good chance I confuse things here.

Thanks for an advance for your answer!

**Comment by panva** [comment]
All claims that are available to the library get returned, even some extras got added recently (like sid). aud is not listed because it is nothing more then the client_id in this library.

What kind of additional response would you like to add? Currently the endpoint is self-sustained with details it finds on the token and it's context, it does not load the account in question, which quite frankly it shouldn't it's token introspection, not userinfo ;)

**Comment by jajadinimueter** [comment]
Thanks for the quick answer! 

What you say makes sense and I guess we just don't get the concept of open id connect. What we are trying to do is this:

We have a Client "C" and an two APIs "A1" and "A2".

The Client "C" is a resource owner. The end user tries to connect to C and has to authenticate. C receives the id_token and an access token. C then wants to call A1 and A1 wants to call A2.

C calls A1 using the access token. A1 has to check whether this access token can be used to call A1, so has A2 when it is called with the same access token. We thought this would be done with the "aud" claim where the client IDs of A1 and A2 would be listed. But I guess that's not the way you do it. Do you know how to do something like this?

I know this is a more general question but maybe you have an answer never the less?

**Comment by panva** [comment]
At the moment there's no way to pass additional audiences to id or access tokens, i welcome any suggestions for how the API would look and where would this information be coming from.

**Comment by panva** [comment]
See #261 and #399
