### ISSUE TITLE
Question: How to bypass login check?

### ISSUE THREAD

**Issue by jsmylnycky** [panva/node-oidc-provider#290]
Hey there,

I've been diving into an implementation of the library here, and so far it's pretty great.  I have run into a problem I'm having a difficult time getting past, however.

Background:

I have a reverse proxy in front of the OIDC Provider, which manages its own session and uses a different service for actually handling the logins.  My proxy sends along an `x-guid` header to the OIDC provider, and by having that header, I can trust that I am logged in as that identifying user.

My goal here is to say "If I have that header, create an Account in OIDC and refer to that guid as an appResourceOwner."

The problem I'm having is I can't figure out how to bypass the login checks, so even trying to customize `interactionCheck` fails since `login_required` seems to get ran and returned first.

Any hints on how to proceed with this implementation would be greatly appreciated.

**Comment by panva** [comment]
You can trust your header in the interactions and immediately redirect back with the results instead of rendering any views, this will then "seamlessly" establish the session for the provider based on whatever you trust.

But you can't run `oidc-provider` solely based on this header. The library has it's own session management for the various features it needs.

**Comment by jsmylnycky** [comment]
Hm that seems pretty reasonable, I'll give it a whirl.  Thank you :)

**Comment by jsmylnycky** [comment]
Just to follow up with how I ended up getting this working:

```
this.app.get('/interaction/:grant', async (req, res, next) => {
  const account = await Account.findByAppResourceOwner(req.header('x-guid'))
  const details = await provider.interactionDetails(req)
  const client = await provider.Client.find(details.params.client_id)

  res.render('authorize', {
    details,
    client,
    title: 'Authorize',
  })
})

this.app.post('/interaction/:grant/confirm', parse, async (req, res, next) => {
  const account = await Account.findByAppResourceOwner(req.header('x-guid'))

  const result = {
    login: {
      account: account.accountId,
      acr: '1',
      remember: true,
      ts: Math.floor(Date.now() / 1000),
    },
    consent: {
      // TODO: remove offline_access from scopes if remember is not checked
    }
  }

  await provider.interactionFinished(req, res, result)
  await next()
})
```

I had some different issues going on regarding account creation that was hanging me up, and less so on this portion.


Thanks a bunch for your speedy replies and help with this :)

**Comment by panva** [comment]
now you have a consent page, 👍
