### ISSUE TITLE
OIDC-View-Accounts example missing redis adapter

### ISSUE THREAD

**Issue by mithun-daa** [panva/node-oidc-provider#292]
I am not sure if I am missing something but
https://github.com/panva/node-oidc-provider-example/blob/master/03-oidc-views-accounts/index.js#L23

calls for the redis adapter
```
const RedisAdapter = require('./redis_adapter');
```

but that file is missing from the repo. I am guessing it uses a version or an instance of https://github.com/panva/node-oidc-provider/blob/master/example/adapters/redis.js. Am I right? Is there anything different?

**Comment by panva** [comment]
did you follow *every* step? downloading the adapter is part of step 2

**Comment by mithun-daa** [comment]
Sorry, I missed the `wget`. Thank you so much!
