### ISSUE TITLE
All Claims are not returned

### ISSUE THREAD

**Issue by jainmanoj** [panva/node-oidc-provider#293]
I am using noid-oidc-provider
and  configure a client
```js
  {
    client_id: 'clientlogin-oidc',
    client_secret: 'clientlogin-oidc',
    grant_types: ['refresh_token', 'authorization_code'],
    redirect_uris: ['http://localhost:3030/auth/openid/callback'],
    post_logout_redirect_uri: 'http://localhost:3030/',
    response_type:[ 'token','id_token', 'code'],
    // scope:"openid profile api1",
    filterProtocolClaims: true,
    loadUserInfo: true,
    token_endpoint_auth_method: "client_secret_post"
  }
```

From  node-oidc-client - scope is set to retrive following claims
```js
    "authorization_params": {
        "scope": "openid profile phone email name"
}
```

I have setup Account of users with all the above claims. But it is just returning userID as sub in userinfo

But it is not returning all the claims.
userinfo response
```js
{
    "sub": "23121d3c-84df-44ac-b458-3d63a9a05497"
}
```

**Comment by panva** [comment]
Please provide your oidc-provider configuration (including findById). It is likely you didn't configure your provider to return the claims for these scopes. see [docs](https://github.com/panva/node-oidc-provider/blob/master/docs/configuration.md#configuring-available-claims)

NB: the first code block definitely does not come from the client definition in oidc-provider (grant types would fail validation, response token is not supported, filterProtocolClaims and loadUserInfo is nonsense),

**Comment by jainmanoj** [comment]
module.exports.config = {
acrValues: ['session', 'urn:mace:incommon:iap:bronze'],
cookies: {
long: { signed: true, maxAge: (1 * 24 * 60 * 60) * 1000 }, // 1 day in ms
short: { signed: true },
keys: ['some secret key', 'and also the old rotated away some time ago', 'and
one more'],
},
discovery: {
service_documentation: pkg.homepage,
version: [
pkg.version,
process.env.HEROKU_SLUG_COMMIT ? process.env.HEROKU_SLUG_COMMIT.slice(0, 7)
: undefined,
].filter(Boolean).join('-'),
},
claims: {
amr: null,
address: ['address'],
email: ['email', 'email_verified'],
phone: ['phone_number', 'phone_number_verified'],
profile: ['birthdate', 'family_name', 'gender', 'given_name', 'locale',
'middle_name', 'name',
'nickname', 'picture', 'preferred_username', 'profile', 'updated_at',
'website', 'zoneinfo'],
},
features: {
devInteractions: false, // defaults to true
// discovery: true, // defaults to true
// requestUri: true, // defaults to true
// oauthNativeApps: true, // defaults to true
// pkce: true, // defaults to true

backchannelLogout: true, // defaults to false
claimsParameter: true, // defaults to false
encryption: true, // defaults to false
frontchannelLogout: true, // defaults to false
introspection: true, // defaults to false
registration: true, // defaults to false
request: true, // defaults to false
revocation: true, // defaults to false
sessionManagement: true, // defaults to false
},
subjectTypes: ['public', 'pairwise'],
pairwiseSalt: 'da1c442b365b563dfc121f285a11eedee5bbff7110d55c88',
interactionUrl: function interactionUrl(ctx, interaction) { //
eslint-disable-line no-unused-vars
return `/interaction/${ctx.oidc.uuid}`;
},
clientCacheDuration: 1 * 24 * 60 * 60, // 1 day in seconds,
ttl: {
AccessToken: 1 * 60 * 60, // 1 hour in seconds
AuthorizationCode: 10 * 60, // 10 minutes in seconds
ClientCredentials: 10 * 60, // 10 minutes in seconds
IdToken: 1 * 60 * 60, // 1 hour in seconds
RefreshToken: 1 * 24 * 60 * 60, // 1 day in seconds

// HEROKU EXAMPLE ONLY, do not use the following expiration unless you want
to drop dynamic
// registrations 24 hours after registration
RegistrationAccessToken: 1 * 24 * 60 * 60, // 1 day in seconds
},
};

module.exports.clients = [
{
client_id: 'testlogin-oidc',
client_secret: 'testlogin-oidc',
grant_types: ['refresh_token', 'authorization_code'],
redirect_uris: ['http://localhost:3030/auth/openid/callback'],
post_logout_redirect_uri: 'http://localhost:3030/',
response_type:[ 'token','id_token', 'code'],
// scope:"openid profile api1",
filterProtocolClaims: true,
loadUserInfo: true,
token_endpoint_auth_method: "client_secret_post"
}

];

**Comment by jainmanoj** [comment]
const assert = require('assert');
const _ = require('lodash');

const store = new Map();
const logins = new Map();
const uuid = require('uuid/v4');

const USERS = {
'23121d3c-84df-44ac-b458-3d63a9a05497': {
email: 'foo@example.com',
email_verified: true,
address: {
country: '000',
formatted: '000',
locality: '000',
postal_code: '000',
region: '000',
street_address: '000',
},
birthdate: '1987-10-16',
family_name: 'Doe',
gender: 'male',
given_name: 'John',
locale: 'en-US',
middle_name: 'Middle',
name: 'John Doe',
nickname: 'Johny',
phone_number: '+49 000 000000',
phone: '+49 000 000000',
phone_number_verified: false,
picture: 'http://lorempixel.com/400/200/',
preferred_username: 'Jdawg',
profile: 'https://johnswebsite.com',
updated_at: 1454704946,
website: 'http://example.com',
zoneinfo: 'Europe/Berlin',
},
'c2ac2b4a-2262-4e2f-847a-a40dd3c4dcd5': {
email: 'bar@example.com',
email_verified: false,
},
};

class Account {
constructor(id) {
//this.accountId = id; // the property named accountId is important to
oidc-provider
this.accountId = id || uuid();
store.set(this.accountId, this);
}

// claims() should return or resolve with an object with claims that are
mapped 1:1 to
// what your OP supports, oidc-provider will cherry-pick the requested ones
automatically
claims() {
return Object.assign({}, USERS[this.accountId], {
sub: this.accountId,
email : this.email,
name : this.given_name

});
}


// static async findById(ctx, id) {
// this is usually a db lookup, so let's just wrap the thing in a promise,
oidc-provider expects
// one
// return new Account(id);
// }

static async findById(ctx, id, token) { // eslint-disable-line
no-unused-vars
// token is a reference to the token used for which a given account is
being loaded,
// it is undefined in scenarios where account claims are returned from
authorization endpoint
// ctx is the koa request context
if (!store.get(id)) new Account(id); // eslint-disable-line no-new
return store.get(id);
}

static findByLogin(email) {
const lowercased = String(email).toLowerCase();
const id = _.findKey(USERS, { email: lowercased });
assert(id, 'invalid credentials provided')
if (!store.get(id)) {
store.set(id, new Account(id));
}

return Promise.resolve(store.get(id));
}

static async authenticate(email, password) {
assert(password, 'password must be provided');
assert(email, 'email must be provided');
const lowercased = String(email).toLowerCase();
const id = _.findKey(USERS, { email: lowercased });
assert(id, 'invalid credentials provided');

// this is usually a db lookup, so let's just wrap the thing in a promise
return new this(id);
}
}

module.exports = Account;

**Comment by panva** [comment]
would you mind formatting your messages? This is PITA to go through.

**Comment by panva** [comment]
would you mind formatting your messages in the future? This is PITA to go through.

when using your account's findById i get all the claims requested by the authorization request. So you're likely not configuring it. Please see the [example](https://github.com/panva/node-oidc-provider-example) and most importantly [configuration](https://github.com/panva/node-oidc-provider/blob/master/docs/configuration.md) first before resolving to opening issues.

furthermore, this client configuration block does not do anything, see configuration section `Clients`.

> response_type: ['token', 'id_token', 'code'],
> // scope:"openid profile api1",
> filterProtocolClaims: true,
> loadUserInfo: true,

and the following is also invalid as there is no scope name, scopes aggregate claims and this is configured with the claims property of configuration

>  From node-oidc-client - scope is set to retrive following claims
>
>      "authorization_params": {
>          "scope": "openid profile phone email name"
>  }
