### ISSUE TITLE
Application fails when there is no authorizations and client is making `session/end` request with id_token_hint

### ISSUE THREAD

**Issue by infloop** [panva/node-oidc-provider#295]
Hi, we have a small issue when embedding `node-oidc-provider` in our project.

Steps to reproduce:
1) Run the provider application server with session management on.
1) Open any browser, open  `<oidc-server-host>/auth/?client_id=foo&response_type=id_token+token&scope=openid+email&nonce=foobar&prompt=login`
2) Do all the interactions and promts, receive `id_token` value
3) Open new **anonymous** tab in browser and open `<oidc-server-host>/session/end?id_token_hint=$id_token`
4) Try to clear only one client session (do not destroy the session completely)
5) Application fill fail at `/lib/actions/end_session.js` at line 182. because  `session.authorizations` is undefined.

At this code:

```javascript
 } else if (logout.clientId) {
   delete session.logout;
   delete session.authorizations[logout.clientId];
   ctx.cookies.set(`${provider.cookieName('state')}.${logout.clientId}`, null, opts);
 }
```

I think it will be better to check session.authorizations first:
```javascript
 } else if (logout.clientId) {
   delete session.logout;
   if (session.authorizations) {
     delete session.authorizations[logout.clientId];
   }
   ctx.cookies.set(`${provider.cookieName('state')}.${logout.clientId}`, null, opts);
 }
```

What do you think?

**Comment by panva** [comment]
Hi @infloop 

nice catch, would you open a PR with a fix and add a test case in `test/session_management/end_session.test.js`?

**Comment by infloop** [comment]
Hi, @panva 

Ok, Thanks for the information and the fix.
