### ISSUE TITLE
Common middleware for custom grant types

### ISSUE THREAD

**Issue by elendirx** [panva/node-oidc-provider#297]
While implementing custom grant types, I need to run some of the checks already covered by the authorization middlewares.

One example is checking for required OAuth2 params as covered in [oauth_required.js](https://github.com/panva/node-oidc-provider/blob/210e6a5c400c2a93b134f9981bf1e3419fd1ab25/lib/actions/authorization/oauth_required.js). 

I have to either copy+paste it or directly require the file from within the node_modules to use it. Would it be a plausible idea to make some of these middlewares public? Thanks!

**Comment by panva** [comment]
Ahoj @elendirx,

you may reuse any of the errors (they're exposed under `Provider.errors`) but not the middlewares. I'd like to avoid exposing middlewares since then i'm essentially making them a public API and mustn't make breaking changes in 'em.

Makes sense?

**Comment by elendirx** [comment]
I expected this answer, because yes you're right about the maintenance, but I tried to ask anyway. :-) I'll copypaste, no problem. Thanks!

**Comment by amaciver** [comment]
Related question: How would you recommend pulling Provider configuration into the custom grant? I would like to avoid requiring the WeakMap, but some of the middlewares and other checks that I am copying for this custom grant want configuration information.

**Comment by panva** [comment]
@amaciver you know what your configuration is when you create that handler, loading the internal configuration is not necessary, if you're running multiple instances then generating that handler from a function that gets YOUR configuration object is the right thing to do.

**Comment by amaciver** [comment]
roger that, thanks 👍
