### ISSUE TITLE
Session Find Returns New Session

### ISSUE THREAD

**Issue by jpreese** [panva/node-oidc-provider#299]
It looks like the .find() method within the Session class will always return a new session, even if a session is not found.

I noticed this in my app when the interactionFinished method (within provider.js) threw an exception when trying to set the Location header to interaction.returnTo

If you search for a session that doesn't exist, a new session will be returned to you with no data )which means no returnTo property) causing the interactionFinished method to fail.

**Comment by SokratisVidros** [comment]
Does this happen in version 4.x.x or 3.x.x?

**Comment by jpreese** [comment]
We're currently running 2.13.1 -- but looking at the current commit of session.js I would expect similar behavior.

**Comment by panva** [comment]
I see.

Are you dropping the sessions from your storage before they're no longer needed? The thing is, these helpers look for these sessions inside `getInteraction` which first looks for the cookie and session.find requires an id (the cookie value) to load a session.

**Comment by jpreese** [comment]
If the flow goes as expected, there isn't really an issue. After the interaction is completed, the session is destroyed within resume.js

The problem arises generally when users click the back button after being dropped on the landing page. 

1. You begin the interaction on the login page, and a session is given to you.
2. Credentials are entered correctly, and you're redirected to the landing page, destroying the session.
3. You click the back button, which dumps you on site.com/interaction/<some-session-guid>
4. Attempting to login from this screen will throw an error at provider.js because it looks up <some-session-guid> and returns an empty session object with no properties other than .id

**Comment by panva** [comment]
Thank you for these steps, very helpful.

**Comment by panva** [comment]
When the user submits the form and you call finished you might as well clear the interaction cookie set for the interaction path. That will prevent this from happening. That's a good thing to do nonetheless.

**Comment by panva** [comment]
See #301

**Comment by jpreese** [comment]
Awesome, thanks @panva! This is more in line with what I would expect the behavior to be.
