### ISSUE TITLE
Error validating client secret

### ISSUE THREAD

**Issue by alejandrogj** [panva/node-oidc-provider#302]
Hello!

I´m sending a token request with this data

```
POST /token HTTP/1.1
Host: localhost:3000
Content-Type: application/x-www-form-urlencoded
Authorization: Basic ZGQ5ZDkzYTktZmNjOS00OGUyLWJkYjgtNWM2MWI0NjNhMDI4OldpTXdiUFlscWlJKzdwUTExN3dpM3A5UjA3OGQxbURlL1dNM0dadHZkTXkySTBZblEvTDh0T1hzaFJWMWJ4OHV1
Cache-Control: no-cache

client_id=dd9d93a9-fcc9-48e2-bdb8-5c61b463a028&grant_type=authorization_code&code=abc&redirect_uri=https%3A%2F%2Fclient.example.org%2Fcallback
```
The client secret in my mongo database is 

`WiMwbPYlqiI+7pQ117wi3p9R078d1mDe/WM3GZtvdMy2I0YnQ/L8tOXshRV1bx8uu`

But after this line of code

https://github.com/panva/node-oidc-provider/blob/master/lib/shared/token_auth.js#L73

the "+" is removed from the client secret. Because of this the client authentication fails

Thanks for your time

**Comment by panva** [comment]
https://github.com/panva/node-oidc-provider/releases/tag/v3.0.0

please make sure you encode your username and password tokens in the Basic scheme according to the standard

**Comment by alejandrogj** [comment]
Awesome! When URL encoding username and password works like a charm

Thanks!

**Comment by panva** [comment]
`URL encoding` is not the same as `x-www-form-urlencoded` but sure, depends on the characters in the secret (space in particular) :)
