### ISSUE TITLE
How to close server instance?

### ISSUE THREAD

**Issue by s-a** [panva/node-oidc-provider#304]
Hi. I tried to call `.close()` method of koa server which is returned from `.listen` method but the node instance is still running. Do I need to clean up other things like mongo db connection or something else?

**Comment by panva** [comment]
> I tried to call .close() method of koa server which is returned from .listen method but the node instance is still running.

And does the server close? (that one is interesting to me)

If your node process is still running this has nothing to do with the provider and just means you need to close connections or other processes that are blocking your event loop from closing. That's a node thing.

**Comment by s-a** [comment]
`HTTP` services are not available anymore. `server.address()` returns `null`. So yes it is down. I am sure the problem is in my provider server code. But no idea where it hangs. So far it loads only the provider server code which is based on the mongodb koa example. I thought maybe I need to close database adapter.

**Comment by s-a** [comment]
Thanks a lot. It took while for me to figure out how to access the client instance from the mongodb provider. After call `.close` method of the mongo client the server exits as expected. By the way your support here is amazing. Do you have some paypal address to receive a donation outer there?
