### ISSUE TITLE
feature request: pass wanings to custom handler

### ISSUE THREAD

**Issue by s-a** [panva/node-oidc-provider#305]
I get warnings like `NOTICE: a draft/experimental feature (backchannelLogout) enabled, future updates to this feature will be released as MINOR releases` which are very usefull! But they crash my unit test log. Does there exist a way to implement a custom handler so I can pass them through my logger instance?

**Comment by panva** [comment]
> Does there exist a way to implement a custom handler so I can pass them through my logger instance?

Nope, seems a bit overkill for what is essentially just an overload of console.warn and console.info

https://github.com/panva/node-oidc-provider/blob/master/lib/helpers/attention.js
