### ISSUE TITLE
id string provided to database adapter is not a valid UUID

### ISSUE THREAD

**Issue by lfurzewaddock** [panva/node-oidc-provider#306]
Hi, I'm currently developing a massive-js adapter for PostgreSQL and testing it with the provided AdapterTest class.

The problem is the id value string generated by node-oidc-provider is a 48 character string, rather than a valid UUID (32 character, hyphen separated groups), so it is rejected by a PostgreSQL table using a 'uuid' data type for its 'id' column.

The 48 character string is generated with `return base64url(uuid());` in file `lib/models/formats/legacy.js` and added to the base_token jti property `lib/models/base_token`.

Later, the same 48 character string is presented to the adapter  'upsert' method where it fails.

**Comment by panva** [comment]
Hi @lfurzewaddock 

The identifier is not a uuid, if you find a piece of documentation saying so, please let me know.

https://github.com/panva/node-oidc-provider/blob/v4.1.3/example/my_adapter.js#L26-L27

If you're working on an implementation today i also highly suggest to use the `opaque` storage format. 
- [1] https://github.com/panva/node-oidc-provider/blob/master/docs/configuration.md#formats
- [2] https://github.com/panva/node-oidc-provider/blob/v4.1.3/example/my_adapter.js

**Comment by lfurzewaddock** [comment]
Thanks for your quick reply @panva.

It was just an assumption that the identifier format should be a UUID as it is to be used for a unique primary key.

Thanks for the tip RE: storage format. 

Currently my use case is focused around supporting OIDC Implicit flow for web applications. In that scenario would you recommend using `jwt` storage over `opaque`?

**Comment by panva** [comment]
Depending on your use case. But only for AccessToken, for other tokens thia never makes sense.
