### ISSUE TITLE
Any plan to implement UMA2?

### ISSUE THREAD

**Issue by endyjasmi** [panva/node-oidc-provider#307]
As the title said, any plan to implement UMA2?

**Comment by panva** [comment]
Not at this point, but something i can consider. Care to share the relevant specification(s)?

**Comment by endyjasmi** [comment]
The working group page for UMA2 is located at https://kantarainitiative.org/confluence/display/uma/Home.

The spec can be found here https://kantarainitiative.org/confluence/display/uma/Specifications+and+Auxiliary+Documents

**Comment by panva** [comment]
It's not something i'm going to pursue in the near future. If time allows and this changes i'll reopen and let you know.
