### ISSUE TITLE
Question: Implementing token exchange draft

### ISSUE THREAD

**Issue by matej-prokop** [panva/node-oidc-provider#308]
Ahoj @panva,

I would like to implement [token-exchange-draft](https://tools.ietf.org/html/draft-ietf-oauth-token-exchange-14) and use it in our API gateway. It matches use-case described within https://github.com/panva/node-oidc-provider/issues/211:

`4. have the API gateway contact the OIDC provider to exchange the access token given by the client SPA against a JWT, and add this JWT to the requests to the underlying microservices`

Example request to exchange token is following (section 2.3. within draft):
```
POST /as/token.oauth2 HTTP/1.1
Host: as.example.com
Authorization: Basic cnMwODpsb25nLXNlY3VyZS1yYW5kb20tc2VjcmV0
Content-Type: application/x-www-form-urlencoded

grant_type=urn%3Aietf%3Aparams%3Aoauth%3Agrant-type%3Atoken-exchange
&resource=https%3A%2F%2Fbackend.example.com%2Fapi%20
&subject_token=accVkjcJyb4BWCxGsndESCJQbdFMogUC5PbRDqceLTC
&subject_token_type=
 urn%3Aietf%3Aparams%3Aoauth%3Atoken-type%3Aaccess_token
```

and matching response:
```
{
  "access_token":"access-token-in-jwt-format",
  "issued_token_type": "urn:ietf:params:oauth:token-type:access_token",
  "token_type":"Bearer",
  "expires_in":60
}
```

### Questions:
1) Note that the request doesn't contain any `client_id`. Is it possible to configure `node-oidc-provider` to not require `client_id` for some grant (token-exchange grant in my case)?
2) Is it possible to configure different access token format for different grants? When issuing access token for "end-user" client using standard flow, I want to issue non JWT token (example `YTA4YjdkOWEtM2VmNS00Njc0LTg1YmUtYTEwMzI5MGMzNzk40nENeYp_4tIZD65TeLuSSBhpCmffkje7fjpVuzGiGkYQQONDbpqZ4zAF1E9IAYqQl5XuihsiFoC5aYw0Fi5_BA`. On the other hand, I want to use JWT format when issuing access token during token exchange.

**Comment by panva** [comment]
Hi @matej-prokop,

1) the need for client_id comes from the client's registered token_endpoint_auth_method. In your linked example the client_id is sent through `Authorization: Basic cnMwODpsb25nLXNlY3VyZS1yYW5kb20tc2VjcmV0`, you don't have to worry about it.
2) This isn't possible out of the box, the defined format is global. You'll have to write a custom format then using the four available public methods on the BaseToken or in your case AccessToken interface, and defer depending on your custom policy. These are

https://github.com/panva/node-oidc-provider/blob/v4.1.3/lib/models/base_token.js#L117-L170

- [klass].prototype.getValueAndPayload
- [klass].prototype.constructor.getTokenId
- [klass].prototype.constructor.verify
- [klass].prototype.constructor.generateTokenId

and you can see the existing implementation for each defined format in https://github.com/panva/node-oidc-provider/tree/v4.1.3/lib/models/formats

I would also be interested in the custom grant implementation you have, just out of curiosity, please share here or via email if you can.

**Comment by matej-prokop** [comment]
Hi @panva, thank you. It is great to you replied so quickly.

ad 1) I totally missed that `Authorization` holds `client_id` so I was confused. It makes sense now.

ad 2) As I am in prototyping phase, I decided to workaround by issuing an IdToken (that is configured to be in JWT format) instead of AccessToken (and pretend that it is access_token) in order to test entire flow. I know it is hack but I can do it as you suggested once I will see that entire flow is viable.

> I would also be interested in the custom grant implementation you have, just out of curiosity, please share here or via email if you can.

Here is very first draft of my custom grant. Any feedback is welcome.  As you can see I have to figure out how to validate and set `audience` properly. Also this implementation is very specific. It requires `audience`, `subject_token_type` to be `access_token`, etc. 

```
const { errors } = require("oidc-provider");
const { InvalidGrant, InvalidRequest } = errors;

const tokenExchangeHandler = async (provider, context, next) => {
  const { subject_token_type, subject_token, audience } = context.oidc.params;

  if (!subject_token_type) {
    throw new InvalidRequest(`missing parameter subject_token_type.`);
  }

  if (!audience) {
    throw new InvalidRequest(`missing parameter audience.`);
  }

  if (subject_token_type !== "access_token") {
    throw new InvalidRequest(`unsupported subject_token_type.`);
  }

  const { Account, AccessToken, IdToken } = provider;

  const accessToken = await AccessToken.find(subject_token, {
    ignoreExpiration: true
  });

  if (!accessToken) {
    throw new InvalidRequest("access token not found");
  }

  if (accessToken.isExpired) {
    throw new InvalidRequest("access token is expired");
  }

  const account = await Account.findById(
    context,
    accessToken.accountId,
    accessToken
  );

  if (!account) {
    throw new InvalidGrant(
      "access token invalid (referenced account not found)"
    );
  }

  // TODO: create token as access token in JWT format with short expiration
  // creating as IdToken is hack (it should be access token) to have token in JWT format
  const token = new IdToken({
    ...(await account.claims("id_token", accessToken.scope))
  });

  token.scope = accessToken.scope;

  const idToken = await token.sign(context.oidc.client, {
    //TODO: check that audience is valid and could be set (based on access token)
    audiences: [context.oidc.params.audience]
  });

  context.body = {
    expires_in: IdToken.expiresIn,
    access_token: idToken,
    token_type: "Bearer"
  };

  await next();
};

module.exports = {
  factory: provider => (context, next) =>
    tokenExchangeHandler(provider, context, next),
  parameters: ["subject_token_type", "subject_token", "audience"]
};
```

**Comment by panva** [comment]
Specific implementations are inevitable with Token Exchange, that's why it can never be shipped by default.

I'll be shipping a tiny improvement to the custom grant that will allow you to specify parameters which can be "duped" (in case of Token Exchange that'd be audience and resource).

**Comment by thomasvargiu** [comment]
Hi @matej-prokop, do you have some gist on how you implemented it (a working example)?
