### ISSUE TITLE
.well-known/openid-configuration behind a load balancer with ssl termination

### ISSUE THREAD

**Issue by jgordor** [panva/node-oidc-provider#31]
Hi,

.well-known/openid-configuration is pointing to the http version of paths (authorization_endpoint, ...), instead the https one where issuer is declared and exposed.

Also, in nginx I setup the proxy_set_header X-Forwarded-Proto https; but seems that the lib is not using it. How I can tweak to be able to allow autodiscovery?

Thanks in advance

**Comment by panva** [comment]
The application itself just relies on koa's internal originalUrl or similar methods, those need to be instructed to trust the headers. The example is using a 'balancer' of heroku already - you need to set your koa's application `proxy` property to true, that way the koa app starts using/trusting the headers. See http://koajs.com/#settings

**Comment by jgordor** [comment]
Thanks,  `app.proxy = true` solved!

**Comment by fdidron** [comment]
How would one setup the same config with a connect application ?

**Comment by panva** [comment]
Likely the same as with express one, set the proxy option on the koa application of oidc-provider.

See: https://github.com/panva/node-oidc-provider/blob/master/docs/configuration.md#trusting-ssl-offloading-proxies
