### ISSUE TITLE
client_secret_jwt and private_key_jwt questions, no Key found

### ISSUE THREAD

**Issue by jayeshnazre** [panva/node-oidc-provider#310]
Hi this is what I am trying to do. I am trying to use introspection endpoint to validate the access token using the token_endpoint_auth_method: 'client_secret_jwt'.
This is the configuration of my client provider, I am using the second client configuration for RP to validate my access token. The first array set is used for implicit flow.

```js
const clients = [{
    client_id: 'test_implicit_app',
    grant_types: ['implicit'],
    response_types: ['id_token token'],
    redirect_uris: ['https://ubuntu.local:3001/pub/tokenext'],
    token_endpoint_auth_method: 'none'
},
{
    client_id: 'client-introspection',
    client_secret: 'secret',
    redirect_uris: [],
    response_types: [],
    grant_types: [],
    token_endpoint_auth_method: 'client_secret_jwt'
  }
];
```

I am using postman to submit the following http request

```
POST /token/introspection HTTP/1.1
Host: ubuntu.local:3001
Content-Type: application/x-www-form-urlencoded
Cache-Control: no-cache
Postman-Token: 1148e17d-424d-4e1b-a06f-b54c7b537552

token=NGE4ODQ5NDQtODRjMy00MDQyLTkzYWUtN2E3NGZiMDQ5NjAzggOY4PLVpsO07sHtnF5Def8IG2iqFJbT_fzd5OoYS-axmyzQ0jMSJv0MjU6MUUIPCDimcr3U7jc65Gl48rWWpw&client_assertion_type=urn%3Aietf%3Aparams%3Aoauth%3Aclient-assertion-type%3Ajwt-bearer&client_assertion=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJjbGllbnQtaW50cm9zcGVjdGlvbiIsInN1YiI6ImNsaWVudC1pbnRyb3NwZWN0aW9uIiwiYXVkIjoiaHR0cHM6Ly91YnVudHUubG9jYWw6MzAwMS90b2tlbi9pbnRyb3NwZWN0aW9uIiwianRpIjoxNTMxMzE5NzczLCJleHAiOjE1MzEzMTk3NzN9.mWlLJtH09B6C1caA-2ot1v0Gku0snHU-u28PQoazwa8
```

I get the following error:  
```js
{
    "error": "invalid_client",
    "error_description": "client authentication failed"
}
```

One of the things I am finding it hard to find is examples of using the other    token_endpoint_auth_method like client_secret_jwt and private_key_jwt.
I am using implicit flow but want to use these two secure methods to validate my access token. Can someone help me with this issue.

When I debug I get the "no Key found" error at jwt.verify in token_jwt_auth.js file.

**Comment by panva** [comment]
The client_secret `secret` is not of sufficient entropy to form non-padded key usable for HS256.

```js
const ks = require('node-jose').JWK.createKeyStore();
const base64url = require('base64url');

(async () => {
  let key = await ks.add({
    alg: 'HS256', use: 'sig', kty: 'oct', k: base64url('secret'),
  });

  console.log(key.algorithms('sign'));

  key = await ks.add({
    alg: 'HS256', use: 'sig', kty: 'oct', k: base64url('secret-loong-enough-to-be-usable'),
  });

  console.log(key.algorithms('sign'));
})();
```

If you specify `introspection_endpoint_auth_signing_alg` on the client the secret length will be validated.

**Comment by jayeshnazre** [comment]
Changing to long client_secret helped. Thanks panva. By the way great work on this node oidc provider.
  A few follow up questions: 
Question 1: The spec wants the introspection claim "exp” as required. I am a bit puzzled by this specification requirement, as the RP (Relying Party) can send anything to the OIDC in that field with epoch value > current time. So what is the real use of that field is a mystery to me, all it ensures is that RP is sending a value that is greater than current time but what benefit you get with that since any malicious program knows this standard as well? Any thoughts.
Question 2: The use of “jti” claim is to ensure that the request for introspection is unique. Now for introspection, why does it matter? I know the standard says - “A unique identifier for the token, which can be used to prevent reuse of the token.”, but the RP is not asking for a new token just validating the access_token via the introspection endpoint. Any thoughts on this or am I missing something?


**NOTE: I am also going to do private key sample next. My intent is to help others as there are not any examples of how to use these two client authentication on this forum with your package.**

**Comment by panva** [comment]
Some resources that might help you, I don't really see the need for examples in the OP library since a client library should help you create those assertions.

- [spec] http://openid.net/specs/openid-connect-core-1_0.html#ClientAuthentication
- [op check implementation] https://github.com/panva/node-oidc-provider/blob/v4.1.3/lib/shared/token_jwt_auth.js
- [rp assertion creation] https://github.com/panva/node-openid-client/blob/v2.2.1/lib/client.js#L845-L863

To your questions, for both actually the same:

`*_jwt` auth is great for many reasons (regardless of which endpoint you use them for)

1) in general it does not leak the client's credentials but still allows for verification (the assertion's integrity) - changing any claim in the assertion will make the signature verification fail
2) are not re-usable if they leak (jti claim) - tho you should still avoid leaking them (i.e. storing them in a db or logging them in clear unredacted)
3) if not used (by whomever issued them) and/or jti re-use isn't implemented on the OP, the issuer (RP) has means to limit the attack surface by limiting it's expiration (exp claim)

When all the required claims are present and you keep your secrets/keys private, there's very limited capability for an attacker to abuse the assertion for making more calls, as opposed to including the secret in the http request (basic or body).

While I don't agree with your argumentation that it doesn't make much sense for introspection, think about how helpful the above is when used for authorization code or refresh token exchange.

**Comment by jayeshnazre** [comment]
Thanks for your inputs - @panva. I will like to still continue with the questions based on just using oidc-provider as a server side option for OIDC, assuming the client can be written in any other programming language. With that in mind, I went along using private_key_jwt option for client side to validate the access_token through introspection endpoint. I have a few questions hopefully you can share your thoughts :
**Some context:** I used postman to submit the request, below is the raw http request – 

POST /token/introspection HTTP/1.1
Host: ubuntu.local:3001
Content-Type: application/x-www-form-urlencoded
Cache-Control: no-cache
Postman-Token: b3522b7e-6e03-49c5-8748-c2792e3abf9d
token=ZDQ2ZjMyODItMDBlYS00NmY5LTk0NzMtMjdlZGEzMTVhMGRjeEow9IUzlsEjv3Et0XOjSo21kdswQ_4Txh6VG_mm6CTTut3Y-KVe3EVMXcGyW-WDHQ5BxW7vF_vVQGhJ2WUfLw&client_assertion_type=urn%3Aietf%3Aparams%3Aoauth%3Aclient-assertion-type%3Ajwt-bearer&client_assertion=eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJjbGllbnQtaW50cm9zcGVjdGlvbiIsInN1YiI6ImNsaWVudC1pbnRyb3NwZWN0aW9uIiwiYXVkIjoiaHR0cHM6Ly91YnVudHUubG9jYWw6MzAwMS90b2tlbi9pbnRyb3NwZWN0aW9uIiwianRpIjoiNjUxMjMzYWw7YXM4OTdoamFzZDtsLTE1MTYyMzkwMjIiLCJleHAiOjE1MzEzNzM5OTd9.U_MU7Fa0Y8vUWC6COv_sVVGtM19KcgNEW5cxkSyw-HDj68qphrinHbIhd7CgkYlY3ygnkUsVA1DJq4yZ2V3azmuhw0ohme7zNTmyPoYmGC8mXdzk_ZXGat_rE5F8H4gWGuWLKTpdpJ7hLe3K9klsXSmLu2JhDbZQ3P7eX-w38WUQZngLD58lktKzJomKDcfijfbX4rhg5CwouGUDoJTZb2pxs11iXMgU53ZfPvfEND--3FkshxrwT2ODmo31xBZeVsegGUPXXjNq4vxrQMxOOi18cfWifT_PRLZDCmKDHA0As7bexd8Y40Gxm30qQ6L-bOIgRW2huQqfShe-nMoHkQ


At the nodejs server side, I have registered the client as shown below: 
const clients = [{
    client_id: 'test_implicit_app',
    grant_types: ['implicit'],
    response_types: ['id_token token'],
    redirect_uris: ['https://ubuntu.local:3001/pub/tokenext'],
    token_endpoint_auth_method: 'none'
},
{
    client_id: 'client-introspection',
    redirect_uris: [],
    response_types: [],
    grant_types: [],
    token_endpoint_auth_method: 'private_key_jwt',
    jwks: { keys:  [{ kty: 'RSA', n: 'AM_v_dfA2WHwGOJARocMlV-7KVZ99l7GRtsAh1unatvfFN82dQslOJmxskJtX8fsfrd3aEvf-UKI48SslQDkP1GZvZlzyaFpyEZ8Wxc1n_dKhh9hVRSHtdE-vcydi83Jg5U13EEENniyE-sChmYKFNnYOrWZG91kurmCR4sVWr5XQloRAlHn59DKU-T-cC34yjneV0y0yOpmqqBHz5SYfSnXUMD9Lyi6viHhhaE94aBp_eWLT6gAxFqA7jjw8x9h8v_WK0gTahDfWYGAnEBv9__ocJ-JnDVBlXg7vv_hITOaoLG2rSVUv_v83764kDDgv3BZl8BBEvnSVUTmEvT5Ho8',  e: 'AQAB' }]}
  }
];

**Question 1:** I am using implicit flow and the RP is using the introspection endpoint for validation of access_token only. It seems like I need to register the “client” with my OIDC-provider with the public key of PKI as shown above, is this how it’s done? The reason I ask is: the private key is used by RP to sign the JWT payload as shown by the first postman raw – http post to the introspection endpoint **(the signed jwt is passed as client_assertion from RP end, I am using postman to simulate RP call)**.  
**Question 2:** So if we have multiple RP will there be multiple private/public keys with the public keys register as separate clients in the “clients” array above? Just seemed odd hence checking if I am doing something wrong here.
Any inputs/thoughts will help

**Comment by panva** [comment]
> is this how it’s done?

You have two ways of letting the OP know of the public keys
`jwks_uri` or `jwks` client properties (see property definitions in [Dynamic Client Registration 1.0](https://openid.net/specs/openid-connect-registration-1_0.html)

Either of these can yield multiple keys (see `keys` being an array?), you might as well register more clients. It depends on what you feel is right.

**Comment by panva** [comment]
And since i can see legacy token format being used...

If you're working on an implementation today i also highly suggest to use the `opaque` storage format. 

- [1] https://github.com/panva/node-oidc-provider/blob/v4.1.3/docs/configuration.md#formats
- [2] https://github.com/panva/node-oidc-provider/blob/v4.1.3/example/my_adapter.js

**Comment by jayeshnazre** [comment]
@panva 
Thanks for responding. My apologies for not doing a good job of formatting and I just realized that when I format in word and copy paste the same. the rich text box template capability in this site does not retain the styles – as usually ms-word.
Just so I understand, I am assuming that what I am doing in terms of using private keys RP end to sign and using public keys at OIDC end to verify is correct, basically I will end up with multiple public keys at the OIDC end one per client (RP)? I first wanted to confirm that is how its done? Right

The part of your response pertaining to using jwks_uri instead of jwks hard coded in properties is just so you can make the client registration more dynamic without changing the configuration setting at the OIDC end as that will require a restart of the server hosting the oidc-provider module everytime a new client (RP) needs to added, as its not dynamic via jwks? Is my understanding correct?

Thanks for being so responsive.

**Comment by panva** [comment]
> Just so I understand, I am assuming that what I am doing in terms of using private keys RP end to sign and using public keys at OIDC end to verify is correct, basically I will end up with multiple public keys at the OIDC end one per client (RP)? I first wanted to confirm that is how its done? Right

How else would you do it? expose your public so that it may be used to verify what you sign with private.

ad jwks_uri) yes, this is so that you can easily rotate your keys without having to reconfigure the clients on the OP.
