### ISSUE TITLE
Features: proper user consent | limited client scopes | multi-user sessions

### ISSUE THREAD

**Issue by cymarechal** [panva/node-oidc-provider#311]
Hi,

I was looking at multiple features Google OIDC implemented, as it would probably be a great idea to get inspired by it.

1. **Proper user consent** (I personally consider this one as a bug)
Now, user consent seems to be client-based. I can first ask for very basic scopes:

> http://[URL]/auth?
>  -  client_id=example&
>  -  **scope=openid email**&
>  -  [...]

If the user accepts it, I can then ask for very sensitive scopes without any interaction from the user:

> http://[URL]/auth?
>  -  client_id=example&
>  -  **scope=openid email sensitivescope**&
>  -  [...]

I believe that user consent should be per client and per scope.

2. **Limited client scopes**
Is there any way we could limit our clients accessible scopes?

3. **Multi-user sessions**
(I know that session management is an experimental feature)
It would be great to handle the `prompt=select_account` parameter.

Is there any of these (cool) features I could help you implement?

**Comment by cymarechal** [comment]
Perfect, thanks!

**Comment by panva** [comment]
I’ll be tracking a subset of this in #340. Please subscribe to that one for updates.
