### ISSUE TITLE
`expiresIn` argument is either seconds or timestamp

### ISSUE THREAD

**Issue by skeltonm** [panva/node-oidc-provider#314]
Since version 4.0.1, the `expiresIn` argument to the adapter `upsert` function either is a value in seconds, or a epoch timestamp.  This changed with [this commit](https://github.com/panva/node-oidc-provider/commit/23172dbd8b4f49d65e1c8222c516da7393f97313#diff-1c25f2af06a7bfd6c36abff0f88b9a2b).

This is problematic since there is no marker showing if the value is seconds or a timestamp.

Should this be updated to always send a value in seconds to the `upsert` method?

**Comment by panva** [comment]
Just for session, right? Everywhere else its fine, isnt it?

**Comment by skeltonm** [comment]
From what I have observed, yes.  It is only affecting session.

**Comment by panva** [comment]
and only in `provider#interactionFinished()` helper. I'll have a fix shortly.

**Comment by skeltonm** [comment]
Thanks!

**Comment by panva** [comment]
thank you for reporting this!
