### ISSUE TITLE
registration_access_token - Revoked

### ISSUE THREAD

**Issue by codestorycooked** [panva/node-oidc-provider#317]
Hi @panva 

The standard mentions: 

>   If the client does not exist on this server, the server MUST respond
   with HTTP 401 Unauthorized and the registration access token used to
   make this request SHOULD be immediately revoked. (https://tools.ietf.org/html/rfc7592#section-2.1)

We can see that a `registration_access_token` is revoked(destroyed) when an incorrect `client_id` is provided for an GET/UPDATE/DELETE of a client => https://github.com/panva/node-oidc-provider/blob/master/lib/actions/registration.js#L66 . Error returned to the client is `invalid token provided`.

So, it is working as per the standard. The only thing we would like to know is whether there is a way in which we can catch this error and log it. This way when a user comes to us saying my registration access token is not working anymore we can go through the logs to figure out when it was incorrectly used.

Now that registration token is no more valid. We will crate new client for this particular client. So how can we delete this client with no `registration_access_token`?  What is typical practice to delete such clients?

**Comment by panva** [comment]
Hi @codestorycooked 

> Error returned to the client is `invalid token provided`.

Error returned is `invalid_token`. The above is just a description.

> The only thing we would like to know is whether there is a way in which we can catch this error and log it.

Two, actually. Choose the one that suites you best. The even route does not block the response sent to the caller, the middleware one might.

1) [README](https://github.com/panva/node-oidc-provider/blob/v4.3.0/README.md#events), [EVENTS](https://github.com/panva/node-oidc-provider/blob/v4.3.0/docs/events.md)

```js
const { errors: { InvalidToken } } = require('oidc-provider')
function listener(err, ctx) {
  if (err instanceof InvalidToken) {
    // your logic goes here
  }
}
provider.on('registration_read.error', listener);
provider.on('registration_update.error', listener);
provider.on('registration_delete.error', listener);
```

2) [configuration](https://github.com/panva/node-oidc-provider/blob/v4.3.0/docs/configuration.md#pre--and-post-middlewares)

```js
const routes = new Set(['client', 'client_update', 'client_delete']);
provider.use(async (ctx, next) => {
  await next();
  if (routes.has(ctx._matchedRouteName) && ctx.status === 401 && ctx.body.error === 'invalid_token') {
    // your logic goes here
  }
});
```

> So how can we delete this client with no registration_access_token?

You have access to your storage where you store all your clients and can also [invalidate](https://github.com/panva/node-oidc-provider/blob/v4.3.0/docs/configuration.md#clients) the running instance client cache.
