### ISSUE TITLE
Assistance: Upgrading from 2.13.1 to 4.1.2 (Introspection)

### ISSUE THREAD

**Issue by jpreese** [panva/node-oidc-provider#319]
We're trying to upgrade from 2.13.1 to 4.1.2 and are encountering a strange issue. Our primary application, using implicit flow, works just fine. No issues with the upgrade. Another one of our apps, using client_credentials, also works just fine.

We do have one app that uses introspection however, and this no longer seems to work. Digging through the web logs, it's always returning an HTTP 400. It does not do this on 2.13.1

![image](https://user-images.githubusercontent.com/6980197/42853976-9f9c79b0-8a07-11e8-9e4d-1ae9ec724d3a.png)

Obviously, there are a ton of variables here, so please feel free to close if its just impossible to deduce, but we figured you might have a couple ideas of what may have changed with introspection between these releases.

**Comment by panva** [comment]
Hi. 

Do you have Logs? The response json? Which steps have you taken to figure the problem out so far?

**Comment by panva** [comment]
I’m betting on the 3.x breaking change in fixing client_secret_basic authentication.

**Comment by panva** [comment]
I'm going to go ahead and close this as there's no issue so far. If you have a client that's sending invalid client_secret_basic or sending auth a different way than is specified by whatever auth method it's using it needs fixing. If you find issues feel free to report them.

To help you debug use DEBUG (see readme) or register a handler for `introspection.error` event (see events)

**Comment by jpreese** [comment]
Just to keep you up to date, we're thinking it has to do with decodeAuthToken(). One of our secrets throw a URI malformed error.

**Comment by panva** [comment]
That's what i kept saying

> My bet would be on how the client is authenticating. See 3.x and 4.x fixes related to client auth.

This was 3.x fix

**Comment by jpreese** [comment]
Yep! We just weren't exactly sure with which piece. We just got to a point to where we can actually see the error being returned.

Testing in a chrome browser, we can see it's throwing an exception. So we'll need to change our secrets.

Is there a standard way of generating secrets? We were just using

> openssl rand -base64 100

Which apparently isn't going to work

**Comment by panva** [comment]
Why would it not work? Just encode the username and password tokens according to the standard.

**Comment by jpreese** [comment]
The secret had a % in it, which causes the decodeURIComponent() method that was introduced to throw an exception. So going forward, we just need to make sure the generated string doesn't throw an exception in this method.

**Comment by panva** [comment]
No, you need to [encode your id and secret values into the basic header](https://github.com/panva/node-openid-client/blob/v2.2.1/lib/client.js#L864-L868) according to the spec. Just try and understand and implement it or get a well behaved client to do this for you.

Or switch to client_secret_body if you can't form url encode the tokens.
