### ISSUE TITLE
Question - Interaction (httpOnly _grant cookie) and SPA angular2 interaction app

### ISSUE THREAD

**Issue by jgordor** [panva/node-oidc-provider#32]
Hi,

I'm tryng to delegate all the interactions to a SPA js angular2 interaction app.

The main problem I'm facing it's that the signed cookie _grant is not accessible from js (http only), perfect to mitigate XSS attacks. Also tried to make an "initialization" get call to oidc backend to get the interaction params (client info, interaction type, ...) but the cookie is not sent to the server side (again http only).

I was thinking on sending this info via url params on the custom interactionUrl function, but seems that the cookie is set after the function is called, so, no this (ctx).cookies _grant available.

Do you know any way to do this?

Best

**Comment by panva** [comment]
Hello,

the reason you don't get the cookie to be sent to your initialization may be that you don't use the same 'path' as the interactionUrl, the cookie itself is bound to a path, this to help with corner cases where users have multiple authz open at the same time.

Anyway my suggestion would be to have the interaction url oidc redirects to use whatever mechanisms your SPA can work with. To begin with - i would simply serve the SPA template with the necessary information in the template already, thus removing any need to read the httpOnly cookie. Or you could read the cookie, and store it separately (maybe even overwrite it) with no httpOnly flag.

**Comment by jgordor** [comment]
Thanks! I ended up using the interactionUrl function to set an initialization cookie for the SPA, this adds an additional redirect but better (I think) that mixing the backend with the frontend.

Again, thanks for you help and this great lib!

**Comment by panva** [comment]
Glad you found a way. Can you share details on your solution? Maybe a snippet?

**Comment by jgordor** [comment]
Sorry for the delay, I still working on use cases, also, figuring out how to use the provider.resume coming from the SPA. I will write here the solution
