### ISSUE TITLE
Duplicate and unnecessary adapter calls

### ISSUE THREAD

**Issue by skeltonm** [panva/node-oidc-provider#325]
While using this package, I was noticing some speed issues when testing it on local.  As it turns out, there was another issue unrelated to this package, but because of that issue, I logged the adapter calls this package makes during the login process.

I am using the Authorization Code Flow and shown below is a list of the 5 routes on the IdP that are called during this process as well as the adapter calls during those routes.

_Note: `upsert` stands for update or insert_

**/auth**
get Session 59bf61c7-8a1a-471f-b595-803fccf3079c
upsert Session 7b95bf7c-f083-4771-ba14-076b77fb0fff
upsert Session 59bf61c7-8a1a-471f-b595-803fccf3079c

**/interaction/7b95bf7c-f083-4771-ba14-076b77fb0fff**
get Session 7b95bf7c-f083-4771-ba14-076b77fb0fff

**/interaction/7b95bf7c-f083-4771-ba14-076b77fb0fff/login**
get account 8f07862055ef2aed4b6235793c5efdc988c416722803f53a9e50d0dba0e99bf5
get Session 7b95bf7c-f083-4771-ba14-076b77fb0fff
upsert Session 7b95bf7c-f083-4771-ba14-076b77fb0fff

**/auth/7b95bf7c-f083-4771-ba14-076b77fb0fff**
get Session 59bf61c7-8a1a-471f-b595-803fccf3079c
get Session 7b95bf7c-f083-4771-ba14-076b77fb0fff
get Session 7b95bf7c-f083-4771-ba14-076b77fb0fff
remove Session 7b95bf7c-f083-4771-ba14-076b77fb0fff
get account 8f07862055ef2aed4b6235793c5efdc988c416722803f53a9e50d0dba0e99bf5
upsert AuthorizationCode NzYyNDE1MTQtYzFhYy00ZjYyLTk1YTUtMGNlNTFhZWY5OGVi
upsert Session 59bf61c7-8a1a-471f-b595-803fccf3079c

**/token**
get AuthorizationCode NzYyNDE1MTQtYzFhYy00ZjYyLTk1YTUtMGNlNTFhZWY5OGVi
get AuthorizationCode NzYyNDE1MTQtYzFhYy00ZjYyLTk1YTUtMGNlNTFhZWY5OGVi
upsert AuthorizationCode NzYyNDE1MTQtYzFhYy00ZjYyLTk1YTUtMGNlNTFhZWY5OGVi
get account 8f07862055ef2aed4b6235793c5efdc988c416722803f53a9e50d0dba0e99bf5
upsert AccessToken YjVlMjY4Y2ItN2E2MC00ZmM0LTg5MTYtOGEyMTBhNjViODg1

Two things prompted me to open this issue:

1. In the fourth route (/auth/7b95bf7c-f083-4771-ba14-076b77fb0fff), there is a duplicate get for the session with id (7b95bf7c-f083-4771-ba14-076b77fb0fff).
1. There is a redirect that occurs after `interactionFinished` is called that redirects the user to /auth/7b95bf7c-f083-4771-ba14-076b77fb0fff.  This redirect causing not only a speed decrease because of the redirect itself, but also because there are four extra adapter calls as a result (shown below)

   get account 8f07862055ef2aed4b6235793c5efdc988c416722803f53a9e50d0dba0e99bf5
   upsert Session 7b95bf7c-f083-4771-ba14-076b77fb0fff
   get Session 7b95bf7c-f083-4771-ba14-076b77fb0fff **\* 2**

**Comment by panva** [comment]
Hi @skeltonm 

Can you trace the calls down to the caller and eliminate any that come from userland (interactions)? I will take a peak at this after my holidays.

**Comment by skeltonm** [comment]
@panva The only change we have to your example that causes extra database interactions is the (get account 8f07862... in /interaction/7b95bf7c.../login).  In your example, you are just storing the logins in a `Map` so there isn't a call to a database to get a user.

Everything else works just like your example.

**Comment by skeltonm** [comment]
Here is the logs of routes and adapter calls using the basic provider setup code as shown in the readme of this repo.

**/auth**
get 7132c180-b671-4e51-b194-20b56bab791f
upsert 656d936c-798b-4534-8681-3028d58aae52
upsert 7132c180-b671-4e51-b194-20b56bab791f

**/interaction/656d936c-798b-4534-8681-3028d58aae52**
get 656d936c-798b-4534-8681-3028d58aae52

**/interaction/656d936c-798b-4534-8681-3028d58aae52/submit**
get 656d936c-798b-4534-8681-3028d58aae52
upsert 656d936c-798b-4534-8681-3028d58aae52

**/auth/656d936c-798b-4534-8681-3028d58aae52**
get 7132c180-b671-4e51-b194-20b56bab791f
get 656d936c-798b-4534-8681-3028d58aae52
remove 656d936c-798b-4534-8681-3028d58aae52
upsert N2I2OWVmMWItNjM1Mi00MzRhLWE4YmYtNGJkY2FkZjZhMzQx
upsert 7132c180-b671-4e51-b194-20b56bab791f

**/token**
get N2I2OWVmMWItNjM1Mi00MzRhLWE4YmYtNGJkY2FkZjZhMzQx
upsert MjA4MjJmYjUtYmU1ZC00NTIyLTg5OTMtNjBjMGMzZTU4Nzk4

**Comment by skeltonm** [comment]
Here is the logs of routes and adapter calls using the basic provider setup code as shown in the readme of this repo.

**/auth**
get Session 8316e19a-02c1-4fef-bfd3-f20102a8c2f3
upsert Session 856b5ea9-085a-44c9-95a2-c69febe4d595
upsert Session 8316e19a-02c1-4fef-bfd3-f20102a8c2f3

**/interaction/856b5ea9-085a-44c9-95a2-c69febe4d595**
get Session 856b5ea9-085a-44c9-95a2-c69febe4d595

**/interaction/856b5ea9-085a-44c9-95a2-c69febe4d595/submit**
get Session 856b5ea9-085a-44c9-95a2-c69febe4d595
upsert Session 856b5ea9-085a-44c9-95a2-c69febe4d595

**/auth/856b5ea9-085a-44c9-95a2-c69febe4d595**
get Session 8316e19a-02c1-4fef-bfd3-f20102a8c2f3
get Session 856b5ea9-085a-44c9-95a2-c69febe4d595
get Session 856b5ea9-085a-44c9-95a2-c69febe4d595
remove Session 856b5ea9-085a-44c9-95a2-c69febe4d595
get grant 856b5ea9-085a-44c9-95a2-c69febe4d595
upsert grant 856b5ea9-085a-44c9-95a2-c69febe4d595
upsert AuthorizationCode:NzkxY2M1NDctN2U2My00NGEzLWE3YTItM2Y0YzY5NDZkMmU5
upsert Session 8316e19a-02c1-4fef-bfd3-f20102a8c2f3

**/token**
get AuthorizationCode:NzkxY2M1NDctN2U2My00NGEzLWE3YTItM2Y0YzY5NDZkMmU5
get AuthorizationCode:NzkxY2M1NDctN2U2My00NGEzLWE3YTItM2Y0YzY5NDZkMmU5
get grant 856b5ea9-085a-44c9-95a2-c69febe4d595
upsert AccessToken:MWIwNDAwNWItZjU1OC00YjE5LTlkYjQtMjk1NzQ3YzgwMDQw

I'm not sure whey there is the two instances of **get grant** where the logs from my application doesn't have that, but nonetheless, the point is still the same.  There is an extra redirect causing more work as well as duplicated adapter calls.

**Comment by panva** [comment]
I’m not sure what you’re getting at it with the redirect. Its not extra. It’s there by design.

**Comment by skeltonm** [comment]
What is the purpose of that redirect the /auth/856b5ea9... after the user submits the login form?

**Comment by panva** [comment]
As far as interactionFinished goes it does exactly what it should, loads the interaction session, upserts with the results and hands off the request to the resume path where the request middlewares take over.

Looking at the code i don't see any duplicate finds, so please post your adapter with the logging code in it to verify your results.

> What is the purpose of that redirect the /auth/856b5ea9... after the user submits the login form?

To end the user interactions and finish the authorization request. Interactions aren't necessarily exclusively in the same node process on the same app. There are variety of use-cases which i don't have the time to explain all that rely on "handing off" the authorization flow. Example, interactions are on a different subdomain handled by a completely different app, that app just reads the cookie, loads the adapter data, and then stores it with a similar interactionfinished process. Then redirects back, oidc-provider cleans up and resumes auth flow.

**Comment by skeltonm** [comment]
You can the adapter I used for testing [here](https://gist.github.com/skeltonm/f7580f09c0f84978e0ed83606a9dbcf2).  It is just the default memory adapter with the storage calls called through helper functions to enable the logging.

**Comment by skeltonm** [comment]
I tracked down where the duplicate calls are coming from.

First, the duplicate session get.

The first call occurs when finding the interaction session during the resume process ([see here](https://github.com/panva/node-oidc-provider/blob/master/lib/actions/authorization/resume.js#L20-L23)).  The second call occurs when destroying the interaction session ([see here](https://github.com/panva/node-oidc-provider/blob/master/lib/actions/authorization/resume.js#L31)).

Second, the duplicate AuthorizationCode call.

The first call occurs when getting the authorization code for verification ([see here](https://github.com/panva/node-oidc-provider/blob/master/lib/actions/grants/authorization_code.js#L20-L22)).  The second call occurs when consuming the authorization code ([see here](https://github.com/panva/node-oidc-provider/blob/master/lib/actions/grants/authorization_code.js#L45)).

**Comment by panva** [comment]
Just as I suspected. Those second calls arent coming from adapter#find. You’re logging them as such but they arent.
