### ISSUE TITLE
Value of ctx.query after middleware

### ISSUE THREAD

**Issue by amaciver** [panva/node-oidc-provider#327]
**Describe the bug**
Hello, wondering if you have any advice:

I have inserted middleware to change a value of `req.query` in my express middleware stack (also have tried using `provider.use` both before and after `initialize`)

I can see that the value has changed throughout my middleware stack, but by the time it gets to `get_params.js`, I have verified that the value of `ctx.query` is the original value from the original request. 

Do you know what I am missing? I have referenced your docs about using middleware, and it seems like I am doing what is recommended.

**Comment by panva** [comment]
The answer is in knowing the frameworks and how they parse and handle querystrings. Changing `req.query` in express really just changes some arbitrary parsed object express is handling for you. By the time the req reaches the provider and `koa` it's going to use it's [own parsing](https://github.com/koajs/koa/blob/2.5.2/lib/request.js#L196-L199) of the original request object's req.
