### ISSUE TITLE
I want to modify the error body JSON

### ISSUE THREAD

**Issue by acodercat** [panva/node-oidc-provider#332]
**Is your feature request related to a problem? Please describe.**
I want to modify the error body JSON

**Comment by panva** [comment]
Docs. https://github.com/panva/node-oidc-provider/blob/master/docs/configuration.md#pre--and-post-middlewares

**Comment by acodercat** [comment]
```js
  oidcProvider.use(async (ctx, next) => {
    await next();
    console.log('middleware post', ctx.method, ctx.oidc.route);
  });
```
Cannot read property 'route' of undefined

**Comment by acodercat** [comment]
sorry  i find it ,but i canot get error, i want in the middleware  modify the error body JSON

**Comment by acodercat** [comment]
please!!!!!!

**Comment by panva** [comment]
ctx.request, ctx.response, ctx.body, ctx.status => https://koajs.com

You’ve got the answer.

**Comment by panva** [comment]
If you can’t get the hint and use the tools already available that can do what you want then i can’t help you any further.

**Comment by panva** [comment]
For those passing by.

```js
provider.use(async (ctx, next) => {
  await next();
  // use anything from context to target the response to check it's an error
  if (ctx.body && ctx.body.error) {
    // ctx.body.error_description = '...';
    // ctx.body.error_uri = '...';
  }
});
```
