### ISSUE TITLE
Use case of grant ids

### ISSUE THREAD

**Issue by P4sca1** [panva/node-oidc-provider#334]
I'm trying to understand what's the use case of grant ids. I read that tokens with the same grant id belong together, so does an access token, a refresh token and an id token generated with the same /token call have the same grant id? Also, in how far is it necessary for security? Are there any official resources about the use of grant ids?

**Comment by P4sca1** [comment]
Alright, that makes ist clear. Thank you!

**Comment by amaciver** [comment]
Curious if there is a reason that the adapter examples don't set an expiration on `grant` keys. Redis is keeping a lot of old grants around.

Do you see a downside to doing something like 
```
if (payload.grantId) {
      const grantKey = grantKeyFor(payload.grantId);
      multi.rpush(grantKey, key);
      multi.expire(grantKey, << VALUE >= Longest token expiration set in OP config >> );
    }
```
?

**Comment by panva** [comment]
> << VALUE >= Longest token expiration set in OP config >>

Its this part that i dont like. Redis isnt one i use so maybe you can suggest a different but still efficient structure.

**Comment by amaciver** [comment]
perhaps: 
```

      if (payload.grantId) {
        const grantKey = grantKeyFor(payload.grantId);
        multi.rpush(grantKey, key);
        await redisClient.ttl(grantKey, (ttl) => {
          if (expiresIn > ttl) {
            multi.expire(grantKey, expiresIn + 10)
          }
        });
      }
```

is there an edge case where the grant record still needs to exist past the expiry of any token?

**Comment by panva** [comment]
Not fond of the extra command needed tbh.

**Comment by panva** [comment]
@amaciver -> 28abbde
