### ISSUE TITLE
Client name limitation using the MongoDB Adapter

### ISSUE THREAD

**Issue by bzuillsmith** [panva/node-oidc-provider#336]
I am building a full example of connecting a native app to a node js server running this library with the MongoDB adapter. I noticed that if the client name has a `.` then a server_error occurs while upserting the authorization code.

`{ _id: 'be4238b5-a6a6-4069-8178-8b944366a6a1',
  expiresAt: 2019-07-31T05:56:57.855Z,
  account: '00000000-a2ad-41a9-a4cf-93a8b7e13d5a',
  loginTs: 1532995017,
  authorizations: { 'my.app': { sid: 'cb446e83-8f72-45a5-a70e-cd55dd4b5d9e'}`

Notice the 'my.app' key. Keys with a period are invalid in MongoDB due to `.` being used to access nested properties. Any workaround I can think of is a bit ugly. I'm not sure you would consider it a bug since it's specific to the MongoAdapter example but I thought it's worth mentioning and maybe worth a Note somewhere in the documentation or adapter code.

**Comment by panva** [comment]
A nice catch but not really a bug, it's an example - not a 100% bullet-proof codebase that i'm pointing anyone to use. If you wish please submit a PR with a comment code in it that suggests workarounds.
