### ISSUE TITLE
how to create registration page

### ISSUE THREAD

**Issue by stephen1706** [panva/node-oidc-provider#337]
i'm following the sample step by step successfully, now i want to add a custom web page for sign-up. 

I added this code : 
```
app.get('/interaction/:grant/register', parse, (req, res, next) => {
          //do sign up here
})
```

registration button :
```
<a href="/interaction/88241140-680c-43f8-a428-e0f5c7a65d05/register?client_id=test_code" class="login login-submit">Register new user</a>
```
is it allow to add custom page in the oidc provider such as sign up, forget password page?

**Comment by panva** [comment]
> is it allow to add custom page in the oidc provider such as sign up, forget password page?

oidc-provider does not care in what form you finish interactions, with a reg or a login, with or without mfa - don't care.  
Don't forget basic principles in developing your interactions tho - csrf prot, conditional captchas and brute force protection - that's all up to you.

**Comment by panva** [comment]
Use the interactionUrl helper and cookies short configuration to direct the interactions to this service and load/save data and redirect back in a similar manner the interactionDetails and interactionFinished provider instance methods do.

**Comment by stephen1706** [comment]
@panva when i redirect back from website after user input credentials, it need to call the interactionDetails to get the client id, etc, seems it need to looks for the cookies. do i need to pass all the cookies to the login website? or is there any other way to authenticate the session other than using cookies?

**Comment by panva** [comment]
The cookie and the url can be used to cross-check-validate the user-agent and based on that load the details from your adapter. In a similar matter then save before redirecting back to the provider. The functions don’t do anything else special.

**Comment by stephen1706** [comment]
@panva so after i press submit in my reactjs website, it will call an api (/interaction/:grant/login) in the provider that will trigger interactionFinished, but since i call the api using fetch library, it cannot open the web redirect in my external website, it will just redirect in the background and i cannot fetch the code. is there an particular way i should call the interactionFinished from external website so that it can intercept the whole redirect flow? so my external website can get the authorization code in the query string

```
app.post('/interaction/:grant/login', parse, (req, res, next) => {
                handler.login(req.body)
                    .then(account => 
                            oidc.interactionFinished(req, res, {
                                login: {
                                    account: account.accountId,
                                    acr: '1',
                                    remember: !!req.body.remember,
                                    ts: Math.floor(Date.now() / 1000),
                                },
                                consent: {
                                // TODO: remove offline_access from scopes if remember is not checked
                                }
                            })
                        ).catch(e => {
                            if(e instanceof ResponseModel){
                                res.status(e.statusCode).send(e.data());
                            } else {
                                next();
                            }
                        });
        })
       ```

**Comment by panva** [comment]
Finish your interactions (call interaction finished or just manually set the results on the interaction details object) and then in whatever manner you have available redirect back to the resume endpoint. Just calling interactionFinished is not going to give you the code, you must redirect the user-agent to resume. No other means of finishing the authorization request is supported.

**Comment by stephen1706** [comment]
@panva for the authorization endpoint, my base url is not a plain example.com/auth instead it is example.com/something/auth because the use of load balancer. when i open the page, it does not redirect to example.com/something/interaction/:grant, but instead it redirect to example.com/interaction/:grant. how to change this behaviour?

**Comment by panva** [comment]
It is literally mentioned in the docs section linked above.

**Comment by panva** [comment]
See #351 from @JSantha to set the interaction results and have it return the url.
