### ISSUE TITLE
Scope can be changed after user logged in.

### ISSUE THREAD

**Issue by sihunqu123** [panva/node-oidc-provider#339]
This is my scenery

**prerequisite**:
grant_type: code.
OIDC defined scope: A B C D.
registered RP: clientA.
user(the browser): userA.

**steps to reproduce this bug**:
1. userA click login link on clientA.
2. clientA redirect userA to OIDC server's authorization with requested scope 'A B', which result to a login page.
3. userA logged in and consent for scope 'A B'.
4. OICD redirect userA to clientA with authcode(which would have scope 'A B' if exchange it with accessToken).
**Important**
5. clientA redirect userA to OIDC server again with extended scope 'A B **C D**'.
6. As a result, OIDC redirect userA to clientA with a new authcode(which would have scope 'AB **C D**' if exchange it with accessToken) directly, without any prompt asking for user consent, just because user if already logged in.

Summary:
the clientA can redirect userA to OIDC server's authorizationUrl  again right after userA logged in with modified/extended scope without user's consent/notification, which is an security issue.
In this case, scope-control doesn't works at all. Once user logged in on OIDC, clientA can have any scope if only it's defined in OIDC.

Expected Behavior:
After userA logged in, OIDC should show consent page in authorization author if clientA's requested scope are extended.

**Comment by panva** [comment]
See #311

I didn’t want this cookie or session based. I’d rather have you track accepted scopes backend wise and use the interactionCheck helper function to request consent if scopes change. Seeing this re-occur tho I agree with the point that some default way of this should be baked in. Probably session based. 

I’d also like to point out that thinking of just scopes is invalid. Claims need to be at the core of this feature, scopes only complement this.

**Comment by panva** [comment]
I’ll be tracking this in #340. Please subscribe to that one for updates.
