### ISSUE TITLE
Error when using signed cookies with mounted oidc-provider

### ISSUE THREAD

**Issue by P4sca1** [panva/node-oidc-provider#341]
When mounting oidc-provider to a koa (express is most likely also affected, not tested) application, it has problems with signed cookies. I was able to fix the issues by doing this in my koa application:

```js
const instance = require('oidc-provider/lib/helpers/weak_cache')

app.keys = instance(oidc).configuration('cookies.keys')
```

Is this intended? If so, we should add it to the documentation.

**Comment by panva** [comment]
> Is this intended?

Yes, but if you're working with koa you know to set the keys on your instance, and then set the same ones on the provider too.
