### ISSUE TITLE
Refresh Token not returned in Authorization Grant Flow.

### ISSUE THREAD

**Issue by codestorycooked** [panva/node-oidc-provider#342]
Hi, 
I am not able to get refresh_token back in authorization grant flow. 

I registered client with following parameters:

```
{
  "client_name": "Web Client",
    "redirect_uris":[
    	"http://localhost:8889/auth/provider/callback"
    	],
  "application_type":"web",
  "grant_types": [
  	        "authorization_code",
  	        "refresh_token"
    ]
}
```

Made a request with:

```
http://localhost:4010/auth?redirect_uri=http://localhost:8889/auth/provider/callback&scope=openid profile offline_access &response_type=code&client_id=xxxx
```

I have provided `offline_access` but server does not returns refresh_token.
More Info:
`alwaysIssueRefreshToken` is set to default value.
library version: 2.5.0

**Comment by panva** [comment]
Try with a properly encoded authorization request.

```
http://localhost:4010/auth?scope=openid%20profile%20offline_access&response_type=code&client_id=xxxx&redirect_uri=http%3A%2F%2Flocalhost%3A8889%2Fauth%2Fprovider%2Fcallback
```

**Comment by codestorycooked** [comment]
I have decoded string for readability in this issue. Yes, I have enabled offline_scope and can see that on wellknown endpoint.

**Comment by panva** [comment]
This is a well-tested core feature. I'm 100% sure something's wrong with your setup or in where you expect the refresh_token to be returned.

1) goto https://tranquil-reef-95185.herokuapp.com
2) select `with_refresh` client setup
3) login
4) refresh token is returned from the token endpoint

**Comment by panva** [comment]
Ah yeah, that's it - you're missing `prompt=consent`.
