### ISSUE TITLE
Specify a set of cookies that will be sent with every redirect.

### ISSUE THREAD

**Issue by amaciver** [panva/node-oidc-provider#343]
**Is your feature request related to a problem? Please describe.**
I would like to send a custom set of cookies to the InteractionURL, beyond those defined in cookies.names. These cookies would be part of the original request, or set on the proxy level, and I would like them to be sent to the IdP. We are setting up a canary cluster and would like traffic to be faithfully routed across an entire flow based on cookie.  

Currently I can only see `_session`, `grant` etc. being returned from the Provider, as specified in `lib/helpers/defaults.js`

Please let me know if I am missing something!

**Describe the solution you'd like**
`cookies.names` could contain a key `custom_cookies` which holds an array, and and these could be attached to every redirect by iterating over the array and leveraging `ctx.cookies.get`

**Describe alternatives you've considered**

**Additional context**

 - [x] i have searched the configuration section for this feature and couldn't find it
 - [x] i have searched the issues tracker on github for similar requests and couldn't find anything related.

**Comment by panva** [comment]
How about a custom middleware to set your cookies whenever you want? https://github.com/panva/node-oidc-provider/blob/v4.5.0/docs/configuration.md#pre--and-post-middlewares

**Comment by amaciver** [comment]
Thanks for this suggestion. I will go that route.
