### ISSUE TITLE
public key for jwt access token and id token

### ISSUE THREAD

**Issue by stephen1706** [panva/node-oidc-provider#344]
how do i get the public key for my other service to verify the signature of the generated access token and id token? i generate the keystore.json using your step by step tutorial. not quite sure which one is the private and public key since the field name is only 1 character like e,n,d,etc

**Comment by panva** [comment]
Fetch them from the provider's `jwks_uri`.

Please refrain from asking generic "how do i OIDC" in the future, contrary to popular belief this is not an oidc support tracker but an issue tracker for oidc-provider. Thank you.
