### ISSUE TITLE
Question: Auth0 rules

### ISSUE THREAD

**Issue by lomboboo** [panva/node-oidc-provider#345]
First of all, thank you for all the work you've done here. This is a great project.

I'd like to ask a question related to [auth0 rules feature](https://auth0.com/docs/rules/current). 
As far as I understand there is no such a thing as *rules* in the OIDC specification. Is there any way I can imitate this feature using node-oidc-provider?

**Comment by panva** [comment]
`interactionCheck` configuration option, `meta` returned in the interaction results object and the fact that interactions are completely standalone should do it.

**Comment by lomboboo** [comment]
@panva thank you for your quick response. Indeed `interactionCheck` looks to do the job.
