### ISSUE TITLE
Custom JWT payload

### ISSUE THREAD

**Issue by SamMcKay** [panva/node-oidc-provider#346]
Hi @panva 

Great work on this library. It is fantastic and constantly getting better.

Can you suggest an appropriate method to customize the payload of a jwt access token?

I would like to embed a users roles within the token itself.

Thanks

**Comment by panva** [comment]
> Can you suggest an appropriate method to customize the payload of a jwt access token?

I think working with the public BaseToken API is your best shot. 

https://github.com/panva/node-oidc-provider/blob/v4.5.0/lib/models/base_token.js#L130
