### ISSUE TITLE
Implementing two factor authentication

### ISSUE THREAD

**Issue by vikas-ss** [panva/node-oidc-provider#347]
Hi,

I would like to know, currently is there a provision to implement (or already implemented in-built) two (or multi) factor authentication using email or google authenticator in this provider. 

Kindly guide me any links or tutorials if it is already there or how should I achieve it with current setup.

**Comment by panva** [comment]
No end-user authentication interactions are bundled in this library. This is a protocol implementation and whenever end-user interaction is needed the request is offloaded to your own flows that you implement.

That being said, MFA can be a part of your signin process you just have to implement all of the auth yourself.

**Comment by panva** [comment]
https://github.com/panva/node-oidc-provider/blob/v4.5.0/docs/configuration.md#interaction
