### ISSUE TITLE
client_secret Authorization header

### ISSUE THREAD

**Issue by ToniIltanen** [panva/node-oidc-provider#35]
I'm using oidc-provider with passport-oauth2, and im getting an error on the callback: client_secret must be provided in the Authorization header. Is there a way to assign this to the headers when returning to callback?

**Comment by panva** [comment]
OIDC defines four client token endpoint auth methods. All of them supported by this library. But you must configure your client with the one it is intending to be used with, defaulting to (as per OIDC) client_secret_basic. Once a client is configured with a method this method must be used.

I will go ahead and assume your library by default sends the client_id and secret via POST body, hence you should configure your client with `{ token_endpoint_auth_method: 'client_secret_post' }`.

List of client authentication methods
- client_secret_basic
- client_secret_post
- client_secret_jwt
- private_key_jwt

**Comment by ToniIltanen** [comment]
How do you add it with a passport strategy? the only available parameters are: clientID,clientSecret,callbackURL,authorizationURL,tokenURL and scope.

Has anyone tried oidc-provider with a passport-oauth2? I can get to the actual login, but the header issue is shown as a error (TokenError: client_secret must be provided in the Authorization header) in the cb (it does go to the right URL after login, though). So am i missing a parameter from the auth url? as in http://localhost:3000/op/auth?token_endpoint_auth_method=client_secret_post.... <- I tried that

**Comment by panva** [comment]
In essence the client you have "registered" on the provider expects to use the default 'client_secret_basic' scheme, where in fact your oauth library uses 'client_secret_post', you have to either tell your client lib to use basic scheme, or tell your provider to expect the post one for this client.

The latter option goes like this:
As I wrote earlier, you're missing a client configuration property on your provider instance side.

i.e. 
```js
const { Provider } = require('oidc-provider');
const instance = new Provider('http://localhost:3000/op');
const clients = [
  {
    // your client metadata is probably here, add the following one
    token_endpoint_auth_method: 'client_secret_post' ,
  },
];
instance.initialize({ clients }).then(() => {
  // ...
});
```

**Comment by ToniIltanen** [comment]
Ahh, finally i got it. My client  was by default sending type None, but still posting the values.
