### ISSUE TITLE
interactionFinished custom response handling

### ISSUE THREAD

**Issue by JSantha** [panva/node-oidc-provider#350]
I would like to implement login interaction in AJAX way and handle redirection on client side. This is not easy to achieve since `provider.interactionFinished` has standard 302 redirect hardcoded.

```js
async interactionFinished(req, res, result) {
    const interaction = await getInteraction.call(this, req, res);
    interaction.result = result;
    await interaction.save(interaction.exp - epochTime());

    res.statusCode = 302; // eslint-disable-line no-param-reassign
    res.setHeader('Location', interaction.returnTo);
    res.setHeader('Content-Length', '0');
    res.end();
}
```
 
It's off course possible to monkey-patch response to achieve AJAX behaviour but it's not obviously a proper solution:

```js
const origEnd = res.end;
res.end = function (this: Response): Response {
    res.end = origEnd;
    const location = this.getHeader('Location');
    this.removeHeader('Location');
    this.removeHeader('Content-Length');
    this.statusCode = 200;

    return res.send({ location });
};
```

Does OIDC allow custom response handling on interaction finished? Or delegating redirection responsibility to client side can imply new security issues?

**Comment by panva** [comment]
This has nothing to do with OIDC, it's internal handling. The function is merely storing what you pass in the interaction object's results and then redirects to the returnTo path. You can easily read what the function does and not use it at all, do it on your own. The only important thing is that after your ajax call finishes you redirect to that location.

**Comment by JSantha** [comment]
Thank you, I thought about this but got afraid of properly setting expiration on save since I need to "reimplement" calculation of expiration `interaction.exp - epochTime()` in my application code.

Maybe it would be great to extract following lines to independent method:

```js
const interaction = await getInteraction.call(this, req, res);
interaction.result = result;
await interaction.save(interaction.exp - epochTime());
```
So I can reuse this logic but handle response by myself. What do you think?

**Comment by panva** [comment]
Sure.

**Comment by JSantha** [comment]
Created PR #351.
