### ISSUE TITLE
Add metadata to setProviderSession

### ISSUE THREAD

**Issue by skeltonm** [panva/node-oidc-provider#352]
**Is your feature request related to a problem? Please describe.**
I am implementing a password complexity check system during the login process, and I would like to add some metadata to `setProviderSession` that I can retrieve later when updating the user's password.

**Describe the solution you'd like**
Would it be possible to add a `meta` key to the object passed to `setProviderSession` that can store metadata?  Or would there be a better approach to doing what I am attempting to do?

 - [x] i have searched the configuration section for this feature and couldn't find it
 - [x] i have searched the issues tracker on github for similar requests and couldn't find anything related.

**Comment by panva** [comment]
Sure, so long as the meta is scoped under a client. So that the result is inline with what `interactionResult` meta does.

Can you work out the PR for adding this and tests for it?

**Comment by skeltonm** [comment]
Sure, I'll work on that.

**Comment by panva** [comment]
i'm thinking something like this should be the signature

```js
async setProviderSession(req, res, {
  account, // account id string
  ts = epochTime(), // [optional] login timestamp, defaults to current timestamp
  remember = true, // [optional] set the session as persistent, defaults to true
  clients = [], // [optional] array of client id strings to pre-authorize in the updated session
  meta: { // [optional] object with keys being client_ids present in clients with their respective meta
    [client_id]: {},
  }
} = {})
```
