### ISSUE TITLE
Redis adapter not retrieving Sessions

### ISSUE THREAD

**Issue by elendirx** [panva/node-oidc-provider#354]
With the latest version of oidc provider and the latest version of example redis adapter I'm getting
```
message: 'WRONGTYPE Operation against a key holding the wrong kind of value',
  command: 
   { name: 'hget',
     args: 
      [ 'oidc:Session:9cb8737b-12a8-409b-9b19-81f97b8fe357',
        'grantId' ] } }
```
during the auth code flow. I believe the correct command should be `hgetall`. I fixed it by adding 'Session' to the [grantable set](https://github.com/panva/node-oidc-provider/blob/4085e3fa3d0cf4b875fe19bd780cd750c5b07c36/example/adapters/redis.js#L8).

Should I submit a PR?

**Comment by panva** [comment]
That’s defo the wrong fix. I’ll look into it. Thanks!

**Comment by elendirx** [comment]
I must admit I didn't really understand the problem. Thanks for the quick fix, I confirm it works now!

**Comment by panva** [comment]
one more refactor 438c42a, should bundle all grantable deletes into one redis command

**Comment by elendirx** [comment]
Tested it and it works, thanks again!
