### ISSUE TITLE
RFC Compliance Question: Client Scopes

### ISSUE THREAD

**Issue by jsmylnycky** [panva/node-oidc-provider#356]
Hello!

I have a question and hoping to leverage your expertise of the RFC.

For my company, we're looking to build a Client Credentials-only workflow, with a UI built to manage clients and what scopes they're allowed to utilize, and a REST interface into OIDC to handle these clientss.

One thing we're considering is how do we handle if the clients may need new scopes created for them that OIDC isn't aware of yet.  It could be burdensome to have to push out an update to OIDCs config every time we need to add new scopes to the provider.

The idea came by where we could create a custom grant-type that instead of relying on the Provider to say if scopes are valid, instead rely on the scopes being stored on each client, and leverage that to perform the intersection when generating a token.

Would it be RFC-compliant to not force the Provider itself to be aware of the scopes, and instead manage this list in our grant-type for each client individually?

How do you think this falls into the RFC? I've done some digging and I'm having a hard time finding a definitive answer.

Thanks!

**Comment by panva** [comment]
Hi @jsmylnycky,

My apologies if I come out blunt.

If there’s a particular oidc-provider related question about “how-to” that’s not clear from the docs I’m happy to help. But this is not the forum to ask architectural questions.

May I suggest stackoverflow or similar.
