### ISSUE TITLE
Question: Native apps custom URI schema

### ISSUE THREAD

**Issue by lomboboo** [panva/node-oidc-provider#357]
So I have a question about `redirect_uris` for native mobile app. 
```
redirect_uris: [
  'appname://somecallback',
]
```
This configuration does not work due to this condition inside `client_schema.js` 
```
if (!protocol.includes('.')) {
  invalidate('redirect_uris for native clients using Custom URI scheme should use reverse domain name based scheme');
}
```

I couldn't find this type of limitation in the OIDC specification. Could you please clear this for me? And how should `redirect_uri` looks like when configuring native client app?

**Comment by panva** [comment]
This comes from https://tools.ietf.org/html/rfc8252 which is enabled by default. (`features.oauthNativeApps`).

**Comment by lomboboo** [comment]
Thanks for quick response. You mean last paragraph of 7.1 section, right? So it basically done to remain scheme unique? In this case valid uri is `appname.domain.com://somecallback`?

**Comment by panva** [comment]
It will pass the validation, but as per the RFC a reverse domain name notation should be used instead `com.domain.appname.://somecallback`.
