### ISSUE TITLE
mounted provider with devInteractions this.render is not a function error

### ISSUE THREAD

**Issue by SimonDegraeve** [panva/node-oidc-provider#36]
When running the `next` branch I get this error:
```
ctx.render is not a function
    at interactionRender (oidc-provider/lib/actions/interaction.js:47:19)
```
There is a [workaround](https://github.com/koajs/ejs#wokraround-for-koa-2):
```js
import co from 'co';
import render from 'koa-ejs';

render(app, options);
app.context.render = co.wrap(app.context.render);

app.use(async (ctx, next) => {
    await ctx.render(view, locals);
});
```

**Comment by SimonDegraeve** [comment]
Actually, I found that you used the recommanded snippet in `initialize_app.js`. Don't know where it comes from then.

**Comment by panva** [comment]
Same on master,

1) sidenote: server_error is not being emitted from dev interactions, easy fix will land on master
2) i am only able to replicate the error on the `devInteractions` when the provider.app is mounted

Reason for 2) is that the ctx is actually the one from your Koa instance and not the one provider's one. Workarounds
- deploy your own working interactions (see example) and turn off devInteractions
- don't mount the provider until you do

I guess i will look for an alternative to koa-ejs that does not bound to ctx or attempt to use it that way.

**Comment by SimonDegraeve** [comment]
Thank you.
