### ISSUE TITLE
Question: Preferred way to limit registration for specific clients.

### ISSUE THREAD

**Issue by lomboboo** [panva/node-oidc-provider#362]
My question is pretty much in the title. I'd like to know is there a preferred way to limit registration for specified client? At the moment I have this config for registration 
```
    registration: { initialAccessToken: 'someString' },
    registrationManagement: true,
```
I noticed in the [docs](https://github.com/panva/node-oidc-provider/blob/master/docs/configuration.md#featuresregistration) that there are couple of choices for `registration`, but don't really understand how can disable registration for specific client?

**Comment by panva** [comment]
Hi, I don't follow the question.

**Comment by lomboboo** [comment]
@panva is there a way to disable registration based on client's configuration? By `client_id` for example

**Comment by panva** [comment]
registration is to create clients, how would you disable registration by clientid when the point of the registration to obtain one?

**Comment by lomboboo** [comment]
Oh, I misunderstood the purpose of `registration`. I'm closing this one.
