### ISSUE TITLE
Pending error handler prevents error propagation

### ISSUE THREAD

**Issue by SokratisVidros** [panva/node-oidc-provider#363]
**Describe the bug**
Errors thrown in OIDC flows are caught by the following pending error handler https://github.com/panva/node-oidc-provider/blob/master/lib/helpers/initialize_app.js#L47

**Expected behaviour**
Errors thrown in OIDC callbacks such as "renderError" should propagate to parent error handling middlewares.

**Environment:**
 - oidc-provider version: [e.g. v4.4.0]
 - node version: [e.g. v8.11.4]

**Additional context**

 - [X] the bug is happening on latest oidc-provider too.
 - [ ] i have tried DEBUG (see readme.md) and can see the issue is with the provider and not my code.
 - [X] i have searched the issues tracker on github for similar issues and couldn't find anything related.

@panva I'd be happy to open a PR about it however I'd like to understand the reasoning of that try/catch block. Since there are already two other error handlers in place, my suggestion would be to remove it. 

Thanks in advance.

**Comment by panva** [comment]
Are you throwing from `renderError` on purpose or did this cause you pain while debugging a problem with your `renderError`?

The reason of this block is that during device flow error handling there are session changes that need to be saved but the session handling middleware is finished by then. Since I can't use something elegant like `on-headers` in koa easily i need another middleware like this.

The TODO in that block however suggests i need to take a look at this.

**Comment by SokratisVidros** [comment]
@panva thanks for the quick reply.

In renderError I throw the error explicitly in order to handle it in my global koa error handling middleware.

Same applies to the following snippet in my app regarding OIDC server events. Events are transformed to errors and they are expected to bubble up.

```js
...
[
  'server_error',
  'authorization.error',
  'grant.error',
  'certificates.error',
  'discovery.error',
  'introspection.error',
  'revocation.error',
  'userinfo.error',
  'check_session.error',
  'end_session.error',
  'webfinger.error',
  'backchannel.error'
].forEach(eventName => {
  provider.on(eventName, (out, ctx) => {
    if (ctx.response.status >= 400) {
      const err = new Error(out.error_description || out.error);
      throw Boom.boomify(err, { statusCode: ctx.response.status });
    }
  }); 
});
...
```

Previously we were using node-oidc-server v3.x.x. Since we upgraded to v4.x.x the error handler practically stopped receiving all the node-oidc-server errors.

**Comment by panva** [comment]
Unintended use of renderError, but still interesting. I’m travelling atm so unless I get some “me” time earliest expected change will be sunday

**Comment by SokratisVidros** [comment]
I see, renderError is mainly used to output the error HTML. However, when oidc is part of another koa app, error handling & rendering can be factored out in one place.

Is there anything I can do to help?

**Comment by SokratisVidros** [comment]
Ok, then we will patch that code on our end temporarily and we will wait for a fix.

Thanks in advance.

**Comment by panva** [comment]
how's this 7a6c439?

**Comment by SokratisVidros** [comment]
Looks good at first sight. I will try it out in more detail. Thanks @panva!

**Comment by SokratisVidros** [comment]
Thanks @panva
