### ISSUE TITLE
Overriding response mode with registerResponseMode

### ISSUE THREAD

**Issue by lomboboo** [panva/node-oidc-provider#365]
I have this setup:
```
  const oidc = new Provider(ISSUER_URL, config)
  oidc.registerResponseMode('fragment', customCB)
  oidc
    .initialize({
...
```
and I'd like to override `fragment` response mode, but instead of overriding `fragment` it **adds new one**. So basically I end up with 2 `fragment` response modes. What did I do wrong?

**Comment by panva** [comment]
Its an internal undocumented method intended to register a mode, not overload one.

**Comment by lomboboo** [comment]
thanks you for the response. There is nothing I can do to customize `fragment` response mode? Do you plan to add a support for it in the future?

**Comment by panva** [comment]
The code allows that tho. Where do you get the two modes?

**Comment by panva** [comment]
What modification are you making? As is the modes are conform. No need for anything extra as far as i can see.

**Comment by lomboboo** [comment]
At the moment `fragment` returns `access_token, expires_in, id_token, session_state, state, token_type`. 
I would like it to return also `scope`

**Comment by panva** [comment]
Again, Where do you get the two modes?

**Comment by lomboboo** [comment]
`provider.js`:
```
  registerResponseMode(name, handler) {
    instance(this).responseModes.set(name, handler);
    // console.log(instance(this).responseModes.get(name));
  }
```

**Comment by panva** [comment]
Yeah but why would there be two with the same name? It’s a Map. Please show me where you get two registered fragments and what your handler even is.

**Comment by lomboboo** [comment]
```
  oidc.registerResponseMode('fragment', (ctx, redirectUri, payload) => {
    const uri = formatUri(redirectUri, payload, 'fragment')
    console.log('payload', payload)
    ctx.redirect(uri)
  })
```

and console.log inside `registerResponseMode  (provider.js)` gives:
![download](https://user-images.githubusercontent.com/12416377/45484876-f37da100-b755-11e8-94cc-8d632a4a61d3.png)

**Comment by panva** [comment]
Then call it after initialize and you’re set.

**Comment by lomboboo** [comment]
thanks for the help, I'll keep it in mind

**Comment by panva** [comment]
7f7ea79 fixes default implementations of the defined response modes overwriting custom implementations

**Comment by lomboboo** [comment]
great! Would you consider to add some description into the docs?
