### ISSUE TITLE
Tokens's TTLs customization not working except for AccessToken

### ISSUE THREAD

**Issue by kenjinsama** [panva/node-oidc-provider#366]
**Describe the bug**
When I try to customize tokens's TTLs (except for AccessToken), the value that is passed to the adapter is the default value.

**To Reproduce**
Provider and Client configuration: (inline or gist)
```js
// provider configuration
const provider = new Provider(`https://${Issuer.domain}/api/v1/oidc/provider`, {
    formats: {
        default: 'opaque'
    },
    claims: {
        address: ['address'],
        family_name: ['family_name'],
        given_name: ['given_name'],
        preferred_username: ['preferred_username'],
        gender: ['gender'],
        birthdate: ['birthdate'],
        profile: ['family_name', 'gender', 'given_name', 'preferred_username', 'birthdate'],
    },
    features : {
        devInteractions: false,
    },
    grant_types_supported: ['authorization_code'],
    response_types: ['id_token'],
    ttl: {
        AccessToken: 5,//3600,
        AuthorizationCode: 5,//600,
        ClientCredentials: 5,//600,
        DeviceCode: 5,//600,
        IdToken: 5,//3600,
        RefreshToken: 5,//1209600,
    },
});

// client(s) configuration
await provider.initialize({
    clients: [{
        "client_id" : "*********************",
        "client_secret" : "************************",
        "redirect_uris" : [
            "https://*******/*******"
        ],
        grant_types: ['authorization_code'],
        response_types: ['code'],
        token_endpoint_auth_method: 'client_secret_post',
        id_token_signed_response_alg: 'HS256',
    }],
    adapter: RedisAdapter, // the default redis adapter
});

```

Steps to reproduce the behaviour:

1.  Configure the ttl to 5 seconds for each token (RefreshToken is the most visible since his default ttl is high)
2.  Add logs into your adapter to see the "expireIn" you receive in upsert function

**Expected behaviour**

The "expireIn" logged must be the configured TTL

**Environment:**

 - oidc-provider version: 4.8.1
 - node version: 8.11.4

**Additional context**

 - [x] the bug is happening on latest oidc-provider too.
 - [x] i have searched the issues tracker on github for similar issues and couldn't find anything related.

**Logs**

Log format: "<%= name %> EXPIRE <% id %> --------------> >%= expireIn %>"

logs :
Session EXPIRE 84e01bd5-cc19-4b06-8ef3-8536b33c63c6 --------------------------------> 600
Session EXPIRE 5d95f9aa-99eb-444c-8978-1bb263939369 --------------------------------> 1209600
Session EXPIRE 84e01bd5-cc19-4b06-8ef3-8536b33c63c6 --------------------------------> 542
Session EXPIRE 5d95f9aa-99eb-444c-8978-1bb263939369 --------------------------------> 1209600
AccessToken EXPIRE sQlTy_TO8c43i0nRtU21BUglAucR6hzIvnW6D50~DXk -------------------------------> 5

**Comment by panva** [comment]
The logs you show display only access token which is correct. Can you show a code, refresh token too?

**Comment by panva** [comment]
Hi @kenjinsama, i'm unable to confirm this, when i set the ttl for any kind of token that value is used and propagated to the adapter's upsert expiresIn argument. I'm closing this as there's no clear problem on my end when i try or in your provided logs. Feel free to reply with more details if necessary.

**Comment by kenjinsama** [comment]
I maybe don't understand but what is this ?
Session EXPIRE 5d95f9aa-99eb-444c-8978-1bb263939369 --------------------------------> 1209600
It seems to match the default TTL for the refresh token. I'll try to provide more information.

**Comment by panva** [comment]
That would be a Session, d’oh, stored on the backend, referenced in the browser by a pushed cookie. It’s ttl is controlled by the cookie’s maxage.

**Comment by kenjinsama** [comment]
But I do not have the sessionManagement active, then it would be the session for interaction ?

**Comment by panva** [comment]
No. Regular OP session. Still needed regardless of sessionManagement

**Comment by kenjinsama** [comment]
If I understand I can ajust time management by using "long" and "short" cookies parameters ?

**Comment by kenjinsama** [comment]
I have some TTL that does not expire :

**Comment by panva** [comment]
Yup. The redis adapter structure isn’t perfect and doesn’t expire these. In your adapter instance feel free to set an appropriate ttl yourself.

**Comment by kenjinsama** [comment]
Thanks for your explanations, I will try to digest that :+1:.

**Comment by panva** [comment]
Long cookies for op session. Short cookies for interaction. As documented

**Comment by kenjinsama** [comment]
Yup, saw that, thanks :+1:.

**Comment by panva** [comment]
28abbde updates the redis example adapter with grant list expiration
