### ISSUE TITLE
No key found error with introspection_endpoint_auth_method configuration set to client_secret_jwt

### ISSUE THREAD

**Issue by andreasenberg** [panva/node-oidc-provider#367]
Hi!

I've been trying to configure the node-oidc-provider to use `client_secret_jwt` as the auth method when invoking the token introspection endpoint but I'm unable to get that working. 
All I'm getting is an "no key found" error which seems to be thrown by the underlying node-jose lib. 

I thought at first that it was missing in my keystore but my understanding is that node-oidc-provider itself adds a key in the client.keystore based on the client secret provided in the client configuration? 

The token itself is passed as the `client_assertion` parameter when invoking the introspection endpoint as per: https://openid.net/specs/openid-connect-core-1_0.html#ClientAuthentication. The `client_id` and `client_assertion_type` parameters are passed as well. It looks like it is able to find the params so that should not be the issue here. 
The client itself is configured with a `client_secret` and `introspection_endpoint_auth_method: 'client_secret_jwt'`

Here is the relevant part of the error message I'm getting in the debug logs from node-oidc-provider:
`error={ error: 'invalid_client', error_description: 'client authentication failed' } detail=no key found`

While debugging this it seems to me that: 
a) node-jose is dependent on the client providing the kid in the jwt header. This means that the oidc clients will have to derive this from the secret as well I guess or how are they intended to get hold of that?
b) node-jose (JWSVerifier, verify.js) not able to locate the key when doing a keystore.get(..) call using the kid from the header.
c) printing the keys using keystore.toJSON(..) returns the expected/generated keyset passed from node-oidc-provider.

I've been trying to find some documentation on how to get this up and running. Does such a documentation exist somewhere that I've failed to find? 
In the end I would like use this auth_method for the revocation and token endpoints as well. 

Any help would be appreciated!

Thanks!

**Comment by panva** [comment]
I'm guessing your secret is not of sufficient length. Same as in [#310](https://github.com/panva/node-oidc-provider/issues/310#issuecomment-404195329). I'm also guessing your client doesn't have a `introspection_endpoint_auth_signing_alg` because otherwise the provider validates the secret has sufficient length to form a signature.

I'm going to introduce a breaking change in 5.x that will validate the length when `_endpoint_auth_signing_alg` is missing to help aid in this problem.

For now, try to set `introspection_endpoint_auth_signing_alg` to `HS256` and you will probably get an `insufficient client_secret length` error. Please confirm and close or provide more details, like the actual `secret` you're using.

**Comment by panva** [comment]
> node-jose is dependent on the client providing the kid in the jwt header. This means that the oidc clients will have to derive this from the secret as well I guess or how are they intended to get hold of that?

it's not, and you should not provide a `kid` for client_secret based symmetrical jwts in OIDC

**Comment by andreasenberg** [comment]
Yes, it appears that the client secret I was using while testing was not of sufficient length. I did not have the `introspection_endpoint_auth_signing_alg` configuration on the client I was using.
Adding that configuration gave me the error message you pointed out and changing the secret length resolved the issue.

Thank you for your help in clarifying this!
