### ISSUE TITLE
example/support/account.js question

### ISSUE THREAD

**Issue by GitStorageOne** [panva/node-oidc-provider#369]
Hello.

Looks like mistake here.

```
static async findById(ctx, id, token) { // eslint-disable-line no-unused-vars
    if (!store.get(id)) new Account(id); // new Account never used
    return store.get(id);
  }
```

**Comment by panva** [comment]
no mistake - if you have an adapter persisting clients, sessions and tokens but didn't connect your account model yet, the in memory account store isn't going to have the id after process restart.

**Comment by GitStorageOne** [comment]
Thanks, now i see that "new Account(id)" also automatically writes itself in store.
Without second store search:
```
    const account = store.get(id);
    if (account)
      return account;
    else
      return new Account(id);
```

**Comment by panva** [comment]
yeah, and obviously this is just for testing, intended to allow any credentials to be entered into the example form.
