### ISSUE TITLE
Session#sid missing for all clients but first one

### ISSUE THREAD

**Issue by stavros-wb** [panva/node-oidc-provider#372]
hello @panva 

I've noticed that upon consecutive logins from multiple clients. The `session.authorizations` look like:

```js
{ 
  client1: { 
    sid: 'e541b3ce-e313-48d0-b38d-460a3a1b6c68',
    promptedClaims: [Array],
    promptedScopes: [Array] 
  },
  client2: {},
  client3: {}
}
```

I think these fields only get filled in the `resume` action and since the user is already authenticated the action is never called. Another side effect of this is that the associated `{ AuthorizationCodes, Tokens }` don't get an `sid` in their payload. 

Is this by design?

**Comment by panva** [comment]
I can't repro

1. go to https://tranquil-reef-95185.herokuapp.com
2. set up a basic client, go through login
3. click on New client setup and setup another one
4. go through login
5. tokens have an `sid`

**Comment by panva** [comment]
I **think** you might have a setup where you don't require an interaction for every new encountered client, correct?

Or at the very least, you don't have this in your `interactionCheck` helper.

```
    if (!ctx.oidc.session.sidFor(ctx.oidc.client.clientId)) {
      return {
        error: 'consent_required',
        error_description: 'client not authorized for End-User session yet',
        reason: 'client_not_authorized',
      };
    }
```

If that's the case you have to fill that `sid` in just like resume does automatically, generate a `sid` of your own and call `ctx.oidc.session.sidFor(ctx.oidc.client.clientId, sid)` from that function.

**Comment by stavros-wb** [comment]
yes you're correct, I don't require a user consent when a user accesses another client in the same session. I'll add the call to `sidFor` in my interaction check helper. Also I'd like to note it's not only the `sid` all the other info (scopes) is missing from the session itself.

Do you think this case should be a part of the library?

**Comment by panva** [comment]
No I don’t and see my edit in the comment above. 

Why not? There may be cases where this kind of flexibility is needed. Don’t think it’s a general case tho as it does pose several security risks such as exposing end-user unconsented scopes and claims.
