### ISSUE TITLE
CONTRIBUTING documentation

### ISSUE THREAD

**Issue by ddumontatibm** [panva/node-oidc-provider#373]
Could you please include a file describing the best way to provide code contributions?  And maybe outline how your code pedigree process works?

Do you have a CLA?

**Comment by panva** [comment]
- open an issue describing the feature/bug you wish to contribute first to start a discussion, explain why, what and how
- follow the eslint rules
- write tests covering 100% of the library code you produce
- one PR per feature/fix unless you follow [standard-version](https://github.com/conventional-changelog/standard-version) commit guidelines

I'll see if i can get CONTRIBUTING.md and CLA assistant going (not sure if needed).

**Comment by ddumontatibm** [comment]
Thanks!

**Comment by panva** [comment]
@ddumontatibm @ahmetcetin Thanks for pushing me to do this.
