### ISSUE TITLE
Authorization Codes never expire after consumed

### ISSUE THREAD

**Issue by skeltonm** [panva/node-oidc-provider#375]
One thing I have noticed about this package is that authorization codes do not expire (in the database) but are only marked as consumed.  For a large scale system with millions of users logging in, this would quickly create a massive amount of database records that never go away.

Why are authorization codes saved without an expiration date on the database record?  I would appreciate any of your thoughts/reasons for this functionality so I can understand it better.

**Comment by panva** [comment]
> Why are authorization codes saved without an expiration date on the database record?

They are not saved without an expiration date. How did you come to this conclusion? Are you not getting a ttl on upsert?

**Comment by skeltonm** [comment]
Apologies, this is an issue with our adapter.  It is saving the expiration when the Authorization Code is created then removing it when the Authorization Code is consumed.

Regarding the consumed flag, what is the purpose if marking a token as consumed?  What is the reason for doing this rather than simply deleting the token?

**Comment by panva** [comment]
> What is the reason for doing this rather than simply deleting the token?

https://tools.ietf.org/html/rfc6749#section-4.1.2

> `If an authorization code is used more than once, the authorization server MUST deny the request and SHOULD revoke (when possible) all tokens previously issued based on that authorization code.`

**Comment by skeltonm** [comment]
Thanks!
