### ISSUE TITLE
Scopes per client

### ISSUE THREAD

**Issue by SokratisVidros** [panva/node-oidc-provider#376]
Hi there

Is there a recommended way to define allowed scopes per client?

Thank you in advance.

**Comment by panva** [comment]
My __personal__ recommendation

- [extraClientMetadata](https://github.com/panva/node-oidc-provider/blob/v5.1.0/docs/configuration.md#extraclientmetadata) to validate the values, set defaults and in general process
- automatically push the ones client requests but doesn't have permission for to interaction result `consent.rejectedScopes` or overload OIDCContext `requestParamScopes` or similar, i think this could be done from a number of places
- depending on your policy, whether this is something you want clients to control or a system admin sets up, play around with pre/post middlewares for the registration actions and `registration_create.success` / `registration_update.success` events to block clients from being able to set this custom property.

**Comment by SokratisVidros** [comment]
Thanks a lot!

**Comment by stavros-wb** [comment]
Hello @panva, I can see the above working for User interactions (implicit, auth code), but can't find an appropriate hook for filtering scopes in Client Credentials flow. Should we create a custom grant to support that?

**Comment by brandonros** [comment]
@panva What about a dynamic issuer configuration option? Would that be hard to do? I am using your package and have a need to sign ID tokens as a different issuer per-client.

**Comment by panva** [comment]
@brandonros that's very unlikely to ever land in oidc-provider.
