### ISSUE TITLE
Question: does oidc-provider provides way to upgrade storage data when upgrade versions?

### ISSUE THREAD

**Issue by sunpeinju** [panva/node-oidc-provider#379]
When we upgrade oidc-provider from V4.3 to V5.1, we found the initialAccectToken format changes and our early version initialAccessToken fail to work. So I would like to raise a question here:

How does oidc-provider consider storage data format backward compatibility? When upgrade from version to version, what's the suggested practice for handling the existing data?

**Comment by panva** [comment]
> How does oidc-provider consider storage data format backward compatibility?

It doesn't for major version updates. When you upgrade major versions it's expected you go through the changelog to see what affects your project and upgrade with extra care and testing.

**Comment by panva** [comment]
> does oidc-provider provides way to upgrade storage data when upgrade versions?

No

**Comment by sunpeinju** [comment]
thanks for the answer.
