### ISSUE TITLE
Question: Login to the Identity Provider

### ISSUE THREAD

**Issue by skeltonm** [panva/node-oidc-provider#381]
As the title states, this is a question not an issue.

We would like to allow users to login to the Identity Provider without starting from and going to a Relying Party.  We would then have account management features in the Identity Provider such as update profile, change password, etc.

How would you recommend implementing this type of feature?

**Comment by panva** [comment]
> We would like to allow users to login to the Identity Provider without starting from and going to a Relying Party.

Aren't you already familiar with the `setProviderSession` helper?

Other then establishing the session for the OP for future authorization with the above helper this goes beyond a protocol implementation that oidc-provider brings, don't you think?

**Comment by skeltonm** [comment]
I have used the `setProviderSession` helper in our implementation of this package, but I didn't notice the following sentence:

> or a session just needs to be established from outside the regular authorization request.

Based on that sentence and your comment, are you suggesting using `setProviderSession` to create a session that can be used for logging users into the Identity Provider and then sending the users to the login route?

**Comment by panva** [comment]
Why would you establish the session and then send the users to a login route? What you're after isn't an OpenID Connect flow, that goes for the actual authentication too.

So if e.g. you want a profile page for the user that is not behind an OIDC client (for whatever reason unknown to me, i think it should be ...) then get the user authenticated with whatever standalone means you have (not related to OIDC flow), then establish the OP session so that the user doesn't have to login again the next time he goes through an actual authorization request (that's what it's for) and continue just like in any web app handling user account management.

**Comment by skeltonm** [comment]
Thanks for the info.  In response to your comment about a profile page for a user that is not behind a OIDC client, do you think there is an issue with that?  If so, are websites like GitHub wrong to have the Identity Provider perform additional operations like profile pages (or in the case of GitHub, everything)?

**Comment by marcelalburg** [comment]
Hello, i will use setProviderSession too but i don't understand, why i need to pass an account ? And i don't found any information inside the docs. 

Can you explain my why an account is required ?

Thanks
Marcel

**Comment by panva** [comment]
Hi @marcelalburg,

Because the point is to establish a session outside of regular interaction flow. So a session in order to have any meaning, needs the account identifier?

**Comment by marcelalburg** [comment]
Mhh i see. Currently i look for a way to store data inside a "session" for multi step interactions. and the only (not nice way) is this:

```
 const result = {
   data: 'blup'
  }

  const redirectTo = await provider.interactionResult(ctx.req, ctx.res, result);

  const interactionUrl = url.parse(ctx.oidc.urlFor('interaction', { grant: details.uuid })).pathname
  ctx.redirect(`${interactionUrl}`);    

```

If i would use the redirectTo Url it redirects me to /auth and back to my side with an error. So i need to redirect manually back to my interaction. Is this the correct way oder do i misunderstood something ?

Thanks for your always prompt response.
Marcel

**Comment by marcelalburg** [comment]
My most important use case is the facebook login. 

1) when facebook redirect the user back to my App i use the facebook code to extract facebook id and email address
2) i check the userdatabase for that facebook id and if i found a user, everything is fine
3) if i not found an user with this facebook id i look into the database with the email
4) if i found an already existing user with that email in my database (but he is not linked with facebook yet) so i need to ask for the user password to link this account with the facebook id

exact for this reason, i need to store the facebook result into some kind of "session" and redirect the user to an other interaction, where he need to enter his user password.


Other user case would be a registration form with two pages (page a: name and email, page b: address) i need a possibility to store data during interactions.

Thanks Marcel

**Comment by panva** [comment]
But then don't abuse the OP session. Your interactions flow may utilize its own session mechanism. I don't feel like opening up the OP session for just about anything. You're gonna need one anyway for things like CSRF protection.

**Comment by marcelalburg** [comment]
Do you’ve an example how’s the best way to open an own session in context of openid provider?

**Comment by panva** [comment]
the interaction itself (apart from loading the details with an OP helper) is like any other standalone web app you'd develop, so use whatever mechanism you're familiar with. There's no need to tie this to the OP. The op just cares about getting the results eventually, it doesn't care how you get them.

**Comment by marcelalburg** [comment]
Ok thanks. But are there any issues with my mentioned code above or could i use this?

**Comment by panva** [comment]
I don't recommend it as it's not future proof, in v6.x that i'm working on all models (including session and interaction) have their whitelisted properties defined, therefore your "data" will not be saved or loaded.
