### ISSUE TITLE
Question: Short cookie max age is very short

### ISSUE THREAD

**Issue by skeltonm** [panva/node-oidc-provider#382]
As the title states, this is a question not an issue.

The default value for the max age of short cookies is 10 minutes.  Is there a reason why it is so short?  We have implemented a forgot password feature which will likely take many users more than 10 minutes to complete so we will be increasing the max age of the short cookie.  However, I want to understand why you have the default setting so short to make sure I make the right decision as to how much to increase the max age of short cookies.

**Comment by panva** [comment]
> The default value for the max age of short cookies is 10 minutes.

This is for interaction.

> We have implemented a forgot password feature...

If your password reset link the user goes to after receiving the password reset mail is the one from within an interaction it's wrong. This should be a standalone flow. For obvious reasons, the interaction is bound to that cookie and if i open the link on another device it ain't gonna work.

> However, I want to understand why you have the default setting so short to make sure I make the right decision as to how much to increase the max age of short cookies.

Good call to raise this question, as mentioned above it's probably not the right choice.

Your password reset should be triggered from within an interaction and that interaction is then finished. Where the user goes to to finish the password reset isn't part of that interaction.

**Comment by panva** [comment]
> I would have to disagree with your proposal for handling forgot password.

That's fine, just implement what you feel is right. How you're going to complete an interaction on another device tho is a mistery to me, unless you relax some of the design decisions I've put forth.

> the user would finish resetting their password and then would be forced to go back to the Relying Party and restart the interaction. This would be a terrible user experience.

TBH this is a very standard experience we have today and client's can be registered with an initiate_login_uri (see core 1.0 section 4) that when set, you can redirect to after the flow is finished and the end-user's password is reset

**Comment by tmedanovic** [comment]
@skeltonm How did you solve this in the end? I also feel like this is wrong UX wise, but it makes sense what @panva described. Are the any security concerns with increasing max age to lets say 24h?
