### ISSUE TITLE
HTTP/2 Compatibility

### ISSUE THREAD

**Issue by mgjm** [panva/node-oidc-provider#383]
**Describe the bug**
The provider expects an http or https request and response object in [assertReqRes(req, res)](https://github.com/panva/node-oidc-provider/blob/531dfbf64a4d9a3dd7e5403f211fab4d4a590941/lib/provider.js#L37-L48). This will throw an AssertionError if an [http2](https://nodejs.org/api/http2.html#http2_compatibility_api) request and response object is provided. But Koa supports the Compatibility API of http2 (see [koajs/koa#1193](https://github.com/koajs/koa/issues/1193#issuecomment-389713217)). And I did not notice any problems with the provider either.

**To Reproduce**
Replace the startup of the server:
```js
const https = require('https');
// ...
const server = https.createServer(tlsOptions, provider.app.callback());
// ...
```
... with the following HTTP/2 startup:
```js
const https2 = require('https2');
// ...
const http2Wrap = callback => (req, res) => {
    // fix to koa/request.host
    req.headers.host = req.headers.host || req.headers[':authority'];
    callback(req, res);
};

const server = http2.createSecureServer({
    allowHTTP1: true, // backward compatibility
    ...tlsOptions,
}, http2Wrap(provider.app.callback()));
// ...
```

Steps to reproduce the behaviour:
1.  Start the provider.
2. Start an interaction.
3. `getInteraction` will call `assertReqRes` and an AssertionError is thrown

**Expected behaviour**
No AssertionError 😃

**Environment:**
 - oidc-provider version: v5.1.0
 - node version: v10.11.0

**Possible solution:**
Change `assertReqRes`:
```js
function assertReqRes(req, res) {
  assert(
    req instanceof http.IncomingMessage || req instanceof http2.Http2ServerRequest,
    'first argument must be the request (http.IncomingMessage), for express req, for koa ctx.req',
  );
  if (arguments.length === 2) {
    assert(
      res instanceof http.ServerResponse || res instanceof http2.Http2ServerResponse,
      'second argument must be the response (http.ServerResponse), for express res, for koa ctx.res',
    );
  }
}
```

**Additional context**

 - [x] the bug is happening on latest oidc-provider too.
 - [x] i have tried DEBUG (see readme.md) and can see the issue is with the provider and not my code.
 - [x] i have searched the issues tracker on github for similar issues and couldn't find anything related.
 - [x] i have searched the [FAQ](https://github.com/panva/node-oidc-provider/wiki/FAQ) and couldn't find anything related.

**Comment by panva** [comment]
I never tried exposing an https server directly, always had a tls terminating proxy. If this is just about the instanceof assertion can you open a PR?

Nice find, thank you @mhjm

**Comment by panva** [comment]
oidc-provider v5.1.2 released with a min koa version bump to incorporate said PR changes, note this does not change how http2 host is detected in scenarios where oidc-provider is mounted to an existing koa version that isn't at least 2.6.1
