### ISSUE TITLE
Access_token scope returning string

### ISSUE THREAD

**Issue by GilVieira** [panva/node-oidc-provider#388]
Hi,
my scope, in the access_token, is returning a single string ('openid api1') instead of an array (['openid', 'api1']). How can I configure to return an array? 

I'm trying to validate the access_token in a .Net 4.5 application with IdentityServer3.AccessTokenValidation.

Thks.

**Comment by panva** [comment]
`scope` is always communicated as a single string with space delimited scope names.

**Comment by GilVieira** [comment]
What a shame, because when I validate the token the .Net library requests the required scopes in an array, for example ["api1"], but if I have all a string ("openid email api1") it recognizes the three as a single token and does not release access.

**Comment by panva** [comment]
You’re gonna have to work with the public storage format options to define your own access token serializer that follows .net’s custom format. 

FYI this is all proprietary formats. There’s no standard defining. So it might be easier for you to overload the validation in your client instead.
