### ISSUE TITLE
Feature Request to Integrate with OAuth2 IDP

### ISSUE THREAD

**Issue by SSKasture** [panva/node-oidc-provider#390]
Can we use this library to connect to a OAuth2 compliant IDP (like Clever) and generate OIDC tokens? We’ll need to do the
OAuth2 Authorization Grant Flow behind the scenes to get the user information as documented on their site:
https://dev.clever.com/docs/identity-api

**Comment by panva** [comment]
Your end-user interactions can either be full blown views with forms or just something that communicates with an upstream idp, so yes. It's not standard, but easily doable if you'll take the time to understand how oidc-provider works, e.g. just stick to the expected contract of how interactions work and you should be fine.
