### ISSUE TITLE
consent prompt does not work on oidc-provider resume's interaction check

### ISSUE THREAD

**Issue by supermanHub** [panva/node-oidc-provider#391]
**Describe the bug**
When RP send a authentication request with parameter `prompt=consent`, and the request scope & claims weren't accepted by end-user, the OP never display a consent page to end-user 

**To Reproduce**
Provider and Client configuration: (inline or gist)
```js
// provider configuration
Default provider configuration

// keystore(s) - if they affect the behaviour
Default keystore configuration

// client(s) configuration
Default clients configuration
```

Steps to reproduce the behaviour:

1.  Make sure there is no `session` for `RP` in database
2. RP send a authentication request(Authorization Code Flow)  to OP with parameter `prompt=consent`
3.  End-user login with account name and password
4.  There is consent page display 

**Expected behaviour**
consent page should be displayed when scopes or claims weren't accepted by the end-user yet

**Environment:**
 - oidc-provider version: [e.g. v5.1.2]
 - node version: [e.g. v8.11.3]

**Root cause**

`promptedScopes` & `promptedClaims` check in `oidc-provider/lib/helpers/default.js` never work.

1. How we set `promptedScopes` & `promptedClaims` in `oidc-provider/lib/actions/resume.js` 

```js
// we save the request scopes into promptedScopes and the request claims into promptedClaims directly like below 
 session.promptedScopesFor(params.client_id, ctx.oidc.requestParamScopes); // line 81 in resume.js
 session.promptedClaimsFor(params.client_id, ctx.oidc.requestParamClaims); // line 82 in resume.js
```

2. How we check `promptedScopes` & `promptedClaims` in `oidc-provider/lib/helps/defaults.js` 

``` js
// we check whether promptedScopes contains requestParamScopes in default.js (line 1270)
// Because of we set promptedScopes = ctx.oidc.requestParamScopes in resume.js (line 81),
// so the scope check does not take any effect.
const promptedScopes = ctx.oidc.session.promptedScopesFor(ctx.oidc.client.clientId);
for (const scope of ctx.oidc.requestParamScopes) {
  if (!promptedScopes.has(scope)) {
    return {
       error: 'consent_required',
       error_description: 'requested scopes not granted by End-User',
       reason: 'scopes_missing',
     };
  }
} 

// we check whether promptedClaims contains requestParamClaims in default.js (line 1281)
// Because of we set promptedClaims = ctx.oidc.requestParamClaims in resume.js (line 82),
// so the claims check does not take any effect.
const promptedClaims = ctx.oidc.session.promptedClaimsFor(ctx.oidc.client.clientId);
for (const claim of ctx.oidc.requestParamClaims) { // eslint-disable-line no-restricted-syntax
  if (!promptedClaims.has(claim) && !['sub', 'sid', 'auth_time', 'acr', 'amr', 'iss'].includes(claim)) {
    return {
      error: 'consent_required',
      error_description: 'requested claims not granted by End-User',
      reason: 'claims_missing',
    };
  }
}
```

 - [x] the bug is happening on latest oidc-provider too.
 - [ ] i have tried DEBUG (see readme.md) and can see the issue is with the provider and not my code.
 - [x] i have searched the issues tracker on github for similar issues and couldn't find anything related.
 - [x] i have searched the [FAQ](https://github.com/panva/node-oidc-provider/wiki/FAQ) and couldn't find anything related.

**Logs**

**Comment by panva** [comment]
I cannot confirm this as a bug. Just something omitted from devInteractions on purpose.

The default devInteractions don't have login followed up consent, yes. 
Are you saying they should? What for, you're not going to be using the dev interactions for long anyway and then you're supposed to provide your own interactions that are going to have a consent screen and flows of your own.

see https://github.com/panva/node-oidc-provider/blob/v5.1.2/lib/actions/interaction.js#L60-L79 regardless of what the developer submits it submits everything as agreed upon.

> Expected behaviour
> consent page should be displayed when scopes or claims weren't accepted by the end-user yet

This expected behaviour is in place. Just not using the developer interactions.

> promptedScopes & promptedClaims check in oidc-provider/lib/helpers/default.js never work.

of course they do, there are tests for all of this.

**Comment by panva** [comment]
Would you work out a PR for this or shall i take care of it when i have the time?

**Comment by supermanHub** [comment]
BTW: I suggest we change the return value of `interactionResult` from `return interaction.returnTo` to `return interaction`. By this way, developers can reduce the additional query in their `interactions` code. 

For example, if I want to get the `client_id` in post login, I can do it like this way:
```js
const interaction = await provider.interactionResult(ctx.req, ctx.res, result);
// reduce the interaction details query
// const details = await provider.interactionDetails(ctx.req);
const clientId = interaction.params.client_id;
```

do you agree with that?

**Comment by panva** [comment]
you'd always be loading using `interactionDetails` (to validate the user-agent still having the cookie etc.) before this step so you already have it, don't you?

**Comment by supermanHub** [comment]
I would like to be a contributor and will work on it in this week. Thanks filip 


发自我的 iPhone

**Comment by panva** [comment]
Actually, there's a feature i wanted to get to for a while now and this would give me a chance to smooth this necessary integration step for developers.

I've been slowly working towards what i call a `results builder` DSL. An API that's used inside interactions to aid in figuring out what to do next, as in, what's the next likely check the provider would fail during resume given existing configuration, request params, established session etc.

So if you wouldn't mind, don't bother with adding this to devInteractions, it'll manifest itself as i work on this builder. Given my current capacity and the fact that i have a somewhat working version of it in my stash already ETA is ~2 weeks.

**Comment by supermanHub** [comment]
Hello Filip, Do you mean not submit PR for the `interactionResult ` function change at the moment, and you will handle it in your `result builder` DSL?

**Comment by panva** [comment]
I will not be changing `interactionResult`, you should not skip loading `interactionDetails` and you should be doing that before posting results.

I meant not to work on changing the devInteractions to have a somewhat feature-complete consent screen.

**Comment by supermanHub** [comment]
Yes.
In my customized `interactions` flow,  the `interactionDetails` is a pre-condition for determining what to do next.

sometimes, we can call `interactionResult` directly due to it can do some same work as `interactionDetails`.

```js
// interactionDetail will check session
async interactionDetails(req) {
    return getInteraction.call(this, req);
}

// interactionResult will check session too 
async interactionResult(req, res, result) {
    const interaction = await getInteraction.call(this, req, res);
    interaction.result = result;
    await interaction.save(interaction.exp - epochTime());

    return interaction.returnTo;
}
```
