### ISSUE TITLE
Revoking of tokens by resource owners

### ISSUE THREAD

**Issue by KoosieDeMoer** [panva/node-oidc-provider#392]
The current standards seem to support only one mechanism for revoking access and refresh tokens before expiry ([RFC7009](https://tools.ietf.org/html/rfc7009)).  This implies that the client is the only actor with the authority to explicitly revoke tokens (when the user, for example, logs out).  In an Open Banking ([PSD2](https://en.wikipedia.org/wiki/Payment_Services_Directive#Revised_Directive_on_Payment_Services_(PSD2))) scenario we are working on, we want to provide the user the opportunity to interact directly with the IdP (under the bank’s custodianship in this case) to revoke tokens previously issued to clients.  The scenario is to allow the user, for instance, to revoke 3rd party rights to data (scopes) she previously consented to by performing some actions on a bank provided portal. 

Are you aware of any initiatives in this space, or are you familiar with similar requirements?  Such a requirement could be met by exposing a privileged interface on the OIDCP through which tokens matching a specific client and user context can be revoked.  This sounds a bit “brute force” so I would like to hear your opinion on the matter and whether solving this issue is something you would consider within the realm of responsibility of your OIDCP implementation.

**Comment by panva** [comment]
> we want to provide the user the opportunity to interact directly with the IdP to revoke tokens previously issued to clients

is that the gist of it? is the user on the IdP portal? I assume so, then it's nothing more then looking at your own records, isn't it? Unless i'm missing something.

It would be really helpful if you described the whole thing in OAuth or OIDC terms, it's not clear to me if the bank is the IdP and whatnot...

In any case:

> Are you aware of any initiatives in this space, or are you familiar with similar requirements?

Nope.

> solving this issue is something you would consider within the realm of responsibility of your OIDCP implementation

Not unless there's a related specification or a profile for an existing specification.

**Comment by KoosieDeMoer** [comment]
Hi @panva 
Thanks for quick response.

Yes the user is on the IdP portal but we believe it is cleaner for the OIDC token validity and scopes to be usable as an authoritative source, rather than reverting to the scopes stored against the user by the IdP on each use of a resource.

Here follows a detailed explanation of the roles and what we are trying to achieve.

The bank is the IdP and the resource server. The resource owner holds a bank account.

I am implementing a solution where the resource owner (bank account holder) maintains a list of scopes held by the bank via online banking (Typical Open Banking scenario). At login the client (or relying party[RP], an external party requiring visibility of the RO data at the bank) obtains a code using the implicit flow with a response_type=code. This flow includes a call to the bank, effectively acting as an IdP, which authenticates the RO using a 2FA mechanism. If the 2FA authn succeeds the bank also returns the list of scopes for the Provider to build into the token. The RP then turns the code into a token and proceeds to use RS resources even after RO logout from RP or browser session expiry. This all works perfectly.

The problem I am trying to solve arises when the RO decides to reduce the scopes as held by the bank (IdP). At this point it is necessary for any in-flight tokens that include the deleted scope to be revoked. The RP is unaware of this and also can’t be trusted to revoke the tokens.

Therefore I need the ability for the RO (using the bank infrastructure) to revoke these tokens. This scenario is alluded to in RFC7009 : OAuth 2.0 Token Revocation as follows:

“A client compliant with [RFC6749] must be prepared to handle unexpected token invalidation at any time.  Independent of the revocation mechanism specified in this document, resource owners may revoke authorization grants, or the authorization server may invalidate tokens…”

Although it would solve this problem, I would prefer not implement a regime of refresh tokens and very short-lived access tokens with the Provider making a call to the bank to obtain scopes on each creation of an access token.

I am considering adding a ‘route’ to the Provider’s peripheral js code for use by the bank that will allow the revoking of all tokens related to specified RO. The bank is not aware of token values or grantIds. What do you think? Alternatives?

**Comment by panva** [comment]
> rather than reverting to the scopes stored against the user by the IdP on each use of a resource.

Not what i was suggesting. The idp has access to all access and refresh token records as well as grants in its db. 

Revoke a client grant, query all tokens with that grant, delete them.

> ... access tokens with the Provider making a call to the bank to obtain scopes on each creation of an access token.

Again confusion. You said bank is the idp / provider. 

I’ma close this as there’s no action item here but feel free to continue with the questions, but stay consistent or explain better please. And if you wouldnt mind, keep the questions around oidc-provider specific use, those i can help with.

**Comment by KoosieDeMoer** [comment]
The bank as an enterprise owns to both the IdP and Provider (and an Open Banking portal[OBP]). These are separate systems which we would prefer to keep separate. Calls to the OBP from external clients include an access token in the header, which is used to test access rights to data using token introspection.
In order to keep the Provider separate from the IdP we plan to expose an interface on the Provider that the IdP can call to kill any grants (and dependent in-flight tokens) related to a user when that user revokes scopes at the IdP end.

I have searched for any standard approach and failed. Hence my question here to canvas your opinions on the idea.

**Comment by panva** [comment]
I think you’re better off asking your standards body, OB, FAPI /cc @jogu

**Comment by jogu** [comment]
The business need is quite common about the UK OB system (and I think such management is a requirement of the FAPI spec), but I'm having a bit of trouble following the exact proposed architecture here to be honest. I think I'd probably recommend you get some expert consultancy to help you match your business needs and the legislation to the appropriate way to apply the protocols; I've worked with https://www.raidiam.com before but there are a lot of competent people in this space.

**Comment by panva** [comment]
And if there's anything you need out of oidc-provider in terms of promoting a given API to public please let me know. I'm more than happy to help and support FAPI.

**Comment by amaciver** [comment]
I have a question that I believe is related to this thread:

What would be a suggested pattern if I wanted to only honor Refresh Tokens if a user was still a valid user on the IdP?

My use case is that a user can be removed from the IdP, or lose access to a specific app. However, being already in possession of an AT/RT, the user can persist access after his status has changed. The IdP has no knowledge of grant_id. 

Any basic clues would be greatly appreciated.

**Comment by spruce-bruce** [comment]
I've accomplished that by modifying my adapters to only return tokens if I can verify that the user exists. So you update find with logic that's like:

1. Get the token from your store
1. Get the account id off of the token
1. attempt to fetch the user from the store
1. if a user is found, return the token, otherwise return false and call `this.destroy(id)`

**Comment by panva** [comment]
> What would be a suggested pattern if I wanted to only honor Refresh Tokens if a user was still a valid user on the IdP?

I don’t follow. 

Refresh Token grant, like all the other endpoints, already loads the user. If a user isnt’t found, the request fails.

> The IdP has no knowledge of grant_id.

Of course it does.

**Comment by panva** [comment]
https://github.com/panva/node-oidc-provider/blob/master/lib/actions/grants/refresh_token.js#L59

Please explain what i’m clearly missing here.

**Comment by spruce-bruce** [comment]
I have no actual explanation for @amaciver's issue, the `.find()` changes I made were not because of anything refresh_token grant related, but just a solution to another problem that's more related to the user management portion of my app.

@panva is obviously more right, @amaciver you probably need to check the `findById` function you're providing and make sure it's returning the right value when a user isn't found.

**Comment by amaciver** [comment]
@panva @spruce-bruce thanks for you response. I do see that this should be occurring. I will take a closer look at the IdP side of things. thanks as always.
