### ISSUE TITLE
Clients with the custom grant type "password" can not have response type "token" or "id_token"

### ISSUE THREAD

**Issue by mackwan84** [panva/node-oidc-provider#396]
Clients with the custom grant type "password" can not have response type "token" or "id_token"

**Comment by panva** [comment]
Please elaborate

**Comment by panva** [comment]
And of course it can.

```
const Provider = require('.');

const provider = new Provider('http://localhost:3000');

provider.registerGrantType('password', async () => {});

(async () => {
  await provider.initialize({
    clients: [
      {
        client_id: 'foo',
        client_secret: 'bar',
        grant_types: ['implicit', 'password'],
        response_types: ['id_token'],
        redirect_uris: ['https://jwt.io'],
      },
    ],
  });
})();
```

Please note that it goes against the best practices to use both ROPC and implicit allowed in the same client. It goes against the best practice to even implement ROPC in 2018 and soon enough it will be the best practice to use code flow + pkce in favor of implicit.
