### ISSUE TITLE
Question: Interact URL and Flow

### ISSUE THREAD

**Issue by GilVieira** [panva/node-oidc-provider#397]
I would render the login interface, registry, consent, etc in the react, I am trying to use the interactionUrl, but my code does not pass through this function. And there is some example with redirect to consent page after login (do not know how to force consent_required error).

My interactionUrl block:

```js
interactionUrl (ctx, interaction) {
     return `http://localhost:8001/auth/${ctx.oidc.uuid}`;
}
```

can anybody help me?

**Comment by panva** [comment]
`interactionUrl` is for where interactions go in general. To prevent the authorization server from responding and forcing an interaction you configure(overwrite) the [`interactionCheck`](https://github.com/panva/node-oidc-provider/blob/v5.3.0/docs/configuration.md#interactioncheck) function.

Keep in mind you SHOULD carry over the default behaviours that are in there unless you know exactly what you're doing and WHY you don't want them there.

**Comment by GilVieira** [comment]
I will render the UI by the provider, but how do I validate the consent in the interactionCheck if the function is only called after interactionFinished and flow is returned to the client? is there a way to invoke interactionCheck after login without interactionFinished?

**Comment by panva** [comment]
No, you ought to be able to understand what interactions will be required without calling interactionCheck all the time. That’s why the docs say you must resolve all interactions that you might halt at at once. 

That being said i have some things planned for this.
