### ISSUE TITLE
error_description: 'unrecognized route' 

### ISSUE THREAD

**Issue by panpansh** [panva/node-oidc-provider#401]
**Describe the bug**
render problem

I just clone the master and start koa version

**To Reproduce**

Steps to reproduce the behaviour:
node example/koa.js

**Expected behaviour**

**Environment:**
- os: win10
 - oidc-provider version: master
 - node version: v10.13

**Additional context**

 - [x] the bug is happening on latest oidc-provider too.
 - [x] i have tried DEBUG (see readme.md) and can see the issue is with the provider and not my code.
 - [x] i have searched the issues tracker on github for similar issues and couldn't find anything related.
 - [x] i have searched the [FAQ](https://github.com/panva/node-oidc-provider/wiki/FAQ) and couldn't find anything related.

**Logs**
koa:application use helmet +0ms
NOTICE: a draft/experimental feature (backchannelLogout) enabled, future updates to this feature will be released as MINOR releases
NOTICE: a draft/experimental feature (deviceFlow) enabled, future updates to this feature will be released as MINOR releases
NOTICE: a draft/experimental feature (frontchannelLogout) enabled, future updates to this feature will be released as MINOR releases
NOTICE: a draft/experimental feature (jwtIntrospection) enabled, future updates to this feature will be released as MINOR releases
NOTICE: a draft/experimental feature (jwtResponseModes) enabled, future updates to this feature will be released as MINOR releases
NOTICE: a draft/experimental feature (sessionManagement) enabled, future updates to this feature will be released as MINOR releases
NOTICE: a draft/experimental feature (webMessageResponseMode) enabled, future updates to this feature will be released as MINOR releases
WARNING: a quick start development-only MemoryAdapter is used
  koa-router defined route HEAD,GET /auth +0ms
  koa-router defined route POST /auth +2ms
  koa-router defined route HEAD,GET /auth/:grant +1ms
  koa-router defined route HEAD,GET /me +1ms
  koa-router defined route POST /me +2ms
  koa-router defined route OPTIONS /me +0ms
  koa-router defined route POST /token +1ms
  koa-router defined route HEAD,GET /certs +0ms
  koa-router defined route OPTIONS /certs +1ms
  koa-router defined route POST /reg +1ms
  koa-router defined route HEAD,GET /reg/:clientId +0ms
  koa-router defined route POST /token/revocation +1ms
  koa-router defined route POST /token/introspection +0ms
  koa-router defined route HEAD,GET /.well-known/webfinger +1ms
  koa-router defined route OPTIONS /.well-known/webfinger +0ms
  koa-router defined route HEAD,GET /.well-known/openid-configuration +1ms
  koa-router defined route OPTIONS /.well-known/openid-configuration +0ms
  koa-router defined route HEAD,GET /session/check +0ms
  koa-router defined route POST /session/check +1ms
  koa-router defined route HEAD,GET /session/end +0ms
  koa-router defined route POST /session/end +1ms
  koa-router defined route POST /device/auth +0ms
  koa-router defined route HEAD,GET /device +1ms
  koa-router defined route POST /device +0ms
  koa-router defined route HEAD,GET /device/:user_code/:grant/ +1ms
  koa:application use proxyWarning +68ms
  koa:application use dispatch +0ms
  koa:application use errorHandler +1ms
  koa:application use invalidRoute +0ms
  koa:application use - +6ms
  koa-router defined route  (.*) +8ms
  koa-router defined route HEAD,GET /interaction/:grant +0ms
  koa-router defined route POST /interaction/:grant/confirm +0ms
  koa-router defined route POST /interaction/:grant/login +1ms
  koa:application use dispatch +2ms
  koa:application use - +1ms
  koa:application listen +0ms
application is listening on port 3000, check it's /.well-known/openid-configuration
  koa-router GET / +0ms
  koa-router test (.*) /^((?:.*))(?:\/(?=$))?(?=\/|$)/i +2ms
  koa-router test /interaction/:grant /^\/interaction\/((?:[^\/]+?))(?:\/(?=$))?$/i +2ms
  koa-router test /interaction/:grant/confirm /^\/interaction\/((?:[^\/]+?))\/confirm(?:\/(?=$))?$/i +1ms
  koa-router test /interaction/:grant/login /^\/interaction\/((?:[^\/]+?))\/login(?:\/(?=$))?$/i +0ms
  koa-router GET / +1ms
  koa-router test /auth /^\/auth(?:\/(?=$))?$/i +0ms
  koa-router test /auth /^\/auth(?:\/(?=$))?$/i +1ms
  koa-router test /auth/:grant /^\/auth\/((?:[^\/]+?))(?:\/(?=$))?$/i +0ms
  koa-router test /me /^\/me(?:\/(?=$))?$/i +1ms
  koa-router test /me /^\/me(?:\/(?=$))?$/i +0ms
  koa-router test /me /^\/me(?:\/(?=$))?$/i +1ms
  koa-router test /token /^\/token(?:\/(?=$))?$/i +0ms
  koa-router test /certs /^\/certs(?:\/(?=$))?$/i +1ms
  koa-router test /certs /^\/certs(?:\/(?=$))?$/i +0ms
  koa-router test /reg /^\/reg(?:\/(?=$))?$/i +0ms
  koa-router test /reg/:clientId /^\/reg\/((?:[^\/]+?))(?:\/(?=$))?$/i +1ms
  koa-router test /token/revocation /^\/token\/revocation(?:\/(?=$))?$/i +0ms
  koa-router test /token/introspection /^\/token\/introspection(?:\/(?=$))?$/i +1ms
  koa-router test /.well-known/webfinger /^\/\.well-known\/webfinger(?:\/(?=$))?$/i +0ms
  koa-router test /.well-known/webfinger /^\/\.well-known\/webfinger(?:\/(?=$))?$/i +0ms
  koa-router test /.well-known/openid-configuration /^\/\.well-known\/openid-configuration(?:\/(?=$))?$/i +1ms
  koa-router test /.well-known/openid-configuration /^\/\.well-known\/openid-configuration(?:\/(?=$))?$/i +0ms
  koa-router test /session/check /^\/session\/check(?:\/(?=$))?$/i +1ms
  koa-router test /session/check /^\/session\/check(?:\/(?=$))?$/i +0ms
  koa-router test /session/end /^\/session\/end(?:\/(?=$))?$/i +1ms
  koa-router test /session/end /^\/session\/end(?:\/(?=$))?$/i +0ms
  koa-router test /device/auth /^\/device\/auth(?:\/(?=$))?$/i +0ms
  koa-router test /device /^\/device(?:\/(?=$))?$/i +1ms
  koa-router test /device /^\/device(?:\/(?=$))?$/i +1ms
  koa-router test /device/:user_code/:grant/ /^\/device\/((?:[^\/]+?))\/((?:[^\/]+?))(?:\/(?=$))?$/i +0ms
  **oidc-provider:error uuid=undefined path=/ method=GET error={ error: 'invalid_request', error_description: 'unrecognized route' } detail=undefined +0ms**
NOTICE: default helper renderError called, you SHOULD change it in order to customize the look of the error page.
  koa-router GET /favicon.ico +123ms
  koa-router test (.*) /^((?:.*))(?:\/(?=$))?(?=\/|$)/i +2ms
  koa-router test /interaction/:grant /^\/interaction\/((?:[^\/]+?))(?:\/(?=$))?$/i +1ms
  koa-router test /interaction/:grant/confirm /^\/interaction\/((?:[^\/]+?))\/confirm(?:\/(?=$))?$/i +0ms
  koa-router test /interaction/:grant/login /^\/interaction\/((?:[^\/]+?))\/login(?:\/(?=$))?$/i +0ms
  koa-router GET /favicon.ico +1ms
  koa-router test /auth /^\/auth(?:\/(?=$))?$/i +0ms
  koa-router test /auth /^\/auth(?:\/(?=$))?$/i +0ms
  koa-router test /auth/:grant /^\/auth\/((?:[^\/]+?))(?:\/(?=$))?$/i +1ms
  koa-router test /me /^\/me(?:\/(?=$))?$/i +0ms
  koa-router test /me /^\/me(?:\/(?=$))?$/i +0ms
  koa-router test /me /^\/me(?:\/(?=$))?$/i +1ms
  koa-router test /token /^\/token(?:\/(?=$))?$/i +0ms
  koa-router test /certs /^\/certs(?:\/(?=$))?$/i +0ms
  koa-router test /certs /^\/certs(?:\/(?=$))?$/i +0ms
  koa-router test /reg /^\/reg(?:\/(?=$))?$/i +1ms
  koa-router test /reg/:clientId /^\/reg\/((?:[^\/]+?))(?:\/(?=$))?$/i +0ms
  koa-router test /token/revocation /^\/token\/revocation(?:\/(?=$))?$/i +1ms
  koa-router test /token/introspection /^\/token\/introspection(?:\/(?=$))?$/i +0ms
  koa-router test /.well-known/webfinger /^\/\.well-known\/webfinger(?:\/(?=$))?$/i +1ms
  koa-router test /.well-known/webfinger /^\/\.well-known\/webfinger(?:\/(?=$))?$/i +0ms
  koa-router test /.well-known/openid-configuration /^\/\.well-known\/openid-configuration(?:\/(?=$))?$/i +1ms
  koa-router test /.well-known/openid-configuration /^\/\.well-known\/openid-configuration(?:\/(?=$))?$/i +0ms
  koa-router test /session/check /^\/session\/check(?:\/(?=$))?$/i +1ms
  koa-router test /session/check /^\/session\/check(?:\/(?=$))?$/i +0ms
  koa-router test /session/end /^\/session\/end(?:\/(?=$))?$/i +1ms
  koa-router test /session/end /^\/session\/end(?:\/(?=$))?$/i +0ms
  koa-router test /device/auth /^\/device\/auth(?:\/(?=$))?$/i +0ms
  koa-router test /device /^\/device(?:\/(?=$))?$/i +2ms
  koa-router test /device /^\/device(?:\/(?=$))?$/i +0ms
  koa-router test /device/:user_code/:grant/ /^\/device\/((?:[^\/]+?))\/((?:[^\/]+?))(?:\/(?=$))?$/i +1ms
  **oidc-provider:error uuid=undefined path=/favicon.ico method=GET error={ error: 'invalid_request', error_description: 'unrecognized route' } detail=undefined +137ms**

**Comment by panva** [comment]
Hi @panpansh, see that this is a request to /favicon.ico made by your browser. There's nothing to fix. You may add a static favicon.ico to your koa app if you wish.

**Comment by panpansh** [comment]
Hi  @panva  :) it's the same for getting root
oidc-provider:error uuid=undefined path=/ method=GET error={ error: 'invalid_request', error_description: 'unrecognized route' } detail=undefined +0ms

**Comment by panva** [comment]
the provider doesn't have/need one. Just go to /.well-known/openid-configuration

**Comment by panpansh** [comment]
but you have views _layout.ejs login.ejs 
idk why is not working with your example

**Comment by panva** [comment]
maybe this example for you then https://github.com/panva/node-oidc-provider-example

**Comment by panva** [comment]
oidc-provider is not a full blown account management solution with root page, signup and login pages etc, it is merely a customisable protocol implementation
