### ISSUE TITLE
Custom Attributes

### ISSUE THREAD

**Issue by greenboxal** [panva/node-oidc-provider#402]
Is there a supported way of adding custom attributes to a client? We want to store some extra information that relevant to flow.

For example, adding a "trusted" flag so we can skip the consent screen for our own apps.

I tried just adding the attribute but when using `provider.Client.findById`, I don't get the value inside the object.

**Comment by panva** [comment]
https://github.com/panva/node-oidc-provider/blob/master/docs/configuration.md#extraclientmetadata
