### ISSUE TITLE
Sign-out 

### ISSUE THREAD

**Issue by melorbany** [panva/node-oidc-provider#406]
**Describe the bug**

I am trying to sign-out from my session and after visit the usr "/session/end" I checked the redis keys I found that sign out is only remove the session key not the access token  and after redirecting to the main app it automatically sign-in without asking for login credential.

**To Reproduce**
Provider and Client configuration: (inline or gist)
```js
// provider configuration
Using Redis Adapter and using accounts.

```

Steps to reproduce the behaviour:

1. Run the app usign for example port '3000' and redirect_uri 'http:///main.app.com'
2. Sign in using the account information 
3. Visit the url ex. 'localhost:3000/session/end' 
4. Click sign out.
5. Visit the main url in the redirect_uri params ex. 'http:///main.app.com'
6. It will work without asking for new login.

**Environment:**
 - oidc-provider version: [e.g. v5.5.1]
 - node version: [e.g. v10]

**Comment by panva** [comment]
Can you provide a dumbed down working example? 

Tokens aren't getting dropped automatically when an end-user signs out, it only drops the session, that's working as intended (for this version anyway, i'm working on a new one where this is significantly improved and follows the recent oauth wg bcp discussions.

> It will work without asking for new login.

Again, please a fully working sample i can repro with, this is basic behaviour that's tested, there's no way that if the cookies are dropped and the session in an adapter no longer exists that you would be auto signed in.

**Comment by melorbany** [comment]
Thanks, @panva I think the problem is related to the web client log out so I will check this and get back if I found anything related
