### ISSUE TITLE
Make openid a configurable scope? 

### ISSUE THREAD

**Issue by keeneagle** [panva/node-oidc-provider#407]
We used the oidc-provider to provide the oAuth 2.0 support for our production. Actually, we don't need id_token for oAuth authorization. But at current, it's always been generated since the openid is a must have scope in oidc-provider. 
@panva, is there any consideration to make openid a configurable scope rather than a must have scope? Thanks

**Comment by panva** [comment]
Hi @keeneagle, there isn't since this is an openid connect provider implementation and its behaviour when openid as a scope is not requested is by spec undefined.

**Comment by panva** [comment]
I understand, but who defines the behaviours when openid scope is not requested, which of the openid features should be gated then.

By default the openid scope just makes it so that you get a token accepted by the userinfo endpoint and an id token containing information about the authentication, no claims. I don’t see the extra weight for a client who just needs oauth. Please elaborate.

**Comment by panva** [comment]
actually, not that difficult now that i think about it

**These authorization parameters would require the `openid` scope to be present.**

- acr_values
- claims
- claims_locales
- id_token_hint
- max_age
- nonce

**access tokens are only usable at the userinfo endpoint if they have the `openid` scope**

**response types with id_token require the `openid` scope**

**token endpoint grant calls only issue ID Token when `openid` scope is present**

Did I miss something?

**Comment by keeneagle** [comment]
Hi @panva, glad that you've thought it more deeper. 👍 Hope this feature would be released soon. :-)

**Comment by panva** [comment]
> Hope this feature would be released soon. :-)

Don't get your hopes up. I wouldn't expect the next feature release (looking at the changes i can already say it's breaking - so 6.x) until 2019 ;)

**Comment by sunpeinju** [comment]
6.x is good enough, `oidc-provider`'s evolution is so quick:)

Your change list covers mine:
- stop returning id_token at /token endpoint if no openid scope
- check openid scope to guard /userinfo endpoint
- About the params check, you are expert:)

**Comment by panva** [comment]
For the record openid will always be required to be available. What i’m gonna do is just make it optional in authorization requests together with the scope parameter
