### ISSUE TITLE
iOS Shared session (SSO) between native safari and UIWebView(in app browser)

### ISSUE THREAD

**Issue by deadmanhead1602** [panva/node-oidc-provider#409]
**Is your feature request related to a problem? Please describe.**
After iOS 11, the cookie space between each Safari instance cannot be shared except using ASWebAuthenticationSession to start the login flow. But the [document](https://developer.apple.com/documentation/authenticationservices/aswebauthenticationsession?language=objc) tells that 'session cookies' still cannot be shared.  

I found node-oidc-provider will turn the session and state cookie become 'session cookies' after login flow. The related code is here. Everything goes right when I remove that. 
https://github.com/panva/node-oidc-provider/blob/b018225e83e8c074d6b3631e7ed756a2eb236fb4/lib/shared/session.js#L34-L39 

**Describe the solution you'd like**
1. Keep login related cookies be 'long cookie' after login
2. Provide an option to tell the provider don't change the login related cookies become 'session cookie'

**Additional context**
 - Only apple device after iOS 11 hit this 
 - Cookie before login 
![before-login](https://user-images.githubusercontent.com/1516117/49911023-e2147400-febf-11e8-9554-410b0214848f.png)

 - Cookie after 
![after-login](https://user-images.githubusercontent.com/1516117/49911036-e80a5500-febf-11e8-81e6-d981d0fbd76c.png)

 - [*] i have searched the configuration section for this feature and couldn't find it
 - [*] i have searched the issues tracker on github for similar requests and couldn't find anything related.

**Comment by panva** [comment]
Your interaction result should pass remember: true in the login block, this will make the session cookie have expiration and not be transient.
