### ISSUE TITLE
Implicit flow with ID & Access token

### ISSUE THREAD

**Issue by SokratisVidros** [panva/node-oidc-provider#410]
Hi there,

Just a quick question regarding implicit flow configuration.

I am using oidc-provider 4.8.2 and I am trying to test an implicit flow and receive both an ID & access token.

My client is configured with `id_token` and `token` response types. However, when I navigate to

`http://localhost:5000/oidc/auth?client_id=my_client&nonce=deadbeef&scope=openid&response_type=idtoken%20token`

the following error is returned:

```json
{"statusCode":400,"error":"Bad Request","message":"response_types can only contain members [code id_token token,code id_token,code token,code,id_token token,id_token,none]"}
```

Could you please spot the mistake in my configuration?

Thank you in advance.

**Comment by fauxsoup** [comment]
`idtoken` is incorrect. should be `id_token`.

**Comment by panva** [comment]
Hi @SokratisVidros 

I see that your authorization request is incorrect, the registered mode is `id_token token`, not `idtoken token`. And the error you're showing is a client validation error, this could mean one of two things, either your configuration also uses `idtoken token`, or you're passing in two array members [`id_token`, `token`] which is not the same as a single `id_token token` value.

https://openid.net/specs/oauth-v2-multiple-response-types-1_0.html

**Comment by panva** [comment]
[For the record](https://tools.ietf.org/html/draft-ietf-oauth-security-topics-10) implicit flows returning access tokens are soon to be deprecated and discouraged from being used for new solutions.

**Comment by SokratisVidros** [comment]
Makes sense @panva. Thank for the reminder.

**Comment by GilVieira** [comment]
Hi @panva ,

> implicit flows returning access tokens are soon to be deprecated and discouraged

so what approach should I use for a SPA application?

**Comment by panva** [comment]
code + pkce

See the bcp draft.

**Comment by panva** [comment]
Also [here, specific to browser apps](https://tools.ietf.org/html/draft-parecki-oauth-browser-based-apps-02) these are drafts and heavily discussed atm on the oauth WG mailing list. While they are subject to change the recommendation is not to use implicit for new development. 

oidc-provider is ready for this if you do a post-middleware to open up the token endpoint to cors (this will be updated in lib eventually)

**Comment by GilVieira** [comment]
@panva , correct me if I'm wrong, this case use the hybrid stream, and I will need a backend to pass the authorization code via https (POST) that will connect with the OP and then return the acess_token to the SPA:

1. **SPA** redirect with `code id_token` and `implicit` to **OP** (authorization_endpoint);
2. **OP** return `id_token` and `code` to **SPA**;
3. **SPA** send `code` to **backend (not OP)** (post https);
4. **backend** send `code` to **OP** (token_endpoint using client_id and secret);
5. **OP** return `access_token` to **backend**;
6. **backend** return `access_token` to **SPA**;
7. **SPA** consume api sending  `access_token` to **Resource Server**;

Is that correct? And silent refresh works in hybrid flow like in implicit (but returning code instead access_token)?

Thanks!

**Comment by panva** [comment]
To begin with, if your use case is just login you should be using `type=id_token` and `mode=form_post` just to get details about the user. There's no point in handling secrets or access tokens if all you use it for is securing your own app.

If you need to get an access for a third party API then...

You have a backend to your SPA? Use whatever flow that doesn't return an access_token from the authorization_endpoint. But if you're consuming responses by a backend then there's no need to use a hybrid flow. Just use code.

If you have a SPA served by a CDN (no backend) then use `code` and pkce, no client authentication - it is a non-confidential client.

Please don't turn this into an OAuth2 helpdesk, study the resources or search for other material online. My job here is not to train developers but to give them a solution that supports the best current practice.
