### ISSUE TITLE
Cannot send secure cookie over unencrypted connection

### ISSUE THREAD

**Issue by brandonros** [panva/node-oidc-provider#411]
```
if (environment === 'production') {
  app.enable('trust proxy')
  provider.proxy = true
}

cookies: {
  keys: cookieKeys,
  short: {
    secure: true,
    signed: true,
    httpOnly: true,
    maxAge: (1 * 60) * 1000 // 1 minutes in ms
  },
  long: {
    secure: true,
    signed: true,
    httpOnly: true,
    maxAge: (10 * 60) * 1000 // 10 minutes in ms
  },
  names: {
    session: '_session',
    interaction: '_interaction',
    resume: '_resume',
    state: '_state'
  }
},

app.use(`${OIDC_URL_PREFIX}/oidc/`, provider.callback)
```

I'm using Express serving HTTP behind nginx which handles turning it into HTTPS. 

I don't understand how to enable secure + signed cookies in the described setup above. Any information you can offer would be a benefit.

**Comment by panva** [comment]
Additional to that flag you must also configure your nginx to pass some headers. This is pretty standard and unrelated to oidc-provider.

https://github.com/panva/node-oidc-provider/blob/master/docs/configuration.md#trusting-tls-offloading-proxies
