### ISSUE TITLE
Question: id_token_hint validation?

### ISSUE THREAD

**Issue by kramer99** [panva/node-oidc-provider#412]
Apologies if any part of this question is vague, I'm quite new to OIDC.

I'm trying to get an OIDC flow from Microsoft Azure working, based off your tutorial examples. Azure passes an id_token_hint, which causes the initial interaction to fail:

`{ error: 'invalid_request', error_description: "could not validate id_token_hint (Cannot read property 'jwksUri' of undefined)",`

...which is thrown at `interactions.js:135`

In my index.js, I'm able to decode the id_token_hint successfuly with:

`const jwtDecode = require('jwt-decode');`
`console.log(jwtDecode(details.params.id_token_hint));`

...and it displays the expected fields (aud, iss, iad, etc, etc)

So my question is: is there some configuration that I am missing in order for this to be decoded by the oidc-provider and then used to build an id_token to return to Azure?

**Comment by panva** [comment]
Hi @kremer99,

> OIDC flow from Microsoft Azure

Not sure what you refer to here. 

> is there some configuration that I am missing in order for this to be decoded by the oidc-provider and then used to build an id_token to return to Azure?

???

More context please.

**Comment by panva** [comment]
> id_token_hint
> OPTIONAL. ID Token previously issued by the Authorization Server being passed as a hint about the End-User's current or past authenticated session with the Client.

_previously issued by the Authorization Server_ - it doesn't seem like whatever is calling your oidc-provider's authorization endpoint is passing an id_token_hint with a value that's previously issued by this provider.

The cryptic error "Cannot read property 'jwksUri' of undefined" inside the actual validation error is something i'll fix, but it won't change the outcome.

Please provide more context.

**Comment by kramer99** [comment]
> > id_token_hint
> > OPTIONAL. ID Token previously issued by the Authorization Server being passed as a hint about the End-User's current or past authenticated session with the Client.
> 
> _previously issued by the Authorization Server_ - it doesn't seem like whatever is calling your oidc-provider's authorization endpoint is passing an id_token_hint with a value that's previously issued by this provider.

Hmm, I see... that would make sense, as there has not been a successful authorization yet. Does that imply that Microsoft is not following the spec correctly with regard to id_token_hint?

> 
> The cryptic error "Cannot read property 'jwksUri' of undefined" inside the actual validation error is something i'll fix, but it won't change the outcome.
> 
> Please provide more context.

Sure, I've taken the example here: https://github.com/panva/node-oidc-provider-example/tree/master/03-oidc-views-accounts and modified the client initialization values like so:
```
oidc.initialize({
    clients: [{ 
        client_id: '18265166-2c91-43dd-ad51-2b9e806e4ae4',
        grant_types: ['implicit'],
        response_types: ['id_token'],
        redirect_uris: ['https://login.microsoftonline.com/common/federation/OAuth2ClaimsProvider'],
        token_endpoint_auth_method: 'none' 
    }],
}).then(() => {
```
The auth call made by Azure to my provider then looks like this:
```
POST https://ionic-oidc.herokuapp.com/auth

Host: ionic-oidc.herokuapp.com
User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10.12; rv:63.0) Gecko/20100101 Firefox/63.0
Accept: text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8
Accept-Language: en-US,en;q=0.5
Accept-Encoding: gzip, deflate, br
Referer: https://login.microsoftonline.com/federation/redirecttoexternalprovider
Content-Type: application/x-www-form-urlencoded
Content-Length: 3035
Connection: keep-alive
Cookie: _session=35cadb67-b099-4b35-9341-1bd7ccf03b3f
Upgrade-Insecure-Requests: 1

state=rQIIAY2QPUvDQACGe02bahG_6KCbQxUVLskld7mkIFgVhFJwKIq4yOVyaaM0p0msRRwVXARxEkdHuzlJf0InR3F0EidHR9t_4PKuz_O8RRVphoboqoI0VClzhrmFfRtyQQ2ILWJBh9gO5Iy4no0Dk9lWPFucvu8tLaenV9sP_cvC7URv7RkstdL0JKnoesCSNI0ZP9baIY9lIoNU47KtJ2EzCqNXAN4A-ALgOVt2TWoiH1PoO5xALDwXOlxYkDHmMNMMbOyhj-zUTvUsbZmjkXF4IR6VMgk4odR3IGGugNgzHegKZkIXUdvgxPIoxi-KOqS2ZfSugE-lxGMWNtdDGYUc-qItR0pvOfCdmxgD05m5mYXMcsHI_-bAU36Y97lyOF_Ci7Xr0qTv9WVmkNfP43p8uiGOEmMPNboNPdgy_K6Qnfp-9WCjQYkRbdbj3bTTOOFrtILuVHWgZmvJj5q9KWT64_-85w81.AQABAAEAAAC5una0EUFgTIF8ElaxtWjTkwndVaM_nsVhrXnwcW7C9S3UeUrLlqwitFrvaWHMOruIZcTLeJq7kXEOZaVa9i_5okQxsHEqOMp4coV54PrgKnJFykmvUgc0X2Z_pqppVsrqNTu49JVA9f_XD0N6GG7sU2Ci_4j6vlsQxX6mRA_1r_pPbpU4T7Qyfm-4-_OG0z7lndkOz7bcuYdQz8KF6XhAVwUy7K934yJBJN1xDJGjpVoo54Wk-_5gQAvIZvrwEk8hR0ip-fteF9FnMtzR57Z9L9tfRQwUdsi_KJ6YyjsGoVqh1VQLUP09hD3xR4i09ErS0iZenL2SvOPjHzsxPbDMFoLRSzB2o8JpG6rJ80xlf5vBDRU5HSEfDSn0yIeIuyFkpWmluLnkVMZZp2PS4F8yBwoYfuk6m8PvImbSzjxzCW-eJEsxnC-XnFaFvRW5lSm7X0g3tPQOmyBxnpl-qcTRz_PqgES0FrsnyDaE-ImvgW22riOGeQ4ZrPzqFh7puf8uTOkZrzqJRHdwx-f6WHDjBZCrtV85ZrQ2o4kY7VUlUAV6c3dka9agYoh5qrM5-JQlfOF-R8ajz-yZtFSEqtlDb43UPUz5rNRayRbR_TH38Vmb34zdNYyxH9XheQeCwMKZ-sFLXlzDu0euFrCghmGaK3Y1t85Pt5eSrpfScB-Z4-PM_vuwwx3Pm4F1HG5PGOnA2xN5Nv9XxXnd7nQ-ouRXzftz_c7F9vkEa1h7mskOk006XDERftkinzN2HqlrQC7sKQFep4iAyOGBvxoY-c0EaZUfDuLkxDf3mQ-rkd9-5uVPOnIIKNAj-rkmR4d-1W5vi-7iaOzKNjgGBo54BeLdL1cVmEJCGe7GJv9jvTKWc1XODW4gBpB8meqgTe5K5UmaATTZuQ6FHI2Y69XY2GlR4Fuzep0XXNiiPJdf534ZESAA&scope=openid&response_mode=form_post&id_token_hint=eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiIsIng1dCI6Im5iQ3dXMTF3M1hrQi14VWFYd0tSU0xqTUhHUSIsImtpZCI6Im5iQ3dXMTF3M1hrQi14VWFYd0tSU0xqTUhHUSJ9.eyJhdWQiOiIzZGQ4M2ZhMC05OGQ1LTRhNWMtYjZkYy0yM2RmNzAwZmZlODYiLCJpc3MiOiJodHRwczovL3N0cy53aW5kb3dzLm5ldC81ZTY3NjMzOC0zNzUwLTQxZDMtOTQ4Ny1lM2Q2NmUxOGM0N2EvIiwiaWF0IjoxNTQ1MDgyNzU4LCJuYmYiOjE1NDUwODI3NTgsImV4cCI6MTU0NTA4MzY1OCwiZmFtaWx5X25hbWUiOiJIZW5kZXJzb24iLCJnaXZlbl9uYW1lIjoiQ3JhaWciLCJuYW1lIjoiQ3JhaWcgSGVuZGVyc29uIiwib2lkIjoiMGM1ZWQ3ZmMtYjNjOS00MWUxLTlkMWMtNWVhZWQ0NWY4MmZiIiwic3ViIjoiT3NvMFBUb1NfdXp0TFhfeFhnNFJxNWJsdTNneWluNzhtY3puSlVvLW5OSSIsInRpZCI6IjVlNjc2MzM4LTM3NTAtNDFkMy05NDg3LWUzZDY2ZTE4YzQ3YSIsInVuaXF1ZV9uYW1lIjoiY3JhaWdAaW9uaWMtZGVtby5jb20iLCJ1cG4iOiJjcmFpZ0Bpb25pYy1kZW1vLmNvbSIsInZlciI6IjEuMCJ9.s10NSOchY14LHSPhBUAwDgB9dxtEWH5TUKNh8SV69iFVCds475RPUhjbkc_sxZqXJ5rUCMWgvYpVlKZ5eZYWW0FqjmpYDkqbNKvPUGM9PoKlYCEC86Hi4aun4eudB45pggKuCKZMUBgogfJPNcApO7V_f2bAe_nQEl5io2XOKwpeqYYJ0PjvCytdLbucRHOoxfuNNY8n8hBBoqC3hdKZW5qtsMkytYUE6lqTTBahdVGntjF2vEti1pPBwOG4uLdtwgWXfwF3oT6BvrfGSlCGE8N-GrYC3N6_W4hSSrjz0tZ5WepZqr0h0xOY2obeVjMqMeCTpgxpbEoCazDarpn5qw&response_type=id_token&client_id=18265166-2c91-43dd-ad51-2b9e806e4ae4&redirect_uri=https%3A%2F%2Flogin.microsoftonline.com%2Fcommon%2Ffederation%2FOAuth2ClaimsProvider&claims=%7B%22id_token%22%3A%7B%22key_fetch%22%3A%7B%22essential%22%3Atrue%2C%22value%22%3A%22yes%22%7D%7D%7D&client-request-id=2826ab92-7174-4784-98ba-7c078d0cab3d&nonce=7832eebe-8271-47ed-a605-e040051f7b06&canary=wrLrqBejs0V1SxS%2FfD0dxeovLXAZBS750nCLrUtvSpc%3D7%3A1&cxh_inclusive=False
```

Let me know what other information I can provide.

**Comment by panva** [comment]
Would you please share the documentation you’re following?

Please explain what the two OPs are for and what your intentions are with this setup.

**Comment by panva** [comment]
@selfissued Mike, it appears that when Azure makes an openid request to an external openid claims provider it send an `id_token_hint` which is an ID Token of Azure and not the one it previously received from the external claims provider.

> id_token_hint
> OPTIONAL. ID Token previously issued by the Authorization Server being passed as a hint about the End-User's current or past authenticated session with the Client.

An `id_token_hint` not issued by the OP itself will fail validation and therefore result in `invalid_request` error. Am I missing something or is Azure in the wrong here?
