### ISSUE TITLE
client authentication failed when try get refresh tokent

### ISSUE THREAD

**Issue by Sh4dow** [panva/node-oidc-provider#414]
I don't think this is a bug, rather my configuration problem. This is how my client is configured.

```json
{
    "client_id": "premium", 
    "grant_types": ["authorization_code", "refresh_token"], 
    "client_secret": "ku1ahthiebaiyavi8Ta6on0ieje6Yoo7naiw6Atheis2Coga9uobae3shul7phoo",
    "redirect_uris": ["http://admin.local.host/?action=auth&show=verify"], 
    "response_types": ["code"],
    "token_endpoint_auth_method": "client_secret_basic"
}
```
Everything is working, I've got access and refresh token in response. But when i'm trying to refresh token i'm getting `client authentication failed` error.
Strange thing is when I log in to OP client token_endpoint_auth_method is checked against and array with one value `[ 'client_secret_basic' ]`, but when I try to refresh token_endpoint_auth_method is checked again this values
```json
[ "client_secret_post",
  "none",
  "tls_client_auth",
  "self_signed_tls_client_auth"]
```
And of course then if got 
```the registered client token_endpoint_auth_method does not match the provided auth mechanism```

I'm using this library https://github.com/jumbojett/OpenID-Connect-PHP
and this lib send such request for refresh token
```POST /token```
```json
{
    "grant_type":"refresh_token",
    "refresh_token":"eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCIsImtpZCI6Ijc5a2t6dzhpeUpUVjUxVU44cjFUS0o0SmRCTGVBTUk2TWFzWm5rS29JSGcifQ.eyJqdGkiOiJ5ZXZqMXpHR0hnV240NDR0dWNyb34iLCJzdWIiOjEsImlzcyI6Imh0dHA6Ly9vcGVuaWQubG9jYWwuaG9zdCIsImlhdCI6MTU0NTEyMjU0MSwiZXhwIjoxNTQ2MzMyMTQxLCJzY29wZSI6Im9wZW5pZCIsImF1ZCI6InByZW1pdW0ifQ.UeTfptHjJ7GLdebON2jtA2MzycTLcqkpdrXcDt4jY3w1hHqYg0aLkHtWMB0Ioj0It-PuMWo0vnXTmUK_j6mx3rvaft_nUh02FSLLVa9oF_tAm88Cpn1llMrwOcnngY-62qxsIytfzyneUQbdhuHKIqGhOpcEIunx_Ignk4CESLm43BumdOrzjE9RUesKK8GjR2GcPV23lZOCkNXZDAomSRAPDutRsfcL1RIuyjGD8NKfccX9rTJ5t0HZ4JB1MNkp9tA3sb82VEdwndbaYp5rJb0OKoTIPDe_ZwJQdcqIrfpX4Tj8QZZQAcEJwoltLy0mAwHRdivD-bXwauo8DZtj1A",
    "client_id":"premium",
    "client_secret":"ku1ahthiebaiyavi8Ta6on0ieje6Yoo7naiw6Atheis2Coga9uobae3shul7phoo"
}
```
Did I configure something wrong or this client library is doing something wrong?

**Comment by panva** [comment]
Hi @Sh4dow,

The problem is indeed your configuration, your client is using client_secret_post, not client_secret_basic.

What's weird is you it does an authorization code exchange with basic, and then refresh token exchange with post. I suggest you dig in your client configuration to align the way it does exchange overall.

**Comment by panva** [comment]
And please keep in mind, it's not allowed to send both at the same time (post and basic).

**Comment by Sh4dow** [comment]
So when i want to use refresh token i can't use client_secret_basic?

**Comment by panva** [comment]
No you can, but your client must use exactly one authentication method throughout all its requests and that's the method you must configure in its configuration on the server side. At the moment (i briefly checked the code) it looks like your client uses two methods at the same time which is not allowed.

**Comment by Sh4dow** [comment]
I've used default configuration for ```tokenEndpointAuthMethods``` and my client library use different methods for each request. For accessToken it use basic if found in .well-known, but didn't check for it in refreshToken request.
Thank You for help.

**Comment by panva** [comment]
> my client library use different methods for each request

There's your problem.

**Comment by Sh4dow** [comment]
I'll fork this lib and prepare some fixes for this and make pull request

**Comment by panva** [comment]
`¯\_(ツ)_/¯`

happy i could help
