### ISSUE TITLE
Use req object inside provider.Account.findById

### ISSUE THREAD

**Issue by jakubzloczewski** [panva/node-oidc-provider#42]
My core need is to use req object and cookies inside my findById but I can't as long it has only accountId passed via arguments.

Maybe there could be elegant way to replace loadAccount middleware with my custom implementation or just pass req object along with accountId?

Any ideas?
Thanks!

**Comment by panva** [comment]
depending on the action used a loadAccount middleware is different, so i'd therefore say the better way for findById to be context aware is to either get the koa ctx as `this` (same as the other helper methods) or have it passed as a second argument (same as what i plan for 2.0.0 once koa2 based version comes out, there will be a breaking change).

So we make it the methods' this and do a similar breaking change for all configurable functions for 2.0? The function will get koa ctx bound as `this` during authorization, during token calls (authorization_code and refresh_token) and obviously userinfo. What do you think?

**Comment by jakubzloczewski** [comment]
Sounds great. I'm wondering what will be better: passing koa ctx as `this` or as last argument. I don't know very well internals of this library but it could leads to problems if we will override original scope of functions. Please correct me if I'm wrong.

**Comment by panva** [comment]
You are correct, i will deprecate (will remain available until 2.0) the original findById, come up with a new name, change the documentation to use the new one and point out the scope assignment.

**Comment by panva** [comment]
As a matter of fact, since i wrap the function in an object of my own, the functions context was never the developer's Account Model one. So no need to deprecate stuff.
