### ISSUE TITLE
Hybrid flow configuration

### ISSUE THREAD

**Issue by jpreese** [panva/node-oidc-provider#420]
I have a client that I want to use the Hybrid flow with node-oidc-provider, but Hybrid is not an acceptable grant type. Using node-oidc-provider I'm not quite sure on how to set up a Hybrid flow since I want the response type to be 'code id_token', but every combination returns:

'response_type not allowed for this client'

`
grant_types: ['authorization_code', 'implicit'],
response_types: ['code id_token'],
`

**Comment by panva** [comment]
Hi @jpreese,

more context please. What's the authorization request you're doing?

**Comment by jpreese** [comment]
Yeah, I have oidc-provider in a container and I've tried restarting after applying the change to the grant_type. I've also messed around with some configs that I know work and those changes are correctly reflected.

e.g. I did 'id_token token' with "implicit" and that worked just fine

**Comment by panva** [comment]
1) Go to https://tranquil-reef-95185.herokuapp.com/setup
2) select hybrid (it uses "code id_token" too)
3) authenticate

Works fine.

Are you just suspending the container or stop and starting it?

**Comment by jpreese** [comment]
Ok I didn't know about that setup app, and that pretty much confirms the configuration I have is correct. Which was an uncertainty on my part. Now that I know the configuration is correct, its just got to be something on my end or else this would be a much bigger problem.

I'll continue playing around with things on my end, so feel free to close. Thanks!
