### ISSUE TITLE
Persistent authorizations after logout

### ISSUE THREAD

**Issue by mraiur** [panva/node-oidc-provider#421]
Is there a way to keep user authorizations after logout. 
I am using mongo adapter and i see the authorizations are stored in user authorizations object.
One logout method removes only the authorization and the other destroys the session completely. 

My question is if there is a way to store the granted authorization for example in the user record and not in the session ?

**Comment by panva** [comment]
As you do your interactions, e.g. login & consent screen, just store the grants on your own terms, then when the user re-surfaces you can skip asking for consents he gave before and just concat them with the results.

Note that some consents like offline_access should never be persisted and that you should always ask for all permissions for public clients (native apps, SPAs).

You may also provide your own `interactionCheck` helper, but be sure to only change what you need.

This isn't really straight forward but if you take the time to understand what's configurable and understand the consenquences of your changes, ought to be fine.
