### ISSUE TITLE
invalid client error when secret contains + character

### ISSUE THREAD

**Issue by chungath** [panva/node-oidc-provider#422]
**Describe the bug**
If there is symbol + in client secret, it will cause client authentication failed, the detail error information is 'invalid secret provided'.

**To Reproduce**
Provider and Client configuration: (inline or gist)
```js
// provider configuration
// normal provider configuration

// keystore(s) - if they affect the behaviour
// normal provider configuration

// client(s) configuration
{
  client_id: a4f13611-c393-4a21-adde-f8c2176c30c2,
  client_secret: 5Q7UtUI6IMFsxLr9J+xicImeXVbuXQFIssDjJIf2oUNQrPCyL1K0KlLb3c1GjWnC
 .
 .
 .
}
```

Steps to reproduce the behaviour:

1.  Dynamic register a client, and make sure there is character + in the client_secret field of registration response. Or you can use a inmemory client with client_id is foo, client_secret is foo+bar.
2.  Send authentication request to RP(Login) with upon client_id.
3.  An invalid_client error will be occurred.

**Expected behaviour**
OP should be able to authenticate the client, even there is a character + in client's client_secret field.

**Environment:**
 - oidc-provider version: [5.0.0]
 - node version: [8.11.3]

**Additional context**
This issue is related to https://github.com/panva/node-oidc-provider/issues/361. 

I understand that the change is as per the RFC expecting the client to formEncode the client id and secret. The corresponding change went in node-oidc-client 2.2.1 verion - https://github.com/panva/node-openid-client/blob/v2.2.1/lib/client.js#L864-L868 .

However, many of our apps are using an earlier version of node-oidc-client and hence they will stop working if the client secret contains the '+' character.

Is there a way in which we can make oidc-provider support both the versions of node-oidc-client(Before 2.2.1 and After 2.2.1)?

At the end of the day all the apps will move to the new version of node-oidc-client, but until that happens we need a way to support the earlier version too.

**Comment by panva** [comment]
As stated many times before, this is not a bug.

> Is there a way in which we can make oidc-provider support both the versions of node-oidc-client

Not out of the box, if the client doesn't support conform `client_secret_basic` then you may switch it to use other methods instead.

Alternatively, this code snippet has been sent to me. If or whether it supports both ways i don't know, i won't waste time investigating.


```js
function encodeBasicAuth(clientId, clientSecret) {
  return Buffer.from(`${clientId}:${encodeURIComponent(clientSecret)}`).toString('base64');
}

/**
 * This middleware ensures backwards compatibility to accept client_secret_basic client authz
 * from the old times when the client_secret wasn't properly uri encoded first.
 * Since the OP issues client_secret of 48 random bytes encoded in base64
 * we can only check for + and / character and if those are present in the base64 decoded
 * basic authz we need to re-encode.
 *
 * @see https://github.com/panva/node-oidc-provider/issues/361
 * @see https://github.com/panva/node-openid-client/releases/tag/v2.0.1
 */
function createClientSecretBasicCompatibilityMiddleware() {
  return async function clientSecretBasicCompatibilityMiddleware(ctx, next) {
    if (!ctx.headers.authorization) {
      await next();
      return;
    }

    // client_secret_basic
    const parts = ctx.headers.authorization.split(' ');
    if (parts.length !== 2 || parts[0] !== 'Basic') {
      await next();
      return;
    }

    const basic = Buffer.from(parts[1], 'base64').toString('utf8');

    // is any of the two unencoded characters present in the base64-decoded auth string?
    if (basic.indexOf('+') === -1 && basic.indexOf('/') === -1) {
      await next();
      return;
    }

    const i = basic.indexOf(':');

    if (i === -1) {
      await next();
      return;
    }

    const clientId = basic.slice(0, i);
    const clientSecret = basic.slice(i + 1);

    ctx.headers.authorization = `Basic ${encodeBasicAuth(clientId, clientSecret)}`;

    await next();
  };
}

module.exports = {
  createClientSecretBasicCompatibilityMiddleware,
};
```

**Comment by chungath** [comment]
Thanks, I will try out this middleware.....
