### ISSUE TITLE
Support `code id_token` without requiring `implicit`

### ISSUE THREAD

**Issue by davidgtonge** [panva/node-oidc-provider#424]
**Is your feature request related to a problem? Please describe.**
The OAuth WG is advising implementers not to use implicit mode, however the response type of `code id_token` currently requires oidc-provider to be have implicit mode enabled. 

**Describe the solution you'd like**
I think the specs aren't entirely clear on this, but I'd like the option to support `code id_token` without enabling `implicit`.

**Describe alternatives you've considered**
Everything works at the moment, so this could be left. But I think it may introduce confusion.

 - [x] i have searched the configuration section for this feature and couldn't find it
 - [x] i have searched the issues tracker on github for similar requests and couldn't find anything related.

**Comment by panva** [comment]
Hi @davidgtonge,

are you referring to the client's `grant_types` registration metadata property?

https://openid.net/specs/openid-connect-registration-1_0.html#ClientMetadata specifies the list of required values in that array for each of the response_type values. Having "implicit" in that list doesn't mean the client will be able to execute `response_type=token`, the `response_types` property will still be the one checked during authorization request validation.

**Comment by davidgtonge** [comment]
Ah, I hadn't check the dynamic registration spec.

And checking the [discovery spec](https://openid.net/specs/openid-connect-discovery-1_0.html) it says:

> Dynamic OpenID Providers MUST support the authorization_code and implicit Grant Type values and MAY support other Grant Types.

I'll close this :-(
