### ISSUE TITLE
Why every endpoint are in http

### ISSUE THREAD

**Issue by sandybemonkey** [panva/node-oidc-provider#426]
I using the dicovery path and i just saw that every endpoint are in http beside the fact my issuer is in https, is there some config that i'm missed?

**Comment by panva** [comment]
Hi @sandybemonkey 

> is there some config that i missed?
yes, a common one when setting up any kind of service behind a TLS offloading proxy

- https://github.com/panva/node-oidc-provider/wiki/FAQ#why-does-my-well-knownopenid-configuration-link-to-http-endpoints-instead-of-https-endpoints
- https://github.com/panva/node-oidc-provider/blob/v5.5.1/docs/configuration.md#trusting-tls-offloading-proxies
