### ISSUE TITLE
question: force reauthentication with new tabs

### ISSUE THREAD

**Issue by spruce-bruce** [panva/node-oidc-provider#427]
I have a use case where my users will be using my app on shared computers. I'm using session storage in my app to keep track of id tokens so that when a user closes a tab that id token is discarded. I'd like to force a user to reauthenticate when they open a new tab, but when I send my user to the oidc-provider login interaction the session cookie is still set (unless they've closed the browser completely) and they're logged in and sent right back to my app.

Right now my plan is to implement and use the password grant and just manage the login interaction in my app, but I'm curious if this use case is supported already and I'm just missing something, or if you'd be interested in supporting that use case if not.

I'm still on 2.18.2 ( :( ), but I can't find how I'd do this with the updated versions either

I started playing with this several months ago and posted a related question here: https://github.com/panva/node-oidc-provider/issues/331

Also kudos to you again and again for this! I really appreciate how diligently you respond here and how actively you maintain this repo

**Comment by panva** [comment]
Hi @spruce-bruce 

> I'd like to force a user to reauthenticate when they open a new tab.

That's not possible.

> if you'd be interested in supporting that use case if not.

It's not on my radar. I wanna flesh out some of the quirks around ephemeral sessions but that's about it.

The answers from #331 still hold today.

> Also kudos to you again and again for this! I really appreciate how diligently you respond here and how actively you maintain this repo.

Thank you.

> Right now my plan is to implement and use the password grant and just manage the login interaction in my app.

Maybe you don't need OIDC at all then?

**Comment by panva** [comment]
To be frank with what's coming v6.x i don't even think you could have tokens without a session, as the token's validity will be bound to the session being present.

That being said maybe you just need login and then you should use `response_type=id_token`, because then you might as well just not store sessions at all (in your adapter you just don't save them) and that gives you what you want.

The moment you include other tokens tho (code, access token), this won't work.
