### ISSUE TITLE
How to close the application when running AdapterTest from jest

### ISSUE THREAD

**Issue by lourenzo** [panva/node-oidc-provider#428]
Hello,

I have implemented my own RedisAdapter, and I'm using jest on the project containing it, but it keeps open handles that break jest from closing it's process, with the following message:

```
Jest did not exit one second after the test run has completed.

This usually means that there are asynchronous operations that weren't stopped in your tests. Consider running Jest with `--detectOpenHandles` to troubleshoot this issue.
```
(But using the option `--detectOpenHandles` only hides the message but the process still stuck...)

How can I sanitize/finish the instance so jest can quit when done testing?

I already have tried reassigning the variable, but still getting the same;

My test file below:
```js
const Provider = require('oidc-provider');
const RedisAdapter = require('./RedisAdapter');
const keystore = require('../../config/keystore.json');

const { AdapterTest } = Provider;

describe('RedisAdapter', () => {
  /**
   * OIDC-Provider contains a bundled AdapterTest which we can reuse.
   */
  test('AdapterTest', async () => {
    const provider = new Provider('http://localhost', {
      features: { devInteractions: false },
      cookies: { keys: ['winspector', 'sharivan'] },
    });

    const adapterTest = new AdapterTest(provider);
    await provider.initialize({
      adapter: RedisAdapter,
      keystore,
    });

    await adapterTest.execute();
  });
});
```

**Comment by panva** [comment]
Hi @lourenzo, the adapter class is your code, so implement a close method you’ll call yourself?

Same as you’d call during graceful shutdown.

**Comment by lourenzo** [comment]
Yes, it makes sense. Thanks.
