### ISSUE TITLE
Question: The `opaque` token format

### ISSUE THREAD

**Issue by acappella2017** [panva/node-oidc-provider#429]
We are considering move to the new `opaque` token format in our project. But I still have some questions regarding to the new format...Could you help to take a look?

- I know that the new `opaque` token makes analysing the data easier. Is there any other improvements by using the new token type? Performance improvement?  

- The `legacy` token is composed of a random jti and a 64 byte random signature:
${jti}-${signature}, and in introspection phrase, odic-provider validates both parts.
In the meanwhile,  the `opaque ` token is the ${jti} itself. Are these 2 kinds of tokens with different length in the same safety level? 

- With the `opaque` token type, the storage adapter will need to find the token in database with the whole token string.  Some database write the query string into log, which may cause the token content be exposed in database log. Do you have any suggestion about this issue?

- When will the `legacy` format be removed from oidc-provider? The next major release (6.*) ?

**Comment by panva** [comment]
Hi @acappella2017,



> I know that the new `opaque` token makes analysing the data easier. Is there any other improvements by using the new token type? Performance improvement?

There's less serialization so in theory, yes, performance, but it's not noticeable.

> The legacy token is composed of a random jti and a 64 byte random signature:
${jti}-${signature}, and in introspection phrase, odic-provider validates both parts.
In the meanwhile, the opaque token is the ${jti} itself. Are these 2 kinds of tokens with different length in the same safety level?

The legacy was kept that long for "legacy" format reasons, nothing else really. The `opaque` format token lengths are [adequate](https://github.com/panva/node-oidc-provider/blob/v5.5.2/lib/models/formats/opaque.js#L12-L27) their application.

> With the opaque token type, the storage adapter will need to find the token in database with the whole token string. Some database write the query string into log, which may cause the token content be exposed in database log. Do you have any suggestion about this issue?

Regular primary index covered queries in logs, really? I find that strange and very unlikely to be the case in a production mode of any proper database engine. In any case, if you want you may do whatever you want with the find argument before you store and retrieve your documents, so you might as well hash it. But i'd rather go with the route of not logging every query ;)

> When will the legacy format be removed from oidc-provider? The next major release (6.*) ?

Yes. It's [gone](https://github.com/panva/node-oidc-provider/issues/429).
