### ISSUE TITLE
Support third party social login with the help of passport.js

### ISSUE THREAD

**Issue by mackwan84** [panva/node-oidc-provider#432]
**Is your feature request related to a problem? Please describe.**
Any example about third party social login such as Github, Facebook or Twitter

**Describe the solution you'd like**
We can extend the authorize action by passing acr_values=idp:github, acr_values=idp:facebook to the /auth endpoint to start third party social login.

**Comment by panva** [comment]
> Any example about third party social login such as Github, Facebook or Twitter

I have none. Unfortunately don't have the bandwidth to code examples for every single framework out there.

> Support third party social login with the help of passport.js

This is not related to the library, interactions can be anything you want. You can develop interactions independently of the provider.

> We can extend the authorize action by passing acr_values=idp:github, acr_values=idp:facebook to the /auth endpoint to start third party social login.

acr values parameter and its values are already available in interactions, you can simple handle them the way you like.

**Comment by mackwan84** [comment]
For more, it is possible to open source the codes of the demo website https://tranquil-reef-95185.herokuapp.com for us to learn more about? Thank you very much.

**Comment by panva** [comment]
> For more, it is possible to open source the codes of the demo website tranquil-reef-95185.herokuapp.com for us to learn more about? Thank you very much.

It used to be part of the openid-client repo as an example use but i ultimately removed it because many developers took it for "how to" which it wasnt. I'm not going to expose it as the openid-client documentation just lists all the public API and how to use it.
