### ISSUE TITLE
question - readme.md - session[authorizationRequestState] howto

### ISSUE THREAD

**Issue by robertparts** [panva/node-oidc-provider#435]
Hi, and apologies in advance for a newbie question.

There is https://github.com/panva/node-openid-client#processing-callback
session[authorizationRequestState] at first line - how can i get them?

Thanks in advance.

**Comment by panva** [comment]
Hi @robertparts 

this doesn't belong here and neither is a github issue tracker a place to start learning about the protocols and their use.

Sry.
