### ISSUE TITLE
Sample program for server initiated flow

### ISSUE THREAD

**Issue by Saranya0721** [panva/node-oidc-provider#437]
Hi Team,

What will be end point to hit back channel authentication flow. Can you share sample code if possible.

**Comment by panva** [comment]
Hi @SaranyaCute 

> What will be end point to hit back channel authentication flow

Can you elaborate in OIDC/OAuth2.0 terms?

**Comment by Saranya0721** [comment]
In OIDC terms. As per this document , https://openid.net/specs/openid-connect-modrna-client-initiated-backchannel-authentication-1_0.html#rfc.section.4 , it's says to bc-authorize with request body. But there is no such end point in oidc-provider

**Comment by Saranya0721** [comment]
> Hi @SaranyaCute
> 
> > What will be end point to hit back channel authentication flow
> 
> Can you elaborate in OIDC/OAuth2.0 terms?
In OIDC terms. As per this document , https://openid.net/specs/openid-connect-modrna-client-initiated-backchannel-authentication-1_0.html#rfc.section.4 , it's says to bc-authorize with request body. But there is no such end point in oidc-provider

**Comment by Saranya0721** [comment]
> > Hi @SaranyaCute
> > > What will be end point to hit back channel authentication flow
> > 
> > 
> > Can you elaborate in OIDC/OAuth2.0 terms?
> > In OIDC terms. As per this document , https://openid.net/specs/openid-connect-modrna-client-initiated-backchannel-authentication-1_0.html#rfc.section.4 , it's says to bc-authorize with request body. But there is no such end point in oidc-provider

**Comment by panva** [comment]
As you can see at the very start of the README CIBA is not amongst the supported specifications.
