### ISSUE TITLE
Getting ClientID before interactionFinished()

### ISSUE THREAD

**Issue by jpreese** [panva/node-oidc-provider#439]
Some of the metadata that we want to pass to interactionFinished requires the clientId of the client that initiated the flow (so that we can do some lookups based on the client, and allow said data to be introspected). However, it seems like all of the examples and issues on here are always after interactionFinished() triggers. 

Is there a way to get the clientId before hand so we can have this client-specific data returned from the introspection endpoint?

Bit of a silly example, but to show client-specific requirement for introspection
```
nameResult = await getClientName(clientId) // how to get clientId at this point?
await Provider.interactionFinished(req, res, { 
login: { ... }, 
meta: {
  clientName: nameResult
}
```

**Comment by panva** [comment]
Hi @jpreese

How is this related to interaction? I’m afraid I don’t follow.

**Comment by jpreese** [comment]
Sorry if it wasn't entirely clear, panva.

From what I can tell, the login{} and meta{} objects that are passed into Provider.interactionFinished() are the data that are returned when making a call to introspection.

We're trying to base some metadata off of the clientId, but are having some struggles getting the clientId before interactionFinished() is called. The context object seems empty. Session looks to be saved after the interaction is called.

Is there a way to get the clientId before interactionFinished is called? Or even a way to set what is returned from an introspection call afterward?

The context is ultimately that we have some data that is tied to each of the users of our clients. So when a client sends a request to the introspection endpoint, we want to be able to return that client-specific data from the introspection endpoint.

**Comment by panva** [comment]
Hi @jpreese 

Thanks for the context. I think you're going about it the wrong way.

> From what I can tell, the login{} and meta{} objects that are passed into Provider.interactionFinished() are the data that are returned when making a call to introspection.

That is not the case. The `login` object properties are cherry picked and assigned to a Session object, session object is used to resolve authorization, authorization then cherry picks information to the token, that's then available in introspection and used to form the response. `meta` object properties are echoed into the client's authorization namespace in the Session object and never used for anything by the provider. These are available for you to use during `interactionCheck` (soon to be history with [changes from v6.x](https://github.com/panva/node-oidc-provider/issues/419))

> We're trying to base some metadata off of the clientId, but are having some struggles getting the clientId before interactionFinished() is called.

Here's my disconnect, why is interaction involved in your thought process at all? If the additional response properties are based off the client_id alone why don't you just register a [post-middleware](https://github.com/panva/node-oidc-provider/blob/master/docs/configuration.md#pre--and-post-middlewares). The client will be available in `ctx.oidc.client`

> Is there a way to get the clientId before interactionFinished is called

Even to this there's an answer and [an example](https://github.com/panva/node-oidc-provider/blob/master/example/routes/koa.js#L30-L31). This again will have different API in v6.x, but I digress.

> So when a client sends a request to the introspection endpoint, we want to be able to return that client-specific data from the introspection endpoint.

Unless I'm missing something you've got the details above.

**Comment by jpreese** [comment]
Thanks for the detailed response, panva! I think that gets us a little bit further.
