### ISSUE TITLE
Retrieve registered client list

### ISSUE THREAD

**Issue by kmorizur** [panva/node-oidc-provider#441]
Hi panva,

First of all thank you for this great oidc provider. 

I'm trying to implement webview to list all the registered clients and also to be able to edit / delete each of them. I found the registration route that retrieves details of one client given its id and associated token but I'm wondering what is the best approach to retrieve all of them ?

Thanks for your answer.

**Comment by panva** [comment]
Hi @kmorizur, that would be to list them out of your adapter.

**Comment by kmorizur** [comment]
You mean each time a new client is added using the POST /registration I store in a dedicated table the client access info (client name + access url + token ) in order to access them later ?

**Comment by panva** [comment]
You already have that table - registration access tokens, you have the value of the token, the client id and from that easily the pattern for client registration uri.

**Comment by kmorizur** [comment]
How can I access this regsitration acces token table from provider ? I didn't find any route for it

**Comment by panva** [comment]
It's your storage the provider stores data in, how you access that storage OOB for other purposes is not of any concern to the provider. Ergo, you're asking me how to access your own db :)

**Comment by kmorizur** [comment]
ok I see thanks for your answer
