### ISSUE TITLE
token based authentication

### ISSUE THREAD

**Issue by David-hod** [panva/node-oidc-provider#443]
currently when user is signed in (on interactions) we need to store a session cookie for his signin.
when user is already logged in, we don't need to authenticate him again.
Do you think that on v6 it would be possible to do a token based authentication?

**Comment by panva** [comment]
HOW you resolve your interactions is up to you. IIRC nothing should forbid you from doing that, i've e.g. had interactions that just bounced the user through a page that requested a client certificate and then immediately resolved.

**Comment by David-hod** [comment]
actually there is a problem. 
today the framework skips on the interactions if all rules are passed. one of the rules is to check if user is signed in. 
the framework checks if user is signed in or not based on a cookie session. I would like that on v6 it would would be based on encryption and tokens.

**Comment by panva** [comment]
The provider has many more needs for a cookie then just to find out the logged in user, sorry I will not be entertaining this idea.

**Comment by panva** [comment]
Also, the check for logged in user in a cookie is done in a call to which you redirect the user. No way you can regularly expect a token to be part of the request.

**Comment by David-hod** [comment]
I mean,  using a cookie to store a token on client. 
checking if user is authenticated is by validating the token from that cookie.

**Comment by stavros-wb** [comment]
@David-hod I think you can achieve what you describe by implementing this check on a custom `interactionCheck`. So even if the library completes all of its checks successfully, you still get to handle the user if the token validation fails
