### ISSUE TITLE
invalid request - missing parameter nonce

### ISSUE THREAD

**Issue by DarkSorrow** [panva/node-oidc-provider#444]
**Describe the bug**
I created a small server and try to send a request to the auth endpoint using
http://localhost:3000/auth?client_id=CloudService&response_type=id_token+token&scope=openid&redirect_uri=http%3A%2F%2Flocalhost%3A4000%2Fauthentified

the localhost:3000 is the oidc-provider, i didn't put a nonce and the loading page request doesnt end. My browser keeps waiting for the request to complete like the end is not sent

**To Reproduce**
Provider and Client configuration: (inline or gist)
I'm using the exemple provider and trying to make some request with another "receiving server"

Steps to reproduce the behaviour:

1.  open browser with http://localhost:3000/auth?client_id=3DCloud&response_type=id_token+token&scope=openid&redirect_uri=http%3A%2F%2Flocalhost%3A4000%2Fauthentified
Output on the debug server: 

**Expected behaviour**
The request should end after the error and not continue to run

**Environment:**
 - oidc-provider version: 6
 - node version: 11

**Logs**
```
application is listening on port 3000, check its /.well-known/openid-configuration
  oidc-provider:authentication:error uid=W_6vCAfVngxQ0nGKSpstb { error: 'invalid_request', error_description: 'missing required parameter(s) (nonce)' } +0ms
```here -->

**Comment by panva** [comment]
Hi @DarkSorrow,

The logs show that the request ended with the expected errror, can you elaborate on the behaviour some more?

The way i see it the request should 302 to the client with invalid_request

**Comment by DarkSorrow** [comment]
Yes i think you are right, the thing is i kept getting a invalid_grant with my request being
I'm using this at the moment: https://oidcdebugger.com/debug

the client is
```
{
    client_id: '3DCloud',
    client_secret: '3DCloud',
    grant_types: ['refresh_token', 'authorization_code'],
    redirect_uris: ['http://localhost:4000/code',  'https://oidcdebugger.com/debug'],
  } 
```
I changed it because my localhost is having strange behaviour somehow. The thing is i run the first debug on this interface with code only that gives a query that looks like this

```
http://localhost:3000/auth
?client_id=3DCloud
&redirect_uri=https://oidcdebugger.com/debug
&scope=openid
&response_type=code
&response_mode=form_post
&nonce=zsmzwhb3ioi
```
This works well and i received the code but when i try to query the token endpoint with a post, using postman this time i get the invalid_grant error. The query is like that

```
POST {tokenEndpoint}
Content-Type: application/x-www-form-urlencoded
 
grant_type=authorization_code&
code=uwM6y6wjP9NrjI8-1ZU0_-WQgz6e74XieHPbOzXuUCc&
client_id=3DCloud&
client_secret={clientSecret}&
redirect_uri=https%3A%2F%2Foidcdebugger.com%2Fdebug
```

I made sure to pass the client id and secret in the basic auth format. I tried to move it to the body as shown in the above link but i had the error saying i wasn't allowed to do that which from the documentation i read is what is exepected. But for the request i'm not sure what i'm suppose to add, here is the log as well. I found it strange that the client_id is seen as undefined as well as client secret even tho i suppose it wouldn't be good to log this info, also i do see in the detail that it says uri_mismatch but the request_uri is the same as the one i passed before

 ```
 oidc-provider:authentication:success uid=9MQAntxvXTacG5yd-YNKv { code: '2C__Qe4nR_1qq4dfd_wEFFdy4jkYWi1s_stdr2SN1pP', session_state: '0c52b6590da94369c35004be9b85a85e5d2a52c7934175b31b58dcc491d416f6' } +2h
  oidc-provider:token accepted uid=nnR5oihSH-GLvjxAFZNG0 Params { grant_type: 'authorization_code', code: '2C__Qe4nR_1qq4dfd_wEFFdy4jkYWi1s_stdr2SN1pP', redirect_uri: 'https%3A%2F%2Foidcdebugger.com%2Fdebug', code_verifier: undefined, client_id: undefined, client_assertion: undefined, client_assertion_type: undefined, client_secret: undefined } +2h
  oidc-provider:uid switched from uid=nnR5oihSH-GLvjxAFZNG0 to value of grantId=Qk8qkqCZsUxHXgjRPVsji +2h
  oidc-provider:error uid=Qk8qkqCZsUxHXgjRPVsji path=/token method=POST error={ error: 'invalid_grant', error_description: 'grant request is invalid' } detail=authorization code redirect_uri mismatch +2h
```

Well i'm not sure if i should put that in another error, or if it's not me doing something wrong. It's related to me trying to code some simple flow at the moment to try to get a token before trying to display different login page. I read about oauth mostly before and saw oidc after. I was checking both this provider and ory/hydra but i feel more at ease using node and having the possibility of overriding the adaptator.
Anyway i wanted to say great work too so far it seems really nicely coded and easy to use, it's just me that have some problem i think understanding some flow and how to configure i think :/

**Comment by panva** [comment]
IIRC these debuggers don’t default to the right client token endpoint authentication method. Providing both post and basic auth is also forbidden. If these tools provide post, just configure their client on the provider with the right token_endpoint_auth_method

At this point i think it’s just about configuring right or using a certified client that does things by the book.

**Comment by DarkSorrow** [comment]
Okay when i read a bit more, even tho i passed an array in lib\actions\grants\authorization_code.js at line  61 the "code.redirectUri" just gives me the first url. so it seems the other url are not being checked. I'm not sure if its suppose to be this way or not but shouldn't it be an array?

**Comment by panva** [comment]
Code is stored with the one uri that was used during the authorization call
