### ISSUE TITLE
Dynamic TTL doesn't change

### ISSUE THREAD

**Issue by SurienDG** [panva/node-oidc-provider#446]
**Describe the bug**
I'm currently using the default in memory adapter. When I set the configure as set for ttl as shown below and then make a request to introspection endpoint for accessToken and refresh token currently get the original ttls. It doesn't seem to change.

I looked at #366  but this doesn't seem to be resolved and I'm not sure the other one is related since he was talking about sessions. 

**To Reproduce**

```js
alwaysIssueRefresh: true,
ttl: {
            AccessToken: 1, // 1 second
            AuthorizationCode: 1, // 1 second
            IdToken: 1, // 1 second
            DeviceCode: 1, // 1 second
           RefreshToken: 1, // 1 second

        },
```

Steps to reproduce the behaviour:

1.  Use the default in memory adapter provided with oidc provider

2.  configure the ttl 
3.  request for client access token using pkce
4. make a request to introspection endpoint for the refresh token and access token (their expiry times still seem to be the defaults)

**Expected behaviour**
Expiry times of the access token should change when updating ttl

 - [x] the bug is happening on latest oidc-provider too.
 - [x] i have tried DEBUG (see README) and can see the issue is with the provider and not my code.
 - [x] i have searched the issues tracker on github for similar issues and couldn't find anything related.
 - [x] i have searched the [FAQ](https://github.com/panva/node-oidc-provider/wiki/FAQ) and couldn't find anything related.

**Comment by panva** [comment]
Hi @SurienDG,

I'm not able to confirm this so you'll have to elaborate and provide concrete reproduction steps.

See my test:

Set all `ttl` options to `15` with the default in-memory adapter, works fine, see below `exp === iat + 15` on both refresh and access token introspection.

<img width="464" alt="Screenshot 2019-04-01 17 08 58" src="https://user-images.githubusercontent.com/241506/55338370-e4b3cd00-54a0-11e9-8d4e-959f93d3b35c.png">

**Comment by SurienDG** [comment]
Nevermind I figured out my issue. I accidentally put the ttl configuration inside the features enclosing.

Thank you so much for your help.

**Comment by panva** [comment]
> Might be a good idea to not have the warning just be that you are using an experimental feature if you are setting something incorrectly that is not a feature.

Ideally using invalid options would err completely. I have some configuration option validations prepared in v6.x (now on master) but it's not really this, it's a step forward nontheless.
