### ISSUE TITLE
Question or error with standalone exemple

### ISSUE THREAD

**Issue by DarkSorrow** [panva/node-oidc-provider#448]
I'm trying to use the standalone version provided in example but each time the login screen gets loaded it seems to load the login.js that is internally present in oidc. This one doesn't make a post to the interaction/uid/login but interaction.uid and goes directly to the consent mode at the moment.

**To Reproduce**
Load the provider in standalone mode and go on the auth endpoing with a client.
It redirects you to the prompt for login then just bypass the itneraction check and post on interaction/uid which validate the user and gives him the consent screen

// provider configuration
Provider from exemple

// keystore(s) - if they affect the behaviour
memory development

// client(s) configuration
Clients in exemple file

**Expected behaviour**

**Environment:**
 - oidc-provider version: latest

**Additional context**
Windows environment

I'm not sure if it's a bug or not but i'm thinking that if someone is getting redirected on the login prompt and change the url to make a login check with just the interaction/{uid} later won't that validate a login as well and allow him to pass to the consent screen with wrong data?
Or is it just because i should have changed something else in the standalone exemple for it to work? Do i have to use the koa creation project instead if i want to use my own templates?

**Comment by panva** [comment]
> but each time the login screen gets loaded it seems to load the login.js that is internally present in oidc

Please elaborate, i can't action on "seems to", the standalone.js examples loads routes from example/routes/koa which uses ejs templates from example/views.

- Did you copy those?
- Do you have devInteractions disabled?

> I'm not sure if it's a bug or not but i'm thinking that if someone is getting redirected on the login prompt and change the url to make a login check with just the interaction/{uid} later won't that validate a login as well and allow him to pass to the consent screen with wrong data?
Or is it just because i should have changed something else in the standalone exemple for it to work? Do i have to use the koa creation project instead if i want to use my own templates?

I can't parse this to make heads or tail out of it, sorry. It does not seem related.

**Comment by DarkSorrow** [comment]
Okay my bad the devinteraction was turned to true so it was getting the login.js from default interaction.
I'm stupid :D
