### ISSUE TITLE
[Question] How to rotate keys in keystore

### ISSUE THREAD

**Issue by SurienDG** [panva/node-oidc-provider#449]
In your documentation you say you can just move the keys in your keystore and add the generated new keys to end. You then say after you do this you should refresh all processes. How do I get the provider to use the new keystore? Do I have to reinitialize it?

Also, is the only way to get the provider to sign with another key in the keystore to move the keys around?

**Comment by panva** [comment]
@SurienDG yes it is the only way. 

The key selection process isn't that straight forward as "take the first key in the list". But rather, given two keys have the same JWK members other than the key material, the one at the beginning of the set will be picked up.

**Comment by SurienDG** [comment]
Ah I see but how do I modify the keystore object so that the provider instance will use a different key, Do I have to remove the old provider instance and create a new one?
