### ISSUE TITLE
Event names are not up to date

### ISSUE THREAD

**Issue by SurienDG** [panva/node-oidc-provider#450]
I was looking [here](https://github.com/panva/node-oidc-provider/blob/HEAD/docs/events.md ) (https://github.com/panva/node-oidc-provider/blob/HEAD/docs/events.md) to find out what events were emitted

When I tried them I didn't get any response so I searched your project for them  and they never get emitted (Ex. access_token.destroyed is not a valid event anymore)

I however managed to find the ones I needed by searching the project but could you please update it. Thanks

**Comment by panva** [comment]
master points to v6.x alpha already.

**Comment by SurienDG** [comment]
Thanks
