### ISSUE TITLE
Documentation: Dead "available configuration" link

### ISSUE THREAD

**Issue by nomad3k** [panva/node-oidc-provider#451]
**Describe the bug**
The "available configuration" link in https://www.npmjs.com/package/oidc-provider#configuration-and-initialization is throwing 404.

**To Reproduce**

1. Visit https://www.npmjs.com/package/oidc-provider#configuration-and-initialization 
1. Click "available configuration"
1. Look at jedi picture

**Expected behaviour**
Link to docs.

**Environment:**
github

**Additional context**

 - [n/a] the bug is happening on latest oidc-provider too.
 - [n/a] i have tried DEBUG (see README) and can see the issue is with the provider and not my code.
 - [X] i have searched the issues tracker on github for similar issues and couldn't find anything related.
 - [X] i have searched the [FAQ](https://github.com/panva/node-oidc-provider/wiki/FAQ) and couldn't find anything related.

**Logs**
n/a

**Comment by panva** [comment]
Well i ain't publishing a version on npm just to fix a link. This will sorted once v6.x hits the `latest` tag on npm.

**Comment by panva** [comment]
Anyway, I've added the old file with a link to the v5.x configuration.
