### ISSUE TITLE
Expiry date while logging out is not validated.

### ISSUE THREAD

**Issue by codestorycooked** [panva/node-oidc-provider#452]
**Describe the bug**

To log out a user from APP or from another registered client, the API https://MYSERVER/session/end is invoked. That API has a parameter id_token_hint which expects a signed, unencrypted JWT. MYSERVER properly verifies the JWT signature and does not accept tokens with algorithm none. However, the expiration date is not checked. 

oidc-version 5.0.3

**Comment by panva** [comment]
ID Tokens are typically very short-lived, not spanning the lifetime of neither OP or RP sessions, with that this behaviour is expected.
