### ISSUE TITLE
Scope/Claims re-validation

### ISSUE THREAD

**Issue by stavros-wb** [panva/node-oidc-provider#453]
**Describe the bug**
No revalidation occurs of scopes for existing session

**To Reproduce**
Steps to reproduce the behaviour:

setup, client A can request scopes: a, c but not b or d
1.  Signin with a client requesting a, b, c
2.  Reject scope b and provide tokens for scopes a and c
3.  Do another signin and request scopes a, c and d
4. OIDC Provider checks to reject only the already rejected scopes
https://github.com/panva/node-oidc-provider/blob/master/lib/helpers/oidc_context.js#L125
and not if the request contains new scopes/claims

**Expected behaviour**
This can be manually handled in `interactionCheck` by something like:
```javascript
  const oldScopes = new Set([
    ...session.rejectedScopesFor(client_id),
    ...session.promptedScopesFor(client_id)
  ]);
  const newScopes = new Set(scope.split(' '));

  return difference(Array.from(newScopes), Array.from(oldScopes));
```

Should this be handled by default?

**Comment by panva** [comment]
Hi @stavros-wb you need to be way more descriptive of the issue. E.g. version, your interactionCheck configuration, etc

If you could provide detailed steps to reproduce using the bundled example of a specific version it'd be great. Until then i'm afraid I'm not convinced there's an action item for me.

**Comment by panva** [comment]
Or is the issue not re-requesting already rejected scopes? That’s intended behaviour by default that you must conciously change and define behaviour for.

**Comment by stavros-wb** [comment]
hello @panva the issue is about requesting scopes (that should be rejected) that you haven't requested the 1st time that client was authorized. So when there's already a session and you request new scopes there's not validation by default.

**Comment by panva** [comment]
Ok, still not getting it, please provide steps to reproduce using the bundled example of either v6.0.0 alpha or v5.5.5 oidc-provider versions. Thank you.

**Comment by stavros-wb** [comment]
Reproduced in master with config:
```
(master) $ git diff
diff --git a/example/koa.js b/example/koa.js
index 9cfa9cd..8c52fe3 100644
--- a/example/koa.js
+++ b/example/koa.js
@@ -26,8 +26,8 @@ render(app, {
   root: path.join(__dirname, 'views'),
 });

+app.keys = providerConfiguration.cookies.keys;
 if (process.env.NODE_ENV === 'production') {
-  app.keys = providerConfiguration.cookies.keys;
   app.proxy = true;
   set(providerConfiguration, 'cookies.short.secure', true);
   set(providerConfiguration, 'cookies.long.secure', true);
diff --git a/example/routes/koa.js b/example/routes/koa.js
index 261df29..aae80c5 100644
--- a/example/routes/koa.js
+++ b/example/routes/koa.js
@@ -81,6 +81,8 @@ module.exports = (provider) => {

   router.post('/interaction/:uid/login', body, async (ctx) => {
     const account = await Account.findByLogin(ctx.request.body.login);
+    const forbiddenScopes = ['email', 'profile'];
+    const interaction = await provider.interactionDetails(ctx.req);

     const result = {
       login: {
@@ -89,6 +91,9 @@ module.exports = (provider) => {
         amr: ['pwd'],
         ts: Math.floor(Date.now() / 1000),
       },
+      consent: {
+        rejectedScopes: interaction.params.scope.split(' ').filter(s => forbiddenScopes.includes(s))
+      }
     };

     return provider.interactionFinished(ctx.req, ctx.res, result, {
diff --git a/example/support/configuration.js b/example/support/configuration.js
index 548a85f..bfcda08 100644
--- a/example/support/configuration.js
+++ b/example/support/configuration.js
@@ -82,12 +82,13 @@ module.exports.provider = Object.assign({
 }, HEROKU_EXAMPLE_CONFIGURATION);

 module.exports.clients = [
-  // {
-  //   client_id: 'oidcCLIENT',
-  //   client_secret: '...',
-  //   grant_types: ['refresh_token', 'authorization_code'],
-  //   redirect_uris: ['http://sso-client.dev/providers/7/open_id', 'http://sso-client.dev/providers/8/open_id'],
-  // }
+  {
+    client_id: 'oidcCLIENT',
+    client_secret: 'deadbeef',
+    grant_types: ['implicit'],
+    response_types: ['id_token token'],
+    redirect_uris: ['https://sso-client.dev/providers/7/open_id']
+  }
 ];
```
#### 1st interaction
• http://localhost:5002/auth?client_id=oidcCLIENT&response_type=id_token token&nonce=deadbeef&scope=openid profile phone&redirect_uri=https://sso-client.dev/providers/7/open_id
• signin
• consent
• id_token={"sub":"fii","nonce":"deadbeef","at_hash":"55soTScW6PEAZ7QBW-5i6w","aud":"oidcCLIENT","exp":1555419812,"iat":1555416212,"iss":"http://localhost:5002"}
  access_token={"urn:oidc-provider:example:foo":"bar","jti":"HQ1Ne3zd5AwzPJmtv9q_v","sub":"fii","iat":1555416212,"exp":1555419812,"scope":"openid phone","iss":"http://localhost:5002","aud":"oidcCLIENT"}

#### 2nd interaction
• http://localhost:5002/auth?client_id=oidcCLIENT&response_type=id_token token&nonce=deadbeef&scope=openid email phone&redirect_uri=https://sso-client.dev/providers/7/open_id
• consent
• id_token={"sub":"fii","nonce":"deadbeef","at_hash":"1HVielLahO0r5h6-Et7w1g","aud":"oidcCLIENT","exp":1555419928,"iat":1555416328,"iss":"http://localhost:5002"}
  access_token={"urn:oidc-provider:example:foo":"bar","jti":"bksXz-etpoBdHjuFyk4xz","sub":"fii","iat":1555416328,"exp":1555419928,"scope":"openid email phone","iss":"http://localhost:5002","aud":"oidcCLIENT"}

On the second pass a new scope is requested `email` but the scopes don't get revalidated. https://github.com/panva/node-oidc-provider/blob/master/lib/helpers/oidc_context.js#L125 only checks that rejected scopes (i.e. `profile`) is not granted, but grants all the rest of the scopes by default. 

I'm wondering if the scopes should get revalidated against the `session.promptedScopes` in this case

**Comment by panva** [comment]
`revalidated` - what do you mean? The scopes have already been granted for that client in that session

**Comment by stavros-wb** [comment]
exactly, but when incrementing authorization, revalidation is needed. 
e.g. not all clients can get the same user claims/scopes. Same with access tokens as well. Scoping a token is about making it less _powerful_, when a client tries to get a more _powerful_ token, revalidation is needed.
the workaround is manually checking on `interactionCheck`, but I thought of opening an issue and checking if a `hook` would be better for this.

**Comment by panva** [comment]
Incrementing is asking for additional, when i run your example i get prompted for the missing **additional** scope `email` as expected, it gets rejected by consent and the resulting token still only has `openid phone`. `phone` has already been granted hence no point in asking for it again.

This default behaviour i'm happy with as-is, rejections are in v6.x additive so after having both `profile` and `email` rejected but prompted the next time any of the two requests is ran no interaction happens since its not incremental any more.

**Comment by panva** [comment]
If you wish to completely ignore previously given consents that's fine and modifying `interactionCheck` (v5.x) or replacing the `scopes_missing`/`claims_missing` checks (v6.x) is the way to do it.
