### ISSUE TITLE
Flexible scope check

### ISSUE THREAD

**Issue by acappella2017** [panva/node-oidc-provider#454]
We are working on customized scopes support in our product. We are planing to allow admin register resource provider in our oidc server, which means admin can register a set of APIs in oidc server, and group them with customized scopes. Since admin may frequently add/remove scopes, we don't want to restart oidc server every time the scopes are changed.

We noticed that oidc-provider has the `dynamicScopes` feature, we are able to pass a set of regrex to oidc-provider so that oidc-provider can check scopes with it.

But since the customized scope names are arbitrary, it is hard to check it with regrex. Looks like it is meaningless if we set the regrex to someghing like `[/^d_\d+$/]`. It doesn't do any real check.

We are wondering whether there is a way to support more flexible scope check?  For example, if there is a way to hook a `checkScope` function into oidc provider, then we can store the customized scopes in database, and check it in the hooked function to make sure the requested scope is really an admin-registered scope.

**Comment by panva** [comment]
Hi @acappella2017,

`dynamicScopes` are really meant for something else, not applicable to your use-case. 

> Since admin may frequently add/remove scopes, we don't want to restart oidc server every time the scopes are changed.

I don't see a problem with that and it is the only way to make new scopes and their scope-to-claim mapping available.

**Comment by acappella2017** [comment]
@panva Thanks for your quick response!

> `dynamicScopes` are really meant for something else, not applicable to your use-case.
We may have some misunderstanding of `dynamicScopes` feature, could you give some instruction of the suitable use case?  

> > Since admin may frequently add/remove scopes, we don't want to restart oidc server every time the scopes are changed.
> 
> I don't see a problem with that and it is the only way to make new scopes and their scope-to-claim mapping available.

Could you give some suggest about how to do scope check in this case?

**Comment by panva** [comment]
> We may have some misunderstanding of `dynamicScopes` feature, could you give some instruction of the suitable use case?

Dynamic scopes are for enabling scopes that contain e.g. the resource identifier as part of the scope. For instance `api:users:read:4WBnu4U`, `4WBnu4U` being the dynamic part.

> Could you give some suggest about how to do scope check in this case? Looks like we can't add dynamic scopes to oidc-provider without enabling the `dynamicScopes` feature..

No you can't use `dynamicScopes` for your case, it doesn't apply based on your description. What i'm saying is that I don't see a problem with just reconfiguring and restarting the server. 

1) I doubt this happens frequently
2) You're likely running multiple processes on multiple hosts, so a rolling restart will make it so that new configuration is available rather quickly and the service will not be unreachable.

**Comment by acappella2017** [comment]
In our case, the scope change may happen frequetly...Restarting server causes some problems to us. e.g. All our memory caches will be lost. And we will have to wait for all the current request to be processed before we can restart the server, so it will need some time to restart.

Is it possible to support passing a function in `dynamicScopes` config, so that oidc-provider can use the function to check scope?

**Comment by panva** [comment]
No it is not. There's more internal configuration and mapping derived from the configuration than just available scopes, e.g. scope to claim mapping, client to scope whitelists, etc.

As I said `dynamicScopes` do not apply to you and restart with new configuration is the only available way, no plans to implement and maintain more than that.
