### ISSUE TITLE
[Question] How to reload oidc-provider when configuration change?

### ISSUE THREAD

**Issue by sunpeinju** [panva/node-oidc-provider#456]
@panva 
I searched some history issues and found the solution you suggest is to restart the process with the updated new config. My question here is could we create a new oidc-provider instance to replace old one within the same process? Maybe uses some logic like below:

```
// stop origin Koa server
server.stop();

// create a new provider instance
const newProvider = new Provider(ISSUER, updatedConfiguration);
newProvider.initialize(...);

// mount to a new Koa and start to listening to port
```

I want to avoid restarting the whole process, which means we need to implement / leverage a separate scheduler process, and need to re-initialize everything.

**Comment by panva** [comment]
Personally I’ve been hot swapping server callbacks for years now. That has however nothing to do with oidc-provider and you’ll have to figure out if it fits or not on your own.

The process goes as follows. 

- disconnect the worker from a pool
- wait for all requests to finish
- disconnect keep alives
- change node server’s request handler
- connect back to the pool

**Comment by sunpeinju** [comment]
@panva Thanks.
As long as two provider instances won't impact each other, application can response to take care the flow you described.
