### ISSUE TITLE
Need to implement password grant type with response type as id_token,token and refresh token.

### ISSUE THREAD

**Issue by testruntry** [panva/node-oidc-provider#457]
**Is your feature request related to a problem? Please describe.**
A clear and concise description of what the problem is.

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

 - [ ] i have searched the configuration section for this feature and couldn't find it
 - [ ] i have searched the issues tracker on github for similar requests and couldn't find anything related.

**Comment by testruntry** [comment]
const express = require('express');
const Provider = require('oidc-provider');

const app = express();
const clients = [{
   client_id: "test_oauth_app",
   client_secret: "super_secret",
   grant_types: [''],
   response_types: [],
   redirect_uris: []
  
}];
const oidc = new Provider('http://localhost:7004',{
//console.log("HII");
claims: {
        email: ['email', 'email_verified'],
        phone: ['phone_number', 'phone_number_verified'],
        profile: ['birthdate', 'family_name', 'gender', 'given_name', 'locale', 'middle_name', 'name', 'nickname', 'picture', 'preferred_username', 'profile', 'updated_at', 'website', 'zoneinfo']
    },
scopes: ["openid"],

features: {
        clientCredentials: true,
		//password: true,
        introspection: true
    },
async findById(ctx, id) {
        return {
            accountId: id,
            async claims() { return { sub: id }; },
        };
    }


});
oidc.registerGrantType('password')

oidc.initialize({clients}).then(function () {
 app.use('/', oidc.callback);
app.listen(7004);
});

**Comment by panva** [comment]
Please. Put some effort into understanding the framework before asking for help.

**Comment by testruntry** [comment]
I have shared the basic code structure irrespective of the grant type, hence kept few fields in clients[] blank after trying . Client credential is working fine for me. Need to add the custom grant so seeked for your help.

**Comment by panva** [comment]
https://github.com/panva/node-oidc-provider/blob/v5.x/docs/configuration.md#custom-grant-types

That’s as far as i’m gonna go. Trying to get a flawed ROPC going goes against every best current practice.

**Comment by testruntry** [comment]
Thanks for the prompt response.

**Comment by testruntry** [comment]
Also, require to authenticate the username and password with AD for ROPC .

**Comment by panva** [comment]
That would be your own implementation you need to put in.

**Comment by testruntry** [comment]
@panva 
while trying for grant_types: ["authorization_code","implicit"] and response_types :["code","id_token","token"] as per the spec **https://openid.net/specs/openid-connect-registration-1_0.html#ClientMetadata.**
Getting the error as : InvalidClientMetadata: invalid_client_metadata

Any corrections required ?

**Comment by panva** [comment]
Why don’t you read the error description.

**Comment by testruntry** [comment]
error_description: 'response_types can only contain members [**code id_token token**,code id_token,code token,code,id_token token,id_token,none]'

Response type that I passed is one of the required ones.

**Comment by panva** [comment]
Response types are not individual tokens, they are the string as-is.

**Comment by testruntry** [comment]
Can you please elaborate what corrections are needed . As I am a beginner to this module.

**Comment by panva** [comment]
Just pass ‘code id_token token’ as one string. While you may be beginner to this module it is expected you understand OIDC before asking for help. This is not the place to get “how do i oidc” support.

**Comment by testruntry** [comment]
Worked :) 
for the following cURL command , curl -X POST \
  http://localhost:3000/token \
  -H 'authorization: Basic dGVzdF9vYXV0aF9hcHA6c3VwZXJfc2VjcmV0' \
  -H 'cache-control: no-cache' \
  -H 'content-type: application/x-www-form-urlencoded' \
  -H 'postman-token: 758e716d-c766-8019-8afb-f3a811d7bba0' \
  -d 'grant_type=authorization_code&scope=openid%20&code=68498567-4623-4d80-a1c2-27f5bbc2c087&redirect_uri=https%3A%2F%2Ftestapp%2Fsignin-oidc'

getting {
    "error": "invalid_grant",
    "error_description": "grant request is invalid"
}

**Comment by panva** [comment]
68498567-4623-4d80-a1c2-27f5bbc2c087 is definitely not an authorization code.

This now goes beyond my capacity for support. You’re not really making an effort.
