### ISSUE TITLE
While registering the new grant type as in the docs above, I get the following error on custom grant_types can only contain members [implicit,authorization_code,refresh_token]

### ISSUE THREAD

**Issue by testruntry** [panva/node-oidc-provider#458]
While registering the new grant type(Password)  as in the docs above, I get the following error on startup grant_types can only contain members [implicit,authorization_code,refresh_token]

**Comment by panva** [comment]
1) instantiate
2) register grant type
3) initialize with clients.

**Comment by testruntry** [comment]
It worked fine! 

Able to generate Access Token , but failing in the case of IdToken for password grand.

**Comment by testruntry** [comment]
How to generate Idtoken in password grant , as there are no claims , acr . amr which is present in authorization_code. And which parameters will be used to sign the token?

**Comment by panva** [comment]
You can see how it's done in the [other built in grants](https://github.com/panva/node-oidc-provider/tree/master/lib/actions/grants).

**Comment by testruntry** [comment]
For eg. Authorization_code while generating Idtoken, it is done through acr, amr, clamis.(code.acr , code.amr)  Currently in password grant none is present.  Below is code , suggest the required changes: 

const token = new IdToken({
	scope: 'openid',
	//acr: at.acr,
        //amr: at.amr,
        auth_time: at.authTime,
	},ctx.oidc.client);
		
	token.set('at_hash', accessToken);
	const idToken = await token.sign();
	console.log("idToken::" + idToken)

-

**Comment by panva** [comment]
> suggest the required changes

If they're not present, don't set them. You're in an uncharted, unsupported, non-interoperable and bad practice space. I'm not going to spend any more time with password grant types.

Please refrain from using this tracker as means for getting help for it.
