### ISSUE TITLE
Revoke access_token and refresh_token

### ISSUE THREAD

**Issue by codestorycooked** [panva/node-oidc-provider#459]
We want to revoke `access_token` and `refresh_token` on endSession. ( we know this is not how it works. It client responsibility to call revocation endpoint) But we want to do it as it is our security requirement. 
To achieve this what we are trying to do is to find `sid` when ` end_session.success` is emitted and delete  (trying) `access_token` and `refresh_token` corresponding to `sid`. 

```
 this.oidc.on('end_session.success', function (ctx) {
            const sid = ctx.oidc.session.sidFor(ctx.oidc.client.clientId);
            // Delete logic 
        });
```
So the question : 
Is this right way to do it? 
Is there any api/method we can use to revoke access_token and refresh_token directly instead of custom logic to delete it? 

Others:
Mongdb adapter 
node-oidc version 5.3.0

Thanks a lot.

**Comment by panva** [comment]
> Is this right way to do it?

Yes. But i fear that 
1) ctx.oidc.client may not always be there, you need to handle those cases.
2) i think `sidFor` in this case will not return anything because the authorization's object client_id specific namespace is already removed.

> Is there any api/method we can use to revoke access_token and refresh_token directly instead of custom logic to delete it?

No.

**Comment by codestorycooked** [comment]
Thanks.
`sidFor` returns `sid` which is common for `access_token`  &  `refresh_token`. I was planning to delete these tokens based on `sid`. 

Is revoking of `access_token` and `refresh_token` be automatic in v6.x? If yes then we may have this temp solution for now as I described and will get away with it once v6.x is stable. 

Thanks for your inputs

**Comment by panva** [comment]
> Is revoking of access_token and refresh_token be automatic in v6.x?

yes, for all tokens that are not marked as session-independent (i.e. offline_access)
