### ISSUE TITLE
How does this lib sign jwt token with alg HS256?

### ISSUE THREAD

**Issue by yelexin** [panva/node-oidc-provider#460]
@panva Thanks for reading this. I have spent a whole night trying to figure out how the jwt token is signed with HS256.
```json

{
    "access_token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJqdGkiOiJLUnRjZkh4aEFXRGllQnpZdXc2aTciLCJzdWIiOiI1Y2MzMmIyOGQ2ZWJhZTJmMjQwYTliZmQiLCJpc3MiOiJodHRwczovL29hdXRoLmF1dGhpbmcuY24vb2F1dGgvb2lkYyIsImlhdCI6MTU1NjMzMDE1MywiZXhwIjoxNTU2MzMzNzUzLCJzY29wZSI6Im9wZW5pZCBwcm9maWxlIG9mZmxpbmVfYWNjZXNzIHBob25lIGVtYWlsIiwiYXVkIjoiNWNjMzJhMTQyMmNlZWFmYWRjZGE5ZTY2In0.ovILpYno0e-YX_qxQdssPjg_BPG4UMib8lkYONvv9U4",
    "expires_in": 3600,
    "id_token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI1Y2MzMmIyOGQ2ZWJhZTJmMjQwYTliZmQiLCJub25jZSI6IjIyMTIxIiwiYXRfaGFzaCI6Inl0dVdaNHZNUUctVzRMMlRQcUdIWVEiLCJzaWQiOiJiMjNiZDQxMy1kMGEyLTQ1Y2EtODYyZS1iMTU4NWFjNGY5OWIiLCJhdWQiOiI1Y2MzMmExNDIyY2VlYWZhZGNkYTllNjYiLCJleHAiOjE1NTYzMzM3NTMsImlhdCI6MTU1NjMzMDE1MywiaXNzIjoiaHR0cHM6Ly9vYXV0aC5hdXRoaW5nLmNuL29hdXRoL29pZGMifQ.6AJ7U2hXbrF6ybjawKRnpG6U8Vl89yaTRgVPU62-tdM",
    "refresh_token": "zQp3s_0BagRz3Wi2IFSZ~IpuQye",
    "scope": "openid profile offline_access phone email",
    "token_type": "Bearer"
}

```

What I want to do is verify the id_token returned from the server(The id_token is signed with HS256). But I have to know how it is signed and with which secret key.
I have read this issue #186 
I also provided the clientmeta jwks described in the specification in mongodb.

![image](https://user-images.githubusercontent.com/27125445/56843570-f5efce00-68d4-11e9-87c1-8f5ec72eef64.png)

I tried to calculate the signature here but it says mismatch.(with the key: P6_bTAMzObUeZNXw3sbG6TuXGwcirqXr6dnjQqSxe7Y)
https://jwt.io/

Please give me some hints. Thanks so much.

**Comment by yelexin** [comment]
I have figured it out. It is the client_secret that is used as key to sign the jwt.

**Comment by panva** [comment]
Yup, per the specification.
