### ISSUE TITLE
Additional claims in the return JWT token

### ISSUE THREAD

**Issue by chakwok** [panva/node-oidc-provider#461]
Hi Filip,

Thanks for providing this library :)

**What I'm trying to achieve**
I am trying to include two extra parameters, namely role and locale, in the return tokens (id, access and refresh token).

I have developed a working implementation of OP that can login and return the tokens accordingly. However, whenever I try to request extra claims, the /auth endpoint won't redirect to the proper login page anymore, returning a status code (302)

**What I've tried**
Attempting to return additional parameters e.g. role, I have done:

1. Enable feature.claimsParameter (see item 3 for code)
2. Add role under claims
3. Override findById function
`const config = {
  features:{ 
    claimsParameter: true,
  },
  claims: {
   acr: null,
   sid: null,
   auth_time: null,
   iss: null,
   openid: [ 'sub' ],
   role: ['role']
  },
  findById: async function(ctx, sub, token) {
    return {
      accountId: sub,
      claims: async function(use, scope, claims, rejected) {
        return {sub: sub, 
                    role: //accessing the db and return value};
      }
    }
  }`

4. Adding claim=role in the request URL
/auth?grant_type=authorization_code&client_id=foo&scope=openid&access_type=offline&response_type=code%20id_token&nonce=03692593648327125&claim=role

I have also looked into similar issues here (e.g. #113), but it doesn't help. Can you please help?

Andy

**Comment by panva** [comment]
4. is not using the “claims” (not claim!) parameter right. 

https://openid.net/specs/openid-connect-core-1_0.html#ClaimsParameter

**Comment by chakwok** [comment]
@panva  Thanks for your prompt reply. 

Sorry for copying the wrong query. I am already using "&claims=role" in the parameter list, but it returns status 302 response when I reach the /auth endpoint. 

p.s. using "claim=role" actually does not return any error, just as expected, and the return tokens do not contain any additional parameters

**Comment by panva** [comment]
Again, you are using the parameter “claims” wrong. Please see the specification on its format and usage. There is no parameter “claim” which is why the request goes through - it’s unrecognized and hence ignored.

**Comment by chakwok** [comment]
I totally overlooked that. Thank you so much
