### ISSUE TITLE
Cannot set grant and session cookies to be secure

### ISSUE THREAD

**Issue by nataliahering** [panva/node-oidc-provider#463]
In an application using koa, we are updating the oidc configuration in order to make the cookies secure:
```
cookies: {
    long: {
      signed: true,
      secure: true
    },
    short: {
      signed: true,
      secure: true
    },
...
```
Based on this https://github.com/panva/node-oidc-provider/tree/master/docs#trusting-tls-offloading-proxies we are also setting the provider proxy to be true.
The `x-forwarded-proto` in the header is set to `https`.

The grant and session cookies are still not secure. We do create a custom cookie, which does get created as secure. 

Is there any other configuration missing in order to make the cookies secure?

Thanks in advance.

**Comment by panva** [comment]
@nataliahering can you share the request / response with set-cookie headers?

**Comment by nataliahering** [comment]
After investigating further we were failing to set the secure cookies due to an unrelated deployment issue. Updating the config cookies settings is enough to make it work. Thanks!
