### ISSUE TITLE
Question : State Prameter

### ISSUE THREAD

**Issue by codestorycooked** [panva/node-oidc-provider#465]
Hi @panva, In any of the flow where `state` parameter is being sent, should we delete them (whatever mechanism is being used a cookie or local storage) after successful or failed login attempt? 

Thanks
Kunal

**Comment by HMaxDesign** [comment]
Hi @codestorycooked, I try an answer to this one. Regarding to corresponding RFC state is there to ensure a link between a specific autorization request and the corresponding callback. In essence this state is scoped to one request/callback. State should be deleted after callback, but it may have been build with persistent data such as a visitId or a sessionId or whatever distinguish two of your application user. Hope this helps.

**Comment by panva** [comment]
This belongs on stackoverflow, not a library **issue** tracker.
