### ISSUE TITLE
sub missing in id_token when dynamicScopes are used

### ISSUE THREAD

**Issue by ayZagen** [panva/node-oidc-provider#466]
**Describe the bug**
Setting dynamicScopes to `/.*/` -which means accept all scopes- makes sub excluded from id_token. However sub in id_token is a must according to [OpenId Specification ](https://openid.net/specs/openid-connect-core-1_0.html#IDToken)

**To Reproduce**
set dynamicScopes to accept all as following:

```js
dynamicScopes: [ /.*/ ]

```

version: 6.0.0-alpha.6 (but i believe it is the same on v5)

**Comment by panva** [comment]
Well, are you requesting the openid scope in the request?

**Comment by ayZagen** [comment]
@panva Of course, this is the request:

URL:
http://localhost3000/oauth/auth

Query String Parameters:
client_id: test
redirect_uri: http://localhost:8080/callback
response_type: id_token token
scope: openid email
state: b0496cfedbbb49699ff15f9ee4d5092f
nonce: b1b53884cb37474aa4fd987d69bef2d1
audience: test-audience

**Comment by panva** [comment]
yeah, i've confirmed this.

**Comment by panva** [comment]
Thank you for the report.

**Comment by ayZagen** [comment]
Thanks for the great work you have done!
