### ISSUE TITLE
[v6.0.0-alpha6] Redis rejson example doesn't use keyPrefix

### ISSUE THREAD

**Issue by thomasvargiu** [panva/node-oidc-provider#467]
Hello @panva,

the redis rejson example doesn't use the keyPrefix with `JSON.SET` calls. I think you should prefix it manually.

**Comment by panva** [comment]
@thomasvargiu thank you for reporting this, can you suggest the change necessary please? I'm short on capacity these days.

**Comment by thomasvargiu** [comment]
I think you can keep it simple. You can avoid the use of the key prefix, and let developers implement it if they need it.
If you want to provide an example with the key prefix, you should prepend it to the key manually when using `JSON.SET()` and `JSON.GET()`.
I will open an PR when i'll not be busy (I'm very busy too these weeks).
