### ISSUE TITLE
access_token not found if consent is skipped

### ISSUE THREAD

**Issue by ayZagen** [panva/node-oidc-provider#468]
Hello,

I am trying to skip scope consent for first party applications. I have modified [scopes_missing consent check](https://github.com/panva/node-oidc-provider/blob/a3d078fde63447fb24180189ad62be10cb02e8ba/lib/helpers/interaction/prompts/consent/scopes_missing.js#L7) like this:

```js
  if (!ctx.isFirstParty) {
    for (const scope of oidc.requestParamScopes) {
      if (!promptedScopes.has(scope)) {
        return true;
      }
    }
  }
```
Everything seems OK until i make request to `userinfo` endpoint with the token provided from the provider. Provider seems couldn't find the token received and returns 401 obviously. If i remove that check it works. I have checked redis and I could see the token is stored there.

The same happens when I remove consent checks completely by commenting this line : [defaults](https://github.com/panva/node-oidc-provider/blob/a3d078fde63447fb24180189ad62be10cb02e8ba/lib/helpers/interaction/index.js#L39)
Using v6.0.0-alpha.6

Thanks

**Comment by panva** [comment]
Sounds familiar. Don’t skip consent ;), the lines in resume action related to consent are important. If you’re skipping consent those need to appear in you updated code somewhere. 

i’m actually working on this now so you’ll see an update with the next alpha release that addresses skipping the resume codepath.

**Comment by panva** [comment]
Please try with `npm i panva/node-oidc-provider#fix-468` and let me know.

**Comment by ayZagen** [comment]
2df0dce fixes it, thank you for your great work :)

**Comment by panva** [comment]
Was just a proposal, i still need to iron the thing out.

**Comment by ayZagen** [comment]
Do you predict lots of changes in the codebase ?

**Comment by panva** [comment]
yes.

**Comment by ayZagen** [comment]
can't wait to see it :)
