### ISSUE TITLE
Question: examples of node-oidc-provider + client on Docker?

### ISSUE THREAD

**Issue by mdbraber** [panva/node-oidc-provider#470]
Hi,

I'm using https://hub.docker.com/r/qlik/simple-oidc-provider which is both OIDC provider + client in one bundle - ideal to be used in an internal setting for lightweight testing / internal use. Unfortunately the QLIK source repo seems to be MIA. Are there any known similar builds available using node-oidc-provider + client in a single package?

Thanks!

**Comment by panva** [comment]
I don’t have such example. Maybe others do, i’ll leave this open for a few days maybe someone will turn up.

**Comment by mdbraber** [comment]
@panva thanks  for your reply! In the meantime I've been able to get what I needed working with https://github.com/dexidp/dex (with an even smaller memory footprint of 4MB). So I'll go ahead and close this issue for now!
