### ISSUE TITLE
Question: Changing default routing within oidc-provider

### ISSUE THREAD

**Issue by bob-sheknowdas** [panva/node-oidc-provider#472]
Hi,

I'm using a oidc-provider app in a docker cluster with traefik.
All requests with the url "/oidc-adapter" are supposed to go reach my oidc-provider app. That works great so far.

But... oidc-provider does a lot of internal routing towards the "/interaction"-url.
Is there any way for me to change that so the internal routing reaches "/oidc-adapter/interaction" instead of just "/interaction" ?

I tried simply overriting the interactionUrl(ctx)-function. But apparently, that wasn't the solution...

**Comment by panva** [comment]
If you could create a stripped down Dockerfile that i could replicate your issue I can help.

Without it tho my only question is if your `issuer` identifier value matches the root path. Essentially, when you visit your `/.well-known/openid-configuration` - does the `issuer` property value include `/oidc-adapter` at the end. If not, try it.

**Comment by bob-sheknowdas** [comment]
The openid-configuration is not the cause of my problem. Following the `/.well-known/openid-configuration`, my browser displays the desired endpoints.

I observed my traffic...
he first request send to my oidc-provider is a GET to the `/oidc-adapter/auth`-endpoint, which returns a 302 (seems to work, i'd say).
The second request is a GET to the `/interaction`-endpoint. It returns a 404 (as expected, since the `/oidc-adapter`-prefix is missing). This second request seems to be a redirection from within the oidc-provider app itself.

**Comment by panva** [comment]
> The openid-configuration is not the cause of my problem. Following the oicd-adapter/.well-known/openid-configuration-uri, my browser displays the desired endpoints.

That's not what I was asking, what is the `issuer` value returned by that document?

**Comment by bob-sheknowdas** [comment]
Oh, my fault. I am sorry for not reading propperly...

Ok, so I've experimented a little with the `issuer`. I've tried using just my base url, which is `issuer=bob.localhost`, as well as the base url + the oidc-provider-app-prefix, which would than be `issuer=bob.localhost/oidc-adapter`.

Both did not solve the problem. I get redirected to the same url...

Did I get ur question right this time?
Am I doing anything fundamentally wrong here?

**Comment by panva** [comment]
> Am I doing anything fundamentally wrong here?

Maybe, i still lack a way to reproduce.

> If you could create a stripped down Dockerfile or project gist that i could replicate your issue.

---

In any case - are you still using `devInteractions` or using your own?

**Comment by bob-sheknowdas** [comment]
> 
> In any case - are you still using `devInteractions` or using your own?

It seems, that was the problem.

So far I only had my own version of GET `/interaction/:grant` and POST `/interaction/:grant/login` but didnt set the `devInteractions=false`.

Having the `devInteractions=true` somehow overwrote my changes in `interactionUrl(ctx)`.
Now that I set them to `false`, my changes in `interactionUrl(ctx)` are recognized by the framework and everything works as expected.

Thanks a lot for your help.

**Comment by panva** [comment]
🎉
