### ISSUE TITLE
unrecognized route or not allowed method (GET ' + 'on /.well-known/oauth-authorization-server)?

### ISSUE THREAD

**Issue by tony-kerz** [panva/node-oidc-provider#473]
when i run an instance of provider and an instance of client,
when the client calls `Issuer.discover()`, i see the following in the output of the provider:
```
  oidc-provider:error uuid=undefined path=/.well-known/oauth-authorization-server method=GET error={ error: 'invalid_request', error_description: 'unrecognized route or not allowed method (GET ' + 'on /.well-known/oauth-authorization-server)' } detail=undefined +0ms
```
is this normal?

regards,
tony.

**Comment by panva** [comment]
Yes. The client is doing discovery on both well known endpoints - oidc and oauth
