### ISSUE TITLE
Ack for mtls check

### ISSUE THREAD

**Issue by thomasvargiu** [panva/node-oidc-provider#478]
Are these checks correct?

https://github.com/panva/node-oidc-provider/blob/4e1bb2f50f265c45bdb9d9f23d81d3b2ffac180c/lib/helpers/configuration.js#L424-L436

https://github.com/panva/node-oidc-provider/blob/4e1bb2f50f265c45bdb9d9f23d81d3b2ffac180c/lib/helpers/configuration.js#L438-L449

`tokenEndpointAuthMethods`, `revocationEndpointAuthMethods` and `introspectionEndpointAuthMethods` are arrays, how can exist an `ack` property?

The warning is: 

> 
> NOTICE: You may disable this notice and these potentially breaking updates by acknowledging the current draft version. See https://github.com/panva/node-oidc-provider/tree/master/docs/README.md#features
> 

and it's linking to the features configuration.

Should we add `tlsClientAuth` and `selfSignedTlsClientAuth` keys in features configuration?

**Comment by panva** [comment]
It is correct. When those values are present in the array and that array has an ack property the warning is muted.
