### ISSUE TITLE
invalid_token when calling /me endpoint with Authorization: Bearer <access_token>. Why? 

### ISSUE THREAD

**Issue by sarangshah-tudip** [panva/node-oidc-provider#479]
First i am calling /token to generate the access_token then i am using it to call /me endpoint and it is throwing me invalid_token error.

I am using oidc-provider 5.5.5 version. Please do let me know fix for this asap. Thanks in advance

**Comment by panva** [comment]
> Please do let me know fix for this asap

really?

This could be anything from your adapter not working right, to I don't know - not using the header correctly.

Please provide more details and logs using `DEBUG=oidc-provider:*`.

**Comment by sarangshah-tudip** [comment]
@panva sorry for saying you asap. I am really sorry for that.

Please find below the last logs i am getting after calling /me endpoint

`middleware pre GET /me
ctx  { authorization:
   'Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiIsImtpZCI6IlZUajZ6T0l1SlYzeHEzUXZGazY4c2Z1RGM4TjhlZWotbzVYMEZjTmtvZUkifQ.eyJhdWQiOiJoYXItdmEiLCJleHAiOjE1NjE3MzIwOTgsImlhdCI6MTU1OTMxMjg5OCwiaW50ZWdyaXR5IjoiMThjVUdJNkNjWFUiLCJpc3MiOiJodHRwczovLzM3NjEyZGJjLm5ncm9rLmlvIiwianRpIjoiWTY5VHJHTkdxTG9oa05LR3lkT3A1M3dLZUlBMElDa213V1FrZmRqSkZ6OCIsInN1YiI6MTAwMDU3MjkyOCwidG9rZW5fdHlwZSI6ImFjY2Vzc190b2tlbiIsImNsYWltcyI6eyJzdWIiOjEwMDA1NzI5MjgsImVtYWlsIjoiaGVhZGVuZHRlc3QxIiwibmFtZSI6Im51bGwgSEVBREVORCBURVNUSU5HIDEiLCJodHRwczovL3R2MmNvbnN1bHRpbmcuY29tL29wZXJhdG9yIjoiaGFyZ3JheSIsImh0dHBzOi8vdHYyY29uc3VsdGluZy5jb20vYWNjb3VudElkIjoiMjAwMDU4NTYxODIifX0.TJt6SoAVnaEB7XUV6fpob5UMvxY_jw4X9RoDEeYbNl7WrpWnfLX282oqV2YOpgtAuPxQNDSmDqa_EW3VYmXiKHeSfSJFuZ2-73zn8KO1CuXuPmsMK01TfwTUVBvpGT1UFv_Npb8kzEyyiT8QW9_pWAyXg3WLVX68m1QLSdcyxdAmtMVD2JHhtnyZ518-UNhI3VUxBSnPGG7-QMT4celPmJkhxF1BkLC1xOCsdegYgsAKN8SrTWWPt7XauRcEUN_2Ydk68cKuCmKO55n-v9JbWr8Cxl_3p-J3JKJIFdI16czbyDfHG4ln3d4VhPRDMyWv4SD9EWujNFlXYbyuVkjIDg',
  'cache-control': 'no-cache',
  'postman-token': 'd0b1eb76-3fc5-4f2c-9ea6-78c904085718',
  'user-agent': 'PostmanRuntime/7.3.0',
  accept: '*/*',
  host: '37612dbc.ngrok.io',
  'accept-encoding': 'gzip, deflate',
  'x-forwarded-proto': 'https',
  'x-forwarded-for': '103.204.119.234' }
find called for Y69TrGNGqLohkNKGydOp53wKeIA0ICkmwWQkfdjJFz8 on access_token
Found session {"_id":"Y69TrGNGqLohkNKGydOp53wKeIA0ICkmwWQkfdjJFz8","accountId":1000572928,"clientId":"har-va","expiresAt":"2019-06-28T14:28:19.066Z","header":"eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiIsImtpZCI6IlZUajZ6T0l1SlYzeHEzUXZGazY4c2Z1RGM4TjhlZWotbzVYMEZjTmtvZUkifQ","payload":"eyJhdWQiOiJoYXItdmEiLCJleHAiOjE1NjE3MzIwOTgsImlhdCI6MTU1OTMxMjg5OCwiaW50ZWdyaXR5IjoiMThjVUdJNkNjWFUiLCJpc3MiOiJodHRwczovLzM3NjEyZGJjLm5ncm9rLmlvIiwianRpIjoiWTY5VHJHTkdxTG9oa05LR3lkT3A1M3dLZUlBMElDa213V1FrZmRqSkZ6OCIsInN1YiI6MTAwMDU3MjkyOCwidG9rZW5fdHlwZSI6ImFjY2Vzc190b2tlbiIsImNsYWltcyI6eyJzdWIiOjEwMDA1NzI5MjgsImVtYWlsIjoiaGVhZGVuZHRlc3QxIiwibmFtZSI6Im51bGwgSEVBREVORCBURVNUSU5HIDEiLCJodHRwczovL3R2MmNvbnN1bHRpbmcuY29tL29wZXJhdG9yIjoiaGFyZ3JheSIsImh0dHBzOi8vdHYyY29uc3VsdGluZy5jb20vYWNjb3VudElkIjoiMjAwMDU4NTYxODIifX0","scope":null,"signature":"TJt6SoAVnaEB7XUV6fpob5UMvxY_jw4X9RoDEeYbNl7WrpWnfLX282oqV2YOpgtAuPxQNDSmDqa_EW3VYmXiKHeSfSJFuZ2-73zn8KO1CuXuPmsMK01TfwTUVBvpGT1UFv_Npb8kzEyyiT8QW9_pWAyXg3WLVX68m1QLSdcyxdAmtMVD2JHhtnyZ518-UNhI3VUxBSnPGG7-QMT4celPmJkhxF1BkLC1xOCsdegYgsAKN8SrTWWPt7XauRcEUN_2Ydk68cKuCmKO55n-v9JbWr8Cxl_3p-J3JKJIFdI16czbyDfHG4ln3d4VhPRDMyWv4SD9EWujNFlXYbyuVkjIDg"}`

I am calling below endpoint
`curl -X GET \
  'https://37612dbc.ngrok.io/me?scope=openid%20profile%20email' \
  -H 'Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiIsImtpZCI6IlZUajZ6T0l1SlYzeHEzUXZGazY4c2Z1RGM4TjhlZWotbzVYMEZjTmtvZUkifQ.eyJhdWQiOiJoYXItdmEiLCJleHAiOjE1NjE3MzIwOTgsImlhdCI6MTU1OTMxMjg5OCwiaW50ZWdyaXR5IjoiMThjVUdJNkNjWFUiLCJpc3MiOiJodHRwczovLzM3NjEyZGJjLm5ncm9rLmlvIiwianRpIjoiWTY5VHJHTkdxTG9oa05LR3lkT3A1M3dLZUlBMElDa213V1FrZmRqSkZ6OCIsInN1YiI6MTAwMDU3MjkyOCwidG9rZW5fdHlwZSI6ImFjY2Vzc190b2tlbiIsImNsYWltcyI6eyJzdWIiOjEwMDA1NzI5MjgsImVtYWlsIjoiaGVhZGVuZHRlc3QxIiwibmFtZSI6Im51bGwgSEVBREVORCBURVNUSU5HIDEiLCJodHRwczovL3R2MmNvbnN1bHRpbmcuY29tL29wZXJhdG9yIjoiaGFyZ3JheSIsImh0dHBzOi8vdHYyY29uc3VsdGluZy5jb20vYWNjb3VudElkIjoiMjAwMDU4NTYxODIifX0.TJt6SoAVnaEB7XUV6fpob5UMvxY_jw4X9RoDEeYbNl7WrpWnfLX282oqV2YOpgtAuPxQNDSmDqa_EW3VYmXiKHeSfSJFuZ2-73zn8KO1CuXuPmsMK01TfwTUVBvpGT1UFv_Npb8kzEyyiT8QW9_pWAyXg3WLVX68m1QLSdcyxdAmtMVD2JHhtnyZ518-UNhI3VUxBSnPGG7-QMT4celPmJkhxF1BkLC1xOCsdegYgsAKN8SrTWWPt7XauRcEUN_2Ydk68cKuCmKO55n-v9JbWr8Cxl_3p-J3JKJIFdI16czbyDfHG4ln3d4VhPRDMyWv4SD9EWujNFlXYbyuVkjIDg' \
  -H 'Postman-Token: a515aae8-a4e3-49a7-9cc8-e001f3b8cf93' \
  -H 'cache-control: no-cache'`

**Comment by panva** [comment]
This doesn't help run with `DEBUG=oidc-provider:*` or provider.on('userinfo.error', console.log) to log the errors with their details.

**Comment by sarangshah-tudip** [comment]
I added the above thing and please find the below logs

`mp-43$ node index.js DEBUG=oidc-provider:*
WARNING: configuration cookies.keys is missing, this option is critical to detect and ignore tampered cookies
(node:83080) DeprecationWarning: current URL string parser is deprecated, and will be removed in a future version. To use the new parser, pass option { useNewUrlParser: true } to MongoClient.connect.
middleware pre GET /me
ctx  { authorization:
   'Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiIsImtpZCI6IlZUajZ6T0l1SlYzeHEzUXZGazY4c2Z1RGM4TjhlZWotbzVYMEZjTmtvZUkifQ.eyJhdWQiOiJoYXItdmEiLCJleHAiOjE1NjE3MzIwOTgsImlhdCI6MTU1OTMxMjg5OCwiaW50ZWdyaXR5IjoiMThjVUdJNkNjWFUiLCJpc3MiOiJodHRwczovLzM3NjEyZGJjLm5ncm9rLmlvIiwianRpIjoiWTY5VHJHTkdxTG9oa05LR3lkT3A1M3dLZUlBMElDa213V1FrZmRqSkZ6OCIsInN1YiI6MTAwMDU3MjkyOCwidG9rZW5fdHlwZSI6ImFjY2Vzc190b2tlbiIsImNsYWltcyI6eyJzdWIiOjEwMDA1NzI5MjgsImVtYWlsIjoiaGVhZGVuZHRlc3QxIiwibmFtZSI6Im51bGwgSEVBREVORCBURVNUSU5HIDEiLCJodHRwczovL3R2MmNvbnN1bHRpbmcuY29tL29wZXJhdG9yIjoiaGFyZ3JheSIsImh0dHBzOi8vdHYyY29uc3VsdGluZy5jb20vYWNjb3VudElkIjoiMjAwMDU4NTYxODIifX0.TJt6SoAVnaEB7XUV6fpob5UMvxY_jw4X9RoDEeYbNl7WrpWnfLX282oqV2YOpgtAuPxQNDSmDqa_EW3VYmXiKHeSfSJFuZ2-73zn8KO1CuXuPmsMK01TfwTUVBvpGT1UFv_Npb8kzEyyiT8QW9_pWAyXg3WLVX68m1QLSdcyxdAmtMVD2JHhtnyZ518-UNhI3VUxBSnPGG7-QMT4celPmJkhxF1BkLC1xOCsdegYgsAKN8SrTWWPt7XauRcEUN_2Ydk68cKuCmKO55n-v9JbWr8Cxl_3p-J3JKJIFdI16czbyDfHG4ln3d4VhPRDMyWv4SD9EWujNFlXYbyuVkjIDg',
  'cache-control': 'no-cache',
  'postman-token': 'f4428544-16a9-4647-b3fd-15e13c8f5881',
  'user-agent': 'PostmanRuntime/7.3.0',
  accept: '*/*',
  host: '37612dbc.ngrok.io',
  'accept-encoding': 'gzip, deflate',
  'x-forwarded-proto': 'https',
  'x-forwarded-for': '103.204.119.234' }
find called for Y69TrGNGqLohkNKGydOp53wKeIA0ICkmwWQkfdjJFz8 on access_token
Found session {"_id":"Y69TrGNGqLohkNKGydOp53wKeIA0ICkmwWQkfdjJFz8","accountId":1000572928,"clientId":"har-va","expiresAt":"2019-06-28T14:28:19.066Z","header":"eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiIsImtpZCI6IlZUajZ6T0l1SlYzeHEzUXZGazY4c2Z1RGM4TjhlZWotbzVYMEZjTmtvZUkifQ","payload":"eyJhdWQiOiJoYXItdmEiLCJleHAiOjE1NjE3MzIwOTgsImlhdCI6MTU1OTMxMjg5OCwiaW50ZWdyaXR5IjoiMThjVUdJNkNjWFUiLCJpc3MiOiJodHRwczovLzM3NjEyZGJjLm5ncm9rLmlvIiwianRpIjoiWTY5VHJHTkdxTG9oa05LR3lkT3A1M3dLZUlBMElDa213V1FrZmRqSkZ6OCIsInN1YiI6MTAwMDU3MjkyOCwidG9rZW5fdHlwZSI6ImFjY2Vzc190b2tlbiIsImNsYWltcyI6eyJzdWIiOjEwMDA1NzI5MjgsImVtYWlsIjoiaGVhZGVuZHRlc3QxIiwibmFtZSI6Im51bGwgSEVBREVORCBURVNUSU5HIDEiLCJodHRwczovL3R2MmNvbnN1bHRpbmcuY29tL29wZXJhdG9yIjoiaGFyZ3JheSIsImh0dHBzOi8vdHYyY29uc3VsdGluZy5jb20vYWNjb3VudElkIjoiMjAwMDU4NTYxODIifX0","scope":null,"signature":"TJt6SoAVnaEB7XUV6fpob5UMvxY_jw4X9RoDEeYbNl7WrpWnfLX282oqV2YOpgtAuPxQNDSmDqa_EW3VYmXiKHeSfSJFuZ2-73zn8KO1CuXuPmsMK01TfwTUVBvpGT1UFv_Npb8kzEyyiT8QW9_pWAyXg3WLVX68m1QLSdcyxdAmtMVD2JHhtnyZ518-UNhI3VUxBSnPGG7-QMT4celPmJkhxF1BkLC1xOCsdegYgsAKN8SrTWWPt7XauRcEUN_2Ydk68cKuCmKO55n-v9JbWr8Cxl_3p-J3JKJIFdI16czbyDfHG4ln3d4VhPRDMyWv4SD9EWujNFlXYbyuVkjIDg"}
{ InvalidToken: invalid_token
    at validateBearer (/Users/mp-43/Downloads/Projects/TV2/oidc-server/node_modules/oidc-provider/lib/actions/userinfo.js:54:31)
    at process._tickCallback (internal/process/next_tick.js:68:7)
  name: 'InvalidToken',
  error: 'invalid_token',
  status: 401,
  statusCode: 401,
  expose: true,
  error_description: 'invalid token provided',
  error_detail: 'access token not found' } { request:
   { method: 'GET',
     url: '/me?scope=openid%20profile%20email',
     header:
      { authorization:
         'Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiIsImtpZCI6IlZUajZ6T0l1SlYzeHEzUXZGazY4c2Z1RGM4TjhlZWotbzVYMEZjTmtvZUkifQ.eyJhdWQiOiJoYXItdmEiLCJleHAiOjE1NjE3MzIwOTgsImlhdCI6MTU1OTMxMjg5OCwiaW50ZWdyaXR5IjoiMThjVUdJNkNjWFUiLCJpc3MiOiJodHRwczovLzM3NjEyZGJjLm5ncm9rLmlvIiwianRpIjoiWTY5VHJHTkdxTG9oa05LR3lkT3A1M3dLZUlBMElDa213V1FrZmRqSkZ6OCIsInN1YiI6MTAwMDU3MjkyOCwidG9rZW5fdHlwZSI6ImFjY2Vzc190b2tlbiIsImNsYWltcyI6eyJzdWIiOjEwMDA1NzI5MjgsImVtYWlsIjoiaGVhZGVuZHRlc3QxIiwibmFtZSI6Im51bGwgSEVBREVORCBURVNUSU5HIDEiLCJodHRwczovL3R2MmNvbnN1bHRpbmcuY29tL29wZXJhdG9yIjoiaGFyZ3JheSIsImh0dHBzOi8vdHYyY29uc3VsdGluZy5jb20vYWNjb3VudElkIjoiMjAwMDU4NTYxODIifX0.TJt6SoAVnaEB7XUV6fpob5UMvxY_jw4X9RoDEeYbNl7WrpWnfLX282oqV2YOpgtAuPxQNDSmDqa_EW3VYmXiKHeSfSJFuZ2-73zn8KO1CuXuPmsMK01TfwTUVBvpGT1UFv_Npb8kzEyyiT8QW9_pWAyXg3WLVX68m1QLSdcyxdAmtMVD2JHhtnyZ518-UNhI3VUxBSnPGG7-QMT4celPmJkhxF1BkLC1xOCsdegYgsAKN8SrTWWPt7XauRcEUN_2Ydk68cKuCmKO55n-v9JbWr8Cxl_3p-J3JKJIFdI16czbyDfHG4ln3d4VhPRDMyWv4SD9EWujNFlXYbyuVkjIDg',
        'cache-control': 'no-cache',
        'postman-token': 'f4428544-16a9-4647-b3fd-15e13c8f5881',
        'user-agent': 'PostmanRuntime/7.3.0',
        accept: '*/*',
        host: '37612dbc.ngrok.io',
        'accept-encoding': 'gzip, deflate',
        'x-forwarded-proto': 'https',
        'x-forwarded-for': '103.204.119.234' } },
  response:
   { status: 401,
     message: 'Unauthorized',
     header:
      [Object: null prototype] {
        'x-powered-by': 'Express',
        vary: 'Origin',
        pragma: 'no-cache',
        'cache-control': 'no-cache, no-store',
        'www-authenticate':
         'Bearer realm="https://37612dbc.ngrok.io", error="invalid_token", error_description="invalid token provided"',
        'content-type': 'application/json; charset=utf-8' } },
  app: { subdomainOffset: 2, proxy: true, env: 'production' },
  originalUrl: '/me?scope=openid%20profile%20email',
  req: '<original node req>',
  res: '<original node res>',
  socket: '<original node socket>' }
`

**Comment by panva** [comment]
```
{ InvalidToken: invalid_token
  error_description: 'invalid token provided',
  error_detail: 'access token not found' }
```

Debug your adapter.

**Comment by sarangshah-tudip** [comment]
Sorry i am new with this and in learning stage so might ask you silly questions. But Debug your adapter in the sense you want me to debug mongodb_adapter.js file. What exactly i should look at?
Thanks in advance

**Comment by panva** [comment]
I don't have the capacity for holding hands, the adapter you're using (whichever one it is) is not returning the documents as it should.

It could be you have an example adapter from master which won't work with 5.x, please retrace your steps and make sure you're pulling data from the right sources. If you want to make sure its the adapter and not anything else then remove the adapter configuration altogether to use the inmemory one, that'll confirm

**Comment by sarangshah-tudip** [comment]
Thanks for the help. Will retrace my steps.
