### ISSUE TITLE
question: on client enc key jwks?

### ISSUE THREAD

**Issue by thomasvargiu** [panva/node-oidc-provider#481]
Hi,

I'm not an expert on JWE, but I'm trying to register in client dynamic registration an `RSA-OAEP` encrypting key (in the `jwks` metadata), but the server returns `jwks must not contain private keys`. 
I saw that the check is based on the `d` key field. Probably it can be correct on signature keys (because the server doesn't need the sign key), but I also think that the server needs the whole encryption JWK for encryption. Am I right?

**Comment by panva** [comment]
@thomasvargiu JWE does public key based encryption so that the recipient's private key is used for decrypting. It's used for confidentiality. The check is correct and client's `jwks` / `jwks_uri` must not contain private key material, just like the provider's `jwks_uri` doesn't.

**Comment by panva** [comment]
good that you brought it up btw, i was missing the `oct` rejection.

**Comment by thomasvargiu** [comment]
@panva Thank you for your complete answer. I will do some other tests because I'm unable to decrypt the id_token, but it's probably a my issue.
