### ISSUE TITLE
Documentation to integrate with AOuth2

### ISSUE THREAD

**Issue by kmalakoff** [panva/node-oidc-provider#484]
Great library. I've started using the 6.alpha version and the interaction API is meeting my needs much better than the 5.x API. Great improvements!

I am looking to also issue OAuth2 tokens and provide a standards compliant server. I found the following issues: 

- https://github.com/panva/node-oidc-provider/issues/390
- https://github.com/panva/node-oidc-provider/issues/473

Would it be possible to have some documentation produced and maybe an example produced or recipe to demonstrate how to do the things you mentioned in 390: `note that oidc-provider will have its own sessions and you will have to provide an adapter for them as well as tokens and helpers to load the account details based on id`

I'm really not all that confident that this is very easy for someone new to oidc-provider like me. I'm thinking that showing the code hooks and APIs to do this in a single Node.js server would be super useful to the community.

**Comment by panva** [comment]
@kmalakoff would you be able to contribute a few paragraphs of explanation how the interactions in v6.x work? I myself am having a hard time coming up with something readable. 

Anyway, i’m not sure what examples you’d need but there are two linked in the readme, one bundled here in this repo one step by step linked outside.

The stuff you mention from 390 comes by default with an in memory adapter and all you can do is change the adapter.

I’m afraid i don’t have the capacity to do extensive examples, and i’m not even sure from your issue what is it that you’d like to see.

**Comment by kmalakoff** [comment]
Thank you for the quick response. I would be looking for documentation and support around things like:

- reuse or override the session and login for an OAuth2 interaction type
- reuse or override the token issuing and decrypting for an OAuth2 implementation
- an example for an endpoint for `/.well-known/oauth-authorization-server` that reuses some endpoints from the oidc provider as possible (such as token issuing and decrypting, starting an OAuth2 interaction, etc)
- etc

I'm not sure which examples you are specifically referencing related to these sorts of needs when exposing OAuth2 functionality from this provider. Maybe linking them in a response against each of them would help myself and others who might want to do this? As you can imagine, many people who need OIDC may also need OAuth2 support.

Where I'm coming from...I think someone from the outside like myself who is not an author of this library would find it difficult to know what can be shared between implementations, may run into hard limits in your APIs where changes might be required to for example support an OAuth2 interaction type (for example, the interactions in 5.x did not meet my needs and you've improved the API in 6.alpha), etc.

I understand you are busy and I am too as I'm in the process of launching a new business. Are you interested in supporting this type of request and keeping the issue open or am I on my own to try to figure this out?

**Comment by kmalakoff** [comment]
I've split out your documentation request into a separate issue: https://github.com/panva/node-oidc-provider/issues/485

**Comment by panva** [comment]
No just I quite frankly don’t understand what you find missing. The provider, And v6.x specifically allows regular oauth requests (without the openid scope) out of the box.

**Comment by panva** [comment]
I thought by improved API you mean the `interaction` configuration policy which is completely redone for v6.x. The actual interactions (what happens after policy says login / consent / whatever is needed) are the same between v5.x and v6.x, as in - you can do whatever you want / need. There's no "one" way to do it that would need documenting and the examples are just that, examples.

**Comment by panva** [comment]
> Are you interested in supporting this type of request and keeping the issue open or am I on my own to try to figure this out?

I'm not keeping "how to" issues open on principle, the tracker is meant for issues. I'm happy to answer questions when i have the capacity. If you'd like a more direct channel then please reach out via email and we can figure something out.

**Comment by panva** [comment]
exposing another well known is as simple as rewriting the url

```js
  provider.use((ctx, next) => {
    if (ctx.path !== '/.well-known/oauth-authorization-server') {
      return next();
    }

    ctx.path = '/.well-known/openid-configuration';
    return next().then(() => {
      ctx.path = '/.well-known/oauth-authorization-server';
    });
  });
```

> - reuse or override the session and login for an OAuth2 interaction type
> - reuse or override the token issuing and decrypting for an OAuth2 implementation

👆 these I don't follow. I have no idea what you mean by an interaction type or what you mean by an OAuth2 implementation. This is an OIDC compliant, ergo OAuth2.0 compliant server, it issues tokens, hands off when user interaction is needed based on a configurable policy, handles all basic authorization flows, albeit with or without an `openid` scope (in v6.x).

**Comment by kmalakoff** [comment]
> I'm not keeping "how to" issues open on principle, the tracker is meant for issues. I'm happy to answer questions when i have the capacity. If you'd like a more direct channel then please reach out via email and we can figure something out.

Makes sense. Maybe mentioning this policy around questions in your issue template would help the community understand your approach. The perception I had by looking at how many issues had only two interactions was that if a request didn't fit into your vision for the library, you preferred to shut down the discussion and leave it to the library consumer to figure it out. With this library being around such a complex standards topic, I was assuming detailed public discussions would be the norm so people could learn about the OIDC and OAuth2 specs plus the innards of this library to reduce repeat questions and to empower the community to solve their own problems based on public information.

Have you thought about creating some sort of public forum to discuss these things, eg. Slack channel or something else

**Comment by kmalakoff** [comment]
>This is an OIDC compliant, ergo OAuth2.0 compliant server, it issues tokens, hands off when user interaction is needed based on a configurable policy, handles all basic authorization flows, albeit with or without an openid scope (in v6.x).

This totally gets to the root of this request. Awesome!

The root of my question was whether this library was fully OAuth2 compliant given it didn't support the `./well-known/oauth-authorization-server` path and I had tried using OAuth2 on 5.x without an openid scope and it didn't seem to work for me (I only switched to 6.alpha this week and I could have configured 5.x incorrectly) so I was a bit confused about how an OIDC implementation built on OAuth2 would not be fully compliant. 

I'll play around with the OAuth2 only configuration and functionality and hopefully it will just work. Cheers!

**Comment by panva** [comment]
> The perception I had by looking at how many issues had only two interactions was that if a request didn't fit into your vision for the library, you preferred to shut down the discussion and leave it to the library consumer to figure it out.

I shut down discussions that are either completely against the best practice, are completely outside of the scope of the library or by first glance show the author did not bother to read the documentation.

I like to have the trackers clean and don't waste my time with what you described as "not my vision".

> public discussions

Public discussions have their place here, but I have yet to see one that's valid :)

> The root of my question was whether this library was fully OAuth2 compliant given it didn't support the `./well-known/oauth-authorization-server`

You don't need to support this route to be RFC8414 compliant. An SDK supporting discovery will likely check both routes (mine openid-client does).

I don't include the `oauth-authorization-server` by default because when mounted its not on a path directly after the issuer. The rules are different for 8414 and OIDC discovery. Given an issuer `https://op.panva.cz/foo` the expected paths for discovery are

- `/foo/.well-known/openid-configuration`
- `/.well-known/oauth-authorization-server/foo`

> 5.x without an openid scope and it didn't seem to work for me

[5.x does not support it](https://github.com/panva/node-oidc-provider/blob/master/CHANGELOG.md#600-alpha0-2019-03-23)

> I know it should sort of go without saying, but still sometimes it helps to make these things explicit.

I might reword some of the descriptions but to anyone familiar with at least the excerpt of OIDC knows its an extension of OAuth2.0, hence every OIDC server is an OAuth2.0 server.

**Comment by kmalakoff** [comment]
Good stuff! The 5.x not supporting OAuth2 seemed a bit contradictory to me also in terms of expectations for OIDC being built on OAuth2 so this super cool that 6.x supports the standard and expectations. Definitely highlight it as it is an critical change!

> I shut down discussions that are either completely against the best practice, are completely outside of the scope of the library or by first glance show the author did not bother to read the documentation.

I would be a little bit cautious of "best practices" in an open source library and community. Best practices are not always an objective standard, but can be just an opinion and opinions should be open to change with discussions within the community. We need to be given a chance to convince you to change your beliefs in what are "best practices". 

As a potential example of an opinion-based "best practices", I'm going to send you an email to debate the non-localhost and mandatory-https requirements for development (I spent around 20 hours trying to workaround and then automate around this "best practice" leading me to potentially next forking this library and removing the restriction to improve developer productivity in development). I definitely could be wrong on this if the OIDC implicit flow mandates https, but if it doesn't then I'm hoping to convince you to change your opinion 😄

**Comment by panva** [comment]
> I'm going to send you an email to debate the non-localhost and mandatory-https requirements for development

You may try, many have before. With implicit going to be discouraged for new applications i find the topic less and less worth discussing. The ONLY possibility i can see is omitting the requirement when the `issuer` identifier is set to localhost. Haven't given that a proper thought yet tho so don't get your hopes up.

> The 5.x not supporting OAuth2 seemed a bit contradictory to me also in terms of expectations for OIDC being built on OAuth2 so this super cool that 6.x supports the standard and expectations.

You're missing my point, prior to v6.x the project just didn't define behaviours for when the `openid` scope was missing. It was and still is by all means an OAuth2.0 compliant server

> From Core 1.0: If the openid scope value is not present, the behavior is entirely unspecified.

> Definitely highlight it as it is an critical change!

I doubt it is for a primarily OIDC server.

> I would be a little bit cautious of "best practices" in an open source library and community. Best practices are not always an objective standard, but can be just an opinion and opinions should be open to change with discussions within the community. We need to be given a chance to convince you to change your beliefs in what are "best practices".

Let's settle on what best practices are - it's whatever the OAuth WG and OIDF WG deems as best practice, i don't make these up and the community doesn't make these up. I will keep on following and interpreting what the standards and OAuth community defines as good / best practice and putting it front and center as default behaviour of this project so that developers don't have to, they can rely on the defaults to be in a good shape. For those who wish to question the best practice and OAuth2.0 security topics there are other projects where everything is up for re-defining, but that also means changes for getting it wrong.

**Comment by kmalakoff** [comment]
@panva I've sent you an email with my case for supporting insecure local development. Let me know if you prefer a public discussion and I'll repeat it here. Thank you!
