### ISSUE TITLE
Question about native apps

### ISSUE THREAD

**Issue by DarkSorrow** [panva/node-oidc-provider#488]
Hello,

I'm trying to test a native application using react-native. I'm using the exemple of "react-native-app-auth" (https://github.com/FormidableLabs/react-native-app-auth/tree/master/Example/AndroidExample) for android to do that.

I created a client using this:
```
this.clients.push({//test
          application_type: 'native',
          client_id: 'native-custom',
          client_secret: 'cacaca',
          grant_types: ['authorization_code', 'refresh_token'],
          response_types: ['code'],
          token_endpoint_auth_method: 'none',
          application_category_id: 0,
          redirect_uris: ['io.identityserver.demo:/localhost/op/callback', 'io.identityserver.demo:/oauthredirect', 'io.identityserver.demo:/'],
      });
```

With this as well in my configurations which grant me a refresh token for this app
```
async issueRefreshToken(ctx, client, code) {
        if (client.application_category_id === 0) {
          return (true);
        }
        return client.grantTypes.includes('refresh_token') && code.scopes.has('offline_access');
      },
```

And on the creact native i'm using this as configuration:
```
issuer: 'http://xxx.xxx.227.246:8143',
  clientId: 'native-custom',
  redirectUrl: 'io.identityserver.demo:/',
  dangerouslyAllowInsecureHttpRequests: true,
  scopes: ['openid', 'profile', 'email', 'offline_access']
```

The thing is i don't get prompted for an offline_access and this doesn't exist later in the promptedScope it seems and when i try to refresh my token i get an error message telling me a scope is missing.
If i understand well in native application we don't want to have a refresh token, this is why the offline_access get taken off from the "promptedScopes"? 
I read in stackoverflow that some people just replay the whole login sequence to try to keep the user logged but this is a lot more slow. I was wondering if there is some other way to still have a refresh token working with the native app. I tried to add a client_secret and comment the token_endpoint_auth_method so that it goes to default but then i just get an error before the call.

But also may if some of you guys are using some react-native component to do the oidc login? That library seemed to be used by many applications tho.

**Comment by panva** [comment]
`offline_access` scope must be accompanied by `prompt=consent`

**Comment by DarkSorrow** [comment]
but wasn't the "issueRefreshToken" allowing us to ask an offline_access without the prompt=consent for what we could call "first party client".
Because in the end a refresh token is issued but since its not pushed in the scope, calling the token endpoint later just generate an error. Actually i haven't tried on the normal web client but it would probably the same thing? If we use the issueRefreshToken to get a refresh_token since the offline_access is not existing this won't work too right? Sorry for all my questions :D

**Comment by panva** [comment]
> but wasn't the "issueRefreshToken" allowing us to ask an offline_access without the prompt=consent for what we could call "first party client".

refresh token is not the same as asking for offline_access, offline_access as a scope has special behaviours defined by Core but you may issue a refresh token under other conditions with the method, you just can't use the offline_access scope as a condition.

**Comment by DarkSorrow** [comment]
Ok thanks i understand better, if i take off the offline_access i can use the refresh endpoint with the email (that i passed and accepted before) and i get a 200.
I guess i will try to see how to use the new features you added in the version 6 to allow pre registered consent. In the past i was loading the consent from my database and injecting it directly in the result object on the login like this
```
const result = {
        login: {
          account: account.subject,
          acr: 'urn:mace:incommon:iap:bronze',
          amr: ['pwd'],
          ts: Math.floor(Date.now() / 1000),
        },
        meta: {
        },
      };
      // Check if consent exist and the client didn't ask for the prompt screen to appear
      if ((consentFlag === true) && (!(params.prompt && params.prompt === 'consent'))) {
        result.consent = account.application_consents[0].details;
      }
```
But it was a bad thing because it bypass the next consent in case there is new scope asked and such. Ill try to read a bit more about this i saw the doc was updated.
Thanks again
