### ISSUE TITLE
Reflected XSS in default render templates

### ISSUE THREAD

**Issue by amaciver** [panva/node-oidc-provider#489]
**Describe the bug**
Seems that the provided default render templates allow for reflected XSS in state param
https://github.com/panva/node-oidc-provider/blob/master/lib/helpers/defaults.js#L1752

**To Reproduce**

Steps to reproduce the behaviour:

1.  Start a flow (Firefox) with a known mismatched redirect_uri, and `<img+src=x+onerror=alert(document.domain)>` as state param 
2.  you will see the script execute upon rendering of the end-user error  

**Expected behaviour**
State param should be sanitized before injection into HTML

**Environment:**
 - oidc-provider version: e.g. v4.1.2, v5.5.5, (code also present in v6.x)
 - node version: [e.g. v8.9.0]

**Additional context**
Other templates are likely implicated

 - [x] the bug is happening on latest oidc-provider too.
 - [x] i have tried DEBUG (see README) and can see the issue is with the provider and not my code.
 - [x] i have searched the issues tracker on github for similar issues and couldn't find anything related.
 - [x] i have searched the [FAQ](https://github.com/panva/node-oidc-provider/wiki/FAQ) and couldn't find anything related.

**Comment by amaciver** [comment]
possibly you will say to sanitize all params on their way in?

**Comment by panva** [comment]
Good thing everyone's responsible for overwriting this helper anyway.

Thanks @amaciver.

**Comment by amaciver** [comment]
Understood, for sure. You clearly indicate that these should be overwritten. Just wanted to flag for you since many people will not think of this when overwriting, and unless they dig into the code will not realize that state and scope are exposed without sanitizing. 👍
