### ISSUE TITLE
Authorization with nested JWT request object

### ISSUE THREAD

**Issue by thomasvargiu** [panva/node-oidc-provider#491]
Hi @panva,

I'm trying to understand why I can't use a nested JWT (signed and encrypted) token with the request object authorization.

The error is:

```
could not decrypt request object (decryption operation failed)
```

Looking at the code I see this:

```js
      if (/^(A|P)/.test(header.alg)) {
        decrypted = await JWT.decrypt(params.request, client.keystore);
        trusted = true;
      } else {
        decrypted = await JWT.decrypt(params.request, keystore);
      }
```

I'm using a `RSA-OAEP` algorithm, so I think it's using the server keystore. Is it correct? Can you explain me?

My JWT header:

```json
{
  "alg": "RSA-OAEP",
  "enc": "A256CBC-HS512",
  "cty": "JWT"
}
```

**Comment by panva** [comment]
@thomasvargiu 

> I'm trying to understand why I can't use a nested JWT (signed and encrypted) token with the request object authorization.

You can, but you are likely not encrypting correctly.

**Comment by thomasvargiu** [comment]
@panva 
Well, I'm able to encrypt and decrypt it with the client JWK set, so I think it's correct.

Should the server use the client jwks to decrypt and verify it? Isn't right?
Because looking the code I see it's using the server keystore.

**Comment by panva** [comment]
If you’re encrypting with asymmetric key its the server public one it exposed via jwks_uri. Symmetric encryption uses a secret key derived from the client secret. RSA-OAEP will use the server keys.

**Comment by panva** [comment]
https://openid.net/specs/openid-connect-core-1_0.html#Encryption

**Comment by thomasvargiu** [comment]
Thank you for explain me that. I'm still a little bit confusing but it's because I don't have a good knowledgement abount encryption with JWT.
