### ISSUE TITLE
Question: remove consent interaction

### ISSUE THREAD

**Issue by jansepke** [panva/node-oidc-provider#492]
Hi, I'm using this project to mock out keycloak for local development. Everything works great so far but I would like to get rid of the consent interaction because it is just an extra click in local development. with this configuration I end up in endless redirect loops between oidc-provider and my frontend (using oidc-client library). without overriding interactions.policy everything works.

```javascript
const basePolicy = base();
basePolicy.remove('consent');

const port = 8084;

const oidcConfig = {
  interactions: {
    policy: basePolicy,
  },
  claims: {
    openid: ['sub', 'preferred_username'],
  },
  formats: {
    AccessToken: 'jwt',
  },
  extraAccessTokenClaims: async (ctx, token) => ({
    preferred_username: token.accountId,
  }),
  responseTypes: ['id_token token'],
  findAccount: async (ctx, id) => ({
    accountId: id,
    claims: async () => ({
      sub: id,
      preferred_username: id,
    }),
  }),
  clients: [
    {
      client_id: 'fury',
      token_endpoint_auth_method: 'none',
      redirect_uris: ['http://localhost:3000/_/callback'],
      post_logout_redirect_uris: ['http://localhost:3000/'],
      grant_types: ['implicit'],
      response_types: ['id_token token'],
    },
  ],
  logoutSource: async (ctx, form) => {
    ctx.body = `<!DOCTYPE html>
        <body>
          <div style="display:none;">
            ${form}
            <button id="logout-btn" type="submit" form="op.logoutForm" value="yes" name="logout"></button>
          </div>
          <script>document.getElementById('logout-btn').click()</script>
        </body>
        </html>`;
  },
};
```

seems like the redirect loop is happening because the callback from the oidc-provider to the callback url is called without any parameters. Seems like I'm missing something in the configuration?

**Comment by panva** [comment]
Just removing it isn’t gonna cut it as the OP just doesn’t have any granted info at hand. Please see the interactions.policy docs l, especially the expandable details.

**Comment by jansepke** [comment]
I was reading these docs that guided me to "modifying the default interaction policy". "disabling default checks" sounds more matching my use case but its hard to get from the documentation what needs to be changed to silently agree to the consent screen. do I only need to modify the details method of the Prompt?

**Comment by panva** [comment]
@jansepke you're either going to have to accept the extra click, automate it for your convenience or experiment and dig into the API, I don't have a prepared answer for this and given that prompt-less flow is of no concern to most.

**Comment by jansepke** [comment]
found a hacky solution that will do it: override the promptedScopesFor method on your oidc-provider instance to always return your requested scoped (WARNING: don't do this in production, use only for local dev setups)
```javascript
provider.Session.prototype.promptedScopesFor = () => new Set(['openid']);
```

**Comment by stanleyyuenyiu** [comment]
actually i skip it by modify the code at

interaction/:uid

while the prompt.name == consent
i directly return below code, and it will skip the Authorize part, and auto Authorized by below code

`
await provider.interactionFinished(req, res, result, { mergeWithLastSubmission: true });
`

**Comment by kareha** [comment]
If it does help anyone:
You can remove the policy by:

```
const { interactionPolicy: { base } } = require('oidc-provider')
const basePolicy = base()
// Uncomment one of:
//basePolicy.remove('native_client_prompt')
//basePolicy.remove('scopes_missing')
//basePolicy.remove('claims_missing')
```

Add the basePolicy to configuration. That will skip the "this is a new authorization .. scope .. continue"-part.
