### ISSUE TITLE
rejectedScopesFor with two parameters return undefined

### ISSUE THREAD

**Issue by DarkSorrow** [panva/node-oidc-provider#493]
Hello,

Not sure if i did something wrong but i tried to use the rejectedScopesFor in the interaction index of consent, in the code i have something like this

```
module.exports = () => new Prompt(
  { name: 'consent', requestable: true },

  async (ctx) => {
    const { oidc } = ctx;
    let prevAcceptedScopes = [];
    let prevRejectedScopes = [];
    let prevAcceptedClaims = [];
    let prevRejectedClaims = [];
    if (dbConsent !== null) {
      prevConsent = dbConsent.consent;
      prevAcceptedScopes = dbConsent.details.acceptedScopes;
      prevRejectedScopes = dbConsent.details.rejectedScopes;
      prevAcceptedClaims = dbConsent.details.acceptedClaims;
      prevRejectedClaims = dbConsent.details.rejectedClaims;
    }
    const acceptedScopes = oidc.session.acceptedScopesFor(
      oidc.params.client_id, prevAcceptedScopes,
    );
    const rejectedScopes = oidc.session.rejectedScopesFor(
      oidc.params.client_id, prevAcceptedScopes,
    );
    const acceptedClaims = oidc.session.acceptedClaimsFor(
      oidc.params.client_id, prevAcceptedClaims,
    );
    const rejectedClaims = oidc.session.rejectedClaimsFor(
      oidc.params.client_id, prevRejectedClaims,
    );
    console.log('************************');
    console.log(acceptedScopes);
    console.log(rejectedScopes);
    console.log(acceptedClaims);
    console.log(rejectedClaims);

...
```
My output goes like this

```
************************
Set {}
undefined
Set {}
undefined
```
And if i change the 
```
const rejectedScopes = oidc.session.rejectedScopesFor(
      oidc.params.client_id, prevAcceptedScopes,
    );
```
to
```
const rejectedScopes = oidc.session.rejectedScopesFor(
      oidc.params.client_id,
    );
```
i do get the proper empty set

From the documentation i saw that only the rejected was suppose to work but is it only the accepted then that is suppose to work? Or did i do something wrong as usual :D?

**Comment by panva** [comment]
The `accepted` is only calculated based on `prompted` - (minus) `rejected`, it doesn't accept a second arg. So what you want to do is use prompted*For and rejected*For with two arguments (setter) only.

https://github.com/panva/node-oidc-provider/blob/master/lib/models/session.js#L217-L312

**Comment by DarkSorrow** [comment]
I see but if i pass an empty array to the rejectedFor
`const rejectedScopes = oidc.session.rejectedScopesFor(oidc.params.client_id, []);`
I get an undefined value returned, shouldn't i get an empty set instead? It's in the case nothing was rejected in the previous consent

**Comment by panva** [comment]
With two args its a setter and returns undefined, it only returns values when used with one arg as a getter.

**Comment by DarkSorrow** [comment]
ok my bad you pointed at the code part i should have checked more carefully.
Thanks
