### ISSUE TITLE
Question : on the OP itself, how to display wether the user is logged-in or not

### ISSUE THREAD

**Issue by madarche** [panva/node-oidc-provider#494]
Hello,

I could not find how to display, **on the website of the OP itself**, wether the user is logged-on or not. The aim is, if the user is logged-in, to display a sign-out link pointing to the session endpoint `/session/end`.

I could not find on the provider instance any method or properties to use to do so.

The route I have been following so far is to find, in the store, a Session with an id being the value of the cookie `provider.cookieName('session')` and an `account` property. But that doesn't verify the cookie integrity through cryptography 😢

I've tried to use `provider.Session(req, res)` and `provider.OIDCContext()` with no avail.

I've also investigated towards `lib/actions/check_session.js`, but this is intended to be used by a client. Again what I'm trying to do is to display this information and sign-out link on the OP itself.

Is there a way to achieve this please?

Thanks in advance!

PS: @panva sorry I was not able to contribute again as I wanted to, I may have a little more time in the quite near future

**Comment by panva** [comment]
> I could not find on the provider instance any method or properties to use to do so.

There isn't one.

> The route I have been following so far is to find, in the store, a Session with an id being the value of the cookie provider.cookieName('session') and an account property.

That's the route you gotta take, are you using koa or express?

**Comment by madarche** [comment]
> That's the route you gotta take, are you using koa or express?

I'm using express.

If I could get the koa instance I could cryptographically verify the cookies I think.

But I don't think the provider instance exposes its koa instance. Does it?

**Comment by panva** [comment]
It does but the koa instance won't help you. Either way you can use https://github.com/pillarjs/cookies which is what koa uses internally with the same keygrip keys you configure the provider with - through that you'll get the cookie value and it'll be checked for integrity.

**Comment by madarche** [comment]
OK! Thanks @panva!

I'll try this approach and will report it asap with actual working code.

**Comment by panva** [comment]
Here you go.

```js
await provider.Session.get(provider.app.createContext(req, res))
```

Please note that this will instantiate an empty session when no session id is found in the cookie.

**Comment by madarche** [comment]
Again, thanks a lot @panva.

Here is the full actual working code for those who will need it:

```javascript
const ctx = provider.app.createContext(req, res)
const session = await provider.Session.get(ctx)
const op_logged_in = !!session.account
```

I have updated the [FAQ](../wiki/FAQ) accordingly.
