### ISSUE TITLE
could the restriction of localhost for implicit be removed?

### ISSUE THREAD

**Issue by katlimruiz** [panva/node-oidc-provider#497]
I am getting an error "You cannot use implicit with localhost redirect uris", 

can we put somewhere a setting that disables this restriction? I understand that this should not go in a production application, but testing locally is hard with this.

Tried setting up the hosts file, which didn't work fully to me.

My scenario is where a .NET Core app is using the nodejs oidc server.

**Comment by katlimruiz** [comment]
A solution found was to modify hosts file to add the line `localhost mytest`

And in .NET, do as follows:

```
                .AddOpenIdConnect("oidc", options => {
                    options.Authority = "http://localhost:5000";
                    options.RequireHttpsMetadata = false;
                    options.SaveTokens = true;
                    options.ResponseType = "code id_token";
                    options.ClientId = cdata.clientid;
                    options.ClientSecret = cdata.clientsecret;
                    options.Events.OnRedirectToIdentityProvider = new Func<Microsoft.AspNetCore.Authentication.OpenIdConnect.RedirectContext, Task>(async (ctx) =>
                    {
                        ctx.ProtocolMessage.RedirectUri = ctx.ProtocolMessage.RedirectUri.Replace("localhost", "mytest");
                        await Task.FromResult(0);
                    });
                });
```

**Comment by panva** [comment]
See the other issues regarding this topic. Bottom line I don’t want an option, people would just leave it enabled and deploy implementations which expose private user data and have known attack vectors open. These restrictions are in for a reason and setting up a local https non localhost environment is quite easy these days.

**Comment by panva** [comment]
Plus using implicit is just not needed today. Unless only for response type id_token sign in flow.

**Comment by panva** [comment]
https://github.com/panva/node-oidc-provider/blob/master/recipes/implicit_http_localhost.md
