### ISSUE TITLE
claims end up in `id_token` but not `access_token`

### ISSUE THREAD

**Issue by brandonros** [panva/node-oidc-provider#498]
This is happening in 5.x

I know you are working on making 6.x be a true OAuth2 provider, not just an OpenID Connect provider.

I'm guessing you kept claims out of `access_token` in 5.x on purpose. Is this true, or are claims supposed to show up in both `id_token` and `access_token`?

**Comment by panva** [comment]
This is making very little sense to me. 

> Is this true, or are claims supposed to show up in both id_token and access_token?

No, user claims do not belong in an access token the same way they do belong in an id token. 

I don’t understand how being able to process pure OAuth requests relates to user claims ending up in access tokens.

OAuth is not for authentication, its for delegating access.

In v6.x you have a helper for pushing any claims to access tokens so if you want to mutilate the protocol rather then using oidc for whats its designed to do you’re free to.
