### ISSUE TITLE
Does it support client ID and Client secret in paramas instead of sending authorization header. 

### ISSUE THREAD

**Issue by testtryrun** [panva/node-oidc-provider#499]

**Comment by panva** [comment]
“it” sure does. Just configure your client with the appropriate token_endpoint_auth_method.

**Comment by testtryrun** [comment]
Thanks. Worked. 

For adding claims in the id_token, i.e. say email and groups(DLs), configuring claims as mentioned under " Configuring available claims" will work OR any other changes are also required as an additional claim(groups) is required.

**Comment by panva** [comment]
You’ll find every setting in the configuration docs. I suggest to read them to know what’s available to you.
