### ISSUE TITLE
Can't be tested in the localhost

### ISSUE THREAD

**Issue by pinkinsect** [panva/node-oidc-provider#50]
I can't set [application_type] to 'native', When register the client in the local.

lib\helpers\client_schema.js 
@line 176 [application_type: 'web',]   --- initialize value
@line 430 [switch (this.application_type) {] --- validate redirectUris

Or could you please let me know how to set [application_type] to 'native'? Thanks a lot!!!

**Comment by panva** [comment]
The application_type 'native' bears with it several defined restrictions on redirect_uris, similar to 'web', those are defined in 

- http://openid.net/specs/openid-connect-registration-1_0.html
- http://openid.net/specs/openid-connect-core-1_0.html

Optionally you can loosen the application_type native restrictions to a level that allows clients with uris as described in https://tools.ietf.org/html/draft-ietf-oauth-native-apps-06 to be configured. (see configuration.md) for details.

If you would go ahead and paste your configuration you're attempting to initialize i may be of more help, like this however, i cannot as i have insufficient details.

**Comment by pinkinsect** [comment]
Thanks for your answer, the problem has been solved.

Thanks  a lot!!!

**Comment by karlbateman** [comment]
Hey @panva is there any way I can set the callback_uri property to localhost?

**Comment by panva** [comment]
Why would you, with local servers like pow or domains rsolving to localhost - lvh.me for instance

The redirect_uri validations follow what the spec defines, the definitions are there to protect both the rp and user's data in the op.

**Comment by karlbateman** [comment]
Mmm, good point, scratch that. For developing an application with openid-client it might be worth a mention as I had completely overlooked that.
