### ISSUE TITLE
On adding claims as email and group to configuration made , it is not returned in id_token(jwt)

### ISSUE THREAD

**Issue by testtryrun** [panva/node-oidc-provider#500]

**Comment by panva** [comment]
@testtryrun please don't open issues like this. Read the docs, put some substance into your issue descriptions, else i will start closing and deleting these.

Your non-issue (it is conform behaviour) is described in the configuration [docs](https://github.com/panva/node-oidc-provider/blob/master/docs/README.md#conformidtokenclaims) as well as [FAQ](https://github.com/panva/node-oidc-provider/wiki/FAQ#id-token-does-not-include-claims-other-than-sub) and allows to be changed. There's even an ❗️mark next to the option in the docs.
