### ISSUE TITLE
Question about session data change cross applications

### ISSUE THREAD

**Issue by DarkSorrow** [panva/node-oidc-provider#501]
Hello,

I have a question about saving session data. From my understanding with the test i did and trying to find info in the doc. Session values that are set in the login for exemple this:
```
const result = {
        login: {
          account: account.subject,
          acr: 'urn:mace:incommon:iap:bronze',
          amr: ['pwd', account.mfa, account.legacy_application],
          ts: Math.floor(Date.now() / 1000),
        },
        meta: {
        },
      };
```
	  
The login values cant be change again without a complete delog / relog right? In my use case i'm trying to test the login of an old user and once he is log the legacy_application become false (after he has agree with condition of the new consent app). This works well if he delogs but in the case he is still log in the application after not being a legacy user when he tries to access a new application the old value stays.
It's the same for the mfa flag somehow, changing it once won't store it in the session even if i put it in the result in the mfa prompt.

I thought of using the meta object but the problem is that its data is valid for an application only, what i would need somehow is meta data that can be set once for all application even after login.

Now i know i can implement this myself using a different call (which is what i'm doing atm) but since i see there are upserts and all already being made i was thinking that there might be better way to update some parameters that are added after the login in "sub" prompt or that i'm missing a function that already exist maybe.

Sorry if i'm not so clear i can reformulate things if you don't understand what i'm saying

**Comment by panva** [comment]
> Sorry if i'm not so clear i can reformulate things if you don't understand what i'm saying

🙏, also [this](https://github.com/panva/node-oidc-provider/blob/master/lib/actions/authorization/resume.js) is what happens when you end interaction with results. What you're working with is an InteractionSession, not a Session :)

**Comment by DarkSorrow** [comment]
When i log the first time the amr has the thrid row set to a string. After he tries to log to a second application, he gets a consent prompt that ask him to change his legacy profile to a new one. Once he does that i need to update the third amr row to null, so that further applications won't ask him the question again.
I can't log him out and i thought that if i could change the amr when he ask for a new AccessToken while being logged, he will get the updated amr too in the access token

I see the difference between the interactionSession and the session somehow but i'm stull able to call the session function when i'm in a controller like the controller one? I'm thinking i'll need something similar to that when i'll try to implement the MFA since once the mfa is accepted, on the same browser if he logs other application he shouldn't get any prompt asking him to put his mfa code again :x

**Comment by DarkSorrow** [comment]
This is what i tried to do on the confirm controller but it's not storing the information about login again, which is why i thought that after a first successful login happened the only thing i can store seems to be application only information (the meta, consent etc) are only for the "applications scope" you can't seems to share information with the result it would seem

**Comment by panva** [comment]
I am not following still, the code i showed you updates the session information, after resume executed that and subsequent authorizations will use that session data. 

Where else would you expect this to be reflected?

**Comment by DarkSorrow** [comment]
Ok my bad as usual my test was failing because i wasn't passing the amr, but i need to put all the information again in order to have the login replaced and i wasn't doing that. it's perfectly fine tho for me to replace all.
Thanks
