### ISSUE TITLE
Invalid token provided

### ISSUE THREAD

**Issue by xperiafan13-rom** [panva/node-oidc-provider#502]
Hi, i use oidc-provider with v5 for node v8
I follow this example: https://github.com/panva/node-oidc-provider-example/blob/master/03-oidc-views-accounts/index.js

But when I enter to /me I get 
  error_description: 'invalid token provided',
  error_detail: 'access token not found' } { request: 

Here is my code:
```
const clients = [{
    client_id: 'foo',
    grant_types: ['implicit'],
    response_types: ['id_token'],
    redirect_uris: ['https://my.test/signin-oidc'],
    token_endpoint_auth_method: 'none'
}];

this.oidc = new Provider('http://localhost:3020', {
            findAccount: Account.findById,
            claims: {
                email: ['email', 'email_verified']
            },
            interactionUrl(ctx) {
                return `/interaction/${ctx.oidc.uid}`;
            },
            formats: {
                AccessToken: 'jwt',
            },
            features: {
                // disable the packaged interactions
                devInteractions: { enabled: false },

                encryption: { enabled: true },
                introspection: { enabled: true },
                revocation: { enabled: true },
            },
        });
```

The other code is the same that is in the example
Whe i logged i get https://my.test/signin-oidc#id_token=eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCIsImt...

Later i use id_token to enter to /me in postman using authorization headers:
Authorization: Bearer .....

But i get
{
    "error": "invalid_token",
    "error_description": "invalid token provided"
}

**Comment by panva** [comment]
> Later i use id_token to enter to /me

ID Token is not for calling APIs.

**Comment by xperiafan13-rom** [comment]
> > Later i use id_token to enter to /me
> 
> ID Token is not for calling userinfo

Can you help me with this please?

**Comment by panva** [comment]
May I suggest stackoverflow with the oauth/oidc tag for “how to” questions. This isn’t really the forum for such questions, plus I lack capacity to explain basics.
