### ISSUE TITLE
How to change the shouldChange methods

### ISSUE THREAD

**Issue by ShlomitG** [panva/node-oidc-provider#504]
Hi,
I want to change logoutSource() to get the logout page look different, as suggested in the code itself, using the shouldChange(). Is there any API for it? I don't want to change it locally, since next 'npm install' will override it.

Thanks.

**Comment by panva** [comment]
https://github.com/panva/node-oidc-provider/blob/master/docs/README.md#logoutsource

Yes, configuration.

**Comment by ShlomitG** [comment]
thanks
