### ISSUE TITLE
Question: How to show error messages to the client back?

### ISSUE THREAD

**Issue by Lakshman1996** [panva/node-oidc-provider#506]
Hi 
I would like to show some user friendly message when authentication fails to the client. I am adding `error` in result object and calling `interactionResult` and redirecting the user manually. But when  ` interaction/uid` end point gets triggered,  `interactionDetails(req)` does not return my error stored earlier.

PS: If error is returned my plan was to render the same interaction again with error view injected

Thanks in advance

**Comment by panva** [comment]
@Lakshman1996 can you provide a sample code? When `provider.interactionResult({ error: 'foo', error_description: 'bar'})` (or `interactionFinished`) is submitted this will get transferred to the client using the standard response mode.

I am not sure what is it that you're trying to achieve from your desription.

**Comment by Lakshman1996** [comment]
Thanks @panva for the quick reply. Here is the code snippet, hope this is clear enough 

```
// Login End point
app.post('/interaction/:uid/login', setNoCache, body, async (req, res, next) => {
    try {
        // user authentication logic
    } catch (err) { 
        // executed for Invalid username / password 
        const result = {
            error: 'Invalid username or password',
            error_description: 'some description of the error',
        };
        const redirectTO = await provider.interactionResult(req, res, result, {  mergeWithLastSubmission: true });
        res.redirect(redirectTO); // redirect to interaction end point with same uid, so that i can use this and show error message
    }
});
```
After redirect the below API gets triggered. While debugging i found that  the interaction object with result  is saved in db before redirect but the same interaction document created in db is deleted as soon the below API gets triggered.
```
// Interaction API
app.get('/interaction/:uid', setNoCache, async (req, res, next) => {
    try {
        // I am expecting 'Invalid username or password' from interactionDetails() from previous login interaction since
        // i redirected with same uid
        const interactionInfo = await provider.interactionDetails(req);
        const client = await provider.Client.find(params.client_id);
        switch (prompt.name) {

            case 'login': {
                return res.render('login', {
                    client,
                    uid,
                    details: prompt.details,
                    params,
                    title: 'Sign-in',
                    session: session ? debug(session) : undefined,
                    error: interactionInfo.result.error, // Pass the error to render engine  to show message to user
                    dbg: {
                        params: debug(params),
                        prompt: debug(prompt),
                    },
                });
            }
        }
    } catch (err) {
        return next(err);
    }
});

```

**Comment by panva** [comment]
I see. So you don't expect 'Invalid username or password' to be returned to the Client (as in OAuth 2.0 terms) but to the end-user.

Returning an error to the client is what that `error` response would be for, and I wonder why it ain't getting sent to the client (or maybe it is and the client immediately starts another auth? Can you check your network trace in the browser?

Anyway - You should not be calling `interactionResult` unless you have a result or an error you want to terminate the interaction with.

For a simple web form post / response render when invalid you need to handle things yourself.

You can see such implementation in the [example repo](https://github.com/panva/node-oidc-provider-example/blob/master/03-oidc-views-accounts/index.js#L114) but please keep in mind this is not how things need to be, the provider does not care how many calls, re-renders or redirects it takes for you to complete the interaction required, so long as **at the end** you submit the result. Until you have it just use whatever koa/express web framework skills you have to develop the end-user interactions.

One hint i usually give to people is to develop the interactions (login, consent, etc) in isolation - and when happy with the result just plug in the provider that triggers these interactions.

**Comment by Lakshman1996** [comment]
Understood! Will look at the examples and try out

**Comment by panva** [comment]
Great.
