### ISSUE TITLE
Checking authenticity of Access Token offline (v5)

### ISSUE THREAD

**Issue by sami-sweng** [panva/node-oidc-provider#507]
In the context of an eventually consistent database, I would like to discuss the possibility to authenticate a user using the Access Token itself only.

Currently to authenticate a user you recommend using [`provider.AccessToken.find`](https://github.com/panva/node-oidc-provider/issues/67) which in turns calls the userland implementation of [`Adpater.find`](https://github.com/panva/node-oidc-provider/blob/v5.x/example/my_adapter.js).

For an eventually consistent database and potentially hundreds of different endpoints around the world, that could implicate issuing Access token that would only be partially valid in the first  seconds / minutes after issuance until the database reach a consistent state. That could reveal frustrating / hard to explain to the end user.

This library offers the possibility to issue JWT Access Token, so potentially that could avoid a database call to verify the validity of the Access Token.

Such a check would obviously prohibit Access Token revocation. But assuming we limit the validity of those tokens to 15 minutes, **would there be other security implication?**

Would there be a helper in this library to perform such an offline check?

Thank you,

**Comment by panva** [comment]
JWT Access Tokens can still be thrown at the revocation endpoint. Regular server side introspection will still tell you those are not valid.

How you validate access tokens at the RS is up to you. If you are worried about replication you may devise a policy for you RSs to check the JWT and every couple of minutes depending for each jti do a server side introspection. 

This library is ultimately just the AS so there’s no helper to use to check a JWT, any JWT library can be used for that.
