### ISSUE TITLE
authorization request has expired

### ISSUE THREAD

**Issue by ToniIltanen** [panva/node-oidc-provider#51]
Hi,
I'm using passport-openidconnect (https://github.com/jaredhanson/passport-openidconnect) for connecting, and after successful login, oidc-provider returns this error (when forwarded to [url]:[port]/op/auth/[uuid] after login post). In getResumeAction on resume.js, this.params.grant contains an uuid. the _grant cookie (or the grant_result cookie) just does not exists.

error shown:
oops! something went wrong
{
    "error": "invalid_request",
    "error_description": "authorization request has expired"
}

**Comment by panva** [comment]
Looks like your cookie config is not in order, the message comes when the op cannot read the cookie it's prepared where all the original auth parameters are. 

Can you compare your setup with the deployed example? Or even better, can i take a stab at it?

**Comment by panva** [comment]
> the _grant cookie (or the grant_result cookie) just does not exist

well it either expired (by default 1 hour), or was manipulated with (.sig removed), or the path configuration is out of whack and so the browser does not send it, it may also not be sent if it was set as secure and you're somehow coming back to the resume part on http.

**Comment by ToniIltanen** [comment]
i got it solved, it was caused by a settings mismatch up on the frontends & load balancer, causing address change on issuer to the auth provider. Issuer should have been auth.address.com, but instead, the issuer was an ip address of the auth from the second front end.

**Comment by panva** [comment]
Sweet, thanks for letting me know :)
