### ISSUE TITLE
Client is invalid

### ISSUE THREAD

**Issue by arjunnaha** [panva/node-oidc-provider#512]
(I'm using the v5.x branch with Node v10.15.1)

When using the [example Mongo adapter](https://github.com/panva/node-oidc-provider/blob/v5.x/example/adapters/mongodb.js), I get a `invalid_client` error:
```
InvalidClient: invalid_client
    at checkClient (/Users/arjunnaha/Developer/server/node_modules/oidc-provider/lib/actions/authorization/check_client.js:18:11)
```
Having looked at the `check_client.js` file, it looks like it can't find the ID of the client.

The URL that node-openid-client generates is:
`http://localhost:3001/oidc/auth?client_id=5d51eb06cec471d3e62270e9&scope=openid%20email&response_type=code&redirect_uri=http%3A%2F%2Flocalhost%3A3001%2Fauth%2Freturn` (provider is mounted to /oidc).

The document from the `client` collection is as follows:
```
{
    _id: 5d51eb06cec471d3e62270e9
    client_id: "5d51eb06cec471d3e62270e9"
    grant_types: Array
    redirect_uris: Array
    client_name: "Web"
    logo_uri: ""
    client_secret:"UAfMQC...."
    isTrusted: true
}
```
Any ideas? Thanks!

**Comment by panva** [comment]
I can see you _id and client_id is an ObjectId which the example mongo adapter and you linked does not use. So I'm thinking you inserted that document yourself and you have to adapt your adapter to wrap `_id: value` as `_id: { $oid: value }`
