### ISSUE TITLE
Send file in renderError

### ISSUE THREAD

**Issue by dafn** [panva/node-oidc-provider#513]
I'm using v6.1.0

I'm trying to send an error page when renderError is run but currently I only get "not found" in the browser. I have tried to send play text and that works. Sending the file from a normal route handler also works.

Works:
`app.use("/", (req, res, next) => {
  res.sendFile(path.resolve('index.html'))
})
`

Works:
`renderError: ({ res }) => {
    res.send("test")
}
` 

Does not work:
`renderError: ({ res }) => {
    res.sendFile(path.resolve('index.html'))
}
` 

Any idea of what I'm doing wrong?

**Comment by panva** [comment]
I don't get why you'd be sending down a file instead of

```js
ctx.type = 'html';
ctx.body = '...'; // html you have in the file
```

So, 

> Any idea of what I'm doing wrong?

that.

> I only get "not found" in the browser

That's because the request is internally handled by the web framework koa, not your express app.

**Comment by dafn** [comment]
I need to send the file as it is generated during build. I dont have the html before building the app. Is there no way to send a file in renderError?

**Comment by panva** [comment]
It doesn’t matter when the file is built. You can read the contents of the built file with the fs standard lib and return them.
