### ISSUE TITLE
configuration of clients is not obvious

### ISSUE THREAD

**Issue by richard-drummond** [panva/node-oidc-provider#514]
**Describe the issue**  
I have the provider running but it is evidently not running in confidential config because I get a debug log from my client and an http error on my callback url.

[auth_openidc:debug] [pid 23680:tid 1360] proto.c(1607): [client 127.0.0.1:65392] oidc_proto_endpoint_auth_none: no client secret is configured; calling the token endpoint without client authentication; only public clients are supported, referer: https://localhost:3000/interaction/MHo5cnwNbiA84svrCHdGq

My provider config has a client secret and so does my client.  There must be some config I am missing.

**To Reproduce**
Provider and Client configuration: (inline or gist)
```js

const configuration = {
  // ... see available options /docs
  clients: [{
    client_id: '996411873298-mshte5ckm3fbn1jgcnckgs8add68ir5bpd.domain',
    client_secret: 'xxxxxxx',
    redirect_uris: ['https://domain/protected/_redirect'],
    // + other client properties
  }],
};```

Steps to reproduce the behaviour:

1.  
2.  
3.  

**Expected behaviour**
A clear and concise description of what you expected to happen.

**Environment:**
 - oidc-provider version: [e.g. v4.3.0]
 - node version: [e.g. v8.9.0]

**Additional context**
Add any other context about the problem here.

 - [ ] the bug is happening on latest oidc-provider too.
 - [ ] i have tried DEBUG (see README) and can see the issue is with the provider and not my code.
 - [ ] i have searched the issues tracker on github for similar issues and couldn't find anything related.
 - [ ] i have searched the [FAQ](https://github.com/panva/node-oidc-provider/wiki/FAQ) and couldn't find anything related.

**Logs**
<!-- run the server with DEBUG=oidc-provider:* and paste the formatted logs or a gist link here -->

**Comment by panva** [comment]
> I have the provider running but it is evidently not running in confidential config because I get a debug log from my client and an http error on my callback url.

The only thing _evident_ from what you're providing is that your client is not configured with the secret and so it's not using it.

> My provider config has a client secret and so does my client. There must be some config I am missing.

The provider client entity is configured with a secret and a defaulted to token_endpoint_auth_method `client_secret_basic`, so it is a confidential client.

Please check with your client software.

@zandbelt, i believe that may be your client software producing this log?

**Comment by zandbelt** [comment]
> @zandbelt, i believe that may be your client software producing this log?

yessir, and it is apparently not configured with a client secret

**Comment by richard-drummond** [comment]
It is configured:
OIDCProviderMetadataURL https://localhost:3000/.well-known/openid-configuration
OIDCClientID 996411873298-mshte5ckm3fbn1jgcnckgs8add68ir5bpd.domain
OIDCClientSecret xxxxxxxxxxx

wish it was that east.  I originally had my client configed with google provider and it worked fine.  switching to local provider using node_oidc_provider is the only difference

The client and secret match on both the client and provider.

**Comment by richard-drummond** [comment]
i reset the client id/secret to foo/bar on both RP and OP.  still same error:

here is the fill log of the transaction.   I am still thinking its a config problem:

[Wed Aug 14 10:19:12.121391 2019] [authz_core:debug] [pid 27624:tid 1372] mod_authz_core.c(817): [client 127.0.0.1:52163] AH01626: authorization result of Require valid-user : denied (no authenticated user yet), referer: https://localhost:3000/interaction/xpqlqrxNg7Jld9XFzBDpp
[Wed Aug 14 10:19:12.122393 2019] [authz_core:debug] [pid 27624:tid 1372] mod_authz_core.c(817): [client 127.0.0.1:52163] AH01626: authorization result of <RequireAny>: denied (no authenticated user yet), referer: https://localhost:3000/interaction/xpqlqrxNg7Jld9XFzBDpp
[Wed Aug 14 10:19:12.122393 2019] [auth_openidc:debug] [pid 27624:tid 1372] mod_auth_openidc.c(3763): [client 127.0.0.1:52163] oidc_check_user_id: incoming request: "/hub/fhirtester/_redirect?code=wSprAWoWODskt5FF5ka9DfotEqCkLkQ21so2dJVvVsw&state=Wewxl7ldKhVyJAMdxzE2731RRv0", ap_is_initial_req(r)=1, referer: https://localhost:3000/interaction/xpqlqrxNg7Jld9XFzBDpp
[Wed Aug 14 10:19:12.122393 2019] [auth_openidc:debug] [pid 27624:tid 1372] util.c(2233): [client 127.0.0.1:52163] oidc_util_hdr_in_get: Cookie=G_AUTHUSER_H=0; G_ENABLED_IDPS=google; mod_auth_openidc_session=7122399e-14c5-b748-a7ed-8c7a5d441f23; mod_auth_openidc_state_Wewxl7ldKhVyJAMdxzE2731RRv0=eyJhbGciOiAiZGlyIiwgImVuYyI6ICJBMjU2R0NNIn0..r7YLExv4lzhltQ8C.iQrkOCCbyf_VQjJmdYv5x_Bn0-e5dSVv-XvKYVlby7moxUCx9EUoDe3taLNlZpaoG1dPakQ757x9KUnkR0e_TlQK1ad1gdQoMMWQxWUrxJ_hFU-3gIKVNQt_H-3enHKkgIhbPFoGFHrulhUCQy01STnxnUyE6BcQ7ADXlOOkGwPNK3fAKXoYUmJJW058juLzoZ_sj0-z49Z333Z_A69pXVH7d-XODOdd4WpxBvOAgf_6YBvy27ZII4Vkk7LiM1zuLPteBFy_94jjNceAEUOB1uu2EeJCoLfAIInGnddXgQgDTXXMv2Y3DXP7kjAj9im51G5xRTt0-etZKScpIpMK3yYykT5Fq67Cs6FikeyLU2iOMR9ReBi6YMq_pd-r.nugR0y_ltLaf7DQM4h_bdQ; _session=7Ax9UX0rEW4pUoaiAv40Y, referer: https://localhost:3000/interaction/xpqlqrxNg7Jld9XFzBDpp
[Wed Aug 14 10:19:12.122393 2019] [auth_openidc:debug] [pid 27624:tid 1372] util.c(1028): [client 127.0.0.1:52163] oidc_util_get_cookie: returning "mod_auth_openidc_session" = "7122399e-14c5-b748-a7ed-8c7a5d441f23", referer: https://localhost:3000/interaction/xpqlqrxNg7Jld9XFzBDpp
[Wed Aug 14 10:19:12.122393 2019] [auth_openidc:debug] [pid 27624:tid 1372] common.c(569): [client 127.0.0.1:52163] oidc_cache_get: enter: 7122399e-14c5-b748-a7ed-8c7a5d441f23 (section=s, decrypt=0, type=shm), referer: https://localhost:3000/interaction/xpqlqrxNg7Jld9XFzBDpp
[Wed Aug 14 10:19:12.123423 2019] [auth_openidc:debug] [pid 27624:tid 1372] common.c(605): [client 127.0.0.1:52163] oidc_cache_get: cache miss from shm cache backend for key 7122399e-14c5-b748-a7ed-8c7a5d441f23, referer: https://localhost:3000/interaction/xpqlqrxNg7Jld9XFzBDpp
[Wed Aug 14 10:19:12.123423 2019] [auth_openidc:debug] [pid 27624:tid 1372] util.c(1180): [client 127.0.0.1:52163] oidc_util_request_matches_url: comparing "/hub/fhirtester/_redirect"=="/hub/fhirtester/_redirect", referer: https://localhost:3000/interaction/xpqlqrxNg7Jld9XFzBDpp
[Wed Aug 14 10:19:12.123423 2019] [auth_openidc:debug] [pid 27624:tid 1372] mod_auth_openidc.c(2199): [client 127.0.0.1:52163] oidc_handle_redirect_authorization_response: enter, referer: https://localhost:3000/interaction/xpqlqrxNg7Jld9XFzBDpp
[Wed Aug 14 10:19:12.123423 2019] [auth_openidc:debug] [pid 27624:tid 1372] util.c(1483): [client 127.0.0.1:52163] oidc_util_read_form_encoded_params: read: code=wSprAWoWODskt5FF5ka9DfotEqCkLkQ21so2dJVvVsw, referer: https://localhost:3000/interaction/xpqlqrxNg7Jld9XFzBDpp
[Wed Aug 14 10:19:12.123423 2019] [auth_openidc:debug] [pid 27624:tid 1372] util.c(1483): [client 127.0.0.1:52163] oidc_util_read_form_encoded_params: read: state=Wewxl7ldKhVyJAMdxzE2731RRv0, referer: https://localhost:3000/interaction/xpqlqrxNg7Jld9XFzBDpp
[Wed Aug 14 10:19:12.123423 2019] [auth_openidc:debug] [pid 27624:tid 1372] util.c(1488): [client 127.0.0.1:52163] oidc_util_read_form_encoded_params: parsed: 82 bytes into 2 elements, referer: https://localhost:3000/interaction/xpqlqrxNg7Jld9XFzBDpp
[Wed Aug 14 10:19:12.123423 2019] [auth_openidc:debug] [pid 27624:tid 1372] mod_auth_openidc.c(2026): [client 127.0.0.1:52163] oidc_handle_authorization_response: enter, response_mode=query, referer: https://localhost:3000/interaction/xpqlqrxNg7Jld9XFzBDpp
[Wed Aug 14 10:19:12.123423 2019] [auth_openidc:debug] [pid 27624:tid 1372] mod_auth_openidc.c(1650): [client 127.0.0.1:52163] oidc_authorization_response_match_state: enter (state=Wewxl7ldKhVyJAMdxzE2731RRv0), referer: https://localhost:3000/interaction/xpqlqrxNg7Jld9XFzBDpp
[Wed Aug 14 10:19:12.123423 2019] [auth_openidc:debug] [pid 27624:tid 1372] mod_auth_openidc.c(801): [client 127.0.0.1:52163] oidc_restore_proto_state: enter, referer: https://localhost:3000/interaction/xpqlqrxNg7Jld9XFzBDpp
[Wed Aug 14 10:19:12.123423 2019] [auth_openidc:debug] [pid 27624:tid 1372] util.c(2233): [client 127.0.0.1:52163] oidc_util_hdr_in_get: Cookie=G_AUTHUSER_H=0; G_ENABLED_IDPS=google; mod_auth_openidc_session=7122399e-14c5-b748-a7ed-8c7a5d441f23; mod_auth_openidc_state_Wewxl7ldKhVyJAMdxzE2731RRv0=eyJhbGciOiAiZGlyIiwgImVuYyI6ICJBMjU2R0NNIn0..r7YLExv4lzhltQ8C.iQrkOCCbyf_VQjJmdYv5x_Bn0-e5dSVv-XvKYVlby7moxUCx9EUoDe3taLNlZpaoG1dPakQ757x9KUnkR0e_TlQK1ad1gdQoMMWQxWUrxJ_hFU-3gIKVNQt_H-3enHKkgIhbPFoGFHrulhUCQy01STnxnUyE6BcQ7ADXlOOkGwPNK3fAKXoYUmJJW058juLzoZ_sj0-z49Z333Z_A69pXVH7d-XODOdd4WpxBvOAgf_6YBvy27ZII4Vkk7LiM1zuLPteBFy_94jjNceAEUOB1uu2EeJCoLfAIInGnddXgQgDTXXMv2Y3DXP7kjAj9im51G5xRTt0-etZKScpIpMK3yYykT5Fq67Cs6FikeyLU2iOMR9ReBi6YMq_pd-r.nugR0y_ltLaf7DQM4h_bdQ; _session=7Ax9UX0rEW4pUoaiAv40Y, referer: https://localhost:3000/interaction/xpqlqrxNg7Jld9XFzBDpp
[Wed Aug 14 10:19:12.123423 2019] [auth_openidc:debug] [pid 27624:tid 1372] util.c(2233): [client 127.0.0.1:52163] oidc_util_hdr_in_get: Cookie=G_AUTHUSER_H=0; G_ENABLED_IDPS=google; mod_auth_openidc_session=7122399e-14c5-b748-a7ed-8c7a5d441f23; mod_auth_openidc_state_Wewxl7ldKhVyJAMdxzE2731RRv0=eyJhbGciOiAiZGlyIiwgImVuYyI6ICJBMjU2R0NNIn0..r7YLExv4lzhltQ8C.iQrkOCCbyf_VQjJmdYv5x_Bn0-e5dSVv-XvKYVlby7moxUCx9EUoDe3taLNlZpaoG1dPakQ757x9KUnkR0e_TlQK1ad1gdQoMMWQxWUrxJ_hFU-3gIKVNQt_H-3enHKkgIhbPFoGFHrulhUCQy01STnxnUyE6BcQ7ADXlOOkGwPNK3fAKXoYUmJJW058juLzoZ_sj0-z49Z333Z_A69pXVH7d-XODOdd4WpxBvOAgf_6YBvy27ZII4Vkk7LiM1zuLPteBFy_94jjNceAEUOB1uu2EeJCoLfAIInGnddXgQgDTXXMv2Y3DXP7kjAj9im51G5xRTt0-etZKScpIpMK3yYykT5Fq67Cs6FikeyLU2iOMR9ReBi6YMq_pd-r.nugR0y_ltLaf7DQM4h_bdQ; _session=7Ax9UX0rEW4pUoaiAv40Y, referer: https://localhost:3000/interaction/xpqlqrxNg7Jld9XFzBDpp
[Wed Aug 14 10:19:12.123423 2019] [auth_openidc:debug] [pid 27624:tid 1372] util.c(1028): [client 127.0.0.1:52163] oidc_util_get_cookie: returning "mod_auth_openidc_state_Wewxl7ldKhVyJAMdxzE2731RRv0" = "eyJhbGciOiAiZGlyIiwgImVuYyI6ICJBMjU2R0NNIn0..r7YLExv4lzhltQ8C.iQrkOCCbyf_VQjJmdYv5x_Bn0-e5dSVv-XvKYVlby7moxUCx9EUoDe3taLNlZpaoG1dPakQ757x9KUnkR0e_TlQK1ad1gdQoMMWQxWUrxJ_hFU-3gIKVNQt_H-3enHKkgIhbPFoGFHrulhUCQy01STnxnUyE6BcQ7ADXlOOkGwPNK3fAKXoYUmJJW058juLzoZ_sj0-z49Z333Z_A69pXVH7d-XODOdd4WpxBvOAgf_6YBvy27ZII4Vkk7LiM1zuLPteBFy_94jjNceAEUOB1uu2EeJCoLfAIInGnddXgQgDTXXMv2Y3DXP7kjAj9im51G5xRTt0-etZKScpIpMK3yYykT5Fq67Cs6FikeyLU2iOMR9ReBi6YMq_pd-r.nugR0y_ltLaf7DQM4h_bdQ", referer: https://localhost:3000/interaction/xpqlqrxNg7Jld9XFzBDpp
[Wed Aug 14 10:19:12.123423 2019] [auth_openidc:debug] [pid 27624:tid 1372] util.c(2311): [client 127.0.0.1:52163] oidc_util_hdr_err_out_add: Set-Cookie: mod_auth_openidc_state_Wewxl7ldKhVyJAMdxzE2731RRv0=; Path=/; Expires=Thu, 01 Jan 1970 00:00:00 GMT; Secure; HttpOnly, referer: https://localhost:3000/interaction/xpqlqrxNg7Jld9XFzBDpp
[Wed Aug 14 10:19:12.125391 2019] [auth_openidc:debug] [pid 27624:tid 1372] util.c(207): [client 127.0.0.1:52163] oidc_util_jwt_verify: enter: JWT header={"alg": "dir", "enc": "A256GCM"}, referer: https://localhost:3000/interaction/xpqlqrxNg7Jld9XFzBDpp
[Wed Aug 14 10:19:12.125391 2019] [auth_openidc:debug] [pid 27624:tid 1372] util.c(2022): [client 127.0.0.1:52163] oidc_util_create_symmetric_key: key_len=32, referer: https://localhost:3000/interaction/xpqlqrxNg7Jld9XFzBDpp
[Wed Aug 14 10:19:12.125720 2019] [auth_openidc:debug] [pid 27624:tid 1372] mod_auth_openidc.c(231): [client 127.0.0.1:52163] oidc_get_browser_state_hash: enter, referer: https://localhost:3000/interaction/xpqlqrxNg7Jld9XFzBDpp
[Wed Aug 14 10:19:12.125720 2019] [auth_openidc:debug] [pid 27624:tid 1372] util.c(2233): [client 127.0.0.1:52163] oidc_util_hdr_in_get: User-Agent=Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/75.0.3770.142 Safari/537.36, referer: https://localhost:3000/interaction/xpqlqrxNg7Jld9XFzBDpp
[Wed Aug 14 10:19:12.125720 2019] [auth_openidc:debug] [pid 27624:tid 1372] mod_auth_openidc.c(855): [client 127.0.0.1:52163] oidc_restore_proto_state: restored state: {"ou":"https://localhost/hub/fhirtester/validate","om":"get","i":"https://localhost:3000","rt":"code","n":"arKot2fz-Lf1h2J-CHEdXGNYs11UJIv7b4eKjfuHurc","t":1565792342,"s":"Wewxl7ldKhVyJAMdxzE2731RRv0"}, referer: https://localhost:3000/interaction/xpqlqrxNg7Jld9XFzBDpp
[Wed Aug 14 10:19:12.125720 2019] [auth_openidc:debug] [pid 27624:tid 1372] common.c(569): [client 127.0.0.1:52163] oidc_cache_get: enter: https://localhost:3000/.well-known/openid-configuration (section=p, decrypt=0, type=shm), referer: https://localhost:3000/interaction/xpqlqrxNg7Jld9XFzBDpp
[Wed Aug 14 10:19:12.125720 2019] [auth_openidc:debug] [pid 27624:tid 1372] common.c(603): [client 127.0.0.1:52163] oidc_cache_get: cache hit: return 1270 bytes from shm cache backend for key https://localhost:3000/.well-known/openid-configuration, referer: https://localhost:3000/interaction/xpqlqrxNg7Jld9XFzBDpp
[Wed Aug 14 10:19:12.125720 2019] [auth_openidc:debug] [pid 27624:tid 1372] proto.c(2891): [client 127.0.0.1:52163] oidc_proto_handle_authorization_response_code: enter, referer: https://localhost:3000/interaction/xpqlqrxNg7Jld9XFzBDpp
[Wed Aug 14 10:19:12.125720 2019] [auth_openidc:debug] [pid 27624:tid 1372] proto.c(2698): [client 127.0.0.1:52163] oidc_proto_validate_issuer_client_id: iss and/or client_id matched OK: (null), https://localhost:3000, (null), foo, referer: https://localhost:3000/interaction/xpqlqrxNg7Jld9XFzBDpp
[Wed Aug 14 10:19:12.126443 2019] [auth_openidc:debug] [pid 27624:tid 1372] proto.c(1928): [client 127.0.0.1:52163] oidc_proto_resolve_code: enter, referer: https://localhost:3000/interaction/xpqlqrxNg7Jld9XFzBDpp
[Wed Aug 14 10:19:12.126443 2019] [auth_openidc:debug] [pid 27624:tid 1372] proto.c(1786): [client 127.0.0.1:52163] oidc_proto_token_endpoint_auth: token_endpoint_auth=none, referer: https://localhost:3000/interaction/xpqlqrxNg7Jld9XFzBDpp
[Wed Aug 14 10:19:12.126443 2019] [auth_openidc:debug] [pid 27624:tid 1372] proto.c(1607): [client 127.0.0.1:52163] oidc_proto_endpoint_auth_none: no client secret is configured; calling the token endpoint without client authentication; only public clients are supported, referer: https://localhost:3000/interaction/xpqlqrxNg7Jld9XFzBDpp
[Wed Aug 14 10:19:12.126443 2019] [auth_openidc:debug] [pid 27624:tid 1372] util.c(618): [client 127.0.0.1:52163] oidc_util_http_add_form_url_encoded_param: processing: grant_type=authorization_code, referer: https://localhost:3000/interaction/xpqlqrxNg7Jld9XFzBDpp
[Wed Aug 14 10:19:12.126443 2019] [auth_openidc:debug] [pid 27624:tid 1372] util.c(618): [client 127.0.0.1:52163] oidc_util_http_add_form_url_encoded_param: processing: code=wSprAWoWODskt5FF5ka9DfotEqCkLkQ21so2dJVvVsw, referer: https://localhost:3000/interaction/xpqlqrxNg7Jld9XFzBDpp
[Wed Aug 14 10:19:12.126742 2019] [auth_openidc:debug] [pid 27624:tid 1372] util.c(618): [client 127.0.0.1:52163] oidc_util_http_add_form_url_encoded_param: processing: redirect_uri=https://localhost/hub/fhirtester/_redirect, referer: https://localhost:3000/interaction/xpqlqrxNg7Jld9XFzBDpp
[Wed Aug 14 10:19:12.126742 2019] [auth_openidc:debug] [pid 27624:tid 1372] util.c(618): [client 127.0.0.1:52163] oidc_util_http_add_form_url_encoded_param: processing: client_id=foo, referer: https://localhost:3000/interaction/xpqlqrxNg7Jld9XFzBDpp
[Wed Aug 14 10:19:12.126742 2019] [auth_openidc:debug] [pid 27624:tid 1372] util.c(664): [client 127.0.0.1:52163] oidc_util_http_form_encoded_data: data=grant_type=authorization_code&code=wSprAWoWODskt5FF5ka9DfotEqCkLkQ21so2dJVvVsw&redirect_uri=https%3A%2F%2Flocalhost%2Fhub%2Ffhirtester%2F_redirect&client_id=foo, referer: https://localhost:3000/interaction/xpqlqrxNg7Jld9XFzBDpp
[Wed Aug 14 10:19:12.126742 2019] [auth_openidc:debug] [pid 27624:tid 1372] util.c(688): [client 127.0.0.1:52163] oidc_util_http_call: url=https://localhost:3000/token, data=grant_type=authorization_code&code=wSprAWoWODskt5FF5ka9DfotEqCkLkQ21so2dJVvVsw&redirect_uri=https%3A%2F%2Flocalhost%2Fhub%2Ffhirtester%2F_redirect&client_id=foo, content_type=application/x-www-form-urlencoded, basic_auth=(null), bearer_token=(null), ssl_validate_server=1, timeout=60, outgoing_proxy=(null), pass_cookies=0, ssl_cert=(null), ssl_key=(null), referer: https://localhost:3000/interaction/xpqlqrxNg7Jld9XFzBDpp
[Wed Aug 14 10:19:12.246793 2019] [auth_openidc:debug] [pid 27624:tid 1372] util.c(825): [client 127.0.0.1:52163] oidc_util_http_call: HTTP response code=401, referer: https://localhost:3000/interaction/xpqlqrxNg7Jld9XFzBDpp
[Wed Aug 14 10:19:12.246793 2019] [auth_openidc:debug] [pid 27624:tid 1372] util.c(830): [client 127.0.0.1:52163] oidc_util_http_call: response={"error":"invalid_client","error_description":"client authentication failed"}, referer: https://localhost:3000/interaction/xpqlqrxNg7Jld9XFzBDpp
[Wed Aug 14 10:19:12.248852 2019] [auth_openidc:error] [pid 27624:tid 1372] [client 127.0.0.1:52163] oidc_util_json_string_print: oidc_util_check_json_error: response contained an "error" entry with value: ""invalid_client"", referer: https://localhost:3000/interaction/xpqlqrxNg7Jld9XFzBDpp
[Wed Aug 14 10:19:12.248852 2019] [auth_openidc:error] [pid 27624:tid 1372] [client 127.0.0.1:52163] oidc_util_json_string_print: oidc_util_check_json_error: response contained an "error_description" entry with value: ""client authentication failed"", referer: https://localhost:3000/interaction/xpqlqrxNg7Jld9XFzBDpp
[Wed Aug 14 10:19:12.248852 2019] [auth_openidc:error] [pid 27624:tid 1372] [client 127.0.0.1:52163] oidc_proto_resolve_code_and_validate_response: failed to resolve the code, referer: https://localhost:3000/interaction/xpqlqrxNg7Jld9XFzBDpp

**Comment by panva** [comment]
It says your `token_endpoint_auth` on the client is `none`.

> oidc_proto_token_endpoint_auth: token_endpoint_auth=none
> oidc_proto_endpoint_auth_none: no client secret is configured; calling the token endpoint without client authentication; only public clients are supported

Your client software is not authenticated therefore it gets `invalid_client` from the OP, that's expected when client auth fails.

**Comment by richard-drummond** [comment]
I agree.  I am not sure why mod_oidc is saying no client secret is configured.  it certainly is configured on the client.  Maybe @zandbelt can shed light.  If you want me to move this issue to his git I sure can....

**Comment by panva** [comment]
I'm just going to lock this one here as there's nothing I can do.

**Comment by panva** [comment]
@richard-drummond I think the @zandbelt's client may be somehow resolving the method to use and since "none" is listed first in this OP's discovery it uses that.

You gotta a find a way to explicitly set the client software method to use since it does not default to "client_secret_basic" or "client_secret_post" when supported but rather the first one it recognizes from the list, which in this case is "none" for public clients.

**Comment by zandbelt** [comment]
is "none" even in the spec?

**Comment by panva** [comment]
https://openid.net/specs/openid-connect-core-1_0.html#ClientAuthentication

its' the defined method for public clients.

**Comment by zandbelt** [comment]
that's about client registration; the OP Discovery spec - which is what we are dealing with here - does not mention it https://openid.net/specs/openid-connect-discovery-1_0.html

**Comment by panva** [comment]
"none" is an IANA registered OAuth Token Endpoint Authentication Method, it just as any other new method registered via an extension MAY be listed as supported value.
