### ISSUE TITLE
404 when requesting through alternate route

### ISSUE THREAD

**Issue by major-mann** [panva/node-oidc-provider#515]
I have been trying to setup some internal service routing. Everything works fine when using the standard public routing, but when using the internal routing all routes defined by the oidc provider return 404.

I assume I am missing a header or headers (I have tried as many combinations with the x-forwarded headers but none seem to make a difference), but am not able to determine which ones (Or, if you have another idea what may be wrong, mention that). Would it be possible for you to list out the required headers, or possibly point me to a location in the code it might be passing through so I can investigate and try to understand the issue.

Thanks
 - oidc-provider version: v5.5.5
 - node version: v10

**Comment by panva** [comment]
`ctx.method` and `ctx.path` is what matters to any koa router. Proxy header rules are useful for changing what the provider sees as hostname, but not paths.

**Comment by major-mann** [comment]
OK, So... When we do a request to the same path (e.g. `/certs`) what could be causing one of the requests to be returning 404?

**Comment by panva** [comment]
No idea, plenty of things starting with how you mount (or not) mount the provider etc ending with what you proxy requests to the provider with and how.

I cannot help further unfortunately. Debug, add middlewares, try with a regular app, compare.

**Comment by major-mann** [comment]
> No idea, plenty of things starting with how you mount (or not) the provider etc ending with what you proxy requests to the provider with and how.
> 
> I cannot help further unfortunately. Debug, add middlewares, try with a regular app, compare.

I will . be doing exactly that tomorrow. Thanks for your help pointing to the method and path as potential entry points into the problem
