### ISSUE TITLE
Cookie Keys - TypeError: Cannot read property 'getHeader' of undefined

### ISSUE THREAD

**Issue by Ineluki** [panva/node-oidc-provider#517]
**Describe the bug**
This occurs when using the config shown below, if the cookies.keys option is set. 
When commenting out the cookies block of the config, the devInteraction endpoint is shown without problem.

**To Reproduce**

```js
// provider configuration
{
  "jwks": {
    "keys": [
      {...}
    ]
  },
  "cookies": {
    "keys": [
      "secre1"
    ]
  },
  "features": {
    "registration": {
      "enabled": true
    },
    "devInteractions": {
      "enabled": true
    }
  },
  "clients": [
    {
      "client_id": "test",
      "client_secret": "test",
      "grant_types": [
        "refresh_token",
        "authorization_code"
      ],
      "id_token_signed_response_alg": "HS256",
      "redirect_uris": [
        "http://localhost:8080/"
      ]
    }
  ]
}

// its a koa setup
app.use( mount(OidcProvider.app) );

```

Steps to reproduce the behaviour:

1.  setup provider with config
2.  use test tool (e.g. https://github.com/VirginPulsePublic/openid-connect-tool)
3.  attempt to reach login interaction

**Expected behaviour**
The interaction is shown, same as when not setting cookie.keys

**Environment:**
 - oidc-provider version: v6.6.0
 - node version: v12

**Additional context**

 - [x] the bug is happening on latest oidc-provider too.
 - [x] i have tried DEBUG (see README) and can see the issue is with the provider and not my code.
 - [x] i have searched the issues tracker on github for similar issues and couldn't find anything related.
 - [x] i have searched the [FAQ](https://github.com/panva/node-oidc-provider/wiki/FAQ) and couldn't find anything related.

**Logs**
```
oidc-provider:authentication:interrupted uid=fdYIuXK-Rji4HR3sESaLi interaction=Interaction 
  { returnTo: 'http://localhost:3000/auth/fdYIuXK-Rji4HR3sESaLi', prompt: { name: 'login', reasons: [ 'no_session' ], details: { max_age: undefined, login_hint: undefined, id_token_hint: undefined } }, lastSubmission: undefined, uid: 'fdYIuXK-Rji4HR3sESaLi', params: { client_id: 'test', redirect_uri: 'http://localhost:8080/', response_type: 'code' }, signed: undefined, session: undefined, kind: 'Interaction', jti: 'fdYIuXK-Rji4HR3sESaLi' } +0ms
app GET /auth?client_id=test&redirect_uri=http%3A%2F%2Flocalhost%3A8080%2F&scope=default&response_type=code - 27ms +0ms
oidc-provider:server_error uid=fdYIuXK-Rji4HR3sESaLi path=/interaction/fdYIuXK-Rji4HR3sESaLi method=GET error=TypeError: Cannot read property 'getHeader' of undefined
at Cookies.set (/.../node_modules/cookies/index.js:86:21)
at Cookies.get (/.../node_modules/cookies/index.js:76:10)
at Provider.getCookie (/.../node_modules/oidc-provider/lib/provider.js:28:18)
at Provider.getInteraction (/.../node_modules/oidc-provider/lib/provider.js:47:24)
at Provider.interactionDetails (/.../node_modules/oidc-provider/lib/provider.js:210:27)
at interactionRender (/.../node_modules/oidc-provider/lib/actions/interaction.js:46:28)
at dispatch (/.../node_modules/koa-compose/index.js:42:32)
at noCache (/.../node_modules/oidc-provider/lib/shared/no_cache.js:4:9)
at dispatch (/.../node_modules/koa-compose/index.js:42:32)
at errorHandler (/.../node_modules/oidc-provider/lib/shared/error_handler.js:23:13)
at dispatch (/.../node_modules/koa-compose/index.js:42:32)
at ensureSessionSave (/.../node_modules/oidc-provider/lib/helpers/initialize_app.js:49:13)
at dispatch (/.../node_modules/koa-compose/index.js:42:32)
at contextEnsureOidc (/.../node_modules/oidc-provider/lib/shared/context_ensure_oidc.js:4:11)
at dispatch (/.../node_modules/koa-compose/index.js:42:32)
at namedRoute (/.../node_modules/oidc-provider/lib/helpers/initialize_app.js:58:12) +0ms

```

**Comment by panva** [comment]
I can't reproduce the issue, if you could provide a working gist rather than this excerpt.

Anyway, i think there may be a couple things at play.

- you're swapping the values and not clearing your cookies, what can happen is that you have a session cookie, then you enable signed cookies and when the existing one gets loaded it fails and tries to unset them. I can fix that by extending `interactionDetails` with a res object.
- if you're setting cookies on the provider only but not your own koa app, it may produce mixed results.

**Comment by Ineluki** [comment]
Here's a minimum server gist that produces the error for me:
https://gist.github.com/Ineluki/8975227e0a5d88070bb23804b42e32d2

The debug tool produces this request first, which works:
http://localhost:3000/auth?client_id=test&redirect_uri=http%3A%2F%2Flocalhost%3A8080%2F&scope=default&response_type=code
and then redirects to
http://localhost:3000/interaction/VO2dCYMcELndxH33Vy_nM
which produces the error.

And I made sure to clear all cookies from previous development before running the test.

**Comment by panva** [comment]
the secret on your koa app that you mount to and the one you pass to the provider configuration must be the same.

**Comment by Ineluki** [comment]
Indeed, that was it! Thanks!
