### ISSUE TITLE
Configuration for interactions URL not taking

### ISSUE THREAD

**Issue by rmaher001** [panva/node-oidc-provider#521]
I am new at using oidc-provider. I am trying to change the the URL path from:
https://foo.bar.com/ to https://foo.bar.com/**api-test-sever**

I have the following show from the config endpoint:
issuer URL: foo.bar.com/api-test-sever
authorization_endpoint: foo.bar.com/auth
all other endpoints also show as foo.bar.com/ with no path api-test-server

The configuration is based on the express example. I have changed this adding the path prefix:
  interactions: {
    policy: interactions,
    async url(ctx, interaction) { 
      return `**/api-test-server**/interaction/${ctx.oidc.uid}`;
    },
  }, 

Below is the full configuration.js file. 

Any help is greatly appreciated.

Thanks,
Richard

PS. actual host has been replaced with foo.bar.com to protect the innocent.

=========================== configuration.js =========================
const {
  interactionPolicy: {
    Prompt,
    base: policy
  }
} = require('oidc-provider'); // require('oidc-provider');

// copies the default policy, already has login and consent prompt policies
const interactions = policy();

// create a requestable prompt with no implicit checks
const selectAccount = new Prompt({
  name: 'select_account',
  requestable: true,
});

// add to index 0, order goes select_account > login > consent
interactions.add(selectAccount, 0);

module.exports = {
  clients: [{
    client_id: 'fooClient',
    client_secret: 'xyzxxx',
    grant_types: ['refresh_token', 'authorization_code'],
    redirect_uris: [
      'http://localhost:3000/callback', 
      'https://foo.bar.com/api-test-server/callback'],
    scopes: ['openid', 'offline_access']
  }],
  interactions: {
    policy: interactions,
    async url(ctx, interaction) { // eslint-disable-line no-unused-vars
      return `/api-test-server/interaction/${ctx.oidc.uid}`;
    },
  },
  cookies: {
    long: {
      signed: true,
      maxAge: (1 * 24 * 60 * 60) * 1000
    }, // 1 day in ms
    short: {
      signed: true
    },
    keys: ['some secret key', 'and also the old rotated away some time ago', 'and one more'],
  },
  claims: {
    address: ['address'],
    email: ['email', 'email_verified'],
    phone: ['phone_number', 'phone_number_verified'],
    profile: ['birthdate', 'family_name', 'gender', 'given_name', 'locale', 'middle_name', 'name',
      'nickname', 'picture', 'preferred_username', 'profile', 'updated_at', 'website', 'zoneinfo'
    ],
  },
  features: {
    devInteractions: {
      enabled: false
    }, // defaults to true
    deviceFlow: {
      enabled: true
    }, // defaults to false
    introspection: {
      enabled: true
    }, // defaults to false
    revocation: {
      enabled: true
    }, // defaults to false
    registration: {
      initialAccessToken: true
    }, // issue refresh token on initial access
  },

  ttl: {
    AccessToken: 1 * 60 * 60, // 1 hour in seconds
    AuthorizationCode: 10 * 60, // 10 minutes in seconds
    IdToken: 1 * 60 * 60, // 1 hour in seconds
    DeviceCode: 10 * 60, // 10 minutes in seconds
    RefreshToken: 1 * 24 * 60 * 60, // 1 day in seconds
  },
};.

**Comment by panva** [comment]
Hi @rmaher001 

Please take the time to format your issue's description properly first.

**Comment by panva** [comment]
@rmaher001 it sounds to me like you actually care to mount the provider to a given path (and have all paths relative to that), `interactions.url` is not the means to achieve that. [`Mounting oidc-provider`](https://github.com/panva/node-oidc-provider/blob/master/docs/README.md#mounting-oidc-provider) is a way to achieve that.

Please correct me if i'm wrong.

**Comment by panva** [comment]
Can you post how your actual google cloud function looks? This is pretty specific so i can't help you without knowing how you're calling everything inside the function.

**Comment by panva** [comment]
Google cloud functions abstracts the "function name" away from the url. This would be fine if you had a custom CNAME / custom url for the function's invocation.

The problem doesn't lie with the provider but rather, your environment and the fact that while its public its not really intended for production use like this (with the function name).

You may try

- putting this into your function's handler before invoking whatever web server abstraction.
```
req.originalUrl = `/api-test-server/${req.originalUrl}
```

afterwards its a matter of setting your `interactions.url` appropriately

**Comment by rmaher001** [comment]
Thank you Filip. I ended up ditching Google Cloud Functions and deploying my own server.
