### ISSUE TITLE
problem in using the examples

### ISSUE THREAD

**Issue by pshaddel** [panva/node-oidc-provider#524]
When I try to start example I got this error :
Error: keystore must be a JSON Web Key Set formatted object
    at Provider.initializeKeystore (/.../node-oidc-provider/lib/helpers/initialize_keystore.js:61:11)
I ran the tests before starting the example but every test passed successfully.
and when I print the jwks it is in correct format.

**Comment by panva** [comment]
@pshaddel you seem to be using mismatching version of the library to the examples. 

Which example are you using? Maybe i forgot to update some.

**Comment by pshaddel** [comment]
this one : https://github.com/panva/node-oidc-provider/blob/master/example/express.js

**Comment by panva** [comment]
You're using node 10 right? The sample uses an EdDSA signing key that isn't supported by node 10 runtime.
