### ISSUE TITLE
invalid_request: unrecognized route or not allowed method (GET on /)

### ISSUE THREAD

**Issue by pttse** [panva/node-oidc-provider#526]
**Describe the bug**

render problem

Have started all three versions( koa, express, standalone) one by one, but the rendered page all displays the same error message:

<img width="468" alt="Screenshot 2019-09-03 at 6 31 11 PM" src="https://user-images.githubusercontent.com/2939262/64166281-58576d00-ce79-11e9-8770-6f490a76aa80.png">

Not sure if I get the flow or not, have checked other issues in the repository but no luck.

**To Reproduce**

Steps to reproduce the behaviour:

1.  run node koa (similar as run node express, run node standalone)
2.  go to the http://localhost:3000

**Expected behaviour**
Page with no error.
**Environment:**
 - oidc-provider version: v6.7.0
 - node version: v10.13.0
-  OS:  macOS 10.14.5 

**Additional context**

 - [x] the bug is happening on latest oidc-provider too.
 - [x] i have tried DEBUG (see README) and can see the issue is with the provider and not my code.
 - [x] i have searched the issues tracker on github for similar issues and couldn't find anything related. 
 - [x] i have searched the [FAQ](https://github.com/panva/node-oidc-provider/wiki/FAQ) and couldn't find anything related.

**Logs** 
$ DEBUG=oidc-provider:* node koa
WARNING: a quick start development-only in-memory adapter is used, you MUST change it in order to not lose all stateful provider data upon restart and to be able to share these between processes
application is listening on port 3000, check its /.well-known/openid-configuration
  oidc-provider:error uid=undefined path=/ method=GET error={ error: 'invalid_request', error_description: 'unrecognized route or not allowed method (GET on /)' } detail=undefined +0ms
NOTICE: default renderError function called, you SHOULD change it in order to customize the look of the error page.

**Comment by panva** [comment]
Hi @pttse,

this is perfectly expected, there's no handler for the root route. You may wanna check `/.well-known/openid-configuration` where all the enabled protocol related stuff has its configuration metadata.

**Comment by mdnmdn** [comment]
Hi @panva,
this actual behaviour seems to override any other further routes declared after registering the provider.

I couldn' t add routes with lower precedence than the oidc's (es for serving a catch all router for a SPA handling the UI).

BTW: great work and thanks!
