### ISSUE TITLE
 Selecting multiple accounts

### ISSUE THREAD

**Issue by alecap7** [panva/node-oidc-provider#527]
Hi panva,
I'm following the example at https://github.com/panva/node-oidc-provider/tree/master/example.
Looking at the code related to the account selection feature, I wonder if it is possible to select between more than one active user (without switching and re-logging, being able to manage multiple active sessions).
In practice, is it possible to offer a UX as in the image using only features offered by the oidc-provider?
![oidc-ux-question](https://user-images.githubusercontent.com/19936148/64532276-76a5e880-d311-11e9-83b4-c2b43932f0a5.jpg)

**Comment by panva** [comment]
The Provider only maintains one end-user in its session. Your interactions may keep more of them and offer this `select_account` feature. This will however keep on changing the provider cookies and trigger cleanup logouts whenever the principal changes. You would also need to disable all "session bound" tokens by setting `expiresWithSession` to always return false.

I don't have a better answer for you now - only that it's not a priority and i'm more thinking about how this could work when it comes to session management features, as in - how could, or rather should, i maintain two sets of session state cookies for a single client should two end-users log in for it. Ultimately i think only the last one should persist, which is the behaviour you'll get when doing the above, i guess.

**Comment by alecap7** [comment]
Ok, i've got it.
Fortunately it was just a curiosity :relaxed:

Thanks for your work and your quick replies!
