### ISSUE TITLE
Remove token_revocation_endpoint?

### ISSUE THREAD

**Issue by raymondsze** [panva/node-oidc-provider#53]
Are there any rfc reference mention the token_revocation_endpoint could exist in the discovery document?
If no, I think it is better to have a way to remove the token_revocation_endpoint in the discovery document even revocation is enabled.

https://accounts.google.com/.well-known/openid-configuration
In google, the revocation endpoint is named as "revocation_endpoint"

**Comment by panva** [comment]
From http://openid.net/specs/openid-connect-discovery-1_0.html
> Additional OpenID Provider Metadata parameters MAY also be used.

There's no registry existing for these extensions, but both property names seem to be mentioned in this [discussion](http://lists.openid.net/pipermail/openid-specs-ab/Week-of-Mon-20140407/004706.html).

I'm thinking i will add an option to this and introspection feature definition that will allow to change the name of the property, and optionally to hide it.

In any case, you may do an upstream middleware like so to remove the property.

```js
provider.app.middleware.unshift(function* (next) {
  yield next;

  if (this.path.endsWith('.well-known/openid-configuration')) {
    delete this.body.token_revocation_endpoint;
  }
});
```

**Comment by panva** [comment]
Are you fine with the middleware solution? Obviously when 2.0.0 hits the GeneratorFunction will have to be changed to an async function but that's going to be a common theme to upgrade anyway.

**Comment by raymondsze** [comment]
Yes. Middleware approach works well.
