### ISSUE TITLE
Unable to cancel end_session logout without revoking grants

### ISSUE THREAD

**Issue by KalleV** [panva/node-oidc-provider#531]
Hello, I'm setting up the session management feature for my project and running into an issue with cancelling logouts. On the default end session page, when I cancel the logout, it is still hitting this block: https://github.com/panva/node-oidc-provider/blob/4ac3905aac5a32c9dc2ccba29975f68587bf77b2/lib/actions/end_session.js#L199 and revoking all the grants such as the AccessToken.

How can I prevent this? I want the user to be able to continue using the app without logging in again if they cancel the logout.

**Comment by panva** [comment]
There’s no logout cancel. There’s logout completely or logout just from the RP that initiated it.

**Comment by KalleV** [comment]
So there isn't a way to prevent the grants from being revoked if the user selects "No, stay signed in" from the logout page?

**Comment by panva** [comment]
No, it proceeds with a specific RP logout (clears data from session) but keeps the OP session overall.

**Comment by panva** [comment]
You can however add your own markup to the logout confirmation prompt that doesn't submit the form and simply leads anywhere with processing the OP side of the logout.

**Comment by KalleV** [comment]
Thanks, I'll try that!
