### ISSUE TITLE
How do I check if a session is present?

### ISSUE THREAD

**Issue by kareha** [panva/node-oidc-provider#532]
I want to use oidc-provider to built a identity management.
How do I implement single sign on?
When I call http://localhost:3000/auth?.. to login, I get redirected to /interaction/:uid every time, even if I already logged in. Is there no option to stay logged in?

How can I check if the user is logged in, when I configure a route like http://localhost:3000/account to create a page for user profile? Do I have to get an id_token within the provider or can I call the account model too?
How can I configure additional routes localy and check if someone is logged in to the oidc provider?

Do I have to set up a client itself to access the user profile on the same platform?

Maybe I miss something. I understand oauth and oidc, but I don't understand your framework completely.
Are there more examples?

Thanks for help in advance

**Comment by panva** [comment]
> Maybe I miss something. I understand oauth and oidc, but I don't understand your framework completely.

This library exposes just the oidc interface, nothing more - it does not expose identity management.

That being said you have multiple options

1) your identity management platform is a client of the OP itself - you can adopt the interaction policy to skip consent prompts for this client and just get yourself the tokens.

2) see #494 - use the fact that the session may already be established and just retrieve the data.

**Comment by kareha** [comment]
Thank you. Maybe I can use something like:

```
  app.get('/account', setNoCache, async (req, res, next) => {
    const ctx = provider.app.createContext(req, res)
    const session = await provider.Session.get(ctx)
    if(!!session.account) {
      const account = await Account.findAccount(null, session.account)
      console.log('show account', account)
    }
  })
```

Or would you advise against it?
I think you helped me out :) thx

**Comment by panva** [comment]
sounds about right, and when there's no session you likely want what's described in the first bullet - an "OP Client" to login the user.
