### ISSUE TITLE
Questions: Local login to idp without client

### ISSUE THREAD

**Issue by kareha** [panva/node-oidc-provider#535]
Hi,

I need to develop management pages around oidc-provider, like _https://idp.example.com/account/manage_ or _https://idp.example.com/admin/create-client_ .
How would I design a local login?

For example:
User goes to idp.example.com to just create a session with the idp (no redirect to other pages/clients)
Should user gets redirected to 
_https://idp.example.com/login_
 or 
_https://idp.example.com/auth?client_id=local&response_type=id_token&scope=openid&nonce=foobar&prompt=login_
?
For latter I have to create a special "local" client. Would the redirect uri for example be _https://idp.example.com/account_ ?
(For development: Why can't I then not redirect to localhost?)

If a user then goes to an application after that, he will get redirected to the auth (interaction) endpoint and should instantly gets redirected back to the application since he has a session with the idp.

How can I skip the page where it shows the claims and the continue button? Or would that be a bad idea?

Are there even example projects for that?
Or can I even implement my own session management with passport for example?

Another issue: Resume-cookies are created, ever time I call the auth/interaction endpoint and get never deleted. Even not after successful login. Is that wanted? How can I prevent that?

Hope you get my points and you can bring some light to me :) thx

**Comment by panva** [comment]
> Should user gets redirected to
> idp.example.com/login
> or
> idp.example.com/auth?client_id=local&response_type=id_token&scope=openid&nonce=foobar&prompt=login

You can either set up a local client or use any out of band authentication mechanism on any of your pages with credentials and use `provider.setProviderSession` to establish the session. 

> (For development: Why can't I then not redirect to localhost?)

For something like this you should probably use a strong authentication confidential client and grant_type code. But the restriction to localhost comes from the spec and there are plenty of issues i've answered as to why I don't allow that.

> How can I skip the page where it shows the claims and the continue button? Or would that be a bad idea?

See https://github.com/panva/node-oidc-provider/tree/master/docs#interactions

> Are there even example projects for that?
> Or can I even implement my own session management with passport for example?

No projects, no examples i worked on. This is a protocol implementation library, if you wish to step outside of the protocol - you have to figure it out on your own.

> Another issue: Resume-cookies are created, ever time I call the auth/interaction endpoint and get never deleted. Even not after successful login. Is that wanted? How can I prevent that?

`resume` cookies are being deleted at the resume path by the OP, `interaction` cookies are not and if you want to clean up you can do so as part of your code. That being said the cookies are short duration (will be dropped by user-agent cookie jar by default in 10minutes) and without the underlying `Interaction` object in the db which gets deleted as part of the resume path are useless.

---

I would recommend going with a local client and adjusting the interaction policy to allow for consent-less flow for this particular client. You'll only have one way of logging in resulting in one less thing to worry about.
