### ISSUE TITLE
Logout without prompt

### ISSUE THREAD

**Issue by javlund** [panva/node-oidc-provider#536]
I'm looking for a way to have the RP log out the user from the OP without directing the user through a prompt.

I have read the [spec](https://openid.net/specs/openid-connect-session-1_0.html#RPLogout) on this matter and realize that it states that "the OP SHOULD ask the End-User whether he wants to log out of the OP as well", and that OIDC-Provider as a faithful provider adheres to this. On the other hand, I see that some other providers are taking more liberal approaches - for instance, [here](http://docs.identityserver.io/en/latest/endpoints/endsession.html) is an example of a provider that chooses to omit the prompt if the recommended `id_token_hint` is present in the request.

I have searched the issue tracker and know this topic has been up before (e.g. in https://github.com/panva/node-oidc-provider/issues/66 and https://github.com/panva/node-oidc-provider/issues/223, the latter suggesting a self-submitting form as a workaround) so I'm thinking I might not be the only person who would like this. As going with a solution like the one where the presence of the `id_token_hint` would trigger a promptless logout would not be directly in violation of the spec, if I understand the word "SHOULD" correctly, I think it would be great to have a feature to turn such a thing on. Basically like the `conformIdTokenClaims` feature that is also not vanilla OIDC but useful in some situations.

**Comment by panva** [comment]
Hi @javlund,

using `logoutSource` and defining the conditions under which you want to go "promptless" ergo rendering a self-submitting is the only way I want to support.

There's a lot of logic in the confirm prompt action that i do not wish to duplicate to the end_session_endpoint.

I considered yet another helper function that controls whether `logoutSource` or a static self-submit is called but I feel you can do the same inside the existing logoutSource helper anyway.

**Comment by javlund** [comment]
Thanks for a blazingly fast response again!

I would love an option to have the endpoint act as a self-submitting form as I believe it's a common usecase and would spare several developers from a bunch of boilerplate, but understand if it's not a priority.

**Comment by panva** [comment]
> believe it's a common usecase

If that's the case people will chime in on either of the existing issues. If the issues guide them to `logoutSource` or a new helper function i don't think makes a difference.

`logoutSource` should be updated by everyone anyway so i don't think of this as boilerplate.
