### ISSUE TITLE
findAccount invoked on request at Auth-Endpoint

### ISSUE THREAD

**Issue by bob-sheknowdas** [panva/node-oidc-provider#537]
Hi,

I'm observing, that the findAccount-method is invoked when a client sends a request to the auth-endpoint.

What i found in your source code is, that you [bind findAccount to 'authorization'](https://github.com/panva/node-oidc-provider/blob/aaf5740df8d7fad766ae8225449b9c1a6907494b/lib/actions/authorization/index.js#L150).

I'm handling my authentication logic on my own in a dedicated method that is invoked via 

```
app.post(BASE_URL + '/interaction/:uid/login', parse, (req, res, next) => {
  accountManager.authenticate(body.username, body.password)
  ...
}
```

There is no need for me to call findAccount at the moment of authorization.

The moment I need to call findAccount is the moment of a request to the token endpoint.

Is there a way to stop oidc-provider from invoking findAccount on every request to the auth-endpoint?

**Comment by panva** [comment]
@bob-sheknowdas `findAccount` is called to confirm the account in the session is "still there". If you wish to make the findAccount a no-op, you can, the claims() method can also be async.
