### ISSUE TITLE
Support Multiple Databases

### ISSUE THREAD

**Issue by phwowcs** [panva/node-oidc-provider#538]
Hi @panva 

Firstly, thank you for making a cool library!
My authentication service needs to support a database for each customer. Could you please give me a hint about the best way to handle this use case? Thank you so much.

**Comment by panva** [comment]
@phwowcs switching storage based on contextual information is something you can place in your adapter (entity storage such as tokens), similarly the `findAccount` helper can switch the used storage based on context.

All of javascript language is available to you.

**Comment by phwowcs** [comment]
Fast support! Thanks @panva 
I have a concern here, how an adapter knows the context to switch between multiple database connections for each request?

**Comment by panva** [comment]
@phwowcs i was always reluctant to add `ctx` to the adapter, which part of the context do you depend on to decide on the storage?

**Comment by phwowcs** [comment]
@panva I'm not sure about this, but I need something like that: 
Each request will have a header or a query param contains the database connection info ( as I said before each customer will have a database ), after that, I want the adapter to use this database connection.
Thanks for the great support.

**Comment by panva** [comment]
I think you may wanna use multiple Provider instances on different domains (tenants) instead.

**Comment by phwowcs** [comment]
Got it. Thank you!
By the way, just one more question, can we have multiple instances of Provider in one Express app?

**Comment by panva** [comment]
so long as you mount or execute their callbacks properly, yes.

**Comment by phwowcs** [comment]
awesome, thanks!
