### ISSUE TITLE
invalid_client_metadata with grant_type "implicit" and response_type "id_token token"

### ISSUE THREAD

**Issue by thecopy** [panva/node-oidc-provider#539]
**Describe the bug**
Im getting
```
error: invalid_client_metadata
error_description: response_types can only contain members [code id_token,code,id_token,none]
```

For this client configuration:
```js
{
    client_id: 'client',
    client_secret: 'secret',
    grant_types: ['implicit', 'authorization_code'],
    response_types: ['id_token', 'id_token token', 'code token', 'none'],
    redirect_uris: ['https://dev.local:4443/']
}
```

**To Reproduce**
Provider and Client configuration: (inline or gist)
```js
// provider configuration
const oidc = new OidcProvider("https://dev.local/", {
  clients: [
    {
      client_id: 'client',
      client_secret: 'secret',
      grant_types: ['implicit', 'authorization_code'],
      response_types: ['id_token', 'id_token token', 'code token', 'none'],
      redirect_uris: ['https://dev.local:4443/']
    },
  ],
  features: {
    devInteractions: {enabled: true },
    ietfJWTAccessTokenProfile: { enabled: true },
    introspection: { enabled: true }
  },
  jwks: JWKs
})
```
// keystore(s) - if they affect the behaviour
```
none
```
// client(s) configuration
```js
{
    client_id: 'client',
    client_secret: 'secret',
    grant_types: ['implicit', 'authorization_code'],
    response_types: ['id_token', 'id_token token', 'code token', 'none'],
    redirect_uris: ['https://dev.local:4443/']
}
```

Steps to reproduce the behaviour:

1.  Create this file:

`index.ts`:
```
import Koa from 'koa'
import mount from 'koa-mount'
import { Provider as OidcProvider } from 'oidc-provider';

const app = new Koa()

const oidc = new OidcProvider("https://dev.local/", {
  clients: [
    {
      client_id: 'client',
      client_secret: 'secret',
      grant_types: ['implicit', 'authorization_code'],
      response_types: ['id_token', 'id_token token', 'code token', 'none'],
      redirect_uris: ['https://dev.local:4443/']
    },
  ],
  features: {
    devInteractions: {enabled: true },
    ietfJWTAccessTokenProfile: { enabled: true },
    introspection: { enabled: true }
  }
})
app.proxy = true
app.use(mount(oidc.app));

app.listen(3000)
```

2. Install dependencies: `
npm install @types/koa @types/koa-mount @types/node koa koa-mount oidc-provider typescript`
3.  Build and start server: `npx tsc --esModuleInterop index.ts && node ./index.js`
4.  Make GET request to http://localhost:3000/auth?client_id=client&response_type=id_token%20token&redirect_uri=https%3A%2F%2Fdev.local%3A4443%2F&scope=openid%20email%20&audience=https%3A%2F%2Fdev.local%2F

**Expected behaviour**
1. I expect to be able to use `token id_token` response type with `oidc-provider` when using `implicit` grant_type.
2. I expect to be presented with the login-form from devInteractions.

**Environment:**
 - oidc-provider version: v6.12.3
 - node version: v12.7.0

**Additional context**

 - [x] the bug is happening on latest oidc-provider too.
 - [x] i have tried DEBUG (see README) and can see the issue is with the provider and not my code.
 - [x] i have searched the issues tracker on github for similar issues and couldn't find anything related.
 - [x] i have searched the [FAQ](https://github.com/panva/node-oidc-provider/wiki/FAQ) and couldn't find anything related.

**Logs**

**Comment by panva** [comment]
https://github.com/panva/node-oidc-provider/blob/v6.12.3/docs/README.md#responsetypes

`id_token token` is not enabled by default as it is no longer recommended for use by new application by the IETF OAuth 2.0 WG.

**Comment by thecopy** [comment]
> https://github.com/panva/node-oidc-provider/blob/v6.12.3/docs/README.md#responsetypes
> 
> `id_token token` and `code token` are not enabled by default as it is no longer recommended for use by new application by the IETF OAuth 2.0 WG. You can enable it if you need it tho. Using the above linked configuration property.

Thank you.
