### ISSUE TITLE
DynamoDB Adapter?

### ISSUE THREAD

**Issue by ianmobbs** [panva/node-oidc-provider#540]
I've seen in a few issues that there are a couple known implementations of a DynamoDB Adapater for `node-oidc-provider` - I was wondering if you could link them, or include an example of one in the `example/adapaters/` folder? In addition to this, it would be awesome if there was some sort of data model explaining the tables, fields, attributes, and indices needed. I've seen the [my_adapter](https://github.com/panva/node-oidc-provider/blob/master/example/my_adapter.js) bit, but I'm having trouble figuring out what is needed to store. I'd be happy to submit an MR if you could link me to some examples :)

**Comment by panva** [comment]
All examples i have at hand are already in that folder + all access patterns are described in the adapter file and docs. That ought to be enough to get started. 

If you do indeed wish to contribute your sample when you’re done, we will for sure welcome the contribution.

**Comment by ianmobbs** [comment]
Thanks @panva! I was just hoping you'd be able to link to a specific DynamoDB examples you've said you've seen [here](https://github.com/panva/node-oidc-provider/issues/126#issuecomment-312714426). I have seen the [mongodb adapter](https://github.com/panva/node-oidc-provider/blob/master/example/adapters/mongodb.js) already.

**Comment by panva** [comment]
It shouldn’t come as a surprise that i’m not able to share and disclose source code that i’m not an author or an owner of.

**Comment by ianmobbs** [comment]
Ah, I assumed they were open source implementations, not closed source - considering the platform we're on :)
