### ISSUE TITLE
Return Types in Adapter

### ISSUE THREAD

**Issue by alvis** [panva/node-oidc-provider#541]
Should `void` instead of `undefined` be the right type in the return of `upsert`, `consume`, `destroy` & `revokeByGrantId` of Adapter?

If it's `undefined`, it imples that these functions must expliticly return `undefined`.

https://github.com/panva/node-oidc-provider/blob/a842b7123854ee5ac5f6b30fd2c53a9ef8b11d5d/types/index.d.ts#L779
https://github.com/panva/node-oidc-provider/blob/a842b7123854ee5ac5f6b30fd2c53a9ef8b11d5d/types/index.d.ts#L783-L785

**Comment by panva** [comment]
Just following what `dtslint` said here. If that's not the norm in TS please let me know i'll add void back and silence the linter instead.

**Comment by alvis** [comment]
Unless you expect an explicit return, which I don't think so, the return type should be void.
See https://github.com/microsoft/dtslint/blob/master/docs/void-return.md

To demostrate, here are some examples

```ts
// NOT OK  TS2355: A function whose declared type is neither 'void' nor 'any' must return a value.
function test1(): undefined {}

// okish but the linter would complain
function test2(): void {
  return undefined;
}

// ok
function test3(): void {}

// ok
function test4(): void {
  return;
}

// ok
function test5(): undefined {
  // you must explicitly return in order to pass
  return;
}

// ok
function test6(): undefined {
  return undefined;
}
```
