### ISSUE TITLE
cookie management

### ISSUE THREAD

**Issue by bob-sheknowdas** [panva/node-oidc-provider#546]
Hi,

I'm trying to set custom cookies. 
As suggested [here](https://github.com/panva/node-oidc-provider/issues/343) I'm trying to set the cookies in a custom post-middleware.

however, that doesn't seem to work.
No cookie is created...

My code looks like this:
```
    provider.use(async (ctx, next) => {
      await next();
      if(ctx.oidc && ctx.oidc.route === 'token'){
        ctx.oidc.cookies.set(
          'key',
          'value',
          {
            secure: undefined,
            signed: true,
            httpOnly: true,
            maxAge: 1209600000
          });
      }
    });
```

Am I doing anything wrong here?

**Comment by panva** [comment]
> No cookie is created...

`set-cookie` headers are being returned with the response when i try your post middleware.

> however, that doesn't seem to work.

What do you expect happens? What use do you have for returning `set-cookie` headers from a token endpoint call?
