### ISSUE TITLE
Question: Own session handling

### ISSUE THREAD

**Issue by kareha** [panva/node-oidc-provider#547]
Hi,

is it possible to have an own session handling like "express-session" or "cookie-session" combined with passport for example?

The reason behind that is, that it would allow to add another type of provider like saml, and both could share the same single sign on or provider login session.

Is there a way of telling oidc-provider how to start a session and how to check for a session? 

Or maybe you have another idea of how to implement that issue in a proper way :)

Thanks in advance!
Kind regards

**Comment by panva** [comment]
> is it possible to have an own session handling like "express-session" or "cookie-session" combined with passport for example?

There is not.

> Is there a way of telling oidc-provider how to start a session and how to check for a session?

You can force a session on the provider during a request using `provider.setProviderSession`, you can't change "how to check a session exists"

> Or maybe you have another idea of how to implement that issue in a proper way :)

Custom session model overrides, interaction policy to begin with. It's not intended tho so i can't guarantee you'll manage you'll manage to do it.
