### ISSUE TITLE
Dev interactions don't work with mountPath other than '/'

### ISSUE THREAD

**Issue by marekmicek** [panva/node-oidc-provider#548]
**Describe the bug**
When using a mountPath as described in https://github.com/panva/node-oidc-provider/blob/master/docs/README.md#mounting-oidc-provider the dev interactions POST action URL still points to the '/interactions/<%= uuid %>'

**To Reproduce**

```js
const prefix = '/oidc';
expressApp.use(prefix, oidc.callback);
```

Steps to reproduce the behaviour:

1.  Made a valid request to the provider, that would require the redirection to the dev interactions
2.  Provide a sample login details
3.  Click Sign-in

**Expected behaviour**
The dev interactions should proceed to the next step, but the post URL is not correct (doesn't have the configured prefix included)

**Comment by panva** [comment]
Thank you for raising this @marekmicek
