### ISSUE TITLE
TS "policies" type

### ISSUE THREAD

**Issue by thomasvargiu** [panva/node-oidc-provider#551]
Hi,

the configuration "features.registration.policies" type doesn't allow use of async functions.

I suggest to change it from:
```
policies?: {
    [key: string]: (ctx: KoaContextWithOIDC, metadata: ClientMetadata) => void | undefined;
};
```
to:
```
policies?: {
    [key: string]: (ctx: KoaContextWithOIDC, metadata: ClientMetadata) => void | undefined;
};
```

**Comment by panva** [comment]
@thomasvargiu thanks for reporting this. It'll be included in the next release.
