### ISSUE TITLE
Signing JWT Access Tokens per client

### ISSUE THREAD

**Issue by kareha** [panva/node-oidc-provider#554]
Hi,

is there a way to set a asymmetric key pair for signing the jwt access tokens (jwt-ietf) per client?
For example create a pair, set the private key at client object and put the public key at the resource server?

If not, how is the proper way for a resource server validating an access token?

Thank you!
Kind regards

**Comment by panva** [comment]
Hi @kareha 

There's no way to have client specific asymmetric keys to sign assertions with. Everything the provider signs comes from its keystore that it publishes at the `jwks_uri`.
