### ISSUE TITLE
Deleting the dynamically created client does not delete the registration access token

### ISSUE THREAD

**Issue by tedbellhop** [panva/node-oidc-provider#555]
Hi,

Deleting the dynamically created client does not delete the registration access token associated with that client.

This is how I have my dynamic client registration features configured, rest of the configuration is as in your [example](https://github.com/panva/node-oidc-provider/blob/master/example/support/configuration.js):
```
features: {
    registration: {
        enabled: true,
        initialAccessToken: "initial.access.token"
    },
    registrationManagement: {
        enabled: true
    }
}
```

I've also tried rotating the registration access tokens (`features.registrationManagement.rotateRegistrationAccessToken = true`), but it did not solve the issue.

I'm using the version `6.12.11` of `oidc-provider`.

This is how my registration request looks like:
```
curl -X POST \
  http://localhost:3000/reg \
  -H 'Accept: */*' \
  -H 'Accept-Encoding: gzip, deflate' \
  -H 'Authorization: Bearer initial.access.token' \
  -H 'Cache-Control: no-cache' \
  -H 'Connection: keep-alive' \
  -H 'Content-Length: 71' \
  -H 'Content-Type: application/json' \
  -H 'Host: localhost:3000' \
  -d '{
    "redirect_uris": [
        "https://localhost:3001/callback"
    ]
}'
```

And the registration response:
```
{
    "application_type": "web",
    "grant_types": [
        "authorization_code"
    ],
    "id_token_signed_response_alg": "RS256",
    "post_logout_redirect_uris": [],
    "require_auth_time": false,
    "response_types": [
        "code"
    ],
    "subject_type": "public",
    "token_endpoint_auth_method": "client_secret_basic",
    "request_uris": [],
    "client_id_issued_at": 1571744596,
    "client_id": "kdRokUE5BZa2cHdN5sRQN",
    "client_secret_expires_at": 0,
    "client_secret": "xknQmxJMwHd1nwtqCqxjl_AtcAeC5KfM5saudzIdoc2GHL7GmEFH1pjvx72ja4KW2fuDbE8D3Xc9z9UVndBy5A",
    "redirect_uris": [
        "https://localhost:3001/callback"
    ],
    "registration_client_uri": "http://localhost:3000/reg/kdRokUE5BZa2cHdN5sRQN",
    "registration_access_token": "xJbTMUpKRO-okddV5uDFRINc6ZsBFa0LmD6_o8vb98W"
}
```

Delete request is as follows:
```
curl -X DELETE \
  'http://localhost:3000/reg/kdRokUE5BZa2cHdN5sRQN?access_token=xJbTMUpKRO-okddV5uDFRINc6ZsBFa0LmD6_o8vb98W' \
  -H 'Accept: */*' \
  -H 'Accept-Encoding: gzip, deflate' \
  -H 'Cache-Control: no-cache' \
  -H 'Connection: keep-alive' \
  -H 'Content-Length: 0' \
  -H 'Content-Type: application/x-www-form-urlencoded' \
  -H 'Host: localhost:3000' \
```

Thanks in advance!

**Comment by panva** [comment]
Hi @tedbellhop,

nice catch, i'll add a test and fix soon.

**Comment by tedbellhop** [comment]
Thanks for the reply!

There seems to be a related bug though.

Making a delete request to non-existing client (non-existing `uid`) with `features.registrationManagement.rotateRegistrationAccessToken` set to `true`, removes the `RegistrationAccessToken` even if that token already belongs to existing client.

Example request:
```
curl -X DELETE \
  'http://localhost:3000/reg/THIS-CLIENT-DOES-NOT-EXIST?access_token=xJbTMUpKRO-okddV5uDFRINc6ZsBFa0LmD6_o8vb98W' \
  -H 'Accept: */*' \
  -H 'Accept-Encoding: gzip, deflate' \
  -H 'Cache-Control: no-cache' \
  -H 'Connection: keep-alive' \
  -H 'Content-Length: 0' \
  -H 'Content-Type: application/x-www-form-urlencoded' \
  -H 'Host: localhost:3000' \
```

**Comment by panva** [comment]
That's not a bug but intended

>   If the client does not exist on this server, the server MUST respond
>   with HTTP 401 Unauthorized and the registration access token used to
>   make this request SHOULD be immediately revoked, if possible.

**Comment by tedbellhop** [comment]
Thanks for clarification.

Is there a way to reissue the access token for the client in that case, or should client re-register?

**Comment by panva** [comment]
```js
const rat = new provider.RegistrationAccessToken({ clientId, ... });
const token = await token.save();
```
