### ISSUE TITLE
no refresh token returned when token_endpoint_auth_method not set to none

### ISSUE THREAD

**Issue by stefdaems** [panva/node-oidc-provider#556]
**Describe the bug**
When the token_endpoint_auth_method is not set to none, the refresh token is never returend upon the /token request.
eg.
{
    client_id: 'test_website',
    client_secret: 'test',
    grant_types: ['authorization_code', 'refresh_token'],
    response_types: ['code'],
    redirect_uris: ['https://openidconnect.net/callback'],
    token_endpoint_auth_method: 'client_secret_basic'
}

**Expected behaviour**
I expect the refresh token to be returned, so the app still needs to do the basic auth verification using client_id and client_secret. 

**Environment:**
 - oidc-provider version: v6.6.2
 - node version: v12.10.0

 - [x ] the bug is happening on latest oidc-provider too.
 - [ x] i have tried DEBUG (see README) and can see the issue is with the provider and not my code.
 - [ x] i have searched the issues tracker on github for similar issues and couldn't find anything related.
 - [x ] i have searched the [FAQ](https://github.com/panva/node-oidc-provider/wiki/FAQ) and couldn't find anything related.

**Comment by amaciver** [comment]
https://github.com/panva/node-oidc-provider/tree/master/docs#issuerefreshtoken this might be what you are looking for

**Comment by stefdaems** [comment]
scope: openid offline_access, is set in the request for authorization
grant_types: refresh_token is set in the client config

according to the default config, this should return true so the refresh token should be returned... no?

**Comment by panva** [comment]
Your request is probably missing `prompt=consent` that's why scope offline_access is ignored and pulled from the scopes.

There have been similar issues opened in the past, the FAQ has an entry about this and its totally unrelated to token endpoint auth method.
