### ISSUE TITLE
supported responseTypes not validated before oidc required

### ISSUE THREAD

**Issue by joolfe** [panva/node-oidc-provider#558]
**Describe the bug**
When oidc-provider is configured with only response type of value 'code' ( in config `responseTypes: ['code']`) and we send in an authorize request a response type of 'id_token', is not failing because unsupported response type, is asking for a nonce with an error "missing required parameter 'nonce'"

**To Reproduce**

I have a create a repo with some test that reproduce the error here 'https://github.com/joolfe/node-oidc-provider-issues'

Steps to reproduce the behaviour:

1.  Download the example code from 'https://github.com/joolfe/node-oidc-provider-issues'
2.  execute `npm install`
3.  execute test using `npm run test-responseType`

**Expected behaviour**
The server should return a "unsupported_response_type" because the response type 'id_token' is not supported by the server. No have sense to ask for a parameter required by 'id_token' response type when this response type is not supported.

**Environment:**
 - oidc-provider version: v6.12.11
 - node version: v10.16.3
 - npm version: 6.9.0

**Additional context**
The problem seem to be related with middleware order, if we look on lib/actions/authorization/index.js file the "checkResponseType" middleware is below the "oidcRequired" middleware, but this check don't have sense if the response type is not supported.

**Comment by panva** [comment]
Hi @joolfe 

there are validations bound to run before others, i'm happy to move this validation up the middleware stack tho. Expect a "fix" soon.
