### ISSUE TITLE
Incorrect private_key_jwt return 400 instead 401.

### ISSUE THREAD

**Issue by joolfe** [panva/node-oidc-provider#559]
**Describe the bug**
When using 'private_key_jwt' authentication, if the jwt is incorrect (not follow rules described in https://openid.net/specs/openid-connect-core-1_0.html#ClientAuthentication) for example don't have claim sub, oidc-provider is returning a 400 error and should be a 401 Unauthorized

**To Reproduce**
I have a create a repo with some test that reproduce the error here 'https://github.com/joolfe/node-oidc-provider-issues'

Steps to reproduce the behaviour:

1.  Download the example code from 'https://github.com/joolfe/node-oidc-provider-issues'
2.  execute `npm install`
3.  execute test using `npm run test-authError`

**Expected behaviour**
Should return a 401 error because this is an authentication error.

**Environment:**
 - oidc-provider version: v6.12.11
 - node version: v10.16.3
 - npm version: 6.9.0

**Additional context**
When incorrect jwt format as for exmaple one claim is missing should return a 401 error not a 400. In function findClientId is only returning 400 errors but sme errors are auth fails.

**Comment by panva** [comment]
Hi @joolfe 

> When incorrect jwt format as for exmaple one claim is missing should return a 401 error not a 400

Why? When the format is incorrect, its clearly an invalid_request and as it'll never pass even if you changed the existing claims.

Once the token is passable as a client_assertion for the server, at that time the error becomes 401 and it swallows the validation message as to not give any clue about what to change to the attacker. Before this, the format to follow is clear and comes from a specification, hence a 400 invalid_request with a clear error message works.

Happy to discuss but this I'll likely not change as i think developers need the feedback to get their assertions in order.

**Comment by panva** [comment]
The 400 in the example is not normative. invalid_client can be either 400 or 401 depending on the context. invalid_request on the other hand is always 400.

I guess it depends on the point at which is the assertion is deemed "acceptable".

The specification is followed once the general token request with client assertion auth format gets satisfied.



```js
// i don't consider these requests valid and wish to let developers know what's wrong
let sub;
try {
  ({ payload: { sub } } = JWT.decode(clientAssertion));
} catch (err) {
  throw new InvalidRequest('invalid client_assertion format');
}

if (clientId && sub !== clientId) {
  throw new InvalidRequest('subject of client_assertion must be the same as client_id provided in the body');
}

if (clientAssertionType === undefined) {
  throw new InvalidRequest('client_assertion_type must be provided');
}

if (clientAssertionType !== assertionType) {
  throw new InvalidRequest(`client_assertion_type must have value ${assertionType}`);
}
```

```js
// i consider these assertions already good enough and don't expose any details via error_description, the error is delivered to the deliver out of band via the emitted error and its error_detail (not exposed via responses).

if (!algorithms.includes(header.alg)) {
  throw new InvalidClientAuth('alg mismatch');
}

if (!payload.exp) {
  throw new InvalidClientAuth('expiration must be specified in the client_assertion JWT');
}

if (!payload.jti) {
  throw new InvalidClientAuth('unique jti (JWT ID) must be provided in the client_assertion JWT');
}

if (!payload.iss) {
  throw new InvalidClientAuth('iss (JWT issuer) must be provided in the client_assertion JWT');
}

if (payload.iss !== ctx.oidc.client.clientId) {
  throw new InvalidClientAuth('issuer (iss) must be the client id');
}

if (!payload.aud) {
  throw new InvalidClientAuth('aud (JWT audience) must be provided in the client_assertion JWT');
}

if (Array.isArray(payload.aud)) {
  if (!payload.aud.some((aud) => acceptedAud.has(aud))) {
    throw new InvalidClientAuth('list of audience (aud) must include the endpoint url, issuer identifier or token endpoint url');
  }
} else if (!acceptedAud.has(payload.aud)) {
  throw new InvalidClientAuth('audience (aud) must equal the endpoint url, issuer identifier or token endpoint url');
}

try {
  await JWT.verify(ctx.oidc.params.client_assertion, keystore, {
    clockTolerance: instance(provider).configuration('clockTolerance'),
    ignoreAzp: true,
  });
} catch (err) {
  throw new InvalidClientAuth(err.message);
}

const unique = await provider.ReplayDetection.unique(payload.iss, payload.jti, payload.exp);

if (!unique) {
  throw new InvalidClientAuth('client assertion tokens must only be used once');
}
```

**Comment by joolfe** [comment]
I understand perfectly what you mean, and seems like neither oauth or openid specify exactly what to do in this situations... 

But from my point of view security layer is on top of all other layers so if for any reason the "client credential" that is being sent is not valid (and this include incorrect format or missing parts) the server should return a "invalid_client" and don't do more validations. Fulfil security must be a precondition to process the request...

About status code I think a 401 is more meanfull in this situations but reading the "OAuth Assertion Framework" spec seem like 400 is also valid...

About "developers need the feedback to get their assertions in order" when we talk about security less info is more secure so you can avoid guessing attacks, returning a "invalid_client" code must be enough info to review how credentials are being generated and sent in my opinion.

Im going to open a ticket in the openId bitbucket to see if they have a opinion or is just a implementation decision. :-) 

Best Regards.

**Comment by joolfe** [comment]
Yes, and also is in violation of 6749 about the status code because Oauth say:

> invalid_client
               Client authentication failed (e.g., unknown client, no
               client authentication included, or unsupported
               authentication method).  **The authorization server MAY
               return an HTTP 401** (Unauthorized) status code to indicate
               which HTTP authentication schemes are supported.  If the
               client attempted to authenticate via the "Authorization"
               request header field, the authorization server MUST
               respond with an HTTP 401 (Unauthorized) status code and
               include the "WWW-Authenticate" response header field
               matching the authentication scheme used by the client.

But because the "OAuth Assertion Framework" is an extension is allowed to modify the behaviour of the base RFCs because you are amending behaviours.

I have open the question here https://bitbucket.org/openid/connect/issues/1121/client-authentication-error

Best Regards.

**Comment by panva** [comment]
But because the "OAuth Assertion Framework" is an extension is allowed to modify the behaviour of the base RFCs because you are amending behaviours.

I doubt you'll get a sign-off on this statement.

Example: when a client submits both authorization header and a client_secret, following 6749 its an invalid_request. But following your explanation, when the client submits an authorization header and a client_assertion its an invalid_client all of a sudden?

That just doesn't click.

I could get behind moving these two into token_jwt_auth

```js
          let sub;
          try {
            ({ payload: { sub } } = JWT.decode(clientAssertion));
          } catch (err) {
            throw new InvalidRequest('invalid client_assertion format');
          }

          if (clientId && sub !== clientId) {
            throw new InvalidRequest('subject of client_assertion must be the same as client_id provided in the body');
          }
```

But these two stay and throw invalid_request, together with multiple auth, following 6749

```js
          if (clientAssertionType === undefined) {
            throw new InvalidRequest('client_assertion_type must be provided');
          }

          if (clientAssertionType !== assertionType) {
            throw new InvalidRequest(`client_assertion_type must have value ${assertionType}`);
          }
```

**Comment by joolfe** [comment]
About
> Example: when a client submits both authorization header and a client_secret, following 6749 its an invalid_request. But following your explanation, when the client submits an authorization header and a client_assertion its an invalid_client all of a sudden?

Yes i know, Openid + oAuth + extension, are clashing all the time... but for the concrete case of the "client_assertion" 6749 don't say anything about how to manage this, is even not mention in 6749, so in theory if you want to use this kind of client authentication (the extension) you should follow the rules described in "OAuth Assertion Framework" and make this rules supersede the existing ones in 6749, not all rules i mean just the ones related with "client_assertion" usage.

Anyway reading the response in https://bitbucket.org/openid/connect/issues/1121/client-authentication-error the returned error seem to be a implementation decision so is up to you :-)

Thanks for your time!
Best Regards

**Comment by panva** [comment]
Cool, i’ll mull it over again but will probably not change anything at this point. 

Thanks for raising the issues, i appreciate the discussion.
