### ISSUE TITLE
Is there a method to validate tokens?

### ISSUE THREAD

**Issue by bob-sheknowdas** [panva/node-oidc-provider#560]
Does oidc-provider expose a convenience method to validate tokens?

I'm not talking about the introspection endpoint.
Im talking about a js method I can call from my code...

I need to extend my express app by adding some extra non-oidc-functions.
But I want to make these functions accessable only for requests containing a valid bearer token...

I searched through the [provider](https://github.com/panva/node-oidc-provider/blob/master/lib/provider.js) as well as through the [introspection action ](https://github.com/panva/node-oidc-provider/blob/75fa44fa893d201b54892f52abd871c4c16f7c40/lib/actions/introspection.js).
But I couldnt find any methode that just requires a token and then tells you if this token is valid...

**Comment by panva** [comment]
Hi @bob-sheknowdas 

There's no such a thing.

You can do this

```js
const token = await provider.AccessToken.find(value);
```

and then check its scope, audience, clientId, grantId, and/or sender constraining mechanisms as the other resource endpoint (userinfo) does.

**Comment by bob-sheknowdas** [comment]
Thanks for your fast reply.

My Issue with that solution:
Im using an express app, not koa. So I dont have access to the koa ctx object and therefor no access to ctx.oidc.getAccessToken.

provider.AccessToken.find(value) does not work with the simple token string that I get from the request header.

Also, you are not using JWTs for the access tokens, so that I could verify the signature part of the token with the public key.

Could you please provide some additional hints on how I could get this working?

**Comment by bob-sheknowdas** [comment]
Oh, I just had a really stupid mistake in my code.
Sry for not looking properly -.-

Everythink works now as expected.
Thank you very much.
