### ISSUE TITLE
Default path is incorrect for code_verification when using device flow

### ISSUE THREAD

**Issue by raymondsze** [panva/node-oidc-provider#561]
**Describe the bug**

<img width="1079" alt="Screenshot 2019-10-24 at 7 37 47 PM" src="https://user-images.githubusercontent.com/15674149/67482242-fefc0500-f695-11e9-9152-f455115b21e3.png">
The form 'action' should be `/oidc/device` instead.

**To Reproduce**
Provider and Client configuration: (inline or gist)
```js
// provider configuration
app.use('/oidc', provider.callback);
```

**Expected behaviour**
The form 'action' should be `/oidc/device` instead.

**Environment:**
 - oidc-provider version: [e.g. v4.3.0]
 - node version: [e.g. v8.9.0]

**Additional context**

 - [x] the bug is happening on latest oidc-provider too.
 - [x] i have tried DEBUG (see README) and can see the issue is with the provider and not my code.
 - [x] i have searched the issues tracker on github for similar issues and couldn't find anything related.
 - [x] i have searched the [FAQ](https://github.com/panva/node-oidc-provider/wiki/FAQ) and couldn't find anything related.

**Logs**

**Comment by panva** [comment]
Thanks for reporting this. It'll be fixed with the next v6.x release.
