### ISSUE TITLE
PKCE question

### ISSUE THREAD

**Issue by joolfe** [panva/node-oidc-provider#562]
Hi,

Just a question about PKCE feature, Is there a reason why the PKCE feature is mandatory when using a native app and "code" response type? i mean, why is not a enable/disable feature like others?

Thanks in advance!

**Comment by panva** [comment]
@joolfe https://tools.ietf.org/html/rfc8252

> Section 6 requires that both clients and servers use PKCE for public
> native app clients.  Authorization servers SHOULD reject
> authorization requests from native apps that don't use PKCE by
> returning an error message, as defined in Section 4.4.1 of PKCE
> [RFC7636].

**Comment by joolfe** [comment]
Great thanks!!
