### ISSUE TITLE
Can node-oidc-provider work with Nestjs?

### ISSUE THREAD

**Issue by phuongduongcxagroup** [panva/node-oidc-provider#563]
Hi. Currently I'm using Nestjs ask a framework for my nodejs project.
I need to implement node-oidc-provider package.
Do you think the node-oidc-provider will work well with Nestjs.
Please help. Thanks

**Comment by panva** [comment]
I really have no idea, so long as you can mount a node style http listener `(req, res)` returned by `provider.callback` it should be fine.

**Comment by yogevlahyani** [comment]
@panva 
Can you reopen this issue?

I'm trying to integrate oidc-provider with nest with no luck
Maybe you can take a look

https://github.com/yogevlahyani/nest-oidc-provider

**Comment by panva** [comment]
> Can you reopen this issue?

To what end?

> Maybe you can take a look

It is not my intention to work out every integration myself. If <insert framework> can deal with pushing its execution down to a bare node.js `(req, res)` style middleware it'll work.

**Comment by yogevlahyani** [comment]
> > Can you reopen this issue?
> 
> To what end?
> 
So we can start a discussion on integrating this library with Nest
> > Maybe you can take a look
> 
> It is not my intention to work out every integration myself. If `<insert framework>` can deal with pushing its execution down to a bare node.js `(req, res)` style middleware it'll work.

I tried it in the example, the thing is that the middleware overrides all endpoints without any option to override the library endpoint with my own login

**Comment by panva** [comment]
> So we can start a discussion

There's a classic node style middleware exposed that needs to be executed for e.g. a whole route namespace (see [hapi](https://github.com/panva/node-oidc-provider/tree/master/docs#to-a-hapi-application)) with the raw req and res while not parsing the request body. There's nothing else.

I can jump in the moment you have the endpoints executing but routing doesn't work right. Before than, I really can't do much.
