### ISSUE TITLE
Interaction routing doesn't work on v6.x.x with AWS lambda

### ISSUE THREAD

**Issue by tmedanovic** [panva/node-oidc-provider#565]
**Describe the bug**

Same koa mounting (or routing?) code that correctly works on v4.x.x doesn't work on v6.x.x.
I can GET .well-known/openid-configuration correctly (jwks also) but when the client initiates implicit flow i get following:

![image](https://user-images.githubusercontent.com/5676600/67958594-b5f90300-fbf7-11e9-859f-db772997408c.png)

![image](https://user-images.githubusercontent.com/5676600/67958606-ba252080-fbf7-11e9-9ef7-6ce136bae91b.png)

After that I somehow end up at https://xxxxxx/interaction/RS_p9zte1oM6zjsy0GvXA (without dev prefix)

And if i try to go to same route with dev prefix I get:

![image](https://user-images.githubusercontent.com/5676600/67959125-87c7f300-fbf8-11e9-9534-3b44b9827d97.png)

**To Reproduce**
Clone node-oidc-provider repository and use example folder as a source for serverless project

const { getMountOption } = require('./../oidc/helpers/get-mount-option') -> 

https://github.com/AKIRA-MIYAKE/serverless-oidc-provider/blob/master/src/app/oidc/helpers/get-mount-option.js

mountOption.directory = /dev

entry point:

```javascript
const path = require('path');

const set = require('lodash/set');
const Koa = require('koa');
const render = require('koa-ejs');
const helmet = require('koa-helmet');
const mount = require('koa-mount');

const Provider = require('oidc-provider');

const Account = require('./support/account');
const configuration = require('./support/configuration');
const routes = require('./routes/koa');

const serverless = require('aws-serverless-express');
const Adapter = require('oidc-provider-dynamodb-adapter');
const { DynamoDB } = require('aws-sdk');
const { getMountOption } = require('./../oidc/helpers/get-mount-option')


const handleRequest = async (event, context) => {

  const mountOption = getMountOption(event);
  configuration.findAccount = Account.findAccount;

  const app = new Koa();
  app.use(helmet());

  render(app, {
    cache: false,
    viewExt: 'ejs',
    layout: '_layout',
    root: path.join(__dirname, 'views'),
  });

  Adapter.setConfig({
    dynamoDB: new DynamoDB(),
    tableName: process.env.AWS_DYNAMODB_TABLE_NAME
  })

  const provider = new Provider(process.env.OIDC_ISSURE, { Adapter, ...configuration });
  provider.proxy = true;

  //provider.use(helmet());

  app.use(routes(provider).routes());
  app.use(mount(mountOption.directory, provider.app));
  app.proxy = true;

  event.path = mountOption.rewriteEventPath;

  console.log(`Rewrite event path: ${mountOption.rewriteEventPath}`);

  // const server = serverless.createServer((req, res) => {
  //   console.log(`Original req: ${req}`);
  //   //req.originalUrl = mountOption.rewriteEventPath;
  //   return app.callback(req, res);
  // });

  const server = serverless.createServer(app.callback());

  return new Promise((resolve, reject) => {
    serverless.proxy(
      server,
      event,
      Object.assign({}, context, {
        succeed: process.env.IS_OFFLINE ? context.succeed : resolve
      })
    )
  })
};

module.exports = { handleRequest };
```

Steps to reproduce the behaviour:

1.  Create node-oidc-provider v4.x.x dependency with same entry point as described above
2.  Start implicit flow from js client - Check that it works
3.  Switch to v6.x.x with the same code (change configuration structure and names where neeeded that changed in v6.x.x)
4. GET .well-known/openid-configuration - It should work, but /interaction URL-s render error

**Expected behaviour**
It should render login UI

**Environment:**
 - oidc-provider version: [e.g. v6.12.13]
 - node version: [e.g. v10.16.3]

**Additional context**
There is related issue https://github.com/panva/node-oidc-provider/issues/521 

 - [x] the bug is happening on latest oidc-provider too.
 - [ ] i have tried DEBUG (see README) and can see the issue is with the provider and not my code.
 - [ ] i have searched the issues tracker on github for similar issues and couldn't find anything related.
 - [x] i have searched the [FAQ](https://github.com/panva/node-oidc-provider/wiki/FAQ) and couldn't find anything related.

**Logs**

**Comment by panva** [comment]
@tmedanovic similar to #521, i do not have the bandwidth to aid in debugging different function deployments that mess around with the path.

My AWS lambda test deployment is using an ALB with a custom domain certificate with the lambda as a target and https://github.com/dougmoscrop/serverless-http for wrapping server for the function. Using this setup i don't have an issue which leads me back to - routing issues are just that, its a lambda issue to work around, not a library one i can spend resources on.

**Comment by tmedanovic** [comment]
@panva Could you post a gist of your serveless.yml, interaction route and file where you mount your app? It would help a lot. I am trying for a week now to get it working, the thing is that I **can** get to the routes that are part of oidc library like /.well-known/openid-configuration and /auth but I **can't** get to the routes I defined like /interaction/:uid. I thought it is somehow connected with changing the router in oidc library, and using old koa-router as part of example but it can't be since you have it working with ALB (Yes, I'm using API gateway but I doubt that it causes the issue).

**Comment by tmedanovic** [comment]
I managed to get it working, here is how:

**serverless.yml** (Added root path)

    events: #Define the events that trigger the lambda
    **# Added this part**
    - http:
        path: / # this matches the base path
        method: ANY
    **# Added this part**
    - http: #Define an HTTP endpoint that respond to any routes
        path: /{proxy+}
        method: ANY
        cors: true

**handler.js** (Removed any mounting paths and url rewriting)

```
  const provider = new Provider(process.env.OIDC_ISSURE, { Adapter, ...configuration });
  provider.proxy = true;

  provider.use(helmet());

  app.use(routes(provider).routes());
  app.use(mount(provider.app));
  app.proxy = true;

  return serverless(app);
```
**configuration.js** (Added interaction url with prefix)

```
    url(ctx, interaction) { // eslint-disable-line no-unused-vars
      return `/dev/interaction/${ctx.oidc.uid}`;
    },
```

Changed every view form action so that i added my prefix /dev:

`<form autocomplete="off" action="/dev/interaction/<%= uid %>/confirm" method="post">`

@panva  Altought I think that last part can be done better (sending url as param on render) since default dev interactions views form action urls generated dynamically with mount path (https://github.com/marekmicek/node-oidc-provider/commit/78d3c09660761b02c60056c9dbf266d5a4b63c55)

**Comment by panva** [comment]
So it was the API gateway... ALB does not need any special care when it comes to routes.
