### ISSUE TITLE
'session/end' endpoint create session if not exist

### ISSUE THREAD

**Issue by joolfe** [panva/node-oidc-provider#566]
**Describe the bug**
When call to the 'session/end' enpoint without session (no cookie) is generating a new session and continuing the logout steps.

**To Reproduce**
I have a create a repo with some test that reproduce the error here 'https://github.com/joolfe/node-oidc-provider-issues'

Steps to reproduce the behaviour:

1.  Download the example code from 'https://github.com/joolfe/node-oidc-provider-issues'
2.  execute `npm install`
3.  execute test using `npm run test-logoutNoSession`

**Expected behaviour**
When caling to 'session/end' should check if session exist, if not exist then should redirect to logout success uri or return an error saying there are no session to end.

**Environment:**
 - oidc-provider version: v6.13.0
 - node version: v12.13.0
 - npm version: 6.12.0

**Additional context**
One of the middlewares used in session_end action is '../shared/session.js', that is using the model 'lib/model/session.js' to get the session, and this model in case of not exist is creating a new one, maybe another method should be created, one for getOrCreate() another one for get()... or just checking is session is empty in end_session endpoint is enough.

**Comment by panva** [comment]
Hi @joolfe 

Isn't the end result all that matters? An empty session gets created to store a CSRF token to submit at the confirmation prompt, that I cannot change (Your test case is invalid because of it). That session, once confirmed gets deleted.

I agree there's a room to improve in some scenarios but its definitely not to redirect straight away or error.

**Comment by joolfe** [comment]
Hi @panva,
Seems very clear for me that this is an incorrect behaviour, if a session not exist you should not create a empty one in the end-session operative, you should inform the user about there are no session to remove.
About the way to show this... straight redirect or show an error are just some ideas, can be a "no session" screen if you prefer, but don't handle the situation is definitely not the solution for me.

> Isn't the end result all that matters?
Let me put you an example about the final result and the user experience, the user go to the '/session/end' endpoint with an active session, the form is presented and the user send the form and complete the operative, then go again to '/session/end' endpoint this time without session, but the logout form is still there, he do the process again to be sure has remove the session, and again and again... is a very bad end result in my opinion.

What do you think?

Best Regards.

**Comment by panva** [comment]
I think c6b1770 dealt with the issue. There's no form for the end user anymore and the end-result is that there's no session cookie nor session object in the db.

**Comment by joolfe** [comment]
up sorry, didn't see the commit id, thanks!

**Comment by joolfe** [comment]
Hi @panva,

I have review your code changes and indeed with this change you avoid an user interaction when no session is present, i don't think pass for the '/session/confirm' endpoint is needed, because there are no things to remove from the session (because just recent created), but is ok...
But i think that solution is breaking the ability to customize the logout form, i mean, there are a "logoutSource" configuration so you can customize the page, but when no session you are returning always the same html and maybe should be another option for setup this "automatic form response"
 
Best Regards

**Comment by panva** [comment]
yeah, `form_post` has a standard handler that cannot be customized for any of its uses and i don't think it has to. It's a standard self submitting form where the user can't interact unless the user-agent has JS disabled.
