### ISSUE TITLE
Well-Known URI should always be present in the root regardless of path prefix

### ISSUE THREAD

**Issue by fiznool** [panva/node-oidc-provider#567]
**Describe the bug**

The documentation [describes how to mount the provider instance in an express/koa application with a path prefix](https://github.com/panva/node-oidc-provider/blob/master/docs/README.md#mounting-oidc-provider), for example:

``` js
const prefix = '/oidc';
expressApp.use(prefix, oidc.callback);
```

The problem is that the `/.well-known` path is also mounted with this prefix, which appears to violate the [Well-Known RFC](https://tools.ietf.org/html/rfc5785) - this mandates that all 'well-known' URIs should be found under the `/.well-known` root path.

**To Reproduce**
Provider and Client configuration: (inline or gist)
```js
// provider configuration
const { Provider } = require('oidc-provider');

const configuration = {
  clients: [{
    client_id: 'foo',
    client_secret: 'bar',
    redirect_uris: ['http://lvh.me:8080/cb'],
  }],
};

const oidc = new Provider('http://localhost:3000', configuration);

const prefix = '/oidc';
expressApp.use(prefix, oidc.callback);
```

Steps to reproduce the behaviour:

1.  Use the configuration above and start a server.
2.  Try to access http://localhost:3000/.well-known/openid-configuration

This results in a 404 not found. Instead, the well-known path is available at http://localhost:3000/oidc/.well-known/openid-configuration

**Expected behaviour**

According to the configuration, this is behaving as it should. But I would argue that this is incorrect - all routes except for the `/.well-known` path should be prefixed.

**Environment:**
 - oidc-provider version: 6.12.13
 - node version: 12.12.0

**Additional context**

I guess that a fix would involve sending through the prefix as a configuration option, rather than asking the user to mount the provider at a particular express mount path. This would allow the provider to prefix the routes internally but leave `/.well-known` alone.

 - [x] the bug is happening on latest oidc-provider too.
 - [x] i have tried DEBUG (see README) and can see the issue is with the provider and not my code.
 - [x] i have searched the issues tracker on github for similar issues and couldn't find anything related.
 - [x] i have searched the [FAQ](https://github.com/panva/node-oidc-provider/wiki/FAQ) and couldn't find anything related.

**Comment by panva** [comment]
Indeed, but there’s no way for the package to reroute the upstream app. You need to do that yourself with e.g. koa-rewrite or whatever express alternative.

**Comment by fiznool** [comment]
Thank you for your quick reply.

I think my overall point was that the documentation describes how to mount the application at a different prefix, but this ends up violating one of the RFCs relating to the OIDC ecosystem. At the very least I would hope to see a disclaimer to this effect in the docs.

For anyone else who comes across this, as a workaround I am declaring a custom routes object which contains the prefix for all routes. I'm then mounting the provider without an express route prefix. Something along the following lines:

``` js
const { Provider } = require('oidc-provider');

const configuration = {
  clients: [{
    client_id: 'foo',
    client_secret: 'bar',
    redirect_uris: ['http://lvh.me:8080/cb'],
  }],
  routes:   {
    authorization: 'oidc/auth',
    check_session: 'oidc/session/check',
    code_verification: 'oidc/device',
    device_authorization: 'oidc/device/auth',
    end_session: 'oidc/session/end',
    introspection: 'oidc/token/introspection',
    jwks: 'oidc/jwks',
    pushed_authorization_request: 'oidc/request',
    registration: 'oidc/reg',
    revocation: 'oidc/token/revocation',
    token: 'oidc/token',
    userinfo: 'oidc/me'
  }
};

const oidc = new Provider('http://localhost:3000', configuration);
expressApp.use(oidc.callback);
```

This results in the behaviour I'm looking for (routes prefixed except for `.well-known`).

**Comment by panva** [comment]
That’s certainly one way to do it. However if one chooses to include the path in his issuer identifier its not needed. 

Bottom line, plenty of ways to handle this, i’ll see if i can include some more guidance in the docs.

**Comment by fiznool** [comment]
Following up on this, thanks for the guidance - I've simplified by setting the issuer path to be equal to the route mount path. Everything works well and to-spec then!

```
// provider configuration
const { Provider } = require('oidc-provider');

const configuration = {
  clients: [{
    client_id: 'foo',
    client_secret: 'bar',
    redirect_uris: ['http://lvh.me:8080/cb'],
  }],
};

const origin = 'http://localhost:3000';
const mountPath = '/oidc';
const issuer = origin + mountPath

const oidc = new Provider(issuer, configuration);
expressApp.use(mountPath, oidc.callback);
```
