### ISSUE TITLE
Token request - re-issue the same token

### ISSUE THREAD

**Issue by sureshvarman** [panva/node-oidc-provider#568]
I have written an custom password grant flow, is there any way, i can re-issue the same set of token, if the user requests for token again.

It will be a combination of rate-limiting but issue the same token again, instead of restricting the user with updated expires_in field.

**Comment by panva** [comment]
Hi @sureshvarman I don't see how you could "issue" the same token again, but since you control the implementation of the grant and the db why don't you pull up the previous token and return that instead.

**Comment by sureshvarman** [comment]
Thanks, @panva .

I thought of the same.
