### ISSUE TITLE
Subdirectories in endpoints

### ISSUE THREAD

**Issue by jacobvinzent** [panva/node-oidc-provider#571]
Hi can I get a subdirectory added to my endpoints, so the all the endpoints URLs get oidc as subdirectory
eg.
authorization_endpoint: "http://test.com:3001/oidc/auth",

**Comment by panva** [comment]
- https://github.com/panva/node-oidc-provider/tree/v6.13.0/docs#mounting-oidc-provider
- https://github.com/panva/node-oidc-provider/tree/v6.13.0/docs#routes
