### ISSUE TITLE
DPoP htu validation fails if provider is not at /

### ISSUE THREAD

**Issue by CarterDawson72** [panva/node-oidc-provider#572]
**Describe the bug**
When requesting a DPoP token with a provider (using express) not mounted at / but on another directory:

`
app.use( '/oidc' , oidc.callback );
`

The validation for the **htu** at the code file **lib/helpers/oidc_context.js** on function **get DPoP** fails since provided path does not equals to the computed path.

       if (payload.htu !==  "${this.ctx.origin}${this.ctx.path}") {
          console.log(" Provided htu: " , payload.htu );

          console.log(" Computed htu: " , `${this.ctx.origin}${this.ctx.path}` );

          throw new Error('htu mismatch');

Output:

>   Provided htu:  http://oidc:4000/oidc/token
>   Computed htu:  http://oidc:4000/token

**To Reproduce**
Provider and Client configuration: (inline or gist)

 // provider configuration
  Enable DPoP configuration on the provider:

>   exports.oidcConfig = {
>   // ... see the available options in Configuration options section
>   ...
>   features: {
>     clientCredentials: { enabled: true },
>     registration: { enabled: true },
>     introspection: { enabled: true },
>     revocation: { enabled: true },
>     deviceFlow: { enabled: true },
>     devInteractions: { enabled: false },      // This will close all login/consent pages from the oidc provider
>     dPoP: { enabled: true, iatTolerance: 60, ack: 'id-03' }   // Enable proof of possession tokens 
>   },
>   ....

 

Mount the provider not at root but some other path, for example /oidc

Enable the client using openid-client to do a DPoP request, using the issuer discovery and hence the discovered URLS.

// keystore(s) - if they affect the behaviour

// client(s) configuration
Used client custom http headers for requesting a DPoP Token.

> global.client = null;
> const privateKey = jose.JWK.generateSync('EC');
> const publicJWK = privateKey.toJWK(false);
> delete publicJWK.kid;
> 
> function dpopHeader (options) {
> console.log("DPOP Header!!!");
> console.log("Options htu: " , options.url );
>   if (
>     options.url === client.issuer.token_endpoint || options.url === client.issuer.userinfo_endpoint
>   ) {    const DPoP = jose.JWS.sign({
>       htu: options.url,
>       htm: options.method,
>       iat: Math.floor(Date.now() / 1000),
>       jti: '393999393933939',
>     },
>     privateKey,
>     {
>       typ: 'dpop+jwt',
>       alg: 'ES256',
>       jwk: publicJWK,
>     });
>     options.headers = options.headers || {};
>     options.headers.DPoP = DPoP;
> 
>     if (options.url === client.issuer.userinfo_endpoint) {
>       if (options.headers.Authorization && options.headers.Authorization.startsWith('Bearer ')) {
>         options.headers.Authorization = `DPoP ${options.headers.Authorization.split(' ')[1]}`
>       }
>     }
>   }
> ...
> ....
> ...
> async function GetAccessToken() {
>     var issuer = await OpenIdClient.Issuer.discover(identityUrl);
>     const oidcclient = new issuer.Client({
>         client_id: clientId,
>         client_secret: clientSecret,
>     });
>     client = oidcclient;
>     client[custom.http_options] = dpopHeader;
> 
>     const grantResponse = await client.grant({
>         grant_type: 'client_credentials',
>         scope: credentialsScope,
>     });
> ....
> 

Steps to reproduce the behaviour:

1.  Start the server with DPoP enabled and running on a non root path, for example /oidc (using express)
2.  Execute the client
3.  Htu is rejected since the payload path is not the computed path

**Expected behaviour**
Both the payload path and the computed path should have the non root directory to validate the htu

**Environment:**
 - oidc-provider version: 6.13.0
 - node version: v13.0.1

**Additional context**

 - [X] the bug is happening on latest oidc-provider too.
 - [X] i have tried DEBUG (see README) and can see the issue is with the provider and not my code.
 - [X] i have searched the issues tracker on github for similar issues and couldn't find anything related.
 - [X ] i have searched the [FAQ](https://github.com/panva/node-oidc-provider/wiki/FAQ) and couldn't find anything related.

**Logs**
```
GET /oidc/.well-known/openid-configuration 200 14.159 ms - 2322
GET /oidc/jwks 200 1.926 ms - 437
  oidc-provider:token accepted uid=y7G-CzTjzSyWLZuGDttcF Params { grant_type: 'client_credentials', scope: 'openid profile', client_id: undefined, client_assertion: undefined, client_assertion_type: undefined, client_secret: undefined } +0ms
 Provided htu:  http://oidc:4000/oidc/token
 Computed htu:  http://oidc:4000/token
  oidc-provider:error uid=y7G-CzTjzSyWLZuGDttcF path=/token method=POST error={ error: 'invalid_request', error_description: 'invalid DPoP Proof JWT (htu mismatch)' } detail=undefined +0ms
{
  request: {
    method: 'POST',
    url: '/token',
    header: {
      'user-agent': 'openid-client/3.7.4 (https://github.com/panva/node-openid-client)',
      authorization: 'Basic bWFjaGluZTpwYXNzd29yZA==',
      dpop: 'eyJ0eXAiOiJkcG9wK2p3dCIsImFsZyI6IkVTMjU2IiwiandrIjp7ImNydiI6IlAtMjU2IiwieCI6ImpSeVAyMGduZV9nNV8tLU5qRm9OS1NpQl9NR3pJNzZPMkNsVGU2RXN2NmsiLCJ5IjoiWXBXaWJuZXJUUDNwOFpuMjV0ck0wMlA3SHhkU2x5Q3JneTB3MUhCdVRiTSIsImt0eSI6IkVDIn19.eyJodHUiOiJodHRwOi8vb2lkYzo0MDAwL29pZGMvdG9rZW4iLCJodG0iOiJQT1NUIiwiaWF0IjoxNTczMTQxOTM0LCJqdGkiOiIzOTM5OTkzOTM5MzM5MzkifQ.GHbSK5VafyEAlBxwvLSLXz9v6sXBBFlP0kFd5AvFFWPMZAKU-sunYR0RCpPTqwec7aIMVCidfn3fyIIGxMY03g',
      accept: 'application/json',
      'accept-encoding': 'gzip, deflate',
      'content-type': 'application/x-www-form-urlencoded',
      'content-length': '50',
      host: 'oidc:4000',
      connection: 'close'
    }
  },
  response: {
    status: 400,
    message: 'Bad Request',
    header: [Object: null prototype] {
      'x-dns-prefetch-control': 'off',
      'x-frame-options': 'SAMEORIGIN',
      'strict-transport-security': 'max-age=15552000; includeSubDomains',
      'x-download-options': 'noopen',
      'x-content-type-options': 'nosniff',
      'x-xss-protection': '1; mode=block',
      'access-control-allow-origin': '*',
      pragma: 'no-cache',
      'cache-control': 'no-cache, no-store',
      'content-type': 'application/json; charset=utf-8'
    }
  },
  app: { subdomainOffset: 2, proxy: false, env: 'development' },
  originalUrl: '/token',
  req: '<original node req>',
  res: '<original node res>',
  socket: '<original node socket>'
}
```

**Comment by panva** [comment]
Hi @CarterDawson72 

can you try this?

```js
if (payload.htu !== `${this.urlFor(this.route)}`) {
```

**Comment by CarterDawson72** [comment]
Yep, it works now.  The htu is validated correctly.

**Comment by panva** [comment]
Thank you, i just did a release a few moments ago before this issue so i'll wait a bit with releasing the fix. Latest sunday if nothing new pops up.

**Comment by panva** [comment]
I've updated the test suite (e2c6156) to run all the tests while

- unmounted (using the provider's koa app)
- mounted to '/' in an express app
- mounted to '/oidc' in an express app
- mounted to '/' in a koa app
- mounted to '/oidc' in a koa app

to make sure these issues are uncovered early on.
