### ISSUE TITLE
https://tools.ietf.org/html/rfc7523 - Authorization Grants

### ISSUE THREAD

**Issue by RalphBragg** [panva/node-oidc-provider#573]
**Is your feature request related to a problem? No - new feature
Feature request - the provider supports private_key_jwt which is specified in section 2 of the RFC. The RFC also defines authorization grants in section 3 and 4. 

Authorization Grants are to be used by the OBIE UK - PSD2 program to standardize a means of TPP "Re-Authentication" of a long lived consent which they're obliged to do so every 90 days.  

This flow is also fantastically useful for testing when you just need to obtain an access token with a predefined payload from the server.

**Describe the solution you'd like**
Extension to include the authorization assertion added to the library. This is a very powerful feature so appropriate ability to restrict access to specific clients and a means of validation the request.

**Describe alternatives you've considered**
Given that it's a request / requirement from an external standards body implementation a different flow that results in the same features wasn't an option unfortunately.

**Additional context**

 - [X] i have searched the configuration section for this feature and couldn't find it
 - [X] i have searched the issues tracker on github for similar requests and couldn't find anything related.

**Comment by panva** [comment]
Hi @RalphBragg 

> **Describe the solution you'd like**
> Extension to include the authorization assertion added to the library. This is a very powerful feature so appropriate ability to restrict access to specific clients and a means of validation the request.

The [registerGrantType](https://github.com/panva/node-oidc-provider/blob/v6.14.1/docs/README.md#custom-grant-types) interface is perfectly suitable for registering these extension grants.

When a grant is registered like this the clients will still get authenticated, the grant still must be whitelisted in client's `grant_types` metadata, etc. It's just the actual grant processing that is left to the implementer, same as issuing tokens for which you can refer to existing [grant implementations](https://github.com/panva/node-oidc-provider/blob/v6.14.1/lib/actions/grants/index.js) as reference.

I've left an example implementation in slack for you.
