### ISSUE TITLE
Impossible to override "resume" cookie options 

### ISSUE THREAD

**Issue by azaxarov** [panva/node-oidc-provider#574]
**Describe the bug**
When logging in multiple times, I see a bunch of "resume" cookies generated for some unique path. The problem is that when starting a new interaction, "resume" cookie does not get overwritten, but instead a new one is issued. The reason a new one is issued is that it is impossible to overwrite path property of "resume" cookie.

I traced the issue back to the following line: https://github.com/panva/node-oidc-provider/blob/eac9b7f0be0f43ab4fcbdc96f26cd0d0ccbfc09d/lib/actions/authorization/interactions.js#L135

Clearly, the fact that cookie options are added before path parameter, its path can be unique. As a result, that cookie will not be overwritten.

Now, it may be intended behaviour, but should it not get the same treatment as an "interaction" cookie (see below)? https://github.com/panva/node-oidc-provider/blob/eac9b7f0be0f43ab4fcbdc96f26cd0d0ccbfc09d/lib/actions/authorization/interactions.js#L128

This change was introduced in: https://github.com/panva/node-oidc-provider/commit/4c7e87734bba2f7b61b9d60250a10a60fbae4b76

**To Reproduce**
Any reasonable configuration will suffice.

**Expected behaviour**
It is expected to be able to set "resume" cookie path (to "/", for example). For that to happen, cookie options have to be applied after path in: 
https://github.com/panva/node-oidc-provider/blob/eac9b7f0be0f43ab4fcbdc96f26cd0d0ccbfc09d/lib/actions/authorization/interactions.js#L135

**Additional context**
I see that a similar issue (https://github.com/panva/node-oidc-provider/issues/403) was opened a while back.

Appreciate all the work you are doing!

**Environment:**
 - oidc-provider version: latest
 - node version: latest

 - [x] the bug is happening on latest oidc-provider too.
 - [x] i have tried DEBUG (see README) and can see the issue is with the provider and not my code.
 - [x] i have searched the issues tracker on github for similar issues and couldn't find anything related.
 - [x] i have searched the [FAQ](https://github.com/panva/node-oidc-provider/wiki/FAQ) and couldn't find anything related.

**Comment by panva** [comment]
Hi @azaxarov,

This is absolutely intended as denoted by the fact that the commit that it was introduced in was labeled as a fix, this was always the intended behaviour since the cookie value is only needed on the resume path which isn’t dynamic. 

The resume cookie is deleted after resume, and if interactions are aborted - its still a short duration cookie

I struggle to understand why you’d want the cookie to be set to “/“ instead of only the path its usable for.

**Comment by panva** [comment]
Note: this + the unique interaction urls solve a common problem - concurrent interactions in multiple tabs.

**Comment by azaxarov** [comment]
Hi @panva, and thanks for the swift response!

You have some valid points. 

I guess my use case is somewhat different, which is why the issue with fixed path is bothering me. Say my authorisation server runs on http://localhost:8000. Whenever it asks for an interaction, it redirects to another application (presentation logic only) running on http://localhost:8001.

The authorisation server sends all the cookies to http://localhost:8001, and in this case a "resume" cookie with a path (i.e. "/auth/{interaction_uid}"). When a successful authorisation takes place, cookies from http://localhost:8001 are not cleared, only from http://localhost:8000. The fact that cookies have a short duration is definitely great, but in my case, it would not do any harm to allow setting a custom cookie path nonetheless.

What are your thoughts on this? Have you come across a similar solution with a separate application for interactions?

**Comment by panva** [comment]
I definitely envision interactions taking place on another domain so maybe what’s missing is actually ignoring the short cookie domain configuration for the resume cookie?

**Comment by azaxarov** [comment]
Yes, that is true. The two application will live under the same hostname. For instance, the auth server is at the root level at https://{some.tld} and the interactions are under https://{some.tld}/interactions. In that case, I believe the problem will go away in production (or in an environment with a stable hostname).

Thank you for your time and help!
