### ISSUE TITLE
Question: (ab)using interaction session?

### ISSUE THREAD

**Issue by fiznool** [panva/node-oidc-provider#575]
This is a follow on to a point originally raised in [this comment](https://github.com/panva/node-oidc-provider/issues/381#issuecomment-457825568).

I'm building a 'multi-step' interaction which works as follows:

- OIDC interaction begins with a route `/interaction/:uid/email`, this shows an input to the user for capturing an email address
- User enters email address and submits form
- Email address is posted to `/interaction/:uid/email` with the email address, which is stored in a session
- The user is redirected to a route `/interaction/:uid/code`, this shows an input to the user for capturing a one-time code
- Meanwhile, the server sends a random 6-digit code to the submitted email address
- User receives email with code, enters code into input box and submits form
- Code is posted to `/interaction/:uid/code`
- Server pulls email address from interaction session, checks that submitted code matches the one that was sent to this email address
- If matches, interaction is finished

As this flow describes I need a session for (at least) 2 things

- Storing the email address after the first step
- CSRF protection on the form post endpoints

---

On to my question. I'm currently piggybacking onto the interaction session via the`meta` property set via `interactionResult` as follows:

``` js
app.postAsync('/interaction/:uid/email', async (req, res) => {
  const { email } = req.body;
  await provider.interactionResult(req, res, {
    meta: {
      email,
    },
  });
  res.redirect('/interaction/:uid/code');
});

app.postAsync('interaction/:uid/code', async (req, res) => {
  const { code } = req.body;
  const { result } = await provider.interactionDetails(req, res);

  const email = result.meta && result.meta.email;
  if(email) {
    // Logic to check whether codes match goes here
  }
});
```

Is this an acceptable/expected use of the `meta` property, or should I be using my own session mechanism here?

**Comment by panva** [comment]
> Is this an acceptable/expected use of the meta property, or should I be using my own session mechanism here?

Well, there's no "meta" property defined on `Interaction`, you're essentially saying hey if there's a "meta" prompt, this is its result. I guess its fine.

**Comment by fiznool** [comment]
Thanks for your super quick reply 😄 

The `meta` property I'm referring to is the one described in the docs under [User Flows](https://github.com/panva/node-oidc-provider/tree/master/docs#user-flows) -> `#provider.interactionFinished(req, res, result)`:

``` js
// meta is a free object you may store alongside an authorization. It can be useful
// during the interaction check to verify information on the ongoing session.
meta: {
  // object structure up-to-you
},
```
