### ISSUE TITLE
Question: split adapters into their own modules?

### ISSUE THREAD

**Issue by fiznool** [panva/node-oidc-provider#579]
Forgive me if this has been asked before, I couldn't find anything in the issue tracker.

Is it worth considering the creation of a module for each adapter, rather than requiring that the adapter is hand-coded each time? I imagine that most people will cut and paste an adapter from the [example](https://github.com/panva/node-oidc-provider/tree/master/example/adapters) so I was wondering if making these standalone modules would help, in the same way that [express-session does](https://github.com/expressjs/session#compatible-session-stores).

**Comment by panva** [comment]
I don’t have the bandwidth to maintain these modules. Furthermore, they’re just examples and require adaption for everyone’s specific deployment. e.g. sentinel for HA redis, index lifecycle maintenance for mongo...

> I imagine that most people will cut and paste an adapter from the example

To begin with, yeah, but i don’t imagine they’re final, they’re just starting points.
