### ISSUE TITLE
Consider removing session uid when session is destroyed

### ISSUE THREAD

**Issue by fiznool** [panva/node-oidc-provider#581]
When [the session ends and it is destroyed](https://github.com/panva/node-oidc-provider/blob/master/lib/actions/end_session.js#L190), the `uid` still lingers in the adapter and becomes dangling. It will eventually be cleaned up due to its TTL, but would it be nice to also remove the uid key?

**Comment by panva** [comment]
I assume this is about the redis adapter. Both device code's `userCodeKeyFor` and session's `uidKeyFor` aren't getting cleaned up. In order to do that, you'd have to load the object by its primary identifier first to get those values. I chose to not to do that so that there's no unnecessary I/O for the delete operation.

Since this is an _example_ adapter to begin with, you can choose to further optimize it.

**Comment by fiznool** [comment]
> I assume this is about the redis adapter

Sorry yes, I forgot to add that piece of info 😊 

> Both device code's userCodeKeyFor and session's uidKeyFor aren't getting cleaned up. In order to do that, you'd have to load the object by its primary identifier first to get those values. I chose to not to do that so that there's no unnecessary I/O for the delete operation.

Yes I see the trade-off here. Since the uid and userCode keys have a TTL they will eventually be cleared anyway.

I've settled on listening for the `session:destroyed` event in the app, and cleaning up the uid that way. I think this has a few advantages:

- It happens 'out of band', meaning that the main request isn't delayed by the extra I/O, and any failures are ignored (in an exceptional circumstance, we can ignore the failure and rely on the TTL to eventually clear it up)
- The `session` object is presented as an argument to the event handler, meaning we don't need another roundtrip to the store to fetch the session UID

To achieve this I add a new method to the adapter `destroyUid(uid)` and call it from within the event handler:

``` js
const Provider = require('oidc-provider');
const Redis = require('ioredis');

const redisClient = new Redis(process.env.REDIS_URL);

class RedisAdapter {
  // ...
  async destroyUid(uid) {
    const key = `oidc:uid:${uid}`
    await redisClient.del(key);
  }
}

const config = {
  // ...
  adapter: RedisAdapter
};

const oidcProvider = new Provider('http://localhost:3000', config);
oidcProvider.on('session.destroyed', session => {
  const { adapter, uid } = session;
  // Make sure to catch the error so it doesn't cause an unhandledPromiseRejection
  adapter.destroyUid(uid).catch(err => {
    console.warn(err);
  });
});
```

I don't use device codes so I haven't added anything to clear those up, but I guess a similar approach could be used.

**Comment by fiznool** [comment]
If using TypeScript things are slightly complicated by the fact that we are adding a new method to the Adapter, so here's a working example for TS:

``` ts
import { Provider, Configuration, Adapter } from 'oidc-provider';
import Redis from 'ioredis';

interface IRedisAdapter extends Adapter {
  destroyUid(uid: string): Promise<undefined | void>;
}

const redisClient = new Redis(process.env.REDIS_URL);

class RedisAdapter implements IRedisAdapter {
  // ...
  async destroyUid(uid: string) {
    const key = `oidc:uid:${uid}`
    await redisClient.del(key);
  }
}

const config: Configuration = {
  // ...
  adapter: RedisAdapter
};

const oidcProvider = new Provider('http://localhost:3000', config);
oidcProvider.on('session.destroyed', session => {
  const { adapter, uid } = session;
  // Cast here to avoid TS error
  (adapter as IRedisAdapter).destroyUid(uid).catch(err => {
    console.warn(err);
  });
});
```
