### ISSUE TITLE
Session Management OP check iframe CSP script nonce

### ISSUE THREAD

**Issue by matthew-nichols-westtel** [panva/node-oidc-provider#583]
**Is your feature request related to a problem? Please describe.**
Session Management iframe doesn't work if CSP script-src is set to `'strict-dynamic' 'nonce-random'` (or equivalent).

**Describe the solution you'd like**
Something less fragile. Automatically parsing the CSP header and adding the nonce where needed seems like the most automatic solution (similar to how `keepHeaders: false` automatically removes `frame-ancestors`).
Also for us it makes sense to expose the JavaScript somehow so it can be bundled (so polyfills/dependencies can be included with it) and expose a source hook to set the source HTML for the frame (`checkFrameSource`?).

**Describe alternatives you've considered**
I am currently using code equivalent to the following (testing quality):
```
provider.use(async (ctx, next) => {
    await next();
    if (ctx.oidc.route === "check_session") {
        ctx.body = ctx.body
            .replace(/<script src=/g, `<script nonce="${ctx.state.nonce}" src=`)
            .replace(/<script type=/g, `<script nonce="${ctx.state.nonce}" type=`);
    }
});
```
It's likely safest to just replace ctx.body entirely (throw error if ctx.body is not the exact expected form so when/if it changes it shows up quickly in development)

**Additional context**
As a side note, it's also important that all assets we host be by hostable by us (there will be installations that have tenuous Internet connections and on-site operations must continue while the Internet is down). This page appears to just need a fetch polyfill and a SHA256 library which seem easy enough to self-host, but is there anything else we should look out for in this library? It's a very nice library by the way.

 - [*] i have searched the configuration section for this feature and couldn't find it
 - [*] i have searched the issues tracker on github for similar requests and couldn't find anything related.

**Comment by panva** [comment]
> Session Management iframe doesn't work if CSP script-src is set to 'strict-dynamic' 'nonce-random' (or equivalent).

Hi, I have no idea what this is for. Can you explain please?

**Comment by matthew-nichols-westtel** [comment]
https://csp.withgoogle.com/docs/strict-csp.html

Essentially I'm using koa-helmet with `scriptSrc: ["'self'", "'strict-dynamic'", `'nonce-${ctx.state.nonce}'`, "'unsafe-inline'"]`

And by "doesn't work" all the scripts on the page (`/session/check` by default, part of the sessionManagement feature) are blocked by the browser on load (because CSP violation)

**Comment by panva** [comment]
And what needs to be changed to make each of them work?

**Comment by matthew-nichols-westtel** [comment]
All the <script> tags need to have a nonce attribute attached

**Comment by panva** [comment]
I'm not likely to parse random nonces out of the `Content-Security-Policy` header and adding them to the script.

```js
provider.use(async (ctx, next) => {
    await next();
    if (ctx.oidc.route === "check_session") {
        ctx.body = ctx.body
            .replace(/<script /g, `<script nonce="${ctx.state.nonce}" `)
    }
});
```

☝️ this does feel like an appropriate solution. You have my 👍

> Also for us it makes sense to expose the JavaScript somehow so it can be bundled (so polyfills/dependencies can be included with it) and expose a source hook to set the source HTML for the frame (checkFrameSource?).

I can't do that either because it would bar me from making changes to the session state calculation in the future and i tend to keep these `source` helpers for end-user facing html that needs to be styled, which isn't the case here.

**Comment by panva** [comment]
What about an optional function helper `features.sessionManagement.scriptNonce` that can return the nonce to add? Default returns `undefined`, when falsy the nonce attribute won't be added?

**Comment by matthew-nichols-westtel** [comment]
That sounds very useful.

And this may technically be a second related issue (can't depend on external CDNs): I'm thinking something where I can bundle/compile ```import run from "oidc-provider/session_check"; run();``` to use in the session management iframe (with rollup, webpack, etc) so that session state calculation is still an internal detail of the library. There may be a better solution though.

**Comment by panva** [comment]
At that point you're better off replacing the source with a similar to solution to the above where you replace the cdn delivered polyfills and libraries.

**Comment by matthew-nichols-westtel** [comment]
Is ctx.body for the check_session route constant for a version of oidc-provider?

Aka will

```
const expected = `...`;
provider.use(async (ctx, next) => {
    await next();
    if (ctx.oidc.router === "check_session") {
        if (ctx.body === expected) ctx.body = `stuff...`;
        else throw new Error("oidc-provider changed check_session route, go fix");
    }
}
```

be generally expected to work (and then yell loudly when it doesn't?)

**Comment by panva** [comment]
It is, given that you don't change the `state` cookie name configuration.

**Comment by matthew-nichols-westtel** [comment]
Fair enough

I just want it to yell loudly when it changes

**Comment by panva** [comment]
For CI i presume.

**Comment by matthew-nichols-westtel** [comment]
Yep

**Comment by panva** [comment]
Please see #584
