### ISSUE TITLE
Create client with client credential grant

### ISSUE THREAD

**Issue by Rogger794** [panva/node-oidc-provider#585]
Hi, I was creating clients using the registration endpoint, but when I try to only create a client with only the credential grant without redirect_uris, it return an error because redirect_uris is mandatory, but in this case, I dont need redirect_uris.

**To Reproduce**
I run my project and use postman. This is my query:
```bash
 POST /reg HTTP/1.1
  Content-Type: application/json
  Accept: application/json
  Host: http://localhost:3001/reg
  Authorization: Bearer <InitialAccessTokenGenerated>

  {
   "application_type": "web",
   "client_name": "My Example",
   "token_endpoint_auth_method": "client_secret_basic",
  }
```

**Expected behaviour**
[example in prerequisites for token-instrospection](https://connect2id.com/products/server/docs/api/token-introspection)

**Environment:**
 - "oidc-provider": "^6.13.0"
 - node version: [e.g. v10.16.3]

**Logs**
{
    "error": "invalid_redirect_uri",
    "error_description": "redirect_uris is mandatory property"
}

**Comment by panva** [comment]
You may not need redirect_uris but the property, like others, are required. 

They may be empty tho, see a test here https://github.com/panva/node-oidc-provider/blob/5a1181344b70647430b048ed85a187a56c13d56c/test/configuration/client_metadata.test.js#L1161

**Comment by Rogger794** [comment]
Thanks, that way works for me.
