### ISSUE TITLE
Back-channel logout headers

### ISSUE THREAD

**Issue by scriptcoded** [panva/node-oidc-provider#588]
**Is your feature request related to a problem? Please describe.**
We're setting up an OIDC service which reads account information from a separate service. To do this our OIDC service sends an API token with it's requests to the account service. We'd like to implement a similar system for the call to the back-channel logout URI as well, but there is no way to add headers or any other details to the request being sent. Even though the RP verifies the logout token, it'd still be nice to be able to have that extra layer of security.

**Describe the solution you'd like**
An extra field would be added to the client metadata, `backchannel_logout_headers`. If set, those headers will be included in the request sent to the RP.

**Describe alternatives you've considered**
Having some form of lookup function would also be a solution. Just like the library uses `findAccount` one could provide a form of middleware to modify the request before it's sent, and set different headers based on the client_id. This would also allow for more customization other than just headers.

**Additional context**
No additional context

 - [x] i have searched the configuration section for this feature and couldn't find it
 - [x] i have searched the issues tracker on github for similar requests and couldn't find anything related.

**Comment by panva** [comment]
@scriptcoded there's nothing extra needed. Just configure `httpOptions` to do this for you.

```js
function httpOptions(options) {
  if (options.body && options.body.logout_token) {
    options.hooks = {
      beforeRequest: [
        async (normalizedOptions) => {
          const clientId = getAudClaimFromJWTPayload(querystring.parse(normalizedOptions.body).logout_token);
          const client = await provider.Client.find(clientId);
          // pull backchannel_logout_headers (extraClientMetadata) from client.backchannel_logout_headers
          normalizedOptions.headers.foo = 'bar';
        },
      ],
    };
  }
  
  return options;
}
```

**Comment by scriptcoded** [comment]
@panva Oh sorry, missed that. Thanks for pointing it out. And great library - it's been a life saver for our company :)

**Comment by panva** [comment]
> it's been a life saver for our company :)

I'm glad it's of use. Please consider [supporting](https://github.com/sponsors/panva) its ongoing maintenance and development efforts.
