### ISSUE TITLE
Do POST /token endpoint support Content-Type = application/json?

### ISSUE THREAD

**Issue by phuocleanh** [panva/node-oidc-provider#589]
**Is your feature request related to a problem? Please describe.**
A clear and concise description of what the problem is.

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

 - [x] i have searched the configuration section for this feature and couldn't find it
 - [x] i have searched the issues tracker on github for similar requests and couldn't find anything related.

**Comment by phuocleanh** [comment]
Hi @panva ,
When I try to call /token endpoint with **Content-Type = application/json** I got the error:
{
    "error": "invalid_request",
    "error_description": "only application/x-www-form-urlencoded content-type bodies are supported on POST /token"
}
So can we configure the provider to support to use Content-Type = application/json on this endpoint?
Thank you for your support!
Phuoc

**Comment by panva** [comment]
Hi @phuocleanh 

> Does `token_endpoint` support Content-Type = application/json?

[No.](https://tools.ietf.org/html/rfc6749#section-4.1.3) It's not intended to.

**Comment by phuocleanh** [comment]
Got it. thanks @panva
