### ISSUE TITLE
Add JWT Access Token as Cookie before Redirect

### ISSUE THREAD

**Issue by marcelalburg** [panva/node-oidc-provider#590]
Hello,

i've a single page application and don't like to store any tokens into memory or local storage. I found a [page](https://auth0.com/docs/cross-origin-authentication) that describes a solution for that. 

After a successful authentication i would like to set a custom cookie with the JWT Access Token for a specific path. With a Pre/Post Custom Middleware i could set this cookie but i don't found a solution to figure out the JWT Token.

Is this approach a valid and secure one and how can i access/generate a JWT Access Token for that cookie ? Did you consider this user flow in oidc-provider already ?

Thanks a lot
Marcel

**Comment by panva** [comment]
@marcelalburg I don't see how Auth0's cross-origin authentication relates to the client not liking to store any tokens.

As such I am not considering adopting anything that's not covered by the existing standards bodies.

**Comment by marcelalburg** [comment]
Hello, thanks for your fast answer. Maybe the link is not a valid one, but it shows that it should be possible to add a cookie on a custom domain so that you don't need to store the JWT Token in local storage nor in memory. 

My question was more, how can I generate a Access Token in Pre/Post Middleware and set this as a cookie ?

Thanks for your help
