### ISSUE TITLE
JTI claim for ID Tokens

### ISSUE THREAD

**Issue by stavros-wb** [panva/node-oidc-provider#591]
Hello @panva 

**Is your feature request related to a problem? Please describe.**
Scanning through the RFCs it seems that `jti` is an [optional](https://tools.ietf.org/html/draft-ietf-oauth-access-token-jwt-01#section-2.2) claim when it comes to `JWT`. I also see that `access_tokens` with `JWT` format include this claim by default because they're [persisted](https://github.com/panva/node-oidc-provider/blob/b5489a4a880339032b6281957dbe6a8299361aa2/lib/models/base_model.js#L47).  I'd like to add the `jti` claim to ID Tokens as well. 

**Describe the solution you'd like**
Can we have a configuration to do just that?

**Describe alternatives you've considered**
I can add it to the result of the `findById` properties and have `oidc-provider` pick it up from there. Is this the correct way of doing it?

**Additional context**

 - [x] i have searched the configuration section for this feature and couldn't find it
 - [x] i have searched the issues tracker on github for similar requests and couldn't find anything related.

**Comment by panva** [comment]
> I'd like to add the jti claim to ID Tokens as well.

Why?

**Comment by stavros-wb** [comment]
for audit logs mainly. being able to associate logs cross monitoring systems

**Comment by panva** [comment]
How about using a hash of the ID Token value for that? I don't feel like `jti` in an id token adds any value. If you can get it through regular claims, so be it.
