### ISSUE TITLE
Add FAQ item for native mobile apps

### ISSUE THREAD

**Issue by fiznool** [panva/node-oidc-provider#592]
I've been working on integrating a native mobile app with the provider and thought I'd document the approach here. I can't figure out how to add it to the wiki or submit a PR for it, so please add it if you see fit to do so.

    # How do I set up a native mobile client?

    Native mobile apps should use the [AppAuth](https://appauth.io) library wherever possible, which enforces the current best practices for native mobile apps, as outlined in [RFC 8252 - Oauth 2.0 for Native Apps](https://tools.ietf.org/html/rfc8252).

    To configure the provider to accept a native mobile client, make sure to set the following properties in the client configuration:

    ```javascript
    {
      application_type: 'native',
      token_endpoint_auth_method: 'none'
    }
    ```

    Also note the following:

    - Ensure that each native app uses a different client ID. For example, if you have an iOS and an Android app, use a separate client ID for each.
    - Do not set a `client_secret` for a native app, as it cannot be kept secret on the client.
    - When setting the `redirect_uris` client configuration, it is recommended to use an ['app-claimed' https URL](https://tools.ietf.org/html/rfc8252#section-7.2). If this is not possible, a ['reverse-domain' private use URI](https://tools.ietf.org/html/rfc8252#section-7.1) should be used, for example `com.domain.reversed://authcallback`.

**Comment by panva** [comment]
Thank you @fiznool, i'll see what i can do.
