### ISSUE TITLE
RefreshToken in JWT Format

### ISSUE THREAD

**Issue by cgeduhn** [panva/node-oidc-provider#593]
Hi, 

we‘ve been using version 5x before and we would like to update to version 6x but the refresh token were in jwt format in version 5x. So we expect some issues for some clients which might expext a jwt formatted refresh token. 
I‘ve tried to to set the RefreshToken: jwt option in the configuration but it seems to have no effect. 
Could someone help us out please :) ?

**Comment by panva** [comment]
Hi,

From the 6.x changelog

> only AccessToken and ClientCredentials may have a format. All other tokens are now forced to be opaque

Other tokens or artifacts don’t make sense as JWTs. In order to limit the surface to maintain i will not be reintroducing this
