### ISSUE TITLE
Token introspection request using bearer token authorization instead of client authentication?

### ISSUE THREAD

**Issue by dnandola-wyze** [panva/node-oidc-provider#594]
Hi,

First of all, thank you for all your effort in maintaining this repository and the comprehensive documentation provided to integrate it with others' environment. I've been playing with the package for a couple of weeks and am evaluating if this is a right solution for our organization. 

I am trying to make introspection request and while I am able to make requests using basic client authentication. However, when I try to do authorization using bearer token, I get error as "invalid authorization header value format". 

So, does node-oidc-provider support bearer token authorization given in RFC https://tools.ietf.org/html/rfc7662#section-2.1.  One way to resolve this is that I registered another OAuth client with client_credentials grant type and then used basic client authentication to do token introspection (which I can also do in resource servers). But, was wondering if I am missing something due to which the above is not working.

**Comment by panva** [comment]
Hi @dnandola-wyze 

You're not missing anything.

> To prevent token scanning attacks, the endpoint MUST also require
> some form of authorization to access this endpoint, **_such as client
> authentication as described in OAuth 2.0_** [RFC6749] or a separate
> OAuth 2.0 access token such as the bearer token described in OAuth
> 2.0 Bearer Token Usage [RFC6750].

The latter (separate oauth 2.0 access token) is not supported by oidc-provider.
