### ISSUE TITLE
How the check if user the is logged in/session active?

### ISSUE THREAD

**Issue by tmedanovic** [panva/node-oidc-provider#595]
Im trying to implement change password route so I need to check if the user is logged in or the session is active and maybe get accountId if that is something that is stored in the session.
What would be the best approach?

**Comment by panva** [comment]
Hi @tmedanovic 

#494 
#532
https://github.com/panva/node-oidc-provider/wiki/FAQ#how-to-display-on-the-website-of-the-op-itself-if-the-user-is-signed-in-or-not
