### ISSUE TITLE
Federated Login

### ISSUE THREAD

**Issue by Rogger794** [panva/node-oidc-provider#598]
Hi @panva,
I would like to know how to implement federated login like using Google. Is there an example or where can I see how to implement your library using federated login? as I see in your example https://tranquil-reef-95185.herokuapp.com/setup when login is clicked.

**Comment by panva** [comment]
Hi @Rogger794,

`https://op.panva.cz` which is the instance that client page uses is [here](https://github.com/panva/node-oidc-provider/blob/master/certification/oidc.js). It is not the only way to do so, but its an inspiration.

**Comment by Rogger794** [comment]
Thanks you @panva.
