### ISSUE TITLE
Adapter implementation

### ISSUE THREAD

**Issue by colinyip** [panva/node-oidc-provider#599]
I am recently trying to build something on top of node-oidc-provider and start thinking about what database to use to persist data. I've seen a few implementations in the example. Here are my questions, and would be really appreciated if there's any insight or if you can point me to any existing documentation:
- Should I pick a database that comes with built-in TTL support such as MongoDB and Redis? I saw there's a new example added with Postgres but I can't see how it handles expired data. Would it be ok to return undefined if the data is expired? the trade-off is we need something to clean up expired data otherwise the table would keep growing. or maybe just leave it?
- Is there any recommended requirements for the database? should I always pick one that provided strong consistency? or does it really depends on the use case where data loss is acceptable? An example would be picking a Redis cluster VS Postgres.

**Comment by panva** [comment]
> Should I pick a database that comes with built-in TTL support such as MongoDB and Redis?

It doesn't matter, the provider does not require you to drop expired records. It's all up to you, TTL support is convenient, but not required. If you choose to leave documents hanging around, it's your choice.

> Would it be ok to return undefined if the data is expired?

It's okay to both return undefined or return the expired document. All documents include an "exp" field and the provider will check it before passing the rest of the data to the model layer.

> Is there any recommended requirements for the database? should I always pick one that provided strong consistency? or does it really depends on the use case where data loss is acceptable? An example would be picking a Redis cluster VS Postgres.

Up to your best judgement again.

**Comment by colinyip** [comment]
Thanks for the explanation. :)
