### ISSUE TITLE
interaction session and authentication session mismatch

### ISSUE THREAD

**Issue by shayim** [panva/node-oidc-provider#600]
Could you please help me understand "interaction session and authentication session mismatch" error.

configuration:
****************
interactions: {
    policy: interactionPolicy.base(),
    url(ctx) {
      return `/account/${ctx.oidc.uid}`;
    },
  },
clients: [
    {
      client_id: 'client',
      client_secret: 'secret',
      **default_max_age: 60**,
      redirect_uris: ['http://example.com/cb']
    }
]
*********************
new account register route (GET & POST):  /account/:uid/register
*** POST *** 
 let account = new AccountData(register)
     // await account.save()
    const result: InteractionResults = { login: { account: account.id, remember: false } }
    const returnTo = await this.provider.interactionResult(req, res, result)
    res.redirect(returnTo)
********************
The problem is when I do the first register a new account, it is all fine, I got  one session and one authorization code , but after 1 minutes, I do the second register a new account, I got the error.

**Comment by panva** [comment]
> Could you please help me understand "interaction session and authentication session mismatch" error.

https://github.com/panva/node-oidc-provider/blob/v6.17.0/lib/actions/authorization/resume.js#L41-L43

The above you posted wouldn't be enough for anyone to reproduce your issue.
