### ISSUE TITLE
Plug-in concept for check_scope.js?

### ISSUE THREAD

**Issue by ChristofSchwarz** [panva/node-oidc-provider#601]
In my implementation of this oidc-provider I had to add a custom behaviour into lib\actions\authorization\check_scope.js where I am adding the session id issued to a global array of my NodeJS app. I don't like to change it that way, because if I do "npm install" again, this is part of the imported modules. Is there a way to add this without overwriting your check_scope.js? 
I also want to add my own logout.ejs page. Thank you

**Comment by panva** [comment]
You're modifying `check_scope.js`?

1) do you realize that's private API and not to be relied upon?
2) even if you required the implementation and wrapped it, it's still a private API not to be relied upon.

The actual "what do you want to achieve" is not clear here and no there's no way to plug in to an arbitrary private API.

**Comment by ChristofSchwarz** [comment]
The short version is, I want to achieve a single-signon for Qlik Sense, so I am issuing a ticket number for a user-claim before the signin starts. The signin begins with contacting the authentication_endpoint (/auth?client_id=...state=...return_uri=...) ... at this very moment your oidc-provider issues a _session number to treat the incoming authentication request and sets a browser cookie. I need to remember two things from /auth: the state and the issued _session ... with this, I can later, in interaction.js, use my original user-claim instead of a username/password prompt

**Comment by panva** [comment]
What I still don't get why is a solution to something like that overwriting `check_scope`. Especially given there are a number of [events](https://github.com/panva/node-oidc-provider/blob/master/docs/events.md) emitted or a post-[middleware](https://github.com/panva/node-oidc-provider/blob/master/docs/README.md#pre--and-post-middlewares) available for you to hook into.

**Comment by ChristofSchwarz** [comment]
That is what I overlooked, such per-design hook points. Seems to be exactly what I was after. Thanks for the great work on this oidc-provider
