### ISSUE TITLE
Passing Errors to the client in the callback

### ISSUE THREAD

**Issue by kareha** [panva/node-oidc-provider#602]
Hi,

when I get an error, for example:

`oidc-provider:authentication:error uid=nXErYso3GrKtA81mJX_qL { error: 'unauthorized_client', error_description: 'response_type not allowed for this client', state: 'oJhxDUa3kghj4ssV28cL161ihh0mJJtD-UDFxyKMoDc' } +24ms`

What happens is, that the client (node openid-client) does not get the error in the callback. I don't know why or what I do wrong.
I'm using the authorization_code grant for this client.

Should the error be passed to the callback in the body? Or does it work differently, like stop at the Provider and render the error at that side?

This results in a redirect-ping-pong situation, where the browser cancels the request after a while.

Thank you!

**Comment by panva** [comment]
> I don't know why or what I do wrong.

Unfortunately I can't possibly know from this report either.

Errors are always redirected back to the client if the client_id and redirect_uri is verified.

**Comment by kareha** [comment]
The response_mode was a good hint. I added { response_mode: 'form_post' } and I received the error message.
Didn't find anything on the documentation.
Thank you.
