### ISSUE TITLE
Add first party client flag to client attributes

### ISSUE THREAD

**Issue by jogee** [panva/node-oidc-provider#603]
In some flows we might want to skip user consent, for example when you own both the authorization and the client application so there is a high level of trust between the two. In current flow you might also create an account and get presented a consent screen immediately after logging on the first time asking to have access to your data even though you didn't use the application yet.

If we could add a 'first_party' application flag on client, similar to what [Auth0 is doing](https://auth0.com/docs/api-auth/user-consent), we can mark these applications to skip consent.

It could be possible now with implementing the policies by storing a separate record, but it would be nice if it was included in the client, then an additional database query wouldn't be necessary.

If you think it's a good idea I could try to submit a pull request.

Ref: https://github.com/panva/node-oidc-provider/issues/148#issuecomment-447284533

**Comment by panva** [comment]
https://github.com/panva/node-oidc-provider/blob/master/docs/README.md#extraclientmetadata

You can already define whatever client metadata using this configuration.

**Comment by jogee** [comment]
That will do too, thanks.

**Comment by jogee** [comment]
I've added the flag with the help of the extra client metadata and it's working but I still can't get entirely past the consent screen since we use a mobile app and we need to have a refresh token. Then we need to use the `prompt=consent` which always shows the consent screen.

The oidc spec states 'MUST ensure that the prompt parameter contains consent unless other conditions for processing the request permitting offline access to the requested resources are in place'. If client did contain a `is_first_party` check it would be possible to skip the consent screen, even for offline_access scope.

Is there another way or isn't this currently possible?

**Comment by panva** [comment]
`offline_access` scope which is the default condition for issuing a refresh token is 100% conditioned by `prompt=consent`. If you wish to issue refresh tokens under other conditions, [configure them](https://github.com/panva/node-oidc-provider/blob/master/docs/README.md#issuerefreshtoken).

I do not recommend skipping consent even for first party apps unless they use claimed https uris tho.
