### ISSUE TITLE
Dynamic scopes documentation

### ISSUE THREAD

**Issue by dnandola-wyze** [panva/node-oidc-provider#604]
Hi,

I am trying to design custom scopes for auth server, which can be configured in different clients and came across dynamic scopes configuration. However, I don't find  much documentation or specifications on it. Is there a brief explanation on what the dynamic scopes are used for and how to implement them?

Thanks
Dhrumin

**Comment by panva** [comment]
Other than [this](https://github.com/panva/node-oidc-provider/blob/master/docs/README.md#dynamicscopes) I don't have any other material.

I'll say that its intended for exactly what's in that expandable section there, scope values that have dynamic portions in them.

I recognize that today's way of configuring and checking if arbitrary scope values should be allowed to be requested is not great and i plan to work on that as soon as i have the time.

**Comment by dnandola-wyze** [comment]
@panva , I see, thank you. So, if I define a dynamic scope, do I need to configure allowed scopes with exact value when I configure a client? I see that dynamic scope is not supported on the client side. Or, all clients also support dynamic scopes defined in the configuration?

**Comment by panva** [comment]
There's an undocumented feature for this.

```
const { Provider, DYNAMIC_SCOPE_LABEL } = require('oidc-provider')
const SIGN = /^sign:[a-fA-F0-9]{2,}$/
SIGN[DYNAMIC_SCOPE_LABEL] = 'sign:{hex}';

new Provider('http://op.example.com', {
  dynamicScopes: [SIGN],
  clients: [
    {
      // ...
      scope: 'openid sign:{hex}'
    }
  ]
})
```

**Comment by dnandola-wyze** [comment]
Perfect, thank you! This is exactly what I was looking for.
