### ISSUE TITLE
Conformance/Sanity test for custom adapters

### ISSUE THREAD

**Issue by dnandola-wyze** [panva/node-oidc-provider#605]
Hi @panva ,

I plan to write my own custom dynamodb adapter (and maybe combine with cache like DAX for faster lookup based on performance testing), to be used  in my project and hopefully I can contribute the solution once all goes well. I am wondering if there are any set of conformance/sanity tests which I can use to inject my adapter and see if I am able to comply to all the flows?
Thanks for all your help,

Dhrumin

**Comment by panva** [comment]
There isn’t. But I’ll be happy to review your work.

**Comment by dnandola-wyze** [comment]
Thank you!
