### ISSUE TITLE
ID token still does not include claims other than sub [after reading the FAQ]

### ISSUE THREAD

**Issue by chakwok** [panva/node-oidc-provider#608]
The program return an idtoken (from the redirected after login) that does not include claims other than sub. I tried requesting from either scope parameter and claims parameters.

Also, I would also like to ask this is best way in v6.0+ to get both idtoken(with custom claims) and refresh_token? 

In v5.x I used to do, but it seems to be no longer working in v6.0+
`/auth -> /login (get both idtoken and code) -> /token (get refresh_token)`

Thank you panva.

Provider configuration: 
```
const configuration = {
  features: {
    devInteractions: false,
    claimsParameter: true,
  },
  scopes: ['openid', 'offline_access', 'email', 'profile'],
  routes,
  jwks,
  claims: {
    acr: null,
    sid: null,
    auth_time: null,
    iss: null,
    address: ['address'],
    email: ['email', 'email_verified'],
    phone: ['phone_number', 'phone_number_verified'],
    profile: ['birthdate', 'family_name', 'gender', 'given_name', 'locale', 'middle_name', 'name',
    'nickname', 'picture', 'preferred_username', 'profile', 'updated_at', 'website', 'zoneinfo'],
    openid: [ 'sub' ],
    role: ['role']
  },
  conformIdTokenClaims: false,
  findAccount: async function(ctx, sub, token) {
    console.log("finding account")
    return  {
      accountId: sub,
      claims: async function(use, scope, claims, rejected) {
           return await accounts.findOne(userId: sub);
        }
      }
    }
  }
};
const clients = [  {
    client_id: oidcConfig.client_id,
    client_secret: oidcConfig.client_secret,
    grant_types: ['authorization_code', 'implicit', 'refresh_token'],
    response_types: [ 'id_token', 'code id_token'],
    redirect_uris: oidcConfig.redirect_uris,
  },
];
  let adapter = MongoAdapter
  await adapter.connect();
  const provider = new Provider('http://localhost/', {adapter, ...configuration, clients});
```

Client Request:
`  const authUrl = OIDCPROVIDER_DOMAIN + '/auth?grant_type=authorization_code&client_id='+oidcConfig.client_id +'&scope=openid&access_type=offline&response_type=id_token&nonce=' + Math.random().toString().substr(2) + '&claims=' + encodeURIComponent('{"id_token":{"role":{"essential":true},"locale":{"essential":true},"email":{"essential":true},"picture":{"essential":true},"name":{"essential":true}}}');
`

**Comment by panva** [comment]
1) your authorization request parameters are weird, there should be no grant_type or access_type
2) Don't use Math.random as a nonce, neither as a state
3) This request will never issue both `id_token` and a `code`, you need to actually request the hybrid response_type `code id_token`
4) Given this configuration, if you're not getting claims its because `accounts.findOne` is not actually returning them in the format they're [expected](https://github.com/panva/node-oidc-provider/blob/master/docs/README.md#findaccount)

**Comment by chakwok** [comment]
3. Didn't you mention in [FAQ1](https://github.com/panva/node-oidc-provider/blob/master/docs/README.md#id-token-does-not-include-claims-other-than-sub). that Only response types that do not end up with an access_token (so, response_type=id_token) have end-user claims other than sub in their ID Tokens.

4. the `accounts.findOne` returns a json object of the user. I am using the same implementation as in v5.x, so that should not be a problem. Anyway I tried a hardcoded version but it still does not work

It still does not work with the new configuration:

the updated auth url: 
```
const crypto = require('crypto');
var nonce = crypto.randomBytes(16).toString('base64');

const authUrl = OIDCPROVIDER_DOMAIN + '/auth?client_id='+oidcConfig.client_id +'&scope=openid&response_type=code%20id_token&nonce=' + nonce  + '&claims=' + encodeURIComponent('{"id_token":{"role":{"essential":true},"locale":{"essential":true},"email":{"essential":true},"picture":{"essential":true},"name":{"essential":true}}}');
```

updated findAccount:
```
  findAccount: async function findAccount(ctx, sub, token) {
    // @param ctx - koa request context
    // @param sub {string} - account identifier (subject)
    // @param token - is a reference to the token used for which a given account is being loaded,
    //   is undefined in scenarios where claims are returned from authorization endpoint
    return {
      accountId: sub,
      async claims(use, scope, claims, rejected) {
        return { sub, email: "test@gmail.com", picture: "a.jpg"};
      },
    };
  }


```

**Comment by panva** [comment]
3) you provided the `conformIdTokenClaims: false` option to get around that spec behaviour
4) i see your error now, in v6.x feature configurations are [objects](https://github.com/panva/node-oidc-provider/blob/master/docs/README.md#featuresclaimsparameter), not booleans.

**Comment by chakwok** [comment]
Ohhh, how did I miss that the whole afternoon... 

Anyways, thanks for your help and for the awesome library

**Comment by panva** [comment]
No problem, please consider [supporting](https://github.com/panva/node-oidc-provider?sponsor=1) the library if it provides value and the support was of help.

**Comment by chakwok** [comment]
Just a side note. I am not sure if it is expected, but it seems strange to me. 

When I put `&scope=openid%20offline_access` in my auth url. The OP always recognize the `scope: 'openid'`. But when I use `&scope=openid%20email`, it works just fine getting ` scope: 'openid email'`. The configuration I use for OP is the same as above.

**Comment by panva** [comment]
That's intended, `offline_access` is ignored unless combined with `prompt=consent` as per the Core 1.0 specification.

**Comment by panva** [comment]
https://github.com/panva/node-oidc-provider/blob/v6.17.3/lib/actions/authorization/check_scope.js#L44-L62
