### ISSUE TITLE
TypeScript definitions regression: incompatible with koa-mount

### ISSUE THREAD

**Issue by thecopy** [panva/node-oidc-provider#609]
**Describe the bug**
I used `6.12.7`, i upgraded to `6.17.3` (latest as of writing), then the issue appeared. I upgraded to latest `koa-mount` and `koa` (`4.0.0` and `2.11.0` respectively) but the issue persisted.

**To Reproduce**
`app.use(mount(oidcProvider.app))` yeilds:
```
Argument of type 'Application<DefaultState, DefaultContext>' is not assignable to parameter of type 'Middleware<ParameterizedContext<DefaultState, ParameterizedContext<DefaultState, DefaultContext>>> | import("/Users/thecopy/dev/sso/sso-oidc-server/app/node_modules/@types/koa/index.d.ts")<...>'.
  Type 'Application<DefaultState, DefaultContext>' is not assignable to type 'import("/Users/thecopy/dev/sso/sso-oidc-server/app/node_modules/@types/koa/index.d.ts")<DefaultState, ParameterizedContext<DefaultState, DefaultContext>>'.
    Types of property 'context' are incompatible.
      Type 'BaseContext & DefaultContext' is not assignable to type 'BaseContext & ExtendableContext & { state: DefaultState; } & DefaultContext'.
        Type 'BaseContext & DefaultContext' is missing the following properties from type 'ExtendableContext': app, request, response, req, and 4 more.ts(2345)
```

Steps to reproduce the behaviour:

1.  Use oidc-provider `6.17.3`
2.  Try to mount on Koa

**Expected behaviour**

**Environment:**
 - oidc-provider version: `6.12.7`
 - node version: `12.3.1`
 - typescript version `3.7.2`

**Additional context**

 - [x] the bug is happening on latest oidc-provider too.
 - [x] i have tried DEBUG (see README) and can see the issue is with the provider and not my code.
 - [x] i have searched the issues tracker on github for similar issues and couldn't find anything related.
 - [x] i have searched the [FAQ](https://github.com/panva/node-oidc-provider/blob/master/docs/README.md#faq) and couldn't find anything related.

**Logs**
(does not compile)

**Comment by panva** [comment]
@thecopy there was no change in the typings related to `Provider.prototype.app` since v6.12.7, hence I don't see where a regression could have been introduced.

Furthermore, i can't reproduce your issue...

package.json
```json
{
  "dependencies": {
    "@types/koa": "^2.11.0",
    "@types/koa-mount": "^4.0.0",
    "koa": "^2.11.0",
    "koa-mount": "^4.0.0",
    "oidc-provider": "^6.17.3"
  }
}
```

```typescript
import { Provider } from 'oidc-provider'
import * as Koa from 'koa'
import * as mount from 'koa-mount'

const provider = new Provider('http://localhost:3000')

const app = new Koa()

app.use(mount(provider.app))
```

No compile problems.
