### ISSUE TITLE
unrecognized route or not allowed method (GET on /session/end/confirm)

### ISSUE THREAD

**Issue by stefdaems** [panva/node-oidc-provider#610]
**Describe the bug**
Default config for terminating/ending a session results in error:

unrecognized route or not allowed method (GET on /session/end/confirm)

The default logoutSource is used, not overwritten by a custom configuration. It should be performing a POST request, but the default config is not executing it as POST, but as GET.

**To Reproduce**
```
/session/end?id_token_hint=xxx.yy.zzz
and confirm
I'm redirect to /session/end/confirm which is showing the error
```

Steps to reproduce the behaviour:

1.  /session/end?id_token_hint=xxx.yy.zzz
2.  confirm
3.  /session/end/confirm showing the error

**Expected behaviour**
The session should be terminated and removed from cache.

**Environment:**
 - oidc-provider version: v6.6.2
 - node version: v12.13.1

**Additional context**
I want to terminate the existing session for my customer in order to have the customer login again.

 - [ ] the bug is happening on latest oidc-provider too.
 - [x ] i have tried DEBUG (see README) and can see the issue is with the provider and not my code.
 - [x ] i have searched the issues tracker on github for similar issues and couldn't find anything related.
 - [x ] i have searched the [FAQ](https://github.com/panva/node-oidc-provider/blob/master/docs/README.md#faq) and couldn't find anything related.

**Logs
Wed, 11 Dec 2019 16:15:42 GMT express:router dispatching GET /session/end/confirm
Wed, 11 Dec 2019 16:15:42 GMT express:router query  : /session/end/confirm
Wed, 11 Dec 2019 16:15:42 GMT express:router expressInit  : /session/end/confirm
Wed, 11 Dec 2019 16:15:42 GMT express:router expressMiddleware  : /session/end/confirm
Wed, 11 Dec 2019 16:15:42 GMT express:router logger  : /session/end/confirm
Wed, 11 Dec 2019 16:15:42 GMT express:router corsMiddleware  : /session/end/confirm
Wed, 11 Dec 2019 16:15:42 GMT express:router helmet  : /session/end/confirm
Wed, 11 Dec 2019 16:15:42 GMT express:router <anonymous>  : /session/end/confirm
Wed, 11 Dec 2019 16:15:42 GMT express:router rawParser  : /session/end/confirm
Wed, 11 Dec 2019 16:15:42 GMT body-parser:raw skip empty body
Wed, 11 Dec 2019 16:15:42 GMT express:router urlencodedParser  : /session/end/confirm
Wed, 11 Dec 2019 16:15:42 GMT body-parser:urlencoded skip empty body
Wed, 11 Dec 2019 16:15:42 GMT express:router jsonParser  : /session/end/confirm
Wed, 11 Dec 2019 16:15:42 GMT body-parser:json skip empty body
Wed, 11 Dec 2019 16:15:42 GMT express:router <anonymous>  : /session/end/confirm
Wed, 11 Dec 2019 16:15:42 GMT express:router <anonymous>  : /session/end/confirm
Wed, 11 Dec 2019 16:15:42 GMT express:router <anonymous>  : /session/end/confirm
Wed, 11 Dec 2019 16:15:42 GMT express:router serveStatic  : /session/end/confirm
Wed, 11 Dec 2019 16:15:42 GMT send stat "/opt/ys_openid_service/src/css/session/end/confirm"
Wed, 11 Dec 2019 16:15:42 GMT express:router handleRequest  : /session/end/confirm
2019-12-11T16:15:42.523Z oidc-provider:error uid=undefined path=/session/end/confirm method=GET error={ error: 'invalid_request', error_description: 'unrecognized route or not allowed method (GET on /session/end/confirm)' } detail=undefined

**Comment by panva** [comment]
@stefdaems Can you paste the rendered confirmation page html? I doubt there's an issue here other than something either specific browser or environment related.

**Comment by stefdaems** [comment]
`
<html><head>
  <meta charset="utf-8">
  <title>Logout Request</title>
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <meta http-equiv="x-ua-compatible" content="ie=edge">
  <style>
  @import url(https://fonts.googleapis.com/css?family=Roboto:400,100);button,h1{text-align:center}h1{font-weight:100;font-size:1.3em}body{font-family:Roboto,sans-serif;margin-top:25px;margin-bottom:25px}.container{padding:0 40px 10px;width:274px;background-color:#F7F7F7;margin:0 auto 10px;border-radius:2px;box-shadow:0 2px 2px rgba(0,0,0,.3);overflow:hidden}button{font-size:14px;font-family:Arial,sans-serif;font-weight:700;height:36px;padding:0 8px;width:100%;display:block;margin-bottom:10px;position:relative;border:0;color:#fff;text-shadow:0 1px rgba(0,0,0,.1);background-color:#4d90fe;cursor:pointer}button:hover{border:0;text-shadow:0 1px rgba(0,0,0,.3);background-color:#357ae8}
  </style>
</head>
<body>
  <div class="container">
    <h1>Do you want to sign-out from openid-playsports-edp.ocean-service.be?</h1>
    <form id="op.logoutForm" method="post" action="<ourUrl_Removed_for purpose now>/session/end/confirm"><input type="hidden" name="xsrf" value="47d98dd5ef10dd0aa2fb0c7c27f1812bb57e52954adb4fbb"></form>
    <button autofocus="" type="submit" form="op.logoutForm" value="yes" name="logout">Yes, sign me out</button>
    <button type="submit" form="op.logoutForm">No, stay signed in</button>
  </div>

</body></html>
`

**Comment by stefdaems** [comment]
Remove the urls but this is the form which I get. No method="post" could be found 
 ```
<html><head>
  <meta charset="utf-8">
  <title>Logout Request</title>
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <meta http-equiv="x-ua-compatible" content="ie=edge">
  <style>
  @import url(https://fonts.googleapis.com/css?family=Roboto:400,100);button,h1{text-align:center}h1{font-weight:100;font-size:1.3em}body{font-family:Roboto,sans-serif;margin-top:25px;margin-bottom:25px}.container{padding:0 40px 10px;width:274px;background-color:#F7F7F7;margin:0 auto 10px;border-radius:2px;box-shadow:0 2px 2px rgba(0,0,0,.3);overflow:hidden}button{font-size:14px;font-family:Arial,sans-serif;font-weight:700;height:36px;padding:0 8px;width:100%;display:block;margin-bottom:10px;position:relative;border:0;color:#fff;text-shadow:0 1px rgba(0,0,0,.1);background-color:#4d90fe;cursor:pointer}button:hover{border:0;text-shadow:0 1px rgba(0,0,0,.3);background-color:#357ae8}
  </style>
</head>
<body>
  <div class="container">
    <h1>Do you want to sign-out from xxxx_removed___?</h1>
    <form id="op.logoutForm" method="post" action="xxxx_removed_xxxx/session/end/confirm"><input type="hidden" name="xsrf" value="47d98dd5ef10dd0aa2fb0c7c27f1812bb57e52954adb4fbb"></form>
    <button autofocus="" type="submit" form="op.logoutForm" value="yes" name="logout">Yes, sign me out</button>
    <button type="submit" form="op.logoutForm">No, stay signed in</button>
  </div>

</body></html>
```

**Comment by panva** [comment]
> No method="post" could be found

Really?

> `<form id="op.logoutForm" method="post"`
