### ISSUE TITLE
Custom session

### ISSUE THREAD

**Issue by vdtn359** [panva/node-oidc-provider#611]
**Is your feature request related to a problem? Please describe.**
I use express-session to create our own session in the Redis store. I would like to tie the OIDC session to the Redis store session so they have the same lifetime. However, it does not seem easy to create your own OIDC session.

**Describe the solution you'd like**
Would it be possible to pass the OIDC context to the adapter constructor so that I could have access to the HTTP request and my session store?

**Comment by panva** [comment]
> would it be possible to pass the OIDC context to the adapter constructor

Very unlikely to happen, for one, adapter constructor is only called once for each model class, not instance, two, oidc context is not passed around alone anywhere. I guess what you mean is to get access to the koa ctx in adapter method calls, but even that i'm not a big fan of and don't have a solution for right now.
