### ISSUE TITLE
How to link interactionResult/Session to AuthorizationCode?

### ISSUE THREAD

**Issue by brandonros** [panva/node-oidc-provider#612]
1. `/auth` request is kicked off
2. user gets redirected to `/interaction/:interactionId`
3. consent check happens, then user gets redirected to `/interaction/:interactionId/finish`. 
4. `interactionResult()` is called with

```
  const userId = '...' /// calculated
  const deviceId = '...' /// calculated
  const deviceInfo = '...' /// calculated
  const interactionResult = {
    login: {
      account: userId
    },
    consent: {
      rejectedScopes: [],
      rejectedClaims: []
    },
    meta: {
      deviceId,
      deviceInfo
    }
  }
```
1. Successful interaction/authorization is turned into an `AuthorizationCode`
1. user calls `/token` with `code` + client credentials
1. there is no way to link sessionId values back to the interactionResult during claims resolution. I'm trying to get the values stored in `interactionResult.meta` during claims resolution and it seems impossible/extremely hacky. Any suggestions?

**Comment by panva** [comment]
You can do `provider.Session.findByUid(token.sessionUid)` to get the session it came from...
