### ISSUE TITLE
/end/session/confirm doesn't delete session in redis Adapter

### ISSUE THREAD

**Issue by stefdaems** [panva/node-oidc-provider#613]
**Describe the bug**
I follow the session/end and /session/end/confirm/ flow to get users redirected to the login pages again and revoke their current login. Just the usual logout flow should be executed resulting in a relogin for the users. But it seems the users session can be found in the redis again and the user is automatically logged in again, no credentials are requested.

**To Reproduce**
Provider and Client configuration: (inline or gist)
```js
/session/end
/session/end/confirm --> Afterwards the customer is redirect to the post_logout_redirect_uri which was passed in the request.
```

Steps to reproduce the behaviour:

1.  hit session/end endpoint
2.  hit session/end/confirm
3.  post_logout_redirect_uri is opened
4. hit /authorize endpoint again

**Expected behaviour**
User should enter his/her credentials again

**Environment:**
 - oidc-provider version: 6.6.2
 - node version: v12.10.0

**Additional context**

 - [x] the bug is happening on latest oidc-provider too.
 - [x] i have tried DEBUG (see README) and can see the issue is with the provider and not my code.
 - [x] i have searched the issues tracker on github for similar issues and couldn't find anything related.
 - [x] i have searched the [FAQ](https://github.com/panva/node-oidc-provider/blob/master/docs/README.md#faq) and couldn't find anything related.

**Logs**
Can't see anything wrong in the logs

**Comment by panva** [comment]
https://tranquil-reef-95185.herokuapp.com logout works as intended, its even certified with the OIDF certification tools to actually process the logout.

@stefdaems i don't know enough about your deployment but based on your past issues there must be something wonky going on.
