### ISSUE TITLE
Regression in 6.17.4 - TypeError: features are no longer enabled/disabled with a boolean value, please see the docs

### ISSUE THREAD

**Issue by ddolcimascolo** [panva/node-oidc-provider#614]
Hi @panva 

I have failing tests when upgrading from v6.17.3 to patch release v6.17.4. As these are breaking changes you should either:
*  Revert
*  Release as a new major version

Thanks,
Regards,

David

**Comment by ddolcimascolo** [comment]
I've spotted the new configuraiton format, I must have missed than when migrating to v6... Anyway, I strongly suggest you do not remove support for boolean features in a patch release

Thx,

David

**Comment by panva** [comment]
> Anyway, I strongly suggest you do not remove support for boolean features in a patch release

This format was actually removed with v6.0.0, there's no regression and no breaking change.

v6.x never supported boolean feature values - as in, its not using them, at all, instead its falling back to the feature's default values when non object is encountered.

You've just been alerted to having invalid configuration now... i'd say thats good.
