### ISSUE TITLE
Change Access Token TTL based on account

### ISSUE THREAD

**Issue by fiznool** [panva/node-oidc-provider#615]
I'd like to be able to set the access token TTL to a specific value, depending on the user account associated with the token.

I can see that the `ttl.AccessToken` configuration key can be a function, which is passed three args:

``` js
{
  ttl: {
    AccessToken(ctx, token, client) {
      // Return the TTL synchronously
    },
  },
}
```

Since this function must return a number synchronously, I cannot use `token.accountId` to query my user database for the TTL to use. Instead, I thought I could use the `token.claims` property, and use a custom claim (e.g. a permission level) to determine the TTL to set. However, I can't figure out where the claims are set in the access token (all I can see is an empty array of `rejected` inside the claims object).

Can you shed any light here or offer an alternative approach?

**Comment by panva** [comment]
> Can you shed any light here or offer an alternative approach?

`ctx.oidc.entities.Account` should be already loaded for you by the time an access token is being issued.

**Comment by fiznool** [comment]
Perfect, just what I needed, thanks!

**Comment by panva** [comment]
No problem, please consider [supporting](https://github.com/panva/node-oidc-provider?sponsor=1) the library if it provides value to your or your company and this and the previous support was of help to you.
