### ISSUE TITLE
WhitelistedJWA.idTokenSigningAlgValues not working for PS256

### ISSUE THREAD

**Issue by SeanStannard** [panva/node-oidc-provider#619]
**Describe the bug**

I'm setting up a simple OIDC server.  The code is:

`const { Provider } = require('oidc-provider');

const provider = new Provider('http://localhost:3002', {
  claims: {
    email: ['email', 'email_verified'],
    phone: ['phone_number', 'phone_number_verified'],
    profile: ['birthdate', 'family_name', 'gender', 'given_name', 'locale', 'middle_name', 'name', 'nickname', 'picture', 'preferred_username', 'profile', 'updated_at', 'website', 'zoneinfo']
  },
    clients: [
    {
        client_id: 'development-authorization',
        application_type: 'web',
        token_endpoint_auth_method: 'private_key_jwt',
        response_types: ['code id_token'],
        grant_types: ['implicit', 'authorization_code'],
        redirect_uris: ['https://www.google.com/']
      }
    ],
    whitelistedJWA: {
    idTokenSigningAlgValues: [
        'PS256'
        ]   
    }
});

const server = provider.listen(3002, () => {
  console.log('oidc-provider listening on port 3002, check http://localhost:3002/.well-known/openid-configuration')
})`

Steps to reproduce the behaviour:

1.  Run the code with `node server.js`
2.  Use a 'Get' on http://localhost:3002/.well-known/openid-configuration
3.  See the configuration response

The output is:
`{
    "authorization_endpoint": "http://localhost:3002/auth",
    "claims_parameter_supported": false,
    "claims_supported": [
        "sub",
        "email",
        "email_verified",
        "phone_number",
        "phone_number_verified",
        "birthdate",
        "family_name",
        "gender",
        "given_name",
        "locale",
        "middle_name",
        "name",
        "nickname",
        "picture",
        "preferred_username",
        "profile",
        "updated_at",
        "website",
        "zoneinfo",
        "sid",
        "auth_time",
        "iss"
    ],
    "code_challenge_methods_supported": [
        "S256"
    ],
    "end_session_endpoint": "http://localhost:3002/session/end",
    "grant_types_supported": [
        "implicit",
        "authorization_code",
        "refresh_token"
    ],
    "id_token_signing_alg_values_supported": [],
    "issuer": "http://localhost:3002",
    "jwks_uri": "http://localhost:3002/jwks",
    "request_object_signing_alg_values_supported": [
        "HS256",
        "RS256",
        "PS256",
        "ES256"
    ],
    "request_parameter_supported": false,
    "request_uri_parameter_supported": true,
    "require_request_uri_registration": true,
    "response_modes_supported": [
        "form_post",
        "fragment",
        "query"
    ],
    "response_types_supported": [
        "code id_token",
        "code",
        "id_token",
        "none"
    ],
    "scopes_supported": [
        "openid",
        "offline_access",
        "email",
        "phone",
        "profile"
    ],
    "subject_types_supported": [
        "public"
    ],
    "token_endpoint_auth_methods_supported": [
        "none",
        "client_secret_basic",
        "client_secret_jwt",
        "client_secret_post",
        "private_key_jwt"
    ],
    "token_endpoint_auth_signing_alg_values_supported": [
        "HS256",
        "RS256",
        "PS256",
        "ES256"
    ],
    "token_endpoint": "http://localhost:3002/token",
    "userinfo_endpoint": "http://localhost:3002/me",
    "userinfo_signing_alg_values_supported": [
        "HS256",
        "RS256"
    ],
    "claim_types_supported": [
        "normal"
    ]
}`

**Expected behaviour**
I was expecting the output to have:
"id_token_signing_alg_values_supported": ["PS256"]
but instead, we get:
"id_token_signing_alg_values_supported": []

**Environment:**
 - oidc-provider version: 6.17.6
 - node version: v10.16.3

**Comment by panva** [comment]
You must provide your own jwks. The default dev one does only have RS256 key in it.
