### ISSUE TITLE
Updating client configuration question

### ISSUE THREAD

**Issue by b0rza** [panva/node-oidc-provider#62]
Considering a scenario where clients get persisted in a storage in order to be accessed and configured via GUI...  The docs state that 
> each oidc-provider caches the clients once they are loaded. When your client configuration changes you should reload your processes.

That means updating clients on a live environment is out of the question if we want the changes to be visible? How would reloading the processes (restarting the server) impact the end user having a valid session? Would it be transparent to him, seeing as all the session data is persisted in the storage?

P.S.
Awesome library! 🎉

**Comment by panva** [comment]
> Considering a scenario where clients get persisted in a storage in order to be accessed and configured via GUI...

You have a GUI that uses a certain storage, then skip initializing clients, and rely on the configured adapter to load clients on demand?

**Comment by b0rza** [comment]
Exactly, that's the setting. 
I suppose they can also be initialized during the inital run, but if I understand correctly it does not matter if they are loaded via initialization or found via adapters #find method. 
The end result is the same: they are cached, correct?

My end goal is to update the cached client settings without disrupting the user flow.

**Comment by panva** [comment]
The reason why the cached data is not invalidated is that the client validation is potentially a very expensive operation.

There cannot be any user flow disruption, your session data, just as well as the tokens, are stored using the provided adapter, the library is ready and supports, thanks to those adapters, a distributed deployment.

Nonetheless, i would recommend to initialize the clients if they're fixed, and make sure your adapter does `return Promise.resolve(null)` on any Client.find calls. Reason for that is that you will know if your client configuration is correct during startup.

**Comment by panva** [comment]
Thinking about it further, it should be possible to wipe the cache on a provider instance programatically, as well as have a possibility to define a TTL for the cache.

**Comment by b0rza** [comment]
Thanks for the quick replies!
