### ISSUE TITLE
Restrict users to access specific clients (by not giving them access tokens)

### ISSUE THREAD

**Issue by kareha** [panva/node-oidc-provider#620]
Hi,

I want to restrict users to some clients (e.g. at authorization_code grant)
I was thinking about where to implement that check functionality.
Since the user could have an existing session with the provider und just calls the auth endpoint to do the redirect things, I could not use my interaction routes, because they are never trigger then.

So I have been looking at the interaction policy. I came up with the idea of adding a new check to the consent prompt like:

```
const { interactionPolicy: { Prompt, Check, base } } = Provider
let myCheck = new Check('myCheck', 'myCheck descr', 'error things', () => {}, (ctx) => {
  const { oidc } = ctx;
  console.log('You may not pass !!!!!')
  return false;
})
basePolicy.get('consent').checks.add(myCheck, 0)

```
But that also gets not triggert.

Do I have to add a hole new Prompt for that?

What could be a best practice for my problem?
Am I on the right track?

OIDC Provider and RP is controlled by the same instance. Not every user should be allowed to access every client (RP). Implementing the access check on client side doesn't seem to be a good solution, I guess.

Hope you get my question. Thanks in advance!

regards,
Stefan

**Comment by kareha** [comment]
Btw: Prompt and Check constructor signature is inconsistent. Prompt takes an object of parameters and Check takes multiple parameters for each attribute. Don't know if that is wanted :)

**Comment by panva** [comment]
Yes, an interaction policy is the way to hook in policies that should prevent tokens and codes from being issued when they shouldn't. You can abuse the check and throw e.g. `access_denied` when encountering something you don't want to allow and otherwise just resolve them.

Personally, i'd always pull these into new non requestable Prompt object, knowing it'll just be throwing and not actually asking for the prompt to be resolved via interactions...

**Comment by kareha** [comment]
Found my issue, now it works. It didn't trigger, because I got the constructor parameters order wrong.
If someone else has the same issue, they are:

new Prompt({ name<string>, requestable<boolean> }, details<function>)
new Check(reason<string>, description<string>, error<string>, check<function>, details<function>)

Thanks a lot! It helped.
