### ISSUE TITLE
Different protocols of issuer and other properties when accessing /.well-known/openid-configuration

### ISSUE THREAD

**Issue by lewiscxa** [panva/node-oidc-provider#621]
This might actually not a bug but a question. So basically, we have our server under a nginx proxy. The nginx server handle the https and certificate stuffs while the nodejs server only support http. When users try to access this API /.well-known/openid-configuration then here is the values for property `issuer` and `jwks_uri`.
```
issuer: "https://example.com/",
jwks_uri: "http://example.com/jwks",
```
This is how we construct the oidc-provider.
```
const provider = new OIDCProvider("https://example.com");
```
It looks like the protocol of `jwks_uri` is automatically taken from the host of nodejs server instead of being inherited from the issuer.

Do you know how to configuring the protocol of those 2 properties to https?

**Comment by panva** [comment]
Please check the docs FAQ or actually search the issue tracker

https://github.com/panva/node-oidc-provider/blob/master/docs/README.md#why-does-my-well-knownopenid-configuration-link-to-http-endpoints-instead-of-https-endpoints
