### ISSUE TITLE
How to handle "wrong username or password"?

### ISSUE THREAD

**Issue by jim-king-2000** [panva/node-oidc-provider#622]
I'm using node-oidc-provider as OIDC server. The default sample allows any username and password. Now I'm adding username/password verification to the server. The expected behavior is: if the username or password is wrong, redirect to the "login" page and show a warning test. How can I do it? How can I pass a parameter from "/interaction/:uid/login" to "/interaction/:uid"?

**Comment by panva** [comment]
How you structure and develop your interactions is intentionally out of scope for my support as well as the library, it’s completely agnostic to this. 

Please proceed as if you were developing the interactions in isolation, not tied to submitting the results on every form submit. Instead, only submit if you are satisfied with the result and then this is nothing more than your standard web development where you would re-render the view upon failed form submission.

**Comment by jim-king-2000** [comment]
I'm trying to use session to transfer the error message. So I'm calling `provider.setProviderSession()`.

```javascript
// POST /interaction/:uid/login
await provider.setProviderSession(ctx.req, ctx.res, {
  account: ctx.request.body.login,
  clients: ['oidcCLIENT'],
  meta: { oidcCLIENT: { error: 'Invalid username or password!' } },
});
ctx.redirect(`/interaction/${uid}`);
```

But the session is undefined when I read it from `provider.interactionDetails()`.

```javascript
const {
      uid, prompt, params, session // session is undefined
    } = await provider.interactionDetails(ctx.req, ctx.res);
```

Is there something wrong? Or I can't use session?
