### ISSUE TITLE
`ResponseType` is different in this repo to the one in openid-client

### ISSUE THREAD

**Issue by fiznool** [panva/node-oidc-provider#623]
When trying to use the same object for a provider and a client, I can see that the `ResponseType` typings are different in this provider repo to the `openid-client` repo.

Here are the differences:

``` ts
// Typings from provider repo shown first, client repo shown second.
export type ResponseType = 'code' | 'id_token' | 'code id_token' | 'id_token token' | 'code token' | 'code id_token token' | 'none';
export type ResponseType = 'code' | 'id_token' | 'code id_token' | 'code token' | 'code id_token token' | 'none';
```

As you can see, the provider repo allows the string `'id_token token'` as one of the allowed types, whereas the client repo does not.

Relevant lines:

- [Provider typing](https://github.com/panva/node-oidc-provider/blob/d3a772bd806f47ec046856fdfb779d2bb3cb5184/types/index.d.ts#L138)
- [Client typing](https://github.com/panva/node-openid-client/blob/dd4aae92eafbdde5ac11c2d7d422d150ceed45da/types/index.d.ts#L34)

**Comment by panva** [comment]
Clearly an omission on the client types. Please open a PR.
