### ISSUE TITLE
Question: How to generate a JWT access token?

### ISSUE THREAD

**Issue by jim-king-2000** [panva/node-oidc-provider#624]
In Auth0, we can acquire JWT access token by assigning an "audience" parameter so that we can verify it in the API side. Can we do the same in node-oidc-provider? If yes, how? If no, how can we use node-oidc-provider in backend API?

**Comment by panva** [comment]
@jim-king-2000 please get familiar with the available configuration first, it has the answers you need.

> How to generate a JWT access token?

Configuration > `formats.AccessToken` > `jwt-ietf` + enable the [IETF draft format](https://github.com/panva/node-oidc-provider/blob/master/docs/README.md#featuresietfjwtaccesstokenprofile)

> In Auth0, we can acquire JWT access token by assigning an "audience" parameter so that we can verify it in the API side.

You can't use the audience parameter but you can use the `resource` parameter as per the specification you can [enable](https://github.com/panva/node-oidc-provider/blob/master/docs/README.md#featuresresourceindicators).

**Comment by jim-king-2000** [comment]
Many thanks.

**Comment by jim-king-2000** [comment]
> @jim-king-2000 please get familiar with...

Forgive me, it is too complicated.

**Comment by panva** [comment]
> > @jim-king-2000 please get familiar with...
> 
> Forgive me, it is too complicated.

In that case please realise I do not have the bandwidth to support developers who clearly don't have the decency to read the documentation before opening issues that consume my time.
