### ISSUE TITLE
Adapter is undefined on latest version

### ISSUE THREAD

**Issue by ShlomitG** [panva/node-oidc-provider#625]
Hi,
I just upgraded from 5.5.2 version. I managed to adjust all the calls, and oidc-provider is starting up ok, but yet - sequalize adapter is undefined,
Is a change in adapter implementation required? I couldn't figure out such from the change log.

Please advise.

Using adapter in latest version (not working):
_import SequelizeAdapter = require('./adapters/sequelize');
....
    oidc = new Provider(ISSUER, { adapter: SequelizeAdapter, clients, keystore, ...configuration });_

Thanks.

**Comment by panva** [comment]
None of the adapters are part of the library. Never were. Notice they’re in the “example” folder.

**Comment by ShlomitG** [comment]
Yet, in the CHANGELOG of your package, you write: 

> _* provider will no longer call `adapter`'s `connect`
method._

If so, in my adapter (sequelize), where should I call sequelize.sync(), previously called from connect()? in the constructor?
(btw, in your example, connect is still there: https://github.com/panva/node-oidc-provider/blob/master/example/adapters/sequelize.js)

**Comment by panva** [comment]
> Yet, in the CHANGELOG of your package, you write:

Yeah so? It's not called by the library tho. See how the example folder deals with it. https://github.com/panva/node-oidc-provider/blob/v6.18.2/example/koa.js#L49-L70

Please keep in mind you said that `"adapter" is undefined`, with no stacktrace, no useful details.
