### ISSUE TITLE
Typescript interface for jwks not 100% correct

### ISSUE THREAD

**Issue by thecopy** [panva/node-oidc-provider#626]
**Describe the bug**
`Configuration.jwks` is declared as JSONWebKeySet, but instantiation of new `Provider` instance will fail if any key in the `jwks.keys` is an instance of a class and not a "pure" JS object. In this example classes from `JWK.Key` from the `jose` library. (Easily fixed by calling `Key.toJWK()`)

**To Reproduce**
Provider and Client configuration: (inline or gist)
```js
import jose, { JSONWebKeySet } from 'jose'
import { Provider } from 'oidc-provider'

const jwk = jose.JWK.generateSync('EC')
const jwks: JSONWebKeySet = { keys: [jwk] } // NOTE: fulfills contract of the `JSONWebKeySet` interface
new Provider('https://example.com/', {
  jwks
})
```

Yields:
```
Error: keystore must be a JSON Web Key Set formatted object
    at Provider.initializeKeystore (node_modules/oidc-provider/lib/helpers/initialize_keystore.js:62:11)
    at new Provider (node_modules/oidc-provider/lib/provider.js:129:24)
```

**Expected behaviour**
I expect `new Provider` to accept my `jwks` value since it fulfills the contract of `JSONWebKeySet`.

**Environment:**
 - oidc-provider version: [e.g. v6.18.1]
 - node version: [e.g. v12.13.1]

**Additional context**

 - [x] the bug is happening on latest oidc-provider too.
 - [x] i have tried DEBUG (see README) and can see the issue is with the provider and not my code.
 - [x] i have searched the issues tracker on github for similar issues and couldn't find anything related.
 - [x] i have searched the [FAQ](https://github.com/panva/node-oidc-provider/blob/master/docs/README.md#faq) and couldn't find anything related.

**Comment by panva** [comment]
If you can think of a way to ensure it is plain object in the types, please open a PR for that. Any other input than a plain object is not intended to be valid.
