### ISSUE TITLE
Disable implicit flow and keep id_token response type

### ISSUE THREAD

**Issue by vlad-cirstean** [panva/node-oidc-provider#627]
In lib/helpers/configuration.js:172 if the word token (token or id_token) is found in response_type then the implicit grant type is enabled in the server. I want to disable the implicit flow from the server but keep the id_token response type. It is a bug?

**Comment by panva** [comment]
No this is [intended](https://openid.net/specs/openid-connect-registration-1_0.html#ClientMetadata), the implicit grant in there still means just `id_token` response type is enabled.
