### ISSUE TITLE
weird error on relogin with different user

### ISSUE THREAD

**Issue by bob-sheknowdas** [panva/node-oidc-provider#628]
So here is my setup:
- I have my web application.
- This web app is using a keycloak server for user management.
- This keycloak on the other hand uses an oidc-provider app as secondary idp.

Here is how to reproduce my problem:
1. open web app and get redirected to keycloak
2. choose to log in via oidc-provider
3. type in username and password and confirm
4. get redirected to web app and be logged in  -->  so far so great
5. log out, get redirected to keycloak
6. choose to log in again via oidc-provider
7. type in username and password of a different valid user and confirm
8. error appears

This is my error message:
error: server_error
error_description: oops! something went wrong
Error: Undefined binding(s) detected when compiling DEL. Undefined column(s): [grantid] query: delete from "access_token" where "grantid" = ?

What i figgured out so far:
- It seems to be connected to the session cookies. If I delete the "_session" cookie the login works again
- It might be connected to using tls. Everything worked fine when I used a reverse proxy. Now I'm using standalone TLS and now the error occurs...

Do u have any idea, why I get this error?

**Comment by panva** [comment]
> Do u have any idea, why I get this error?

I don't, the error is not from the library, it is likely from an adapter implementation of yours. Maybe related to a missing field in your DB schema? I dunno.

**Comment by bob-sheknowdas** [comment]
For future readers encountering a similar problem.

My error was caused by the library calling `adapter.revokeByGrantId()` with `undefined`.
This happened whenever I logged in with user1, logged out and then logged in again with user2 (aka when a "_session" cookie was already present in my browser).

The error has the following stack trace:
```
at SqlDbAdapter.revokeByGrantId (/src/storage/dbadapter/sqldbadapter.js:219:9)
at Function.revokeByGrantId (/node_modules/oidc-provider/lib/models/mixins/has_grant_id.js:3:24)
at /node_modules/oidc-provider/lib/helpers/revoke_grant.js:16:42
at Array.map (<anonymous>)
at revokeGrant (/node_modules/oidc-provider/lib/helpers/revoke_grant.js:16:21)
at /node_modules/oidc-provider/lib/actions/end_session.js:176:23
at processTicksAndRejections (internal/process/task_queues.js:93:5)
at async Promise.all (index 0)
at async endSession (/node_modules/oidc-provider/lib/actions/end_session.js:165:11)
at async checkLogoutToken (/node_modules/oidc-provider/lib/actions/end_session.js:106:7)
at async selectiveBody (/node_modules/oidc-provider/lib/shared/selective_body.js:49:5)
at async parseBodyIfPost (/node_modules/oidc-provider/lib/shared/conditional_body.js:5:5)
at async sessionHandler (/node_modules/oidc-provider/lib/shared/session.js:22:5)
at async noCache (/node_modules/oidc-provider/lib/shared/no_cache.js:4:3)
at async errorHandler (/node_modules/oidc-provider/lib/shared/error_handler.js:23:7)
at async ensureSessionSave (/node_modules/oidc-provider/lib/helpers/initialize_app.js:49:7)
```

The error does not accur when using the default memory_adapter.
This is cause the default memory_adapter catches `undefined` values [click me](https://github.com/panva/node-oidc-provider/blob/0e918a7d5fdf8bfa5df305b1fea7faba41bb7629/lib/adapters/memory_adapter.js#L79).

Especially aggravating is the fact that I couldn't find any hints about `undefined` values beeing acceptable behaviour neither in the [general documentation](https://github.com/panva/node-oidc-provider/blob/master/docs/README.md#adapter) nor in the [adapter API documentation](https://github.com/panva/node-oidc-provider/blob/0e918a7d5fdf8bfa5df305b1fea7faba41bb7629/example/my_adapter.js#L229).

**Comment by panva** [comment]
> My error was caused by the library calling `adapter.revokeByGrantId()` with `undefined`.
> This happened whenever I logged in with user1, logged out and then logged in again with user2 (aka when a "_session" cookie was already present in my browser).

This is the most valuable part of your comment. It helped me find two bugs i'll be fixing with the next release.

For the future, please understand i can't "reproduce" stuff that is unique to your deployment such as keycloak, interactions, adapters. If the reproduction steps were useful, so would be my previous response to you.
