### ISSUE TITLE
Omit fields in /reg GET response

### ISSUE THREAD

**Issue by phmz** [panva/node-oidc-provider#629]
Currently the client_secret is returned when calling /reg with HTTP GET method. In a previous issue https://github.com/panva/node-oidc-provider/issues/104#issuecomment-301886002, it was said that it would be prefarable to omit the client_secret from the response but we did not find how to do it.

Is there an option we missed to omit certain fields from the response, and if not, is it possible to implement such feature ?

 - [x] I have searched the configuration section for this feature and couldn't find it
 - [x] I have searched the issues tracker on github for similar requests and couldn't find anything related.

**Comment by panva** [comment]
https://github.com/panva/node-oidc-provider/blob/v6.18.1/docs/README.md#pre--and-post-middlewares

Use an after/post middleware to hide the fields you don't want to return.

**Comment by phmz** [comment]
Thanks for your quick answer. It worked for me.

**Comment by panva** [comment]
> Thanks for your quick answer. It worked for me.

Glad i could help, please consider [supporting](https://github.com/panva/node-oidc-provider?sponsor=1) the library if it provides value to you or your company and this support was of help to you.
