### ISSUE TITLE
feature: Support relaxed client schema enforcement with debug or local_environement flag

### ISSUE THREAD

**Issue by debben** [panva/node-oidc-provider#63]
I've been using oidc-provider for some time now. After upgrading to the latest few releases I've noticed there's a much more strict enforcement of the [client_schema](https://github.com/panva/node-oidc-provider/blob/master/lib/helpers/client_schema.js#L436).

```
if (this.grant_types.indexOf('implicit') !== -1 && redirectUri.startsWith('http:')) {
              invalidate('redirect_uris for web clients using implicit flow MUST only register URLs using the https scheme');
            }
```

For my client app I have different urls for environments (mysite.com for production, test.mysite.com for testing, etc). I also keep a set of configurations for the different environments. My staging and production environments use https, but locally I do not. 

For a long time I had been using localhost when running my client project locally. I then switched to a hosts file entry (local.mysite.com). Initially this was an alias for localhost, but over time it became a local entry pointing to the IP of a local vagrant VM or docker container I was using for development.

When trying to just setup a local development environment and run a local instance of my OP and a local instance of my RP, oidc-provider complains because the config for the local client doesn't use https. For a time I got arround this by just deleting the code block above from node_modules/oidc-provider locally. This became an added local setup step though when sharing my code with other developers.

Would you be open to adding a configuration flag that relaxes the enforcement of some client_schema rules when turned on?

**Comment by panva** [comment]
I can see the reasoning, i myself have fallen victim to this. However, if it becomes a configurable flag, i'm pretty sure there will be developers who will either forget it or leave there intentionally, leaving their deployment susceptible to attacks. Especially with implicit flow over http, that's like asking to have user information sniffed :)

Is setting up nginx / caddy on your RP virtual environment not an option? With either self-signed or valid [free ssl certificates](https://letsencrypt.org/) being piss easy to get, i think it's the preferred way.

**Comment by debben** [comment]
I understand.

For a time I was configuring my local client as 'native' a temporary workaround. This got me past the need for https and since I was running the app with the name "localhost" it wasn't a problem. This didn't really become an issue for me till I changed to use a hosts file entry.

What might be best is to just close this issue and leave it here for posterity. If someone really wants to prefix that check with something like `process.env.NODE_ENV != 'local' &&`, they can fork the repository and just use that. That way they're explicitly taking the risks of leaving the flag on themselves.

**Comment by boehlke** [comment]
Hello @panva ,
I can understand your argument concerning security. Would you at least consider adding a client-wise https-required-flag which defaults to true? Keycloak has such a flag on realm-level.
I would make a PR for a changes!

Kind regards
André

**Comment by panva** [comment]
Hi @boehlke,

> Would you at least consider adding a client-wise https-required-flag which defaults to true? Keycloak has such a flag on realm-level.

I would not.

1) The only case where this is somewhat a nuisance is implicit and hybrid modes, which are being discouraged from being used for new client development anyway.
2) Client-level flag is from my POV an even worse idea then a an environment level one because it would allow clients to opt in
3) You can already [disable](https://github.com/panva/node-oidc-provider/blob/v5.5.5/test/configuration/clients.test.js#L84-L102) the redirectUri checks for development purposes with ease.

**Comment by panva** [comment]
https://github.com/panva/node-oidc-provider/blob/master/recipes/implicit_http_localhost.md
