### ISSUE TITLE
Logout problems with invalid id_token_hint

### ISSUE THREAD

**Issue by bob-sheknowdas** [panva/node-oidc-provider#630]
My oidc-provider issues access and id tokens, each valid for 1 hour.

If my app calls the "end session"-endpoint after that 1 hour expires, I get an error "post_logout_redirect_uri can only be used in combination with id_token_hint".

However, an id_token_hint is given as request param. It is just, that the given id token is expired...

Is that expected behaviour?

**Comment by panva** [comment]
@bob-sheknowdas if you're getting `post_logout_redirect_uri can only be used in combination with id_token_hint` then `id_token_hint` is for sure NOT part of the request.

The [code](https://github.com/panva/node-oidc-provider/blob/v6.18.1/lib/actions/end_session.js#L34-L66) speaks for itself.

**Comment by panva** [comment]
Please be diligent in your own investigation before opening issues and consider [supporting](https://github.com/panva/node-oidc-provider?sponsor=1) the library if you wish to continue getting answers to issues such as this one or the [previous](https://github.com/panva/node-oidc-provider/issues?utf8=%E2%9C%93&q=author%3Abob-sheknowdas) ones.
