### ISSUE TITLE
Support custom function to compare client secret

### ISSUE THREAD

**Issue by phmz** [panva/node-oidc-provider#631]
Currently oidc-provider does not allow to compare salted and hashed client secret. Same as https://github.com/panva/node-oidc-provider/issues/104, we would like to store the client_secret as a salted hash in our database. 
Because we are using an irreversible hashing function for our client secret we cannot use the adapter to decrypt the stored client secret.

We wrote the necessary code (https://github.com/phmz/node-oidc-provider/commit/5ca1e3feffec67f81fa3bf666a2349d013c1106e) to support a custom function to compare client secret. Is this something you would be interested in ? If so we can provide a PR. 

 - [x] I have searched the configuration section for this feature and couldn't find it
 - [x] I have searched the issues tracker on github for similar requests and couldn't find anything related.

**Comment by panva** [comment]
@phmz I definitely want to support the scheme where client secret is one-way hashed and/or encrypted.

But I don't necessarily think a function like this is a way to do it. For one, the description does not mention the fact that this locks the provider out of supporting a slew of other features, such as symmetric encryption or symmetric signatures.

Rather then going with a front and center configuration option, in this case i'd go with an exposed client prototype function that you're free to overload to plug in your behaviour. See 4d8bbe6 and provide feedback.

**Comment by phmz** [comment]
@panva Thanks for your feedback. 

I read your commit and I agree it is better to overload the prototype function.
The code you provided is working as expected. 

Do you think you'd be able to implement this feature for the next release?

**Comment by panva** [comment]
> Do you think you'd be able to implement this feature for the next release?

yup
