### ISSUE TITLE
interactionUrl not part of Typescript definition for provider

### ISSUE THREAD

**Issue by ajmas** [panva/node-oidc-provider#632]
**Describe the bug**

I am getting the following error when specifying 'interactionUrl' as a parameter to the Provider constructor, per the example:

> Argument of type '{ adapter: any; clients: { client_id: string; redirect_uris: string[]; response_types: "id_token"[]; grant_types: string[]; token_endpoint_auth_method: "none"; }[]; jwks: any; findAccount: (context: any, userId: any) => Promise<...>; claims: { ...; }; interactionUrl(ctx: any): string; features: { ...; }; }' is not assignable to parameter of type 'Configuration'.
  Object literal may only specify known properties, but 'interactionUrl' does not exist in type 'Configuration'. Did you mean to write 'interactions'?ts(2345)

**To Reproduce**

I am following the following example:

https://github.com/panva/node-oidc-provider-example/blob/master/03-oidc-views-accounts/index.js

where the code causing the issue is:

```js
const oidc = new Provider(`https://${process.env.HEROKU_APP_NAME}.herokuapp.com`, {
  adapter: RedisAdapter,
  clients: [
    {
      client_id: 'foo',
      redirect_uris: ['https://example.com'],
      response_types: ['id_token'],
      grant_types: ['implicit'],
      token_endpoint_auth_method: 'none',
    },
  ],
  jwks,

  // oidc-provider only looks up the accounts by their ID when it has to read the claims,
  // passing it our Account model method is sufficient, it should return a Promise that resolves
  // with an object with accountId property and a claims method.
  findAccount: Account.findAccount,

  // let's tell oidc-provider you also support the email scope, which will contain email and
  // email_verified claims
  claims: {
    openid: ['sub'],
    email: ['email', 'email_verified'],
  },

  // let's tell oidc-provider where our own interactions will be
  // setting a nested route is just good practice so that users
  // don't run into weird issues with multiple interactions open
  // at a time.
  interactionUrl(ctx) {
    return `/interaction/${ctx.oidc.uid}`;
  },
  features: {
    // disable the packaged interactions
    devInteractions: { enabled: false },

    introspection: { enabled: true },
    revocation: { enabled: true },
  },
});
```

Looking at the `oidc-provider/types/index.d.ts` I confirm that `interactionUrl` is not specified as an option. Looking at the latest code in this repo, I see that it is not an option that is defined there etiher.

**Expected behaviour**

Expect `interactionUrl` to be part of `index.d.ts` or example corrected, if this is no longer valid.

**Environment:**
 - oidc-provider version: 6.18.2
 - node version: 10.17.0
 - typescript version: 3.7.3

**Additional context**

 - This is a build time issue.
 - I have looked at the index.d.ts file

**Logs**

**Comment by panva** [comment]
This is an example issue, the types are correct. Thanks for raising it, i’ll review the example.
