### ISSUE TITLE
Little error in mongodb adapter example

### ISSUE THREAD

**Issue by joolfe** [panva/node-oidc-provider#634]
**Describe the bug**
I know is just an example (for documentation purpose) but i think there are a error in the mongodb adapter implementation here [mongodb.js](https://github.com/panva/node-oidc-provider/blob/master/example/adapters/mongodb.js), when choosing the index depending of the `name` as for example here:
```
const grantable = new Set([
  'access_token',
  'authorization_code',
  'refresh_token',
  'device_code',
]);
```
Is using snake_case for the model names but reading the comments in [my_adapter.js](https://github.com/panva/node-oidc-provider/blob/master/example/my_adapter.js) seems like models names are using PascalCase, so this should be something like:
```
const grantable = new Set([
  'AccessToken',
  'AuthorizationCode',
  'RefreshToken',
  'DeviceCode',
]);
```
Also for the rest of the name literals.

**Comment by panva** [comment]
@joolfe see https://github.com/panva/node-oidc-provider/blob/v6.18.2/example/adapters/mongodb.js#L49

**Comment by joolfe** [comment]
Ups sorry, i didn't see that line.
