### ISSUE TITLE
preventing duplicate client registration?

### ISSUE THREAD

**Issue by bvitale** [panva/node-oidc-provider#638]
With dynamic registration, is it typical to prevent the same `client_name` in two registrations? With no async permitted in `extraClientMetadata.validator`, I'm not seeing an easy way to do this, so I must be missing something? Thanks very much.

**Comment by panva** [comment]
@bvitale it isn't typical, the only uniqueness required from the generic AS perspective is the `client_id`.

I'd recommend to put this validation in your adapter. You can `throw new Provider.errors.InvalidClientMetadata('message')` right from your adapter store.
