### ISSUE TITLE
Question: retrieve user data

### ISSUE THREAD

**Issue by Eomm** [panva/node-oidc-provider#639]
Hi,
I would like to ask clarification about retrieving the user data.

I have customized the `interactions` behaviour and I'm using successfully the `oidc.interactionResult(request.raw, reply.res, result)` in a custom endpoint.

In the HTTP endpoint, I'm doing a query to a MongoDB to check if the user has enough permission, but then, in the `findAccount` function parameter, I must re-do the query to retrieve the user data (like name, surname.. etc..) to build the claims:

```
  async function findAccount (ctx, userId, token) {
    const user = await fastify.mongo.client.db(opts.mongo.db).collection('Users')
      .findOne({ _id: userId },
        {
          _id: 1,
          name: 1,
          surname: 1,
        })

    if (!user) {
      fastify.log.debug('Account %s NOT found', userId)
      // this should never happen
      return undefined
    }

    return {
      accountId: user._id,
      async claims (use, scope, claims, rejected) {
        return {
          sub: user._id,
          name: `${user.FirstName} ${user.LastName}`,
          given_name: user.name,
          family_name: user.surname
        }
      }
    }
  }
```

Is this double query necessary or I have misunderstood some steps?

Thank you

**Comment by panva** [comment]
Yes, any extra checks you do in your own interactions before resolving is "your land", the library needs the `findAccount` operation for many other operations.
