### ISSUE TITLE
404 on unmatched route

### ISSUE THREAD

**Issue by cguedes** [panva/node-oidc-provider#64]
Hi,

I'm using node-oidc-provider with success in a standalone server.
But when integrated into an express server I think I've found an issue related to the internal koa pipeline/behavior. 

The thing is that I have the requirement to serve content with a '*' route. To have this I need to configure your handler (`app.use(oidc.callback)`) before my wildcard route configuration. The issue is that your internal koa pipeline is returning 404 without letting the request pipeline to continue the execution.

Can you disable this behavior?

**Comment by panva** [comment]
Simply not mounting the catch-all of oidc-provider won't cut it, the moment koa starts handling the request it will get responded to.

You can get around this easy though, by mounting the callback to a path prefix like so.
```js
  expressApp.use('/op', oidc.callback);
  expressApp.use('*', yourCatchAll);
```

You don't even have to change your issuer identifier if (using express-urlrewrite) you do this:
```js
  expressApp.use(rewrite('/.well-known/*', '/op/.well-known/$1'));
  expressApp.use('/op', oidc.callback);
```

I have not accounted for this and so have a bugfix to do first, but afterwards you should be able to do this with no downside.

**Comment by cguedes** [comment]
@panva Thanks for the reply. 

I've already tried the solution with the base path.
But it fails with the `devInteractions: true`. The `/op/auth...` request returns a redirect to `/interaction/b553d605-c6c0-47a6-8a4b-...` but that way your handler won't be executed. Shouldn't this returned URL be also prefixed by the base path?

**Comment by panva** [comment]
I see, this [configuration](https://github.com/panva/node-oidc-provider/blob/master/lib/helpers/defaults.js#L293-L296) option would then be your way to tell the OP that your interactions (eventhough they're still the dev ones), are prefixed by /op.

**Comment by panva** [comment]
See the released fix https://github.com/panva/node-oidc-provider/compare/v1.8.0...v1.8.1

**Comment by cguedes** [comment]
You have forgotten the URLs used in the views

![image](https://cloud.githubusercontent.com/assets/174127/21870677/8212f212-d855-11e6-947a-d99af5958c72.png)

**Comment by panva** [comment]
Yeah, should have hold back on the bugfix until i am able to test them. https://github.com/panva/node-oidc-provider/compare/v1.8.0...v1.8.2 this should do now, *fingers crossed*
