### ISSUE TITLE
Missing fields in OAuth 2.0 Dynamic Client Registration Protocol RFC7591 

### ISSUE THREAD

**Issue by hadyrashwan** [panva/node-oidc-provider#641]
**Description**

I do not get jwks_uri after the registration is done in the response object. 
I do not know how to set `software_id` and `software_version` while registering.

**To Reproduce**

Use the following configurations https://github.com/badgewell/badge-connect-implementation/blob/master/apps/oauth/src/controllers/oauth.controller.ts for OAuth server configuration. 

I Use the following code to call it.
https://github.com/badgewell/badge-connect-implementation/blob/master/apps/client/src/controllers/register.controller.ts

**Expected behaviour**

Getting back the `jwks_uri` plus be able to send the `software_id` and `software_version`.

**Environment:**
 - oidc-provider version: 6.20
 - node version: 12.14.1

**Additional context**

 - [x] the bug is happening on latest oidc-provider too.
 - [x] i have tried DEBUG (see README) and can see the issue is with the provider and not my code.
 - [x] i have searched the issues tracker on github for similar issues and couldn't find anything related.
 - [x] i have searched the [FAQ](https://github.com/panva/node-oidc-provider/blob/master/docs/README.md#faq) and couldn't find anything related.

**Logs**
No error occurred

**Comment by panva** [comment]
Hi @hadyrashwan 

I cannot replicate the `jwks_uri` part, which is the only weird part in your report...

```sh
❯ curl -sX POST https://op.panva.cz/reg \
  -H 'content-type: application/json' \
  -d '{"redirect_uris":["https://rp.panva.me"], "jwks_uri":"https://foobar.example.com/jwks"}' | jq
{
  "application_type": "web",
  "grant_types": [
    "authorization_code"
  ],
  "id_token_signed_response_alg": "RS256",
  "post_logout_redirect_uris": [],
  "require_auth_time": false,
  "response_types": [
    "code"
  ],
  "subject_type": "public",
  "token_endpoint_auth_method": "client_secret_basic",
  "introspection_endpoint_auth_method": "client_secret_basic",
  "revocation_endpoint_auth_method": "client_secret_basic",
  "backchannel_logout_session_required": false,
  "frontchannel_logout_session_required": false,
  "request_uris": [],
  "authorization_signed_response_alg": "RS256",
  "tls_client_certificate_bound_access_tokens": false,
  "client_id_issued_at": 1580583774,
  "client_id": "_iy0lLmekOhRtxj2VqajX",
  "client_secret_expires_at": 0,
  "client_secret": "mJUtL6eDSVuMvlCI_hX2kbK7K9TwURndIJZPBQH_6wsVbmCvYuMQuJyadnOm36TPAAuXDL8ytbHvnuxI1iXMuA",
  "jwks_uri": "https://foobar.example.com/jwks",
  "redirect_uris": [
    "https://rp.panva.me"
  ],
  "registration_client_uri": "https://op.panva.cz/reg/_iy0lLmekOhRtxj2VqajX",
  "registration_access_token": "ueMFJPxlyIBLh1SuoKcnQq06mqlMBKpXP0E0ciyqHpO"
}
```

For `software_id` and `software_version` which requires some form of validation, and imo should be accompanied by a software statement, please use configuration option [`extraClientMetadata`](https://github.com/panva/node-oidc-provider/blob/v6.20.0/docs/README.md#extraclientmetadata) to have them recognized and define their validations.

Ad your register controller, i have no idea what is it that you're trying to achieve there...

**Comment by hadyrashwan** [comment]
Got it. I was confused cause I'm not familiar with the standard as callback in the OpenID library error said it was not provided by the issuer. I thought it should be provided by the host server not being sent by the RP when registering in the first place. Thanks for the help :)
