### ISSUE TITLE
Corss-client Introspection question

### ISSUE THREAD

**Issue by amaciver** [panva/node-oidc-provider#642]
**Describe the bug**
I have questions about the intended behavior when trying to introspect a token that was issued to Client A, using credentials from Client B for introspections.

My main question: When request hits the same issuer i can introspect Client A from Client B, is this intended? I see in the code (4.x-6.x) that it is only when 
```
if (ctx.oidc.client.introspectionEndpointAuthMethod === 'none') {
        if (token.clientId !== ctx.oidc.client.clientId) {
          return;
        }
      }
```
I am curious your thoughts about how this aligns with RFC 
```
   If the introspection call is properly authorized but the token is not
   active, does not exist on this server, or the protected resource is
   not allowed to introspect this particular token, then the
   authorization server MUST return an introspection response with the
   "active" field set to "false".
```

Would you be able to tell me if i am missing something?

I can see that when i use two different Instances of the Provider (two different issuers), Introspection is correctly prevented when making cross-issuer-cross-client calls, and also prevented when making cross-issuer-same-client calls. This is because the `verify` method on the tokens checks if the current issuer matches the token's issuer, so `token.find` is `undefined`. 

I just don't understand what should be expected for same-issuer-cross-client, and introspectionAuthMethod defaulting to the same as client (in my case basic auth).

Am I misunderstanding the RFC? Other web searches seem to indicate that cross-client should not be allowed.

**To Reproduce**

Steps to reproduce the behaviour:

1.  issue token to ClientA
2.  Introspect with clientB
3.  active: true

**Expected behaviour**
active:false

**Environment:**
 - oidc-provider version: 4.1.2, 5.5.5
 - node version: 10.x 12.x

**Additional context**

 - [(not sure)] the bug is happening on latest oidc-provider too.
 - [x] i have tried DEBUG (see README) and can see the issue is with the provider and not my code.
 - [x] i have searched the issues tracker on github for similar issues and couldn't find anything related.
 - [x] i have searched the [FAQ](https://github.com/panva/node-oidc-provider/blob/master/docs/README.md#faq) and couldn't find anything related.

**Logs**

**Comment by panva** [comment]
> is this intended?

Yes, public clients cannot introspect token's other than those issued to them. Resource Servers with a tight relationship with the AS can introspect tokens issued to other clients since they would otherwise not be able to. Since Client !== Resource Server.

This is the default behaviour and the moment you establish Resource Indicators and issue tokens to a client but with a RS audience you can use the post middleware option to overload this behaviour and only return success when the authenticated client is the audience of the token.

I also plan to revisit this in 7.x

**Comment by amaciver** [comment]
thanks!
