### ISSUE TITLE
The `interaction.started` event incorrectly emits a prompt object instead of an interaction

### ISSUE THREAD

**Issue by alvis** [panva/node-oidc-provider#643]
**Describe the bug**
The `interaction.started` event incorrectly emits a `prompt` object instead of an `interaction` stated in the documentation (or the doc incorrectly states the wrong object):
https://github.com/panva/node-oidc-provider/blob/e5ecd85c346761f1ac7a89b8bf174b873be09239/docs/events.md#L39
https://github.com/panva/node-oidc-provider/blob/e5ecd85c346761f1ac7a89b8bf174b873be09239/types/index.d.ts#L1279

However, in the code:
https://github.com/panva/node-oidc-provider/blob/e5ecd85c346761f1ac7a89b8bf174b873be09239/lib/actions/authorization/interactions.js#L138

**Additional context**

 - [x] the bug is happening on latest oidc-provider too.
 - [x] i have tried DEBUG (see README) and can see the issue is with the provider and not my code.
 - [x] i have searched the issues tracker on github for similar issues and couldn't find anything related.
 - [x] i have searched the [FAQ](https://github.com/panva/node-oidc-provider/blob/master/docs/README.md#faq) and couldn't find anything related.

**Comment by panva** [comment]
> or the doc incorrectly states the wrong object

i guess that's what needs to get fixed, docs and types. I'd rather have it be the interaction object but that would be a breaking runtime change.

**Comment by alvis** [comment]
I agree, also it makes more sense to emit a prompt than an interaction when it starts.
