### ISSUE TITLE
Memory usage increasing as Clients increases

### ISSUE THREAD

**Issue by Lakshman1996** [panva/node-oidc-provider#645]
Hello,

I have dynamic client registration enabled and clients are increasing every day. While debugging i found that client information is in memory. I am assuming because of this my app memory usage is increasing.  Is there any way to not cache this. ?
Thanks

**Comment by panva** [comment]
Client model instances are [capped](https://github.com/panva/node-oidc-provider/blob/v6.20.1/lib/models/client.js#L195) at 100 instances through an LRU cache mechanism.

**Comment by Lakshman1996** [comment]
Are you considering to make cache mechanism  configuration in future?

**Comment by panva** [comment]
I do not, with the client metadata validation and instantiation process being a rather heavy operation, cache is crucial.

**Comment by Lakshman1996** [comment]
Okay. Thanks for the info
