### ISSUE TITLE
Configuration generator issue with embedded multiline html

### ISSUE THREAD

**Issue by big-kahuna-burger** [panva/node-oidc-provider#649]
**Describe the bug**
docs/README.md have a trimmed version of HTML for frontchannelLogout.logoutPendingSource function due to error in update-configuration.js

**To Reproduce**
<img width="870" alt="Screen Shot 2020-02-17 at 9 25 09 AM" src="https://user-images.githubusercontent.com/11753867/74636021-74b93e80-5167-11ea-864b-dd5fce5d3d66.png">

Steps to reproduce the behaviour:

**Expected behaviour**
Default value without shouldChange fn 

**Environment:**
 - oidc-provider version: latest
 - node version: N/A

**Additional context**

 - [x] the bug is happening on latest oidc-provider too.
 - [x] i have tried DEBUG (see README) and can see the issue is with the provider and not my code.
 - [x] i have searched the issues tracker on github for similar issues and couldn't find anything related.
 - [x] i have searched the [FAQ](https://github.com/panva/node-oidc-provider/blob/master/docs/README.md#faq) and couldn't find anything related.

**Logs**
N/A

**Comment by panva** [comment]
fixed https://github.com/panva/node-oidc-provider/commit/8a14919f3311654c6370205aad9235f951436d5a?w=1

Thank you @big-kahuna-burger
