### ISSUE TITLE
question: Is there any way to force access token expiration?

### ISSUE THREAD

**Issue by pinkinsect** [panva/node-oidc-provider#65]
Such as title, please help. Thanks a lot!!!

**Comment by panva** [comment]
Yes absolutely, several.

1) OAuth2.0 Revocation
2) dropping it from your storage (id is the first 48 characters of the tokenValue);
3) 
```js
provider.AccessToken.find(tokenValue).then((token) => {
  if (token) return token.destroy();
}).catch(console.error);
```
