### ISSUE TITLE
SessionNotFound because oidc-provider compares objects, not strings

### ISSUE THREAD

**Issue by kareha** [panva/node-oidc-provider#650]
**Describe the bug**
Ran into SessionNotFound error because accountIds couldn't be compared in
Line: https://github.com/panva/node-oidc-provider/blob/master/lib/provider.js#L62

**To Reproduce**
I used mongoose as mongodb models
Same setup like your mongodb-Adapter example.

Steps to reproduce the behaviour:

Added following output to Line 62 (before compare):
```
    console.log('typeof interaction.session.accountId:', typeof interaction.session.accountId)
    console.log('interaction.session.accountId:', interaction.session.accountId)
    console.log('typeof session.accountId():', typeof session.accountId())
    console.log('session.accountId():', session.accountId())
```

Got output:
```
typeof interaction.session.accountId: object
interaction.session.accountId: 5e45750816e05978f3333f03
typeof session.accountId(): object
session.accountId(): 5e45750816e05978f3333f03
```

Recommendation: (?)

Change provider.js Line 62 to:
`if (interaction.session.accountId.toString() !== session.accountId().toString()) {
`
(At least this solved my problem)

Is it possible to implement that? Or is there a better solution?
Or did I do something wrong?

 - [ ] the bug is happening on latest oidc-provider too.
 - [ ] i have tried DEBUG (see README) and can see the issue is with the provider and not my code.
 - [x] i have searched the issues tracker on github for similar issues and couldn't find anything related.
 - [x] i have searched the [FAQ](https://github.com/panva/node-oidc-provider/blob/master/docs/README.md#faq) and couldn't find anything related.

**Comment by panva** [comment]
> Is it possible to implement that?

No, because it's not needed.

> Or did I do something wrong?

Have you considered that the fact that your account is set to an object and not a string is the actual problem?

It's meant to be a string in the first place. Don't pass in mongoose/mongo ObjectId objects.

**Comment by kareha** [comment]
The problem was, I just defined the session Schema with `payload: {type: Object}`, because of flexibility to your library.
But then all ID Strings are stored as ObjectID.

Thanks for the hint. It works now, by defining a specific Schema.
And sorry for the stupid question :)
