### ISSUE TITLE
JWKS and Cookie Key Rotation

### ISSUE THREAD

**Issue by solaris765** [panva/node-oidc-provider#651]
Background:
I'm currently running an oidc-provider based auth system in a kubernetes cluster.  One of the features that I'm currently exploring is automatic secret rotation. 

Ex: when a secret is mounted as a file, the file is automatically updated in a running pod some time after the secret is updated in the cluster.

I know your docs list restarting the service as best practice. My concerns are:
* Providing a service worker with rights to restart services
* Letting my auth system restart itself (enabling accidental simultaneous downtime for running services)

Questions:
  * Would replacing the `provider.keys` or `provider.app.keys` properties during runtime have any unforeseen issues?
  * Is there a way to rotate the JWKS Object during runtime?

I figure If I can rotate keys while the server is running I can reduce unnecessary reboots. But any insight here would be much appreciated.

Thanks

**Comment by panva** [comment]
> Is there a way to rotate the JWKS Object during runtime?

No

> Would replacing the provider.keys or provider.app.keys properties during runtime have any unforeseen issues?

I don't know and since it's not the intended mode of operation, i can't recommend it.

> I know your docs list restarting the service as best practice.

It is, any distributed system should be capable of having a rolling restart triggered.
