### ISSUE TITLE
Interface to manage current sessions/tokens

### ISSUE THREAD

**Issue by rickwang7712** [panva/node-oidc-provider#652]
**Is your feature request related to a problem? Please describe.**

May I ask is there a management interface to handle actions like `delete all authenticated sessions of a specific user`? For example, I will need to revoke user's existing sessions/tokens after the user change password.

**Describe the solution you'd like**

An API or any method to revoke user's related authentication/consent sessions.

Thanks!

**Comment by panva** [comment]
There isn’t and won’t be, its out of scope for a protocol implementation. You control the adapter layer, build you API on top of it.
