### ISSUE TITLE
SessionNotFound: invalid_request - External login page

### ISSUE THREAD

**Issue by totolef** [panva/node-oidc-provider#654]
Hi, I know it might be more a problem on my side than a bug. I'm seeking help if it is possible here.

**Describe the bug**
/interaction/:uid/login step return SessionNotFound error.

My authentication process is the following : 
User goes on localhost:3006/login, on an express server using oidc passport strategy with the following configuration : 
```
{
            issuer: "http://localhost:3000",
            authorizationURL: "http://localhost:3000/auth",
            tokenURL: "http://localhost:3000/token",
            userInfoURL: "http://localhost:3000/me",
            clientID: "uRSzY-UU4JnNMEidlUcY4",
            clientSecret:
                "xRw8tbRpJ1GNiSXyjUCQb6tYI88zbMhEzWr8FkoGIQEZ6AXW3eVJfH_KTqUne9GRX3dqQcXGqA6WOs2S72LVYw",
            callbackURL: "http://localhost:3006/authorization-code/callback",
            scope: "openid"
},
```
It redirect user to http://localhost:3000/interaction/:uid, the express server with oidc-provider. I redirect him to http://localhost:3001/auth/login/:uid, a React server where their is the login form
```
case "login": {
                    return res.redirect(
                        "http://localhost:3001/auth/login/" + uid
                    );
}
```
I have a form on this page that send login form data to ttp://localhost:3000/interaction/:uid/login : 
```
<form
                                action={
                                    "http://localhost:3000/interaction/" +
                                    match.params.id +
                                    "/login"
                                }
                                method="post"
                            >
```
When the form is sent, I get the bug described at the beginning.
I never see the session cookie when looking on the Chrome Dev Tools.

I think it comes from the change of domain at every step, but don't know how to fix this.

**Logs**
SessionNotFound: invalid_request
    at Provider.getInteraction (/core-server/node_modules/oidc-provider/lib/provider.js:50:11)
    at Provider.interactionResult (/core-server/node_modules/oidc-provider/lib/provider.js:192:46)
    at Provider.interactionFinished (/core-server/node_modules/oidc-provider/lib/provider.js:210:33)
    at app.post (/core-server/routes/opid/index.js:137:32)
    at process._tickCallback (internal/process/next_tick.js:68:7)

**OIDC-Provider Config**

```
{
    clients: [],
    interactions: {
        policy: interactions,
        url(ctx, interaction) {
            // eslint-disable-line no-unused-vars
            return `/interaction/${ctx.oidc.uid}`;
        }
    },
    findAccount: findUser,
    formats: {
        AccessToken: "jwt"
    },
    cookies: {
        long: { signed: true, maxAge: 1 * 24 * 60 * 60 * 1000 }, // 1 day in ms
        short: { signed: true },
        keys: [
            "some secret key",
            "and also the old rotated away some time ago",
            "and one more"
        ]
    },
    claims: {
        openid: ["sub"],
        username: ["username"],
        firstname: ["firstname"],
        lastname: ["lastname"]
    },
    features: {
        devInteractions: { enabled: false },
        deviceFlow: { enabled: true },
        encryption: { enabled: true },
        introspection: { enabled: true },
        revocation: { enabled: true },
        sessionManagement: true,
        registration: {
            enabled: true,
            initialAccessToken: "****"
        },
        registrationManagement: {
            enabled: true
        }
    },
    jwks,
    ttl: {
        AccessToken: 1 * 60 * 60, // 1 hour in seconds
        AuthorizationCode: 10 * 60, // 10 minutes in seconds
        IdToken: 1 * 60 * 60, // 1 hour in seconds
        DeviceCode: 10 * 60, // 10 minutes in seconds
        RefreshToken: 1 * 24 * 60 * 60 // 1 day in seconds
    }
```

**Comment by panva** [comment]
Because `http://localhost:3001` is a different origin from `http://localhost:3000` and the cookies are set to `sameSite=lax`, a POST from 3001 to 3000 will not contain the cookies needed.
