### ISSUE TITLE
OIDC-provider prevents mongodb.ObjectId to be an accountId.

### ISSUE THREAD

**Issue by jim-king-2000** [panva/node-oidc-provider#655]
**Describe the bug**

If we use the default _id field from mongodb as accountId, oidc-provider would fail quietly.

```javascript
    const user = await mongodb.find(...);
    const result = {
      select_account: {},
      login: {
        account: user._id,  // Here, _id is mongodb.ObjectId type.
      },
    };

    return provider.interactionFinished(ctx.req, ctx.res, result, {
      mergeWithLastSubmission: false,
    });
```

Then, oidc-provider does not work. Function `provider.interactionDetails` returns 400 and the browser shows "Bad Request". But it works if we switch back to memory adapter.

**Analysis**

After a long time debugging, we locate './lib/provider.js' line 62.

```javascript
if (interaction.session.accountId !== session.accountId()) {
  throw new SessionNotFound('session principal changed');
}
```

OIDC-provider uses `!==` to compare accountId. But we pass an object of ObjectId type which can't be compared by `!==` (It uses `ObjectId.equals()`.). So, the comparison fails even with the same two accountIds.

**Root cause and suggestions**

It's actually **NOT** a bug of OIDC-provider. I post it here for saving other people's time from debugging. The following suggestions could be something beneficial.

1. Throwing `SessionNotFound` exception could show us some information. It can be showed either on browser console or DEBUG trace log. Then we could locate the issue very quickly.
2. OIDC-provider could complain when accountId is an object by a warning or something else.
3. The comparison (./lib/provider.js line 62) could accommodate ObjectId. If `accountId.equals()` exists, it is used for the comparison. If not, use `!==`.

**Environment:**
 - oidc-provider version: [e.g. v6.21.0]
 - node version: [e.g. v13.9.0]

**Additional context**

 - [x] the bug is happening on latest oidc-provider too.
 - [x] i have tried DEBUG (see README) and can see the issue is with the provider and not my code.
 - [ ] i have searched the issues tracker on github for similar issues and couldn't find anything related.
 - [ ] i have searched the [FAQ](https://github.com/panva/node-oidc-provider/blob/master/docs/README.md#faq) and couldn't find anything related.

**Comment by panva** [comment]
same as in #650

> I post it here for saving other people's time from debugging.

🙇 thank you, this is really great

> OIDC-provider could complain when accountId is an object by a warning or something else

I think this is what i'll put in, if its not a string it'll just throw at you when you call `interactionFinished` or similar.
