### ISSUE TITLE
Trusting TLS offloading proxies : Apache configuration

### ISSUE THREAD

**Issue by kaboume** [panva/node-oidc-provider#656]
Hi,
For those who use Apache as Reverse Proxy, here is the configuration to do for TLS offloading:

ProxyRequests off
ProxyPreserveHost On
RequestHeader set X-Forwarded-Proto https
ProxyPass  / http://localhost:9001/
ProxyPassReverse  / http://localhost:9001/

**Comment by panva** [comment]
I think this might not be 100% correct, setting the proto always to https is only okay if your server listens only on 443. The proto should be set to an evaluated expression by apache e.g `REQUEST_SCHEME` from https://httpd.apache.org/docs/trunk/mod/mod_rewrite.html
