### ISSUE TITLE
Question: Is there any sample code of dynamic client registration?

### ISSUE THREAD

**Issue by jim-king-2000** [panva/node-oidc-provider#657]
# requirement

We need to list all the existing clients of the provider, and need to do CRUD to a specific client.

# investigations we did

1. We see this in the document of oidc-provider, then we know it is feasible. But we can't find the sample code.

> A feature-rich example configuration of oidc-provider is available for you to experiment with here. Dynamic Client Registration is open, you can literally register any client you want there. An example client using this provider is available here (uses openid-client).

2. We find `features.registration` and `features.registrationManagement` in the doc. So we open both of them in our server code, since we are not sure which one should be employed.

```javascript
  ...
  features: {
    devInteractions: { enabled: false }, // defaults to true
    deviceFlow: { enabled: true }, // defaults to false
    introspection: { enabled: true }, // defaults to false
    revocation: { enabled: true }, // defaults to false
    registration: { enabled: true },
    registrationManagement: { enabled: true },
  },
  ...
```

3. We find `Client.fromUri(registrationClientUri, registrationAccessToken[, jwks])` in the document of openid-client. But we are not sure how to prepare the two arguments. So we try the client code like the following.

```javascript
import OidcClient from 'openid-client';

const issuer = await OidcClient.Issuer.discover(
  'http://localhost:7000/.well-known/openid-configuration'
);
const client = await issuer.Client.fromUri(issuer.metadata.registration_endpoint);
```

Then we get an error:
```
  Rejected promise returned by test. Reason:

  OPError {
    error: 'invalid_request',
    error_description: 'unrecognized route or not allowed method (GET on /reg)',
  }
```

# questions

1. Is there any code sample for dynamic client registration (list, CRUD)? The client-side one is OK.
2. Is my server configuration OK? Are there any more mandatory properties.
3. What did we miss in the client-side code? How to list the existing clients?

**Comment by panva** [comment]
Hi @jim-king-2000 

[`features.registration`](https://github.com/panva/node-oidc-provider/blob/v6.21.0/docs/README.md#featuresregistration) opens up the POST to `registration_endpoint` and GET to the dynamically registered client's `registration_client_uri` from [Dynamic Client Registration 1.0](https://openid.net/specs/openid-connect-registration-1_0.html)

[`features.registrationManagement`](https://github.com/panva/node-oidc-provider/blob/v6.21.0/docs/README.md#featuresregistrationmanagement) can't be enabled on its own, it requires that `features.registration` is also enabled and it enables the Update (PUT) and Delete (DELETE) operations from [OAuth 2.0 Dynamic Client Registration Management Protocol](https://tools.ietf.org/html/rfc7592) on the dynamically registered client's `registration_client_uri`

To dynamically register a client you can use [`issuer.Client.register`](https://github.com/panva/node-openid-client/blob/v3.13.0/docs/README.md#clientregistermetadata-other) in openid-client, this will do the POST to `registration_endpoint` and give you back a client with metadata that includes the `registration_client_uri` and `registration_access_token`.

To read a client configuration you would use [`issuer.Client.fromUri`](https://github.com/panva/node-openid-client/blob/v3.13.0/docs/README.md#clientfromuriregistrationclienturi-registrationaccesstoken-jwks) with the uri and token you got from registration.

To update and delete a client registration there's no implementation for in openid-client but you can see how it can be done in https://github.com/panva/openid-client-cli

There isn't and won't be an API for just listing all clients. But the dynamically registered ones that you have uris and tokens for you can manage.

None of this is possible for clients that are declared using the static `clients` configuration or ones that you just stored in the DB and they're just retrieved by an adapter. The one's created using the `registration_endpoint` have a corresponding `RegistrationAccessToken` entry in your DB.

None of this is proprietary and the specifications that are implemented are linked.

Please consider [supporting](https://github.com/panva/node-oidc-provider?sponsor=1) the library if it provides value to you or your company and this and the previous support was of help to you. Supporting the library means, amongst other things, that such support will be available in the future.
