### ISSUE TITLE
typescript: KoaContextWithOIDC is not correctly defined

### ISSUE THREAD

**Issue by alvis** [panva/node-oidc-provider#659]
In oidc-provider, an OIDCContext is assigned at `ctx.oidc`. However, it's incorrectly defined in the typescript definition due to the type parameter mispositioned in `ParameterizedContext`.

The correct definition of `KoaContextWithOIDC` should be
```ts
export type KoaContextWithOIDC = Koa.ParameterizedContext<{}, {oidc: OIDCContext}>;
```

instead of the one we have today below

https://github.com/panva/node-oidc-provider/blob/71a4a7df23873ef1f6457c3c843c1ff68370bce8/types/index.d.ts#L704

See the definition of `ParameterizedContext`,

https://github.com/DefinitelyTyped/DefinitelyTyped/blob/a0d47c0ec44c174267c4f3f85ade76ef91355a62/types/koa/index.d.ts#L704-L706

```ts
type ParameterizedContext<StateT = any, CustomT = {}> = ExtendableContext & {
        state: StateT;
    } & CustomT;
```

Currently, the type definition suggests `ctx.state.oidc` which is wrong.

**Comment by panva** [comment]
@alvis thank you and can you propose a PR?

**Comment by alvis** [comment]
sure. I'll do it later. ;)
