### ISSUE TITLE
Logging out

### ISSUE THREAD

**Issue by ToniIltanen** [panva/node-oidc-provider#66]
Question about session ending.

id_token, is it mandatory? what i understand, the id_token should be provided to end session endpoint as a id_token_hint. Mut this brings up an issue, i dont have it. I am using a normal passport js strategy for handling the auth, and it returns the deserialized profile, i dont have access to the actual id_token anywhere. So i have the whole user as an object, but what it seems, you must provide the token, otherwise you will just log automatically in after relogin. Passport js is so popular, that i would assume there is a way for this, or oidc logout can be done without the id_token.

in the OpenID Connect docs (http://openid.net/specs/openid-connect-session-1_0.html#RPLogout), it says:

> id_token_hint
> RECOMMENDED. Previously issued ID Token passed to the logout endpoint as a hint about the End-User's current authenticated session with the Client. This is used as an indication of the identity of the End-User that the RP is requesting be logged out by the OP. The OP need not be listed as an audience of the ID Token when it is used as an id_token_hint value.

so, it seems its recommended, not mandatory. But i just dont know how to logout without it :(

**Comment by panva** [comment]
With passport being so popular is there no generic openid connect strategy that would return you the ID Token?

ID Token is very essential part of the specification so my immediate reaction would be that you should aim to adapt your RP to get access to it. It is afterall RECOMMENDED.

> 3. SHOULD   This word, or the adjective "RECOMMENDED", mean that there
   may exist valid reasons in particular circumstances to ignore a
   particular item, but the full implications must be understood and
   carefully weighed before choosing a different course.

The specifics of this implementation sadly mean that when no id_token_hint is provided the post_logout_redirect_uris of the client cannot be loaded (since client load is based on the token). You will not be able to redirect the user back to your portal without it.

What's your take on this?

**Comment by ToniIltanen** [comment]
if i pass only the 'post_logout_redirect_uri', as in http://localhost:3000/op/session/end?post_logout_redirect_uri=http://127.0.0.1:8080, and click the log out only from this application, i get a redirect to http://localhost:3000/op/session/end?loggedOut=true, not to the redirect uri. IF i click the logout from everywhere, i get an error back

    "error": "server_error",
    "error_description": "oops something went wrong"

in the logs the following lines are added:

authorization code not found
authorization code is expired
authorization code already consumed
authorization code client mismatch
authorization code redirect_uri mismatch
authorization code invalid (referenced account not found)

about passport.js, it does not return the token_id, it returns the actual user. 
The mechanism for passport strategy's are always the same - load up a strategy depending on what auth you are going to use, and it returns the deserialized user to the client. So in my case, i use passport-openidconnect strategy, which handles the whole auth, and returns the user profile back after authentication. logout only removes the session stuff relating to passport, but in openid connect, there still is the session in the provider. this causes the problem, i cannot truly logout without the id_token, if user log's out, another one cannot login from the same browser. the new user is automatically logged in as the previous, because the provider has the existing session.

**Comment by panva** [comment]
> if i pass only the 'post_logout_redirect_uri', as in http://localhost:3000/op/session/end?post_logout_redirect_uri=http://127.0.0.1:8080, and click the log out only from this application, i get a redirect to http://localhost:3000/op/session/end?loggedOut=true, not to the redirect uri.

Your provided `post_logout_redirect_uri` will never be acknowledged by this implementation without `id_token_hint` being provided with it. It is simply a limitation of this specific implementation not being aware of all clients at all times as they may be loaded from an adapter. The source shows that pretty clear. 

https://github.com/panva/node-oidc-provider/blob/master/lib/helpers/defaults.js#L214-L244 will let you change the source and fallback url used for logout requests without verified `post_logout_redirect_uri`.


> logout only removes the session stuff relating to passport, but in openid connect, there still is the session in the provider. this causes the problem, i cannot truly logout without the id_token, if user log's out, another one cannot login from the same browser. the new user is automatically logged in as the previous, because the provider has the existing session.

This behavior is not specific to OIDC or this implementation but every single SSO protocol and provider, your local session logout does not affect the OP session.  
[Core 1.0](http://openid.net/specs/openid-connect-core-1_0.html) defines several mechanism that allow you to make sure a login screen is rendered by an OP, parameters max_age and prompt being few of them.


> IF i click the logout from everywhere, i get an error back

I will look into the server error, it should not occur, it will not however solve your request, see the above points.

> about passport.js, it does not return the token_id, it returns the actual user. The mechanism for passport strategy's are always the same - load up a strategy depending on what auth you are going to use, and it returns the deserialized user to the client. So in my case, i use passport-openidconnect strategy, which handles the whole auth, and returns the user profile back after authentication.

passport-openidconnect has not been released for four years and i'm pretty sure there are forks out there that return the id token with the user profile.

**Comment by ToniIltanen** [comment]
i use the one from https://github.com/jaredhanson/passport-openidconnect, which is updated 3 months ago. It's just the npm package which has not been updated for a long time. I tried the forks also, but none of them returned anything outside the user profile. 

It seems OpenID Connect is rather rare in the passport.js. I do have the original access_token available from the first callback, can i use it to get the id_token again?

**Comment by panva** [comment]
There's no such a mechanism in OIDC that doesn't involve a new authentication request. You may receive a new id token from the refresh_token grant that is up to each OP to decide on.

Looking at passport-openidconnect master branch i think you can easily get all params (including id_token) returned from the token endpoint.

1. [here](https://github.com/jaredhanson/passport-openidconnect/blob/master/lib/strategy.js#L92) params are passed from the token endpoint response
2. [here](https://github.com/jaredhanson/passport-openidconnect/blob/master/lib/strategy.js#L220-L245) they are being passed back to your callback you specify during instantiating the strategy

**Comment by ToniIltanen** [comment]
Ahh, i just assumed the callback came from passport.js, not the strategy. i got this fixed, thank you!

**Comment by ToniIltanen** [comment]
Error came from end_session.js. When no state was provided for the end_session endpoint, provider would crash on ln 131
```
          // get all cookies matching _state.[clientId](.sig) and drop them
          this.get('cookie').match(STATES).forEach(val => this.cookies.set(val.slice(0, -1), null,
          cookieOpts));
```
If the only parameters were id_token_hint and redirect url, this line will cause a crash (forEach loop on undefined)

**Comment by panva** [comment]
Yeah nut it's not the latest version, is it?

**Comment by mshwery** [comment]
>logout only removes the session stuff relating to passport, but in openid connect, there still is the session in the provider. this causes the problem, i cannot truly logout without the id_token, if user log's out, another one cannot login from the same browser. the new user is automatically logged in as the previous, because the provider has the existing session.

I too am curious about this, as I attempt to coordinate a "single log out" by ending the session at the OP.

Per [OpenID Connect Session draft :: RP-Initiated Logout](http://openid.net/specs/openid-connect-session-1_0.html#RPLogout) it makes sense that we wouldn't want to enable RPs the ability to logout the OP – however, I think it makes sense to provide a mechanism (exposed endpoint?) to directly logout of the OP – especially if the RPs are controlled by the same entity as the OP.

I'm thinking something akin to Google's "Sign out" which goes directly to their accounts service, regardless of which Google product you are using – `https://accounts.google.com/Logout?hl=en&continue=https://inbox.google.com/u/0/&timeStmp=1488323021&secTok=[redacted]`

Perhaps what I'm after isn't OpenID Connect Session Management at all? Maybe I should handle session for authenticated users in the OP separately?

I think the language and intention is a bit unclear in the spec, but perhaps that's just me.

Since you've obviously spent a lot of time with the spec and understand what mechanics are exposed – what are your thoughts about this?

**Comment by panva** [comment]
@mshwery 
> Perhaps what I'm after isn't OpenID Connect Session Management at all?
Sounds about right, you're looking to implement your own behaviour, one outside the scope of the specifications.

All openid-provider can do for you is, similar to #84, give you a chance to trigger this forced logout behaviour when end-user chooses to logout at the OP too and the provider instance emits `end_session.success`.
