### ISSUE TITLE
Question: Second factor authentication

### ISSUE THREAD

**Issue by kareha** [panva/node-oidc-provider#661]
Hi,
where would I ideally place a two factor authentication?

Could the interaction policy be a place for that, like a consent?
Or better place this at the routes and return an error at provider.interactionFinished() after POST login with the request? How to add more variables to the session for that?

I tried it by policy, but then the session is created anyway and the user is logged in :/
Hope you can give me a hint. How and where would you implement something like that?
Thx!

**Comment by panva** [comment]
@kareha your own interactions, ideally you don't resolve "login" before MFA is resolved when MFA is required after credential authentication. And policies if you want to be able to step-up authenticate on demand.
