### ISSUE TITLE
post_logout_redirect_uris loopback listener support for native applications

### ISSUE THREAD

**Issue by 625dennis** [panva/node-oidc-provider#663]
**Is your feature request related to a problem? Please describe.**
A clear and concise description of what the problem is.

When setting redirect_uris, I can use any localhost uri for application_type="native". This isn't true for post_logout_redirect_uris. I was wondering if this should be included or if maybe my flow is designed wrong.

**Describe the solution you'd like**

Allow loopbacks for post_logout_redirect_uris.

**Describe alternatives you've considered**

**Additional context**

 - [X] i have searched the configuration section for this feature and couldn't find it
 - [X] i have searched the issues tracker on github for similar requests and couldn't find anything related.

**Comment by panva** [comment]
`post_logout_redirect_uris` is validated to be a valid [`URL`](https://developer.mozilla.org/en-US/docs/Web/API/URL). That means loopbacks are allowed too because the hostname is not evaluated...

**Comment by 625dennis** [comment]
It requires a static port though.
`postLogoutRedirectUriAllowed(uri) {
      return this.postLogoutRedirectUris.includes(uri);
    }`

This is in contrast with `redirectUriAllowed(value)` which removes the port during evaluation.

**Comment by panva** [comment]
I fear you didn’t mention anything about the dynamic port part. I see. 

If you want this behaviour feel free to overload the client method in question. Its public API.

**Comment by 625dennis** [comment]
@panva I'm not sure how to configure the public api for client. I tried changing the client object in the new Provider() call, but that seems to get stripped out. Also, I don't think we have access to the Client prototype. Can you guide me to some documentation on this?

**Comment by 625dennis** [comment]
I found extraClientMetadata. I'll look into this for now

**Comment by 625dennis** [comment]
Found this https://github.com/panva/node-oidc-provider/issues/423#issuecomment-450750364

**Comment by panva** [comment]
its basic javascript really

```js
provider.Client.prototype.postLogoutRedirectUriAllowed = function customPostLogoutRedirectUriAllowed(uri) {
  return false;
};
```
