### ISSUE TITLE
Typescript implementation does not support directly using JWKS from jwks.json file

### ISSUE THREAD

**Issue by ionizer** [panva/node-oidc-provider#666]
**Describe the bug**
I tried to make an example to run this library with Typescript, but I'm getting this typing error if I try to use a JWKS file (jwks.json) like in the step-by-step example and use `tsc` to build.

```
Type '{ "keys": { "e": string; "n": string; "kty": string; "kid": string; }[]; }' is not assignable to type 'JSONWebKeySet'.
  Types of property 'keys' are incompatible.
    Type '{ "e": string; "n": string; "kty": string; "kid": string; }[]' is not assignable to type 'JSONWebKey[]'.
      Type '{ "e": string; "n": string; "kty": string; "kid": string; }' is not assignable to type 'JSONWebKey'.
        Type '{ "e": string; "n": string; "kty": string; "kid": string; }' is not assignable to type 'JWKRSAKey'.
          Types of property 'kty' are incompatible.
            Type 'string' is not assignable to type '"RSA"'.ts(2322)
index.d.ts(1024, 3): The expected type comes from property 'jwks' which is declared here on type 'Configuration'
```

**To Reproduce**
Provider and Client configuration: (inline or gist)
```js
import jwks from './jwks.json';
// provider configuration
const config: Configuration = {
  //...Other configs
  jwks, //Gives error: Type 'string' is not assignable to type '"RSA"'
}
// keystore(s) - if they affect the behaviour
//File: jwks.json
{
  "keys": [
    {
      "e": "AQAB",
      "n": "kWp2zRA23Z3vTL4uoe8kTFptxBVFunIoP4t_8TDYJrOb7D1iZNDXVeEsYKp6ppmrTZDAgd-cNOTKLd4M39WJc5FN0maTAVKJc7NxklDeKc4dMe1BGvTZNG4MpWBo-taKULlYUu0ltYJuLzOjIrTHfarucrGoRWqM0sl3z2-fv9k",
      "kty": "RSA",
      "kid": "1"
    }
  ]
}
```

Steps to reproduce the behaviour:

1.  Create a jwks.json file containing a JWK like the above code
2.  Import it where OIDC Provider configuration is contained (say, `import jwks from './jwks.json';`)
3.  Use the import in the config
4.  Try building the project

**Expected behaviour**
It should not throw type error

**Environment:**
 - oidc-provider version: v6.23.0
 - node version: v12.13.0
 - typescript version: 3.6.4

I feel a quick solution to this is to just move `kty` to `KeyParameter` interface and set it to string instead, but I realize this is likely going to break validation (and auto-complete on IDEs) on the possible `kty` values. I'm no expert Typescript developer unfortunately, so I can't say for sure what would be a proper solution...

**Comment by panva** [comment]
@alvis ideas?

```ts
import { Configuration } from 'oidc-provider'
import { JSONWebKeySet } from 'jose'

{
  const jwks = {
    keys: [{
      kty: 'RSA',
      e: '...',
      n: '...',
      d: '...',
    }],
  }

  const works: Configuration = {
    jwks: {
      keys: [{
        kty: 'RSA',
        e: '...',
        n: '...',
        d: '...',
      }],
    }
  }

  const fails: Configuration = {
    jwks: jwks
  }

  const failsToo: JSONWebKeySet = jwks;
}
```

**Comment by fiznool** [comment]
The issue is that since `jwks` is an object, there is nothing to stop the following from happening:

``` js
jwks.keys[0].kty = 'foo';
```

TS is therefore falling back to assumming that the `kty` field should be a string, rather than anything stricter. For that, you'd need an explicit type:

``` ts
  const jwks: JSONWebKeySet = {
    keys: [{
      kty: 'RSA',
      // etc
    }],
  }
```

Sadly this doesn't help the case where you are importing from a JSON file. I don't think there's much else you can do here, since by nature the JSON file doesn't support type annotations, hence an explicit cast would be necessary.

``` ts
const noLongerFails: Configuration = {
  jwks: jwks as JSONWebKeySet
}
```

**Comment by panva** [comment]
Thank you.

**Comment by ionizer** [comment]
This does mean I have to install the `jose` package (`npm i -S jose`) just to have the type though...

**Comment by panva** [comment]
> Does this mean I have to install the `jose` package (`npm i -S jose`) just to have the type though?

FWIW it's already installed, `oidc-provider` depends on it.

**Comment by ionizer** [comment]
Some ESLint rules seems to be not very happy about this apparently. It gives me the following error if I don't specify `jose` in my package.json and install it.
```
'jose' should be listed in the project's dependencies. Run 'npm i -S jose' to add it
eslint(import/no-extraneous-dependencies)
```

Though, I can probably get away with just disabling the rule specifically for my type import. Thanks a lot for the help!
