### ISSUE TITLE
Migrating to 6.x: keeping old tokens active?

### ISSUE THREAD

**Issue by wilsonjackson** [panva/node-oidc-provider#667]
**Is your feature request related to a problem? Please describe.**
Not sure that "feature request" is exactly the right descriptor here, but it's definitely not a bug. I'm in the process of upgrading an app based on oidc-provider up to 6.x and we want to avoid, if at all possible, invalidating every user's tokens when we release.

We use postgres for the backend, with an account provider based on your old sequelize example. The upgraded provider is up and running, but since all the tables have changed significantly, I let sequelize recreate them in a new schema, and I'm not sure how to massage the token/session data from the old tables into the new ones.

**Describe the solution you'd like**
Any help or pointers on a migration path would be appreciated. Or a simple "this can't be done" if it can't be done, so I don't waste too much more time trying.

**Describe alternatives you've considered**
I've poked at token data generated before and after the upgrade and tried to reverse-engineer my own migration path, but it's eluding me.

Apologies if this is a duplicate request (I can't imagine I'm the first with this question in all this time) but I couldn't find any other relevant issues.

**Comment by panva** [comment]
this can't be done, effort ain’t worth it depending on your 5.x storage format.
