### ISSUE TITLE
Authentication / Authorization middleware

### ISSUE THREAD

**Issue by cguedes** [panva/node-oidc-provider#67]
Hi,

I'm using this module to configure an oidc provider with "Authorisation code flow". I've configured the auth / token endpoints with success. After a successful user authentication, the Relying Party (RP) has a valid `access_token` (Bearer), and it can use it to access the `info` endpoint. 

My server has additional endpoints (API) that I want the RP to be able to access to get user data. Do you provide a way (i.e. middleware) to do this?

**Comment by panva** [comment]
Such middleware is not bundled. It is a good practice to separate your authorization and resource servers. You can utilize introspection to get meta info about a presented access token from any location.

**Comment by panva** [comment]
But a cool feature request nontheless. Will dig in further.

**Comment by panva** [comment]
The library would have to expose two middlewares, one for koa, the other for express, the fact that all userinfo Bearer related functionality is prepared for koa would make it easy for koa. I think that does not help your setup though :)

There are however already libraries out there that provide such a middleware (they extract the bearer token according to RFC6750) for each respective stack. What you need to know is that you have `provider.AccessToken.find` at your disposal, it accepts the Bearer value and returns a promise. Resolved with the AccessToken object you have available `accountId, clientId, scope` to help decide whether to continue your request or not.

Rejected with InvalidTokenError when not found, invalid format or expired.

**Comment by cguedes** [comment]
@panva Thanks for the help. Maybe worth put a note about this in the documentation. Knowing that I can pass the `access_token` to the `provider.AccessToken.find` was helpfull.

**Comment by panva** [comment]
true, might as well call the model API stable too by documenting it.
