### ISSUE TITLE
Passing RSA certificate into jwk

### ISSUE THREAD

**Issue by lewiscxa** [panva/node-oidc-provider#672]
This is actually a question. I'm having an issue with passing the  RSA certificate into OIDC provider. Currently, my jwks API is returning these values:
```
{
keys: [
{
e: "AQAB",
n: "tGBfQwO_NQ11yCest6ob_OKZCa-Hd4jLKWKlKGZenQ4gzl-0sney-jczIf6WymY01Dt-Hz3LySUOZi60kzhwdr40oqH13naAywikz8a-iuBSb2ZScWNM-P2FuwtQCuzptA6O6bFmDK94aLgAyJAzEn0Sz3au-oYXAlGqiPjN23_erU31ooHJOdm74W73_oUBSo8Egt3LWZbd7KQ2LtGZRO2trBsTEfVHkx_EIA2TEDIPnUiw1LCMsAp1Ww9-1gmaRlbp6yI7v9GLwAvhyZ_rwehdxNXHKaBlktJC3k3BXixPY8jmd0HeiqbBn6m7foKRHr6ICeaBjuPNjDOUtvhPmQ",
kty: "RSA",
kid: "CemLM209i04WZ6isQ0sTAK300baSvF6PuHIHgLOne08",
use: "sig"
}
]
}
```
As you can see from the above jwk then prop `x5c` and `x5t` are missing. It's obviously because I haven't passed the RSA certificate into ODIC provider. The thing is I can not find an instruction for including the cert into ODIC provider. There is only 1 configuration for jwks stuffs, which is specified via `configs.jwks`. I'm currently using it for passing the RSA private key.

**Comment by panva** [comment]
You're passing the RSA private key as a JWK in a JWKS. All you have to do is add the x5c member with your cert in it.

**Comment by lewiscxa** [comment]
@panva Sorry for the mis-info. I actually pass the JWK generated from RSA private key into `configs.jwks`. Does that mean I'll only need to add the missing props into the JWK then OIDC provider will handle the rest?

**Comment by panva** [comment]
```js
{
  // ... other config,
  jwks: {
    keys: [
      {
        kty: 'RSA',
        // ... other RSA private key required members
        x5c: [
           '// base64 encoded DER certificate value'
        ]
      }
    ]
  }
}
```
