### ISSUE TITLE
scopes_missing when starting new session

### ISSUE THREAD

**Issue by martonboti** [panva/node-oidc-provider#673]
Hi, I have a question about the authorization.

I log in using email/pass, I get to the authorize page, hitting continue, all good there. But then if I open an incognito window, I log in with the same user and the authorize page comes up again.

Is there a way to get rid of the re-authorization everytime a new session is created or am I supposed to store the sessions?

**Comment by panva** [comment]
Storing grants outside of the session is not part of the default interaction policy. I'm saying default because you can define your own policy and store pre-existing grants any way you want.
