### ISSUE TITLE
Simple working example

### ISSUE THREAD

**Issue by Tyrben** [panva/node-oidc-provider#674]
Hi all,
New to api and node in general. I was suprised to find some deprecated examples over the Internet (depending on oidc provider v2.0.0). So I switched to the last version and decided to follow the Readme.
My surprise was when running the example, my client received the error 

> error: invalid_request
> error_description: unrecognized route or not allowed method (GET on /)

The minimal example of a Readme shouldn't be a working example?

I'm certainly wrong in some way, but maybe I'm right.

Greatings,

**Comment by panva** [comment]
well, it is a fully working example, `/` is not a useful route and the example tells you to check `/.well-known/openid-configuration`.

**Comment by Tyrben** [comment]
Ok, thanks, that was maybe unclear.
