### ISSUE TITLE
Unable to understand the significance of `devInteractions` field in featues.

### ISSUE THREAD

**Issue by kartikchauhan** [panva/node-oidc-provider#675]
In the section [features.devInteractions](https://github.com/panva/node-oidc-provider/blob/v6.23.1/docs/README.md#featuresdevinteractions), the documentation says 

> Development-ONLY out of the box interaction views bundled with the library allow you to skip the boring frontend part while experimenting with oidc-provider.

What I inferred from this statement is that one doesn't need to build his own frontend if he wants to experiment with the library and by default the library will show its frontend pages to the User.

But after setting the value to `false`, I'm still able to see the UI pages.

I'm guessing I inferred it wrong but could you please tell me what difference will setting the value of `devInteractions` to `false` from the default value `true` will make. Thank you.

**Comment by panva** [comment]
You inferred right but you don’t set interactions with just a boolean anymore. Its { enabled: false } to override the default.

**Comment by kartikchauhan** [comment]
Yes, this is how I set the value in `support/configuration.js`
```
features: {
    devInteractions: { enabled: false }, // defaults to true
...
```

When it didn't work, I overrode the default value in `defaults.js` as well.
```
devInteractions: { enabled: true }
```

**Comment by panva** [comment]
```
const { Provider } = require('./lib');

const provider = new Provider('http://localhost:3000', {
  features: {
    devInteractions: { enabled: false },
  },
  clients: [
    {
      client_id: 'foo',
      token_endpoint_auth_method: 'none',
      grant_types: ['implicit'],
      response_types: ['id_token'],
      redirect_uris: ['https://jwt.io'],
    },
  ],
});

provider.listen(3000);
```

Afterwards, navigating to `http://localhost:3000/auth?client_id=foo&response_type=id_token&nonce=foo&scope=openid` shows there is no default UI from the `devInteractions` feature.
