### ISSUE TITLE
Empty /me?access_token={token} response

### ISSUE THREAD

**Issue by karlbateman** [panva/node-oidc-provider#68]
Great job on this @panva :+1:

I have followed the example, step by step and at the final stage having defined the custom interactions, I can go through the process of authenticating using the login form but when I visit the url `ISSUER_URL/me?access_token={token}` I get  an empty `{}` json response.

What am I missing? Do I need to do something with the claims to emit some user metadata?

Here is my `Account` class.
```javascript
class Account {
  constructor(id) {
    this.id = id || uuid()
  }

  claims() {
    return Object.assign({}, USERS[this.id], {
      id: this.id,
    })
  }

  static findById(id) {
    return Promise.resolve(new Account(id))
  }

  static authenticate(email, password) {
    assert(password, 'password must be provided')
    assert(email, 'email must be provided')

    const lowercased = String(email).toLowerCase()
    const id = _.findKey(USERS, { email: lowercased })

    assert(id, 'invalid username or password')
    return Promise.resolve(new this(id))
  }
}
```

I have a few questions related to setting this up, mostly with regard to implementing custom endpoints for JSON responses and rendered views. It would be awesome to get that documented :smile: 

Regards

**Comment by panva** [comment]
At a first glance, the claim name should be sub, not id ;) Claims returned by your model must correspond with claims you have set on your op, obviously. 

To do custom outside of the op, this is not a framework you could add endpoints to, please see the mounting section of the configuration.md, hope it pushes you in the right direction.

**Comment by panva** [comment]
Reference: https://github.com/panva/node-oidc-provider/blob/master/docs/configuration.md#accounts

**Comment by panva** [comment]
Yeah, an absolute oversight on my end, sorry, i've fixed the example source, just redo [03-oidc-views-accounts](https://github.com/panva/node-oidc-provider-example/tree/master/03-oidc-views-accounts), re-run yarn and you should be good to go.

The example you ran through already gives you an expressApp which you're free to do with as you please (custom apis, render index page etc)

**Comment by karlbateman** [comment]
Thanks @panva I am now getting the `{ sub: [id] }` response as expected.  One final thing, could you provide an example of returning an email address with this JSON response, I think this would really help with getting started.

Thanks again for the quick response 👍

**Comment by panva** [comment]
But it already does - did you re-copy both account and index files? And do you request the email scope from the authorization endpoint?

**Comment by karlbateman** [comment]
Yep, and I am getting an authorization error.

**Comment by karlbateman** [comment]
Interestingly, I fixed it on my example application by using `this.id` instead of `this.accountId`

**Comment by panva** [comment]
.id does not figure in the examples at all > [/me valid for the next two hours](https://rocky-ocean-58237.herokuapp.com/me?access_token=OWVlYTEyMTQtMWI2Ny00MDAxLThmZjctYjE0MGQxYTNjMzA4gM1dN9fJIEgWflTkKDxfujj3hGG1KiYINgPaBus75L1JFs4OahCLOoYZkmjSebQbq6FtODII6oNAFfqKNy7pTA)

1) https://github.com/panva/node-oidc-provider-example/blob/master/03-oidc-views-accounts/account.js#L24-L28
2) https://github.com/panva/node-oidc-provider-example/blob/master/03-oidc-views-accounts/index.js#L119

**Comment by karlbateman** [comment]
Your example works and as a result, I realized that after renaming `this.accountId` I forgot to adjust `account.accountId` on the login `POST` interaction.

Any pointers as to how I might implement a view which renders that data from `/me?access_token=[token]`?

Thanks for all your help on this. Feel free to close.

**Comment by panva** [comment]
Happy I was able to help, thanks for pointing out the example was incomplete.

> Any pointers as to how I might implement a view which renders that data from /me?access_token=[token]?

Nope, sounds like something you'll to tackle on your own as it does fall outside of OIDC scope.

**Comment by karlbateman** [comment]
Not to worry, glad I could help 😄
