### ISSUE TITLE
Increase lfetime of short session

### ISSUE THREAD

**Issue by lewiscxa** [panva/node-oidc-provider#680]
AFAIK then short session is used for storing non-logged users' metadata. The default lifetime is 10m if I was not mistaken. I'm just wondering whether or not it's ok increase its lifetime to a longer time like 1 day or 1 month. Will there be security risks of doing that? Also do you know where can I can the related spec for short sessions?
```
    cookies: {
      long: {
        maxAge: Config.cookieLongMaxAge,
      },
      short: {
        maxAge: Config.cookieShortMaxAge
      }
    },

**Comment by panva** [comment]
> AFAIK then short session is used for storing non-logged users' metadata.

short cookie config applies to the Interaction model, that one has nothing to do with user's metadata per se, it's to store details about why an interaction is requested and, when part of an already authenticated flow, tie to to its session.

> I'm just wondering whether or not it's ok increase its lifetime to a longer time like 1 day or 1 month.

I'm wondering why one might want that? Are you expecting end-users to take 1 day or a month to fill out a login form?

**Comment by lewiscxa** [comment]
@panva I'm having an issue that we're throwing the invalid_request error when the short cookie expires. Right now it's set to 10 minutes. There can be a case that users reach the login page and just go out and comeback after 1hour for example. If they try to login again then they'll see that error. I intend to increase the session lifetime to 1h but I'm just a bit worry about security stuff so I'm asking for your helps to clarify the case.

**Comment by lewiscxa** [comment]
I'm also quite new to OIDC so I don't really understand about the purpose of short cookie lifetime. Will it be for removing unnecessary temporary data only or is there any security reasons for that?

**Comment by panva** [comment]
1hr is fine.

**Comment by lewiscxa** [comment]
@panva Is this ODIC-provider implementation for short cookie following OIDC spec?
