### ISSUE TITLE
About the error of interaction session id cookie not found

### ISSUE THREAD

**Issue by StarinkFan** [panva/node-oidc-provider#683]
Hello! I am trying to develop a oidc provider with your code. However, I just got the error of interaction session id cookie not found" when I tested my project. So, I ran your example code of koa, but got the same error. I have no idea how to deal with it, as I cannot find any code showing how to set cookie and session properly. So, may you update your example folder to show the correct way to use cookie and session. Thank you!

**Comment by panva** [comment]
Everything works fine, but due to the samesite changes, you kinda have to run dev on https now.

**Comment by StarinkFan** [comment]
But it seems that my provider can get the cookie in request without https now. Does running without https affect something I don't know?

**Comment by StarinkFan** [comment]
I meet this error when my RP request the OP for the first time, when running function interactionDetail(req, res)

**Comment by panva** [comment]
Again, 

I just add a test client to example/koa.js

```
const provider = new Provider(ISSUER, { adapter, ...configuration, clients: [
    {
      client_id: 'foo',
      response_types: ['id_token'],
      grant_types: ['implicit'],
      redirect_uris: ['https://jwt.io'],
      token_endpoint_auth_method: 'none',
    }
  ] });
```

Run

```
node example/koa.js
```

visit http://localhost:3000/auth?client_id=foo&response_type=id_token&nonce=foo&scope=openid

It all works, in this case because of the samesite legacy compatibility cookie which behaves as a lax cookie now.

Whatever issue you're having you must've introduced yourself.
