### ISSUE TITLE
How can I list all Clients authorized by user?

### ISSUE THREAD

**Issue by clairtonluz** [panva/node-oidc-provider#684]
There is any way to list all Clients (Applications) which was authorized by user before?

I want create a page where the user can see all apps that have access to him information and allow him to remove this access.

**Comment by panva** [comment]
@clairtonluz this is out of scope - you own the DB adapter, how you denormalize and store data is up to you.

**Comment by clairtonluz** [comment]
Ok, I only ask to make sure that I won't make something that already exists. Tks
