### ISSUE TITLE
CIBA Implementation plan

### ISSUE THREAD

**Issue by ramajd** [panva/node-oidc-provider#685]
just wanted to know if there is any plan about adding the [_Client initiated backchanel authentication_ (CIBA)](https://openid.net/specs/openid-client-initiated-backchannel-authentication-core-1_0.html) flow to this library? 

if no, is there any difficulties about implementing this feature that you decide about not implementing that?  otherwise, is there any part that I could help on? 

Regards,
Reza

**Comment by panva** [comment]
@ramajd i don’t have concrete plans for implementing CIBA at the moment that i could share with you. 

Should your company want to sponsor its development please reach out to me via email.
