### ISSUE TITLE
Invalid_client error during authorization code token exchange flow.

### ISSUE THREAD

**Issue by Oscar3000** [panva/node-oidc-provider#687]
Hello, I am currently implementing oauth for mobile app using this library, I created a Provider and I use a MySQL adapter to allow saving clients that are dynamically registered in my server( Express/NodeJs).  Here is my initial setup 
```
const oidc = new Provider(config.get('defaultAddress.url') + '/oidc_p', {
		adapter: MySQLAdapter,
		findById: Account.findById,
		claims: {
				acr: null,
				auth_time: null,
				iss: null,
				openid: ['sub'],
				email: ['email', 'email_verified'],
				profile: [
					'email',
					'email_verified',
					'family_name',
					'given_name',
					'name',
					'picture',
					'updated_at',
					'zoneinfo'
				]
			},
			features: {
				devInteractions: false,
				claimsParameter: true,
				clientCredentials: true,
				discovery: true,
				encryption: true,
				introspection: true,
				request: true,
				requestUri: true,
				revocation: true,
				registration: true,
				registrationManagement: true,
				// may be deactivate session management and use our session?
				sessionManagement: false,
				alwaysIssueRefresh: true
			},
		});
```
so I created a client dynamically and since I am using react-native-app-auth. this is the configuration object: 
```
config =  {
    issuer: "http://192.168.1.22:3000/oidc_p",
    clientId: "CLIENT_ID",
    redirectUrl: "http://192.168.1.22:3000/mobile-login",
    scopes: ["openid", "profile", "email", "phone", "address"],
    serviceConfiguration: {
      authorizationEndpoint: "http://192.168.1.22:3000/oidc_p/auth",
      tokenEndpoint: "http://192.168.1.22:3000/oidc_p/token",
      revocationEndpoint: "http://192.168.1.22:3000/oidc_p/token/revocation"
    }
  }
```

I created a mobile-login redirect function that gets the authorization code and state then in that  function, I created a post request(using the request package) to the token endpoint here is the request: 
redirect function

 ```
router.get('/mobile-login', async function(req, res) 
{
		const clientId = 'CLIENT_ID';
		const clientSecret =
			'CLIENT_SECRET';
		const oidc = openIdProvider().oidc;
		const client = await oidc.Client.find(String(clientId));
		if (!client) {
			throw errors(400, {
				message: "No client with clientId ${clientId} found",
				errorCode: 'no_client_found'
			});
		}
		console.log('client: ', client);

		if(req.query.code) {
			var options = {
				method: 'POST',
				url: 'http://192.168.1.22:3000/oidc_p/token',
				headers: {
					'content-type': 'application/x-www-form-urlencoded',
					Authorization: "Basic MTIwOWFlYjUtYzZlOS00Yjc1LWJiNGQtMDcyNGI5YjU1MWEzOlBDY0ZqZHF4ZzkxTlZwWnUwVGZHWjV0VmpSbGNKejhlak0lMkZORW96T2tFSWp6Q3MzRnFVcnpCRzdVOWtBNnJKTA=="
				},
				form: {
					grant_type: 'authorization_code',
					code: req.query.code,
					redirect_uri: 'http://192.168.1.22:3000/mobile-login'
				}
			};

			request(options, function (error, response, body) {
				if (error) throw new Error(error);

				console.log('token returned ', body);
			});
			res.redirect(
				"app://oauth"
			);
		}
	});
```
Now when I search for the client using the oidc.Client.find method, I get a client object and I have checked my database and the client exists. But whenever I try to send a Post request for the access token as I did above or using Postman, I keep getting this error 

> {"error":"invalid_client","error_description":"client is invalid"}

I want to know what I did wrong and if there is a problem with my configuration.

Node version: 13.8.0
oidc-provider version: 1.15.12.
Linux Ubuntu 18.04

**Comment by panva** [comment]
@Oscar3000 please format your issue properly first.

**Comment by Oscar3000** [comment]
@panva I have formated it

**Comment by panva** [comment]
Is this your client_id? `1209aeb5-c6e9-4b75-bb4d-0724b9b551a3`

**Comment by Oscar3000** [comment]
Yes, It is, I placed it like this Base64(urlencoded(clientId):urlencoded(clientSercet)) in the Authorization header.

**Comment by panva** [comment]
I don't get the boundaries of your system, it's not clear to me why the client code has access to the provider database interfaces like in your code. Because of that I can't say "yeah you're doing everything right".

**Comment by Oscar3000** [comment]
do you mean this?
```
const oidc = openIdProvider().oidc;
   	const client = await oidc.Client.find(String(clientId));
   	if (!client) {
   		throw errors(400, {
   			message: "No client with clientId ${clientId} found",
   			errorCode: 'no_client_found'
   		});
   	}
   	console.log('client: ', client);

```
I was just showing that the client exists in the database.

**Comment by panva** [comment]
Yeah.

Either way

> `oidc-provider version: 1.15.12`

🤷‍♂

**Comment by Oscar3000** [comment]
@panva could you please show me an example of creating a client for a native app (I use react-native for frontend and I use this package(React-Native-Auth-App) to handle authorization. As I have tried everything and token endpoint keeps giving me invalid_client.

**Comment by panva** [comment]
I don't have the capacity to try and resolve your issue here. Your setup is, ... strange, to say the least. Why are you using a version from 2017!? Why is the RP's redirect url an OP hosted url that itself does the code exchange? ... i could go on.

Use the [appauth](https://tools.ietf.org/html/rfc8252) pattern properly, follow the quick starts, only add client configuration and don't implement proprietary endpoints that beat the purpose of a secure oauth exchange.
