### ISSUE TITLE
Make param defined in extraParams available in extraAccessTokenClaims?

### ISSUE THREAD

**Issue by fiznool** [panva/node-oidc-provider#688]
I don't see how I can get access to a param (that I've whitelisted in `extraParams`) inside `extraAccessTokenClaims`, and was wondering if I can workaround this somehow.

Background: I'd like to be able to determine a set of 'logged-in' devices, i.e. devices that have requested an access/refresh token pair. This would be used to display each individual device in a list, along with the ability to revoke tokens on a device-by-device basis.

I figured I could segregate devices by the auth server assigning a 'deviceId' to each on first login. This device ID would be associated with the access/refresh token pair (via `extraAccessTokenClaims`), and would also be exposed to the device on successful login, so it can store it locally. When the device next logs in, it would pass the previously stored deviceId as a custom parameter on the authorization URL, for example `cb_device_id=<uid>`. On recognition of this param, the auth server would not generate a new deviceId, instead it would take the passed one and associate it with the new token pair. This way, the server can track each individual device's logged-in status.

To achieve this using the proposed implementation, I need to access the `cb_device_id` param inside the `extraAccessTokenClaims`. Unfortunately since the `ctx` object in this method relates to the `/token` URL rather than the `/authorization` URL, I am not able to do so.

Perhaps there is a better way to achieve the goal here?

**Comment by panva** [comment]
> extraParams
> Pass an iterable object (i.e. Array or Set of strings) to extend the parameters recognised by the **authorization and device authorization endpoints**.

☝️ 

As far as accessing custom body params and or query string members, use `ctx.query` for query, or `ctx.oidc.body` for the parsed body before param filtering.
