### ISSUE TITLE
configurable cookie names

### ISSUE THREAD

**Issue by pinkinsect** [panva/node-oidc-provider#69]
The code in session model is below. For example: change '_session' to instance(provider).configuration('cookies.session_key'). I think this will be more flexible, and can avoid the value is covered. What do you think of it? Or what's your opinion?

`static get(ctx) {
      // is there supposed to be a session bound? generate if not
      const sessionId = ctx.cookies.get('_session', {
        signed: instance(provider).configuration('cookies.long.signed'),
      }) || uuid();
      return this.find(sessionId).then((session) => {
        // refresh the session duration
        ctx.cookies.set('_session', sessionId, instance(provider).configuration('cookies.long'));
        return session;
      });
    }`

**Comment by panva** [comment]
Makes sense, I gotta bundle this with a residue cookie cleanup, so won't be there right away.
