### ISSUE TITLE
oidc.callback redirect behavior

### ISSUE THREAD

**Issue by ionizer** [panva/node-oidc-provider#690]
I noticed what I feel like a little quirky behavior with this library, specifically with `devInteractions` configuration. When this is enabled, I don't have to specify `interactions: { url: (ctx) => '/interactions/:uid' }` and it redirects me to my interaction views. But this is not the case when `devInteractions` is disabled and the provider will redirect to the wrong interactions url if it's not configured and if we use a prefix like the example below.

**Minimum example**
```js
// index.js
const express = require('express');
const bodyParser = require('body-parser');

const app = express();

app.use(bodyParser.urlencoded({ extended: false }))

app.use('/openid', require('./routes/openid'));
app.listen(3000);

// routes/openid.js
const { Router } = require('express');
const router = Router();

const Provider = require('oidc-provider');
const oidc = new Provider(`https://localhost:3000/`, {
  clients: [{
    client_id: 'foo',
    client_secret: 'bar',
    redirect_uris: ['http://lvh.me/cb'],
  }],
  features: {
    devInteractions: { enabled: false } //change to true and we don't have to configure interactions url
  }
});

router.use(oidc.callback);

module.exports = router;
```

Is this by design? Or can this be improved so it behaves in such a way like when `devInteractions` is enabled? If this is by design, I think we should at least make it clear in the documentation that when `devInteractions` is disabled, `interactions.url` should be configured when using route prefixes.

**Comment by panva** [comment]
Same as with any configuration, there's a [default](https://github.com/panva/node-oidc-provider/blob/master/docs/README.md#interactionsurl) value.
