### ISSUE TITLE
Client credentials never return jwt token

### ISSUE THREAD

**Issue by sginer** [panva/node-oidc-provider#691]
Hello
I force acces token format to jwt in my configuration and the response is never a jwt token.

Config in configuration.js

formats: {
    AccessToken : "jwt"
  },

I do a post request on /token with grant_type=client_credentials, client_id ans client_secret and the response is always looks like this

{
    "access_token": "PgtQz-llNMd2kDeglD6JpG9TZrdTUwREw3FGNCW-Dj-",
    "expires_in": 600,
    "token_type": "Bearer"
}

regards

Stéphane GINER

**Comment by panva** [comment]
https://github.com/panva/node-oidc-provider/blob/v6.23.3/docs/README.md#formats

> default value:
> ```js
> {
>   AccessToken: 'opaque',
>   ClientCredentials: 'opaque',
> }
> ```

They're separate configs for AccessToken model and ClientCredentials model.

**Comment by sginer** [comment]
Ok great

Thank you for your answer

Regards
