### ISSUE TITLE
Implementing API key auth

### ISSUE THREAD

**Issue by alexeyknyshev** [panva/node-oidc-provider#692]
Hello @panva !

Currently we have custom grant type "api_key" that allows getting AccessToken from some opaque secret (id generated by nanoid). The drawback of using custom grant is that resulting flow is close to "refresh_token" one and forces user to interact with IDP (refreshing access token periodically). On the other hand, our goal is to allow passing this API key / opaque secret as Bearer auth to RP, so RP should not know whether it's an AccessToken or an ApiKey (kinda long-lived AccessToken). So far I came up with the following options:

1.  Override AccessToken.getValueAndPayload as you suggested in [the comment for this issue](https://github.com/panva/node-oidc-provider/issues/93#issuecomment-333486517). If I understand correctly, this should allow us to add some extra fields into AccessToken and store them persistently via adapter. The question here is how custom fields can be propagated from AccessToken constructor into context of getValueAndPayload so we store them persistently. Should we just monkey-patch access AccessToken instances and add some required fields there to be accessible within getValueAndPayload method? Can we use [extraAccessTokenClaims](https://github.com/panva/node-oidc-provider/blob/master/docs/README.md#extraaccesstokenclaims) for storing additional fields depending on whether this AccessToken is API-key actually or not? Lifetime handling of such tokens is also questionable as we would like them to be long-lived. If I understand correctly, there's no way to specify custom TTL on token by token basis except this recommendation.
2. Try to implement API-key handling within the Adapter. So just store required info in separate table form other tokens table in DB and return some pseudo access tokens from find method. This looks more hacky and problematic as provider instance seems to be unavailable from adapter methods, does it? Also I expect significant slowdown in lookup as it will always require to check tokens table first to check if generic AccessToken exists by id, otherwise fallback to API-key existence check and fire second DB request into that separate table. So we'll end up with 2 queries per API-key lookup. Maybe it can be optimized by inferring token type from id before lookup (some special prefix or any other mark for adapter - looks ugly tho)
3. Create custom token type in addition to existing ones. But it seems to be the most complicated way as I have no idea how it would be handled by token introspection endpoint.

Thanks!

**Comment by panva** [comment]
@alexeyknyshev 

- 1) is no longer available public API in v6.x
- 2) and 3) i can’t say much about

I’d recommend to use standard flows rather then something proprietary in the first place. Secondly, coming up with / conceptualizing custom proprietary ones isn’t what i can offer my capacity for. I hope you understand.

**Comment by alexeyknyshev** [comment]
Thanks for quick turnaround!

Let me ask about token TTLs then:
Is the following solution with modifying expiration property getter still valid in the recent versions: https://github.com/panva/node-oidc-provider/issues/181#issuecomment-350961990?

**Comment by panva** [comment]
ttl configuration members themselves can now be a function that determines the ttl at the time the token is being issued, see docs
