### ISSUE TITLE
Setting interaction cookies

### ISSUE THREAD

**Issue by odub** [panva/node-oidc-provider#693]
Hi @panva,

Thanks for your hard work on this library, it's warmly appreciated!

I'm in the process of implementing email address verification as a node-oidc-provider interaction.

I'd like my interaction route to be able to set interaction and session cookies after the user clicks a link sent to their email. I'm using a JWT URL param that would allow me to transfer any data needed to resume the session, eg. the interaction uid.

If it's possible, I'd like users to be able to pick up where they left off with their interactions even if they have switched browsers/devices or otherwise lost access to the cookies that grant access to their interactions and session.

Is there a public interface that allows me to set the cookies necessary to resume an interaction session in a browser session without the original cookies?

`setProviderSession` seems like it might be the tool I need? If it is, I can't currently see how to derive my interaction state from the Session object it returns

**Comment by panva** [comment]
> `setProviderSession` seems like it might be the tool I need?

It is not.

> Is there a public interface that allows me to set the cookies necessary to resume an interaction session in a browser session without the original cookies?

There is not. Your only chance is to emulate the cookie setup.

**Comment by odub** [comment]
Ok! I can continue on from this information. It's good to know that there's no other way

Thank you for taking time to clarify
