### ISSUE TITLE
_interaction cookie is missing

### ISSUE THREAD

**Issue by fidenz-chim** [panva/node-oidc-provider#694]
**Describe the bug**
I'm following the express sample provided in [examples](https://github.com/panva/node-oidc-provider/tree/master/example)
When authorization-endpoint is invoked for a new user, it fails with following error.
```
SessionNotFound: invalid_request
    at Provider.getInteraction (.../libs/oidc_provide/lib/provider.js:55:11)
    at Provider.interactionDetails (.../libs/oidc_provide/lib/provider.js:233:27)
    at /Chim/Fidenz/Dev/siop/libs/oidc_provide/example/routes/express.js:54:26
    at Layer.handle [as handle_request] (.../libs/oidc_provide/node_modules/express/lib/router/layer.js:95:5)
    at next (.../libs/oidc_provide/node_modules/express/lib/router/route.js:137:13)
    at setNoCache (.../libs/oidc_provide/example/routes/express.js:46:5)
    at Layer.handle [as handle_request] (.../libs/oidc_provide/node_modules/express/lib/router/layer.js:95:5)
    at next (.../libs/oidc_provide/node_modules/express/lib/router/route.js:137:13)
    at Route.dispatch (.../libs/oidc_provide/node_modules/express/lib/router/route.js:112:3)
    at Layer.handle [as handle_request] (.../libs/oidc_provide/node_modules/express/lib/router/layer.js:95:5)
```

**To Reproduce**
provider configuration
https://gist.github.com/fidenz-chim/0006911a1d107f87deb61ed7c015beda

```js

// keystore(s) - if they affect the behaviour

// client(s) configuration
{
          client_id: 'EPXH7xeHBvve0RMF-ZbCV',
          client_secret: '3HU_yptlA87-6w7f25hk5FqUqAy_gPkZKbPT28JID-XOy_H-po5RE7dCP4xQ9vaNTOMTzD5Pz2NG6JIPh05qBw',
          redirect_uris: ['https://localhost:5000/callback'],
          response_types: ['code'],
        }
```

Steps to reproduce the behaviour:
1.  Run the oidc-provider
2.  Run the RP
3.  Invoke authorisation-endpoint using following code
```
        const _url = client.authorizationUrl({
          scope: 'openid email profile',
          // scope: 'openid',
          resource: issuerssuer.metadata["authorization_endpoint"],
          code_challenge,
          code_challenge_method: 'S256',
        });
        res.redirect(_url);
```

**Expected behaviour**
Callback url https://localhost:5000/callback get invoked in RP

**Environment:**
 - oidc-provider version: v6.23.3
 - node version: v12.16.1

**Additional context**
- I have a RP app (express app with openid-client) running locally on https://localhost:5000. 
- Then oidc-provider (based on [oidc-provider example with express](https://github.com/panva/node-oidc-provider/tree/master/example) ) running on https://localhost:3000. 
- Simple HTML/JS page invokes the authorisation-endpoint via a route in RP.
- I have included features.registration.enabled:true to configurations provided under 
[support/configurations.js](https://github.com/panva/node-oidc-provider/blob/master/example/support/configuration.js)
- redis has been locally setup and configured using example/adapters/redis.js

- I could observe following request from browser

http://localhost:3000/auth?client_id=EPXH7xeHBvve0RMF-ZbCV&scope=openid%20email%20profile&response_type=code&redirect_uri=https%3A%2F%2Flocalhost%3A5000%2Fcallback&resource=http%3A%2F%2Flocalhost%3A3000%2Fauth&code_challenge=MR09wBrOHIX_q-FU1wrXGXaszcKUavg6FUcIY0W5XhU&code_challenge_method=S256

 - Then a redirection to

http://localhost:3000/interaction/R5ytEDexxII-fK7LlOJdp

At this point, request fail with 400 Bad request and server returns the following
_SessionNotFound: invalid_request_

***Additional Info***
- Provider Discovery and Registration of relying parties work as expected.

- I have tried the [step-by-step](https://github.com/panva/node-oidc-provider-example) sample on Heroku and standalone sample locally. Ended up with the exact same issue.

- I have tried siteSame=false assuming cookies are store for a different domain, but no luck

- Further, I debugged the app and found that _interaction cookie is not found in the context and that causing the failure when 
```
// lib/provider.js
async function getInteraction(req, res) {
  assertReqRes.apply(undefined, arguments); // eslint-disable-line prefer-spread, prefer-rest-params
  const ctx = this.app.createContext(req, res);
  // console.log( "=============>>ctx.cookies", ctx.cookies);
  // console.log( "=============>>this.cookieName(interaction)", this.cookieName('interaction') );
  // console.log( "=============>>instance(this).configuration('cookies.short')", instance(this).configuration('cookies.short'));

  const id = ssHandler.get(
    ctx.cookies,
    this.cookieName('interaction'),
    instance(this).configuration('cookies.short'),
  );
  console.log( "=============>>id", id ); // undefined
  if (!id) {
    throw new SessionNotFound('interaction session id cookie not found');
  }
```
 - [ ] the bug is happening on latest oidc-provider too.
 - [x] i have tried DEBUG (see README) and can see the issue is with the provider and not my code.
 - [x] i have searched the issues tracker on github for similar issues and couldn't find anything related.
 - [x] i have searched the [FAQ](https://github.com/panva/node-oidc-provider/blob/master/docs/README.md#faq) and couldn't find anything related.

**Logs**
[DEBUG output](https://gist.github.com/fidenz-chim/d97b8f3f9b9640f061710c75ee09e7a0)

**Comment by fidenz-chim** [comment]
In my setup, implicit flow works as expected (thank you for the guidance above). Still I get the same error when try to use the authorization code flow.
I did a cleaner implementation of the above and following are the details.

I have https://rptest.com (relying party) & https://optest.com (provider based on [this example](https://github.com/panva/node-oidc-provider/tree/master/example) ) are locally setup. Both domains are behind a nginx proxy.
with self issued SSL certs. Further I had to disable SSL cert validation using _process.env["NODE_TLS_REJECT_UNAUTHORIZED"] = 0;_

#### Setting up OIDC Provider include ####
# CORS enabled
# Redis Adaptor configured
# Features enabled
```
{
    // disable the packaged interactions
    devInteractions: { enabled: false },
    introspection: { enabled: true },
    revocation: { enabled: true },
    registration: {enabled:true},
    sessionManagement: {enabled:false},
    encryption: {enabled:true},

}
```
# I get the following warning when start the Provider, but not sure whether it has any impact.
```
WARNING: configuration cookies.keys is missing, this option is critical to detect and ignore tampered cookies
```

#### Register Client ####
I do register my clients dynamically and following are the parameters I use.
```
{"grant_types": ["authorization_code"],"response_types": ["code"],"redirect_uris": ["https://rptest.com/acf_callback"],"token_endpoint_auth_method": "client_secret_basic","post_logout_redirect_uris":["https://rptest.com/logout"]}
```
I could confirm Clients get registered successfully. Following is from Redis DB
```
"{\"application_type\":\"web\",\"grant_types\":[\"authorization_code\"],\"id_token_signed_response_alg\":\"RS256\",\"post_logout_redirect_uris\":[\"https://rptest.com/logout\"],\"require_auth_time\":false,\"response_types\":[\"code\"],\"subject_type\":\"public\",\"token_endpoint_auth_method\":\"client_secret_basic\",\"introspection_endpoint_auth_method\":\"client_secret_basic\",\"revocation_endpoint_auth_method\":\"client_secret_basic\",\"request_uris\":[],\"client_id_issued_at\":1588314858,\"client_id\":\"WDc6pb1mixNCu0N85oYGo\",\"client_secret_expires_at\":0,\"client_secret\":\"DRCeSY1uHsGqwsI5TbN5I7wpJ17hXfy0Mxl0_99KGnQ6Dx0SAf43IfvEckh4Zl-axiGUT1WkE4TkF9ZGyAyfQw\",\"redirect_uris\":[\"https://rptest.com/acf_callback\"]}"
```

#### Client Login ####
My RP app has HTML/JS front end and Node/Express backend. Login request get initiated from frontend which invokes the following in Node app
```
function userLoginFunction(req, res, next) {
    console.log("userLoginFunction Invoked");

    const { Issuer } = require('openid-client');
    Issuer.discover(REMOTE_URL) // => Promise
      .then(function (googleIssuer) {
        // console.log('Discovered issuer %s %O', googleIssuer.issuer, googleIssuer.metadata);
        console.log("['authorization_endpoint']",googleIssuer.metadata["authorization_endpoint"]);

        client = new googleIssuer.Client({
            client_id: 'WDc6pb1mixNCu0N85oYGo',
            client_secret: 'xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx',
            redirect_uris: ['https://rptest.com/acf_callback'],
            response_types: ['code'],
            //   scope:['openid'],
            // id_token_signed_response_alg (default "RS256")
            // token_endpoint_auth_method (default "client_secret_basic")
        }); // => Client

        const code_challenge = generators.codeChallenge(code_verifier);

        const _url = client.authorizationUrl({
            scope: 'openid email profile',
            nonce: 'foo',
            //resource: googleIssuer.metadata["authorization_endpoint"],
            resource: 'www.api.com/test',
            code_challenge,
            code_challenge_method: 'S256',
        });

        console.log('url', _url);
        res.redirect(_url);

      }).catch(function(e) {
          console.error(e.message); // "oh, no!"
      });
}
```
Following is the generated Authorization url
```
https://optest.com/auth?client_id=WDc6pb1mixNCu0N85oYGo&scope=openid%20email%20profile&response_type=code&redirect_uri=https%3A%2F%2Frptest.com%2Facf_callback&nonce=foo&resource=www.api.com%2Ftest&code_challenge=DAQ48z09ol9W9pEAOrBLAhqwe3E92CYgQxxptdrx1_A&code_challenge_method=S256
```
At this point, I'm expecting the Provider to prompt user login and then consent screens but request fails at _/interaction/:uid_ with the following output;
```
oidc-provider:authentication:interrupted uid=FnU7EiQfwVp7MDzRr3716 interaction=Interaction { returnTo: 'https://optest.com/auth/FnU7EiQfwVp7MDzRr3716', prompt: { name: 'login', reasons: [ 'no_session' ], details: { max_age: undefined, login_hint: undefined, id_token_hint: undefined } }, lastSubmission: undefined, uid: 'FnU7EiQfwVp7MDzRr3716', params: { client_id: 'WDc6pb1mixNCu0N85oYGo', code_challenge: 'DAQ48z09ol9W9pEAOrBLAhqwe3E92CYgQxxptdrx1_A', code_challenge_method: 'S256', nonce: 'foo', redirect_uri: 'https://rptest.com/acf_callback', response_type: 'code', scope: 'openid email profile' }, signed: undefined, session: undefined, kind: 'Interaction', jti: 'FnU7EiQfwVp7MDzRr3716', exp: 1588381473 } +0ms
SessionNotFound: invalid_request
  at Provider.getInteraction (/Chim/Fidenz/Dev/siop/libs/test_oidc2/node_modules/oidc-provider/lib/provider.js:50:11)
  at Provider.interactionDetails (/Chim/Fidenz/Dev/siop/libs/test_oidc2/node_modules/oidc-provider/lib/provider.js:234:27)
  at /Chim/Fidenz/Dev/siop/libs/test_oidc2/src/index.js:112:32
  at Layer.handle [as handle_request] (/Chim/Fidenz/Dev/siop/libs/test_oidc2/node_modules/express/lib/router/layer.js:95:5)
  at next (/Chim/Fidenz/Dev/siop/libs/test_oidc2/node_modules/express/lib/router/route.js:137:13)
  at setNoCache (/Chim/Fidenz/Dev/siop/libs/test_oidc2/src/index.js:106:3)
  at Layer.handle [as handle_request] (/Chim/Fidenz/Dev/siop/libs/test_oidc2/node_modules/express/lib/router/layer.js:95:5)
  at next (/Chim/Fidenz/Dev/siop/libs/test_oidc2/node_modules/express/lib/router/route.js:137:13)
  at Route.dispatch (/Chim/Fidenz/Dev/siop/libs/test_oidc2/node_modules/express/lib/router/route.js:112:3)
  at Layer.handle [as handle_request] (/Chim/Fidenz/Dev/siop/libs/test_oidc2/node_modules/express/lib/router/layer.js:95:5)
```
I believe my code goes through the same scenario as [this issues](https://github.com/panva/node-oidc-provider/issues/552).

Any guidance would be highly appreciated.

**Comment by panva** [comment]
Something “based” on an example isn’t the example. The examples work. 

Give me a code I can simply run that reproduces your issue and I can tell you what you’re likely missing or doing wrong. Else i’m not able to reproduce
