### ISSUE TITLE
Using the same client id for multiple app types

### ISSUE THREAD

**Issue by ChadKillingsworth** [panva/node-oidc-provider#695]
What's the recommendation around utilizing the same client id for both a web and native app? If I'm reading the code correctly, it's not supported - mainly due to URL validation.

**Comment by panva** [comment]
Not being able to re-use the clients is intended by the OpenID specs.

There is however a scenario for web and native app to re-use the same client - you can set up a web application and add claimed https uri that will be used by the mobile app. Both will then use an https uri.
