### ISSUE TITLE
Routes starting with /d go to device flow - code input step

### ISSUE THREAD

**Issue by acorbel** [panva/node-oidc-provider#696]
**Describe the bug**
It seems that all routes starting with /d go to the device flow at the source input step.

**To Reproduce**
Here are some examples:
https://op.panva.cz/d
https://op.panva.cz/dzzz
https://op.panva.cz/dffff

I'm using the 6.23.4 version and it has the same behaviour.

Is it a wanted feature?

Thank you!

**Comment by panva** [comment]
Nice find @acorbel
