### ISSUE TITLE
Example configuration for Device Authorization Grant

### ISSUE THREAD

**Issue by wklenk** [panva/node-oidc-provider#702]
I would like to use this project to demonstrate _Oauth2 Device Authorization Grant_, without writing any code. Is it possible to "play" through this grant flow using Postman and running this oidc-provider?

I managed to create a configuration by try-and-error, but the final step to get a JWT fails all the time giving an "access_denied" HTTP response.

I would like to request the following:

* Please provide a working, minimal configuration for "Device Authorization Grant"
* Make a statement how it is possible to use this oidc-server without code modifications, and if not possible, suggest the minimal modifications that need to be added to the code.

Thanks a lot!

**Comment by panva** [comment]
@wklenk enable the feature and use e.g. openid-client. It works out of the box. If you’re getting access denied then you’re not asking for any scopes (and not resolving any default ones).
