### ISSUE TITLE
How to make prompts after consent mandatory?

### ISSUE THREAD

**Issue by acorbel** [panva/node-oidc-provider#703]
Hello,

I'm trying to add another required prompt after the log in with the following policy:
```js
// copies the default policy, already has login and consent prompt policies
const interactions = policy();

// create a requestable prompt with no implicit checks
const configureAccountPrompt = new Prompt({
    name: 'configure',
    requestable: true,
});

interactions.add(configureAccountPrompt);

...
const config = {
       [...]
        interactions: {
            policy: interactions,
        },
};
```

According to the [prompt helper](https://github.com/panva/node-oidc-provider/blob/1a68bd8348126818982c65e5bbc62de1736ab411/lib/helpers/interaction_policy/prompt.js#L42), a required check is created as the `requestable` attribute is set to true.

When calling `interactionFinished` after the consent screen, the overall process is considered resolved and the authorization code is given to the end user.
After consent screen, the result is the object below and the configure attribute is not set (as the prompt has never been showed).
```js
{
    login: {
        account: account.id,
    },
    consent: {
        rejectedScopes: [],
        rejectedClaims: [],
        replace: false,
    }
}
```

Am I missing a thing with the requestable prompt after the consent prompt? 
Thank you!

**Comment by panva** [comment]
> How to make prompts after consent mandatory?

The Prompt instance needs some `Check`s that will resolve to true when you want to raise them. https://github.com/panva/node-oidc-provider/blob/master/lib/helpers/interaction_policy/prompt.js#L4-L7

> According to the prompt helper, a required check is created as the requestable attribute is set to true.

No, `requestable` means clients can include the prompt name in the `prompt` parameter. Not that it is required. `oidc.prompts.has(name) && oidc.promptPending(name)` this means "does prompts parameter include `name`? AND was it already resolved in this authorization request".

**Comment by acorbel** [comment]
Ok. Crystal clear!
Thank you for your incredible work!
