### ISSUE TITLE
How can I auto approve scopes to applications in first party?

### ISSUE THREAD

**Issue by clairtonluz** [panva/node-oidc-provider#704]
I wanna that my application not need scope approvation in my oauth. How can I do it?

**Comment by panva** [comment]
@clairtonluz see the expandable details in https://github.com/panva/node-oidc-provider/blob/v6.23.5/docs/README.md#interactionspolicy

basically you'll have to add checks that never resolve to true but automatically call e.g. `ctx.oidc.session.promptedClaimsFor` to add the scope you want always consented to when the client is a first party one.

To set a client as a first party, use https://github.com/panva/node-oidc-provider/blob/v6.23.5/docs/README.md#extraclientmetadata

**Comment by clairtonluz** [comment]
Tks

**Comment by bslipek** [comment]
Step by step solution: 

1. Create an additional check. Create file `firstPartyClientAutoConsent.ts`

```ts
import Koa from 'koa'
import { interactionPolicy } from 'oidc-provider'

const { Check } = interactionPolicy

export const firstPartyClientAutoConsent = () => new Check('first_party_client_auto_consent', '', 
  (ctx: Koa.Context) => {
    const { oidc } = ctx;

      if( oidc.client.firstParty ) {
        oidc.session.ensureClientContainer(oidc.client.clientId);
        oidc.session.promptedScopesFor(oidc.params.client_id, oidc.requestParamScopes);
        oidc.session.promptedClaimsFor(oidc.params.client_id, oidc.requestParamClaims);
      }

    return false;
});
```
This will auto-accept all scopes/claims when the client is firstParty.

2. Add new Check to `consent` prompt. Update your oidc-provider configuration:
```ts
import Koa from "koa";
import type { Configuration } from "oidc-provider";
import { interactionPolicy } from "oidc-provider";

import { firstPartyClientAutoConsent } from "./firstPartyClientAutoConsent";

const { base: policy } = interactionPolicy;
const interactions = policy();

interactions.get("consent").checks.add(firstPartyClientAutoConsent(), 0);

export const configuration: Configuration = {
  interactions: {
    policy: interactions,
  },
  // rest of the configuration
```

3. Allow the client to has `firstParty` flag. Update oidc-provider configuration:
```ts
{
...
extraClientMetadata: {
    properties: ["firstParty"],
    validator: (key, value, metadata) => {
      if (key === "firstParty") {
        metadata[key] = !!value;
      }

      return metadata;
    },
  },
...
}
```

4. Add flag to client config. Update oidc-provider configuration:
```ts
{
...
clients: [
    {
      ...
      firstParty: true,
    },
...
}
```

This works but maybe should I change something here?
