### ISSUE TITLE
In Typescript prompt.checks.get(reason) not exists

### ISSUE THREAD

**Issue by clairtonluz** [panva/node-oidc-provider#705]
in the docs https://github.com/panva/node-oidc-provider/blob/v6.23.5/docs/README.md#interactionspolicy 
in the session **modifying the default interaction policy** says

`// prompt.checks.get(reason) => returns a Check instance by its reason`

but when using typescript the method **get(reason)** not exists. It is outdate in the docs or in the types?

**Comment by panva** [comment]
It's just the types that don't include these methods. Feel free to open a PR.

**Comment by clairtonluz** [comment]
ok
