### ISSUE TITLE
Federated code grant

### ISSUE THREAD

**Issue by solaris765** [panva/node-oidc-provider#708]
I'm trying to implement a federated Azure AD login flow that maintains access to the Azure api.
So far the login flow works great.

The only thing that is really confusing me is where I should be storing the azure Bearer tokens (if at all).

My current thought is to add them to the session. But I'd like some guidance on if that is even a good idea and if so, how would I add them to the session payload?

**Comment by panva** [comment]
@solaris765 I can't provide guidance on this. You've got to make your own assessment.

You should devise your own way of storing data referenced to the session.

---

Or overload the `IN_PAYLOAD` static method on the Session model, add a property name, which you'll be assigning to, there and it'll be saved using your adapter. Use a non conflicting name tho.

**Comment by solaris765** [comment]
Ah, awesome. I wasn't sure whether or not overloading that method was inadvisable. 
Thank you.
