### ISSUE TITLE
Enforce PKCE for a SPA client

### ISSUE THREAD

**Issue by vdtn359** [panva/node-oidc-provider#709]
Hello, I am planning to use Authorization code flow with PKCE for a SPA client. Is it possible to enforce PKCE for these types of clients too? Currently, it is only enforced for native clients.

**Comment by panva** [comment]
There's no `application_type` designated that would indicate a SPA application. If you can identify them (e.g. through enforing a [custom client metadata](https://github.com/panva/node-oidc-provider/blob/v6.23.5/docs/README.md#extraclientmetadata)) then you can easily add listeners to [events](https://github.com/panva/node-oidc-provider/blob/v6.23.5/docs/events.md) (`authorization.accepted` and `interaction.started`) which checks the params and if PKCE is missing, throw an [InvalidRequest](https://github.com/panva/node-oidc-provider/blob/v6.23.5/lib/index.js#L7)
