### ISSUE TITLE
Processing https://client.example.com/callback#id_token ...

### ISSUE THREAD

**Issue by karlbateman** [panva/node-oidc-provider#71]
Hi @panva 

Quick question, I have the `node-oidc-provider` setup and running and I am now trying to implement the `node-openid-client` at the stage where I have authenticated correctly and I am returned the callback url of the client I am unable to process the parameters.

Perhaps I lack the understanding of the implementation or there is something I have missed, could you shed some light on this?

Regards,
K

**Comment by karlbateman** [comment]
Has this got something to do with needing to set `response_type=query`?

**Comment by panva** [comment]
perhaps i can offer you a more direct channel of communication, please check your email - there really isn't an issue with the libraries themselves here.

**Comment by karlbateman** [comment]
@panva That's great thank you
