### ISSUE TITLE
Adding custom properties to session

### ISSUE THREAD

**Issue by tmedanovic** [panva/node-oidc-provider#710]
Is there a way to set custom properties on the user session? Preferably assigning custom values in the `provider.interactionFinished` method and retrieving it later using `provider.Session.get`.

I am aware that `meta` property exists, but those properties are tied to the client.

Use case: Storing third party Idp session identifier so that I can end session on the external Idp before destroying user session.

**Comment by panva** [comment]
See https://github.com/panva/node-oidc-provider/issues/708#issuecomment-619236172

**Comment by tmedanovic** [comment]
@panva Can you help me a little bit? I tried overriding IN_PAYLOAD property on session model but I can't figure out how to save property to session that I returned in interaction result.

Overriding IN_PAYLOAD:

```
const IN_PAYLOAD = provider.Session.IN_PAYLOAD;

  Object.defineProperty(provider.Session, "IN_PAYLOAD", {
     get: function () { 
      return [...IN_PAYLOAD, "customProperty"];
     }
  });
```

Interaction finished:

```
var result = {
      login: {
        account: user.accountId,
        remember : false,
        ts: Math.floor(Date.now() / 1000)
      },
      consent: {},
      meta: {},
	  customProperty: '12345'
    }

return provider.interactionFinished(ctx.req, ctx.res, result);
```
I can't find the part of code that copies properties from Interaction to Session, is there such a code? When and how is session created?

**Comment by panva** [comment]
What gave you the idea that there is such a thing?

**Comment by tmedanovic** [comment]
@panva Seems like accountId is somewhere copied from interaction to session so I assumed there is such code.

Am I completely off?

**Comment by panva** [comment]
> Seems like accountId is somewhere copied from interaction to session so I assumed there is such code.

Again there's no such code in place that would copy properties off your interaction results onto the session.

You can do that yourself in an interaction policy, where you'll have `ctx.oidc.result` available.
