### ISSUE TITLE
Best practice for storing access/refresh tokens in database

### ISSUE THREAD

**Issue by fiznool** [panva/node-oidc-provider#712]
Apologies if this has been answered elsewhere - I found [this comment](https://github.com/panva/node-oidc-provider/issues/419#issuecomment-495754701) but not much else on the topic.

What is the best practice for storing the access/refresh tokens in the persistent store? Specifically, I'm wondering about encrypting the tokens so that a compromised database would not reveal tokens in plaintext.

Would you (for example) advocate using a symmetrical encryption algorithm to encrypt the data in the store before it is persisted? I see that the adapters in the example folder store the data in plaintext, and so wondered if this is really necessary or not.

**Comment by panva** [comment]
@fiznool this goes above and beyond my capacity to give advise on.

Part of the beauty of making storage your responsibility is just that.

**Comment by panva** [comment]
FWIW the [supporter](https://github.com/panva/node-oidc-provider?sponsor=1) slack workspace is where i'd be happy to dive deeper into that topic.

**Comment by fiznool** [comment]
Sure, I understand. As there are example stores, I wondered if this was in scope. But thanks for confirming that it isn’t.

**Comment by panva** [comment]
They're example so that devs get a starting point, a sense of the expected API contract.

**Comment by fiznool** [comment]
In case anyone is interested, I implemented the following in my persistent store adapter. My main motivation was to prevent a hypothetical database breach from leaking access and refresh tokens, and so I focussed on hashing and encrypting the relevant pieces of data in the database.

- In the `upsert` method:
  - if the record is 'grantable' (i.e. is an access token, refresh token, auth code or device token), the ID is the token itself, and is hashed using SHA256. Since the token is of high entropy (currently 258 bits for an opaque token) I decided that a straighforward hash is sufficient (there is no need for a salt since the original token is basically unguessable)
  - the `data` JSON blob is stringified and encrypted using AES-256 with a random initialisation vector and an environment-stored secret. This results in a base64 encoded string which is persisted to the database.
- In the `find`, `consume` and `destroy` methods:
  - if the the record is 'grantable' then the passed ID is first hashed using the same SHA256 algorithm so it can be looked up correctly
- In the `find`, `findByUserCode` and `findByUid` methods:
  - If a record is found with the passed ID, the `data` property is decrypted to a JSON object before being returned.

Here's some code that implements this, based on the Sequelize adapter from the examples folder. The hashing and encryption/decryption utilities were built using the [built-in node crypto module](https://nodejs.org/en/knowledge/cryptography/how-to-use-crypto-module/).

``` js
const { sha256Hash, makeEncryptor } = require('./crypto.utils');

const encryptor = makeEncryptor(process.env.OIDC_ENCRYPTOR_SECRET);

class SequelizeAdapter {
  asId(id: string) {
    return grantable.has(this.name) ? sha256Hash(id) : id;
  }

  async upsert(id, data, expiresIn) {
    const dataEncrypted = await encryptor.encrypt(data);
    await this.model.upsert({
      id: this.asId(id),
      data: dataEncrypted,
      ...(data.grantId ? { grantId: data.grantId } : undefined),
      ...(data.userCode ? { userCode: data.userCode } : undefined),
      ...(data.uid ? { uid: data.uid } : undefined),
      ...(expiresIn ? { expiresAt: new Date(Date.now() + (expiresIn * 1000)) } : undefined),
    });
  }

  async find(id) {
    const found = await this.model.findByPk(this.asId(id));
    if (!found) return undefined;
    const data = encryptor.decrypt(found.data);
    return {
      ...data,
      ...(found.consumedAt ? { consumed: true } : undefined),
    };
  }

  async findByUserCode(userCode) {
    const found = await this.model.findOne({ where: { userCode } });
    if (!found) return undefined;
    const data = encryptor.decrypt(found.data);
    return {
      ...data,
      ...(found.consumedAt ? { consumed: true } : undefined),
    };
  }

  async findByUid(uid) {
    const found = await this.model.findOne({ where: { uid } });
    if (!found) return undefined;
    const data = encryptor.decrypt(found.data);
    return {
      ...data,
      ...(found.consumedAt ? { consumed: true } : undefined),
    };
  }

  async destroy(id) {
    await this.model.destroy({ where: { id: this.asId(id) } });
  }

  async consume(id) {
    await this.model.update({ consumedAt: new Date() }, { where: { id: this.asId(id) } });
  }
}
```

After a bit of testing all seems to work well - the client receives the plaintext tokens whereas the database stores a hashed version of them, and all data is encrypted when stored.
