### ISSUE TITLE
Setting custom end_session_endpoint?

### ISSUE THREAD

**Issue by tmedanovic** [panva/node-oidc-provider#713]
Is it possible to set custom `end_session_endpoint` in openid-configuration document?

I have a custom endpoint since I have to end session on a third-party provider before ending session on my provider? (I am redirecting to session/end after)

**Comment by panva** [comment]
Yes, https://github.com/panva/node-oidc-provider/blob/v6.24.0/docs/README.md#pre--and-post-middlewares

**Comment by tmedanovic** [comment]
@panva Can you clarify how can I put different URL in the discovery document openid-configuration document? Should I intercept request to openid-configuration? Change the document and return it?

**Comment by panva** [comment]
Yes.

```js
provider.use(async (ctx, next) => {
  await next();

  if (ctx.status === 200 && ctx.oidc.route === 'discovery') {
    ctx.body.end_session_endpoint = '...'
  }
})
```

**Comment by tmedanovic** [comment]
@panva Now I'm wondering would it be better to execute pre middleware an leave URL as is.
Anyway, something to think about. Thanks alot!

**Comment by panva** [comment]
I don't see how pre-middleware would be of any help.

You seem to be a long time user of the library

<img width="519" alt="Screenshot 2020-05-04 17 10 56" src="https://user-images.githubusercontent.com/241506/80981427-3e1bc780-8e2a-11ea-8b8f-4aa4fa9ea621.png">

please consider [supporting](https://github.com/panva/node-oidc-provider?sponsor=1) the library if it provides value to you or your company and this and the previous support was of help to you. Supporting the library means, amongst other things, that such support will be available to you in the future.

**Comment by tmedanovic** [comment]
@panva Executing the third party logout before end session is called, as I mentioned in the first question.

You have done wonderful work on the library, we are discussing it!

**Comment by panva** [comment]
> Executing the third party logout before end session is called, as I mentioned in the first question.

Ah, got it.
