### ISSUE TITLE
Is there a reason for not exporting the type for the Client object received by the 'backchannel.error' handler?

### ISSUE THREAD

**Issue by andyjdavis** [panva/node-oidc-provider#715]
The 'backchannel.error' handler receives various props include client. The other props are either primitives or the type definition is readily available.

A small code example.

import Provider, { errors, KoaContextWithOIDC } from 'oidc-provider'

const prvdr = new Provider(`${config.publicUrl}/oidc`, {...})

prvdr.on('backchannel.error', (ctx: KoaContextWithOIDC, err: Error, client: Client, accountId: string, sid: string) => {...})

The type Client isnt exported so to get it I had to use this workaround as described at https://github.com/panva/node-oidc-provider/issues/569#issuecomment-551058463.

type Client = InstanceType<Provider['Client']>

Here is a small PR that simply exports the Client class. https://github.com/panva/node-oidc-provider/pull/714 Feel free to merge or decline as you see fit :)

**Comment by panva** [comment]
The types follow the library interface, Client is not an exported Class constructor.
