### ISSUE TITLE
select_account example, missing logout prompt ?

### ISSUE THREAD

**Issue by adriencohen** [panva/node-oidc-provider#720]
I was looking at the [example](https://github.com/panva/node-oidc-provider/tree/master/example) for setting up a `select_account` interaction and from what I understand it's missing a logout prompt.

I supposed that the logout prompt should destroy all the tokens attached to the session and the interaction attached to it could just show the login form. It shouldn't be to much of a hassle if I'm right.

But what I don't get the most is why are we adding `login` instead of `logout` if there is stuff in `interaction.params.prompt`

```(js)
if (req.body.switch) {
        if (interaction.params.prompt) {
          const prompts = new Set(interaction.params.prompt.split(' '));
          prompts.add('login');
          interaction.params.prompt = [...prompts].join(' ');
        } else {
          interaction.params.prompt = 'logout';
        }
        await interaction.save();
      }
```
(https://github.com/panva/node-oidc-provider/blob/master/example/routes/express.js)

Could you explain it further please ?

**Comment by panva** [comment]
Erm, it should actually say `login`.
