### ISSUE TITLE
incorrect returnTo

### ISSUE THREAD

**Issue by doowb** [panva/node-oidc-provider#722]
**Describe the bug**

I'm implementing `oidc-provider` using the "mount point" technique for `express` at `/login/oauth` and during development I passed `http://localhost:4242` as the `issuer` to `new Provider()`. Everything seemed to be working fine at this point and the `returnTo` hostname was `localhost` as expected.

Once, I deployed my code to kubernetes, I noticed that the `hostname` is resolving to the internal kubernetes `hostname` for the service pointing to the pod my app is running in. I thought this was due to forgetting to change the `issuer`, so I corrected the issuer, but the `returnTo` url is still using the internal kubernetes hostname.

**To Reproduce**
Provider and Client configuration: (inline or gist)

https://gist.github.com/doowb/7d98fa0e3a61d22a557149fa9234711b

Steps to reproduce the behaviour:

Use following url once deployed:

https://my-issuer.example.com/login/oauth/authorize?client_id=foo&redirect_uri=https%3A%2F%2Foidcdebugger.com%2Fdebug&scope=openid%20email&response_type=id_token&response_mode=form_post

**Expected behaviour**

I expect the `returnTo` to use the issuer (or at least provide some other way to control that).
I updated the `issuer` due to seeing [this line of code](https://github.com/panva/node-oidc-provider/blob/051f58819e8f3a8477af036d1d04d08ad6bfe3e2/lib/provider.js#L136)

**Environment:**
 - oidc-provider version: `v6.26.1`
 - node version: `v12.16.3`

**Additional context**

 - [ ] the bug is happening on latest oidc-provider too.
 - [ ] i have tried DEBUG (see README) and can see the issue is with the provider and not my code.
 - [x] i have searched the issues tracker on github for similar issues and couldn't find anything related.
 - [x] i have searched the [FAQ](https://github.com/panva/node-oidc-provider/blob/master/docs/README.md#faq) and couldn't find anything related.

**Comment by doowb** [comment]
Update: I did see [this issue](https://github.com/panva/node-oidc-provider/issues/350) so I'm using `interactionResult` now instead of `interactionFinished` and doing the redirection myself.

I'm able to get the correct url by doing something like this:

```js
const OIDC_ISSUER = 'https://my-issuer.example.com';
let returnTo = await provider.interactionResult(req, res, result);
const url = new URL(returnTo);
const newUrl = new URL(url.pathname, OIDC_ISSUER);
returnTo = newUrl.toString();
// do redirection logic
```

**Comment by panva** [comment]
See the sample in https://github.com/panva/node-oidc-provider/blob/master/docs/README.md#trusting-tls-offloading-proxies

You need to be setting some headers from your proxy/load balancer that you’re missing. 

This is not oidc-provider specific, this is webapp production quazi standard practice.

Always following the issuer value only would disqualify a whole slew of deployments and use cases so instead, you’re responsible for forwarding the real used url (host, proto) via commonly used upstream headers and making sure to only listen on the hostname you want.

**Comment by doowb** [comment]
Thanks, that worked!

I did read that section when I first went through the docs, but I didn't make that connection and search for the correct terms because I was too focused on the `returnTo` value.

**Comment by panva** [comment]
Please consider [supporting](https://github.com/panva/node-oidc-provider?sponsor=1) the library if it provides value to you or your company and this support was of help to you. Supporting the library means, amongst other things, that such support will be available in the future.
