### ISSUE TITLE
Support for additional scopes in refresh token grant

### ISSUE THREAD

**Issue by chungath** [panva/node-oidc-provider#723]
**Is your feature request related to a problem? Please describe.**
Currently the refresh token grant supports scope parameter. However the scopes can only be the same or a subset of the original scopes issued.

We need a mechanism where the token gets refreshed with additional scopes compared to the original list of scopes in the access token. 

**Describe the solution you'd like**
The solution could be to implement a configuration updateAccessTokenClaimsOnRefresh - similar to how it is done in [identityserver4](https://identityserver4.readthedocs.io/en/latest/topics/refresh_tokens.html).

**Describe alternatives you've considered**

**Additional context**

 - [x] i have searched the configuration section for this feature and couldn't find it
 - [x] i have searched the issues tracker on github for similar requests and couldn't find anything related.

**Comment by panva** [comment]
> We need a mechanism where the token gets refreshed with additional scopes compared to the original list of scopes in the access token.

That goes against the 6749 rfc, sorry.

**Comment by chungath** [comment]
Sorry, i made a mistake when writing the feature request. 

What I meant was updating the claims(not scopes) in the access token during refresh - updateAccessTokenClaimsOnRefresh - similar to how it is done in  [identityserver4](https://identityserver4.readthedocs.io/en/latest/topics/refresh_tokens.html).

Is that possible?

**Comment by panva** [comment]
I don't think it's possible with a specific API, but you can certainly hook into [these](https://github.com/panva/node-oidc-provider/blob/v6.26.1/lib/actions/grants/refresh_token.js#L164) helpers/prototype methods.
