### ISSUE TITLE
Already given grant appears as a new grant when session is expired

### ISSUE THREAD

**Issue by jogee** [panva/node-oidc-provider#724]
Hi @panva,

Great library, great work!

What I wanted to ask you is that when you login in now and you are presented the consent screen, the first time he shows it as a new grant. After that you can confirm already given grant type, but with my current configuration it only works when a session is found. When the session is expired it asks my consent again as if it's a new grant even though I already granted the application.

Is this a configuration issue on my side or is this by design / specification?

Thanks!

**Comment by panva** [comment]
This is by design, for now granted scopes and claims are stored only in the session - as you can see in your db obviously.

You can redefine the interaction policy and check for scopes/claims being granted elsewhere.

In the upcoming v7.x major release this will be much simpler to achieve tho.

**Comment by honzapatCZ** [comment]
V 7.x when?

**Comment by panva** [comment]
> V 7.x when?

When it's ready.

**Comment by honzapatCZ** [comment]
Iam really looking for this feature together with handling of showing consent ui when app requests different scoprs than last time and per application allowed scopes

**Comment by panva** [comment]
But you can already achieve all of that. You just need to be more involved.

**Comment by honzapatCZ** [comment]
So its already possible? Awesome. I almost started to look into identity server 4
