### ISSUE TITLE
[Question]: federated endpoint HTTP method

### ISSUE THREAD

**Issue by twawszczak-wr** [panva/node-oidc-provider#725]
Hi @panva, I would like to ask, is there any - security or another - reason, why are you exposing `federated` endpoint with post method?

https://github.com/panva/node-oidc-provider/blob/051f58819e8f3a8477af036d1d04d08ad6bfe3e2/example/views/repost.ejs#L22

**Comment by panva** [comment]
Because it’s reposting an id_token > containing private fields that should stay away from browser history, webserver logs etc. So, privacy.
