### ISSUE TITLE
issue access tokens from a 3rd party (cognito)

### ISSUE THREAD

**Issue by dlydiard** [panva/node-oidc-provider#727]
I'm looking into replacing the AWS Cognito Hosted UI with node-oidc-provider. Unfortunately, the Cognito API does not support returning an Authorization Code to exchange with their /token endpoint unless you use their hosted UI. When you authorize with Cognito their API returns the id/refresh/access tokens. This means node-oidc-provider will have to handle the auth code/token exchange and refreshes instead of AWS's endpoints.

Is there a way with node-oidc-provider.to issue your own id/refresh/access tokens? Is there a proper way to override/intercept these values before it gets to my custom dynamodb adaptor class? We still want to use Cognito integration with API Gateway and their infrastructure for handling password resets, verification, MFA, etc 

Also, is there a way to override the reported endpoints in the well-known/openid-configuration output? There might be some opportunity for us to still take advantage of some the Cognito endpoints.

Thanks for creating such an involved project!

**Comment by panva** [comment]
Majority of what you’re asking is out of scope, this is a standalone server, not a shim. 

As far as overloading endpoint responses, search the issue tracker this has been asked several times already. 

Apologies for not having more concrete responses at this time, circumstances...
