### ISSUE TITLE
Can't overwrite default interaction routes

### ISSUE THREAD

**Issue by ViktorSimko** [panva/node-oidc-provider#728]
I'm trying to use oidc-provider in a fastify app.
This is how my code looks like roughly:

```
const fastify = require('fastify')(fastifyConfig)
const oidc = new Provider(ISSUER, configuration)

fastify.register(require('../routes/auth/Auth'), {})

fastify.use(oidc.callback)
```

`routes/auth/Auth.js`:
```
module.exports = function (fastify, opts, next) {

	fastify.route({
		method: 'GET',
		url: '/interaction/:uid',
		handler: async (request, reply) => {

			return {result: 'OK'}
		}
	})

	next()
}
```

With this code, the `oidc` instance's interaction methods are called, not the ones I register.
I have also tried registering the routes after `fastify.use(oidc.callback)` line.

If I remove that line, my registered route gets called.
With the callback registered I get this error when any other route is called:

```
{
  "error": "invalid_request",
  "error_description": "unrecognized route or not allowed method (GET on /other)"
}
```

**Comment by panva** [comment]
And the `configuration`?

**Comment by ViktorSimko** [comment]
This is the config:

```
{
	features: {
		introspection: { enabled: true },
		revocation: { enabled: true },
	},
	formats: {
		AccessToken: 'jwt',
	},
	clients: [
		{
			client_id: 'foo',
			client_secret: 'bar',
			redirect_uris: ['http://lvh.me:8080/cb'],
		}
	],
	pkce: {
		methods: [
			'S256'
		],
		required: (ctx, client) => {
			return true
		}
	}
}
```

**Comment by panva** [comment]
And this warning in the console?

```
WARNING: a quick start development-only feature devInteractions is enabled, you are expected to disable these interactions and provide your own
```

You should [disable](https://github.com/panva/node-oidc-provider/blob/v6.27.0/docs/README.md#featuresdevinteractions) the default interactions.

**Comment by panva** [comment]
And, being unfamiliar with fastify here, circumvent whatever router matching they have. This works for me, i get the `OK` rendered when i hit `http://localhost:3000/oidc/auth?client_id=foo&response_type=id_token&nonce=foo&scope=openid`

```js
const fastify = require('fastify')();

fastify.route({
	method: 'GET',
	url: '/interaction/:uid',
	handler: async (request, reply) => {
		return { result: 'OK' }
	}
})

const { Provider } = require('./lib');

const oidc = new Provider('https://op.panva.me/oidc', {
  clients: [
    {
      client_id: 'foo',
      token_endpoint_auth_method: 'none',
      grant_types: ['implicit'],
      response_types: ['id_token'],
      redirect_uris: ['https://jwt.io'],
    },
  ],
  features: {
    devInteractions: { enabled: false },
  },
});

fastify.use(oidc.callback);

fastify.listen(3000);
```

**Comment by ViktorSimko** [comment]
Thanks!

**Comment by panva** [comment]
Please consider [supporting](https://github.com/panva/node-oidc-provider?sponsor=1) the library if it provides value to you or your company and this and the previous support was of help to you. Supporting the library means, amongst other things, that such support will be available in the future.
