### ISSUE TITLE
Restoring scopes and claims

### ISSUE THREAD

**Issue by rossholdway** [panva/node-oidc-provider#729]
Hi Panva,

I'm trying to understand how best to restore scopes and claims that a user has already been prompted for, and approved, in order to avoid having the user re-approve / see the consent screen on every login to the same client.

My understanding so far is that I'd need to set `promptedScopesFor` and `promptedClaimsFor` however I'm not sure where best to call these methods in order to 'restore' the data...

For example, currently I plan to save to the users account (external SQL DB) that they have been previously prompted (by this client) with scopes A, B and C (and approved them) within the POST /confirm interaction for the consent page, but at what point would I call something like the following?

```javascript
...
const promptedScopes = await db.getAccount([sub]).getPromptedScopes();
oidc.session.promptedScopesFor(oidc.client.clientId, promptedScopes);
...
```

I'd like to restore the `promptedScopesFor` and `promptedClaimsFor` to the session before the consent check is rerun....

Any guidance would be really appreciated.

**Comment by panva** [comment]
You would call this in your interactions.policy configuration rules.

**Comment by panva** [comment]
Yeah, you can certainly do that. Great observation!
