### ISSUE TITLE
SSO using Session Management

### ISSUE THREAD

**Issue by tquackenbush** [panva/node-oidc-provider#730]
Hello,

I'm attempting to implement a SSO solution across multiple replying parties against our node-oidc-provider instance. From what I understand this could be done using the draft Session Management features of OIDC. I would like to use a 'silent login' (sending prompt=none in the login request) through the relying party Session Management iframes to check if the user has already authenticated to the provider. The problem I'm running into is that our node-oidc-provider instance is requiring consent if the user has not already authenticated with the new relying party client_id. This prevents checking for an existing global session if the user is coming from a new unauthenticated relying party. The code triggering a check for an existing client_id specific session on the provider seems to be in the [Consent Prompt](https://github.com/panva/node-oidc-provider/blob/master/lib/helpers/interaction_policy/prompts/consent/client_not_authorized.js#L5).

My question is, is it possible to skip the consent checks in this scenario? Either for all client_ids or a specific list of trusted relying parties? Is this even good practice?

Some additional info...
I'm using the [oidc-client-js example relying party](https://github.com/IdentityModel/oidc-client-js/tree/dev/samples/VanillaJS) for testing this flow, and reading about the [Auth0 provider](https://auth0.com/docs/api-auth/tutorials/silent-authentication) flows for best practices.

Thank you in advance for your advice.

**Comment by panva** [comment]
Session Management iframes are not for prompt=none authorization requests. Session Management is not for SSO, it’s for checking session state after having the client already undergone authorization. 

As far as the consent prompt, see the interactions policy configuration and adjust it to whatever fits your case. 

I won’t speak to best practice here.
