### ISSUE TITLE
Trigger authentication flow from external source

### ISSUE THREAD

**Issue by MikaelSoderstrom** [panva/node-oidc-provider#736]
Hello,

I am currently writing an integration against a system using [IMS-LTI 1.0](http://www.imsglobal.org/activity/learning-tools-interoperability) which is using OAuth 1.0.

When opening an link from that system, an post is made with all information about the user (and also OAuth data such as the signature). I can read all information and parse the relevant user data, but now I would want to automatically sign in that user based on the data that came from the other system.

The problem I am having is that since I haven't initiated any interactions via the authorize endpoint, I have no interaction to finish. I am going to have an URL where the user will be redirected after login, but that URL are dependent on the data from the posted body.

So my question is: how can I create a new interaction manually, and then finish it in the same flow?

Thanks

**Comment by panva** [comment]
You can't "create an interaction" manually. You can establish an OP session externally through `setProviderSession`.

**Comment by panva** [comment]
Please consider [supporting](https://github.com/panva/node-oidc-provider?sponsor=1) the library if it provides value to you or your company and this and the previous support was of help to you. Supporting the library means, amongst other things, that such support will be available in the future.
