### ISSUE TITLE
Record user IP address as claim in ID token

### ISSUE THREAD

**Issue by major-mann** [panva/node-oidc-provider#737]
How could I go about storing the user's IP address during the interactions so I can add it as a claim to the ID token. I don't appear to be able to modify the access token claims (I am on version 5) and it seems the sessions (as documented) are different

**Comment by panva** [comment]
@major-mann there is a way for sure in v6, with the last minor for v5.x released over 2 years ago i won't be revisiting it to confirm, but i have a hunch it lacks the necessary helpers to accomodate.

**Comment by panva** [comment]
You seem to be a long time user of the library, please consider [supporting](https://github.com/panva/node-oidc-provider?sponsor=1) the library if it provides value to you or your company and this and the previous support was of help to you. Supporting the library means, amongst other things, that such support will be available in the future. Given sufficient sponsorship I can help you out with v6.x upgrade as well as guiding you to implement this feature.
