### ISSUE TITLE
Question: Access allowed audiences in custom grant type implementation

### ISSUE THREAD

**Issue by rockebee** [panva/node-oidc-provider#738]
Hi,
I'm about to implement an use case for custom grant type [OAuth 2.0 Token Exchange](https://www.rfc-editor.org/rfc/rfc8693.html), and trying to setup/create new token set according to [the docs](https://github.com/panva/node-oidc-provider/tree/01843ced952b3e986489b6fc1a7bbec68a26ca32/docs#custom-grant-types). However, while taking a look into the existing ```lib/actions/grants``` implementations, I have seen that the audiences are set by referencing the ```audiences``` function, which probably relates to the provider configuration, e. g. for ```lib/actions/grants/authorization_code.js```:
```
at.setAudiences(await audiences(ctx, account.accountId, at, 'access_token'));
```
Now it seems that from "outside" the provider library I cannot access the initially set provider configuration, as with (mock-code only)
```
// initialization
const oidcp = require('oidc-provider');
const provider = new oidcp(this.issuer, { 'audiences: async (ctx, sub, token, use) => { return 'my-audience'; }});

// register custom grant type
const parameters = [
    'audience', 'resource', 'scope', 'requested_token_type',
    'subject_token', 'subject_token_type',
    'actor_token', 'actor_token_type'
];
const allowedDuplicateParameters = ['audience', 'resource'];
const grantType = 'urn:ietf:params:oauth:grant-type:token-exchange';
const tokenExchangeHandler = async function(ctx, next) {
    // [...]
    // create AT
    const {
            AccessToken, IdToken, RefreshToken, ReplayDetection
    } = ctx.oidc.provider;
    const at = new AccessToken({
        // ...
    });
    // [...]
    // let audiences = ctx.oidc.provider.??? // <= this is the place I'm failing
    // at.setAudiences(await audiences(ctx, account_id, at, 'access_token'));
    ctx.oidc.entity('AccessToken', at);
    const accessToken = await at.save();
}
provider.registerGrantType(grantType, tokenExchangeHandler, parameters, allowedDuplicateParameters);
```

Is there anything obvious I'm missing?
Would be great if you could guide me how to proceed here.
Many thanks!

**Comment by panva** [comment]
well, you either have a custom audiences function in which case you can call it because - well, you have the reference for it, or you don't need to call this now, do you? (given the default just returns undefined)

**Comment by panva** [comment]
Please consider [supporting](https://github.com/panva/node-oidc-provider?sponsor=1) the library if it provides value to you or your company and this support was of help to you. Supporting the library means, amongst other things, that such support will be available in the future.

**Comment by rockebee** [comment]
Hi @panva,
thx for quick reply. I guess I understood what you meant and of course I'm aware there are workarounds for getting/filling the ```aud``` claim, however keep in mind that of course my mock-example below is a very shortened one. Obviously a real-world application is much more complex in terms of module-splits and e. g. the place where the ```audiences``` method is defined (and from where it is added to the provider instance configuration), and where finally the token exchange takes place - due to the ```ctx``` parameter in the registered grantType function call one has direct access to the provider instance (```ctx.oidc.provider```), but obviously not to the provider configuration. It is just about having a straight-forward and clean access to the method reference that is known to be used by the lib itself versus referencing/requiring a method which hopefully remains the same source also in one year, without someone else having changed the provider configuration setup.

So my question hence was basically about: Is there any way to access the provider configuration from outside the library? Or is really the only way to somehow pass around either the reference to the ```audiences``` method to the registered grantType method or duplicating ```require```s?

**Comment by panva** [comment]
Intentionally there isn’t, in this instance the configuration object just yields back whatever you’ve set, but in many instances the results are pre-processed and private for reasons i won’t go into.
