### ISSUE TITLE
Error "no client authentication mechanism provided" when passing header transfer-encoding chunked

### ISSUE THREAD

**Issue by lewiscxa** [panva/node-oidc-provider#739]
**Describe the bug**
This change https://github.com/panva/node-oidc-provider/commit/d5148ad6149672cf93851f0e0e6d72ddedd09ec3 is actually causing an issue with Transfer-Encoding: chunked passed into requests to the token route `/token` on flow client credentials. I tried to log the variable `ctx.request.length` (`lib/shared/selective_body.js :11`) and it's always undefined when the above header is passed.

**To Reproduce**
Provider and Client configuration: (inline or gist)
Not necessary

Steps to reproduce the behaviour:
```
curl --location --request POST 'localhost/token' \
--header 'Content-Type: application/x-www-form-urlencoded' \
--header 'Transfer-Encoding: chunked' \
--data-urlencode 'grant_type=client_credentials' \
--data-urlencode 'client_id=clientId' \
--data-urlencode 'client_secret=clientSecret'
```

**Expected behaviour**
return status 200

**Environment:**
 - oidc-provider version: v6.17.3 +
 - node version: v12.13.0

**Additional context**
It's working with v6.17.2-

**Logs**
```
{"error":"invalid_request","error_description":"no client authentication mechanism provided"}
```

**Comment by panva** [comment]
@lewiscxa thank you for raising this ⭐ i'm preparing a fix.

**Comment by panva** [comment]
`v6.27.3` released with the regression fixed. Note: in my test suite i can't validate this works properly when running "mounted". This might as well be a problem in the suite's orchestration, not sure and i don't have to look into it further.
