### ISSUE TITLE
Hook after oidc-provider:authentication:success

### ISSUE THREAD

**Issue by kareha** [panva/node-oidc-provider#740]
I would like to write a log about a successful login with accountId and clientId.

I looked at the pre&post middleware thing, but there is only the route "resume" that occurs after successful login. Is that correct?
And also I can't find the accountId there too.

Is there a better way where I can place my code or overwrite a function?

The same goes for logout.

Thanks a lot!

**Comment by panva** [comment]
> I would like to write a log about a successful login with accountId and clientId.

That's exactly what `authorization.success` [event](https://github.com/panva/node-oidc-provider/blob/v6.27.3/docs/events.md) is for, why can't you use that?

Furthermore you can easily use a post-action middleware hooking into resume and authorization routes. All details you want are under `ctx.oidc`. `ctx.oidc.client.clientId` as well as `ctx.oidc.account.accountId`
