### ISSUE TITLE
Example of dynamic clients without using registration endpoints

### ISSUE THREAD

**Issue by alanchrt** [panva/node-oidc-provider#741]
Hi, we have a list of clients in our db that we keep updated manually. There's no flow that makes sense for them to register themselves using the OIDC registration apis.

I saw mention that there may be a way to get a list of clients dynamically using an adapter, rather than passing them statically through the `clients` configuration prop. Are there any examples of this in action?

**Comment by panva** [comment]
There's no example but all you need to do is not provide them in the `clients[]` configuration array but instead resolve the adapter `.find()` method with the same object based on the `client_id` passed in as the `uid` argument. Use of a low TTL value cache - e.g. wrapping your db calls with something like `p-memoize` might make sense for these.

**Comment by panva** [comment]
Please consider [supporting](https://github.com/panva/node-oidc-provider?sponsor=1) the library if it provides value to you or your company and this support was of help to you. Supporting the library means, amongst other things, that such support will be available in the future.

**Comment by alanchrt** [comment]
Thanks so much for the reply. It's extremely helpful and would have taken me some time to chase down.
