### ISSUE TITLE
Wrong redirection on Sign-in button clic

### ISSUE THREAD

**Issue by GauthierEmilien** [panva/node-oidc-provider#742]
**Describe the bug**
Hi,
I think the auto-generated sign-in form must have `action` tag like `http://192.168.1.0:3000/interaction/:uid/login`.
I don't know why, I can't upload image here for now but if you go to Google Devtools and inspect the **sign-in** button. You will see no `login` in the url. 
Therefore, I can't get the password to connect to my own database because the app never go to login interaction.

**To Reproduce**
Launch an app with oidc-provider and launch an auth request. 
In Chrome, go to Devtools and inspect the login form, look at the `action` tag.

**Expected behaviour**
The form `action` tag should end with `login` like in [your example](https://github.com/panva/node-oidc-provider-example/blob/63c8628a3bbb06922a38d5965c19c9700a66fab3/03-oidc-views-accounts/views/login.ejs#L133)

**Environment:**
 - oidc-provider version: 6.27.3
 - node version: 12.18.1

**Additional context**
 - [x] the bug is happening on latest oidc-provider too.
 - [ ] i have tried DEBUG (see README) and can see the issue is with the provider and not my code.
 - [x] i have searched the issues tracker on github for similar issues and couldn't find anything related.
 - [x] i have searched the [FAQ](https://github.com/panva/node-oidc-provider/blob/master/docs/README.md#faq) and couldn't find anything related.

**Comment by panva** [comment]
There’s no autogenerated form, no bundled interactions that you should be re-using. Interactions are your land. Implement them whatever way you feel like.

**Comment by GauthierEmilien** [comment]
Oh okay, I didn't undestood the documentation like that, english isn't my main language.

Thank you for your response !
