### ISSUE TITLE
OIDC provider does not enforce client to use 'state' parameter

### ISSUE THREAD

**Issue by tamjidrahat** [panva/node-oidc-provider#744]
**Describe the bug**

**Security bug**: OIDC Provider does not enforce clients to use '_**state**_' parameter in authorization request, which is recommended by the specification (https://tools.ietf.org/id/draft-bradley-oauth-jwt-encoded-state-08.html) to avoid potential **CSRF attacks**. According to specification: 
"_**The Client MUST use the **state** parameter to encode both Cross Site Request Forgery protection and any other state information it wishes to preserve for itself regarding the authorization request.**_".

Currently, OIDC provider only processes the '_**state**_' parameter if it is provided within the request:
https://github.com/panva/node-oidc-provider/blob/dbc24dd1e0ef81000ecd7b513066a0e43d919209/lib/actions/authorization/process_request_object.js#L90). 

To avoid potential CSRF attacks, it should enforce client to use the _**state**_ parameter. In other words, grant request should be invoked if '_**state**_' is not provided by client.

**Comment by panva** [comment]
A client must does not translate to the server having to enforce. 

Clients can use any number of mechanisms to do CSRF, the one recommended is PKCE and within oidc nonce. 

I don’t see how enforcing any state value to be provided would be of any help if pkce or nonce is also used. 

That being said, you’re free to enforce that through any number of extensions points.
