### ISSUE TITLE
Does node-oidc-provider support token exchange (on-behalf-of flow)

### ISSUE THREAD

**Issue by bsorek** [panva/node-oidc-provider#746]
Hi,
Does this library support the token exchange flow as described here:

https://tools.ietf.org/html/draft-ietf-oauth-token-exchange-16#page-3

Thank you,
Ben Sorek

**Comment by panva** [comment]
Token Exchange is a framework. One that needs to be profiled. You can implement TX through the custom grant API.

**Comment by panva** [comment]
https://github.com/panva/node-oidc-provider/blob/master/docs/README.md#custom-grant-types
