### ISSUE TITLE
Cannot find Access Token

### ISSUE THREAD

**Issue by bsorek** [panva/node-oidc-provider#749]
Hi,
I am trying to implement the token exchange flow and added a custom grant. The flow essentially works - I can  exchange a token (tokenA) for a new token (tokenB) , however now I am trying to get a new access token (tokenC) based on tokenB . As far as I can tell this is supposed to be supported by the spec https://tools.ietf.org/html/rfc8693 as part of the chained delegation. 

The problem is that when I trying to exchange TokenB for TokenC I get the following error:
`not returning AccessToken OMBOZ4zurrGiBh9CSFsr8 because it is session bound and client's token and session grantId are now different `

I tried setting  `ctx.oidc.uid = at.grantId`, but that didn't work
This is the handler code:

```
async tokenExchangeHandler(ctx, next) {
        presence(ctx, 'subject_token');

        const conf = instance(ctx.oidc.provider).configuration();

        const {
            audiences,
        } = conf;

        const {
            Account, AccessToken, IdToken, ReplayDetection,
        } = ctx.oidc.provider;

        const subjectTokenValue = ctx.oidc.params.subject_token;

        const at = await AccessToken.find(subjectTokenValue);
        if(!at) {
            throw new InvalidGrant('access token not found');
        }

        if (at.isExpired) {
            throw new InvalidRequest('access token is expired');
        }

        const account = await Account.findAccount(ctx, at.accountId, at);
        if (!account) {
            throw new InvalidGrant('access token invalid (referenced account not found)');
        }


        // ctx.oidc.entity('Account', account);
        const scope = 'xyz'//TBD: set scope according to params
        const delegatedAt = new AccessToken({
            accountId: account.accountId,
            claims: at.claims,
            client: ctx.oidc.client,
            expiresWithSession: at.expiresWithSession,
            grantId: at.grantId,
            gty: at.gty,
            scope,
            sessionUid: at.sessionUid,
            sid: at.sid,
        });

        delegatedAt.setAudiences(await audiences(ctx, account.accountId, delegatedAt, 'access_token'));
        ctx.oidc.entity('AccessToken', delegatedAt);
        const accessToken = await delegatedAt.save();

        ctx.body = {
            access_token: accessToken,
            expires_in: delegatedAt.expiration,
            token_type: delegatedAt.tokenType,
        };

        await next();
    }

```
I am probably missing something here, just not sure what.

**Comment by bsorek** [comment]
Yes. However A and B have different client ids
TokenA: client_id = foo
TokenB: client_id = bar
TokenC: client_id = bar

**Comment by panva** [comment]
Okay, so you're switching clients somewhere. In that case this gets way more complicated and it should be failing on TokenA > TokenB already as far as i can tell.

Simplest solution is to detach the exchanged tokens from the session by setting the exchanged token's `expiresWithSession` to `false`. 

If you want to retain that binding it gets way more complicated and goes beyond my capacity to help here. Please consider [supporting](https://github.com/panva/node-oidc-provider?sponsor=1) the library with an appropriate tier to be invited to my slack for supporters where i can offer extended support.
