### ISSUE TITLE
'state' param not appended to 'post_logout_redirect_uri'

### ISSUE THREAD

**Issue by b0rza** [panva/node-oidc-provider#75]
The `state` parameter doesn't seem to be added to `this.oidc.session.logout` object used in ending the session flow. See here:
https://github.com/panva/node-oidc-provider/blob/f3f5b4978e94543fa8d5c8d02a1b157f2193d799/lib/actions/end_session.js#L76-L81

This causes the `post_logout_redirect_uri` to be built incorrectly - without the above parameter appended as part of the query.
(https://github.com/panva/node-oidc-provider/blob/f3f5b4978e94543fa8d5c8d02a1b157f2193d799/lib/actions/end_session.js#L148-L151)

Am I missing something or is this indeed a bug?

**Comment by panva** [comment]
Indeed a bug.
