### ISSUE TITLE
How can I do a similar login process like twitter.com

### ISSUE THREAD

**Issue by gigo1980** [panva/node-oidc-provider#750]
How can I create an embedded login Form into my Application and use the OAuth / OIDC flow in the Background? I know `password` grant type can do that, but I do not want to provide the client-secret and so on.

This is how twitter is doing that.
![image](https://user-images.githubusercontent.com/2462953/87201072-27985d80-c2fe-11ea-89ac-8d108f3e97cd.png)

**Comment by panva** [comment]
This is not the forum to ask such questions.
