### ISSUE TITLE
Register new client

### ISSUE THREAD

**Issue by alepekhin** [panva/node-oidc-provider#751]
I am trying to register client.

Request
http://localhost:4000/oidc/.well-known/openid-configuration
returns me
"registration_endpoint":"http://localhost:4000/oidc/reg"

I post to this address 
{
"client_id":"foo4",
"redirect_uris":["http://localhost:3000"] 
}
with content-type and accept as application/json
but got "Bad request" with empty response body

There is "Error: Parse Error" in oidc server log
but my json seems to be valid

What wrong I am doing?

**Comment by panva** [comment]
Debug log if you would.

**Comment by alepekhin** [comment]
Thank you, it works
