### ISSUE TITLE
Automatic end_session during resume when account in session does not match the account in interaction

### ISSUE THREAD

**Issue by chungath** [panva/node-oidc-provider#752]
Hello,

   We are running to a situation where end_session_confirm is being invoked from the library on an interaction resume where the account in interaction does not match the account in session at [resume.js#L64](https://github.com/panva/node-oidc-provider/blob/v6.23.2/lib/actions/authorization/resume.js#L64).

  In our case the token sub( which corresponds to account) claim contains the user email address and the tenant account. For example if the user ranjith@gmail.com logs into sales_account, the token subject would be `ranjith@gmail.com|sales_account`.

  The following is a use case where the problem occurs:

- User logs into App1(clientid1) to the account sales_account and the token is generated with sub claim as `ranjith@gmail.com|sales_account` . 
- Now, the same user logs into App2(clientid2)( in the same browser - reuses the session ) to the account dev_account. Here the oidc account is `ranjith@gmail.com|dev_account`.
- During the "Interaction" resume of App2, the library identifies that there exists a session and the account in that session(`ranjith@gmail.com|sales_account`) does not match the account in the interaction(`ranjith@gmail.com|dev_account`) and it initiates a logout at the code I specified above.

In our case, even though the account("sub" claim) is different, it belongs to the same user(same email address). Basically me as a user is logging into multiple tenant accounts and hence we do not want the library to logout from App1 during the interaction in this case.

Is there a way we can add a hook there to pass in the two account ids. The hook can be implemented at our end to compare the email from the account and return a boolean to specify whether the session should be ended in this case or not?

 Or if there is another way for handling this use case, please let me know.

Thanks,
Ranjith

**Comment by panva** [comment]
If you're changing the sub value, it's going to perform logout. There's no way around it.

1) You may consider using `pairwise` subject_type configuration for your applications. Essentially, your sub would be the bare email and you'd use the `pairwiseIdentifier` configuration helper to return a different sub with your tokens and userinfo responses.
2) Don't bind your tokens to session presence.

**Comment by panva** [comment]
You seem to be a long time user of the library, please consider [supporting](https://github.com/panva/node-oidc-provider?sponsor=1) the library if it provides value to you or your company and this and the previous support was of help to you. Supporting the library means, amongst other things, that such support will be available in the future.
