### ISSUE TITLE
Change devInteractions URL?

### ISSUE THREAD

**Issue by jasonboyle** [panva/node-oidc-provider#756]
I am using AWS to host my node app, so all URLs must begin with `/stage/`.  I have set devInteractions to true, and as a result I am redirected to `/interaction/<uid>` rather than `/stage/interaction/<uid>`.  I have attempted to customize this URL via interactions.url, but it appears this setting is ignored when devInteractions is true.  How can I change the devInteractions redirect URL to include the `/stage/` prefix?

**Comment by panva** [comment]
You must disable dev interactions and provide your own.

**Comment by jasonboyle** [comment]
I'm aware that it is ignoring the configuration but I would like to use devInteractions.  It appears this is not possible based on your response.  Could this be considered a feature request?

**Comment by panva** [comment]
No. I will not be spending cycles making sure dev interactions work on a variety of urls.
