### ISSUE TITLE
How to consume access_token and get user's account

### ISSUE THREAD

**Issue by GDreyV** [panva/node-oidc-provider#757]
Pretty silly question but I didn't find it in documentation. In my case application api and oidc is the same express app. So client got access_token and sent request to the api with `bearer {access_token}`. How I can get user's account by that token? I don't see any methods like that in provider. I suppose I should write (or reuse) middleware which will do something like `await provider.getUser(req)`.
In case if oidc and api are different applications I suppose I should use signed jwt token. How I can verify it without trip to the oidc? What methods should be called?

**Comment by panva** [comment]
Within the context of the provider you can get the access token entity with `provider.AccessToken.find`. Based on the `accountId` property of that object you can lookup your account in whatever way suits you, it's using your storage afterall.

**Comment by panva** [comment]
Please consider [supporting](https://github.com/panva/node-oidc-provider?sponsor=1) the library if it provides value to you or your company and this support was of help to you. Supporting the library means, amongst other things, that such support and the library itself will be available in the future.

**Comment by GDreyV** [comment]
Sorry, `provider.AccessToken.find` what? As I understand it requires token id but not the authorization header. I have request object and I need to get current user. What should I call for that? In other words I need to implement function auth.getUser(provider, req). What should be inside it?
It looks like `findAccount` might be helpful but I didn't find how to create instance of the `KoaContextWithOIDC`. `ctx = this.provider.app.createContext(req, res)` creates context which is slightly different and can't be used in that case.

**Comment by panva** [comment]
My answer stands. AccessToken find takes the token value, not just its internal identifier.

**Comment by GDreyV** [comment]
Sorry, maybe I should rephrase my question: how can I get `Account` with claims and everything else from `Request` object?

**Comment by panva** [comment]
Well, [this](https://github.com/panva/node-oidc-provider/issues/757#issuecomment-660651635).

After you've gotten the AccessToken, read its accountId property and perform account lookup. You don't need to use findAccount since, well, you own it anyway, you also don't need any contextual access to it since, well, you provide it in the first place. But well, `provider.Account.findAccount`.

**Comment by GDreyV** [comment]
That was my idea at first - to use `provider.Account.findAccount` but it requires as first parameter `context` of type `KoaContextWithOIDC` but I didn't find how to create such context. I was trying to use:
```
const ctx = this.provider.app.createContext(req, res);
```
but it returns something different and can't be used with `findAccount`. Sow how can I create `KoaContextWithOIDC`?

**Comment by panva** [comment]
Are you using the `ctx` in **your configured implementation** of findAccount? If not, just pass undefined. It seems like you just want to look up account by its identifier so i don't see the point of this whole discussion. Lookup the token, find out the accountId, then proceed using the tools at your disposal.

**Comment by GDreyV** [comment]
The point is that I was looking for a single method which I should call to get `Account` and claims from `Request`. Library already knows what kind of token to expect and how to obtain it as it's in client's configuration. Also it knows how to populate `Account` as I provided that function in configuration.

But I got your point. Thanks for help.
