### ISSUE TITLE
client_credentials flow client additional properties.

### ISSUE THREAD

**Issue by KindOf** [panva/node-oidc-provider#758]
Hello there and thank you for your great lib!

We have implicit flow configured for regular users. Their permissions are transferred from findAccount to RP via id_token. Also we need to implement service to service auth with client_credentials (jwt access_token) flow for statically registered clients. Is there a way to add custom metadata to jwt access_token (e. g. permission sets)?

**Comment by panva** [comment]
Why yes, two actually 

- https://github.com/panva/node-oidc-provider/blob/v6.28.0/docs/README.md#formatscustomizers
- https://github.com/panva/node-oidc-provider/blob/v6.28.0/docs/README.md#extraaccesstokenclaims

**Comment by panva** [comment]
Please consider [supporting](https://github.com/panva/node-oidc-provider?sponsor=1) the library if it provides value to you or your company and this support was of help to you. Supporting the library means, amongst other things, that such support and the library itself will be available in the future.
