### ISSUE TITLE
Callback url calls with no params (so passport authentication fail)

### ISSUE THREAD

**Issue by carolineBda** [panva/node-oidc-provider#759]
Hello,

I can not find what I implemented wrong, but after the login, when the callback url is called there is no query params passed to the client so it do not authenticates.

    const getUserByEmail = util.promisify(userModel.getUserByEmail);
    let oidc;
    jwksModel.getKeys(function (err, jwks) {
  
      if (err) logger.error('Error while getting JSON Web Key Set (jwks)', err);
      const configuration = {
        jwks,
        features: {
          devInteractions: {enabled: false},
          introspection: {enabled: true},
          revocation: {enabled: true},
          encryption: {enabled: true}
  
        },
        formats: {
          AccessToken: 'jwt',
        },
        claims: {
          email: ['email', 'email_verified'],
          phone: ['phone', 'phone_verified'],
          profile: ['lastName', 'firstName']
        },
        cookies: {
          long: {signed: true, maxAge: config.mongo.session.ttl * 1000},
          short: {signed: true, path: '/'},
          keys: [config.session.secretKey]
        },
        findAccount: async (ctx, email) => {
          const user = await getUserByEmail(email);
          if (!user) return;
          return {
            accountId: email,
  
            async claims() {
              return {
                sub: email,
                email: user.email,
                lastName: user.lastName,
                firstName: user.firstName,
                email_verified: user.emailVerified,
                phone_verified: user.phoneVerified
              };
            },
          };
        },
        discovery: {},
        interactions: {
          url(ctx) {
            return `/fr/api/oidc/registration/${ctx.oidc.uid}`;
          }
        },
        adapter: adapter,
        clients: [config.declarationLegal, config.ngrok]
      };
  
      oidc = new Provider(config.host, configuration);
      oidc.proxy = true;
  
      router.get('/registration/:uid', middlewares.setNoCacheHeader, async (req, res, next) => {
        try {
          const {prompt} = await oidc.interactionDetails(req, res);
          logger.info('OIDC registration', prompt.name);
          viewRenderer.renderApp(res, {noindex: true});
        } catch (err) {
          logger.error('Error on GET /registration/:uid', err);
          return next(err);
        }
      });
  
      // This is called happens straight after a separated call to the app's login endpoint
      router.post('/registration/:uid/login', async (req, res, next) => {
        try {
          const {uid, prompt, params} = await oidc.interactionDetails(req, res);
          logger.info('OIDC login', prompt.name, params, uid, req.params.uid);
          const result = {select_account: {}, login: {account: uid}};
          await oidc.interactionFinished(req, res, result, {mergeWithLastSubmission: false});
        } catch (err) {
          logger.error('Error on POST /registration/:uid/login', err);
          return next(err);
        }
      });
  
      router.post('/registration/:uid/confirm', middlewares.setNoCacheHeader, async (req, res, next) => {
        try {
          await oidc.interactionFinished(req, res, {consent: {}}, {mergeWithLastSubmission: true});
        } catch (err) {
          logger.error('Error on POST /registration/:uid/confirm', err);
          return next(err);
        }
      });
  
      router.use('/', oidc.callback);
    });

Would the problem come from the fact that the login is done in two times (one call to the login's app and then one call to the OIDC login endpoint ?

**Comment by panva** [comment]
[Debug logs](https://github.com/panva/node-oidc-provider/blob/master/README.md#debugging) if you wouldn’t mind. Also the client configurations.

**Comment by carolineBda** [comment]
Sure :

The client is configured like this :

    const issuer = new Issuer({
      issuer: 'https://xx.herokuapp.com/fr/api/oidc',
      authorization_endpoint: 'https://xx.herokuapp.com/fr/api/oidc/auth',
      token_endpoint: 'https://xx.herokuapp.com/fr/api/oidc/token',
      end_session_endpoint: 'https://xx.herokuapp.com/fr/api/oidc/session/end',
      jwks_uri: 'https://xx.herokuapp.com/fr/api/oidc/jwks'
    });
    
    const client = new issuer.Client({
      client_id: 'aa',
      client_secret: 'bb',
      redirect_uri: 'https://972e5cdf2af6.ngrok.io/fr/api/users/signed-in-gt',
      response_types: ['id_token']
    });
    
    const gtStrategy = new Strategy({client}, (tokenset, done) => {
      userModel.createGTUser(tokenset.claims(), done);
    });
    
    
    module.exports.useStrategies = function () {
      passport.use('oidc', gtStrategy);
    };

On the server side :

      ...
      adapter: adapter,
      clients: [{
        token_endpoint_auth_method: 'none',
        client_id: 'aa',
        client_secret: 'bar',
        grant_types: [
          'implicit'
        ],
        response_types: [
          'id_token'
        ],
        redirect_uris: [
          'https://972e5cdf2af6.ngrok.io/fr/api/users/signed-in-gt'
        ]
      }]
    };

In the chrome console, after the confirm consent, it calls the client callback which comes back to the /auth :
![](https://i.ibb.co/gTxK9LY/Screenshot-2020-07-20-at-20-19-20.png)

I see this error at the end :
![](https://i.ibb.co/C78sNmN/Screenshot-2020-07-20-at-20-18-31.png)

Log in the server :

**Comment by carolineBda** [comment]
Here are the debug logs on the server :

        Jul 20 20:18:00 xx app/web.1: 2020-07-20T18:18:00.251Z oidc-provider:authentication:interrupted uid=LxeYpC6e5Sin2YqwtI7a6 interaction=Interaction { returnTo: 'https://xx.herokuapp.com/fr/api/oidc/auth/LxeYpC6e5Sin2YqwtI7a6', prompt: { name: 'login', reasons: [ 'no_session' ], details: { max_age: undefined, login_hint: undefined, id_token_hint: undefined } }, lastSubmission: undefined, uid: 'LxeYpC6e5Sin2YqwtI7a6', params: { client_id: 'aa', nonce: 'hAOwp_RIuuq2Dbyg4CYzWJEWQO0yPj7npDLLcziyTjQ', redirect_uri: 'https://972e5cdf2af6.ngrok.io/fr/api/users/signed-in-gt', response_type: 'id_token', scope: 'openid', state: 'K2JcrlNcDOWVYItfuhZPVFGeS9SqPEJ6SeKzNnpgjKs' }, signed: undefined, session: undefined, kind: 'Interaction', jti: 'LxeYpC6e5Sin2YqwtI7a6', exp: 1595269680 }
        Jul 20 20:18:06 xx app/web.1: 2020-07-20T18:18:05.939Z oidc-provider:authentication:resumed uid=LxeYpC6e5Sin2YqwtI7a6 { select_account: {}, login: { account: 'LxeYpC6e5Sin2YqwtI7a6' } }
        Jul 20 20:18:06 xx app/web.1: 2020-07-20T18:18:05.950Z oidc-provider:authentication:interrupted uid=LxeYpC6e5Sin2YqwtI7a6 interaction=Interaction { returnTo: 'https://xx.herokuapp.com/fr/api/oidc/auth/LxeYpC6e5Sin2YqwtI7a6', prompt: { name: 'consent', reasons: [ 'scopes_missing' ], details: { scopes: [Object], claims: [Object] } }, lastSubmission: { select_account: {}, login: { account: 'LxeYpC6e5Sin2YqwtI7a6' } }, uid: 'LxeYpC6e5Sin2YqwtI7a6', params: { client_id: 'aa', nonce: 'hAOwp_RIuuq2Dbyg4CYzWJEWQO0yPj7npDLLcziyTjQ', redirect_uri: 'https://972e5cdf2af6.ngrok.io/fr/api/users/signed-in-gt', response_type: 'id_token', scope: 'openid', state: 'K2JcrlNcDOWVYItfuhZPVFGeS9SqPEJ6SeKzNnpgjKs' }, signed: [], session: { accountId: 'LxeYpC6e5Sin2YqwtI7a6', uid: 'rP_l0lR6JDRUTZC-MgiOe', cookie: 'JAsEDu7bmyiAcpWTYZsjA' }, kind: 'Interaction', jti: 'LxeYpC6e5Sin2YqwtI7a6', exp: 1595269685 }
        Jul 20 20:18:10 xx app/web.1: 2020-07-20T18:18:09.908Z oidc-provider:authentication:resumed uid=LxeYpC6e5Sin2YqwtI7a6 { select_account: {}, login: { account: 'LxeYpC6e5Sin2YqwtI7a6' }, consent: {} }
        Jul 20 20:18:10 xx app/web.1: 2020-07-20T18:18:09.910Z oidc-provider:authentication:accepted uid=LxeYpC6e5Sin2YqwtI7a6 Params { acr_values: undefined, claims_locales: undefined, client_id: 'aa', code_challenge: undefined, code_challenge_method: undefined, display: undefined, id_token_hint: undefined, login_hint: undefined, max_age: undefined, nonce: 'hAOwp_RIuuq2Dbyg4CYzWJEWQO0yPj7npDLLcziyTjQ', prompt: undefined, redirect_uri: 'https://972e5cdf2af6.ngrok.io/fr/api/users/signed-in-gt', registration: undefined, request: undefined, request_uri: undefined, response_mode: undefined, response_type: 'id_token', scope: 'openid', state: 'K2JcrlNcDOWVYItfuhZPVFGeS9SqPEJ6SeKzNnpgjKs', ui_locales: undefined }
        Jul 20 20:18:10 xx app/web.1: 2020-07-20T18:18:09.924Z oidc-provider:server_error uid=LxeYpC6e5Sin2YqwtI7a6 path=/auth/LxeYpC6e5Sin2YqwtI7a6 method=GET error=TypeError: Cannot read property 'claims' of undefined at idTokenHandler (/app/node_modules/oidc-provider/lib/actions/authorization/process_response_types.js:85:31) at /app/node_modules/oidc-provider/lib/actions/authorization/process_response_types.js:130:16 at Array.map (<anonymous>) at processResponseTypes (/app/node_modules/oidc-provider/lib/actions/authorization/process_response_types.js:123:69) at dispatch (/app/node_modules/koa-compose/index.js:42:32) at respond (/app/node_modules/oidc-provider/lib/actions/authorization/respond.js:16:21) at dispatch (/app/node_modules/koa-compose/index.js:42:32) at interactions (/app/node_modules/oidc-provider/lib/actions/authorization/interactions.js:74:11) at runMicrotasks (<anonymous>) at processTicksAndRejections (internal/process/task_queues.js:94:5) at async resumeAction (/app/node_modules/oidc-provider/lib/actions/authorization/resume.js:144:3) at async sessionHandler (/app/node_modules/oidc-provider/lib/shared/session.js:29:5) at async noCache (/app/node_modules/oidc-provider/lib/shared/no_cache.js:4:3) at async authorizationErrorHandler (/app/node_modules/oidc-provider/lib/shared/authorization_error_handler.js:55:7) at async ensureSessionSave (/app/node_modules/oidc-provider/lib/helpers/initialize_app.js:51:7) at async contextEnsureOidc (/app/node_modules/oidc-provider/lib/shared/context_ensure_oidc.js:4:5) at async /app/node_modules/oidc-provider/lib/helpers/initialize_app.js:243:5 at async errorHandler (/app/node_modules/oidc-provider/lib/shared/error_handler.js:23:7)
        Jul 20 20:18:10 xx app/web.1: 2020-07-20T18:18:09.924Z oidc-provider:server_error:trace TypeError: Cannot read property 'claims' of undefined
        Jul 20 20:18:10 xx app/web.1:     at idTokenHandler (/app/node_modules/oidc-provider/lib/actions/authorization/process_response_types.js:85:31)
        Jul 20 20:18:10 xx app/web.1:     at /app/node_modules/oidc-provider/lib/actions/authorization/process_response_types.js:130:16
        Jul 20 20:18:10 xx app/web.1:     at Array.map (<anonymous>)
        Jul 20 20:18:10 xx app/web.1:     at processResponseTypes (/app/node_modules/oidc-provider/lib/actions/authorization/process_response_types.js:123:69)
        Jul 20 20:18:10 xx app/web.1:     at dispatch (/app/node_modules/koa-compose/index.js:42:32)
        Jul 20 20:18:10 xx app/web.1:     at respond (/app/node_modules/oidc-provider/lib/actions/authorization/respond.js:16:21)
        Jul 20 20:18:10 xx app/web.1:     at dispatch (/app/node_modules/koa-compose/index.js:42:32)
        Jul 20 20:18:10 xx app/web.1:     at interactions (/app/node_modules/oidc-provider/lib/actions/authorization/interactions.js:74:11)
        Jul 20 20:18:10 xx app/web.1:     at runMicrotasks (<anonymous>)
        Jul 20 20:18:10 xx app/web.1:     at processTicksAndRejections (internal/process/task_queues.js:94:5)
        Jul 20 20:18:10 xx app/web.1:     at async resumeAction (/app/node_modules/oidc-provider/lib/actions/authorization/resume.js:144:3)
        Jul 20 20:18:10 xx app/web.1:     at async sessionHandler (/app/node_modules/oidc-provider/lib/shared/session.js:29:5)
        Jul 20 20:18:10 xx app/web.1:     at async noCache (/app/node_modules/oidc-provider/lib/shared/no_cache.js:4:3)
        Jul 20 20:18:10 xx app/web.1:     at async authorizationErrorHandler (/app/node_modules/oidc-provider/lib/shared/authorization_error_handler.js:55:7)
        Jul 20 20:18:10 xx app/web.1:     at async ensureSessionSave (/app/node_modules/oidc-provider/lib/helpers/initialize_app.js:51:7)
        Jul 20 20:18:10 xx app/web.1:     at async contextEnsureOidc (/app/node_modules/oidc-provider/lib/shared/context_ensure_oidc.js:4:5)
        Jul 20 20:18:10 xx app/web.1:     at async /app/node_modules/oidc-provider/lib/helpers/initialize_app.js:243:5
        Jul 20 20:18:10 xx app/web.1:     at async errorHandler (/app/node_modules/oidc-provider/lib/shared/error_handler.js:23:7)
        Jul 20 20:18:11 xx app/web.1: 2020-07-20T18:18:11.045Z oidc-provider:authentication:interrupted uid=yYosgRUA6A6qjsP1vdlCO interaction=Interaction { returnTo: 'https://xx.herokuapp.com/fr/api/oidc/auth/yYosgRUA6A6qjsP1vdlCO', prompt: { name: 'login', reasons: [ 'no_session' ], details: { max_age: undefined, login_hint: undefined, id_token_hint: undefined } }, lastSubmission: undefined, uid: 'yYosgRUA6A6qjsP1vdlCO', params: { client_id: 'aa', nonce: 'FNrEK9MC0T9fII50gQeu2YXpW3yiX56xvzAxMCd0Bds', redirect_uri: 'https://972e5cdf2af6.ngrok.io/fr/api/users/signed-in-gt', response_type: 'id_token', scope: 'openid', state: '3EN-2u03MDXY1hQBhlT0lh6rmkZDP6-Bam5IZjxJ--Y' }, signed: undefined, session: undefined, kind: 'Interaction', jti: 'yYosgRUA6A6qjsP1vdlCO', exp: 1595269691 }
        Jul 20 20:25:06 xx app/web.1: 2020-07-20T18:25:06.331Z oidc-provider:authentication:interrupted uid=mXtvfWh-IHuZQ5_Y_JuIy interaction=Interaction { returnTo: 'https://xx.herokuapp.com/fr/api/oidc/auth/mXtvfWh-IHuZQ5_Y_JuIy', prompt: { name: 'login', reasons: [ 'no_session' ], details: { max_age: undefined, login_hint: undefined, id_token_hint: undefined } }, lastSubmission: undefined, uid: 'mXtvfWh-IHuZQ5_Y_JuIy', params: { client_id: 'aa', nonce: 'ifHfqzVJwIhC5uQpbUyFI610gQOmMiKxAuO5qfIJjUw', redirect_uri: 'https://972e5cdf2af6.ngrok.io/fr/api/users/signed-in-gt', response_type: 'id_token', scope: 'openid', state: 'pTK8kSoSeethJHmVziEUCgt_Q4WyNsfW8Lz62820qBQ' }, signed: undefined, session: undefined, kind: 'Interaction', jti: 'mXtvfWh-IHuZQ5_Y_JuIy', exp: 1595270106 }

**Comment by panva** [comment]
@carolineBda so there are clearly multiple things going.

Starting off with the easy one - "no" callback parameters for your client. What you're exhibiting is expected behaviour. For the response_type id_token the default response_mode is `fragment`. So, your callback parameters are not in a query (and cannot be for this response type) but, instead, in the fragment. To resolve: make your client request an additional parameter `response_mode=form_post` and change your callback route verb from `GET` to `POST`.

This alone fixes the non-issue you're asking about. You'll start getting responses, from looking at your logs tho, they'll all be `server_error`.

So clearly have an issue in your interactions that I cannot troubleshoot like so. I'm talking about this.

```
    Jul 20 20:18:10 xx app/web.1: 2020-07-20T18:18:09.924Z oidc-provider:server_error uid=LxeYpC6e5Sin2YqwtI7a6 path=/auth/LxeYpC6e5Sin2YqwtI7a6 method=GET error=TypeError: Cannot read property 'claims' of undefined at idTokenHandler (/app/node_modules/oidc-provider/lib/actions/authorization/process_response_types.js:85:31) at /app/node_modules/oidc-provider/lib/actions/authorization/process_response_types.js:130:16 at Array.map (<anonymous>) at processResponseTypes (/app/node_modules/oidc-provider/lib/actions/authorization/process_response_types.js:123:69) at dispatch (/app/node_modules/koa-compose/index.js:42:32) at respond (/app/node_modules/oidc-provider/lib/actions/authorization/respond.js:16:21) at dispatch (/app/node_modules/koa-compose/index.js:42:32) at interactions (/app/node_modules/oidc-provider/lib/actions/authorization/interactions.js:74:11) at runMicrotasks (<anonymous>) at processTicksAndRejections (internal/process/task_queues.js:94:5) at async resumeAction (/app/node_modules/oidc-provider/lib/actions/authorization/resume.js:144:3) at async sessionHandler (/app/node_modules/oidc-provider/lib/shared/session.js:29:5) at async noCache (/app/node_modules/oidc-provider/lib/shared/no_cache.js:4:3) at async authorizationErrorHandler (/app/node_modules/oidc-provider/lib/shared/authorization_error_handler.js:55:7) at async ensureSessionSave (/app/node_modules/oidc-provider/lib/helpers/initialize_app.js:51:7) at async contextEnsureOidc (/app/node_modules/oidc-provider/lib/shared/context_ensure_oidc.js:4:5) at async /app/node_modules/oidc-provider/lib/helpers/initialize_app.js:243:5 at async errorHandler (/app/node_modules/oidc-provider/lib/shared/error_handler.js:23:7)
    Jul 20 20:18:10 xx app/web.1: 2020-07-20T18:18:09.924Z oidc-provider:server_error:trace TypeError: Cannot read property 'claims' of undefined
    Jul 20 20:18:10 xx app/web.1:     at idTokenHandler (/app/node_modules/oidc-provider/lib/actions/authorization/process_response_types.js:85:31)
    Jul 20 20:18:10 xx app/web.1:     at /app/node_modules/oidc-provider/lib/actions/authorization/process_response_types.js:130:16
    Jul 20 20:18:10 xx app/web.1:     at Array.map (<anonymous>)
    Jul 20 20:18:10 xx app/web.1:     at processResponseTypes (/app/node_modules/oidc-provider/lib/actions/authorization/process_response_types.js:123:69)
    Jul 20 20:18:10 xx app/web.1:     at dispatch (/app/node_modules/koa-compose/index.js:42:32)
    Jul 20 20:18:10 xx app/web.1:     at respond (/app/node_modules/oidc-provider/lib/actions/authorization/respond.js:16:21)
    Jul 20 20:18:10 xx app/web.1:     at dispatch (/app/node_modules/koa-compose/index.js:42:32)
    Jul 20 20:18:10 xx app/web.1:     at interactions (/app/node_modules/oidc-provider/lib/actions/authorization/interactions.js:74:11)
    Jul 20 20:18:10 xx app/web.1:     at runMicrotasks (<anonymous>)
    Jul 20 20:18:10 xx app/web.1:     at processTicksAndRejections (internal/process/task_queues.js:94:5)
    Jul 20 20:18:10 xx app/web.1:     at async resumeAction (/app/node_modules/oidc-provider/lib/actions/authorization/resume.js:144:3)
    Jul 20 20:18:10 xx app/web.1:     at async sessionHandler (/app/node_modules/oidc-provider/lib/shared/session.js:29:5)
    Jul 20 20:18:10 xx app/web.1:     at async noCache (/app/node_modules/oidc-provider/lib/shared/no_cache.js:4:3)
    Jul 20 20:18:10 xx app/web.1:     at async authorizationErrorHandler (/app/node_modules/oidc-provider/lib/shared/authorization_error_handler.js:55:7)
    Jul 20 20:18:10 xx app/web.1:     at async ensureSessionSave (/app/node_modules/oidc-provider/lib/helpers/initialize_app.js:51:7)
    Jul 20 20:18:10 xx app/web.1:     at async contextEnsureOidc (/app/node_modules/oidc-provider/lib/shared/context_ensure_oidc.js:4:5)
    Jul 20 20:18:10 xx app/web.1:     at async /app/node_modules/oidc-provider/lib/helpers/initialize_app.js:243:5
    Jul 20 20:18:10 xx app/web.1:     at async errorHandler (/app/node_modules/oidc-provider/lib/shared/error_handler.js:23:7)
```

If you could describe your interaction flow in thorough detail please.

**Comment by carolineBda** [comment]
Ok in that case I'll leave the callback as it is.

The flow is this one :

Client hit the sign-in url :
`https://972e5cdf2af6.ngrok.io/fr/api/users/sign-in-gt
`
Configured as :
`router.get('/sign-in-gt', passport.authenticate('oidc'));
`

302 to 
`https://xx.herokuapp.com/fr/api/oidc/auth?client_id=aa&scope=openid&response_type=id_token&redirect_uri=https%3A%2F%2F972e5cdf2af6.ngrok.io%2Ffr%2Fapi%2Fusers%2Fsigned-in-gt&state=JJp1hqc6ARvvhBC7NaR8QiHDb0bbABXO13NugEPXDXo&nonce=xG1BOUGDsruDrCuJbtO5hgTv7cXImmV-geQGdZJQ_Y4`

The server shows a login page, the user enter the right credential which does a POST to the usual website login endpoint :
`Request URL: https://xx.herokuapp.com/fr/api/users/sign-in
Request Method: POST`

Straight after POST to the OIDC login endpoint :
`Request URL: https://xx.herokuapp.com/fr/api/oidc/registration/0ExG_-pyVpjCVaZFYedri/login
Request Method: POST`

302 to
`Request URL: https://b2b-test.herokuapp.com/fr/api/oidc/auth/0ExG_-pyVpjCVaZFYedri
Request Method: GET`

302 to
`Request URL: https://b2b-test.herokuapp.com/fr/api/oidc/registration/0ExG_-pyVpjCVaZFYedri
Request Method: GET`

The user accept the consent which POST to the OIDC consent endpoint :
`Request URL: https://b2b-test.herokuapp.com/fr/api/oidc/registration/0ExG_-pyVpjCVaZFYedri/confirm
Request Method: POST`

Which 302 to
`Request URL: https://b2b-test.herokuapp.com/fr/api/oidc/auth/0ExG_-pyVpjCVaZFYedri
Request Method: GET`

Which 302 to callback
`Request URL: https://972e5cdf2af6.ngrok.io/fr/api/users/signed-in-gt
Request Method: OPTIONS
Status Code: 204 No Content`

`Request URL: https://972e5cdf2af6.ngrok.io/fr/api/users/signed-in-gt
Request Method: GET
Status Code: 302 Found`

Which 302 to /auth again
`Request URL: https://b2b-test.herokuapp.com/fr/api/oidc/auth?client_id=aa&scope=openid&response_type=id_token&redirect_uri=https%3A%2F%2F972e5cdf2af6.ngrok.io%2Ffr%2Fapi%2Fusers%2Fsigned-in-gt&state=bYOqPMu61Cx8hpTSeFksosE5BDikCyv_4G225E9EegE&nonce=lfRvi1dYbX_iQiggQgHZ5heq6YTstlqJlUibv7xsOwU
Request Method: OPTIONS
Status Code: 204 No Content`

`Request URL: https://b2b-test.herokuapp.com/fr/api/oidc/auth?client_id=aa&scope=openid&response_type=id_token&redirect_uri=https%3A%2F%2F972e5cdf2af6.ngrok.io%2Ffr%2Fapi%2Fusers%2Fsigned-in-gt&state=bYOqPMu61Cx8hpTSeFksosE5BDikCyv_4G225E9EegE&nonce=lfRvi1dYbX_iQiggQgHZ5heq6YTstlqJlUibv7xsOwU
Request Method: GET`

Which 302 to Registration again which then send the 400 :
`Request URL: https://b2b-test.herokuapp.com/fr/api/oidc/registration/T4mW6t9SOChECiyy3Nnfg
Request Method: GET
Status Code: 400 Bad Request`

I can send you in private the url the test server so you can see it yourself if that is easier

**Comment by panva** [comment]
> Ok in that case I'll leave the callback as it is.

No, you need to change that 💯 anyway.

**Comment by panva** [comment]
> I can send you in private the url the test server so you can see it yourself if that is easier

Please do.

**Comment by panva** [comment]
Resolved outside of the issue tracker.
