### ISSUE TITLE
OpenID Connect HTTP-Based Logout 1.0 - draft 04 - not implemented?

### ISSUE THREAD

**Issue by TinMarkovic** [panva/node-oidc-provider#76]
Greetings,

As I see, in your implementation, there's no action providing regular (not backchannel) logout functionality for the Provider. It seems like a relatively simple action, so I was wondering if there was something I am missing.

I am referring to this document, and section: 

http://openid.net/specs/openid-connect-logout-1_0-04.html#OPLogout

Regards

**Comment by panva** [comment]
HTTP-Based Logout 1.0 spec is now called Front-Channel Logout 1.0. The name is confusing though, it does not define what you would expect, together with Back-Channel Logout 1.0 it provides means for RP's to learn about OP logout via either frontend or backend means. Think of it as a webhook to let RP's know the user has logged out at the OP.

Both Back and Front refer to and pull RP-Initiated Logout from [OpenID Connect Session Management 1.0](https://openid.net/specs/openid-connect-session-1_0.html). It is the only spec defining RP-Initiated OP logout and it is supported by this implementation.

Back-Channel is also supported in it's draft version. I do not plan Front-Channel support for now.
