### ISSUE TITLE
Refresh token length

### ISSUE THREAD

**Issue by mciocan** [panva/node-oidc-provider#760]
Hello @panva,

I was wondering if there is any capability to change the current refresh token length ([which is currently 43](https://github.com/panva/node-oidc-provider/blob/master/lib/models/formats/opaque.js#L14))?

Thank you!

**Comment by panva** [comment]
No there isn’t. Is 256 bits of encoded randomness not unguessable enough? This bit length does follow the recommendations.

**Comment by mciocan** [comment]
Thank you your fast response! 
We have some clients with higher requirements.

**Comment by panva** [comment]
This passes the FAPI OIDC profile requirements. I suggest your clients stop looking at string length but rather how much randomness it contains.

**Comment by panva** [comment]
Nevertheless, should you feel like sponsoring the feature development of making this configurable i’m not opposed.
