### ISSUE TITLE
How can session data stored during the interaction be retreived during authorization code grant?

### ISSUE THREAD

**Issue by rasmias** [panva/node-oidc-provider#761]
If we store some session data during interaction - lets say id token/access token claims, can it be retrieved during the the POST call?

We get a callback to findAccount() during the auth code grant with the ctx, account id and the code. The code contains a sessionUid which is same as the uid of the Session object created during the interaction.

What is the right way to read this session in our findAccount() implementation?

**Comment by panva** [comment]
provider.Session.findByUid
