### ISSUE TITLE
Client Authentication with private_key_jwt

### ISSUE THREAD

**Issue by atiface** [panva/node-oidc-provider#762]
Hi There
Could you please guide me how to configure the provider for client authentication using only private_key_jwt
It would be helpful if you can provide an example configuration

**Comment by panva** [comment]
Hi, please read the docs on how to enable only some specific client authentication methods.

**Comment by atiface** [comment]
The docs don't have that information.

**Comment by panva** [comment]
> The docs don't have that information.

Really? I literally opened the docs, ctrl+f, search for private_key_jwt and [found](https://github.com/panva/node-oidc-provider/blob/master/docs/README.md#tokenendpointauthmethods) exactly what you need to use to configure the OP to support a given list of authentication methods.
