### ISSUE TITLE
redirect_uri in Interaction is wrong

### ISSUE THREAD

**Issue by kareha** [panva/node-oidc-provider#763]
**Describe the bug**
I configured a client for local login with implicit grant like:
```
  let localClient = {
    client_name: 'My great idm',
    client_id: 'default',
    grant_types: ['implicit'],
    response_types: ['none'],
    redirect_uris: [ path.join(ISSUER, 'profile') ],
    token_endpoint_auth_method: 'none'
  }
```

ISSUER is: "https://mygreatidm.domain.tld"

I configured an express route like this:

```
  app.get('/signin', async (req, res, next) => {
    if (req.user && req.user.id) {
      return res.redirect(`/profile`)
    }
    let nonce = Date.now()
    return res.redirect(`/auth?client_id=default&response_type=none&scope=openid&nonce=${nonce}&prompt=login`)
  })
```

Now the issue:
If I enter the route /signin, redirect happens and an interaction will be created. Ok.
But within the interaction, the param `payload.params.redirect_uri` is: `'https:/mygreatidm.domain.tld/profile'`

Why is there a slash missing in protocol https:/ ?

Do I have to set the param for redirect_uri in the /auth call explicit?
I ask, because on my local machine it worked like a charm with http://localhost:3000/
(of course disabling the https check)

Hope you have an idea what I am missing.

Thanks a lot!

Kind regards Stefan

**To Reproduce**
See code above

**Expected behaviour**
payload.params.redirect_uri should be be: 'https://mygreatidm.domain.tld/profile'

**Environment:**
 - oidc-provider version: latest
 - node version: v14

**Additional context**

 - [x] the bug is happening on latest oidc-provider too.
 - [x] i have tried DEBUG (see README) and can see the issue is with the provider and not my code.
 - [x] i have searched the issues tracker on github for similar issues and couldn't find anything related.
 - [x] i have searched the [FAQ](https://github.com/panva/node-oidc-provider/blob/master/docs/README.md#faq) and couldn't find anything related.

**Comment by panva** [comment]
```
> ISSUER = 'https://mygreatidm.domain.tld'
'https://mygreatidm.domain.tld'
> path.join(ISSUER, 'profile')
'https:/mygreatidm.domain.tld/profile'
```

It's your code.

**Comment by panva** [comment]
You seem to be a [long time user of the library](https://github.com/panva/node-oidc-provider/issues?q=author%3Akareha), please consider [supporting](https://github.com/panva/node-oidc-provider?sponsor=1) the library if it provides value to you or your company and this and the previous support was of help to you. Supporting the library means, amongst other things, that any support and the library itself will be available to you in the future.
