### ISSUE TITLE
Adding option to use issuer in generation of discovery endpoints?

### ISSUE THREAD

**Issue by jstuder-gh** [panva/node-oidc-provider#764]
**Describe the solution you'd like**

I am in need of the ability for the application developer to set a Configuration option instructing the library to use the issuer URL in the generation of OIDC discovery endpoints. Something like the following:

```js
const provider = new Provider(ISSUER_URL, {
  determineEndpointsFromIssuer: true, // default === false
  // rest of configuration options...
});
```

Is this something you would be consider accepting upstream if I submitted a PR?

**Describe alternatives you've considered**

I understand that it is possible to set the web server to accept `x-forwarded-*` headers and use them in place of the request URL in generating the endpoints (as seen at https://github.com/panva/node-oidc-provider/blob/v6.28.0/docs/README.md#user-content-trusting-tls-offloading-proxies).

However, this could provide an alternative in instances where the server is behind a proxy that is stripping the `x-forwarded-*` headers. In this case the issuer would provide the best indication of where the OIDC provider application is accessible from the internet.

**Additional context**

 - [x] i have searched the configuration section for this feature and couldn't find it
 - [x] i have searched the issues tracker on github for similar requests and couldn't find anything related.

**Comment by panva** [comment]
I understand the ask but giving in doesn’t solve much for you. If your proxy is stripping standard transparent reverse proxy headers then i.e. your cookies won’t be set as secure secure either. This isn’t even because of this library, but directly in koa, the web framework used.

In any case, you can simply overload the provider.OIDCContext.prototype.urlFor function to achieve this.

**Comment by jstuder-gh** [comment]
Oh I see. I didn't realize that the cookie functionality was also dependent upon the `x-forwarded-*` headers being set correctly. So, as you say, even if we side-step the issue here it will still crop up somewhere else.

Thanks for clearing that up and I appreciate the quick response!

**Comment by panva** [comment]
Np, the x-forwarded-* headers are really the norm.
