### ISSUE TITLE
typescript: Export OIDCContext (or adding DefaultContext type) for koa-router

### ISSUE THREAD

**Issue by kevinschoonover** [panva/node-oidc-provider#765]
**Is your feature request related to a problem? Please describe.**
Using the ["/interaction/:uid/login" route in the default example](https://github.com/panva/node-oidc-provider/blob/ca7def416a473717b00280252497d65a7ea6441c/example/routes/koa.js#L115) causes the following:
```
src/routes.ts:78:11 - error TS2345: Argument of type 'ParameterizedContext<any
 RouterParamContext<any, {}>>' is not assignable to parameter of type 'Paramet
rizedContext<DefaultState, DefaultContext & { oidc: OIDCContext; }>'.
  Property 'oidc' is missing in type 'ExtendableContext & { state: any; } & Ro
terParamContext<any, {}>' but required in type '{ oidc: OIDCContext; }'.
```

as koa-router provides its own type for the ctx / state.

**Describe the solution you'd like**
koa-router allows you to parameterize it types with something like
```
const router = new Router<
  Koa.DefaultState,
  Koa.DefaultContext & { oidc: OIDCContext }
>();
```

so I would be interested in something like
```
export type DefaultContext = Koa.DefaultContext & {
  oidc: OIDCContext;
};

export type KoaContextWithOIDC = Koa.ParameterizedContext<
  Koa.DefaultState,
  DefaultContext
>;
```

or exporting OIDCContext. 

**additional information**
Can provide a minimal repo for reproduction. Happy to make a PR and thank you for your work on this excellent library.

 - [X] i have searched the configuration section for this feature and couldn't find it
 - [X] i have searched the issues tracker on github for similar requests and couldn't find anything related.

**Comment by panva** [comment]
Please propose a PR.

**Comment by panva** [comment]
Wait. In your interactions OIDCContext isn’t available anyway.

**Comment by kevinschoonover** [comment]
Let me do some further investigation, my guess is I am using the account interface wrong. Thanks for the quick response.

**Comment by panva** [comment]
Also, oidccontext is exported attached to provider instance https://github.com/panva/node-oidc-provider/blob/master/types/index.d.ts#L1499

**Comment by kevinschoonover** [comment]
> OIDCContext isn’t available in your interactions anyway.

Does this mean that the ctx begin passed [here](https://github.com/panva/node-oidc-provider/blob/ca7def416a473717b00280252497d65a7ea6441c/example/routes/koa.js#L58) is just the standard Koa context? As the type for this particular function in the provider is defined as
```ts
export type FindAccount = (ctx: KoaContextWithOIDC, sub: string, token?: AuthorizationCode | AccessToken | DeviceCode) => CanBePromise<Account>;
```

Just making sure I am not overthinking this by doing something like a union type or writing a separate function.

**Comment by panva** [comment]
You probably are. Within the context of the helper function used by the library it is enriched koa context. Within your interactions, use whatever you want. No need to use the helper definition you passed to provider configuration because afterall your interaction result account will just be a string with the identifier
