### ISSUE TITLE
Where to silently grant scopes

### ISSUE THREAD

**Issue by johndc7** [panva/node-oidc-provider#766]
I would like to skip all consent prompts for first-party services (which at the moment is all of them).

Since all of them are currently first party, I removed the consent prompt from the `interactionPolicy`. I am then adding the consent when the user completes the login interaction. When the user logs in to another client after being authenticated previously for something else, the login interaction is skipped how it normally is. Now the problem is that there is no consent being added and I get an access denied error. How do I add the scopes without using an interaction (I would like to use the `prompt=none` option from my client)?

Here is where the error is coming from in the provider:
```
// check there's something granted to continue
    // if only claims parameter is used then it must be combined with openid scope anyway
    // when no scope paramater was provided and none is injected by the AS policy access is
    // denied rather then issuing a code/token without scopes
    if (!oidc.acceptedScope()) {
      throw new errors.AccessDenied(undefined, 'authorization request resolved without requesting interactions but no scope was granted');
    }
```
Thanks for your help

**Comment by panva** [comment]
#606
