### ISSUE TITLE
Recommendation for client verification strategy?

### ISSUE THREAD

**Issue by wolfejw86** [panva/node-oidc-provider#767]
Hi, first off thanks for such a cool package. It has really helped me to understand the openid connect workflows and how to handle them.  I have a question about authorization.  

Lets say I have several nodejs microservices that are dependent on this oidc-provider server as the security token service.  Many of the other nodejs microservices only need to handle the verification of the jwt being provided at the authorization level.  I am looking for a recommendation on how to best implement the following workflow:
`User arrives at external site` -> `User accesses dashboard` -> `Not Authenticated` -> `Redirected to complete PKCE with the security token service (node-oidc-provider)` -> `Success, redirected back to dashboard` -> `Dashboard makes API calls to multiple services` -> `Each service needs a way to independently verify the JWT (ideally via middleware)`

Do you have a recommended middleware or suggested approach to authorize these jwts produced by node-oidc-provider?

**Comment by panva** [comment]
Hi. I am not the capacity to make such recommendation.

**Comment by wolfejw86** [comment]
😢

**Comment by janhalama** [comment]
@wolfejw86 Hi, take a look at [Kong API gateway]( https://konghq.com/kong/).

**Comment by serhiisaviuk** [comment]
@wolfejw86  we made own middleware on Node.JS, also if you use Nginx, you can write plugin there on lua, for automatize this header check.
