### ISSUE TITLE
Session check html - Ajax cloudflare lib

### ISSUE THREAD

**Issue by cgeduhn** [panva/node-oidc-provider#769]
**Session check html - Ajax cloudflare lib**
In the session check html the ajax library is loaded by a cloudflare url. 
It would be great if it would be possible to change the ajax library url or if the dependency would be changed or if vanilla javascript would be used here. 
Because we had issues with the session check because cloudflare was not reachable for at least 1 hour. 

Cloudflare is not the best option to host static files... in my opinion

Region: germany - Dortmund

**Comment by panva** [comment]
@cgeduhn you can easily change the html response body in a post middleware.

```js
provider.use((ctx, next) => {
  if (ctx.oidc && ctx.oidc.route === 'check_session') {
    ctx.body = ctx.body.replace('...') // replace the script tags etc
  }
});
```
