### ISSUE TITLE
Create an Integrity keystore

### ISSUE THREAD

**Issue by fdidron** [panva/node-oidc-provider#77]
Hi,

I'm struggling genereating an integrity keystore. I have been trying to follow this part of the documentation https://github.com/panva/node-oidc-provider/blob/master/docs/keystores.md#integrity-keystore
but it seems there is no explanation on how to proceed.

Kind regards,

Florian

**Comment by panva** [comment]
The readme is wrong, let me fix it.

**Comment by panva** [comment]
My recommendation

1) Generate a HS512 oct sig key and locally store the value
```js
const { createKeyStore } = require('oidc-provider');
const keystore = createKeyStore();
keystore.generate('oct', 512, { use:'sig', alg: 'HS512' }).then(() => {
  console.log('this is the integrity JWKS:\n', keystore.toJSON(true));
});
```

2) pass it to initialize, confirm by NOT seeing the console warning anymore.

```js
const integrity = // ... the JWKS from above
provider.initialize({ clients, keystore, integrity });
```

**Comment by fdidron** [comment]
Worked like a charm thanks for the quick update !
