### ISSUE TITLE
How to set "check_session_iframe" option?

### ISSUE THREAD

**Issue by SansDK** [panva/node-oidc-provider#770]
In the [sample application](https://tranquil-reef-95185.herokuapp.com/setup), under `Issuer`, the `check_session_iframe` is set to `https://op.panva.cz/session/check`.

I read through the documentation but I couldn't find anything about this setting. I want to use this check-session-iframe to poll / check if the user is still logged in, just like what is happening in the example app.

Can someone tell me how to configure this?

Thanks!

**Comment by panva** [comment]
https://github.com/panva/node-oidc-provider/blob/master/docs/README.md#featuressessionmanagement

**Comment by SansDK** [comment]
Thanks for the quick reply. I've read this piece of documentation, but I'm unable to figure out how to use the `sessionManagementScriptNonce` method to get the `check_session_iframe` to show up in the discovery document.

I'm very new to OpenID Connect and this library, could you please elaborate?

**Comment by panva** [comment]
You should just *enable* the feature first, that has nothing to do with understanding Connect. I would also like to point out that if you're new to connect it's likely not the best idea to be setting up a server, altho if you're going to - using this package is likely to make you mess up the least in Node.js.

**Comment by SansDK** [comment]
Oh yeah sorry I forgot to mention, but I have already enabled the `sessionManagement` in the Provider features. The `end_session_endpoint` is showing up in the discovery document already. It's just the `check_session_iframe` which is missing.

The server setup is part of a research so for now it's okay if I might mess things up. Setting this up in practice helps me understand the OIDC concepts and flows pretty well so far.

**Comment by panva** [comment]
`end_session_endpoint` is ALWAYS exposed, if you're not seeing `check_session_iframe` then you have not enabled the feature.

**Comment by SansDK** [comment]
It was a typo in the `sessionManagement` feature. Typed `enbaled` instead of `enabled`....

Sorry for the issue but thanks a lot for the replies!

**Comment by panva** [comment]
Please consider [supporting](https://github.com/panva/node-oidc-provider?sponsor=1) the library if it turns out to provide value to you or your company and this support was of help to you. Supporting the library means, amongst other things, that the library itself and such support will be available to you in the future.
