### ISSUE TITLE
Issue with PKCE code_verifier & code_challenge

### ISSUE THREAD

**Issue by SansDK** [panva/node-oidc-provider#771]
I'm trying to use PKCE, but the `expected ` value is never equal to the given `code_challenge` in the `lib/helpers/pkce.js` file. Therefor I get the error `grant request is invalid` and it obviously doesn't work.

Example:
```
code_verifier = d2OJlOfGOolT1tZoKKhrpYttdAfUR969P0NWY3wjGBzc6Ii0Bcksc7TMso8N2JHacQQTiMjJjUcBLszsrI5UG6xo5bzySrXjYRIFTnPxNVS
code_challenge = OWE3MjM1YTExMWJlODlkMWRlYTU0ZTM2YjlhMWUyNTkxNGQ4N2EyYWFjYmRmZGYyYzY0YTEwMGRmZjEyZGY5Ng
method = SHA-256

expected in pkce.js = mnI1oRG-idHepU42uaHiWRTYeiqsvf3yxkoQDf8S35Y
```

I verified my client's SHA256 hashing & base64 encoding with this tool: https://emn178.github.io/online-tools/sha256.html. The output of my code and this tool are the same, however it _looks like_ this library hashes & encodes it differently (hence the different expected value).

I do however have to strip the base64 padding (==) from my code_challenge when sending it with the /auth route. Otherwise I would get the `... must only contain [a-Z] / [0-9] / "-" / "." / "_" / "~"` error from the `pkce_format.js` checks obviously.

---

I'm using the `authorization_code` flow. My steps:

1. Redirect to /auth like this:

`http://localhost:3000/auth?client_id=${client_id}&redirect_uri=${redirect_uri}&response_type=code&scope=openid profile&state=${state}&code_challenge=${ccb}&code_challenge_method=S256` (where ccb is the SHA-256 hashed & base64 encoded string)

2. Login with credentials, accept scopes, and wait for it to redirect back to the redirect_uri
3. Send a request to the /token endpoint with the following `x-www-form-urlencoded` body:

`client_id=${client_id}&grant_type=authorization_code&code=${code}&redirect_uri=${redirect_uri}&code_verifier=${code_verifier}`

4. I can see in the oidc-provider logging that the code_challenge doesn't match the expected value that is calculated by the library from the code_verifier.

5. I get the error `grant request is invalid`

**Comment by panva** [comment]
`mnI1oRG-idHepU42uaHiWRTYeiqsvf3yxkoQDf8S35Y` is indeed the expected code_challenge value for `d2OJlOfGOolT1tZoKKhrpYttdAfUR969P0NWY3wjGBzc6Ii0Bcksc7TMso8N2JHacQQTiMjJjUcBLszsrI5UG6xo5bzySrXjYRIFTnPxNVS` as code_verifier.

```
base64url.encode(crypto.createHash('sha256').update('d2OJlOfGOolT1tZoKKhrpYttdAfUR969P0NWY3wjGBzc6Ii0Bcksc7TMso8N2JHacQQTiMjJjUcBLszsrI5UG6xo5bzySrXjYRIFTnPxNVS').digest())
// mnI1oRG-idHepU42uaHiWRTYeiqsvf3yxkoQDf8S35Y
```

**Comment by panva** [comment]
Your problem is

1) you're using base64 and not base64url
2) you're encoding already hex encoded value where you should be encoding the raw octets produced by a hashing algorithm.

Look.


```
const verifier = 'd2OJlOfGOolT1tZoKKhrpYttdAfUR969P0NWY3wjGBzc6Ii0Bcksc7TMso8N2JHacQQTiMjJjUcBLszsrI5UG6xo5bzySrXjYRIFTnPxNVS'

// bad
base64url.encode(crypto.createHash('sha256').update(verifier).digest('hex'))
'OWE3MjM1YTExMWJlODlkMWRlYTU0ZTM2YjlhMWUyNTkxNGQ4N2EyYWFjYmRmZGYyYzY0YTEwMGRmZjEyZGY5Ng'

// good
base64url.encode(crypto.createHash('sha256').update(verifier).digest())
'mnI1oRG-idHepU42uaHiWRTYeiqsvf3yxkoQDf8S35Y'
```

**Comment by panva** [comment]
Please consider [supporting](https://github.com/panva/node-oidc-provider?sponsor=1) the library if it turns out to provide value to you or your company and this support was of help to you. Supporting the library means, amongst other things, that the library itself and such support will be available to you in the future.
