### ISSUE TITLE
TypeError: Cannot read property '3' of undefined on bson module

### ISSUE THREAD

**Issue by luvicsoura** [panva/node-oidc-provider#772]
**Describe the bug**
When fixing the query from the example MongoDB adapter, which wasn't retrieving any clients, the bson dependency started throwing the following error: 'TypeError: Cannot read property '3' of undefined'.

**To Reproduce**

Steps to reproduce the behaviour:

1.  Roll up a server with the example MongoDB adapter
2.  fix the query on `find`  to `{
            _id: new ObjectId(_id)
}` in order to actually retrieve something from the database
3.  See the server error out

**Expected behaviour**
The provider should validate the client and redirect the user to the redirect_uri

**Environment:**
 - oidc-provider version: 6.29.1
 - node version: 14.5.0

**Additional context**

 - [x] the bug is happening on latest oidc-provider too.
 - [x] i have tried DEBUG (see README) and can see the issue is with the provider and not my code.
 - [x] i have searched the issues tracker on github for similar issues and couldn't find anything related.
 - [x] i have searched the [FAQ](https://github.com/panva/node-oidc-provider/blob/master/docs/README.md#faq) and couldn't find anything related.

**Logs**
```
 oidc-provider:server_error uid=7t-5ULNDVQhefMKKJ09Po path=/auth method=GET error=TypeError: Cannot read property '3' of undefined at Object.get [as generationTime] (/home/myUserName/Projects/companyName/cria-id/node_modules/bson/lib/bson/objectid.js:373:19) at /home/myUserName/Projects/companyName/cria-id/node_modules/object-hash/index.js:251:33 at Array.forEach (<anonymous>) at Object._object (/home/myUserName/Projects/companyName/cria-id/node_modules/object-hash/index.js:247:21) at Object.dispatch (/home/myUserName/Projects/companyName/cria-id/node_modules/object-hash/index.js:190:30) at /home/myUserName/Projects/companyName/cria-id/node_modules/object-hash/index.js:251:18 at Array.forEach (<anonymous>) at Object._object (/home/myUserName/Projects/companyName/cria-id/node_modules/object-hash/index.js:247:21) at Object.dispatch (/home/myUserName/Projects/companyName/cria-id/node_modules/object-hash/index.js:190:30) at /home/myUserName/Projects/companyName/cria-id/node_modules/object-hash/index.js:251:18 at Array.forEach (<anonymous>) at Object._object (/home/myUserName/Projects/companyName/cria-id/node_modules/object-hash/index.js:247:21) at Object.dispatch (/home/myUserName/Projects/companyName/cria-id/node_modules/object-hash/index.js:190:30) at hash (/home/myUserName/Projects/companyName/cria-id/node_modules/object-hash/index.js:131:10) at objectHash (/home/myUserName/Projects/companyName/cria-id/node_modules/object-hash/index.js:33:10) at fingerprint (/home/myUserName/Projects/companyName/cria-id/node_modules/oidc-provider/lib/models/client.js:36:37) +18s
  oidc-provider:server_error:trace TypeError: Cannot read property '3' of undefined
  oidc-provider:server_error:trace     at Object.get [as generationTime] (/home/myUserName/Projects/companyName/cria-id/node_modules/bson/lib/bson/objectid.js:373:19)
  oidc-provider:server_error:trace     at /home/myUserName/Projects/companyName/cria-id/node_modules/object-hash/index.js:251:33
  oidc-provider:server_error:trace     at Array.forEach (<anonymous>)
  oidc-provider:server_error:trace     at Object._object (/home/myUserName/Projects/companyName/cria-id/node_modules/object-hash/index.js:247:21)
  oidc-provider:server_error:trace     at Object.dispatch (/home/myUserName/Projects/companyName/cria-id/node_modules/object-hash/index.js:190:30)
  oidc-provider:server_error:trace     at /home/myUserName/Projects/companyName/cria-id/node_modules/object-hash/index.js:251:18
  oidc-provider:server_error:trace     at Array.forEach (<anonymous>)
  oidc-provider:server_error:trace     at Object._object (/home/myUserName/Projects/companyName/cria-id/node_modules/object-hash/index.js:247:21)
  oidc-provider:server_error:trace     at Object.dispatch (/home/myUserName/Projects/companyName/cria-id/node_modules/object-hash/index.js:190:30)
  oidc-provider:server_error:trace     at /home/myUserName/Projects/companyName/cria-id/node_modules/object-hash/index.js:251:18
  oidc-provider:server_error:trace     at Array.forEach (<anonymous>)
  oidc-provider:server_error:trace     at Object._object (/home/myUserName/Projects/companyName/cria-id/node_modules/object-hash/index.js:247:21)
  oidc-provider:server_error:trace     at Object.dispatch (/home/myUserName/Projects/companyName/cria-id/node_modules/object-hash/index.js:190:30)
  oidc-provider:server_error:trace     at hash (/home/myUserName/Projects/companyName/cria-id/node_modules/object-hash/index.js:131:10)
  oidc-provider:server_error:trace     at objectHash (/home/myUserName/Projects/companyName/cria-id/node_modules/object-hash/index.js:33:10)
  oidc-provider:server_error:trace     at fingerprint (/home/myUserName/Projects/companyName/cria-id/node_modules/oidc-provider/lib/models/client.js:36:37) 
```

**Comment by panva** [comment]
Why open an issue here when your issue is with rollup messing up the mongodb driver.

The adapter works fine - it does [not](https://github.com/panva/node-oidc-provider/blob/master/example/adapters/mongodb.js#L66) utilize ObjectId as _id.

**Comment by luvicsoura** [comment]
No, the example does not use ObjectId, but MongoDB does, making the example adapter fail when using its default implementation. As for rollup, I actually meant "Spin up a server...", I guess I got the nomenclature mixed up. Nonetheless, the response out of the box and the response with the query properly set up to how MongoDB handles _id by default should be the same, leading me to believe the issue resides, either, within the server itself or within a server dependency.

Heres a snippet of the `find` method with the 'correct' query:
```javascript
...
async find(_id) {
        const result = await this.coll().find({
            _id: new ObjectId(_id)
        }, {
            payload: 1
        }, ).limit(1).next();

        if (!result) return undefined;
        return result;
}
...
```

**Comment by panva** [comment]
Both upsert and find are also used for tokens with intentionally random identifiers that are not ObjectIds and while you're trying to make it work for the Client model using ObjectId that you've probably prepared in the DB it will fail for everything else.

**Comment by luvicsoura** [comment]
Thanks for the insight, now I better understand what's happening. Would you recommend me a way for registering the clients in a compliant form?

**Comment by panva** [comment]
1. don't use objectids if you wish your adapter to stay simple
2. use the example as is
3. your client object should be something like this

```
{
  _id: 'foo',
  payload: {
    client_id: 'foo',
    client_secret: 'bar',
    redirect_uris: ['https://rp.example.com/cb'],
    // the rest of your client metadata
  }
}
```

**Comment by luvicsoura** [comment]
I'll update my client document. Thank you a lot!

**Comment by panva** [comment]
You are welcome, as you are a new user of the library please consider [supporting](https://github.com/panva/node-oidc-provider?sponsor=1) it when it proves to provide value to you or your company and this support was of help to you. Supporting the library means, amongst other things, that such support will be available to you in the future.
