### ISSUE TITLE
Unable to logout when browser is re-opened.

### ISSUE THREAD

**Issue by codestorycooked** [panva/node-oidc-provider#773]
Hi @panva 

Use Case:
1) First user login to the app
2) When login is successful, he closes the browser (Before closing the browser id_token is grabbed) 
3) starts the browser again now invokes end/session?id_token_hint=grabbed-id-token from step 2 - Successful logout message is displayed but it does not come to logoutSource which I have configured. 
4) User logs in to the app and now NO login screen is shown - Ideally, it should show since we invoked logout.
5) if User now again invokes the end/session?id_token_hint=new-grabbed-id-token from step 4 - Successful logout message is displayed but this time it comes to configure logoutSource which I have configured.

Further debugging: 
I found when the user initiates logout after browser is closed and opened, it is not able to find a session and executes this code https://github.com/panva/node-oidc-provider/blob/master/lib/response_modes/form_post.js which is coming from https://github.com/panva/node-oidc-provider/blob/dec138286c53dc67f7dec141a6bcbc7a27f4257d/lib/actions/end_session.js#L84 where  `ctx.oidc.session.accountId()` is null. 

Is there any way I can handle this scenario, whenever the browser is reopend and logout is initiated immediately actually logs out the user?

Let me know if you need more details

**Comment by panva** [comment]
It's clear your session is not found during step 3 but is found during step 4. I suggest you take a look at your browser's network/cookie logs and check if some cookies are omitted from being sent and why.

Also please avoid using the term "browser close/re-opened" etc, it has absolutely zero meaning given that what matters is your browsing session resume configuration.

Unless you provide reproduction steps using the example OP and RP linked in the project's readme I cannot act upon this in any way.

You're a [long time user](https://github.com/panva/node-oidc-provider/issues?q=author%3Acodestorycooked) of the library, please consider [supporting](https://github.com/panva/node-oidc-provider?sponsor=1) the library if it provides value to you or your company and this and the previous support was of help to you. Supporting the library means, amongst other things, that such support will be available to you and others in the future.
