### ISSUE TITLE
TypeScript typings for Adapter.find() return type AdapterPayload does not support returning ClientMetadata

### ISSUE THREAD

**Issue by dlydiard** [panva/node-oidc-provider#774]
The Adapter interface `find()` definition only allows `AdapterPayload` as a return type. When the constructor type is 'Client' I want to return `ClientMetadata` as the type, but this isn't allowed by the interface definition.

According to the docs `find()` is where I'm supposed to be returning non-static clients.
Example:

```typescript
class DynamoProviderAdapter implements Adapter {
  async find(id: string): Promise<AdapterPayload | undefined | void> {
    if (this._model === 'Client') {
      ...
     return { // can't return this type as defined by https://github.com/panva/node-oidc-provider/tree/master/docs#clients
       client_id: ...,
       client_name: ...,
       client_secret: ...,
       grant_types: ...,
    }
  }
}
```
Should the return type of `find()` be `Promise<AdapterPayload | ClientMetadata | undefined | void>`?

**Additional context**

 - [x] the bug is happening on latest oidc-provider too.
 - [ ] i have tried DEBUG (see README) and can see the issue is with the provider and not my code.
 - [x] i have searched the issues tracker on github for similar issues and couldn't find anything related.
 - [x] i have searched the [FAQ](https://github.com/panva/node-oidc-provider/blob/master/docs/README.md#faq) and couldn't find anything related.

**Comment by dlydiard** [comment]
hmm i was able to cast 

```
return {
  ...
} as ClientMetadata
```

and all is good. I guess was expecting the return typings to be more concrete on what the expected response should be in this scenario.

**Comment by panva** [comment]
@dlydiard thanks for raising this. 6631a2d addresses that problem.
