### ISSUE TITLE
typescript: Allow a factory for the Adapter

### ISSUE THREAD

**Issue by twawszczak-wr** [panva/node-oidc-provider#775]
@panva what do you think about allowing a factory as an adapter creator in the configuration typings? Something like that:

```ts
export type AdapterFactory = (name: string) => Adapter;

export interface AdapterConstructor {
  new(name: string): Adapter;
}

export interface Configuration {
  ...
  adapter?: AdapterConstructor | AdapterFactory;
  ...
```

It will not require any changes in the javascript codebase, because the `new` keyword will also work with a factory.

**Comment by panva** [comment]
feel free to submit a PR with the change and [with TS tests added](https://github.com/panva/node-oidc-provider/blob/master/types/oidc-provider-tests.ts).
