### ISSUE TITLE
How to link interactionResult/Session to AuthorizationCode for v5.x version?

### ISSUE THREAD

**Issue by klouvas** [panva/node-oidc-provider#779]
I found this [issue](https://github.com/panva/node-oidc-provider/issues/612) that indicates how to retrieve the session in authorization code flow but the response is related to ^v6 of package.
We are using v5.5.5 version of your package and we would like to ask if there is a simple way to achieve that without upgrading to v6.
PS: Thank you for your great work creating this package.

**Comment by panva** [comment]
There isn't out of the box. The artifacts in v5.x are never tied to a session, that's a feat that came with v6.x.

If you're already using the library, please consider [supporting](https://github.com/panva/node-oidc-provider?sponsor=1) it if it provides value to you or your company. Supporting the library means, amongst other things, that the library will be available in a maintained state in the future.

**Comment by klouvas** [comment]
I know it's out of the scope of this package, but do you have any suggestion about how we can handle this?

**Comment by panva** [comment]
The AuthorizationCode model stores in it's payload an `sid`, this is the opaque session id generated for the client session at the OP. You could use that to lookup the Session object from the DB.

Other than that, upgrade to v6.x 🤷
