### ISSUE TITLE
JSON in request object's claims field

### ISSUE THREAD

**Issue by dzhoou** [panva/node-oidc-provider#78]
I was trying out the example, when I noticed that the `claims` field in auth request objects only accepts JSON strings, instead of JSON objects. So for example if I do 

`"claims":"{\"userinfo\": {\"email\" : null}}"`

the request goes through, but if I pass in an actual object to `claims` like the [example given in OpenID spec](http://openid.net/specs/openid-connect-core-1_0.html#RequestObject), the request would fail.

Not a big thing anyway, just in case you haven't noticed.

**Comment by panva** [comment]
Cool find, thanks!
