### ISSUE TITLE
Access the request object from within the database adapter

### ISSUE THREAD

**Issue by champikasam** [panva/node-oidc-provider#781]
Hi,

It is possible to access the request object from within the database adapter class? I am trying to do some validations within the adapter class, and need access to the request object in order to do that. I did see that validations can be done in a policy/software statement, but i didn't want to add extra client metadata into the payload in order to send some additional data into the adapter class methods.

Thanks in advance.

**Comment by panva** [comment]
@champikasam it is not possible. You can do synchronous validations via `extraClientMetadata` as well when you add a known property to `extraClientMetadata.properties`.
