### ISSUE TITLE
cookie config question

### ISSUE THREAD

**Issue by chriskacerguis** [panva/node-oidc-provider#782]
In my setup I have the following:

```
    const oidc = new Provider(
      this.configService.get<string>('SITE_URL'), {
        adapter: DynamoDBAdapter,
        jwks,
        ...configuration
      });

  _.set(configuration, 'cookies.keys', cookieKeys);
```

However, when using the lib, I am getting the following:

```
WARNING: configuration cookies.keys is missing, this option is critical to detect and ignore tampered cookies
```

I'm trying to pull the cookies.keys from outside source (Vault), but I'm not 100% sure why it is saying that.  Would you be able to point me in the right direction?

**Comment by panva** [comment]
That’s because at the time the configuration is evaluated the keys config is missing. Setting it afterwards doesn’t do a thing. You should consolidate your configuration before the Provider constructor is called.
