### ISSUE TITLE
Bug: Invalid cookies cause the provider returning 500 in '/token' endpoint.

### ISSUE THREAD

**Issue by jim-king-2000** [panva/node-oidc-provider#783]
**Describe the bug**

When we logged in and then the user is deleted, the cookie of the provider becomes invalid. Then we open the page and login again, the '/token' endpoint of the provider returns 500 and the login page can't pop out.

**To Reproduce**
Steps to reproduce the behaviour:

1.  Login, and close the browser.
2.  Delete the user in database.
3.  Login again, see the error message.

Error message:
```
Request URL: http://localhost:7000/token
Request Method: POST
Status Code: 500 Internal Server Error
Remote Address: [::1]:7000
Referrer Policy: no-referrer-when-downgrade
```

**Expected behaviour**
Ignore the invalid cookie and pops the login page. Invalid cookie should be treated as no cookie.

**Environment:**
 - oidc-provider version: [v6.29.3]
 - node version: [v14.10]

**Additional context**

 - [x] the bug is happening on latest oidc-provider too.
 - [x] i have tried DEBUG (see README) and can see the issue is with the provider and not my code.
 - [x] i have searched the issues tracker on github for similar issues and couldn't find anything related.
 - [x] i have searched the [FAQ](https://github.com/panva/node-oidc-provider/blob/master/docs/README.md#faq) and couldn't find anything related.

**Comment by panva** [comment]
Not sure what to respond to this. Cookies play absolutely no role in the token endpoint. They’re not even loaded or evaluated. 

So a 500 from the token endpoint can be anything that you add. 

Please enable the debug logs or listen for the server_error event. You’ll likely figure out the problem is your configured helper than the provider.

**Comment by jim-king-2000** [comment]
The error is caused by `findAccount`, which is my code.

```javascript
async findAccount(ctx, id) {
    return {
      accountId: id,
      async claims(use, scope) {
        const user = await mongodbGetUser({ _id: id });
        return {
          sub: user._id.toString(),
          name: user.username,
        };
      },
    };
  }
```

Since the current user has been deleted, the `user` variable is `null`. When we use `user._id.toString()` afterwards, the error occurs(`TypeError: Cannot read property '_id' of null`).

So, my question is, how to express `not found` status in `findAccount` which could let the login process go on?

**Comment by panva** [comment]
Resolve falsy.

**Comment by jim-king-2000** [comment]
I add the following line:
```javascript
if (!user) return user;
```

But the result is not what we expect. Oidc-provider still generates a JWT token without sub in id_token and oidc-client catches the exception and stop the login process. What we expect is that the login process continues (pop up login dialog) as if the user had logged out.

**Comment by panva** [comment]
While I don't have a concrete fix for this yet, you can continue by either

- removing the session entries in your DB related to the user you delete as you delete it
- replacing the `no_session` interaction policy `login` prompt Check with 

```js
module.exports = () => new Check('no_session', 'End-User authentication is required', (ctx) => {
  const { oidc } = ctx;
  if (!oidc.account) {
    return false;
  }

  return true;
});
```

**Comment by jim-king-2000** [comment]
Great! I'll try the methods ASAP. Thanks.

**Comment by jim-king-2000** [comment]
The first scheme works. The login dialog pops up after the session entry is deleted. It is a good workaround and I'm looking forward to the perfect fixing.
