### ISSUE TITLE
async checks evaluated in parallel

### ISSUE THREAD

**Issue by dcharbonnier** [panva/node-oidc-provider#784]
Inserting checks at specific positions is really confusing,
If you only have synchronous checks, they are evaluated sequentially.
If you have asynchronous checks, they are evaluated in parallel (more or less because they share states)
The only advantage I can see is performance, but the cost in terms of complexity does not worth the benefits IMO .
How can I execute a check before everything else ?

**Comment by panva** [comment]
> How can I execute a check before everything else ?

You cannot. They’re all executed in parallel. And the defaults are written in such way that one does not depend on the passing of another.

**Comment by dcharbonnier** [comment]
why not but the point of this issue is that we insert checks at a specific index and that make no sense no ?

**Comment by panva** [comment]
Why don't you explain what you're trying to achieve instead of this...

**Comment by dcharbonnier** [comment]
I'm trying to make the code and the documentation more easy to understand. This parameter is confusing and mostly useless, leading to bad understanding of the way the policy works.
When you read this https://github.com/panva/node-oidc-provider/issues/704#issuecomment-618603403 you “understand” that the checks will be executed on a serial way too, so you can mutate the state and use this change in the next check.
But that's true only if you never release the event loop. I'm not even sure Promise.all is specified this way so the order of execution may change in the future.
I will figure out a way to achieve what I need, just trying to help people that will fall in the same trap :smiley:

**Comment by panva** [comment]
> This parameter

What parameter. What function/API. These questions really lack detail.

> When you read [this] you “understand” that the checks will be executed on a serial way too, so you can mutate the state and use this change in the next check.

I don't get anything about serial execution from that comment.

What I'll give to you that this part is poorly documented and I would welcome any and all help improving that bit.

**Comment by dcharbonnier** [comment]
sure, https://github.com/panva/node-oidc-provider/blob/3cfcd778cb3a9bdecac0ad51dec062daa187e6b0/types/index.d.ts#L1518
The index parameter is useless, as inserting them in a specific order make no difference in the execution order.

**Comment by panva** [comment]
Do you feel like you have to use this particular API tho? Because usually you'd instantiate a Prompt with all Checks already in the constructor.

**Comment by dcharbonnier** [comment]
This api is public
Same in this issue #704 you will see :
`interactions.get("consent").checks.add(firstPartyClientAutoConsent(), 0);`
That's seams like a good idea, to achieve what you said : 
> basically you'll have to add checks that never resolve to true but automatically call e.g. ctx.oidc.session.promptedClaimsFor to add the scope you want always consented to when the client is a first party one.

But in the end, this solution only works if you have no async checks and in my case I need to make some requests to microservices or queries in the database.
Or I find a way to add a middleware to store all I need in the context before this gets executed https://github.com/panva/node-oidc-provider/blob/4393476fa4f39d01d60e42401ea1fd08e9df5a70/lib/actions/authorization/interactions.js#L23, or I will provide only one check that will execute all "regular" checks on a serial way.

**Comment by panva** [comment]
Or you async load your dependencies in a fake entered Prompt with one check that never actually prompts, then assign and use them from context. 

Options are plenty.
