### ISSUE TITLE
Dynamic claims based on Client ID

### ISSUE THREAD

**Issue by gcochard** [panva/node-oidc-provider#787]
**Is your feature request related to a problem? Please describe.**
I would like to have certain claims be dynamic based on the client ID, such as different `groups` for different clients. These groups are stored in the users table namespaced by client ID, but the `claims` method on the account is not passed any client information.

**Describe the solution you'd like**
Pass the `ctx.oidc.client` object to the `account.claims` method.

**Describe alternatives you've considered**
I experimented with leaving the client ID in the JWT (e.g. `...{ "groups": { "oidcCLIENT": ["a", "b"] } }`, but certain clients (kubernetes, for example) cannot accept a JWT in that form. I also experimented with modifying the `scope` parameter in the interaction handler to inject the client ID by mutating `groups` to `groups/oidcCLIENT `, resulting in a token that looks like `...{ "groups/oidcCLIENT": ["a", "b"] }` but that seems kludgy to me since that would change the scope from what the client requested.

**Additional context**

I patched this for my own use and it requires a one-line change to the following files:
- lib/actions/authorization/process_response_types.js
- lib/actions/grants/authoirzation_code.js
- lib/actions/grants/device_code.js
- lib/actions/grants/refresh_token.js

and a two-line change to the following:
- /lib/actions/userinfo.js

 - [x] i have searched the configuration section for this feature and couldn't find it
 - [x] i have searched the issues tracker on github for similar requests and couldn't find anything related.

**Comment by panva** [comment]
But... The whole findAccount function closure gets the context as first argument.. https://github.com/panva/node-oidc-provider/blob/master/docs/README.md#findaccount

**Comment by gcochard** [comment]
So it is, thanks for pointing out the obvious!
