### ISSUE TITLE
Connecting to Nestjs framework

### ISSUE THREAD

**Issue by milo526** [panva/node-oidc-provider#788]
Hello;

I'd like some help understanding a problem I have while connecting this library to the [NestJS](https://nestjs.com) framework.

In essence I have the same problem as #563, however, the user there sadly did not follow your advice and post their solution to help others. Therefor id like to try this again (hopefully with some more concrete information for you to help with).

The NestJS framework does allow passing `(req, res)` style callbacks through there [request objects](https://docs.nestjs.com/controllers#request-object).
I have been able to successfully deploy your library on our application in this setting.

The problem lays in route resolving (as also stated in #563). If I'm understanding correctly your library should be bound to a wildcard route (or as a global middleware).
When I bind the callback your library provides to a wildcard route, it takes precedence over other routes. Since it is a route instead of middleware there will not be a fall through and the routes that are "behind" the oidc callback are unreachable.

To solve this I wanted to move my installation of this library to the `/oidc` path following the steps explained [in your documentation](https://github.com/panva/node-oidc-provider/blob/master/docs/README.md#mounting-oidc-provider).

To facilitate this I added a controller prefix as [documented by Nestjs](https://docs.nestjs.com/controllers#routing).

This does properly invoke the callback (debug log entry below)

```
oidc-provider:error uid=undefined path=/oidc/auth method=GET error={ error: 'invalid_request', error_description: 'unrecognized route or not allowed method (GET on /oidc/auth)' } detail=undefined +0ms
```

But clearly the routing is wrong. When I use the path prefix as specified in [your documentation](https://github.com/panva/node-oidc-provider/blob/master/docs/README.md#mounting-oidc-provider) this `/oidc` part of the path is "consumed" by the router and it is forwarding only `/auth`, a part that your library properly understands.

Now in my controller I have the controller action:

```
import { Request, Response } from 'express';

@Controller('/oidc')
export class OidcController {
    @Get('/*')
    public get(@Req() req: Request, @Res() res: Response): void {
      return this.callback(req, res);
    }
}
```

Where ```this.callback``` references the the oidc-provider callback.

So my questions:
Can I rewrite some part of an express Request object to change the url and remove the router prefix from the path so the callback properly understands the routes?
Can I define this path prefix in the library configuration to aid the provider in understanding my paths.

**Comment by panva** [comment]
Can you give me a working snippet of code i can actually run? (the mounted to /oidc one), please create a gist with two files, index.js and package.json, i'm hoping to run this app with `node index.js`.

**Comment by milo526** [comment]
I don't believe it is possible to run Nest in such an isolated manner; I can make a nest application with the minimal configuration and this controller included? Would that work for you?

Then you should be able to run the application with

`
yarn && yarn start
`

**Comment by panva** [comment]
> I don't believe it is possible to run Nest in such an isolated manner; I can make a nest application with the minimal configuration and this controller included? Would that work for you?
> 
> Then you should be able to run the application with
> 
> `yarn && yarn start`

Sure, anything so that i can avoid having to setup <yet another framework with obscure setup steps>

**Comment by milo526** [comment]
I believe the repository [here](https://github.com/RiskChallenger/minimal-nest-oidc-provider) suffices to illustrate the issue.

While writing this I came to a possible solution.
Rewriting the url before passing it to the callback using `req.url = req.url.substring(5);` seems to work.

```javascript
@Get('/*')
  public get(@Req() req: Request, @Res() res: Response): void {
    req.url = req.url.substring(5);
    return this.provider.callback(req, res);
  }
```

Do you expect the above solution to work properly or will that yield other problems later on?
Does your library use anything but `req.url` to validate the url path?

**Comment by panva** [comment]
So, in my testing based on your repo - req.url was always just '/', which is weird to begin with. But req.originalUrl was already present. So what i did to make it work is set proper req.url. Also apply to `@All` - the important ones - GET, POST and OPTIONS, but also for dynamic registration the PUT and DELETE. No need to cherry pick, just `@All`.

```ts
import { Controller, All, Req, Res } from '@nestjs/common';
import { Request, Response } from 'express';
import { provider } from './provider';

const { callback } = provider;
const prefix = '/oidc';

@Controller('oidc')
export class OidcController {
  @All('/*')
  public rewriteToProvider(@Req() req: Request, @Res() res: Response): void {
    req.url = req.originalUrl.replace(prefix, '');
    return callback(req, res);
  }
}
```

Please consider [supporting](https://github.com/panva/node-oidc-provider?sponsor=1) the library if it turns out to value to you and/or your company. Supporting the library means, amongst other things, that such support and the library will be available and maintained in the future.

**Comment by milo526** [comment]
The suggested code worked as a charm!
There was only one weird interaction that I did not catch at first.
[This line](https://github.com/panva/node-oidc-provider/blob/master/lib/actions/interaction.js#L37) in the code block:

```js
instance(provider).configuration('interactions').url = async function interactionUrl(ctx) {
    return url.parse(ctx.oidc.urlFor('interaction', { uid: ctx.oidc.uid })).pathname;
};
```
Found in `lib/actions/interaction.js` has some weird interactions in this case. With the dev interactions enabled there is a proper redirect from the `/${prefix}/auth` endpoint to `/${prefix}/interaction/:uid`. This is however not the case with dev interactions disabled. If you disable dev interactions the redirect points to `/interaction/:uid`.

This is not an issue since we can overwrite this using the [interactions.url](https://github.com/panva/node-oidc-provider/blob/master/docs/README.md#interactionsurl) config value.

I added the following to my config:

```js
interactions: {
    url: (ctx: KoaContextWithOIDC, interaction): string => {
        return `/${prefix}/interaction/${ctx.oidc.uid}`;
    }
},
```

@panva it is slightly weird that the redirect here changes based on devInteractions. Is that as expected / by design?

**Comment by panva** [comment]
It is expected.
