### ISSUE TITLE
Supporting X-Forwarded-Proto

### ISSUE THREAD

**Issue by chrisshiplet** [panva/node-oidc-provider#79]
I'm hosting my implementation of `node-oidc-provider` behind an Nginx proxy that is also the SSL termination point. The Nginx proxy attaches `x-forwarded-proto: https` to the request headers but it seems like this is ignored by the provider or `koa`, because when the provider calls `urlFor` to build the form action for HTML pages, it gets a URL that starts with `http://`, causing the POST request to fail.

Anyone have this working behind a proxy? Maybe I'm missing something obvious.

**Comment by panva** [comment]
You have the koa app at your disposal, set the proxy option either on it or the one which you mount it to.

https://github.com/panva/node-oidc-provider/wiki/FAQ#why-does-my-well-knownopenid-configuration-link-to-http-endpoints

Also see the bundled example, it's also on heroku behind ssl offloading proxy.

**Comment by chrisshiplet** [comment]
Totally missed your wiki! Apologies for spamming up the issues.

**Comment by panva** [comment]
No worries, happy to be of help

**Comment by chrisshiplet** [comment]
Yes, that would've definitely saved me some time debugging. Although, looking at the bigger picture, is there a reason that the provider needs to generate absolute URLs rather than using relative paths?

**Comment by panva** [comment]
Maybe not in this very instance (the views), but for discovery, jwt client authz the spec dictates absolute urls.

I've pushed a one time warning and some notes in documentation to master.

Again, thanks
