### ISSUE TITLE
About 2FA login features

### ISSUE THREAD

**Issue by mraffo** [panva/node-oidc-provider#790]
Hi Filip, 
Amazing project. Thanks a lot. So, Im thinking about to put some aditionals validations/verifications on login like the 2fa. Are there any possibility for this? Thanks! Regards!

**Comment by panva** [comment]
There is. As part of user interactions and custom interaction policy you can make any form of mfa happen. I do not provide samples for this tho.

**Comment by mraffo** [comment]
> There is. As part of user interactions and custom interaction policy you can make any form of mfa happen. I do not provide samples for this tho.

Very thanks! Regards!
