### ISSUE TITLE
Feature request: Rich Authorize Requests (RAR) 

### ISSUE THREAD

**Issue by MikaelSoderstrom** [panva/node-oidc-provider#795]
As it is now, I need to add info about which parts of the systems the user are be able to access for legacy reasons. RAR would solve this problem in a standards compliant way, which is why I am asking for this.

In the readme you mention that JAR is implemented, which should make it safer to use this new spec. 

Draft of specification:
https://tools.ietf.org/id/draft-lodderstedt-oauth-rar-02.html

**Comment by panva** [comment]
RAR is not on the roadmap for oidc-provider just yet. Definitely not going to happen in v6.x, unlikely to ship with early v7.x too.
