### ISSUE TITLE
Allow adapter to be a factory function instead of a class.

### ISSUE THREAD

**Issue by jamespedid** [panva/node-oidc-provider#796]
**Is your feature request related to a problem? Please describe.**
When using a dependency injection tool, it is imperative to have control over the instantiation of each instance to ensure that dependencies are properly resolved. The `node-oidc-provider` package has a very rigid constraint on what an adapter can be: the adapter must be a class with a constructor function. As a result, `node-oidc-provider` has complete control over the instantiation of any given adapter, which is in direct conflict with using dependency injection or inversion of control patterns.

**Describe the solution you'd like**
It would be a much more friendly design if the adapter can be things other than a class. In particular, it would be helpful if an adapter can also be a function that returns a class or object with the expected properties, instead of rigidly defining the adapter to be a class with a well-defined constructor. Ideally, the constructor should be absent from the interface entirely, and left up to the consumers of the library to instantiate the adapter.

**Describe alternatives you've considered**
Two options are alternatives: one of which is to violate the dependency injection pattern to provide a static class to inject the dependencies needed. Another is to resolve the dependencies in a dynamic matter when generating the configuration object. Both solutions are not patterns that are recommended in an environment that heavily uses dependency injection to construct its object models.

**Additional context**
N/A

 - [x] i have searched the configuration section for this feature and couldn't find it
 - [x] i have searched the issues tracker on github for similar requests and couldn't find anything related.

**Comment by panva** [comment]
FWIW it may already be a factory.

**Comment by jamespedid** [comment]
@panva I'm not sure if that is true. It may work with typescript, but for node I get the following error on initialization:

![image](https://user-images.githubusercontent.com/1280555/95640951-68268500-0a6d-11eb-926b-b47fad15af41.png)

**Comment by panva** [comment]
Use a named function.
