### ISSUE TITLE
Interaction timeout after idling login prompt

### ISSUE THREAD

**Issue by steve-wolfe** [panva/node-oidc-provider#798]
Hello,

Great library, it's nice to have something standardized and secure, but still customizable. 

Anyway, my issue.. I have my application configured so that the user is logged out after an idle session. After redirects and clean-up, the page goes back to the secure home which triggers the login prompt. If the user comes back hours later, enters their credentials, and submits.. They receive back, "Bad Request".

On the server is the very clear exception:
SessionNotFound: invalid_request
  at Provider.getInteraction (/app/node_modules/oidc-provider/lib/provider.js:50:11)
  at Provider.interactionDetails (/app/node_modules/oidc-provider/lib/provider.js:228:27)
  at /app/src/index.js:332:50
  at Layer.handle [as handle_request] (/app/node_modules/express/lib/router/layer.js:95:5)
  at next (/app/node_modules/express/lib/router/route.js:137:13)
  at /app/node_modules/body-parser/lib/read.js:130:5
  at invokeCallback (/app/node_modules/raw-body/index.js:224:16)
  at done (/app/node_modules/raw-body/index.js:213:7)
  at IncomingMessage.onEnd (/app/node_modules/raw-body/index.js:273:7)
  at IncomingMessage.emit (events.js:326:22)

I've read through the code and issues I found regarding interaction cookies and it seems like they use the short cookie duration. That's fine and I doubt I would want to change that, but I'm wondering if you have any suggestions on handling the situation for a cleaner user experience?

Here's my code for the login, mostly lifted from the sample, with consent prompt bypassed:
`
    expressApp.post(
      "/interaction/:uid/login",
      setNoCache,
      parse,
      async (req, res, next) => {
    try {
      const { uid, prompt, params } = await oidc.interactionDetails(req, res)
      const client = await oidc.Client.find(params.client_id)

      const accountId = await Account.authenticate(
        params.client_id,
        req.body.userId,
        req.body.password
      )

      if (!accountId) {
        res.render("login", {
          client,
          uid,
          details: prompt.details,
          params: {
            ...params,
            login_hint: req.body.userId,
          },
          title: "Sign-in",
          flash: "Invalid User ID or password.",
        })
        return
      }

      const result = {
        login: {
          account: accountId,
        },
        consent: {
          rejectedScopes: [], 
          rejectedClaims: [],
        },
      }

      await oidc.interactionFinished(req, res, result, {
        mergeWithLastSubmission: false,
      })
    } catch (err) {
          next(err)
        }
      }
    )
`

The exception is being throw at the interactionDetails helper call. It seems to me that I could just ignore the exception and authenticate the request, then maybe shore up the provider integrity by calling setProviderSession once I have the accountId. Would that work and keep the provider happy? Is there a better way to handle this through configuration or something else?

Thanks for your help,
Steve

**Comment by panva** [comment]
> That's fine and I doubt I would want to change that, but I'm wondering if you have any suggestions on handling the situation for a cleaner user experience?

Maybe consider not triggering a new interaction automatically but instead adding a page like "we've logged you out due to inactivity, click [here] to re-login". That [here] button would then trigger a new interaction.

KISS

**Comment by steve-wolfe** [comment]
Thanks for the response.

My app is a react SPA and, in order to KISS, all routes are protected. I think I'd actually have to jump through a lot more hoops to make a special case route that doesn't trigger logging in happen. Plus, I like the behavior of automatically having the login prompt come up.

It's not a huge deal, the user just has to hit the back button or navigate to their home page to get a fresh login prompt, but I was hoping that I could handle the situation in my provider to simply log them in and not have any blips.

Would changing the interaction URL to not use :uid keep the login prompt stateless? I saw you recommend that in a different issue, but it's not clear to me from the documentation what else I'd need to do.. manually establish the provider session, I assume, but I'm not sure what else.

**Comment by panva** [comment]
It'll always be stateful.

**Comment by panva** [comment]
Solution are plenty. Bending whats meant to be stateful to be stateless isn't a way forward. Routes on the other hand can be unprotected.
