### ISSUE TITLE
AdapterFactory cant be specified as adapter

### ISSUE THREAD

**Issue by Asesjix** [panva/node-oidc-provider#799]
If an AdapterFactory is specified in the Configuration, the error _Expected "adapter" to be a constructor, provide a valid adapter in Provider config._ occurs.

https://github.com/panva/node-oidc-provider/blob/master/types/index.d.ts#L837
https://github.com/panva/node-oidc-provider/blob/master/lib/helpers/initialize_adapter.js#L15

**To Reproduce**

```ts
import Provider, { Configuration, Adapter  } from 'oidc-provider'

export class OidcService {
  public createProvider() : Provider {
    const configuration: Configuration = {
      // ...
      adapter: (name) => this.createAdapter(name),
      // ...
    }
    return new Provider(this.#config.issuer, configuration)
  }

  public createAdapter(name: string): OidcAdapter {
    const database = this.#client.db(this.#config.connectionDb)
    return new OidcAdapter(database.collection<AdapterPayload>(name))
  }
}

export class OidcAdapter implements Adapter {
   // ...
}
```

**Expected behaviour**
That an AdapterFactory can be specified.

**Environment:**
 - oidc-provider version: 6.29.4
 - node version: v12.18.4

**Logs**
Expected "adapter" to be a constructor, provide a valid adapter in Provider config.

**Comment by panva** [comment]
```js
  if (!adapter.prototype || !adapter.prototype.constructor.name) {
    throw new Error(
      'Expected "adapter" to be a constructor, provide a valid adapter in Provider config.',
    );
  }
```

```
> (() => {}).prototype
undefined
> (function () {}).prototype
{}
> (function () {}).prototype.constructor.name
''
> (function foo () {}).prototype.constructor.name
'foo'
```

I know it's probably annoying, but just use a named function.
