### ISSUE TITLE
Unable to make client_credential flow work

### ISSUE THREAD

**Issue by kml7** [panva/node-oidc-provider#80]
I am not able to make client credentials flow work.

Our client definition is:
```
{
    client_id: 'a_ui',
    client_secret: '<secret>',
    grant_types: ['client_credentials', 'authorization_code'],
    redirect_uris: <url>,
    token_endpoint_auth_method: 'client_secret_post',
    post_logout_redirect_uris: <url>
}
```

I am able to use authorization_code flow without any problem with this client.

http -f POST localhost:3000/op/auth client_id=a_ui grant_type=client_credentials response_type=code scope=openid

Is there any good way to investigate why this is happening? Or my configuration is invalid for this flow?

**Comment by panva** [comment]
Hi @kml7, it looks like you're posting to authorization endpoint instead of token endpoint.

Docs: https://tools.ietf.org/html/rfc6749#section-4.4

**Comment by panva** [comment]
Example: 

```
curl -X POST -u foo:bar https://gate.panva.cz/sso/oidc/token -d grant_type=client_credentials 
{"access_token":"M2FmYzdlZjAtYTdkZC00ODZiLWE4YTUtOGM4Nzg0Y2E1NzgymQHxL-DJdzyzZb6LoEIKPO1Dho6oBNCWujDXZQW-XLDTSmhsiXYy3zfHwhAhhRTKowGTvJDvcmCgGgjuw2s7cg","expires_in":600,"token_type":"Bearer"}
```

**Comment by kml7** [comment]
Thanks for the help

**Comment by panva** [comment]
@kml7 You're welcome.
