### ISSUE TITLE
Handling SessionNotFound for Interaction 

### ISSUE THREAD

**Issue by codestorycooked** [panva/node-oidc-provider#801]
When the user waits on the login page for a long time - The interaction cookie get expired and error SessionNotFound is thrown by the library. 
We want to send this error information back to the apps redirect URL. Is there a way to do that?

**Comment by panva** [comment]
There is not. Since the interaction details are expired so are the parameters of the authorization request.

**Comment by codestorycooked** [comment]
Thank you for quick response.
