### ISSUE TITLE
Accessing the decoded request body in extraAccessTokenClaims

### ISSUE THREAD

**Issue by OliverHGray** [panva/node-oidc-provider#804]
I am trying to access a property from the request in the `extraAccessTokenClaims` callback, but I can't find where the decoded body might be stored. `context.body` is an empty object, and `context.req.body` is undefined.

Note I am using Express.

If I add a `bodyParser` middleware then `context.req.body` contains the body as expected, but I get the warning from the provider not to add an upstream parser.

**Comment by panva** [comment]
`ctx.oidc.body`

**Comment by panva** [comment]
Please consider [supporting](https://github.com/panva/node-oidc-provider?sponsor=1) the library if it provides value to you or your company and this support was of help to you. Supporting the library means, amongst other things, that such support will be available in the future.
