### ISSUE TITLE
5 -> 6 upgrade path on an application I'm trying to support that uses this

### ISSUE THREAD

**Issue by hcldan** [panva/node-oidc-provider#806]
This comment about one of your 6 changes

> clientCacheDuration configuration option and provider.Client.cacheClear method have been removed, the provider now handles everything internally and Client objects are re-instantiated automatically if the client's configuration changes.

The application I'm supporting forks its process a few times for workers.  They communicate over message passing to each other, and if one process updates a client, they call a cacheClear method in the others.
This method is now gone, and I'm not understanding the update workflow that should be done now.

Any pointers?

**Comment by panva** [comment]
You don't need to call anything now, changes in the Client document returned by your adapter are now detected by the provider itself.

**Comment by hcldan** [comment]
you ask the adapter each time now?  no more memory cache?

**Comment by panva** [comment]
Yes the provider loads the adapter document every time now, but only re-instantiates the Client document when the returned data changes.

If you wish to cache - do it on your adapter level, e.g. with https://www.npmjs.com/package/p-memoize

**Comment by hcldan** [comment]
ok interesting... 

So the staticCache here is for things added via addStatic(metadata)? Was confused by this path, not really sure what it's for.
https://github.com/panva/node-oidc-provider/blob/master/lib/models/client.js#L551

**Comment by panva** [comment]
static clients are those that you declare in your provider configuration, those never change.

**Comment by hcldan** [comment]
Ok!
Thank you very much for your time!

**Comment by panva** [comment]
Please consider [supporting](https://github.com/panva/node-oidc-provider?sponsor=1) the library if it provides value to you or your company and this support was of help to you. Supporting the library means, amongst other things, that such support will be available in the future.
