### ISSUE TITLE
Another upgrade question...

### ISSUE THREAD

**Issue by hcldan** [panva/node-oidc-provider#807]
Looks like adapters now have findByUid...  currently it's being called to get a session object.
When it was saved it was saved via 
```js
await this.adapter.upsert(this.jti, upsert, ttl);
```
The uid is in the session object, but I'm wondering why it's keyed by the jti if i need to look it up by the uid?

**Comment by panva** [comment]
find and findByUid (session model only) serve different purpose, it's used to load up a session by a uid reference, uid is in the original upsert payload.

**Comment by panva** [comment]
See the example adapters. If you'd wish to discuss further upgrade related topics in more detail consider sponsoring the package and i'll add you on slack.

v6.x is our for more than a year, i don't have the capacity to do LTS support in the issues tracker.

**Comment by panva** [comment]
There was never a client_scopes property built in.

**Comment by hcldan** [comment]
hmm...   more digging for me I guess.

**Comment by hcldan** [comment]
I'm still getting used to the project structure....   this kinda fell in my lap.
Any hints on the flow for where ctx.oidc.client gets set?   and any good debugging tips around things like that?
