### ISSUE TITLE
invalid_token when accesing userinfo endpoint

### ISSUE THREAD

**Issue by Pahicz** [panva/node-oidc-provider#808]
I started using your OAuth2 server with oidc.
My goal is simple, to access https://myserver/me which is UserInfo endpoint.

While trying to learn how to use the server I also used this guide(https://www.scottbrady91.com/OpenID-Connect/Getting-Started-with-oidc-provider) 
Where I found that I could create token by sending request to endpoint /token.

Into the configuration I added this code(full server code is below):

```
{
    client_id: 'test_oauth_app',
    client_secret: 'super_secret',
    grant_types: ['client_credentials'],
    redirect_uris: [],
    response_types: [],
}
```

In postman I was able to get my the access_token by this request

```
POST /token
Headers:
Content-Type: application/x-www-form-urlencoded
Authorization: Basic dGVzdF9vYXV0aF9hcHA6c3VwZXJfc2VjcmV0
Body:
grant_type=client_credentials&scopes=api1
``` 

I get this as a response:

```
{
    "access_token": "zdjmZo7_BQSIl4iK9IMcBbKffxGO-wQ3jLzzQXTlyws",
    "expires_in": 600,
    "token_type": "Bearer"
}
```

When I checked the token by /token/introspection I found out that the token equals to jti. So I think it actually returns jti and by that I of course cannot access /me endpoint.

Here is the whole sample of server that I use:
```

const { Provider } = require('oidc-provider');
const configuration = {
        features: {
                introspection: { enabled: true },
                clientCredentials: { enabled: true },
                userinfo: { enabled: true },
                jwtUserinfo: { enabled: true },
        },
        formats: {
            AccessToken: 'jwt',
        },
        clients: [{
            client_id: 'test_oauth_app',
            client_secret: 'super_secret',
            grant_types: ['client_credentials'],
            redirect_uris: [],
            response_types: []
        }],
        scopes: ['api1']
};

const oidc = new Provider('http://localhost:3000', configuration);
oidc.proxy = true

// express/nodejs style application callback (req, res, next) for use with express apps, see /examples/express.js
oidc.callback

// koa application for use with koa apps, see /examples/koa.js
oidc.app

// or just expose a server standalone, see /examples/standalone.js
const server = oidc.listen(3000, () => {
  console.log('oidc-provider listening on port 3000, check https://localhost:3000/.well-known/openid-configuration');
});
```

The proxy is set to true because I have https set up on apache redirecting to this server.

I tried to change response_types, but than it required redirect_uri which I do not want to have in my scenario.

Here is the request I am trying to post it like so:

```
POST /me
Headers:
Content-Type: application/json
Authorization: Bearer zdjmZo7_BQSIl4iK9IMcBbKffxGO-wQ3jLzzQXTlyws
```

The response:

```
{
    "error": "invalid_token",
    "error_description": "invalid token provided"
}
```

I found similar problem here as issue(https://github.com/panva/node-oidc-provider/issues/502) but you told the guy to use SO. SO unfortunately has no answer to this.

I even tried to debug the lib code in VS code. I located that the jti is somehow created in client_credentials.js on line 69.
`const value = await token.save();`

But I am not much familiar with the framework that you are writing it in. But probably I just do not understand something essential and should modify the configuration in the first place.

Could you please point me to the right direction?

**Comment by panva** [comment]
Client Credential grant resulting tokens are not for accessing userinfo. Use any of the standard user-involved grants.

**Comment by Pahicz** [comment]
Thank you, I read some more about the client_credentials grant type I now I understand why it makes no sense.
I used authorization_code grant type to obtain code and from it, I obtained an access token and got to the endpoint /me.
