### ISSUE TITLE
Why employ an `onload` form submission to get to the callback?

### ISSUE THREAD

**Issue by mshwery** [panva/node-oidc-provider#81]
I'm curious why the client callback/redirect uri is triggered by way of a form submission (initiated from page `onload`) as opposed to issuing a 302 redirect directly?

**Comment by panva** [comment]
Eh? Sorry you must be mistaken :) The way callback is handled is dictated by the response_mode you pass to your authentication request. If one isn't provided it is [resolved](https://github.com/panva/node-oidc-provider/blob/26bc4335345d694bfb72416c44614da451e598d3/lib/actions/authorization/check_response_mode.js#L15) automatically for you.

The three response modes supported are query, fragment (these are standard) and form_post (this is an [extension](https://openid.net/specs/oauth-v2-form-post-response-mode-1_0.html))

- response_mode=query and response_mode=fragment are [redirected with a 302](https://github.com/panva/node-oidc-provider/blob/26bc4335345d694bfb72416c44614da451e598d3/lib/actions/authorization/respond.js#L63-L66)
- [response_mode=form_post](https://openid.net/specs/oauth-v2-form-post-response-mode-1_0.html) is doing a form submission as it should

**Comment by mshwery** [comment]
@panva thanks for the clarification.

I was following the network requests from the example client that integrates with the example provider when I noticed this flow.

**Comment by panva** [comment]
It's using form post because it is a universal way of receiving the responses for all response types in your backend directly.
