### ISSUE TITLE
Custom Claims in RefreshToken

### ISSUE THREAD

**Issue by mihirvadalia** [panva/node-oidc-provider#811]
Hi Filip,

First of all, thank you for making this wonderful oidc provider library.

I was looking into the documentation and nothing I found about adding the extra claims in RefreshToken (Introspection).

ExtraClaims are there for AccessToken and UserInfo.

Can you please tell us about how to add Extra Claims in RefreshToken? And if it is in documentation, please give us that section hyperlink.

Thanks again!

**Comment by panva** [comment]
@mihirvadalia "extra claims for a refresh token for the purposes of introspection" is not an available capability.

**Comment by mihirvadalia** [comment]
Filip,

Can you give some pointers for which I can contribute on this?

I will do implementation and submit for your review. Hope that will be fine.

**Comment by panva** [comment]
@mihirvadalia thank you for the offer but I'm not looking for such feature at this point in time.
