### ISSUE TITLE
Question about requestable

### ISSUE THREAD

**Issue by jamespedid** [panva/node-oidc-provider#812]
Hello, I have a question about the requestable property of a prompt as I don't seem to see where it applies or how to use it properly.

Right now, I have the library working up to the point where I can sign in using the login and the consent form, and I added a select account form like in the example, however I'm not quite sure how to get this form to show up.

What I'm hoping to accomplish is the ability to follow a link to the authorize page that can be used to switch accounts. Right now when I log in, if the cookie is still present, it just goes through the flow to get a token without having an opportunity to switch users. I was under the impression that this is what the select_account interaction was supposed to do, but it doesn't seem to show. I'm not sure if that's due to a misconfiguration or if I have to leverage the requestable property and add something somewhere to force the user to go to the selectAccount view even if their cookie is still valid.

Can you provide any advice on how to accomplish this?

**Comment by panva** [comment]
You need to provide the prompt parameter to the authorization request
