### ISSUE TITLE
PAR with Encrypted Request Object

### ISSUE THREAD

**Issue by mihirvadalia** [panva/node-oidc-provider#813]
I was trying to send PAR request with **Encrypted** "request" object. But seems it is failing at below point of code, and code is only decoding the "request" object, not decrypting it. Can you please confirm, that PAR with Encrypted request object is supported or currently it is not supported?

node-oidc-provider/lib/actions/authorization/pushed_authorization_request_response.js 
```javascript
    ({ request } = ctx.oidc.body);
    const now = epochTime();
    const { payload: { exp } } = JWT.decode(request);
```

Error log is as per below:
```javascript
  oidc-provider:server_error:trace TypeError: invalid JWT.decode input
  oidc-provider:server_error:trace     at Function.decode (node-oidc-provider\node-oidc-product\node_modules\oidc-provider\lib\helpers\jwt.js:65:13)
  oidc-provider:server_error:trace     at pushedAuthorizationRequestResponse (node-oidc-provider\node-oidc-product\node_modules\oidc-provider\lib\actions\authorization\pushed_authorization_request_response.js:18:38)
```

FYI... The same Encrypted Request Object is working in Authorization Endpoint. It is not working only in Pushed Authorization Endpoint (PAR).

**Comment by mihirvadalia** [comment]
FYI... The same Encrypted Request Object is working in Authorization Endpoint. It is not working only in Pushed Authorization Endpoint (PAR).

**Comment by panva** [comment]
They are supported, this is simply a bug in the response middleware that's trying to default the par expiration to the "exp" of the request object, not taking encrypted objects into consideration. To be fixed.

**Comment by panva** [comment]
Thank you for bringing this up.

Please consider [supporting](https://github.com/panva/node-oidc-provider?sponsor=1) the library if it provides value to you or your company and this support was of help to you. Supporting the library means, amongst other things, that such support will be available in the future.
