### ISSUE TITLE
Revisiting UMA2

### ISSUE THREAD

**Issue by cjlpowers** [panva/node-oidc-provider#814]
Hey @panva, you discussed UMA2 in https://github.com/panva/node-oidc-provider/issues/307.
I would like to leverage this implementation but also need some UMA functionality. 
[MITREid Connect has an implementation](https://github.com/mitreid-connect/OpenID-Connect-Java-Spring-Server/tree/master/uma-server) but this project is more active.
Are you still looking for help on that and if so what is the level of effort you think would be required to support it?

**Comment by panva** [comment]
@cjlpowers My position has not changed since #307. I still have no immediate plans to support and maintain UMA2 functionality.
