### ISSUE TITLE
SessionNotFound when running through Docker container

### ISSUE THREAD

**Issue by hxhieu** [panva/node-oidc-provider#815]
Hi and thanks for the awesome provider.

So far it's been running well directly from command line such as `npm start`
We are using a Koa host.

However, after packaging the server as a Docker image, we keep getting `SessionNotFound` error
Here are some of the context
- Docker ports map 9001:7001
- Interaction flow okay, so we can see the login screen but as long as we post the login details back for further processing then the session is not found.

I am not sure if I have missed anything here, could anyone share some advice?

Many thanks,
H

**Comment by panva** [comment]
Either proxy setting or samesite cookie configuration.

**Comment by hxhieu** [comment]
@panva Thanks for the responses so we check and the cookies are passing along fine.
At the end it was something to do with the in-memory adapter, as soon as we swap to a persistent adapter it works well.
It looks like the memory cache dies really quick on the Docker container and we don't want to dig more since the in-memory just for development!

**Comment by panva** [comment]
Sigh.

**Comment by hxhieu** [comment]
Well I just note here so if anyone else is having the same issue then they would understand that they should not rely on the in-memory adapter even for the very early development i.e. persistent adapter all the way.
