### ISSUE TITLE
Token endpoint HS256 Cannot read property 'crv' of undefined

### ISSUE THREAD

**Issue by jamesacres** [panva/node-oidc-provider#816]
Most of the time POST /oidc/token is working as intended and returning 200.

But after some number of requests across multiple sessions, it starts returning 500 due to the following issue:
```
Cannot read property 'crv' of undefined
at /usr/src/app/node_modules/oidc-provider/lib/models/id_token.js:163:67
```

Client has both a client_secret and jwks_uri - which I suspect may be related looking at the lazy loading logic. I have not been able to find the cause yet and it is hard to reproduce as mostly it works then sometimes not, so creating this issue now while I continue to investigate.

Client configuration
```
{
        "client_name": "Dev",
        "client_id": "dev-client",
        "client_secret": "xxxxx",
        "token_endpoint_auth_method": "client_secret_post",
        "id_token_signed_response_alg": "HS256",
        "redirect_uris": [
          "https://xxxx/devClient/callback"
        ],
        "application_type": "web",
        "response_types": [
          "code"
        ],
        "grant_types": [
          "client_credentials",
          "authorization_code",
          "refresh_token"
        ],
       jwks_uri: "https://xxxx/jwks"
       cors_origins: "https://xxxx"
}
```

I do have some logic to skip the consent which may be related.
```
            session.ensureClientContainer(client.clientId);
            session.promptedScopesFor(params.client_id, oidc.requestParamScopes);
            session.promptedClaimsFor(params.client_id, oidc.requestParamClaims);
```

I have done some debugging:

```
          console.info('from client');
          ({ keystore } = client);
        } else {
          console.info('from provider');
          ({ keystore } = instance(provider));
        }   

        const key = keystore && keystore.get({ alg, use: 'sig' }); 

        console.info('keystore', keystore);
        console.info('alg', alg);
        console.info('key', key);
```

most of the time it works, and outputs:
```
2020-11-10T10:42:05.192Z info: 	from client
2020-11-10T10:42:05.195Z info: 	keystore {"_keys":{},"freshUntil":1605004939}
2020-11-10T10:42:05.195Z info: 	alg HS256
2020-11-10T10:42:05.195Z info: 	key {"alg":"HS256","use":"sig","kid":"udG9i7XoSu3qPjRX69_1vQcX3AXys_jqdt3cRTtExc8","kty":"oct"}
```

when the error happens it outputs:
```
2020-11-10T12:23:29.694Z info: 	from client
2020-11-10T12:23:29.695Z info: 	keystore {"_keys":{},"freshUntil":1605011029}
2020-11-10T12:23:29.695Z info: 	alg HS256
2020-11-10T12:23:29.695Z info: 	key
```

**Environment:**
 - oidc-provider version: 6.29.1
 - node version: v12.18.2

**Comment by panva** [comment]
Can you go ahead and post the FULL stack trace too?

**Comment by panva** [comment]
Found it, fixed in 6.29.7. Thank you for bringing this up.

**Comment by panva** [comment]
Please consider [supporting](https://github.com/panva/node-oidc-provider?sponsor=1) the library if it provides value to you or your company and this support was of help to you. Supporting the library means, amongst other things, that such support will be available in the future.

**Comment by jamesacres** [comment]
Many thanks for the super speedy fix! Much appreciated, I will raise supporting with my team.
