### ISSUE TITLE
Correlation between access-token and id-token?

### ISSUE THREAD

**Issue by param-artha** [panva/node-oidc-provider#817]
Is there any correlation between the generated id-token and access-token? We are trying to invalidate the id-token once the user logs out. It looks like every time a new session is created, access-token gets saved and it also gets deleted once the session expires or if the user logs out. 

But is there a way for our service middleware to look at the id-token and cross-reference in the access-token collection to check if the session is still active? 

The only other way I can think of is by adding a custom claim and adding session-id to the custom claim and somehow figure out/guess the claim value in the logout call.

Thx!

**Comment by panva** [comment]
An ID token is not used to access any resources hence needs no invalidation. Furthermore it is only used to establish new client sessions with csrf and replay protections in place so that it cannot be "replayed" to reestablish sessions.

**Comment by panva** [comment]
In other words your question indicates you're not using the artifacts as they should be used and it is therefore out of scope for me to look into it any further.

**Comment by param-artha** [comment]
@panva Thanks! I was just using the examples from [Auth0](https://auth0.com/docs/quickstart/backend/nodejs/01-authorization#validate-access-tokens) and they were using JWTs for gaining resource access, so the confusion.

**Comment by panva** [comment]
> @panva Thanks! I was just using the examples from [Auth0](https://auth0.com/docs/quickstart/backend/nodejs/01-authorization#validate-access-tokens) and they were using JWTs for gaining resource access, so the confusion.  

JWT Access Token is not an ID Token. These are completely different artifacts intended for different uses.

**Comment by param-artha** [comment]
Isn't id-token a JWT?

So if I understand correctly, I can set the configuration "formats.AccessToken" to "jwt" to get a JWT correct?

**Comment by panva** [comment]
Yes, it's a JWT. But not one profiled or purposes to access resources.
