### ISSUE TITLE
Remove sub from logout token

### ISSUE THREAD

**Issue by EdouardPauw** [panva/node-oidc-provider#818]
Hi Panva,

The OpenID spec says : "A Logout Token MUST contain either a sub or a sid Claim, and MAY contain both."
We have enabled the 'backchannel_logout_session_required' attribute and we now get both 'sub' and 'sid' in the logout token.

But we are wondering if there is a way to remove the 'sub' attribute from the logout token ? We would like to avoid implementation errors from the RPs.

**Comment by panva** [comment]
There's no way at the moment.
