### ISSUE TITLE
authorization_code flow web clients using localhost in redirect_uri

### ISSUE THREAD

**Issue by mshwery** [panva/node-oidc-provider#82]
When starting up an `oidc-provider` application I get this during `oidc.initialize()` due to a client configuration:

```js
const clients = [
  {
    application_type: 'web',
    client_id: 'foo',
    client_secret: 'bar',
    grant_types: [
      'authorization_code',
      'refresh_token'
    ],
    response_types: [
      'code'
    ],
    redirect_uris: [
      'http://localhost:3001/login/oidc/callback'
    ],

    /**
     * Session management attributes
     * @see {@link http://openid.net/specs/openid-connect-session-1_0.html#RPLogout}
     */
    post_logout_redirect_uris: [
      'http://localhost:3001'
    ]
  }
]
```

When I change the `redirect_uris` value to a non-`localhost` uri it works fine. Why exclude same domain (especially when its not the same-origin: different subdomain or different port)?

**Comment by panva** [comment]
You may be right, this restriction might only apply to web clients when they use implicit flow (section 3.2.2.1 of core) so i may relax the rules there to reflect this.

Nevertheless, when working with localhost just use lvh.me or similar always-localhost domain, alternatively a dev server like pow to create your own something.dev pointing to localhost.

**Comment by mshwery** [comment]
Yep, I created an alias to get around this issue. Thanks!

**Comment by panva** [comment]
> Why exclude same domain (especially when its not the same-origin: different subdomain or different port)?

This part i don't get all. There is no same domain concept between OP and RP. They are separate entities and there are no exception to how redirect_uris are validated.

**Comment by mshwery** [comment]
@panva I may have been mistaken by what's actually being validated and throwing the exception – I thought it was the usage of the same domain `localhost` that was causing the issue (both the provider and the client were running on different ports for that origin).

**Comment by panva** [comment]
6b1f75d + ed3ff60a relaxed localhost for non-implicit web clients

**Comment by mshwery** [comment]
Awesome thanks.
