### ISSUE TITLE
Error trying to integrate microsoft authenticator

### ISSUE THREAD

**Issue by lucas-aragno** [panva/node-oidc-provider#820]
Hello there! Thanks for this amazing library. I'm trying to integrate my openID connect protocol to MS authenticator. For what I understand is pretty simple if I already have an oidc server set up. But I'm having and issue using my server and is that I need to redirect to a `vcclient://openid` url and this client throws a `redirect_uris must only contain web uris'` Is there any way to bypass this? I could make my own fork and remove the check or add vcclient to the parsing rules but I don't want to deal with updating my fork whenever an update happens on the main repo.

Thanks!

**Comment by panva** [comment]
That url is a native application url, so setting the application_type to native would be the way to go. If only microsoft followed the BCP when it comes to custom uri schemes in that they should be domain schemes.

Anyway. Here's a way for you to go forward. Don't whitelist this url at all and overload the client prototype method for checking if a url is allowed or not.

```js
const { redirectUriAllowed } = provider.Client.prototype;
provider.Client.prototype.redirectUriAllowed = function wildcardRedirectUriAllowed(redirectUri) {
  if (this.clientId === 'expectedvalue' && redirectUri === 'vcclient://openid') {
    return true; // bypass checking the declared whitelist
  }
  return redirectUriAllowed.call(this, redirectUri);
};
```

**Comment by panva** [comment]
Please consider [supporting](https://github.com/panva/node-oidc-provider?sponsor=1) the library if it provides value to you or your company and this support was of help to you. Supporting the library means, amongst other things, that such support will be available in the future.
