### ISSUE TITLE
Is it possible to respond with response_type code after authorization instead of redirecting?

### ISSUE THREAD

**Issue by Pahicz** [panva/node-oidc-provider#822]
I have a windows native app (game in Unreal Engine). I would like integrate the game with oidc, the problem is that in the game you cannot use redirect_uri. 

I would like to receive the response_type code in response after authorizing(in response body or header) instead of redirecting to the redirect_uri.

I found out that interactionFinished helper method is redirecting to /auth/uid with does some magic under the hood and makes the redirect.
Is it possible to change interactionFinished helper and return code from there or must the redirect to /auth/uid be done?

**Comment by panva** [comment]
It is not possible to mutilate the very core protocol. But any application can pose as a native application and get a redirect to a custom scheme uri.
