### ISSUE TITLE
Why array of values are not supported for audience in access token?

### ISSUE THREAD

**Issue by chungath** [panva/node-oidc-provider#823]
The documentation for [audiences](https://github.com/panva/node-oidc-provider/tree/master/docs#audiences)  says the following.

`array of string aud values (it is supported but NOT RECOMMENDED, consider it DEPRECATED)
`

Wanted to understand why it is to be considered as deprecated. Does the openid spec not allow  audiences as arrays?

Thanks.....

**Comment by panva** [comment]
It is to be considered deprecated because moving forward, in v7.x it will no longer be even possible. I do not wish to support these cases any longer.

**Comment by chungath** [comment]
Thanks for the quick reply.

My question was mainly to understand why you do not want to support these any longer. Is this feature(array of string aud values) deviating from the openid specs?

**Comment by panva** [comment]
openid does not deal with access token audiences at all. oauth2, resource indicators specification and the oauth2 security topics bcp does.

While it is within the "allowed" realm, it is a complicated topic and in my opinion, a smell. That's why I will not be supporting it any further.
