### ISSUE TITLE
JWKS key generation examples in documentation use jose@2

### ISSUE THREAD

**Issue by ctavan** [panva/node-oidc-provider#826]
The examples in https://github.com/panva/node-oidc-provider/blob/master/docs/README.md#jwks make use of `jose@2`. With `jose@3` being the latest npm tag now, these examples no longer work when users `npm install jose` explicitly and try to run the examples. They still do work of course when run in a repository where `oidc-provider` is installed which pulls `jose@2` as a dependency and where the user did not manually run `npm install jose`.

I'm not sure what the best way forward is and I don't think it's a huge problem, I just stumbled on this one recently and it may confuse other users of this library as well.

**Comment by panva** [comment]
Thank you for bringing this up.

**Comment by alexanderankin** [comment]
Is this possible? I just read that jose 3 is a totally different library on the jose discussions, like different api and supported feature set.

**Comment by panva** [comment]
@alexanderankin see 006f654, `jose@2` remains a [supported](https://github.com/panva/jose#supported-versions) and stable module.
