### ISSUE TITLE
How to change specified .well-known/openid-configuration endpoints when serving under prefixed location with nginx?

### ISSUE THREAD

**Issue by omizrahi99** [panva/node-oidc-provider#827]
First of all, thank you for creating such an amazing and intuitive library.

I am working off of example 03-oidc-views-accounts from the step-by-step examples. I have the application running behind an nginx proxy with a location prefix of "/oidc/". The server block is shown below:

```
server {
    listen 80;
    server_name ${SERVER_NAME};
    location /oidc/ {
        proxy_pass_header Server;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;

        proxy_connect_timeout 10;
        proxy_read_timeout 10;
        proxy_pass http://localhost:3001/;
    }
    location / {
        // parameters for app being served at "/"
    }
   // ssl configurations here
}
```

In the node app, I set the interactions url like so:

```
interactions: {
    url(ctx) {
      return `/oidc/interaction/${ctx.oidc.uid}`;
    },
  }
```

Everything so far works as it is supposed to, but the endpoints specified at http://${SERVER_NAME}/oidc/.well-known/openid-configuration return urls without the /oidc prefix. For example, it is specifying the token endpoint to be "http://${SERVER_NAME}/token" instead of "http://${SERVER_NAME}/oidc/token". What is the best fix for this? Thanks!

**Comment by panva** [comment]
Your only option is to mimic the prefix by applying the same one to your Provider instance.
