### ISSUE TITLE
Authentication on provider server

### ISSUE THREAD

**Issue by AkanshDivker** [panva/node-oidc-provider#828]
Hi,

I'm pretty new with all this so this might be a stupid question, just trying to get a better understanding. I need to make an identity provider server, but I'm not sure how to go about some steps after that. If I create an identity provider server using node-oidc-provider, do I also need oidc-client to authenticate through myself?

I can't figure out how to let users login to my service and be available as an identity provider through node-oidc-provider. I have a login/registration system setup but I'm not sure how to get it going with this. Certain routes are protected that require login for my service, so I was wondering if it was possible for me to do this all through oidc-provider or if I also need to use oidc-client for the same server.

Main thing I'm confused on it, logging in and using my service through the provider library, and protecting routes through the same way. For example, `/profile` or `/admin` route should require being logged in/authenticated and verified to access.

**Comment by panva** [comment]
> I'm pretty new with all this so this might be a stupid question, just trying to get a better understanding.

This is not the venue to learn about oidc, it's actors and terminology. That would be the specs, the numerous material on the internet, or workshops. 

This package is for exposing the oidc interfaces/protocols. If within the same server you have other maintanence or user management routes, those are to be authenticated using e.g. using the oidc interface or any oob means that may or may not utilize the session established by the provider. That is however beyond my capacity to support on. You may be in luck if you search the faq's or prior issues in the tracker.
