### ISSUE TITLE
Session is persisted across multiple logins

### ISSUE THREAD

**Issue by leandrosandoval** [panva/node-oidc-provider#831]
I'm getting started with this library and I seem to have an issue in which after a successful login (a successful prompt = login interaction and then a successful prompt = consent interaction) if I restart the flow the app is skipping the login and going straight to consent. Seems like this is related to the KOA session being stored on the cookie. Is there a way to always force the user to perform a login? Maybe removing the cookie or something like that?
Thanks in advance.

**Comment by panva** [comment]
Hi @leandrosandoval 

> I seem to have an issue

You're actually exhibit behaviour that the majority of implementers want to have.

The library does not out of the box cater to experiences without SSO, without persisted sessions.

You can get the experience you want through various extensibility means - pre/post middlewares, emitted events, etc. When you get around to implement that just make sure you don't bind your tokens to the session you're going to be dropping.
