### ISSUE TITLE
Indicating user doesn't exist

### ISSUE THREAD

**Issue by mikesir87** [panva/node-oidc-provider#832]
I've written a `findAccount` that returns `undefined` (and have tried `null`) if an account isn't found. However, while doing the login using the `devInteraction` feature enabled, login continues and the token exchange fails. It would be nice if the unknown user case failed earlier on. Or, am I doing something wrong? Or is this a limitation of using the built-in dev interactions? Any guidance would be appreciated! 😄

**Comment by panva** [comment]
yes, you should stop using dev interactions. They don't use your findAccount method at all
