### ISSUE TITLE
How to Fix ERR_TOO_MANY_REDIR

### ISSUE THREAD

**Issue by taraa62** [panva/node-oidc-provider#837]
I use openid-client + openid-provider and have problem with error - ERR_TOO_MANY_REDIR.
It happens when I call an endpoint  `'/auth/callback'` and then backend call a callback `'/auth/callback'`. 

Can you pleace check my test configuration [here](https://gist.github.com/taraa62/184015edf0a2f8faf92f407abc45c646).

--------
node: 14.10.1
oidc-provider: ^6.29.8
openid-client: ^4.2.2

**Comment by panva** [comment]
You're using hybrid response type which responds in a fragment, so the client can't read the callback params. Stick with code response type only or make adjustments to switch to form_post response mode.

**Comment by taraa62** [comment]
Can you help me find a way for the server to send me refresh_token?
І don't understand way server remove offline_access scope and this
` MUST ignore the offline_access request unless the Client is using a response_type value that
   *  would result in an Authorization Code being returned,`

Which are response_type and other params return refresh_token?

**Comment by panva** [comment]
https://github.com/panva/node-oidc-provider/blob/master/docs/README.md#refresh-tokens
