### ISSUE TITLE
SessionNotFound: invalid_request

### ISSUE THREAD

**Issue by AlijiEmmanuel-dev** [panva/node-oidc-provider#839]
I was using the default in memory adapter during testing. I use an spa vue front end for all my interactions, the SPA get loaded at the resolved interaction.
After building my adapter with mongoose with connection working, in fact I node OIDC-Provider was able to save the interaction object to the database, every time I try to test the server, I get the following error.
Can you please tell me the possible causes.

SessionNotFound: invalid_request
    at Provider.getInteraction (C:\projects\VOIP\backend\auth\node_modules\oidc-provider\lib\provider.js:54:11)
    at process._tickCallback (internal/process/next_tick.js:68:7)

**Comment by panva** [comment]
Hi @AlijiEmmanuel-dev,

so you implemented an adapter and things stopped working, I don't see how I can possibly help. It's your adapter implementation, debug it.
