### ISSUE TITLE
Session management doesn't remove access tokens

### ISSUE THREAD

**Issue by darbio** [panva/node-oidc-provider#84]
I'm following your getting started tutorials, and noticed that when I perform an 'end session' with the provider, the code doesn't remove the access tokens associated with that session.

This seems to be because `grantId` never gets populated on payload (it always is nothing when dealing with sessions). This means that when `destroy` is called, and it looks for a property called `grantId` on the session, it doesn't exist.

https://github.com/panva/node-oidc-provider/blob/master/example/adapters/redis.js

Is there a way to fix this?

**Comment by panva** [comment]
It is not the end session's intention to automatically remove active tokens, as a matter of fact, session management does not mention other tokens at all. A client initiating the logout can easily toss out the tokens and ensure they are revoked using the revocation endpoint. Clients that aren't initiating the logout can be notified about logout using backchannel (supported) or frontchannel (not supported) specs.

Enforcing all token invalidations can be your OP specific behavior and can likely be achieved by registering a listener for the `end_session.success`.

**Comment by darbio** [comment]
Ok. My misunderstanding. I'll do that.
