### ISSUE TITLE
SessionNotFound: invalid_request: ....provider.js:54:11

### ISSUE THREAD

**Issue by AlijiEmmanuel-dev** [panva/node-oidc-provider#840]
This is my setup, 
I have a mongoose MongoDB client, I have set up the session schema declaration like this:
`
const SessionSchema = new mongoose.Schema({
    id: String,
    grantId: String,
    payload: Object,
    uid: String,
    data: Object,
    expiresAt: Date,
    consumedAt: Date
});
`

my interaction URL stays at default: ` /interaction/${ctx.oidc.uid};`

This is the express URL handler code. 
`   
 app.get('/interaction/:uid', setNoCache, async (req, res, next) => {

    try {

      const {
        uid, prompt, params, session
      } = await provider.interactionDetails(req, res);

      const client = await provider.Client.find(params.client_id);

      let interaction  = {
        uid: uid,
        client: client,
        prompt: prompt,
        params: params,
        session: session? true : undefined,
        email: sessEmail? true: undefined,
        details: prompt.details,
      };

      interactionStore.set(uid, interaction); 

      res.render('index', {interactions: interaction});

    } catch (err) {
      return next(err);
    }
  });
`

Note: on the mongo DB, I can confirm interactions data is persisted to the DB.
Note: the mongo DB only creates the interaction schema, here is my mongo DB Adapter Logic.
`
const PushedAuthorizationRequest = mongoose.model('PushedAuthorizationRequest');
const AccessToken = mongoose.model('AccessToken');
const AuthorizationCode = mongoose.model('AuthorizationCode');
const DeviceCode = mongoose.model('DeviceCode');
const ClientCredentials = mongoose.model('ClientCredentials');
const Client = mongoose.model('Client');
const InitialAccessToken = mongoose.model('InitialAccessToken');
const Interaction = mongoose.model('Interaction');
const RefreshToken = mongoose.model('RefreshToken');
const RegistrationAccessToken = mongoose.model('RegistrationAccessToken');
const ReplayDetection = mongoose.model('ReplayDetection');
const Session = mongoose.model('Session');

 var modelMap  = new Map();
 modelMap.set('Session', Session);
 modelMap.set('AccessToken', AccessToken);
 modelMap.set('AuthorizationCode', AuthorizationCode);
 modelMap.set('RefreshToken', RefreshToken);
 modelMap.set('DeviceCode', DeviceCode);
 modelMap.set('ClientCredentials', ClientCredentials);
 modelMap.set('Client', Client);
 modelMap.set('InitialAccessToken', InitialAccessToken);
 modelMap.set('RegistrationAccessToken', RegistrationAccessToken);
 modelMap.set('Interaction', Interaction);
 modelMap.set('ReplayDetection', ReplayDetection);
 modelMap.set('PushedAuthorizationRequest', PushedAuthorizationRequest);
`

and the constructor.
`  
constructor(name) {
    this.model = modelMap.get(name);
    this.name = name;
  }
`

The full error shown is.
`
SessionNotFound: invalid_request
    at Provider.getInteraction (C:\projects\VOIP\backend\auth\node_modules\oidc-provider\lib\provider.js:54:11)
    at process._tickCallback (internal/process/next_tick.js:68:7)
`

Please, I need your help.

**Comment by panva** [comment]
https://github.com/panva/node-oidc-provider/issues/839#issuecomment-744416036

Please, don't open the same issue again. If the only thing you're changing is the adapter, then the answer is in your adapter.

**Comment by AlijiEmmanuel-dev** [comment]
Ok, thank you so much for your fast response. I didn't realize you replied.
