### ISSUE TITLE
Use oidc-provider with keycloak

### ISSUE THREAD

**Issue by kedevked** [panva/node-oidc-provider#841]
Hi, 

I am trying to use the library with nestjs. I rewrote the findAccount to accept whatever the user and password are. The callback after the login comes with a query parameter `error=access_denied` . Maybe could you please provide some insights on what I am doing wrong?
Here is the repo for reproductibility:  https://github.com/kedevked/nest-oidc-provider
test url : http://localhost:3000/oidc/auth?client_id=foo&response_type=code

Thanks

**Comment by panva** [comment]
> Maybe could you please provide some insights on what I am doing wrong?

Your request does not include a scope and the request does not "resolve and default to" one. The error detail if you were to log it (e.g. through following the debugging section) would tell you.

**Comment by kedevked** [comment]
Including a scope in the request, I still have the access denied. You mean that the request is using default route handlers ? 

using the debug,

I have the following: 
```
uid=zFqV0ZNk_HZKFoaHrS83f interaction=Interaction { returnTo: 'http://localhost:3000/oidc/auth/zFqV0ZNk_HZKFoaHrS83f', prompt: { name: 'login', reasons: [ 'no_session' ], details: { max_age: undefined, login_hint: undefined, id_token_hint: undefined } }, lastSubmission: undefined, uid: 'zFqV0ZNk_HZKFoaHrS83f', params: { client_id: 'foo', redirect_uri: 'http://localhost:4200', response_type: 'code' }, signed: undefined, session: undefined, kind: 'Interaction', jti: 'zFqV0ZNk_HZKFoaHrS83f', exp: 1607970693 }
```

**Comment by panva** [comment]
Your interaction params log no scope parameter. So yeah, you are not requesting nor resolving a scope.

**Comment by kedevked** [comment]
Yeah, that's it. Thanks !
