### ISSUE TITLE
findAccount not called on /auth?response_type=code&client_id=test

### ISSUE THREAD

**Issue by coliveirabsg** [panva/node-oidc-provider#851]
**Describe the bug**
`findAccount` is not called on `/auth` requests

Following the code, Provider.Client.find(id) method searches for the id on the static and dynamic caches, but never falls back on findAccount to find the Account.
If the `client_id` is added to the `clients`, on the `configuration`, the flow proceeds to login as expected.

**To Reproduce**
```
// From the documentation (merged the 2 relevant code snippets):

const { Provider } = require('oidc-provider');
const configuration = {
  async findAccount(ctx, id) {
    console.log(`Called findAccount: ${id}`);
    return {
      accountId: id,
      async claims(use, scope) { return { sub: id }; },
    };
  }
};

const oidc = new Provider('http://localhost:3000', configuration);

// or just expose a server standalone, see /examples/standalone.js
const server = oidc.listen(3000, () => {
  console.log('oidc-provider listening on port 3000, check http://localhost:3000/.well-known/openid-configuration');
});
```

Steps to reproduce the behaviour:

1.  Run the code snippet above
2. Browse to `http://localhost:3000/auth?response_type=code&client_id=test`

**Expected behaviour**
1. The console outputs `Called findAccount: test`
2. The browser proceeds to the login

**Environment:**
 - oidc-provider version: [e.g. v6.29.9]
 - node version: [e.g. v12.18.2]

**Comment by panva** [comment]
Why would find**Account** be called to load **Client** configuration?

**Comment by coliveirabsg** [comment]
I missed something while digging into the code.
The provided snippet or the included express.js example does not work:
1. run the provided `express` example: `node examples/express.js`
2. expose port 3000 to the outworld
3. Test with `https://openidconnect.net`

**Comment by panva** [comment]
The examples work as intended, it's your usage approach that doesn't.
