### ISSUE TITLE
Login interaction details

### ISSUE THREAD

**Issue by HNicolas** [panva/node-oidc-provider#853]
https://github.com/panva/node-oidc-provider/blob/2f9def003ee3194588f98947abeadea12996ef76/lib/helpers/interaction_policy/prompts/login/index.js#L18-L22

Hello,
I think there is an error in the order of the ternary expressions : in the final object the value is set when it is undefined and omitted when it is defined.

**Comment by panva** [comment]
It sure is, care to open a PR?

**Comment by HNicolas** [comment]
It's done.
