### ISSUE TITLE
Non json response returned from /keys endpoint

### ISSUE THREAD

**Issue by goranpavlovicptc** [panva/node-oidc-provider#856]
Under high load, the call to 

https://express-oidc-provider.someurl.com/discovery/keys 

causes this error in ambassador oauth2 filter

"HTTP 500 invalid character 'u' looking for beginning of value"

This error is a result of an app expecting json response but getting something else. Like a default html response...Or stack trace...

So what happens (most likely) is that when we call /keys under load, some error is not handled properly, and oidc provider returns non json error response, which ambassador doesn’t know what to do with.

Can you please check that all errors are handled correctly inside the keys code?

**Comment by panva** [comment]
@goranpavlovicptc I have no idea what ambassador oauth2 filter is. The provider does a very simple JSON serialization of the keys it has in memory. If you're under load it is possible your deployment can't keep up. Your proxy may have a timeout on the provider response and it doesn't come in time and the proxy then returns its standard e.g. 504 gateway timeout. That's normal, you should scale your deployment to fit the incoming traffic. 

All errors in this endpoint are handled correctly and no html error is ever returned to a non-html request.
