### ISSUE TITLE
Where to implement consent screen?

### ISSUE THREAD

**Issue by mihaerzen** [panva/node-oidc-provider#86]
Hi!

I'm trying to implement oidc into our app for authorization. I haven't really understood how I can implement the consent screen when user is already authenticated similar to this:

<img src="https://www.packtpub.com/sites/default/files/Article-Images/B03653_02_02.png" alt="facebook consent screen" width=300/>

Where would be the correct place to implement the consent screen OR is there a configuration that already enables that? Is there a way for user to disable certain request for claims?

Thank you very much for any answer / input.

**Comment by panva** [comment]
oidc-provider is an implementation of the protocol, not user management, not user views, not consent screens and newsletter signups.

You are encouraged to implement your own unique-looking and functioning user flows. The development interactions bundled must be disabled (features.devInteractions) and you must provide your own views. The devInteractions provide absolutely no basis for a production ready system on purpose (no csrf, no brute force prot, no signup).

See https://github.com/panva/node-oidc-provider/blob/master/docs/configuration.md#interaction

**Comment by panva** [comment]
`interactionUrl` configuration option helps you to customize where the OP redirects the user when interactions are needed
`interactionCheck` configuraiton option helps you to customize the final interaction check, to possible skip or enforce an interactio based on your business rules.
