### ISSUE TITLE
Best way to logout from oidc

### ISSUE THREAD

**Issue by cguedes** [panva/node-oidc-provider#87]
I have been using OIDC integrated with my API (not deployed as an external server), and I want to sync the logout on OIDC with the API logout.

I haven't found documentation on how to do this in this scenario.

To mitigate this, I've configured a well-known session cookie name for OIDC, and upon logout, I'm also removing that cookie. Not sure this is the correct way to implement this.

**Comment by panva** [comment]
In brief, [Session Management](http://openid.net/specs/openid-connect-session-1_0.html) (supported by oidc-provider) defines how RP should initiate a logout. 

Logging out a user outside of openid connect scope (i.e. API???) is up to you, you may clear the cookies oidc-provider relies upon (but how when you're doing a backend to backend api call? and if not, why not use session management) or just delete the session in your backend (you provided an adapter for it).

**Comment by cguedes** [comment]
I understand your point.

So maybe I should do the [RP-Initiated Logout](http://openid.net/specs/openid-connect-session-1_0.html#RPLogout) flow using a `post_logout_redirect_uri` to get back to the RP. 

Do you have support for this `post_logout_redirect_uri` right?

**Comment by panva** [comment]
Yes, sessionManagement feature flag. 

Beware the specification covering the feature is still draft and so using ~ in your package.json is thefore recommended as changes to draft updates may be backwards incompatible.
