### ISSUE TITLE
Session object stays after successful logout

### ISSUE THREAD

**Issue by slavab89** [panva/node-oidc-provider#88]
I've started using your module and building the example on my end.
Using mongo as a backend to save all the needed data.

I've notices that my Session collection does not clean up after a logout. Although the "destroy session" is being called, because of the nature of session middleware https://github.com/panva/node-oidc-provider/blob/60ff0d889294346290b42858387cc21064b6fc8a/lib/shared/session.js#L16, The session is being saved once again to the DB

The `yield next` calls for the end_session function and after doing that, it saves the session once more.
```javascript
const endSession = getEndSession(this);
get('end_session', routes.end_session, error(this, 'end_session.error'), session, endSession.get);
post(routes.end_session, error(this, 'end_session.error'), session, endSession.post);
```

**Comment by panva** [comment]
Hey @slavab89,
That's a great find, does it also create a new session object and leave the old one not used? Or does it clear the object's payload and just reuses the same session id?

**Comment by slavab89** [comment]
It saves the whole payload like it was before the removal - with the logout details, account, loginTs, authorizations etc. Uses the same session id like before.

Just for clarification, it happens during a full logout from the OP.

**Comment by panva** [comment]
Interesting. but how come the user is actually logged out?

**Comment by slavab89** [comment]
Not 100%.
It followed the client example. Did a `client.revoke(access_token)` followed by `res.redirect(issuer.end_session_endpoint?.....)`.

Thanks a lot for the modification 😃
