### ISSUE TITLE
Why does the Provider initialization require an "issuer" URI?

### ISSUE THREAD

**Issue by mshwery** [panva/node-oidc-provider#89]
One of the minor nitpicks about initializing a `new Provider` is that it requires knowledge of where it is mounted. Presumably this is to help establish the `.well-known` configuration information that is publicly exposed – is that accurate?

What's inconvenient about this is that you now need to either provide a hard-coded value or an environment variable for the URI despite operating the same server in different environments (e.g. localhost vs qa vs production).

Is it possible to omit that URI value and use relative paths? Am I missing some other context?

**Comment by panva** [comment]
I am sorry but I don't really follow your train of thought, are you asking why is `issuer` value a mandatory property?

**Comment by mshwery** [comment]
Yes, "issuer" being a URI where the app itself is hosted.

**Comment by panva** [comment]
For one it's an Identifier of your server, it is not a value that should change depending on the requested hostname and it is not meant to be dynamic. That's why it's required and must be a valid issuer format (web uri with no query and fragment).

And it has little to do with the hostname the app is exposed on. The issuer value is pushed to tokens and e.g. Dynamic Profile clients will be validating that the issuer value they discovered via configuration is in the token claims.

**Comment by mshwery** [comment]
Yeah I'm not suggesting that it be _dynamic_ per se. I don't envision that you would ever want it to change. But each environment may have a completely different origin: e.g. `http://localhost:3000`, `https://staging-oidc-provider.example.com`, `https://oidc-provider.example.com`.

>And it has little to do with the hostname the app is exposed on

I don't quite understand this comment. It seems the answer is that you are required to configure the ISSUER uri to explicitly match the server origin.

**Comment by panva** [comment]
> Yeah I'm not suggesting that it be _dynamic_ per se. I don't envision that you would ever want it to change. But each environment may have a completely different origin: e.g. `http://localhost:3000`, `https://staging-oidc-provider.example.com`, `https://oidc-provider.example.com`.

I am aware of that, they are all different issuers with their own identifiers, their configuration may vary and if a PROD client is validating a token from QA it should not pass validations.


> I don't quite understand this comment. It seems the answer is that you are required to configure the ISSUER uri to explicitly match the server origin.

That is not true. In my side project setup my issuer setup is like so, the issuer value i configure is `https://issuer.example.com`. And i make the server available via `*.example.com`. This means regardless of which subdomain you hit the discovered issuer value will be the same (as it should be!) but the rest of the discovered endpoints will follow the current requested hostname, allowing me to change e.g. the interaction look and feel.

Same applies to mounting the provider app to a path in a bigger express/koa application, e.g. to `/oidc`. Your issuer can remain "nice" without a path then, so long as you handle routing the well known requests to /oidc too. There's a section on that in the configuration file.

**Comment by mshwery** [comment]
Ah, interesting. That's good to know. My resistance to it was a misunderstanding of what that value represents.

Thanks for clarifying!

**Comment by amaciver** [comment]
@panva Would you mind providing a brief explanation of your statement?

> This means regardless of which subdomain you hit the discovered issuer value will be the same (as it should be!) but the rest of the discovered endpoints will follow the current requested hostname

It seems that many large OPs allow for issuer to be pegged to the subdomain used by the tenant, ostensibly because many OIDC clients validate the issuer against the discovery endpoint. Would love to know more about your thinking and whether dynamic issuer is something you have ever considered.

Thanks

**Comment by panva** [comment]
Hi @amaciver, I have not, will not. One `Provider` instance is for exactly one issuer identifier. To run multiple in one process, just instantiate more and mount/route accordingly. That's outside of my support scope tho.
