### ISSUE TITLE
Gitter channel?

### ISSUE THREAD

**Issue by mshwery** [panva/node-oidc-provider#90]
@panva it might be nice to have an open room on [gitter](https://gitter.im/) for chatting about some questions and patterns. Thoughts?

**Comment by panva** [comment]
Not sure what it brings or what's expected of me there > https://gitter.im/node-oidc-provider

I would prefer that patterns get to a github wiki or ultimately, the documentation.

**Comment by mshwery** [comment]
Yeah, I agree (and am happy to contribute to the repo). You certainly don't need to feel obligated to use gitter or keep an open room. It might be nice if there are people using this library to be able to talk about usage patterns and flows.

Honestly, I feel like I have too many questions to ask all via github issues. But perhaps the question/answer forum is nicer via github issues because it is documented and less ephemeral.
