### ISSUE TITLE
Issue : Inconsistency with cert and .well-know endpoints 

### ISSUE THREAD

**Issue by codestorycooked** [panva/node-oidc-provider#904]
**Describe the bug**

We are using oidc-provider library `6.23.2` with custom oidc configuration for cert endpoint and default for well-known endpoint.  Recently our security scanning reported some inconsistency with these endpoints and the way it can be accessed.
example; 
cert endpoint can be accessed (and is also reproducible with a default route of jwks)
http://localhost:3000/certs
http://localhost:3000/ce
http://localhost:3000/cer
http://localhost:3000/cert

Whenever above endpoints are invoked we get the certificates without error. Though we have configured it as below:

```
 routes: {
                jwks: '/certs'
            },
```
Similarly, .well-known endpoint can be accessed:
http://localhost:3000/.w
http://localhost:3000/.well
http://localhost:3000/.well-know
.... and adding each character it works
http://localhost:3000/.well-known/openid-configuration

We tested this with standalone.js sample which is provided in the library 
https://github.com/panva/node-oidc-provider/tree/v6.23.2/example 

Note: This is happening only with this specific version of the library. Is there a way to fix this with some extension point? 

**To Reproduce**
Provider and Client configuration: (inline or gist)
```js


// provider configuration
```
 routes: {
                jwks: '/certs'
            },
```
// keystore(s) - if they affect the behaviour

// client(s) configuration

```

Steps to reproduce the behaviour:

1. Clone: https://github.com/panva/node-oidc-provider/tree/v6.23.2
2. got to the example folder
3. run node stanalone.js

**Expected behaviour**
It should output invalid route message

**Environment:**
 - oidc-provider version: 6.23.2
 - node version: 12.x

**Additional context**

 - [ ] the bug is happening on latest oidc-provider too.
 - [x] i have tried DEBUG (see README) and can see the issue is with the provider and not my code.
 - [x] i have searched the issues tracker on github for similar issues and couldn't find anything related.
 - [x] i have searched the [FAQ](https://github.com/panva/node-oidc-provider/blob/master/docs/README.md#faq) and couldn't find anything related.

**Logs**

**Comment by panva** [comment]
Upgrade to a more recent release where this was already fixed. I don't get the point of this issue given that you've figured out its fixed on latest.
