### ISSUE TITLE
JSON Cookies URI Escaping?

### ISSUE THREAD

**Issue by andrewrod33** [panva/node-oidc-provider#91]
I've been using this module recently and have had issues with the cookie parsing (since the JSON is not URI escaped). I've forked the project (https://github.com/panva/node-oidc-provider/compare/master...andrewrod33:cookies_encoding_and_decoding) and URI escaped and unescaped the piece of the project I'm using so far and it works ok.  What do you think about this being changed for all JSON cookies?

**Comment by panva** [comment]
What cookie values do you have issues with in particular? I would like to reproduce the issue you describe first.

**Comment by andrewrod33** [comment]
I am using a Rails App to do the user login flow and Rails does not parse the _grant cookie correctly (looks like because of the commas in JSON) and when I set a JSON cookie in Rails it is URI encoded so the provider does not read it correctly either.

Cookie setting code that I am referring to:
https://github.com/panva/node-oidc-provider/blob/master/lib/actions/authorization/interactions.js#L182
https://github.com/panva/node-oidc-provider/blob/master/lib/actions/authorization/interactions.js#L189

Cookie retrieving code:
https://github.com/panva/node-oidc-provider/blob/master/lib/provider.js#L30
https://github.com/panva/node-oidc-provider/blob/master/lib/shared/resume.js#L18

**Comment by panva** [comment]
Right, but can you provide an actual cookie value that you have a problem with? Or is it a general "all cookies" the interaction app needs to handle problem?

**Comment by andrewrod33** [comment]
I haven't gone through all flows yet but the _grant cookie is the one that I've had a problem with.

**Comment by panva** [comment]
An actual value, please.

**Comment by andrewrod33** [comment]
Cookie value: 
```
{"returnTo":"http://localhost:3080/auth/f8e9d28b-b0b2-4a7f-aabf-6cff779d21f8","interaction":{"error":"login_required","error_description":"End-User authentication is required","reason":"no_session","reason_description":"Please Sign-in to continue."},"uuid":"f8e9d28b-b0b2-4a7f-aabf-6cff779d21f8","params":{"client_id":"foo","nonce":"foo","redirect_uri":"https://example.com","response_mode":"query","response_type":"code","scope":"openid","state":"foo"}}
```

**Comment by panva** [comment]
seems like something rails has to be told to tackle differently, what do you think?

**Comment by andrewrod33** [comment]
Quicker/cleaner fix to be done in the OIDC Provider. If this can't be added to the project that is fine. I will just fork and implement the fix there.

**Comment by andrewrod33** [comment]
What about adding a configuration option encodeCookies that would be off by default in case there are others with this problem?

**Comment by panva** [comment]
on an unrelated note, don't forget to set up [cookies](https://github.com/pillarjs/cookies)-like cookie signing on your rails side, else you're susceptible to users manipulating cookies.

**Comment by andrewrod33** [comment]
Thanks!

**Comment by panva** [comment]
I don't get this,

`env["HTTP_COOKIE"]` has the right cookie header value
`CGI::Cookie.parse(env["HTTP_COOKIE"])["_grant"]` shows the right un-cutoff value

while unpretty (you may prettify at your leasure), you can access and parse cookies like so `JSON.parse CGI::unescape CGI::Cookie.parse(env["HTTP_COOKIE"])["_grant"].to_s.split('=')[1].split(';')[0]`

**Comment by panva** [comment]
I will introduce two config options for handling serialization and deserialization of the values. You will be able to put this rails workaround there.

**Comment by andrewrod33** [comment]
Great thanks!

**Comment by andrewrod33** [comment]
What you pasted there is basically exactly what I doing before I started encoding the cookies.

**Comment by panva** [comment]
To be frank i am still not sure what's right here. Browsers handle the cookies just fine, rack handles the cookie just fine, so this a rails quirk. Simply starting encode/decoding everything is not the answer as it breaks existing implementations and increases complexity. Please either stick to your fork or write a helper for rails to do so, you're gonna need one for keygrip cookie signatures anyway.

**Comment by andrewrod33** [comment]
Typically you wouldn't have to use the piece of Rails code you wrote. When encoded all that is needed is a call cookies("_grant") and that would give access to the _grant cookie. Parsing manually seemed a bit hacky to me and I was trying to avoid that. Thanks for the feedback and quick turnaround.
