### ISSUE TITLE
Best way to handle access token expirations

### ISSUE THREAD

**Issue by slavab89** [panva/node-oidc-provider#92]
I've noticed that even when an access token expires, i am still able to use it. (Using Mongo/Memory adapter)
Specifically i'm using the userinfo action.

I wanted your opinion on how to best handle access token expiration.
Should i handle this in my adapter find function? Meaning that if the token is expired then i destroy it (remove from storage/mark as consumed)?
Should i create some additional middleware before all else that verifies the token?
Some other option?

**Comment by panva** [comment]
An expired but still persisted token should not be usable for any action. If that's the case it's a bug. Can you provide more details?

**Comment by panva** [comment]
This access token will expire but stay in the database in 2 hours (2017-03-22 16:02:47 +0100, 1490194967), so let's see then.

```
curl -XPOST 'https://guarded-cliffs-8635.herokuapp.com/me' -d 'access_token=OTJjY2ZjYzAtZWI5Yy00MTcyLWEzNzEtMTAzZjkxZDAwMjM4uJHUPDXFaCme-0IunlbDOdIqqxg7lRxWiiX4lzporhc1nbKwoKcseU50PyIZ-zLuqIrAjHab4N98McKexDAnEg'
```

**Comment by slavab89** [comment]
Yeah, you are right, i'm sorry.
What i meant was that in the memory/mongo adapter the access token object has `expiresAt` property with some time, but i understand that its just for reference and the actual expiration time is in the payload.


When the token expires i get back an error saying that its invalid - at this point, should i try to request a new one using refresh_token endpoint right?

What about the next case: I have a valid access token, I have the provider running on server X and some data api running on server Y. I want to access data that is found in server Y using the token that server X (the provider) gave me.
I send a request to server Y with the access token and then server Y send a request to server X asking if the token is valid and can be used (is it correct?). In order to achieve that, should i use the userinfo endpoint to verify the access token or some other way?

**Comment by panva** [comment]
XYZ are too confusing ;)

You have the following parties Resource Server, Resource Owner, Authorization Server, Relying Party

Relying Party (RP) has the user (Resource Owner - RO) use the Authorization Server (AS) to gain authorization to access the Resource Server (RS). RP gets a Bearer token from AS, RP uses the Bearer to call the RS, *RS validates the Bearer with the AS*.

The bold part is what you want, you can either do that by calling userinfo or what's called an Introspection endpoint. Using an Introspection Endpoint is the preferred way if the RS only needs to get the Bearer validity and subject metadata.

Introspection is supported (check docs for how to enable and what the interface is like) by this provider. The added benefit of using introspection is that your RS gets a client_id and client_secret that does not allow it to start authorization requests but just call introspection with any received bearer tokens.

A client you configure for introspection only can look like this.
```
{
    client_id: 'client-introspection',
    client_secret: 'secret',
    redirect_uris: [],
    response_types: [],
    grant_types: [],
  }
```

Now towards dropping tokens from your persisted storage, you see the library does not care, it's up to you if you want to keep them for some reason or not.
