### ISSUE TITLE
Nest.js integration is broken after updating to node-oidc-provider@7.0.0 (request hangs indefinitely)

### ISSUE THREAD

**Issue by slavafomin** [panva/node-oidc-provider#936]
**Describe the bug**
An update to version `7.0.0` of the `node-oidc-provider` breaks the integration with Nest.js. Any requests to the `/oidc` route are getting hanged indefinitely.

**To Reproduce**
Clone the [sample repository](https://github.com/RiskChallenger/minimal-nest-oidc-provider) from the #788 issue and do `npm i && npm i node-oidc-provider@7.0.0 && npm run start`, then try to send any request to the `/oidc` endpoint.

**Expected behaviour**
The request should be processed as usual.

**Environment:**
 - oidc-provider version: `>=7`
 - node version: `v14.16.0`

**Additional context**

 - [X] the bug is happening on latest oidc-provider too.
 - [X] i have tried DEBUG (see README) and can see the issue is with the provider and not my code.
 - [X] i have searched the issues tracker on github for similar issues and couldn't find anything related.
 - [X] i have searched the [FAQ](https://github.com/panva/node-oidc-provider/blob/v7.x/docs/README.md#faq) and couldn't find anything related.

**Logs**
The log is empty.

**Comment by panva** [comment]
Please follow the changelog and look for breaking changes related to the callback getter.
