### ISSUE TITLE
Understanding `keystore` and `integrity` storage

### ISSUE THREAD

**Issue by mshwery** [panva/node-oidc-provider#94]
In your example app, you generate custom sign and integrity keystores and output them to `.json` files.

My presumption is that these files should **not** be tracked in version control, correct?

There's also the usage of `oidc.app.keys` and heroku's key rotation addon. It's not clear to me what the intention of these two pieces (`oidc.app.keys` and `keystore`, `integrity` keystores) are and how they work together.

FWIW I'm setting up an application using Elastic Beanstalk and will need to support horizontal scaling. My presumption is that I'll need to securely store the generated keys somewhere (outside version control) and in a place that can be accessed by each app server instance that gets spun up in the same load balancer.

**Comment by panva** [comment]
- app keys > http://koajs.com/#app-keys-
- keystore > should be absolutely clear, its the keys your provider exposes under discovery's jwks_uri
- integrity > https://github.com/panva/node-oidc-provider/blob/6f392ff/docs/configuration.md#certificates-and-token-integrity

all must obviously be kept secret

**Comment by mshwery** [comment]
Am I right in assuming that these keys need to be identical across horizontally scaled apps (i.e. when requests may hit one of several servers)?

**Comment by panva** [comment]
Indeed.

**Comment by mshwery** [comment]
Perfect, thanks for clarifying1

**Comment by panva** [comment]
FYI to be 100% in spec compliance when using `client_secret_jwt` or `private_key_jwt` as client's token_endpoint_auth_method you should also ensure the `uniqueness` helper mechanism is shared between multiple processes. It is used to validate the one time use of the jti claim for the auth jwts.

http://openid.net/specs/openid-connect-core-1_0.html#ClientAuthentication
> jti
> REQUIRED. JWT ID. A unique identifier for the token, which can be used to prevent reuse of the token. These tokens MUST only be used once, unless conditions for reuse were negotiated between the parties; any such negotiation is beyond the scope of this specification.
