### ISSUE TITLE
WARNING: a quick start development-only MemoryAdapter is used

### ISSUE THREAD

**Issue by suityou01** [panva/node-oidc-provider#941]
**Describe the bug**
The warning is printed to the console output when an alternative adapter is specified

**To Reproduce**
Use config such as 
```
{
 adapter: MyAdapter
}
```
```js
// provider configuration
```
{
    adapter: RedisAdapter,
    clients: [
        {
            client_id: '1702a39a-195d-4326-9975-a912a3c40ffd',
            client_secret: '5502380a-a40b-4bd5-85c8-708245dd8207',
            grant_types: ['refresh_token', 'authorization_code'],
            redirect_uris: ['http://sso-client.dev/providers/7/open_id', 'http://sso-client.dev/providers/8/open_id'],
       }
    ],
    interactions: {
      url(ctx, interaction) { // eslint-disable-line no-unused-vars
        return `/interaction/${interaction.uid}`;
      },
    },
    cookies: {
      keys: ['some secret key', 'and also the old rotated away some time ago', 'and one more'],
    },
    claims: {

    },
    features: {
      devInteractions: false , // defaults to true
      deviceFlow: { enabled: false }, // defaults to false
      revocation: { enabled: true }, // defaults to false
    },
    jwks
  };
```

**Expected behaviour**
The error is not printed to the console

**Environment:**
 - oidc-provider version: latest
 - node version: 14.4

 - [ ] the bug is happening on latest oidc-provider too.
 - [ ] i have tried DEBUG (see README) and can see the issue is with the provider and not my code.
 - [ ] i have searched the issues tracker on github for similar issues and couldn't find anything related.
 - [ ] i have searched the [FAQ](https://github.com/panva/node-oidc-provider/blob/v7.x/docs/README.md#faq) and couldn't find anything related.

**Comment by panva** [comment]
This is working as intended, the moment I configure an adapter property with anything but undefined the warning goes away.

**Comment by suityou01** [comment]
I can recreate the problem using the examples given in your documentation easily.

I have ascertained that the problem is because you have to call the initialize method of the Provider class and pass in the adapter this way.

This is not at all clear from any of the examples or the documentation.

**Comment by panva** [comment]
There is no `initialize` method on the Provider prototype since v6.x. You might be working with outdated docs or examples, in which case if those are linked from the repo's `main` branch, let me know.
