### ISSUE TITLE
Unique Keystore per subdomain

### ISSUE THREAD

**Issue by andrewrod33** [panva/node-oidc-provider#95]
Without running multiple Provider instances is it possible to have different certs at each different subdomain (multi tenant provider maybe)? If I have mysite.example.com/oidc/certs and yoursite.example.com/oidc/certswould it be possible to have each one have their own certs?

**Comment by panva** [comment]
No, you must run multiple provider instances. Not only certs are bound to an instance, also your issuer identifier, clients etc.

**Comment by panva** [comment]
That being said you can get creative having multiple instances mounted to one express/koa application and somehow play around with routing using koa-rewrite or express's version of it.

**Comment by andrewrod33** [comment]
Thanks for the quick turnaround! 1 more brainstorming idea before I try the multiple instances. I can actually retrieve the certs at the client level (these are all unique instances). Anyway to do the signing by client and not by OIDC Provider instances?

**Comment by panva** [comment]
Sorry, the clients can only specify an algorithm they want keys to be signed with, they cannot choose a specific key. Why do you need different keys anyway? The clients shouldn't care if there are others having the same signing keys.

**Comment by andrewrod33** [comment]
Still working this out. Basically we typically generate certs/key for each instance/account.

**Comment by andrewrod33** [comment]
Thanks again for the information!
