### ISSUE TITLE
Implicit grant for response_type ['code id_token ']

### ISSUE THREAD

**Issue by ruiengana** [panva/node-oidc-provider#957]
**Describe the bug**
Provider is adding Implicit grant type when response type is simply ['code id_token']

**To Reproduce**
```js
// provider configuration
{
...
responseTypes: ['code id_token'],
...
}

// keystore(s) - if they affect the behaviour
don't affect

// client(s) configuration
don't affect
```

Steps to reproduce the behaviour:
1.  Set provider configuration responseTypes to ['code id_token'] and run provider
2.  Check provider grant types on well-know endpoint

**Expected behaviour**
Expected Implicit grant type to not be in list.

**Environment:**
 - oidc-provider version:  v7
 - node version: v14

 - [X] the bug is happening on latest oidc-provider too.
 - [X] i have tried DEBUG (see README) and can see the issue is with the provider and not my code.
 - [X] i have searched the issues tracker on github for similar issues and couldn't find anything related.
 - [X] i have searched the [FAQ](https://github.com/panva/node-oidc-provider/blob/v7.x/docs/README.md#faq) and couldn't find anything related.

**Logs**

**Comment by panva** [comment]
This is expected and as per the specifications.

**Comment by tmonck** [comment]
I may be misreading this but according to the spec [RFC](https://tools.ietf.org/html/rfc6749#section-4.2.1) it says that the `response_type` Value MUST be set to "token", which means that the implicit client shouldn't be allowed to register without one of the items in the `response_types` array being `token`. It seems like the table from the link you send is out of date. There is an updated [RFC for dynamic client registration](https://tools.ietf.org/html/rfc7591#section-2.1) which says the implicit client response_types value includes `token`.

**Comment by panva** [comment]
@tmonck RFC7591 only deals with two response type values `code`, and `token`. The latter of which is not supported by this implementation at all.

>    Extensions and profiles of this document that introduce new values to
>   either the "grant_types" or "response_types" parameter MUST document
>   all correspondences between these two parameter types.

This is exactly what https://openid.net/specs/openid-connect-registration-1_0.html#ClientMetadata does.

**Comment by panva** [comment]
I do not understand the contention here, the `response_types_supported` values are what matters after all.
