### ISSUE TITLE
Too much rare implementing the provider on Express.js and receiving Koa context

### ISSUE THREAD

**Issue by mraffo** [panva/node-oidc-provider#961]
I mean,

Listening, by example, and event like 

**providerInstance.on('registration_create.error', (ctx, error) => {});**

We recieve the Koa context. Any way to delete the Koa dependencies? there is no clear architecture / implementation when we have two web frameworks in same project.

Or, is a recommendation integrates it with Koa?

Thanks!

**Comment by panva** [comment]
Please don't open issues for what is clearly a question. The ctx will always be the koa ctx. If you want the node.js req or res, get from the koa ctx via ctx.req, or ctx.res respectively.
