### ISSUE TITLE
Client credentials grant type client without redirect uri

### ISSUE THREAD

**Issue by jakubzloczewski** [panva/node-oidc-provider#97]
Is it possible to use client 'credential_grant' type without 'redirect_uris' and additional grant types like 'implicit' or 'authozation_code'? 

I'm trying to get access token for service A and use this access token to make reqeusts to protected service B. I'm using this as reference: https://connect2id.com/blog/client-credentials-grant-support

I would like to have client like:

```
{
   client_id: 'service_a',
   client_secret: 'secret_for_service_a',
   grant_types: ['client_credentials'],
   token_endpoint_auth_method: 'client_secret_post'
}
```

but when I'm trying to get token: 
```
curl -X POST \
-d 'grant_type=client_credentials&client_id=service_a&client_secret=secret_for_service_a' \
"http://localhost:2000/op/token"
```
I got:
```
{"error":"invalid_redirect_uri","error_description":"redirect_uris is mandatory property"}
``` 

When I add 'authorization_code' to grant_types and any redirect_uris then it works as I expect but I would not like to use 'authorization_code' and I don't need redirect_uri in case of client credential flow.
Or maybe I have wrong understanding of 'client credential' flow?

Thanks for any help!

**Comment by panva** [comment]
Hello @jakubzloczewski, this is a great point! something that's hopefully easy to adapt to allow (similar to introspection only clients).

FYI, you're getting this error because the client validation runs the first time it's loaded from your adapter, if you were to give it to the `#initialize()` it would fail right away.

**Comment by panva** [comment]
redirect_uris is still a mandatory property, to conform with http://openid.net/specs/openid-connect-registration-1_0.html, but you can pass it empty and have a valid client_credentials client.

Release pending (will be v1.15.3).

```js
{
  client_id: 'foo',
  client_secret: 'bar',
  redirect_uris: [],
  response_types: [],
  grant_types: ['client_credentials']
}
```

**Comment by codestorycooked** [comment]
How do I register the client with only 'client_credentials' grant?

**Comment by panva** [comment]
Exactly as in the comment above, assuming you have client credentials grant enabled on your provider? There's even a [test](https://github.com/panva/node-oidc-provider/blob/v2.17.0/test/configuration/client_metadata.test.js#L776-L788) with exactly this.

**Comment by codestorycooked** [comment]
Thanks. It worked. Have a gooday.

**Comment by NoumanDilshad** [comment]
I am still getting an error when using client_credentials.
I am using this clients = 
```
[{
    client_id: 'foo',
    client_secret: 'bar',
    redirect_uris: [],
    response_types: [],
    grant_types: ['client_credentials']
  }]
```
Error: UnhandledPromiseRejectionWarning: InvalidClientMetadata: invalid_client_metadata

**Comment by panva** [comment]
@NoumanDilshad handle it and read the error description

**Comment by NoumanDilshad** [comment]
Please help me out.
This is the complete error:

> (node:5472) UnhandledPromiseRejectionWarning: InvalidClientMetadata: invalid_client_metadata
>     at invalidate (C:\Users\Nouman\Desktop\openid-quickpay\node_modules\oidc-provider\lib\helpers\client_schema.js:31:9)
>     at Object.entries.forEach (C:\Users\Nouman\Desktop\openid-quickpay\node_modules\oidc-provider\lib\helpers\client_schema.js:412:13)
>     at Array.forEach (<anonymous>)
>     at Schema.enums (C:\Users\Nouman\Desktop\openid-quickpay\node_modules\oidc-provider\lib\helpers\client_schema.js:401:28)
>     at new Schema (C:\Users\Nouman\Desktop\openid-quickpay\node_modules\oidc-provider\lib\helpers\client_schema.js:209:12)
>     at schemaValidate (C:\Users\Nouman\Desktop\openid-quickpay\node_modules\oidc-provider\lib\models\client.js:187:20)
>     at Object.add [as clientAdd] (C:\Users\Nouman\Desktop\openid-quickpay\node_modules\oidc-provider\lib\models\client.js:299:12)
>     at Provider.addClient (C:\Users\Nouman\Desktop\openid-quickpay\node_modules\oidc-provider\lib\helpers\initialize_clients.js:4:25)
>     at Array.map (<anonymous>)
>     at Provider.initializeClients (C:\Users\Nouman\Desktop\openid-quickpay\node_modules\oidc-provider\lib\helpers\initialize_clients.js:11:30)
>     at initializeKeystore.call.then.then.then (C:\Users\Nouman\Desktop\openid-quickpay\node_modules\oidc-provider\lib\provider.js:150:37)
>     at <anonymous>
>     at process._tickCallback (internal/process/next_tick.js:188:7)
>     at Function.Module.runMain (module.js:695:11)
>     at startup (bootstrap_node.js:188:16)
>     at bootstrap_node.js:609:3
> (node:5472) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 2)
> (node:5472) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

**Comment by panva** [comment]
> This is the complete error

No it's not. Handle the promise rejection and print the actual error, not a `UnhandledPromiseRejectionWarning`.

**Comment by NoumanDilshad** [comment]
It says: 
```
name: 'InvalidClientMetadata',
  error: 'invalid_client_metadata',
  status: 400,
  statusCode: 400,
  expose: true,
  error_description: 'grant_types can only contain members [implicit,authorization_code,refresh_token]' }
```

**Comment by NoumanDilshad** [comment]
I need to handle 

> client_credentials 
how can I handle that in odic-provider

**Comment by panva** [comment]
You don’t have client credentials enabled at all. Please follow the configuration doc and enable the feature first.
