### ISSUE TITLE
Session Management

### ISSUE THREAD

**Issue by andrewrod33** [panva/node-oidc-provider#98]
I am not currently planning on using the Session Management feature. Is there any reason that I would still need the _session cookie? I was planning on having the session being kept outside of the provider.

**Comment by panva** [comment]
The provider will always have its own session. _session has nothing to do with session management features.

**Comment by panva** [comment]
The provider will always have its own session. _session has nothing to do with session management features.

**Comment by andrewrod33** [comment]
I want the user to hit the service that is managing their session every time an auth request is received. In your opinion what is the best way to make that happen? Setting a short cookie time?

**Comment by panva** [comment]
In my opinion you need to first explore how the library works and figure out if it's the right one for your case.

But I would place my bets on overloading the interactionCheck option to always tell the instance an interaction is needed and then doing interactionFinished to pass the results. This however does not get rid of the session cookie, the provider will always be maintaining that one.

**Comment by andrewrod33** [comment]
As always, thank you for the information and quick responses!

**Comment by maitscha** [comment]
@andrewrod33 Have you solved your issue? I have the same/similar requirement. I would like to use a session cookie on top of the OpenID Connect Provider. If the session cookie is valid I don't want the user to authenticate, but instead show only the consent confirmation form.

Any ideas?
