### ISSUE TITLE
External Auth Providers

### ISSUE THREAD

**Issue by coreyperkins** [panva/node-oidc-provider#99]
Is it possible to add external auth providers? Something along the lines of what idsrv4 is doing in their asp.net core lib? (http://docs.identityserver.io/en/release/quickstarts/4_external_authentication.html)

**Comment by panva** [comment]
This is not a library you simply install, configure and you'd be good to go. As seen in the readme and configuration section the user interactions are only part of the example, you must build your own interactions (authentication views), part of which can be any mechanism you want - social, username/password - you name it.

**Comment by coreyperkins** [comment]
Understood. Thank you!

**Comment by panva** [comment]
yvw
